### ISSUE TITLE
How do I compile with C++?

### ISSUE THREAD

**Issue by roshanDD** [ARMmbed/mbedtls#1005]
I am currently building a http2 client (using nghttp2) and sitting on top of the mbedtls. I am coding in C++, this might be a pretty stupid question. How do I compile my C++ code using g++ command?

It looks to me that when I naively run `g++ -Wall -o http_client.cpp .`, it gives the error that 
`#include "mbedtls/platform.h" not found`. Am I missing a command which links to a library or something? 

I am compiling the code on my mac. Thanks

**Comment by roshanDD** [comment]
My ultimately development enrioment will be on Rapsberrian Jessie. I am compiling on my mac because it's too slow on the Raspberrian Jessie. Thanks

**Comment by RonEld** [comment]
Hi @roshanDD You should have the include path in your compilation command as the `-I` compilation flag

**Comment by RonEld** [comment]
I believe this question was answered, therefore closing it.
If you are not happy with the answer, pleaser reopen this issue
