### ISSUE TITLE
Investigate integer conversion warnings

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1007]
__Issue:__ When compiling mbed TLS with GCC and compilation flag `-Wconversion` set, numerous warnings about implicit integer conversions are emitted.

__Task:__ In case we don't want to generally dismiss those warnings, they should be systematically investigated. For each of them, we should either make the conversion explicit (and argue that it's safe) or change the types accordingly. 

__Relates to:__ https://github.com/ARMmbed/mbedtls/pull/999

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1534

**Comment by sbutcher-arm** [comment]
Warnings are bugs for us, not enhancements, so relabelling.

'Enhancement' is meant to mean 'feature request'.
