### ISSUE TITLE
signing a certificate using MBEDTLS_PK_RSA_ALT is broken

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1011]
signing a certificate using `MBEDTLS_PK_RSA_ALT` fails because of the following:
when calling `mbedtls_x509write_crt_der`, the function within,` mbedtls_oid_get_oid_by_sig_alg` fails because `MBEDTLS_PK_RSA_ALT` is not found.
Raised by J.B. in the [support forum](https://tls.mbed.org/discussions/generic/using-an-external-rsa-private-key)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1538

**Comment by gilles-peskine-arm** [comment]
Fixed by #1089 which has been merged to development, and backports #1108 #1109
