### ISSUE TITLE
mbed TLS 1.3: test_suite_memory_buffer_alloc tests not backported

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#1014]
There are about 6 tests that were introduced in the `test_suite_memory_buffer_alloc` test suite that were never backported to mbed TLS 2.1 and 1.3. I have already backported the changes to mbed TLS 2.1 as part of PR https://github.com/ARMmbed/mbedtls/pull/1009. I think we should do the same for mbed TLS 1.3.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1541

**Comment by sbutcher-arm** [comment]
mbed TLS 1.3 is a maintenance branch that's very near it's end of life. I don't see the value in, at this point in its lifecycle, backporting additional test cases. New users and existing users of 1.3 should all be using the most recent release or the 2.1 branch or planning to do so.

As such I'm closing the ticket, but if anyone feels strongly that this is the wrong choice, please say so and I'd welcome other points of view.
