### ISSUE TITLE
MBEDTLS_NO_PLATFORM_ENTROPY causes segfault in RSA test suite

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1023]
Defining in `config.h` the option `MBEDTLS_NO_PLATFORM_ENTROPY` causes the RSA test suite to segfault on execution.

Maybe the test isn't valid with the option and is missing a dependency.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1580
