### ISSUE TITLE
Most of functions in Bignum.c variable ret not initilized with 0 ?

### ISSUE THREAD

**Issue by RaspiRepo** [ARMmbed/mbedtls#1039]
### Description
- Type: Bug | Enhancement\Feature Request | Question
- Priority: Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
mbed-OS : Threax RTOS 
ARM Cortex-M4 Microcontroller 

**mbed TLS build:**  
Version: 2.5.1 or git commit id  
OS version: ThreadX RTOS 

Additional environment information:  
a. Cross ARM C Compiler for ARM cortex M4
b. IDE : Eclipse on  windows 10 

----------------------------------------------------------------
## Enhancement\Feature Request

**Suggested enhancement**  

Most of the functions in File bingnum.c ret variable NOT set to 0 as default. 
a. Is always assumed that compiler will set default with 0?
b. Several functions return error code macro if there is failure in middle of the function, but end of the function used "return ret;"

What would be return unitized variable ?
-----------------------------------------------------------------

## Question
What would be return value of variables unitized in a function ?

**Comment by RonEld** [comment]
Hi @RaspiRepo Thank you for your information!
It is not assumed that ret is initialized with zero, however, if `ret` was not set before usage, the static analyzer would have raised a warning on this, and so would most of the compilers.
Note that most of the bignum functions use the macro `MBEDTLS_MPI_CHK`:
~~~
#define MBEDTLS_MPI_CHK(f) do { if( ( ret = f ) != 0 ) goto cleanup; } while( 0 )
~~~
So this macro sets a value to `ret`.
I agree with you that it's good practice to always initialize variables however I don't consider this as a bug, hence marking this as an enhancement and a question,

**Comment by RaspiRepo** [comment]
Hi RonEld,

Thanks for update, I could see macro and understand code now.
Also I fixed all int ret = 0; anyway.  Reason I suspected this due to below issue.

I am having issue with following function, issue looks strange.
/*
 * Check a private RSA key
 */
int mbedtls_rsa_check_privkey( const mbedtls_rsa_context *ctx )

This function return error code MBEDTLS_ERR_RSA_KEY_CHECK_FAILED for "Check for a valid PKCS1v2 private key" if condition. 

RSA Key (Private Key from AWS IoT) verification is failed with error code.

Same code and same certificate works well in Windows OS (mbed-TLS for AWS IOT). 
But ARM cortexM4 (Microcontroller)i.e cross ARM build not working.  IF certificate is an issue then windows also should return same error code.
Is any idea how to debug this issue on embedded platform (ThreadX RTOS)?

NOTE: CA Root, AWS IOT X509 certification load and verification is success. only problem with PrivateKey validation failed. 

Thanks
Mariya

**Comment by RaspiRepo** [comment]
My Development board : Renesas SKS7G2 which runs ThreadX RTOS

**Comment by RonEld** [comment]
Hi @RaspiRepo Please raise this as a new issue, as it is different than the subject of this issue.

**Comment by RaspiRepo** [comment]
thanks I will do now
