### ISSUE TITLE
some tests dependant on MBEDTLS_ECDSA_C not marked as dependant

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1040]
### Description
- Type: Bug
- Priority:  Minor

---------------------------------------------------------------
## Bug

**OS**  
Linux

**mbed TLS build:**  
Version: 2.5.1
OS version: Ubuntu 16.04  
Configuration:MBEDTLS_ECDSA_C undefined 

**Expected behavior**   
tests passing
**Actual behavior**  
some tests fail because they are dependant on `MBEDTLS_ECDSA_C` ut not marked as such, and are not skipped while running tests
**Steps to reproduce**  
1. uncomment `MBEDTLS_ECDSA_C`
2. build mbed TLS library and tests
3. run `test_suite_x509parse`

raised by Fredrik Axelsson in the [support forum](https://tls.mbed.org/discussions/bug-report-issues/tests-dependend-on-mbedtls_ecdsa_c)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1599

**Comment by mpg** [comment]
Note: I believe we have a branch that, among many other things, fixes this issue: https://github.com/ARMmbed/mbedtls-restricted/pull/382 (currently internal, sorry).
