### ISSUE TITLE
PKCS1v2 private key validation failed with  MBEDTLS_ERR_RSA_KEY_CHECK_FAILED 

### ISSUE THREAD

**Issue by RaspiRepo** [ARMmbed/mbedtls#1041]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug |  Question
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  

Threadx RTOS

**mbed TLS build:**  
Version: 2.5.1  
platform specific malloc/free, bsd style network.

Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  
Hardware : ARM Cortex M4
IDE : E2Studio, SSP 1.2.1 (Synergy Software Platform), Threadx RTOS
Board : Renesas SKS7G2
Tool chain :  GNU Tools for ARM Embedded Processors (arm-none-eabi-gcc)
Compiler: gcc

**Actual behavior**  
Function 

/*Check a private RSA key */
int mbedtls_rsa_check_privkey( const mbedtls_rsa_context *ctx )

return error code MBEDTLS_ERR_RSA_KEY_CHECK_FAILED for "Check for a valid PKCS1v2 private key" one of the IF condition.

This RSA Key (Private Key generated AWS IoT) verification is failed with error code for this platform (ARM-Cortex M4). 

But same code and same certificate works well in Windows OS (mbed-TLS for AWS IOT). I can send IoT MQTT data to AWS IoT. So all certificates are OK. 

NOTE: CA Root, AWS IOT X509 certification load and verification is success. only problem with PrivateKey validation failed.
Thanks
Mariya

**Comment by RonEld** [comment]
Hi @RaspiRepo Thank you for your information.
I am having some trouble understanding your flow.
What is your usage with the private key? Where did you get it? 
Not that certificate verification is done with the public key, and the signing is done with the private key on the server side ( unless the client signs its own certificate and sends the server for verification)
Please check what part of the private key is failing, and check that you have enough stack size.

**Comment by RaspiRepo** [comment]
Hello RonEld,
Sorry for long delay to respond to your question.

Found problem outside of mbedTLS and this above crashing also resolved.

Now I can connect My Renesas IoT board (ThreadX RTOS) to AWS IoT server without any issue.

Successfully ported mbedTLS  code to ThreadX RTOS.

Thanks 
Mariya
