### ISSUE TITLE
Certificates with validity years over 2100 will not be dated correctly

### ISSUE THREAD

**Issue by veselov** [ARMmbed/mbedtls#1042]
Looking at master/ab0a8042f44b2ceb5b515da538334eed488c6518

Bug: The x509_write_time function in x509write_crt.c has a logic that uses ASN1_UTC_TIME for years below 2050, but it will also used that (shorter) form, if the year is > 2099, just because of the logic it employs.

2100 may be far away, but having y2k like problems without necessity (sure, GENERALIZED_TIME can't encode years more than 4 digits long) may prevent certain application where certificate validity times are purposefully long.

**Comment by hanno-arm** [comment]
Hi @veselov,

thanks for your report! Could you provide some more details? Looking at `x509_write_time`, it seems that the path using `ASN1_UTC_TIME` is taken exactly if the first to numbers in the time string are `2` and `0`, and the third is below `5`. All other years, including those beyond `2099`, will accordingly take the other path using `ASN1_GENERALIZED_TIME`.

Regards,
Hanno

**Comment by veselov** [comment]
I should print, in large font, a "don't try to play a computer" and stick it on a wall in front of me. Thank you for checking and explaining this.
