### ISSUE TITLE
set `LC_ALL=C` in all the scripts, to prevent locale issues

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1057]
### Description
- Type:  Enhancement
- Priority: Minor

## Enhancement

**Justification - why does the library need this feature?**  
As fixed and suggested in #1056 , it is better to set `LC_ALL=C` in all the scripts, for preventive issues, to avoid locale problems.
More information on `LC_ALL` can be found [here](https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1665

**Comment by gilles-peskine-arm** [comment]
Looking quickly through the scripts, I see:

* Dependency on collation order in `generate-code.pl`, affecting the output which needs to match exactly so it's a bad one. Solved by #1056.
* Dependency on collation order in `check-names.sh` and the `list-*.sh` scripts. This affects the output of `list-*`, but for `check-names.sh` itself, it's only internal, so not important. Besides we're planning to replace `check-names.sh`, so no action needed.
* Use of `a-z` to mean “all lowercase letters” (or likewise `A-Z`) in several scripts: `compat.sh`, `check-names.sh` and `lits-*.sh`. In `check-names.sh` this affects the behavior but is low-priority. For `compat.sh`, there's another usage problem of `tr` that needs to be fixed.
