### ISSUE TITLE
Bad CMAC output with Tlen of 32 bits?

### ISSUE THREAD

**Issue by jussihi** [ARMmbed/mbedtls#1068]
### Description
- Type: Bug / Question
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.5.1 
Configuration: [config.zip](https://github.com/ARMmbed/mbedtls/files/1261023/config.zip)

So I have this code:
```
uint8_t cmackey[16] = {0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c};

uint8_t outputCMAC[16];

uint8_t expectedCMAC1[16] = {0xbb, 0x1d, 0x69, 0x29, 0xe9, 0x59, 0x37, 0x28, 0x7f, 0xa3, 0x7d, 0x12, 0x9b, 0x75, 0x67, 0x46};

uint8_t *msg1 = NULL;

/*
 * With these generate params I get a nice CMAC output
 * bb1d6929e95937287fa37d129b756746
 */
generateCMAC(cmackey, msg1, 0, outputCMAC, 128);

/*
 * However, if I want to generate a 32-bit CMAC, it will give me zeros (the buffer also will have some random 0x77 and 0x7c
 * 0000000000000000770000007c000000
 */
generateCMAC(cmackey, msg1, 0, outputCMAC, 32);

int generateCMAC(uint8_t* w_key, uint8_t* w_data, uint32_t w_len, uint8_t* o_cmac, uint8_t w_keyLen)
{
mbedtls_cipher_context_t m_ctx;
const mbedtls_cipher_info_t *cipher_info;
if((cipher_info = mbedtls_cipher_info_from_type(MBEDTLS_CIPHER_AES_128_ECB)) == NULL)
{
	return -1;
}
mbedtls_cipher_init(&m_ctx);
mbedtls_cipher_setup(&m_ctx, cipher_info);
if((ret = mbedtls_cipher_cmac_starts(&m_ctx, w_key, w_keyLen)) != 0)
{
	return -1;
}
mbedtls_cipher_cmac_update(&m_ctx, w_data, w_len);
mbedtls_cipher_cmac_finish(&m_ctx, o_cmac);
mbedtls_cipher_free(&m_ctx);
}
```

**Expected behavior**   
With this piece of code I would expect a nice and good CMAC authentication key in my o_cmac buffer.

**Actual behavior**  
 I get a nice auth key when my w_len is 128 bits, but as I'm making a LTE security implementation, I would need a 32 bit CMAC code (32 as TLen). If I input 32 as w_len, I only get 4 bytes filled with 0s.

## Question

Is this actually meant to work like this?

**Comment by RonEld** [comment]
Hi @jussihi Thanks for your report!
I have tried to reproduce this issue with your configuration file and example, but I didn't get 4 bytes filled with 0's.
Note that `mbedtls_cipher_cmac_update` receives the iLen in bytes, not bits, so if you put 32 as input length, you might not get what you wished for. What you are describing is not the desired behavior, but you should check your parameter types and values. In addition, CMAC is a MAC functionality, which means that the output should be a constant size buffer; In this use case, it is Block size ( 16 bytes ), so I am not sure how you get only 4 bytes of zeros.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1683

**Comment by jussihi** [comment]
Thank you @RonEld  for very fast response. And sorry, I mixed the params in my initial post. I actually mean that I use 32 as the w_keyLen. Should the key length also be set as bytes and not bits? I will edit my code and the initial so it corresponds my actual implementation and I can give some reference data as well.

**Comment by RonEld** [comment]
Hi @jussihi 
`w_keyLen` should be in bitlen, however you are using AES 128, which means that the AES key size you are working on should be 128. This means, that your call to `mbedtls_cipher_cmac_starts` should have returned `MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA` , so you finish with an error. 32 is not a valid key size (in bits), and it is also not secure, as 32 bit key size is highly computable

**Comment by jussihi** [comment]
Thanks for the respond again @RonEld 

So basically, if I'm told to use 32 as TLen, should I also feed the algorithm with a 32-bit key? The LTE Security specification is really confusing. I know the LTE security uses generally 128 bit keys, so I guess the idea is to generate a 128-bit key and just use the first 32 bits of the CMAC output?

This is how the specification says:
"AES in CMAC mode is used with these inputs to produce a Message Authentication Code T (MACT) of length Tlen = 32. T is used directly as the 128-EIA2 output MACT[0] .. MACT[31], with MACT[0] being the most significant bit of T. "

The full specification can be found here;
http://www.etsi.org/deliver/etsi_ts/133400_133499/133401/13.05.00_60/ts_133401v130500p.pdf
and the section is B.2.3

So my actual question now is; can I generate a CMAC hash of 32 bits, with a 128-bit key?

**Comment by jussihi** [comment]
After some further investigation, could it be that this implementation of CMAC in mbedtls library does not allow user to input the TLen of the CMAC hash? Or is the TLen hash of 32 bits the same as 32 first bits of a 128-bit hash?

**Comment by RonEld** [comment]
HI @jussihi `AES CMAC` output length is by standard definition, the AES block size (128 bit ).
As we are not LTE experts, I can't comment on the LTE standard. The size of **`MACT`** according to your reference, is 32 bit, but it is generated using 128-EIA2 which is based on CMAC. It is not clear to me from the standard you referenced how the generated MACT is done. According to [this figure](https://www.researchgate.net/figure/279263961_fig11_Figure-211-EIA2-Algorithm), I believe that MACT is the 5 MSB of the MAC. Note that the key remains 128bit size,

**Comment by jussihi** [comment]
Thank you very much for your dedication to my little issue @RonEld . I appreciate it a lot. Did you mean 4 MSB though? As a complete newcomer to cryptography, I don't understand the picture you linked, but I believe you here, and I also think that it's the only reasonable solution/option. I will go with that. Once again, thank you for your time. You can close this issue after you confirm the 4 MSB.

**Comment by RonEld** [comment]
Hi @jussihi Yes, sorry, it was a typo. I meant 4 MSB.
Please try the test vectors in your LTE reference standard to confirm.
The picture is basically explanation of AES-CMAC. And at the end, you see MSB of the output is the MAC

**Comment by jussihi** [comment]
Thank you. The test vectors were only for 128-bit TLen output, that's why I was confused. Maybe, and hopefully this question can help someone else too in the future!

**Comment by RonEld** [comment]
Hi @jussihi , Just for the record, the test vectors in the reference show 32 bit MACT:
for example
MACT = (hex) 118c6eb8

**Comment by jussihi** [comment]
@RonEld thanks again, I will check them this time with my both eyes open!

**Comment by jussihi** [comment]
@RonEld sorry for still commenting to already closed issue, but is it not possible to give the iLen in bitlen to the CMAC hash generation functions? Now all the test vectors that have byte aligned bitlen work, but if the iLen is not byte aligned (say the bitlen of the message is 511 bits) the CMAC output is wrong.

**Comment by RonEld** [comment]
Hi @jussihi , If you think there is a need to change the implementation to accept the iLen as bit size, and not byte size, please open a new issue, as an enhancement request. Your request is to change the CMAC function, to support your algorithm, which is not reasonable, IMHO, It is strange that the input is in bitlen in your standard, as it is not according to the CMAC standard. Please check what is the padding type that is used in your algorithm.
One correction to your comment, CMAC is not a hash generation function. It is a MAC function.

**Comment by jussihi** [comment]
Hello @RonEld ,
thank you for your correction. For the other integrity function (Snow3G), the padding bits are zeroed if the data is not byte aligned. I think I won't open a new issue for that need. I will look further a bit. 
Here on line 659 [some python implementation](https://github.com/mitshell/CryptoMobile/blob/master/CM.py) the input is given as bitlen. I don't know if this actually changes anything, as I'm already zeroing all the padding bits, at least in the input data.

**Comment by jussihi** [comment]
Commenting again, I just read the security specification, and it says 

> NOTE: This section provides both byte aligned and non byte aligned test data sets. For EPS implementation verification, byte alignment test data sets (2, 5 and 8) can be used, as EPS RRC and EPS NAS messages are byte aligned. The non byte aligned test data sets may be used to verify implementations that support non byte aligned messages. 

This can be closed again. Thank you for your help @RonEld  !

**Comment by RonEld** [comment]
Hi @jussihi 
As you see in the [link you gave me](https://github.com/mitshell/CryptoMobile/blob/master/CM.py#L667):
~~~
      if lastbits:
                M = ''.join((M[:-1], \
                    chr(ord(M[-1:]) & (0x100 - (1<<lastbits))) ))
~~~
This means you can pad the end of your message as mentioned in the script

**Comment by jussihi** [comment]
Yes, I just got scared as my test results didn't match the specification's expected results!
