### ISSUE TITLE
inplace cipher for AES-CTR returns `MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA` on buffer that is not a multiple of AES block

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1076]
### Description
- Type: Bug
- Priority:  Major 

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: development branch
OS version: Ubutu 16.04| WIndows 10

Version:  2.6.0

**Expected behavior**   
AES CTR supports buffer length that isn't a multiple of AES block (16 bytes), and should succeed using the cipher wrapper APIs
**Actual behavior**  
`mbedtls_cipher_update` returns `MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA` because of:
~~~
    if( input == output &&
       ( ctx->unprocessed_len != 0 || ilen % block_size ) )
    {
        return( MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA );
    }
~~~
**Steps to reproduce**  
use the cipher wrapper API on a buffer of 1 byte, with AES-CTR as the mode

raised by Antonio in the [support forum](https://tls.mbed.org/discussions/crypto-and-ssl/bogus-aes-ctr-input-validation-in-mbedtls_cipher_update)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1705
