### ISSUE TITLE
Dead code in mbedtls_cipher_update

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1086]
__Issue:__ There's a duplicated check for `block_size == 0` in `mbedtls_cipher_update` at https://github.com/ARMmbed/mbedtls/blob/development/library/cipher.c#L309 and https://github.com/ARMmbed/mbedtls/blob/development/library/cipher.c#L370.

Study which code-path to keep and remove the other.

__Internal Reference:__ IOTSSL-979

**Comment by gelldur** [comment]
No longer valid ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2536

**Comment by Patater** [comment]
Looks like this is still valid. 

We probably don't need this bit.
https://github.com/ARMmbed/mbedtls/blob/ab8d58cb2d0653c84ca44a8d9e3486ed8b9de930/library/cipher.c#L438
