### ISSUE TITLE
ECB MODE doesn't need IV

### ISSUE THREAD

**Issue by ezdevelop** [ARMmbed/mbedtls#1091]
## Bug
Here are the comments in the header file https://github.com/ARMmbed/mbedtls/blob/72ea31b026e1fc61b01662474aa5125817b968bc/include/mbedtls/cipher.h#L624-L638

But the all-in-one function '**mbedtls_cipher_crypt**' still check for IV data.
https://github.com/ARMmbed/mbedtls/blob/72ea31b026e1fc61b01662474aa5125817b968bc/library/cipher.c#L812-L835

https://github.com/ARMmbed/mbedtls/blob/72ea31b026e1fc61b01662474aa5125817b968bc/library/cipher.c#L214-L221

**Comment by RonEld** [comment]
Hi @ezdevelop 
Thank you for reporting this issue!
I believe you are correct in your analysis

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1753
