### ISSUE TITLE
hmac_drbg_free() called too often and too early inside benchmark.c

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1095]
### Description
- Type: Bug
- Priority: Minor

There's a bug in the mbedTLS benchmark program. When HMAC_DRBG_C is tested, two configurations, namely with SHA1 and with SHA256 are tested. However for both configurations mbedtls_hmac_drbg_free() is called, which means that the context is freed too early although it is being used later. mbedtls_hmac_drbg_free() should only be called at the end of the 
`#if defined(MBEDTLS_HMAC_DRBG_C)` - code.

---------------------------------------------------------------
## Bug
**mbed TLS build:**  
Version: 2.6.0

**Comment by RonEld** [comment]
Hi @TrinityTonic Thank you for reporting this
Although I agree that this is confusing that `mbedtls_hmac_drbg_free()` is called after every operation, it is not a major bug, as the ` mbedtls_hmac_drbg_free()` only clears the context from its internal data.
I agree it might cause a problem when `MBEDTLS_THREADING_C` is defined, or when there will be an alternative implementation support for HMAC DRBG in the future.

**Comment by TrinityTonic** [comment]
@RonEld  Yea, I was noticing the problem with MBEDTLS_THREADING_C as my (alternative) Mutex is freed when hmac_drbg_free() is called and later on the the code tried to lock the mutex it had freed before.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1761
