### ISSUE TITLE
Compiler warning, variable 'ret' is used before its value is set in mbedtls_pk_parse_key

### ISSUE THREAD

**Issue by MartinBP** [ARMmbed/mbedtls#1098]
The variable 'ret' in mbedtls_pk_parse_key is casted to void in line 1184 before it has been assigned a value when just MBEDTLS_ECP_C of the preprocessor symbols in that function is defined.

ret is always assigned a value in line 1211, so it looks like only pwd and pwdlen needs to be casted to void to avoid warnings about variables not referenced.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1772

**Comment by gelldur** [comment]
Not important but done ;)

**Comment by sbutcher-arm** [comment]
PR #1854 has now been merged which should fix this issue. Therefore it can be closed.
