### ISSUE TITLE
Crash when calling mbedtls_ssl_cache_free twice

### ISSUE THREAD

**Issue by MilenkoMitrovic** [ARMmbed/mbedtls#1104]
When using the cache i have a crash when calling mbedtls_ssl_cache_free more than one time. This happens because **cache->chain** is deleted on the first call and not set to NULL so the second call will try to free it up again.

This can be fixed by adding a simple memset at the end of mbedtls_ssl_cache_free
`memset( cache, 0, sizeof( mbedtls_ssl_cache_context ) );`

- Type: Bug
- Priority: Minor

**Comment by RonEld** [comment]
HI @MilenkoMitrovic Thank you for reporting this.
As you menioned, this is a minor bug, as there is a quick workaround. 
Is there a specific scenario where you call `mbedtls_ssl_cache_free` more than once? Usually it's n ot good practice to do that

**Comment by MilenkoMitrovic** [comment]
I have Initialize/Release functions within my code and Release might be called twice just to make sure that some code/class is really released. Of course, i can add a check if this release code has been called before but... i don't think we need to discuss about that :)

**Comment by MilenkoMitrovic** [comment]
I mean, i would have done that but since i have seen that the other context_free calls like `mbedtls_net_free` are reseting the internal state i expected it to be a bug.

**Comment by RonEld** [comment]
I agree with you it's a bug

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1786
