### ISSUE TITLE
function mbedtls_ssl_conf_ciphersuites does not work?

### ISSUE THREAD

**Issue by GreenHero** [ARMmbed/mbedtls#1106]
i want to set the list of allowed ciphersuites and the preference order. So I uncomment macro MBEDTLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE 

```
static const int ciphersuites[2] = {MBEDTLS_TLS_PSK_WITH_AES_128_CBC_SHA, MBEDTLS_TLS_PSK_WITH_AES_256_CBC_SHA};

```

```
    int ret = 0;
    mbedtls_net_init(&(pParams->socket_fd));
    mbedtls_ssl_init(&(pParams->ssl));
    mbedtls_ssl_config_init(&(pParams->ssl_conf));
    mbedtls_ctr_drbg_init(&(pParams->ctr_drbg));
    mbedtls_x509_crt_init(&(pParams->ca_cert));
    mbedtls_x509_crt_init(&(pParams->client_cert));
    mbedtls_pk_init(&(pParams->private_key));

    mbedtls_entropy_init(&(pParams->entropy));
    if ((ret = mbedtls_ctr_drbg_seed(&(pParams->ctr_drbg), mbedtls_entropy_func,
                                     &(pParams->entropy), NULL, 0)) != 0) {
        Log_e("mbedtls_ctr_drbg_seed failed returned %d", ret);
        return -1;
    }

    if (pConnectParams->port == SYM_ENCRYPTION_HOST)
    {

        if ((ret = mbedtls_x509_crt_parse_file(&(pParams->ca_cert), pConnectParams->ca_file)) != 0) {
            Log_e("load ca file failed returned %d", ret);
            return -1;
        }
        
        if ((ret = mbedtls_x509_crt_parse_file(&(pParams->client_cert), pConnectParams->cert_file)) != 0) {
            Log_e("load client cert file failed returned %d", ret);
            return -1;
        }
        
        if ((ret = mbedtls_pk_parse_keyfile(&(pParams->private_key), pConnectParams->key_file, "")) != 0) {
            Log_e("load client key file failed returned %d", ret);
            return -1;
        }
    } else {
        if (pConnectParams->psk == NULL) {
            Log_e("psk can not be empty");
        }
        if (pConnectParams->psk_id == NULL) {
            Log_e("psk_id can not be empty");
        }
        char *psk_id = pConnectParams->psk_id;
        mbedtls_ssl_conf_psk(&(pParams->ssl_conf), (unsigned char *)pConnectParams->psk, strlen(pConnectParams->psk),
                             (const unsigned char *) psk_id, strlen( psk_id ));
    }
    mbedtls_ssl_conf_ciphersuites(&(pParams->ssl_conf), ciphersuites);
```

But I caught the packet through the network，client still took many ciphersuites
![image](https://user-images.githubusercontent.com/16236724/30967996-796b3e40-a423-11e7-9171-a8b83898cc3f.png)
Is this my code is not correct?

**Comment by hanno-arm** [comment]
Hi @GreenHero,

it seems you are configuring the server-side (otherwise you don't need the option `MBEDTLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE`), which has no influence on what the client offers in his `ClientHello` message. Instead, your configuration affects which ciphersuite from the ones offered by the client your server will chose. 

Also, please note that the list of ciphersuites must be null-terminated, see [the documentation of `mbedtls_ssl_conf_ciphersuites`](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L1532) - otherwise, the library has no way of knowing how many suites you intend to provide.

Hope this helps,
Kind regards,
Hanno

**Comment by GreenHero** [comment]
@hanno-arm thank u for your answer.
I'm configuring the client-side. So i don't need to uncomment macro `MBEDTLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE`?

my ciphersuites code : 
![image](https://user-images.githubusercontent.com/16236724/30970032-c03f9608-a429-11e7-8f7d-1c435112275f.png)

**Comment by hanno-arm** [comment]
Hi @GreenHero,

if you're configuring the client-side, you don't need the macro. Please add a `0` entry to the end of the ciphersuites array, i.e. `const int ciphersuites[] = { MBEDTLS_TLS_PSK_WITH_AES_128_CBC_SHA, MBEDTLS_TLS_PSK_WITH_AES_256_CBC_SHA, 0 };` and try again. It might by that be some bad luck your `ciphersuite` variable was followed by non-zero random garbage in memory, resulting in lots of ciphersuites being added (unknown IDs are silently dropped, so one wouldn't notice).

Kind regards,
Hanno

**Comment by GreenHero** [comment]
Hi @hanno-arm 
I modified the code according to your suggestion。

```
const int ciphersuites[] = { MBEDTLS_TLS_PSK_WITH_AES_128_CBC_SHA, MBEDTLS_TLS_PSK_WITH_AES_256_CBC_SHA, 0 };

 int _mbedtls_client_init(TLSDataParams *pParams, TLSConnectParams *pConnectParams) {
    int ret = 0;
    mbedtls_net_init(&(pParams->socket_fd));
    mbedtls_ssl_init(&(pParams->ssl));
    mbedtls_ssl_config_init(&(pParams->ssl_conf));
    mbedtls_ctr_drbg_init(&(pParams->ctr_drbg));
    mbedtls_x509_crt_init(&(pParams->ca_cert));
    mbedtls_x509_crt_init(&(pParams->client_cert));
    mbedtls_pk_init(&(pParams->private_key));

    mbedtls_entropy_init(&(pParams->entropy));
    // 随机数, 增加custom参数, 目前为NULL
    if ((ret = mbedtls_ctr_drbg_seed(&(pParams->ctr_drbg), mbedtls_entropy_func,
                                     &(pParams->entropy), NULL, 0)) != 0) {
        Log_e("mbedtls_ctr_drbg_seed failed returned %d", ret);
        return -1;
    }

    if (pConnectParams->port == SYM_ENCRYPTION_HOST)
    {

        if ((ret = mbedtls_x509_crt_parse_file(&(pParams->ca_cert), pConnectParams->ca_file)) != 0) {
            Log_e("load ca file failed returned %d", ret);
            return -1;
        }
        
        if ((ret = mbedtls_x509_crt_parse_file(&(pParams->client_cert), pConnectParams->cert_file)) != 0) {
            Log_e("load client cert file failed returned %d", ret);
            return -1;
        }
        
        if ((ret = mbedtls_pk_parse_keyfile(&(pParams->private_key), pConnectParams->key_file, "")) != 0) {
            Log_e("load client key file failed returned %d", ret);
            return -1;
        }
    } else {
        if (pConnectParams->psk == NULL) {
            Log_e("psk can not be empty");
        }
        if (pConnectParams->psk_id == NULL) {
            Log_e("psk_id can not be empty");
        }
        char *psk_id = pConnectParams->psk_id;
        mbedtls_ssl_conf_psk(&(pParams->ssl_conf), (unsigned char *)pConnectParams->psk, strlen(pConnectParams->psk),
                             (const unsigned char *) psk_id, strlen( psk_id ));
    }
    mbedtls_ssl_conf_ciphersuites(&(pParams->ssl_conf), ciphersuites);

    return 0;
}
```
Unfortunately my question is still unresolved. This is a screenshot of my new network capturing packets:
![image](https://user-images.githubusercontent.com/16236724/30997461-aa1b6f78-a48d-11e7-9f7c-23e8d243b9da.png)

**Comment by GreenHero** [comment]
hi @hanno-arm 
I might call the function `mbedtls_ssl_conf_ciphersuites` too early, causing the encryption suite to fail. In the original code, I executed `mbedtls_ssl_conf_ciphersuites` before the function `mbedtls_net_connect` and the function `mbedtls_ssl_config_defaults` were called.
Now I succeeded in calling the function `mbedtls_ssl_setup` after executing `mbedtls_ssl_conf_ciphersuites`, and then i set the list of allowed ciphersuites successfully

![image](https://user-images.githubusercontent.com/16236724/30999047-23912064-a498-11e7-8497-4a908c8772af.png)

thank u.

**Comment by hanno-arm** [comment]
Hi @GreenHero,

with that additional information, the problem got apparent: When you call `mbedtls_ssl_config_defaults`, the configuration is brought into a default state which includes setting a fixed list of ciphersuites. Hence if you call this function after you've called `mbedtls_ssl_conf_ciphersuites`, the effect of the latter will be overwritten.

In general, the order should be: (1) Initialize configuration and potentially set to default state. (2) Make manual adaptions through `mbedtls_ssl_conf_XXX`, in particular `mbedtls_ssl_conf_ciphersuites`. (3) Bind config to SSL context via `mbedtls_ssl_setup`. (4) Start connection.

Kind regards,
Hanno

**Comment by GreenHero** [comment]
thank u, @hanno-arm
