### ISSUE TITLE
Can RSA support CRT and NO_CRT mode at same time

### ISSUE THREAD

**Issue by edison-ai** [ARMmbed/mbedtls#1114]
### Description
- Type: Enhancement\Feature Request 
- Priority: Major
---------------------------------------------------------------
## Enhancement\Feature Request
We are merging mbedtls into OPTEE os. OPTEE will use RSA in CRT mode or NO_CRT mode at same time. 

But, In function mbedtls_rsa_private() in rsa.c, mbedtls use MBEDTLS_RSA_NO_CRT to configure which mode it is. Can we move the MBEDTLS_RSA_NO_CRT, and support CRT and NO_CR at same time? 

-----------------------------------------------------------------

**Comment by hanno-arm** [comment]
Hi @sliai,

at the moment, the use of CRT is determined at compile time through the option `MBEDTLS_RSA_NO_CRT`. In particular, the interface to the RSA functions does not offer the choice between CRT / non-CRT. 

Could you provide more information on why and how you intend to use CRT and non-CRT simultaneously? Is the choice at least fixed for every RSA context, or do you want to perform both CRT and non-CRT on a single context?

Kind regards,
Hanno

**Comment by sliai** [comment]
Hi Hanno, 

Thanks for your quick response.

In OPTEE, the app will pass parameters(D, P, Q) to encrypt function. P and Q are optional. So, there will have two case:
1. Only pass D, so we can use RSA NO_CRT mode.
2. Pass D, P and Q. Of course, we can still use NO_CRT mode here. But I think it will be better if we can use CRT mode in this case.

Can you confirm which mode it is through checking if P and Q are NULL?

Kind regards,
Edison

**Comment by hanno-arm** [comment]
Hi @sliai,

for that scenario, we might be able to get away differently: There's a PR #1060 open at the moment which intends to support setting up RSA contexts from a restricted set of core parameters, including `N,D,E` only. In the latter case, it would infer `P,Q` automatically, provided they are needed (for CRT or blinding, e.g.).

Could you have a look and check wheter that would resolve your issue?

Kind regards,
Hanno

**Comment by sliai** [comment]
Hi @hanno-arm,

That may be useful for my scenario, I need to test it when you finished. 
When will you finish this PR?

Kind regards,
Edison

**Comment by hanno-arm** [comment]
Hi Edison,

as you can see, the PR is under quite active discussion, so we're working to get it in soon.

If you want to give it a try, you'd pass the parameters you have via `mbedtls_rsa_import` and call `mbedtls_rsa_complete` afterwards, and potentially missing parameters will should hopefully be deduced automatically. You'll find numerous examples for that in the [test suite for RSA](https://github.com/hanno-arm/mbedtls/blob/56bae95e1d3528d4c562293c915c74ea8762505c/tests/suites/test_suite_rsa.function), e.g. [the decryption-test](https://github.com/hanno-arm/mbedtls/blob/56bae95e1d3528d4c562293c915c74ea8762505c/tests/suites/test_suite_rsa.function#L335).

Of course, if you have any feedback, especially on whether it'll suit your needs, let us know,

Regards,
Hanno

**Comment by RonEld** [comment]
Closing this issue, as the referenced PR has been merged. If the #1060 doesn't resolve your issue, please reopen.
