### ISSUE TITLE
Bugs in example program pk_encrypt.c

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1128]
### Description
- Type: Bug 
- Priority:  Minor
Raised via Email by Brace Stout
---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: development branch

I was looking through the example programs trying to get an idea of how to use the PK wrapper to abstract the RSA/EC functions, and think there are some issues with the pk_encrypt.c example program. This is probably low priority, but as an example program, it should be an example of proper use.
Specifically, the following code occurs at the exit label:
~~~
exit:
mbedtls_ctr_drbg_free( &ctr_drbg );
mbedtls_entropy_free( &entropy );
~~~
In some code paths, entropy is not yet initialized.
Similarly, the `mbedtls_pk_context` variable `pk` is never freed, even when it is initialized.
Two approaches to addressing these problems come immediately to mind:
1) init everything at the same time: `ctr_drbg`, `entropy`, and `pk` and then free them all at the same time (at the exit label), or
2) have three separate exit labels (e.g. exitA, exitB, exitC) and branch to whichever is appropriate at the point an error is encountered.
~~~
exitA:
mbedtls_pk_free( &pk );
exitB:
mbedtls_entropy_free( &entropy );
exitC:
mbedtls_ctr_drbg_free( &ctr_drbg );
~~~

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1806

**Comment by sbutcher-arm** [comment]
PR #1129 has now been merged so issue can be closed.
