### ISSUE TITLE
Add possibility to configure CTR_DTBG AES key size

### ISSUE THREAD

**Issue by al1img** [ARMmbed/mbedtls#1146]
### Description

- Type: Enhancement
- Priority: Major

## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

There are SoC's which have HW AES module with certain key size (128). For example TI CC265X,
Microchip SAMR21 etc. But for DTLS it is impossible to use HW AES as CTR_DRBG requires AES 256.
According to NIST SP 800-90 128 bits also can be used.

**Suggested enhancement**  

Add support of 128 bits key (or any acceptable) to CTR_DRBG and make it configurable through MBEDTLS_CONFIG_FILE.

**Comment by RonEld** [comment]
Hi @al1img Thank you for reporting this. 
We are aware of this  limitation. and we are thinking how and if to change this. e.g. whether to make it configurable, or just change it to AES 128, as you rightfully stated that NIST SP 800-90 A allows AES 128. We will take into consideration your request, and we will also need to thoroughly investigate what else should be modified.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1855

**Comment by RonEld** [comment]
Hi @al1img 
I believe that #1183 addresses your issue.

**Comment by gilles-peskine-arm** [comment]
@RonEld #1183 addresses this as a side effect, but it also changes the API so we aren't going to adopt it, and it doesn't test non-default key sizes. We've independently added an option to configure the key size for CTR_DRBG in #1902 which is ready for merge.

**Comment by al1img** [comment]
Thanks all. #1902 resolves my issue.
