### ISSUE TITLE
ecp_internal.h results in undefined reference

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#1147]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
mbed-OS

**mbed TLS build:**  
Version: 2.6.0
OS version: 5.6 with  https://github.com/ARMmbed/mbed-os/pull/4825

**Expected behavior**   
Compilation succeeds without errors nor warnings

**Actual behavior**  
Warning: implicit declaration of function 'mbedtls_internal_ecp_xxx'. This is due to ECP_SHORTWEIERSTRASS being checked in the ecp_internal.h header which is supposed to supply the function prototypes, but the ECP_SHORTWEIERSTRASS define is only set in the ecp.c source file, after the header has already been pulled in.
https://github.com/ARMmbed/mbedtls/blob/005939db984168406d8fed04874379677cdd630f/include/mbedtls/ecp_internal.h#L101

As indicated by @RonEld  in https://github.com/ARMmbed/mbed-os/pull/4825 ECP_SHORTWEIERSTRASS is an internal define of mbed TLS and should therefore not be globally defined.

**Steps to reproduce**  
Apply PR and build an mbed-os sample application using mbedTLS ECP.

----------------------------------------------------------------
## Enhancement\Feature Request

**Suggested enhancement**  
Remove the check on ECP_SHORTWEIERSTRASS from the header file, since the function prototypes should always be visible.

**Comment by RonEld** [comment]
Hi @stevew817 Thanks you for reporting this
We will look in to this to understand what is the best approach to fix this

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1860

**Comment by RonEld** [comment]
HI @stevew817 I believe that https://github.com/ARMmbed/mbedtls/pull/965 already fixes this issue
