### ISSUE TITLE
Composite algorithm call basic algorithm directly

### ISSUE THREAD

**Issue by edison-ai** [ARMmbed/mbedtls#1148]
### Description
- Type: Enhancement\Feature Request
- Priority: Blocker

----------------------------------------------------------------
## Enhancement\Feature Request

**OS**
OPTEE_OS

**Basic algorithm**
Like hash, aes, des

**Composite algorithm**
Like GCM, HMAC which base on  the basic algorithm 

**Background**

We are integrate mbedTLS into OPTEE_OS(secure OS), but we met one issue:
OPEE will alloc and manage the context memory the crypto function needed. It is conflict with mbedtls, because mbedtls will alloc context memory in its start() function. The detail of process in optee is this:
- Get context size which crypto needed, then alloc it.
- Call init, update and finished function to do crypto.
- End, free the context memory.

AS we know, the structure in mbedtls is like this:
1. MbedTLS high level interface
2. Internal glue layer on top of each algorithm
3. The actual algorithm
In this structure, mbedtls will alloc and manage its context memory in level 1. 

For the integration, we will skip level 1 and 2, and call the interfaces of level 3 directly. This method is ok for basic algorithm. But it cannot works on composite algorithm like GCM and CMAC. Because the composite algorithm(level 3) will call cipher's interfaces in level 1. 

**Enhancement\Feature Request**
So, our suggestion is that enhance those composite algorithm which let them call the interfaces in level 3 directly. It will be very helpful for our integration.

Thanks,
Edison

**Comment by RonEld** [comment]
Hi @sliai Thank you for your suggestion.
We will look whether and how this could be achieved

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1859

**Comment by edison-ai** [comment]
Do not need again for our integrate, because optee_os had support the wrap layer interfaces now.
