### ISSUE TITLE
Let caller to allocate and manage context memory for mbedTLS

### ISSUE THREAD

**Issue by edison-ai** [ARMmbed/mbedtls#1154]
### Description
•	Type: Enhancement\Feature Request
•	Priority: Blocker
## Enhancement\Feature Request
**OS**
OPTEE_OS

**Background**
We are integrate mbedTLS into OPTEE_OS(secure OS), but we met one issue: OPEE need to allocate and manage the context memory for crypto function. It is conflict with mbedTLS, because mbedTLS will allocate  and manage its context memory by itself.

**Suggestion**
So, we suggest to enhance the mbedTLS to let it support the context memory allocate and manage by its caller. 
The detail change can like this:
1.	Add one build flag (for example: CALLOC_BUFFER_BY_CALLER) to let new mode (allocate by caller) differ from the old mode (allocate by mbedTLS).
2.	Add union for algos. Use md as a example:
```
typedef union _mbedtls_md_state {
	char dummy[1];
#if defined(MBEDTLS_MD2_C)
	mbedtls_md2_context md2;
#endif
#if defined(MBEDTLS_MD4_C)
	mbedtls_md4_context md4;
#endif
#if defined(MBEDTLS_MD5_C)
	mbedtls_md5_context md5;
#endif
#if defined(MBEDTLS_RIPEMD160_C)
	mbedtls_ripemd160_context ripemd160;
#endif
#if defined(MBEDTLS_SHA1_C)
	mbedtls_sha1_context sha1;
#endif
#if defined(MBEDTLS_SHA256_C)
	mbedtls_sha256_context sha256;
#endif
#if defined(MBEDTLS_SHA512_C)
	mbedtls_sha512_context sha512;
#endif
	void *data;
} mbedtls_md_state;
```
3.	Change the structure of context (union added in step 2) to replace the ctx point with its structure. Use md as a example:
```
typedef struct {
    /** Information about the associated message digest */
    const mbedtls_md_info_t *md_info;
#if defined(CALLOC_BUFFER_BY_CALLER)
    mbedtls_md_state md_ctx;
    unsigned char hmac_ctx[256];
#else
    /** Digest-specific context */
    void *md_ctx;
    /** HMAC part of the context */
    void *hmac_ctx;
#endif
} mbedtls_md_context_t;
```
4.	Caller will get the size of the mbedtls_md_context_t and allocate buffer for it.
5.	End, change the functions which are relative with the memory allocate and free. 

Of course, all changing will not affect the current functions in mbedTLS: tests, applications, etc.

Thanks,
Edison

**Comment by RonEld** [comment]
Hi @sliai Thank you for your suggestion.
I am not sure why you think Mbed TLS allocates the memory itself.  
If you look at the md example you have given, you will see that all the md API receive `mbedtls_md_context_t *ctx` as parameter. In the examples, it is a pointer to a context set on the stack, but it could easily be a pointer on the heap. According to the algorithm type, you know the size of the context, so you have all the information you need.  
According to your description, I assume you mean the [line](https://github.com/ARMmbed/mbedtls/blob/development/library/md.c#L230):
~~~
if( ( ctx->md_ctx = md_info->ctx_alloc_func() ) == NULL )
~~~
But if I understand OP-TEE correct, the `get_ctx_size ` should be for the API context size, hence `mbedtls_md_context_t`, and not internal pointer used.  
Am I missing something?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1858

**Comment by sliai** [comment]
Hi @RonEld Thanks for your replay. 
In our scenario, we need to use crypto library as this:
- Get context size which crypto needed, then allocate it.
- Call init, update and finished function to do crypto.
- End, free the context memory.
Also, use md as example, we use interface in md.c. When OS need to get context size, it can get the size of struct mbedtls_md_context_t. But as you know, the mbedtls_md_context_t only has a pointer for  actual algorithm. So, Os need to call the interface mbedtls_md_setup() to let mbedtls to allocate internal context memory for each actual algorithm. 
For the caller, it want to know how many memory size the mbedtls needs and allocate the memory for it. And the memory will be managed by the caller. So I talked before, we need replace the internal pointer in struct mbedtls_md_setup with its variable. 
As this structure:
```
typedef struct {
    /** Information about the associated message digest */
    const mbedtls_md_info_t *md_info;
#if defined(CALLOC_BUFFER_BY_CALLER)
    mbedtls_md_state md_ctx;
    unsigned char hmac_ctx[256];
#else
    /** Digest-specific context */
    void *md_ctx;
    /** HMAC part of the context */
    void *hmac_ctx;
#endif
} mbedtls_md_context_t;
```
we use _mbedtls_md_state md_ctx;_ directly here. In this method,  caller can know the actually memory for internal use. 
By the way, the mbedtls_md_setup() will not allocate buffer anymore in my solution.

Thanks,
Edison

**Comment by RonEld** [comment]
Hi Edison, Thanks for your explanation.
I understand your suggestion, but I think we could still achieve OP-TEE to work with the current implementation.
in your provider code:
~~~
#if defined(_CFG_CRYPTO_WITH_HASH)
	.hash = {
		.get_ctx_size = sizeof(mbedtls_md_state md_ctx),
		.init = hash_init,
		.update = hash_update,
		.final = hash_final,
	},
#endif
~~~
and your implementation of `hash_init` could be as following:
~~~
hash_init()
{
mbedtls_md_init
mbedtls_md_setup
}
~~~
This will allocate the memory in the driver code, and not the OS layer, but unless I am missing something, it should work.
Alternatively, you could avoid using the md wrapper code, and use directly the MD functionality, which doesn't allocate any memory:
For example, `mbedtls_sha1_xxx` , `mbedtls_sha256_xxx` , `mbedtls_sha512_xxx`

**Comment by sliai** [comment]
Hi @RonEld, thanks for your suggestions.
1. Do mbedtls_md_setup() in hash_init().
Yes, we had tried as this before. But there is one problem. There is not interface in OPTEE_OS for mbedTLS to free its allocated memory. You can see, there only are 4 interfaces. By the way, the hash_init() maybe called many times because this function is considered as a reset() function to clear memory in OPTEE_OS. And the hash_finish() is just as mbedtls_md_finish(), we cannot free memory in here.
Of course, we can add new interfaces in OPTEE_OS to let mebdTLS to free memory. But that solution does not make sense. 

2. Skip wrapper layer.
Yes, we also have one solution in this method. But there are still two problems. 
- One  is that the modules as GCM will call the cipher's wrapper interface directly. I had created a issue to talk about that: https://github.com/ARMmbed/mbedtls/issues/1148. 
- Another is that there are still many data process in the interface and wrapper layers. We can see the cipher function. If we skip the top two layers, we have to implement another layer in OPTEE_OS which do as mebdTLS's interface and wrapper layers. But this will be difficult for later maintaining. We cannot fix the issue just like "git rebase", while we have to merger them by hand. 

So, after trying some solutions, we think that solution(what we suggest in this issue) will be better. 
Do you have any more suggestions to fix the issue we met?

Thanks,
Edison

**Comment by RonEld** [comment]
Hi @sliai 
Thank you for your explanation
>By the way, the `hash_init()` maybe called many times because this function is considered as a `reset()`

I think this could be problematic. If one would have an alternative implementation using HW accelerated functionality, the HW accelerated driver might allocate  some internal memory, which will cause future issues. I think having an `init` function with out a corresponding `finish` function is not good.

>One is that the modules as GCM will call the cipher's wrapper interface directly.
These are special cases, where we could discuss on the other issue

>Another is that there are still many data process in the interface and wrapper layers.
The cipher wrapper adds some additional code such as padding, but is this something that would\should be supported in OP-TEE?
I think at least for MD functionality, there isn't additional data process, and you could call directly the `mbedtls_shaxxx_xxx()` functions ( and all other md functions)

**Comment by sliai** [comment]
Hi @RonEld 
Yes, the MD functionality is simply and no data process in wrapper layer. So it will be ok to call directly algo functions. But I think it will be better that we have one same method for all functionality: call interface layer or algo interfaces.

It is strange for the usage of has_init() function. But I think that OPTEE_OS needs to allocate and manage all context memory for crypto.  So it think that the init() function can be used as that way. 

Yes, OPTEE_OS need to support those like padding. If we call AES or DES function directly, we have to add their support in OPTEE_OS. But if we can use the interface in cipher.c, it will be more  simple and make sense.

We had test MD, cipher, GCM, CCM of mbedTLS with all test are pass. And the changing are not many and complex. Wit the configure flag, it will not affect any current functions and applications.

**Comment by RonEld** [comment]
Hi @sliai 
Thank you for your information
>It is strange for the usage of has_init() function. But I think that OPTEE_OS needs to allocate and manage all context memory for crypto. So it think that the init() function can be used as that way.

As mentioned, I think it might cause future issues, when there will be usage of HW accelerators with mMbed TLS

**Comment by edison-ai** [comment]
Do not need again for our integrate, because optee_os had support the wrap layer interfaces now.
