### ISSUE TITLE
missing prototype error in aes.c when MBEDTLS_DEPRECATED_REMOVED is defined

### ISSUE THREAD

**Issue by gkerrien38** [ARMmbed/mbedtls#1156]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
none

**mbed TLS build:**  
Version: 2.6.0  
OS version: none  
Configuration: MBEDTLS_DEPRECATED_REMOVED is defined  
Compiler and options:  IAR EWARM 7.80.4 with "Require prototype" option.
Additional environment information:  

**Peer device TLS stack and version**  
None

**Expected behavior**   
 Compilation succeeds without errors nor warnings

**Actual behavior**  
With mbedTSL 2.6.0, when MBEDTLS_DEPRECATED_REMOVED is defined in config.h, there are 2 errors "missing prototype" for functions mbedtls_aes_encrypt() and mbedtls_aes_decrypt() in aes.c.

**Steps to reproduce**  
define MBEDTLS_DEPRECATED_REMOVED in config.h and compile.

**Comment by hanno-arm** [comment]
Hi @gkerrien38,

thanks for catching and reporting this! :+1: We have recently noticed it, too, and it has been fixed as part of #1100 (specifically https://github.com/ARMmbed/mbedtls/pull/1100/commits/78457e8148573b423b1d17ee8c46217ef0c61353) which is currently under review.

Kind regards,
Hanno

**Comment by gkerrien38** [comment]
Hi

Yes,  78457e8 solves the build problem.

Thanks,
Bill

**Comment by hanno-arm** [comment]
Hi @gkerrien38,

great, thanks for confirming! 

In that case, we will close this issue as soon as #1100 has been merged.

Kind regards,
Hanno

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2534

**Comment by Patater** [comment]
Fixed by #1448
