### ISSUE TITLE
Incorrect use of Arm Trademarks

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1158]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

The `README.md` file does not correctly use the 'Mbed' trademark, as per [Arm's guidelines](https://www.arm.com/company/policies/trademarks/arm-trademark-list/mbed-trademark), and thoughout the file refers to 'mbed TLS' not 'Mbed TLS'.

Trivial and maybe petty, but if you don't refer to the trademark correctly you're not using the trademark.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1862

**Comment by gilles-peskine-arm** [comment]
Merged #1159 into `development`. No backport requested.

**Comment by gilles-peskine-arm** [comment]
Fixed by https://github.com/ARMmbed/mbedtls/pull/1159
