### ISSUE TITLE
Solaris: tests won't compile

### ISSUE THREAD

**Issue by tropikhajma** [ARMmbed/mbedtls#1170]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Solaris

**mbed TLS build:**  
Version: 2.6.0
OS version: 11.3  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
gcc 5.4.0

**Expected behavior**   
compiles cleanly

**Actual behavior**  
-bash-4.4$ CC=/usr/bin/gcc gmake all
  CC    test_suite_aes.ecb.c
main_test.function: In function 'main':
main_test.function:411:50: error: lvalue required as unary '&' operand
main_test.function:423:56: error: lvalue required as unary '&' operand
gmake[1]: *** [Makefile:202: test_suite_aes.ecb] Error 1
gmake: *** [Makefile:21: tests] Error 2

**Steps to reproduce**  
CC=/usr/bin/gcc gmake all

I can get it to compile with the attached patch
[patch.txt](https://github.com/ARMmbed/mbedtls/files/1479495/patch.txt)

**Comment by RonEld** [comment]
@tropikhajma thank you for reporting this issue. We will look into this, and investigate what should be the best fix that will be compatible to all OS.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1933
