### ISSUE TITLE
Correct superseding of mbedtls_aes_xxcrypt

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1171]
__Issue:__ The functions `mbedtls_aes_encrypt` and `mbedtls_aes_decrypt` are documented as being deprecated and superseded by `mbedtls_aes_xxcrypt_ext`, which don't exist. Probably `mbedtls_internal_aes_xxcrypt` are meant, but judging from their name these are not intended to be public, hence shouldn't be considered a replacement for a public function.

```
/**
 * \brief           Deprecated internal AES block encryption function
 *                  without return value.
 *
 * \deprecated      Superseded by mbedtls_aes_encrypt_ext() in 2.5.0
 *
 * \param ctx       AES context
 * \param input     Plaintext block
 * \param output    Output (ciphertext) block
 */
MBEDTLS_DEPRECATED void mbedtls_aes_encrypt( mbedtls_aes_context *ctx,
                                             const unsigned char input[16],
                                             unsigned char output[16] );
```

__Suggestion:__ Supersede `mbedtls_aes_xxcrypt` by the respective calls to `mbedtls_aes_ecb`, i.e. `mbedtls_aes_encrypt( A, B, C )` by `mbedtls_aes_ecb( A, MBEDTLS_AES_ENCRYPT, B, C )` and `mbedtls_aes_decrypt( A, B, C )` by `mbedtls_aes_ecb( A, MBEDTLS_AES_DECRYPT, B, C )`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2533
