### ISSUE TITLE
mbedtls_aes_self_test is missing tests for stream resuming in CTR mode

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1177]
### Description
- Type: Enhancement\Feature Request
- Priority:  Minor

## Enhancement\Feature Request
Missing tests for different `*nc_off` in CTR mode, in `mbedtls_aes_self_test`

**Justification - why does the library need this feature?**  
When implementing alternative aes, for example in Hardware acceleration, there is a need to test that implementation was correct

**Suggested enhancement**  
run the `mbedtls_aes_crypt_ctr` function twice, with different lengths for the first call

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1932

**Comment by RonEld** [comment]
@sbutcher-arm comment:
>There's no need to have `nc_off` tests in a self-test.
To be clear - self-tests are supposed to be functional tests that can be executed as start-up or diagnostic tests on the final production device, as a way of confirming that the device is functioning correctly. Sometimes these tests may be executed to confirm a device hasn't been compromised by an attack.
The `nc_off` test is a design test to validate the implementation - and specifically - this is a robustness provision. There's no reason, nor advantage to execute it on a final device, so I don't think it belongs in a self-test.

Therefore, closing this issue, and we will continue to track this in #1085
