### ISSUE TITLE
In test_suite_pk.function, the invalid size tests are not testing what they should

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1179]
- Type: Bug
- Priority: Minor

In `tests/suites/test_suite_pk.function`, there are calls to `mbedtls_pk_sign`, `mbedtls_pk_verify` and `mbedtls_pk_verify_ext` that pass a NULL pointer as the signature buffer and a size that is too large. The test verifies that the function returns `MBEDTLS_ERR_PK_BAD_INPUT_DATA`, but it's actually doing that because of the NULL pointer and not because of the size. Since the job of the test is to validate the size check, the test is not doing its job, it's just passing by coincidence.

The test should pass a valid pointer instead.

Detected in #900

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1931
