### ISSUE TITLE
AES is much slower than OpenSSL with AESNI enabled

### ISSUE THREAD

**Issue by WuBingzheng** [ARMmbed/mbedtls#1189]
### Description
- Type:Question
- Priority: Minor

---------------------------------------------------------------

## Question

I test the speed of AES-128 in CBC and GCM of mbedtls(2.6.0) and openssl(1.0.1e-fips), with AESNI enabled.
Here is the result in Mbytes/s :

```
|         | CBC | GCM  |
| mbedtls | 385 | 167  |
| openssl | 700 | 1545 |
```

mbedtls is much slower than openssl, especially at GCM mode.
Is this ok, or did I miss anything?

CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
OS: CentOS 7.2
Commands:
 - mbedtls: programs/test/benchmark
 - openssl: openssl speed -evp aes-128-cbc; openssl speed -evp aes-128-gcm

Thanks,
Wu

**Comment by RonEld** [comment]
Hi @WuBingzheng Thank you for raising this into our attention!
I have checked as well, limiting both programs to a single processor, and saw similar results. We will investigate this further.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1935

**Comment by bwesterb** [comment]
Is there any progress on this issue?

(Our preliminary profiling suggests that `mbedtls_aesni_gcm_mult` is the culprit.)

**Comment by jack-fortanix** [comment]
There are a couple of causes for the poor GCM performance.

First, mbedtls does not pipeline the AES-NI instructions. The latency of these instructions is 6-8 cycles, but a new one can be issued every cycle. Thus the best performance is achieved by processing between 4 and 8 blocks in parallel, which hides the instruction latency. This does not help all modes, but it does speed up ECB, CTR, XTS, GCM, or (for decryption only) CBC. This speedup can be observed by comparing `openssl speed -evp aes-128-cbc` with and without `-decrypt` flag (decrypt is over 4x faster on my machine).

Second the GCM reduction algorithm (in `mbedtls_aesni_gcm_mult`) is non-optimal. By precomputing a few multiples of `H` it is possible to do a delayed reduction. This is described in Intel's manual for CLMUL. In the past I've found this technique to be about 2-3x faster than what mbedtls currently does.
