### ISSUE TITLE
RSA and ECDSA much slower than openssl

### ISSUE THREAD

**Issue by WuBingzheng** [ARMmbed/mbedtls#1214]
### Description
- Type: Question
- Priority: Minor

---------------------------------------------------------------

## Question

I test the speed of RSA-2048 and ECDSA-256 of mbedtls(2.6.1) and openssl(1.1.0f), at raspberrypi with arm7.
Here is the result (sign/verify in ops/s) :

             ras2048  ecdsa256
    mbedtls  21/823    150/47
    openssl  36/1363  1437/718

where mbedtls is much slower than openssl both.
I test this on x86_64 and get similar result, but I do not have the result by now.

I build mbedtls with the default config.h.
Is the result right?

With [another issue](https://github.com/ARMmbed/mbedtls/issues/1189) I posted, I want to ask that, have you benchmarked mbedtls and compared with openssl? Do you care about the performance of mbedtls?

Thanks,
Wu

**Comment by RonEld** [comment]
Hi @WuBingzheng Thank you for raising this!
AS I answered in the other issue, we will investigate this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1952
