### ISSUE TITLE
Consider naming structs so it is possible to forward declare them

### ISSUE THREAD

**Issue by randombit** [ARMmbed/mbedtls#1215]
Currently in ecp.h the `mbedtls_ecp_keypair` struct is defined as

```
typedef struct {
  // various values
} mbedtls_ecp_keypair;
```

The problem arises, I am currently working on a codebase that supports both OpenSSL and mbedtls. For the OpenSSL case I have something like `typedef struct ec_key_st MY_ECC_KEY` and then use `MY_ECC_KEY*` as parameters to various functions. But there is afaict no way to provide a similar forward declaration for `mbedtls_ecp_keypair`, because the `struct` has no name! Instead I must actually include the mbedtls header in order to get the typedef.

It would be nice if this could be fixed in a future release. I believe all that is required is to grep for "typedef struct {" and for each case insert the same name as the typedef. Then my code would not have to include mbedtls in the header, and I could use

```typedef struct mbedtls_ecp_keypair MY_ECC_KEY```.

(This already works for some structs, like ``mbedtls_x509_crt``)

I think this would be useful outside my case as I imagine there are many applications that support mbedtls as well as another implementation, and being able to forward declare types allows making the implementation more opaque to the larger codebase.

**Comment by RonEld** [comment]
HI @randombit Thank you for your suggestion.
We would take this into consideration.

As an open source project, we welcome contributions from the community, as long as the contributor followed our [coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards) and signed the [CLA](https://github.com/ARMmbed/mbedtls#contributing).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1951

**Comment by deleisha** [comment]
Just did a grep on `typedef struct` and found that it is less than 80 places where the possible changes might takes place, excluding tests and program folder. 
Let me know if you want a volunteer. I intend to change by reusing the typedef name as also the struct TAG, for example

``` C
typedef struct
{
    uint32_t P[MBEDTLS_BLOWFISH_ROUNDS + 2];    /*!<  Blowfish round keys    */
    uint32_t S[4][256];                 /*!<  key dependent S-boxes  */
}
mbedtls_blowfish_context;
```
to 
``` C
typedef struct mbedtls_blowfish_context
{
    uint32_t P[MBEDTLS_BLOWFISH_ROUNDS + 2];    /*!<  Blowfish round keys    */
    uint32_t S[4][256];                 /*!<  key dependent S-boxes  */
}
mbedtls_blowfish_context;

**Comment by sbutcher-arm** [comment]
PR #1861 merged so this issue can now be closed.
