### ISSUE TITLE
Different behavior in AES-GCM update command compared to openssl

### ISSUE THREAD

**Issue by daohongLi** [ARMmbed/mbedtls#1218]
### Description
- Type: Question
- Priority: Minor

---------------------------------------------------------------
## Question
I'm not sure if this is a bug or not. The mbedtls's cipher_update behaves differently to the openssl's.

It seems that the nonce is incremented by 1 every time an update is invoked, even the input data is less than 16 byte. 
```C
    if(mbedtls_cipher_update(&ctx, dummy, 5, output, &out_len) < 0){
        printf("unable to update\n");
        return 0;
    }

    if(mbedtls_cipher_update(&ctx, input, input_len, output, &out_len) < 0){
        printf("unable to update\n");
        return 0;
    }
```
In this case the second update gives a ciphertext **c6a106d14e264892cc3cfaa6ebdbbcd787**

Meanwhile in openssl, if the input data is less than 16 byte.
```C
    if(EVP_CipherUpdate(ctx, output, &out_len, dummy, 5) == 0){
        printf("unable to update\n");
        return 0;
    }

    if(EVP_CipherUpdate(ctx, output, &out_len, input, input_len) == 0){
        printf("unable to update\n");
        return 0;
    }
```
The second update gives a differente ciphertext **782daccb8b339489e2df58c6a106d14e26**, seems that the nonce is not incremented.

Now, if the first update has 16 byte as input data, the nonce is incremented by 1,
```C
    if(EVP_CipherUpdate(ctx, output, &out_len, dummy, 16) == 0){
        printf("unable to update\n");
        return 0;
    }

    if(EVP_CipherUpdate(ctx, output, &out_len, input, input_len) == 0){
        printf("unable to update\n");
        return 0;
    }
```
and the second update give ciphertext **c6a106d14e264892cc3cfaa6ebdbbcd787** which is exactly the ciphertext obtained by using mbedtls.

This can be generalized for large input size. The point is I have this problem since I can't decrypt the mbedtls encrypted message by using openssl and vice versa.

I hope it is understandable.... I'm trying my best to explain the situation, test codes are attached.

[mbed_gcm.txt](https://github.com/ARMmbed/mbedtls/files/1572725/mbed_gcm.txt)
[openssl_gcm.txt](https://github.com/ARMmbed/mbedtls/files/1572726/openssl_gcm.txt)

Thank you.

**Comment by RonEld** [comment]
Hi @daohongLi Thank you for raising this!
Although your analysis is correct, if you look at the [function documentation](https://tls.mbed.org/api/gcm_8h.html#a922addfa5c93fa08b6e9da134d5d8f2d) you will see the notice that it:
>Expects input to be a multiple of 16 bytes! Only the last call before mbedtls_gcm_finish() can be less than 16 bytes!

So your use case is not according to documentation.

**Comment by daohongLi** [comment]
@RonEld Thank you very much for clarifying. My bad, I wasn't paying attention to the documentation.
