### ISSUE TITLE
Too much data read from /dev/urandom when using POLARSSL_TIMING_C

### ISSUE THREAD

**Issue by NWilson** [ARMmbed/mbedtls#122]
Each iteration of entropy gathering collects 8 bytes of data from the `hardclock_poll` source, which has a target of 32 bytes (`ENTROPY_MIN_HARDCLOCK`). This means that four iterations of the entropy gathering loop happen before the hardclock poll target is reached.

We therefore read 512 bytes from HAVEGE and `/dev/urandom` -- that seems a bit excessive, and will mess up any tracking the OS is doing to gauge how much entropy there is left in the pool. This will cause problems for anyone reading from the (blocking) `/dev/random`. Arguably, 128 bytes already completely overkill!

**Comment by mpg** [comment]
This is fixed in the 2.0 branch. I also changed the thresholds to a more sensible 32 bytes (256 bits) for havege and platform, and 4 bytes (32 bits) for the cycle counter.
