### ISSUE TITLE
ssl->f_send length argument negative

### ISSUE THREAD

**Issue by samoconnor** [ARMmbed/mbedtls#1245]
It looks like the `ssl->out_left` counter can go negative here `ssl->out_left -= ret`: https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L2446

Maybe a check like this is needed ?
```patch
--- ssl_tls.c.orig	2017-12-29 15:25:21.000000000 +1100
+++ ssl_tls.c	2017-12-29 15:25:30.000000000 +1100
@@ -2434,22 +2434,28 @@
     while( ssl->out_left > 0 )
     {
         MBEDTLS_SSL_DEBUG_MSG( 2, ( "message length: %d, out_left: %d",
                        mbedtls_ssl_hdr_len( ssl ) + ssl->out_msglen, ssl->out_left ) );

         buf = ssl->out_hdr + mbedtls_ssl_hdr_len( ssl ) +
               ssl->out_msglen - ssl->out_left;
         ret = ssl->f_send( ssl->p_bio, buf, ssl->out_left );

         MBEDTLS_SSL_DEBUG_RET( 2, "ssl->f_send", ret );

+        if( ret > ssl->out_left )
+        {
+            MBEDTLS_SSL_DEBUG_MSG( 1, ( "f_send returned > out_left!" ) );
+            return( MBEDTLS_ERR_SSL_INTERNAL_ERROR );
+        }
+
         if( ret <= 0 )
             return( ret );

         ssl->out_left -= ret;
     }
```

https://github.com/JuliaWeb/MbedTLS.jl/issues/116

**Comment by RonEld** [comment]
Hi @samoconnor Thank you for reporting this!
Is this a real use case? Did you encounter a case where the `f_send` bio callback returned a value larger than  `ssl->out_left`? According to the issue you referenced, the root cause for your issue was a concurrency problem and adding a mutex fixed your issue. Am I right?
I order to take your fix suggestion, we will need to ask you to sign a Contributor's License Agreement (CLA) as described [here](https://github.com/ARMmbed/mbedtls#contributing)

Thank you in advance!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1962

**Comment by samoconnor** [comment]
>  Did you encounter a case where the f_send bio callback returned a value larger than ssl->out_left?
No, I encountered a problem where f_send was passed a "negative" (huge positive) value for length.

I noticed the problem described in this issue while reviewing the code to try to understand how I was getting negative length values. The problem is that values are not bounds-checked at a module interface:
 - There should  be a wrap-around check before subtracting a value obtained from an external module (the callback) from an unsigned value.
 - There should also be a check that ssl->out_left is not larger than buf before f_send is called.

> According to the issue you referenced, the root cause for your issue was a concurrency problem and adding a mutex fixed your issue. Am I right?

The root cause is not concurrency in the sense of multiple contexts operating on the data structure at the same time. The Julia program is signle-threaded. Neither does the problem seem to be direct reentrance. i.e. I don't believe the same mbedtls function was entered twice. The problem seems to be that during the f_send callback the Julia program called back into a different mbedtls function to receive data. It seems that the send and receive operations share a data structure, and that it gets corrupted if a receive operation is attempted inside the f_send callback. The work-around in MbedTLS.jl is to add a per-connection lock around all access to mbedtls functions.

> I order to take your fix suggestion, we will need to ask you to sign a Contributor's License Agreement (CLA) as described
The suggested "check like this..." above is not intended as a copyrighted "contribution", it is simply intended to illustrate the point. Please make whatever change you feel is appropriate for your library to address the issue.

**Comment by RonEld** [comment]
Hi @samoconnor Thank you for your clarifications, we will work on this issue.

>It seems that the send and receive operations share a data structure, and that it gets corrupted if a receive operation is attempted inside the f_send callback.

In this case, I believe the root cause was in the platforms glue layer, so the priority of this issue should be accordingly, nonetheless, we will look into this.

Im my previous comment, it was a typo: "I order to take your fix..." -> "In order to take your fix.." . I didn't order you anything:)

Thanks again for raising this issue!

**Comment by hanno-arm** [comment]
Thanks @samoconnor for reporting this. I second @RonEld's view that this an issue with the underlying transport, whose `recv` and `send` functions are not supposed to read/write (or report to have done so) more than what the user has requested. Nonetheless, for sake of containment of flaws it makes sense to add the suggested check, not only in the writing function but also in the [receiving function `ssl_fetch_input`](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L2399).
