### ISSUE TITLE
Can I configure the keys for ticket if using the default ticket functions?

### ISSUE THREAD

**Issue by WuBingzheng** [ARMmbed/mbedtls#1248]
### Description
- Type: Question
- Priority: Minor

Can I configure the keys for ticket if using the default ticket functions?

From the example of `programs/ssl/ssl_server2.c`, it seems that I can only configure session-ticket-timeout, while the encrypt/decrypt keys are generated randomly in `mbedtls_ssl_ticket_setup()`:

        if( ( ret = mbedtls_ssl_ticket_setup( &ticket_ctx,
                        mbedtls_ctr_drbg_random, &ctr_drbg,
                        MBEDTLS_CIPHER_AES_256_GCM,
                        opt.ticket_timeout ) ) != 0 )
        {
            mbedtls_printf( " failed\n  ! mbedtls_ssl_ticket_setup returned %d\n\n", ret );
            goto exit;
        }

        mbedtls_ssl_conf_session_tickets_cb( &conf,
                mbedtls_ssl_ticket_write,
                mbedtls_ssl_ticket_parse,
                &ticket_ctx );

**Comment by RonEld** [comment]
Hi @WuBingzheng Thank you for your query.
Quoting [RFC5077](https://tools.ietf.org/html/rfc5077#page-13):
>The keys should be generated securely following the randomness
      recommendations in [RFC4086].

[and](https://tools.ietf.org/html/rfc5077#section-4):
>One possibility is to generate new
   random keys and key_name every time the server is started.

The keys should be random, for security reasons. For your **debug** purposes only, you may consider modifying [`ssl_ticket_gen_key`](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_ticket.c#L64) to output constant keys, **but be careful not to ship with this flawed code!**

**Comment by WuBingzheng** [comment]
I need to configure the key not for debugging, but for production.
For a heavy-load service, the server program can be multi-processes(like nginx), or even deployed at multiple machines (as a cluster). All the processes should share the same key, or the session will not resume unless it get into the same process in the same machine.
I know random generating is better, but it's useless for multi-processes program.
Configuring is not safe, but since we have to configure the private key for certificate, so adding another secret key should not make thing worse.

**Comment by WuBingzheng** [comment]
Is mbedtls designed for embed system specially, but not for generic purpose?
In addition to this one, I found that mbedtls does not care about the performance [here](https://github.com/ARMmbed/mbedtls/issues/1214) and [here](https://github.com/ARMmbed/mbedtls/issues/1189).

I like to use mbedtls because of its clear API. But now I think maybe it's not suitable for a service program.

**Comment by RonEld** [comment]
Hi @WuBingzheng As you can see from the code, the keys are random generated only on setup, and when the ticket lifetime has expired.  
If you share the same memory between the processes, you *should* be able to use same ticket between them, and generating a new key only when expired. 
However, as you mentioned, Mbed TLS is mostly aimed for embedded systems, but it should work on service programs as well.

**Comment by RonEld** [comment]
Closing as I believe this question was addressed. If you think this question is still awaiting an answer, please reopen.
