### ISSUE TITLE
key_app_writer writes wrong public key in der format

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1257]
### Description
- Type: Bug
- Priority: Minor
Reported in the [support forum](https://tls.mbed.org/discussions/generic/mbedtls_pk_parse_public_key-returned-0x3d62) by Aryeh R.
---------------------------------------------------------------
## Bug

**OS**  
linux|windows

**mbed TLS build:**  
Version: development 
OS version: Ubuntu16.04 and windows10 (irrelevant in this bug) 

**Expected behavior**   
parsing the created public key should pass
**Actual behavior**  
parsing the created `der` public key fails with error -0x3d62
**Steps to reproduce**  
- Generate a key pair
- use `key_app_writer` to write a public key in der format
- try parsing the public key
~~~
./gen_key type=rsa rsa_keysize=4096 filename=rsa_4096_private.der format=der
./key_app_writer mode=private filename=rsa_4096_private.der output_mode=public output_format=der output_file=rsa_4096_public.der
./key_app mode=public filename=rsa_4096_public.der
~~~
I believe the bug is [here](https://github.com/ARMmbed/mbedtls/blob/development/programs/pkey/key_app_writer.c#L131)
The `- 1` is redundant. It adds a leading zero byte, which causes a failure in the ASN1 parsing, as it is not the expected tag.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1991
