### ISSUE TITLE
3 Tests in testsuite "version" fail due to missing dependency checks

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1299]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.6.0

3 / 5 tests in the version testsuite fail when MBEDTLS_VERSION_FEATURES is disabled. They should "depend on" that compile time option and thus be skipped if not present.

**Comment by RonEld** [comment]
@TrinityTonic Thank you for reporting this. I believe you are correct in your assessment

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2046
