### ISSUE TITLE
Unknown compile-time option in ecp_internal.h

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1301]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Minor
---------------------------------------------------------------
## Bug

When alternate ECC implementation is enabled (`MBEDTLS_ECP_INTERNAL_ALT`) in ecp_internal.h, some functions might be included depending on whether they are explicitly set in the config file. ecp_internal.h itself, checks if `ECP_SHORTWEIERSTRASS` is defined. However, `ECP_SHORTWEIERSTRASS` is only defined in ecp.c and never reaches ecp_internal.h which means that these functions will have missing declarations.

mbed TLS build:**  
Version: 2.6.0

ECP_SHORTWEIERSTRASS

**Expected behavior**   
Enable MBEDTLS_ECP_INTERNAL_ALT and for example MBEDTLS_ECP_RANDOMIZE_JAC_ALT while at least one shortweierstrass curve is enabled. The declaration for mbedtls_internal_ecp_randomize_jac() should become visible. 

**Actual behavior**  
mbedtls_internal_ecp_randomize_jac() remains invisible as ECP_SHORTWEISTRASS is never defined for ecp_internal.h

**Comment by RonEld** [comment]
@TrinityTonic Thank you for reporting this issue. I believe this issue is a duplicate of https://github.com/ARMmbed/mbedtls/issues/1147

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2532

**Comment by Patater** [comment]
Closing as duplicate of #1147
