### ISSUE TITLE
Server unaivalable

### ISSUE THREAD

**Issue by TimonSchokker** [ARMmbed/mbedtls#1309]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
ESP32

**mbed TLS build:**  
Version: 1.2 or git commit id  

I am using an ESP32 development board with mbedTLS 1.2

When i am succesfully connected to my TLS server everything is working like it is suppose to do.
But when i disable my Ethernet cable from my server, thus the server becomes unavailable, the ESP32 and mbedTLS still think its connected and they keep reading and keep on sending data.

If i reconnect the cable and thus restart the Server then mbedTLS says, the connection is reset by peer and i have to recconnect.
The reconnect is working fine and everything works like before.

But i can't figure out why mbedTLS still thinks its connected to the server even when the ethernet is out and the server is unavailable to ping

**Comment by RonEld** [comment]
Hi @TimonSchokker Please note that Mbed TLS version 1.2 is no longer supported, and suggest you upgrade your version to latest Mbed TLS version.
Please follow the following KB articles:
https://tls.mbed.org/kb/how-to/migrate-from-polarssl-1.2-to-polarssl-1.3
https://tls.mbed.org/kb/how-to/upgrade-2.0

In addition, please supply more information, such as whether you are using DTLS or TLS, and logs.
Please also supply the OS you are using. (RTOS? Mbed OS? )

**Comment by RonEld** [comment]
Since no further correspondence has been made for some time now, closing this issue.
Please reopen this issue, if there is followup for this issue.
