### ISSUE TITLE
Key Interop issue with OpenSSL

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1339]
### Description
- Type: Bug 
- Priority: Blocker

---------------------------------------------------------------
## Bug

Described by @ordex in PR #1219:

> only SHA1 is in HMAC for PBKDF2 in PKCS5. This means that keys encrypted and authenticated using another algorithm of the SHA family cannot be decrypted [by Mbed TLS].
> 
> This deficiency has become particularly incumbent now that PKIs created with openssl-1.1 are encrypting keys using hmacSHA256.

**Peer device TLS stack and version**  
OpenSSL

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2081
