### ISSUE TITLE
Benchmark program should obey message-digest return codes

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1342]
__Issue:__ The benchmark program [programs/test/benchmark.c](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c), specifically the macro [TIME_AND_TSC](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c#L110), doesn't check the newly introduced error codes from the message-digest functions. If alternative message-digest implementations fail, the benchmark application won't notice and return inappropriate running times.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2080

**Comment by RonEld** [comment]
This issue was fixed in https://github.com/ARMmbed/mbedtls/commit/51d7cfe026fa3f33d86a80d27ea9013830f33992

Still exists in `mbedtls-2.7` though

**Comment by RonEld** [comment]
fixed with #1617
