### ISSUE TITLE
2.6.1 download is missing

### ISSUE THREAD

**Issue by ilovezfs** [ARMmbed/mbedtls#1350]
There is a GitHub tag for 2.6.1 but no download at https://tls.mbed.org/download/mbedtls-2.6.1-apache.tgz

What is the status of 2.6.1? Is it a real release?

**Comment by sbutcher-arm** [comment]
Hi @ilovezfs,

If you have a look at Mbed TLS 2.6.1, as you can see [from this diff](https://github.com/ARMmbed/mbedtls/compare/mbedtls-2.6.0...mbedtls-2.6.1),  it contained a single fix to do with renegotiation. The release was done for Mbed, but we didn't consider this to merit a full release on the Mbed TLS website as most customers would be unlikely to encounter the issue. You only encounter the issue if SHA-1 is disabled which isn't the default configuration and limits interoperability.

Hope this answers the question! Assuming this is sufficient, I'm closing the issue, but feel free to reopen it or follow up with more questions.
