### ISSUE TITLE
certificate verification fails when using suiteb configuration and preset

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1351]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Major 
raised by daniel in the [support forum](https://tls.mbed.org/discussions/generic/certificate-ec-public-key-algorithms)
---------------------------------------------------------------
## Bug

**OS**  
Linux

**mbed TLS build:**  
Version: development branch
OS version: Ubuntu 16.04
Configuration: config_suiteb.h with additional `MBEDTLS_FS_IO`, `MBEDTLS_PLATFORM_C`, `MBEDTLS_DEBUG_C`

Version:  

**Expected behavior**   
certificate verification succeeds
**Actual behavior**  
certificate verification fails on bad PK algorithm
**Steps to reproduce**  

run ssl_server
run mini_client with `MBEDTLS_SSL_PRESET_SUITEB` to use suiteb profile.

Reason for failure is because certificate has in its `Public Key Algorithm:` value of `id-ecPublicKey`. The returned pk alg from [oid parser](https://github.com/ARMmbed/mbedtls/blob/development/library/oid.c#L430) is `MBEDTLS_PK_ECKEY`, but [`mbedtls_x509_crt_profile_suiteb`](https://github.com/ARMmbed/mbedtls/blob/development/library/x509_crt.c#L136) only allows `MBEDTLS_PK_ECDSA ` as the pk algorithm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2074
