### ISSUE TITLE
benchmark.c is using disallowed C99 features

### ISSUE THREAD

**Issue by mrpippy** [ARMmbed/mbedtls#1353]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Mac OS 9

**mbed TLS build:**  
Version: 2.7.0
Compiler and options:  Metrowerks CodeWarrior Pro 8
Additional environment information:  

When compiling `programs/test/benchmark.c` in C89 mode, I get the following errors:
```
Error   : illegal constant expression
benchmark.c line 670   const unsigned char *dhm_P[] = { dhm_P_2048, dhm_P_3072 };

Error   : illegal constant expression
benchmark.c line 674   const unsigned char *dhm_G[] = { dhm_G_2048, dhm_G_3072 };
```

I believe these two lines (added in b953921a4e1af098aabbf748a13f7f2f731280ca) are not C89 compliant, causing the errors.

If I use the same compiler and enable C99 extensions, the file compiles without errors. I am also able to compile the rest of mbed TLS without needing to enable C99.

**Comment by RonEld** [comment]
@mrpippy Thank you for reporting this.
Did you mean in your subject "benchmark.c is using disallowed **C89** features" ?
Could you describe why you need C89 compliance?

**Comment by mrpippy** [comment]
No, in this case the code in benchmark.c is initializing the array with non-constant expressions. This is allowed in C++, C99, and GNU C, but not in C89. It is also not a C99 feature listed as being used in the [coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards).

clang will throw a warning for this when operating in C89 mode:
```
$ cat test.c
int main()
{
	const unsigned char test[] = "abcdef";
	const unsigned char *testarr[] = {test};
	return 0;
}
$ clang -ansi -pedantic -o test test.c
test.c:5:36: warning: initializer for aggregate is not a compile-time constant [-Wc99-extensions]
        const unsigned char *testarr[] = {test};
                                          ^~~~
1 warning generated.
```
I'm using mbed TLS on an old platform (classic Mac OS) where C99 compilers were not common, and the rest of the library builds without needing C99 extensions. Also as mentioned above, I think this violates the project's coding standards.

An easy fix for the issue is to define `dhm_P_2048` and the other arrays as `static`, this makes their addresses constant expressions. Should I create a pull request for this?

**Comment by sbutcher-arm** [comment]
Hi @mrpippy,

We currently target C99 and don't actively support C89. We don't have any C89 builds in our test system, nor any targets that need C89. So strictly speaking this isn't a bug for us, but that's not very helpful to you.

If you submit a PR, I can't imagine it causing any problems for us, so I think we can merge it. What we can't really do is fix it ourselves when there are so many other bugs to fix and when this isn't strictly a bug for us.

So submit something and if you provide a CLA and it meets our standards, we'll welcome the fix, but I can't promise we won't break your target in the future as it's not a target we test.

Hope this is helpful.
