### ISSUE TITLE
Incorrect return value when using server with disabled TLS 1.0 and client using TLS 1.0

### ISSUE THREAD

**Issue by mjansta** [ARMmbed/mbedtls#1357]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

Invalid return value when TLS 1 and TLS 1.1 are not compiled in (undefined) and a client tries to connect to a mbedTLS server using TLS 1.0.

**mbed TLS build:**  
Version: 2.6.0
Configuration: default

**Peer device TLS stack and version**  
mbed TLS

**Expected behavior**  
Should return -28288 - SSL - Handshake protocol not within min/max boundaries

**Actual behavior**  
Server returns -27648 - SSL - Internal error

**Steps to reproduce**  

Build the ssl_server example with the definition MBEDTLS_SSL_PROTO_TLS1 and MBEDTLS_SSL_PROTO_TLS1_1 undefined, i.e. only MBEDTLS_SSL_PROTO_TLS1_2 is defined.

Build the ssl_client2 example with TLS 1.0 support.

Use the client to connect to the server using TLS 1.0.

See the following output:

SERVER
```
> ssl_server.exe

  . Loading the server cert. and key... ok
  . Bind on https://localhost:4433/ ... ok
  . Seeding the random number generator... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -27648

Last error was: -27648 - SSL - Internal error (eg, unexpected failure in lower-level module)
```

CLIENT
```
> ssl_client2.exe force_version=tls1

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x2700
    Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2092
