### ISSUE TITLE
Redundant declaration of mbedtls_ssl_list_ciphersuites

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1359]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.7.0 (although also noticed on earlier versions)

...\Components\mbedTLS\mbedtls-2.7.0\include/mbedtls/ssl.h:937:12: error: redundant redeclaration of 'mbedtls_ssl_list_ciphersuites'
...\Components\mbedTLS\mbedtls-2.7.0\include/mbedtls/ssl_ciphersuites.h:353:12: note: previous declaration of 'mbedtls_ssl_list_ciphersuites' was here

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2091
