### ISSUE TITLE
website: Unclear content on "mbed TLS Core Features" page (and other typos in the docs on site)

### ISSUE THREAD

**Issue by pfalcon** [ARMmbed/mbedtls#1361]
### Description
- Type: Website Issue
- Priority: Minor

---------------------------------------------------------------
## Website Issue

At https://tls.mbed.org/core-features, under "Ensuring code quality", below reassuring notice "You want to use high-quality code that is bug-free. So do we!", there's a sentence like:

> Because most of the world uses OpenSSL as a basis, we think it's no more that logical to ensure compatibility.

I'm not sure I can understand the 2nd part of the sentence. I'm not a native English speaker, so there's always a chance of me missing something, but the phrase doesn't look like written in literature English to me. Perhaps, the 2nd part should read as "... we think it's more than logical to ensure compatibility." That still not a stellar phrase stylistically, but at least grammar makes sense.

One of the next sentences is:

> In addition we test against GnuTLS and we test SSL options, resumptions and extensions for correctness.

This one, it's not very clear what "resumptions" are meant there. No, a TLS expert could understand that sentence, likely "SSL session resumptions" were meant there. But a more layman reader might be perplexed - while "SSL options" and "SSL extensions" are describe in this document previously, word "resumption" doesn't appear anywhere else. A suggestion would be to rewrite the sentence as e.g.:

"In addition we test against GnuTLS, and we test SSL options, session resumption operations, and extensions for correctness."  

As the initial quote from this doc ("You want to use high-quality code that is bug-free. So do we!") says, it's important to have the high-quality code. But not less it's important to have high-quality documentation. Confusing documentation for security code correlates with incorrect usage of it, which undermines its security properties.

Thanks.

(To clarify, this is submitted as part of Linaro engineer's work on (further) integration of mbedTLS into Zephyr RTOS, specifically, assessing how easy it is to perform correct mbedTLS configuration based on the available documentation.)

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into it.

**Comment by pfalcon** [comment]
On https://tls.mbed.org/kb/development/thread-safety-and-multi-threading , there's an occurrence of "MBEDTS_THREADING_PTHREAD" (missing "L" in "MBEDTS").

**Comment by RonEld** [comment]
Hi @pfalcon Thank you for informing us on the typo! I have fixed the typo in the article.
Thanks again!

**Comment by pfalcon** [comment]
@RonEld : Thanks! Closing then.

**Comment by RonEld** [comment]
@pfalcon I fixed the typo in the article you mentioned in your second comment. I didn't fix the site page where the original issue was raised on. If you think that it still needs attention, please reopen

**Comment by pfalcon** [comment]
Well, if you guys think that such reports are useful, sure. (Myself, I think that mbedTLS is important piece of the modern IoT infrastructure, and it's worth polishing it from different sides.) Reopening, thanks.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2531
