### ISSUE TITLE
Compilation fails when PLATFORM_C undefined and HAVE_TIME defined

### ISSUE THREAD

**Issue by rps102** [ARMmbed/mbedtls#1366]
When MBEDTLS_PLATFORM_C is undefined (ie. we want to use the libc functions directly) and MBEDTLS_HAVE_TIME is defined (ie. the libc implementation does have time functions) the build fails with a duplicate typedef error.

This is because debug.c/error.c/net_sockets.c have local defines of the form
   #define mbedtls_time_t time_t
and that error.c and net_sockets.c include "ssl.h" which itself then includes "platform_time.h".

This is a problem because "platform_time.h" does:
   #include <time.h>
   typedef time_t mbedtls_time_t;
which after preprocessor macro expansion becomes:
   typedef time_t time_t;
which is an error.

Replacing the 3x defines to instead #include "mbedtls/platform_time.h" allows the build to complete (since that header has the appropriate checks on MBEDTLS_PLATFORM_C inside it, though I've not surveyed whether that causes some other problem given the number of possible valid switch combinations.
 
mbedTLS 2.6.0 (though checking the latest sources in github shows them unchanged.

**Comment by sbutcher-arm** [comment]
Thanks for raising this! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2089
