### ISSUE TITLE
Cast warnings from blowfish.c

### ISSUE THREAD

**Issue by rps102** [ARMmbed/mbedtls#1367]
The arrays P[] and S[] in this source file are arrays of type uint32_t but the constants used to initialise them are qualified with only 'L' (signed long) rather than 'uL' (unsigned long), resulting in 1000+ warnings about implicit type cast.
 
mbedTLS 2.6.0 (though checking the latest sources in github shows them unchanged.

**Comment by sbutcher-arm** [comment]
Thanks for raising the issue! What compiler are you using?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2088

**Comment by rps102** [comment]
The compiler is IAR 5.51.3, though it was running it through MISRA 2004 that highlighted the issue (clause 6.10.6, implicit type conversion).
