### ISSUE TITLE
question about gcm add and update payload

### ISSUE THREAD

**Issue by Summer-ARM** [ARMmbed/mbedtls#1369]
### Description
- Type: Question

---------------------------------------------------------------

Hi guys,
My team is integrating mbedtls into OPTEE, and I am in charge of gcm.
There is something that I want to confirm from you:
1. regarding to add
https://github.com/ARMmbed/mbedtls/blob/6d6c7982ceab2e7f28c9c0e76ce4fd8bb59c3fb2/library/gcm.c#L291-L292
in mbedtls_gcm_starts(), always do the above operations.
so does it mean mbedtls gcm only support add additional data in integrity，we can't not split the additional data and call mbedtls_gcm_starts() several times to add additional data?

2. regarding to update payload
https://github.com/ARMmbed/mbedtls/blob/6d6c7982ceab2e7f28c9c0e76ce4fd8bb59c3fb2/library/gcm.c#L377-L406
we can call mbedtls_gcm_update() several times to update the payload, but the length of each payload must be multiples of 16 bytes except the last payload, is my understanding correct?

Thanks in advance,
Summer

**Comment by RonEld** [comment]
Hi @Summer-ARM GCM, as an AEAD algorithm, accepts only one additional data, for the integrity check. `mbedtls_gcm_starts` , as its name suggests, is used to start the operation, and it should be called once.

Regarding your second question, yes, every update should hav e a length of a multiple of 16 bytes, except the last one. As mentioned in the file [documentation](https://tls.mbed.org/api/gcm_8h.html#a922addfa5c93fa08b6e9da134d5d8f2d):
>Encrypts/decrypts using the given GCM context. Expects input to be a multiple of 16 bytes! Only the last call before mbedtls_gcm_finish() can be less than 16 bytes!

**Comment by Summer-ARM** [comment]
Hi @RonEld
Thanks for your confirm and nice explaination.

**Comment by Summer-ARM** [comment]
Hi @RonEld 
Just searched some website and they treat AES-GCM as some `stream-cipher` 
As a stream cipher, like CTR, I think it means the user can pass any length input data to call `mbedtls_gcm_update()` and immediately get the results, no need to expect input to be a multiple of 16 bytes. 
In OPTEE, internal gcm and tomcrypt gcm both treat gcm as a stream cipher and don't have the limitation of the input length.
Is this mbedtls need to improve or there are something I misunderstand?

**Comment by RonEld** [comment]
Hi @Summer-ARM I don't know what sites you searched, nut GCM is not a stream cipher. GCM is an AEAD algorithm, which uses CTR internally. As an AEAD algorithm, the only relevant result is the final encrypted \ decrypted data, and the generated tag.
Theoretically, GCM update can be implemented in a way that it can get inputs that are not a multiples of 16 bytes, but there is no point in that. You can, if you want, hold an accumulative buffer in your context, which will hold the residue.
