### ISSUE TITLE
Compiling for a kernel module

### ISSUE THREAD

**Issue by mtahmed** [ARMmbed/mbedtls#137]
I was trying to compile parts of polarssl as a library and then link it into a kernel module but it seems that I am unable to because some files include `stdio.h`, `string.h` and other such standard library headers that are not available in the kernel space (and not needed by me either). E.g. `bignum.h` includes it. I also noticed that all the IO stuff is enclosed in `#if defined(POLARSSL_FS_IO)` so I was wondering if this should be as well?

Some way to tell the build system that we are building for kernel and to provide our own (kernel) versions of memset etc. would be nice.

Something like the following in `config.h` might do the trick:

``` c
#define POLARSSL_TYPES_H_INCLUDE <linux/types.h>
#define POLARSSL_STRING_H_INCLUDE <linux/string.h>
```

Or maybe have a per-function/feature include:

``` c
#define POLARSSL_TYPES_INCLUDE <linux/types.h>
#define POLARSSL_MEMSET_INCLUDE <linux/string.h>
```

And then in code, instead of:

``` c
#include <string.h>
```

we can have:

``` c
#include POLARSSL_STRING_H_INCLUDE
```

Or:

``` c
#include POLARSSL_MEMSET_INCLUDE
#include POLARSSL_MEMCPY_INCLUDE
#include POLARSSL_TYPES_INCLUDE
```

etc. ...

Thoughts?

**Comment by KimSangpil** [comment]
@mtahmed Can I ask about the issue that you have posted 17 Nov 2014?
I'm looking for code to solve unknown symbol __udivti3 too...
I'm very appreciated if you help me to solve it.

**Comment by mtahmed** [comment]
@KimSangpil Sure.

The problem is that the those symbols are provided libgcc which is not available when compiling for kernel. *Assuming* you are compiling for kernel, you can simply disable `POLARSSL_HAVE_UDBL` by `#if 0`ing any where they define `HAVE_UDBL`. For example in bignum.h, `#if 0` the following code like so:

```c
#if 0
       typedef unsigned int t_udbl __attribute__((mode(TI)));
       #define POLARSSL_HAVE_UDBL
#endif
```

There's no way around it that I could find if you are compiling for kernel.

**Comment by mpg** [comment]
The correct way to disable the use of `__attribute__((mode(TI)))` is to define `MBEDTLS_HAVE_INT32` and to disable `MBEDTLS_HAVE_ASM`.

Regarding the other issues, you'll find that using macros instead of function pointers for functions that are abstracted in platform.[hc] is now supported. (It was introduced in the 1.3.11.)

Regarding other functions, would you be interested in submitting a patch that would allow to define eg `MBEDTLS_PLATFORM_STRING_H` in config.h and then use that in the relevant files if it is defined?

**Comment by milabs** [comment]
Hello,

I've just started porting mbedTLS to Linux kernel:
https://github.com/milabs/mbedtls-lk

At the moment, all the self tests were passed (except the ENTROPY test).

**Comment by pjbakker** [comment]
@milabs One issue I see is that you are declaring this module as GPL, but are using an Apache licensed mbed TLS library.

**Comment by milabs** [comment]
@pjbakker What kind of license should I use wrt Linux kernel (http://lxr.free-electrons.com/source/include/linux/module.h?v=4.1#L97)?

**Comment by milabs** [comment]
@pjbakker Update license to GPLv2

**Comment by pjbakker** [comment]
Still.. The code you reference in your 'submodule' is Apache 2.0 licensed, which is incompatible with the Linux kernel.

**Comment by milabs** [comment]
@pjbakker Ok, but what does it mean "mbed TLS is available as open source under the Apache 2.0 license, the GPL 2.0 license or under an mbed partnership. The Apache 2.0 license enables you to use mbed TLS in both open source and closed source projects"?

**Comment by pjbakker** [comment]
It's available as a GPL package in the download archive on the website. The source on github is Apache licensed.

-------- Original message --------

**Comment by milabs** [comment]
@pjbakker Ok, I'll fix it.

**Comment by daverodgman** [comment]
Closing - building inside the kernel isn't a use-case we actively support. If there are specific issues that the platform layer doesn't cover that are still causing problems please raise them.
