### ISSUE TITLE
File pem.h does not include "confg.h"

### ISSUE THREAD

**Issue by Dmitry-Frantsev** [ARMmbed/mbedtls#1371]
### Description
- Type: Bug 
- Priority:  Minor

---------------------------------------------------------------
## Bug
File pem.h does not include "confg.h"
It is neccessary to add such code

#if !defined(MBEDTLS_CONFIG_FILE)
#include "config.h"
#else
#include MBEDTLS_CONFIG_FILE
#endif

**Comment by RonEld** [comment]
Hi @Dmitry-Frantsev Thank you for reporting this issue!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2096
