### ISSUE TITLE
Add support for generating self-signed certificates

### ISSUE THREAD

**Issue by ToiletCommander** [ARMmbed/mbedtls#1376]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor
---------------------------------------------------------------------------------
### Feature
- I am now trying to build a software to help encrypt data flows.  
- I am using SSL obfuscations to pretend those internet data flows as "HTTPS Request", so I am using mbedtls as my client and server base.  
- I would like mbedtls to add feature support for generating self-signed certificates, so that the firewalls will not be able to block any specific certificates since self-signed certs varies from its CA name.

**Comment by RonEld** [comment]
Hi @ToiletCommander Mbed TLS supports generation of self signed certificates
Please follow https://tls.mbed.org/kb/how-to/generate-a-self-signed-certificate to learn how to do that.

**Comment by ToiletCommander** [comment]
Well, is there an API for mbedtls to generate a self-assigned cert, or I have to use the command line tool?

**Comment by RonEld** [comment]
Hi @ToiletCommander there isn't such an API.
Note that this isn't a command line tool, but a code for your reference.
