### ISSUE TITLE
Definitions of deprecated `mbedtls_aes_xxcrypt` not guarded by `! MBEDTLS_DEPRECATED_REMOVED`

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1388]
__Issue:__ The functions `mbedtls_aes_decrypt` and `mbedtls_aes_encrypt` are deprecated, but their definitions in `aes.c` are not guarded by `! MBEDTLS_DEPRECATED_REMOVED`. This leads to compilation warnings, and hence to a build failure when using CMake in `ASanDbg` build type.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2103
