### ISSUE TITLE
0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbedtls#139]
ssl client connect error:

```
./ssl_client2 server_name=openapi.baidu.com server_port=443 ca_file=certdata.txt  debug_level=1
```

certdata.txt

```
-----BEGIN CERTIFICATE-----
MIIE0zCCA7ugAwIBAgIQGNrRniZ96LtKIVjNzGs7SjANBgkqhkiG9w0BAQUFADCByjELMAkGA1UE
BhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBUcnVzdCBO
ZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVk
IHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRp
ZmljYXRpb24gQXV0aG9yaXR5IC0gRzUwHhcNMDYxMTA4MDAwMDAwWhcNMzYwNzE2MjM1OTU5WjCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2ln
biBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2lnbiwgSW5jLiAtIEZvciBh
dXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQCvJAgIKXo1nmAMqudLO07cfLw8RRy7K+D+KQL5VwijZIUVJ/XxrcgxiV0i6CqqpkKz
j/i5Vbext0uz/o9+B1fs70PbZmIVYc9gDaTY3vjgw2IIPVQT60nKWVSFJuUrjxuf6/WhkcIzSdhD
Y2pSS9KP6HBRTdGJaXvHcPaz3BJ023tdS1bTlr8Vd6Gw9KIl8q8ckmcY5fQGBO+QueQA5N06tRn/
Arr0PO7gi+s3i+z016zy9vA9r911kTMZHRxAy3QkGSGT2RT+rCpSx4/VBEnkjWNHiDxpg8v+R70r
fk/Fla4OndTRQ8Bnc+MUCH7lP59zuDMKz10/NIeWiu5T6CUVAgMBAAGjgbIwga8wDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwbQYIKwYBBQUHAQwEYTBfoV2gWzBZMFcwVRYJaW1hZ2Uv
Z2lmMCEwHzAHBgUrDgMCGgQUj+XTGoasjY5rw8+AatRIGCx7GS4wJRYjaHR0cDovL2xvZ28udmVy
aXNpZ24uY29tL3ZzbG9nby5naWYwHQYDVR0OBBYEFH/TZafC3ey78DAJ80M5+gKvMzEzMA0GCSqG
SIb3DQEBBQUAA4IBAQCTJEowX2LP2BqYLz3q3JktvXf2pXkiOOzEp6B4Eq1iDkVwZMXnl2YtmAl+
X6/WzChl8gGqCBpH3vn5fJJaCGkgDdk+bW48DW7Y5gaRQBi5+MHt39tBquCWIMnNZBU4gcmU7qKE
KQsTb47bDN0lAtukixlE0kF6BWlKWE9gyn6CagsCqiUXObXbf+eEZSqVir2G3l6BFoMtEMze/aiC
Km0oHw0LxOXnGiYZ4fQRbxC1lfznQgUy286dUV4otp6F01vvpX1FQHKOtw5rDgb7MzVIcbidJ4vE
ZV8NhnacRHr2lVz2XTIIM6RUthg/aFzyQkqFOFSDX9HoLPKsEdao7WNq
-----END CERTIFICATE-----
```

result:

```
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok
  . Connecting to tcp/openapi.baidu.com/443 ... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...
Verify requested for (Depth 2):
cert. version     : 3
serial number     : 25:0C:E8:E0:30:61:2E:9F:2B:89:F7:05:4D:7C:F8:FD
issuer name       : C=US, O=VeriSign, Inc., OU=Class 3 Public Primary Certification Authority
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2021-11-07 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication, Code Signing, ???, ???
  ! self-signed or not signed by a trusted CA

Verify requested for (Depth 1):
cert. version     : 3
serial number     : 64:1B:E8:20:CE:02:08:13:F3:2D:4D:2D:95:D6:7E:67
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=Terms of use at https://www.verisign.com/rpa (c)10, CN=VeriSign Class 3 International Server CA - G3
issued  on        : 2010-02-08 00:00:00
expires on        : 2020-02-07 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  :
key usage         : Key Cert Sign, CRL Sign
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication, ???, ???
  This certificate has no flags

Verify requested for (Depth 0):
cert. version     : 3
serial number     : 2D:73:DA:EE:3D:44:A1:DD:F6:65:13:18:39:20:58:00
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=Terms of use at https://www.verisign.com/rpa (c)10, CN=VeriSign Class 3 International Server CA - G3
subject name      : C=CN, ST=Beijing, L=Beijing, O=BeiJing Baidu Netcom Science Technology Co., Ltd, OU=service operation department, OU=Organization and domain(s) authenticated by iTrus China, CN=openapi.baidu.com
issued  on        : 2014-10-31 00:00:00
expires on        : 2015-11-02 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : openapi.baidu.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication, ???
  This certificate has no flags
 failed
  ! ssl_handshake returned -0x2700
    Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
```

**Comment by FarhanAhmad** [comment]
@pjbakker whats 'top' ? Didn't understand what you meant.

**Comment by pjbakker** [comment]
@FarhanAhmad A certificate chain runs all the way from a child certificate to the 'top' (The CA certificate).
In case of the issue above, the CA Chain provided to the application contained the certificate up to (but not including) the 'top' certificate. Without that top certificate, the chain could not be verified in full.

That said. I believe the behaviour of verification has been modified in more recent version, so you might now be able to provide a 'middle' certificate as trusted instead. Maybe @sbutcher-arm can comment on that?

**Comment by PravallikaKG** [comment]
@pjbakker I am facing the similar error('**-9984 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed**') at 'mbedtls_ssl_handshake' call.
I am new to mbed tls, i dont know much fundamentals of it. Following is my scenario, please tell me if i am doing anything wrong.

1) I have my own ca.cert, server.cert, client.cert, server.key,client.key and ca.key files. 
Following is my piece of code at server side and client side:

server partial code:
-----------------------------
``
    int ret = mbedtls_x509_crt_parse_file(&cacert, ca_file);
    if (ret != 0) {
        mbedtls_printf( " failed\n  !  mbedtls_x509_crt_parse_file returned %d\n\n", ret );
        goto exit;
    }

    ret = mbedtls_x509_crt_parse_file(&srvcert, server_file);
    if (ret != 0) {
        mbedtls_printf( " failed\n  !  mbedtls_x509_crt_parse_file returned %d\n\n", ret );
        goto exit;
    }

    ret = mbedtls_pk_parse_keyfile(&pkey,serverkey_file,password);
    if (ret != 0) {
        mbedtls_printf( " failed\n  !  mbedtls_pk_parse_keyfile server returned %d\n\n", ret );
        goto exit;
    }
   ..............
   ..............
    
    **mbedtls_ssl_conf_ca_chain( &conf, &cacert, NULL );
    if( ( ret = mbedtls_ssl_conf_own_cert( &conf, &srvcert, &pkey ) ) != 0 )
    {
        mbedtls_printf( " failed\n  ! mbedtls_ssl_conf_own_cert returned %d\n\n", ret );
        goto exit;
    }**

    if( ( ret = mbedtls_ssl_setup( &ssl, &conf ) ) != 0 )
    {
        mbedtls_printf( " failed\n  ! mbedtls_ssl_setup returned %d\n\n", ret );
        goto exit;
    }
    ........................
    .....................
    // Performing the SSL/TLS handshake...
    **while( ( ret = mbedtls_ssl_handshake( &ssl ) ) != 0 )
    {
        if( ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE )
        {
            mbedtls_printf( " failed\n  ! mbedtls_ssl_handshake returned %d\n\n", ret );
            goto reset;
        }
    }**
``

Client side code:
-----------------------

``
    	ret = mbedtls_x509_crt_parse_file(&cd->ca_cert, ca_cert_filename);
    	if (ret != 0) {
        	mbedtls_printf( " failed\n  !  mbedtls_x509_crt_parse_file of ca returned %d\n\n", ret );
        	exit(ret);
    	}

	ret = mbedtls_x509_crt_parse_file(&cd->client_cert, client_cert_filename);
    	if (ret != 0) {
        	mbedtls_printf( " failed\n  !  mbedtls_x509_crt_parse_file of client returned %d\n\n", ret );
        	exit(ret);
    	}

	ret = mbedtls_pk_parse_keyfile(&cd->client_pkey,client_key_filename,password);
	if (ret != 0) {
		mbedtls_printf( " failed\n  !  mbedtls_pk_parse_keyfile client returned %d\n\n", ret );
		exit(ret);
	}

       mbedtls_ssl_conf_authmode( &cd->conf, MBEDTLS_SSL_VERIFY_REQUIRED );
    	
       **mbedtls_ssl_conf_ca_chain( &cd->conf, &cd->ca_cert, NULL  );
	if( ( ret = mbedtls_ssl_conf_own_cert( &cd->conf, &cd->client_cert, &cd->client_pkey ) ) != 0 )
        {
            mbedtls_printf( " failed\n  ! mbedtls_ssl_conf_own_cert returned %d\n\n", ret );
	    exit(ret);
        }**
    	......................

    	if( ( ret = mbedtls_ssl_setup( &cd->ssl, &cd->conf ) ) != 0 )
    	{
        	mbedtls_printf( " failed\n  ! mbedtls_ssl_setup returned %d\n\n", ret );
        	freeClientTLSData(ret,cd);
		exit(ret);
    	}

    	**while( ( ret = mbedtls_ssl_handshake( &cd->ssl ) ) != 0 )
    	{
        	if( ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE )
        	{
            		mbedtls_printf( " failed\n  ! mbedtls_ssl_handshake returned -0x%x\n\n", -ret );
            		freeClientTLSData(ret,cd);
			exit(ret);
        	}
    	}**

``


Please let me if i am doing anything wrong at 'mbedtls_ssl_conf_ca_chain'  , 'mbedtls_ssl_conf_own_cert' calls order or if any.
And also which certificates(ca, client, server certs) are mainly required at both server and client side code.


Thanks in Advance.

**Comment by PravallikaKG** [comment]
My issue is resolved. I am facing it because of certificates I am using are invalid

**Comment by martinius96** [comment]
@PravallikaKG yes, because you haven't self-signed them.

**Comment by RonEld** [comment]
@Carmeloning certificate verification failure can happen for many reasons. For example, you haven't set the correct trusted root certificate.
The error -0x2700 is `MBEDTLS_ERR_X509_CERT_VERIFY_FAILED` and returned when the certificate verification fails.
You should check the verification flags as well.

**Comment by martinius96** [comment]
I had similar error when i was generating Root CA certificate from 1024-bit RSA key.
How did you generate it?
If u using RSA key how many bits it have?

**Comment by RonEld** [comment]
@martinius96 
As you can see in the [default profile used for cerification](https://github.com/ARMmbed/mbedtls/blob/development/library/x509_crt.c#L97), the minimal keysize allowed is 2048 bits. This is because a 1024 bit key size is unsecure.

**Comment by martinius96** [comment]
@RonEld Thanks a lot.. finally i found it in codes..
I was 3 months solving problem why it isnt working and i was using 1024-bit rsa key... :(
:D :-)

**Comment by RonEld** [comment]
@Carmeloning Have you checked the verification flags? They are not shown in this log.

Without too much information in this log, I can guess two possible reasons for your failure:
1. You haven't set the proper trusted CA certificate( certificate which has a CN "myCA" in its subject name), in `mbedtls_ssl_conf_ca_chain()`.
2. You haven't defined `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` in your configuration. SHA1 is considered not a secure hash, and by default not allowed to be used in certificates, in Mbed TLS
