### ISSUE TITLE
verification flags have invalid information when mbedtls_x509_crt_verify_with_profile fails

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1397]
### Description
- Type: Bug
- Priority: Major
Raised by Marian Kechlibar in the [support forum](https://tls.mbed.org/discussions/bug-report-issues/all-flags-set-if-certificate-verification-fails)
---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.7

**Expected behavior**   
verification flags to point to the actual reason for failure
**Actual behavior**  
verification flag has all bits set

**Steps to reproduce**  
have a certificate verification failure, and look at the verification flags

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2105

**Comment by Marian-Kechlibar** [comment]
Hello, I can reproduce the problem always when I attempt to connect to a SSL server whose server certificate is in any way invalid or has unknown CA. I used badssl.com to test it.

```
mbedtls_ssl_handshake_step(mbedtls_ssl_context * ssl) Line 6627
mbedtls_ssl_handshake_client_step(mbedtls_ssl_context * ssl) Line 3370
mbedtls_ssl_parse_certificate(mbedtls_ssl_context * ssl) Line 4619
mbedtls_x509_crt_verify_with_profile(...) Line 2325

```
My line numbers may vary slightly, because I change some typedefs.

**Comment by hanno-arm** [comment]
@Marian-Kechlibar Do you use a custom verify function? If yes, could you confirm that you obey the requirement that that function must return `0` for everything apart from a fatal error? As @RonEld mentioned in the forum, the documentation states:
```
All flags left after returning from the callback are also returned to the application. 
The function should return 0 for anything (including invalid certificates) other than 
fatal error, as a non-zero return code immediately aborts the verification process. 
For fatal errors, a specific error code should be used (different from
MBEDTLS_ERR_X509_CERT_VERIFY_FAILED which should not be returned 
at this point), or MBEDTLS_ERR_X509_FATAL_ERROR can be used if no better 
code is available.
```

**Comment by RonEld** [comment]
@Marian-Kechlibar  We are closing this issue, as we believe the root cause for the error was not returning 0 on the user defined `f_vrfy` function, on failed certificates as well, as the documentation mentions, and as mentioned in the forum issue.
An error should be returned only on non recoverable errors.
If your use case is different, please reopen, and update this ticket with your user defined verification function.
