### ISSUE TITLE
What is the current license status of this project?

### ISSUE THREAD

**Issue by Tianjiao** [ARMmbed/mbedtls#1413]
### Description
- Type: Question
- Priority: Minor
-----------------------------------------------------------------

## Question
From the [Wikipedia](https://en.wikipedia.org/wiki/Mbed_TLS), I read that this project is dual-licensed with the Apache License version 2.0 (with GPLv2 also available)

But according to the explaination by Apache [here](https://apache.org/licenses/GPL-compatibility.html)

> Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.

And from the explaination by FSF [here](http://www.gnu.org/licenses/license-compatibility.html)

> One lax license, Apache 2.0, has patent clauses which are incompatible with GPL version 2; since I think those patent clauses are good, I made GPL version 3 compatible with them.

So what is the current license status of this project? If it is as per said by Wikipedia, then are you dual-license it in two incompatible licenses?

_Disclaimer: I am not a lawyer, I am just an ordinary user with some question._

**Comment by RonEld** [comment]
@Tianjiao I believe I answered your question in our [support forum](https://tls.mbed.org/discussions/generic/what-is-the-current-license-status-of-this-project), therefore closing this issue.
