### ISSUE TITLE
 Security advisory notice took 28 days

### ISSUE THREAD

**Issue by jay** [ARMmbed/mbedtls#1414]
I am subscribed to mbedTLS 'Security Advisories' updates via e-mail. This afternoon 2/28 I received a notification of two security advisories that were issued a month ago. That is too long, I expect them same day. In the future please send out the advisory notices immediately. Thanks

**Comment by sbutcher-arm** [comment]
Hi @jay,
 
We sent the security advisory out to our Mbed TLS mailing list, as we usually do for all such advisories. This time however, we found out that our mailing system had gone too long without proper maintenance and failed to operate properly with our mail service provider. This has caused a long series of events before we could recover full mailing capability as we needed to swap providers, which caused a long delay in sending the notice.

We have taken the appropriate steps to make sure this kind of glitch cannot happen again.

Please accept our apologies for this delay, and rest assured we do value the timeliness of sending out security advisories.
