### ISSUE TITLE
Memory leak in cert_write example program 

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1422]
__Issue:__ The [programs/x509/cert_write](https://github.com/ARMmbed/mbedtls/blob/1bf6123fca97a9a35c2f403ab0c96495f9580db6/programs/x509/cert_write.c) example program doesn't free the CSR and issuer CRT structures `csr` resp. `issuer_crt` after use. Their initialization happens [here](https://github.com/ARMmbed/mbedtls/blob/1bf6123fca97a9a35c2f403ab0c96495f9580db6/programs/x509/cert_write.c#L242) and [here](https://github.com/ARMmbed/mbedtls/blob/1bf6123fca97a9a35c2f403ab0c96495f9580db6/programs/x509/cert_write.c#L244), but the [cleanup section](https://github.com/ARMmbed/mbedtls/blob/1bf6123fca97a9a35c2f403ab0c96495f9580db6/programs/x509/cert_write.c#L791) omits them. 

This leads to a memory leak when running `programs/x509/cert_write` with either the `request_file` or the `issuer_crt` argument set, as witnessed by a run with address sanitizer enabled.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2152
