### ISSUE TITLE
rsa_internal.h is missing a #ifdef __cplusplus } #endif  at the bottom

### ISSUE THREAD

**Issue by ademko** [ARMmbed/mbedtls#1426]
rsa_internal.h is missing a 

#ifdef __cplusplus
}
#endif 

at the bottom, right before the final #endif

Symptomizes with mbedtls 2.7.0 under VS 2012, release mode, using my own project settings/files.

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2167
