### ISSUE TITLE
All VS2010 projects have incorrect Release|x64 configuration

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#1430]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug
All VS2010 projects have an error in `Release|x64` configuration.
This line must be deleted:
 `<PlatformToolset>Windows7.1SDK</PlatformToolset>`
In that case the value would be inherited from project defaults, which is fine - as it is in other configurations.
If `PlatformToolset` was to be defined, the value should have been `v100`.
It looks like a `TargetPlatform` definition, but in that case the line is in the wrong place; and this is not necessary either.

**OS**  
Mbed OS: Windows

**mbed TLS build:**  
The bug was present in `development` branch since the first commit.

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2165

**Comment by irwir** [comment]
A `sed` command deleting the lines with the pattern and applied to all `*.vcxproj` files should do the trick:
`/Windows7.1SDK/d`

**Comment by irwir** [comment]
This trivial change is of the kind that are cheaper to fix and forget immediately rather than keep and maintain in the list.
Is there anything blocking, or maybe a PR is needed?

**Comment by hanno-arm** [comment]
@RonEld Why is this being closed?

**Comment by irwir** [comment]
The issue was mostly fixed in the development branches of both `mbedtls` and `mbedtls-crypto`.
But there is one complication.
The main project `visualc\VS2010\mbedTLS.vcxproj`, unlike others, is created from 
template `scripts\data_files\vs2010-main-template.vcxproj`.

**Comment by Patater** [comment]
@irwir Please raise PRs and we can review and merge from there. Thanks!

**Comment by irwir** [comment]
@Patater
Would it be possible to merge more than one tiny issues into one PR?

**Comment by Patater** [comment]
@irwir The smaller the PR, the quicker it is for us to review and merge. Large PRs tend to get left behind and go stale. The preferred approach is multiple PRs that can be merged independently.
