### ISSUE TITLE
Documentation for Mbed TLS should mention DTLS and RFC 6347

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbedtls#1432]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
All OS

**mbed TLS build:**  
Version: 2.0.0

[Driss on the forum asks](https://tls.mbed.org/discussions/feature-request/compliancy-to-dtls-rfc6347):

> Does mbedTLS support and compliant with RFC6347 ? You didn't put any reference to DTLS RFC in the compliancy and core-feature web pages: https://tls.mbed.org/standard-compliance https://tls.mbed.org/core-features
> 
> is it a mistake or there is realy a feature gap with DTLS RFC6347 standard?
> 
> Best Regards
> 

**Expected behavior**   

The documentation for Mbed TLS should reflect the standards it supports. We should update the documentation for our library on the supported standards.

**Actual behavior**  

Mentions of DTLS and its RFC are missing from both [standard-compliance](https://tls.mbed.org/standard-compliance) and [core-features](https://tls.mbed.org/core-features).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2164
