### ISSUE TITLE
Status checks return error

### ISSUE THREAD

**Issue by Alonof** [ARMmbed/mbedtls#1437]
### Description
- Type: Bug 
- Priority: Major

---------------------------------------------------------------

## Bug
after adding status checks in function `mbedtls_ssl_derive_keys()` CI tests are failing line [893](https://github.com/ARMmbed/mbedtls/pull/1421/files#diff-995204bbb15401337db9b64bc314e1f6R893) in `ssl_tls.c

**OS**  
linux

**mbed TLS build:**  
Version: Development /  [Commit](https://github.com/ARMmbed/mbedtls/pull/1421/commits/fecf48f51abebd911c49c1a88f89ddbda79d8a0a)

**Expected behavior**   
The status check should return success.
**Actual behavior**  
tests are failing 
**Steps to reproduce**  
run test with the branch from [PR](https://github.com/ARMmbed/mbedtls/pull/1421)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2171

**Comment by gilles-peskine-arm** [comment]
Hi Alon, could you clarify whether #1437 is a preexisting issue? Normally, if a PR causes a test failure, we'd expect an update to the PR to fix this issue.

**Comment by gilles-peskine-arm** [comment]
After investigation, the code in development has the correct behavior (except for the missing error checks that #1421 adds), but it is not robust. There is one particular place in the code where it is correct to ignore one particular error. Given that this isn't robust, I propose to make the check explicit: #1461
