### ISSUE TITLE
2.6.1 changelog entry missing

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#1438]
### Description
- Type: Question

## Question

The 2.6.1 ChangeLog entry is missing from releases 2.7.0 and later. Is this on purpose?

**Comment by RonEld** [comment]
Hi @stevew817 As mentioned in #1350 version 2.6.1 was an internal release intended for Mbed. It contains a single fix, and this fix is mentioned in the 2.7.0 ChangeLog.

**Comment by RonEld** [comment]
Assuming this is sufficient, I'm closing the issue, but feel free to reopen it or follow up with more questions.
