### ISSUE TITLE
TODO in mbedtls_asn1_write_int

### ISSUE THREAD

**Issue by dgreen-arm** [ARMmbed/mbedtls#1443]
**Issue:** There is a TODO in `mbedtls_asn1_write_int`, this should be tracked rather than just exist as a TODO in the code.

TODO negative values and values larger than 128
DER format assumes 2s complement for numbers, so the leftmost bit
should be 0 for positive numbers and 1 for negative numbers.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2170

**Comment by hanno-arm** [comment]
Fixed through https://github.com/ARMmbed/mbedtls/pull/1446.
