### ISSUE TITLE
TODO in mbedtls_ssl_read

### ISSUE THREAD

**Issue by dgreen-arm** [ARMmbed/mbedtls#1444]
**Issue:** There is a TODO in `mbedtls_ssl_read`, this should be tracked rather than just exist as a TODO in the code.

TODO

The logic should be streamlined here:

Instead of

- Manually checking whether ssl->in_offt is NULL
- Fetching a new record if yes
- Setting ssl->in_offt if one finds an application record
- Resetting keep_current_message after handling the application data

one should

- Adapt read_record to set ssl->in_offt automatically
  when a new application data record is processed.
- Always call mbedtls_ssl_read_record here.

This way, the logic of ssl_read would be much clearer:

(1) Always call record layer and see what kind of record is on
    and have it ready for consumption (in particular, in_offt
    properly set for application data records).
(2) If it's application data (either freshly fetched
    or something already being partially processed),
    serve the read request from it.
(3) If it's something different from application data,
    handle it accordingly, e.g. potentially start a
    renegotiation.

This will also remove the need to manually reset
ssl->keep_current_message = 0 below.

**Comment by hanno-arm** [comment]
This is fixed in https://github.com/ARMmbed/mbedtls/pull/946

**Comment by RonEld** [comment]
CLosing, as #946 has been merged
