### ISSUE TITLE
CMAC self test unconditionally runs AES-192 vectors

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#1447]
### Description
- Type: Bug

When running the CMAC unit tests for a device that doesn't support accelerated AES-192, and instead returns the `MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE` error code as implemented in #964 and confirmed correct in #963, the CMAC unit test still fails. Now that we have an official error code to check for, please make sure all unit tests are up-to-date and compatible with this error code.

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS

**mbed TLS build:**  
Version: 2.7.1

**Expected behavior**   
Unit tests pass for the actual target.

**Actual behavior**  
Unit test errors out.

**Steps to reproduce**  
Run test_suite_cmac unit test on a target that doesn't support AES-192.

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2200

**Comment by stevew817** [comment]
Resolved through #3994 and #4146
