### ISSUE TITLE
Test "DTLS client reconnect from same port" often fails in CI

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbedtls#1456]
Recently this test has become unstable in CI and fails often.

```
DTLS client reconnect from same port: reference ........................ FAIL
  ! pattern 'resend' MUST NOT be present in the Client output
  ! outputs saved to o-XXX-327.log
```

See CI logs https://jenkins-internal.mbed.com/job/mbedtls-release/243/execution/node/66/log/
Unfortunately test logs are not saved by CI. Failure has to be reproduced locally for triage.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2199
