### ISSUE TITLE
Reject known failing MemSan build

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1478]
Steps to reproduce (on `mbedtls-2.7.0` or 2.8):
```
scripts/config.pl full
CC=clang cmake -D CMAKE_BUILD_TYPE:String=MemSan .
make
make test
```

Several tests fail. In fact we know about this — `all.sh` says
```
scripts/config.pl unset MBEDTLS_AESNI_C # memsan doesn't grok asm
```

We should reject the configuration at the `cmake` or `make` step. Doing it in `cmake` may be easier, but doing it at the `make` step (ideally through a `#warning` directive so that it's independent of the build system) would have the advantage that it would work even if `config.h` is changed after running `cmake` or when using other build systems.

**Comment by mpg** [comment]
This should be fairly easy to do at the source level:
```
#if defined(__has_feature)
#if __has_feature(memory_sanitizer)
#warning "This function doesn't work with Memory Sanitizer"
#endif
#endif
```

We could also try to make the tests actually pass using `__attribute__((no_sanitize("memory")))` on some functions (but I'm not sure if it still marks memory written by those functions as initialised) or the [sanitizer special case list](https://clang.llvm.org/docs/SanitizerSpecialCaseList.html), though last time I tried the latter approach I couldn't get anywhere.

**Comment by gilles-peskine-arm** [comment]
Fixed in https://github.com/ARMmbed/mbedtls/pull/1560
