### ISSUE TITLE
Test cmake subproject build in all.sh

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1482]
In `all.sh`, we test a cmake build in place, and a cmake build in a separate directory (out-of-tree build). We don't test a cmake build where mbedtls is a subdirectory of another project, and this was broken for a while, see #1242.

We should add a non-regression test in `all.sh`. @schwabe [proposes the following setup](https://github.com/ARMmbed/mbedtls/pull/1242#pullrequestreview-105749759):

> Folder test with: test.c (empty) mbedtls (git clone of this) and CmakeLists.txt:

>     cmake_minimum_required(VERSION 3.4.1)
>     
>     add_subdirectory(mbedtls)
>     add_executable(testpgm test.c)
>     target_link_libraries(testpgm mbedtls)

**Comment by gilles-peskine-arm** [comment]
@Patater Does https://github.com/ARMmbed/mbedtls/pull/2747 add a test for that or am I mixing up scenarios?

**Comment by Patater** [comment]
It is intended that the test added in #2747 would catch where we've broken the use case where mbedtls is used as a CMake subproject of another.

```
cmake_minimum_required(VERSION 2.6)
  
# We use the parent Mbed TLS directory as the MBEDTLS_DIR for this test. Other
# projects that use Mbed TLS as a subproject are likely to add by their own
# relative paths.
set(MBEDTLS_DIR ../../../)

# Add Mbed TLS as a subdirectory.
add_subdirectory(${MBEDTLS_DIR} build)

# Link against all the Mbed TLS libraries.
set(libs
    mbedtls
    mbedcrypto
    mbedx509
)

add_executable(cmake_subproject cmake_subproject.c)
target_link_libraries(cmake_subproject ${libs})
```

**Comment by Patater** [comment]
This can be closed, as we now have a test in `all.sh` (`component_test_cmake_as_subdirectory`) as of https://github.com/ARMmbed/mbedtls/pull/2706
