### ISSUE TITLE
Test our claimed c89/c90 compatibility

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1484]
The [Mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards) state:

> The code uses a restricted version of the C99 ISO standard. The only features from C99 (with comparison to C89 / ANSI C) used are:

> * the stdint.h header for fixed-width types such as uint32_t.
> * the inline keyword (though we use __inline instead with some compilers known not to support it, such as armcc 5).
> * one-line comments with //
> * bounded functions snprintf() and vsnprintf()
> * the long long and uint64_t types
> * to be pedantic, some string literals that are longer than the length that C89 compilers are required to support
> * to be really pedantic, trailing comas in enumerator lists.

We don't test this as part of our CI though: we only do builds that allow proprietary extensions and builds in C99 mode. We should do a build in C89/C90 pedantic mode plus a small, selected set of extensions with at least one of GCC or Clang on at least one platform. This could (should) be one of the builds in `all.sh`.

Example of non-compliance: #1353

**Comment by mrpippy** [comment]
I don't think gcc/clang have separate flags to ignore different C99 warnings (they all get bunched under `-Wc99-extensions`), but it might work to build in C89 mode and then filter-out the warnings for features that are ok (like trailing commas), with a command like the one here: https://lists.archlinux.org/pipermail/pacman-dev/2011-April/012888.html

**Comment by mpg** [comment]
Or perhaps we could change our claim to something that's easier to test (eg "we require C99 but won't use some problematic features such as VLAs, [list to be completed], and include workarounds for compilers that don't provide 'inline'" and [list to be completed]) and still sufficient in the real world.

**Comment by gilles-peskine-arm** [comment]
We've internally decided to drop support for C89 in the development branch. We've removed `-Wdeclaration-after-statement` to our build options in `CMakeLists.txt`. We run some builds with `gcc -std=c99 -pedantic` so we do test C99 compliance to a reasonable extent. Thus this issue is resolved.
