### ISSUE TITLE
Optimize algorithms for size ? 

### ISSUE THREAD

**Issue by pan-** [ARMmbed/mbedtls#1489]
### Description
- Type: Question
- Priority: Blocker 

## Question

I'm integrating Bluetooth Low Energy secure connections in mbed OS BLE. This feature requires the generation of Diffie-Hellman keys and the computation of a shared secret. Mbed TLS being integrated into mbed OS; it seems like the right candidate to achieve the task. 

Unfortunately the overhead in term of stack memory is too important for us (more than 3K); code size overhead is non negligible either. 

Thanks to ARMCC static stack analysis capability I was able to locate the functions consuming too much stack: 

1.  [mbedtls_mpi_fill_random](https://github.com/ARMmbed/mbedtls/blob/32605dc83042d737e715a685e53176388d73540e/library/bignum.c#L1880) allocates on the stack an array of `MBEDTLS_MPI_MAX_SIZE` bytes regardless of the number of random bytes requested. The default value of `MBEDTLS_MPI_MAX_SIZE` is set to 1024 bytes. That may be fine for desktop or embedded linux platform but it is very large for mbed OS application; the size of mbed OS stacks being by default 4K large. 
1. [mbedtls_internal_sha512_process](https://github.com/ARMmbed/mbedtls/blob/b7f6086ba3f1193042d48a871b7ee965d0e195d7/library/sha512.c#L209) allocates on the stack an array `W` of 80 uint64_t (640 byte) to realize the computation. This array is used to pre-compute values that will be used later by the algorithm .

I've solved 1. using a variable length array instead of a fixed length array (N/A in mbed tls); As the code exit if the size in input is larger than `MBEDTLS_MPI_MAX_SIZE` it is not more vulnerable than the existing code. Other solutions like dynamic memory allocation of the temporary buffer or iterating in loop the cycle `random number generation` + `copy`  can be considered. 

I've solved number 2. by removing [W pre-computation](https://github.com/ARMmbed/mbedtls/blob/b7f6086ba3f1193042d48a871b7ee965d0e195d7/library/sha512.c#L240-L244) and delaying computation to the point of use (my solution [here](https://gist.github.com/pan-/1a16f468171b8695e10f5f4fccc6642b)). I've also removed loop unrolling; in the end that's 3.6 to 3.9X less code (1.8K to 2.5K) generated and 512K of bytes of stack saved but at the expense of a 30% to 80% performance degradation for the function. Benchmarked as a whole in my application the performance degradation observed is less than a percent.

After these two changes more than 1.5K of bytes are saved on the stack and I'm able to use mbed TLS.

Now I'm coming to my questions: 
* What is the recommended strategy to fix large stack allocation ? 
* Have you considered a compile time flag that would favor size over speed optimizations ? With such flag it would be possible to have algorithms implementation that are crafted specifically for their footprint regardless of their performance. In my case I cannot see myself submitting a PR that yield 80% performance degradation for all users even if the footprint gains are large.

**Comment by sbutcher-arm** [comment]
Hi @pan- 

To answer your questions:-

> What is the recommended strategy to fix large stack allocation ?

We don't really have one. This is more a known problem that we're working on.

> Have you considered a compile time flag that would favor size over speed optimizations ? With such flag it would be possible to have algorithms implementation that are crafted specifically for their footprint regardless of their performance. In my case I cannot see myself submitting a PR that yield 80% performance degradation for all users even if the footprint gains are large.

That's not really how we work today. We have a lot of fine-grained configurations held in `config.h` which allows a sophisticated user to tweak the library for code-size over performance. We're working on making those configurations work at a higher level, and in a more easily configurable way, but that work is still in the pipeline.

Does that satisfy your questions?

**Comment by pan-** [comment]
Hi @sbutcher-arm 

Thanks for the quick reply. It perfectly answers my questions. Now I know what I have to do to submit my enhancements.
