### ISSUE TITLE
ssl_server.c and ssl_client1.c are using an SHA-1 signed certificate

### ISSUE THREAD

**Issue by iluxonchik** [ARMmbed/mbedtls#1519]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.8.0

**Problem Description**
The ssl_server1.c and ssl_client1.c demo programs use an [SHA-1 cert](https://github.com/ARMmbed/mbedtls/blob/development/library/certs.c#L221), while the [default configuration has SHA-1 certs as disabled](https://github.com/ARMmbed/mbedtls/blob/f65379bc400707baac9466cce88a759685ac6c01/include/mbedtls/config.h#L2802).

**Problem Solution**
Update the default RSA certificate to one using an SHA-2 signature.

**Comment by RonEld** [comment]
@iluxonchik Thank you for raising this issue. We will look into this

**Comment by iluxonchik** [comment]
@RonEld no problem, I already submitted a pull request

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2202

**Comment by RonEld** [comment]
Although https://github.com/ARMmbed/mbedtls/commit/750c353c5c828d27d077022f2c856fb13e6a5258 added SHA256 certificates to `certs.c` , this issue is not resolved, because `ssl_server` still sends a SHA1 certificate
