### ISSUE TITLE
Unchecked dependencies on ASN1_PARSE_C in various modules

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#1531]
### Description
- Type: Bug 
- Priority: Major

Various modules (pkparse, asn1write, pkcs12, pkcs5) try to call functions from `asn1_parse` without checking that it is enabled. This should be fixed either by making the modules depend on `ASN1_PARSE_C` in `check_config.h` or making specific functions withing the modules depend on it.

## Bug

**OS**  
Any.

**mbed TLS build:**  
Try to build with the following disabled:
```
BEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
MBEDTLS_SSL_SERVER_NAME_INDICATION
MBEDTLS_ASN1_PARSE_C
MBEDTLS_DHM_C
MBEDTLS_ECDSA_C
MBEDTLS_X509_USE_C
MBEDTLS_X509_CRT_PARSE_C
MBEDTLS_X509_CRL_PARSE_C
MBEDTLS_X509_CSR_PARSE_C
```

**Peer device TLS stack and version**  
Any.

**Expected behavior**   
The build succeeds, or fails at compile-time with a clear error message from `check_config.h`.

**Actual behavior**  
Bunch on linker errors when building tests, output of `make -C tests 2>&1 | grep function` is:
```
../library/libmbedcrypto.a(pkparse.c.o): In function `mbedtls_pk_parse_subpubkey':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_get_pk_alg':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_use_ecparams':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_parse_key_pkcs1_der':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_parse_key_sec1_der':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_parse_key_pkcs8_unencrypted_der':
../library/libmbedcrypto.a(pkparse.c.o): In function `pk_parse_key_pkcs8_encrypted_der':
../library/libmbedcrypto.a(asn1write.c.o): In function `mbedtls_asn1_store_named_data':
../library/libmbedcrypto.a(pkcs12.c.o): In function `pkcs12_pbe_derive_key_iv':
../library/libmbedcrypto.a(pkcs5.c.o): In function `mbedtls_pkcs5_pbes2':
```

**Steps to reproduce**  
See above.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2529

**Comment by hanno-arm** [comment]
Suggestion:
1. For the ASN.1-write module, only `mbedtls_asn1_store_named_data()` needs `mbedtls_asn1_find_named_data()` from the ASN.1-parse module. I suggest the introduction of an `MBEDTLS_ERR_ASN1_FEATURE_UNAVAILABLE` error code that's returned from `mbedtls_asn1_store_named_data()` when `ASN1_PARSE_C` is not defined. 
2. For the PK-parse module, every function needs the ASN.1-parsing module, so I suggest to add the dependency of `MBEDTLS_PK_PARSE_C` on `MBEDTLS_ASN1PARSE_C` to `check_config.h`.
3. For PKCS-12, `mbedtls_pkcs12_pbe()` builds on ASN.1-parsing, while `mbedtls_pkcs12_derivation()` doesn't. I suggest to guard `mbedtls_pkcs12_pbe_xxx()` by `MBEDTLS_ASN1PARSE_C` and return the existing error code `MBEDTLS_ERR_PKCS12_FEATURE_UNAVAILABLE` if it's unset.
4. For PKCS-5, `mbedtls_pkcs5_pbes()` needs ASN.1-parse, while `mbedtls_pkcs5_pbkdf2_hmac()` doesn't, so again I suggest to have `mbedtls_pkcs5_pbes()` return `MBEDTLS_ERR_PKCS5_FEATURE_UNAVAILABLE` if `MBEDTLS_ASN1PARSE_C` is unset.
Unless there are objections, I'll create a PR with the corresponding changes.

**Comment by mpg** [comment]
I agree about point 2, but for the others I'm not sure why we should return an error at runtime rather than just remove the function at compile time. If we know at compile time that a particular function will never work, then we should indicate that by throwing an error at compile. OTOH, if the function may or may not work depending on what data is passed to it an runtime, then a runtime error is OK.

(I don't think removing a function in some configurations is a violation of our API stability promise if it never worked before. Our promise is that if your code works and is correct with a version, it will keep working an being correct with any later version, until the major version number is bumped. We're not promising anything about code that never worked in the first place.)

**Comment by hanno-arm** [comment]
@mpg Thank you for your feedback! I will go forward removing the respective functions at compile time if they cannot work in a certain configuration.

**Comment by hanno-arm** [comment]
@mpg The current implementation of `mbedtls_asn1_store_named_data()` creates a dependency of `asn1_write.c` on `asn1_parse.c` because of the use of `mbedtls_asn1_find_named_data()`, which doesn't to anything ASN.1 related but essentially searches through a list of strings. This dependency then propagates to e.g. a dependency of `X509_CREATE_C` on `ASN1_PARSE_C`, which is counter intuitive. Given that `mbedtls_asn1_find_named_data()` doesn't do any ASN.1 parsing and is very short, I'd suggest to duplicate it statically in `asn1_write.c` to remove the dependency. What do you think?

**Comment by mpg** [comment]
I agree, duplicating a small portion of generic code seems better than having those counterintuitive dependencies.
