### ISSUE TITLE
Don't use %d printf format string for size_t variables

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1534]
There are multiple places in the library, e.g. https://github.com/ARMmbed/mbedtls/blob/90226be77957608b89f409ad851c4e79c46849a1/library/ssl_tls.c#L2472 where the value of variables of type `size_t` is formatted using the `%d`-flag for integers when being printed for debugging purposes. Depending on the platform, this can lead to wrong output or crash.

The correct format string `%zu` is not used as it is not supported by Visual Studio versions prior to 2013.

One possible fix which prints the correct output most of the time and is not endangering a crash is to use `%lu` instead while explicitly casting the respective variable to `unsigned long` in debugging calls.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2204

**Comment by gilles-peskine-arm** [comment]
To get the warnings on printf formats from GCC: https://github.com/gilles-peskine-arm/mbedtls/commit/91115bbbe7e873267ffea55319fa7dead1690e51

**Comment by irwir** [comment]
> The correct format string %zu is not used as it is not supported by Visual Studio versions prior to 2013.

There is a non-standard legacy MS format `I`. It is possible to check compiler version `_MSC_VER` and compose the correct format string using concatenation capability of preprocessor.

> One possible fix which prints the correct output most of the time and is not endangering a crash is to use %lu instead while explicitly casting the respective variable to unsigned long in debugging calls.

No crash, but high 32-bits would be lost in 64-bit mode.
