### ISSUE TITLE
ssl-opt.sh does not start if lsof is not present

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1536]
./tests/ssl-opt.sh: 311: ./tests/ssl-opt.sh: START_DELAY: parameter not set

The culprit is the line
```
    echo "Warning: lsof not available, wait_server_start = sleep $START_DELAY"
```

`START_DELAY `is only set later in the script.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2221
