### ISSUE TITLE
Recommended environment/versions for running tests/scripts/all.sh

### ISSUE THREAD

**Issue by projectgus** [ARMmbed/mbedtls#1568]
### Description
- Type: Question
- Priority: Minor

As [mentioned here](https://github.com/ARMmbed/mbedtls/pull/536#issuecomment-380692156), I had some trouble finding a Linux environment where all of `all.sh` passed so I was wondering if there is any recommended one to use.

If desirable, I can send a PR which adds a `Vagrantfile` to quickly spin up a controlled environment for any developer to run the tests in (I have a working Vagrantfile, but as mentioned it's not currently passing all tests...)

I tried these environments:

* Arch Linux. Ships openssl 1.1.0h without 3DES cipher support.[*]
* Ubuntu Trusty. Ships gnutls-3.0.11 which doesn't support `--priority:NORMAL:%SAFE_RENEGOTIATION` and similar.
* Ubuntu Xenial. Ships gnutls-3.4.10 and openssl 1.0.2g. This works for almost all tests & configs, but as mentioned I get about 5 failures that appear to be because Ubuntu openssl no longer ships a NULL cipher.[*] (Plus one openssl internal error, but this may have been a one-off failure not reproducible.)

[*] Can exclude missing ciphers from a run of `ssl-opt.sh` by passing `--exclude`, but this option is not available for `all.sh`.

**Comment by mpg** [comment]
Hi @projectgus! Currently our environment for running `all.sh` is based on Ubuntu 16.04 on x86-64. On top of that, we install custom OpenSSL and GnuTLS versions:
- OpenSSL 1.0.1j pointed to by `$OPENSSL_LEGACY`
- OpenSSL 1.1.1-pre1 pointed to by `$OPENSSL_NEXT`
- GnuTLS 3.3.8 (libnettle 2.7.1) pointed to by `$GNUTLS_CLI_LEGACY` and `$GNUTLS_SERV_LEGACY`

We also have the usual C compilers and tools (gcc-multilib, Clang, valgrind) and some cross-compilers (arm-none-eabi-gcc, i686-w64-mingw32-gcc, and if you don't have a license for armcc/armclang, you can use the `--noarmcc` option).

Hope this helps! Let us know how it works for you.

**Comment by RonEld** [comment]
We believe this question has been answered, therefore closing.
If you believe that the issue requires further  action, please reopen.
