### ISSUE TITLE
Odd VS version number in online docs

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#1569]
### Description
- Type: Bug / Enhancement
- Priority: Minor

---------------------------------------------------------------
## Bug
The article [mbed TLS automated testing and Quality Assurance](https://tls.mbed.org/kb/generic/what-tests-and-checks-are-run-for-mbedtls) in the list of compilers / IDE environments has this line:
`MS Visual Studio 12`.
Internal VS version 12 corresponds to VS 2013.
Other docs mention VS 2010, and that is currently the target version for project files in the repository.

**Comment by RonEld** [comment]
@irwir Thank you for putting this into our attention!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2528

**Comment by irwir** [comment]
What kind of `openness to community contibution` is meant, if a normal PR is impossible?

Apparently, the exact text of the line could be as in other documents:
`MS Visual Studio 2010 or later`
The rest (supplying this data to people who maintain your site) should be simpler than making a new blog entry. :)

**Comment by RonEld** [comment]
Hi @irwir 
We have described our new approach in [this blog](https://tls.mbed.org/tech-updates/blog/a-new-defect-management-approach) as you probably seen.
You are welcome to contribute a fix for this issue.

**Comment by irwir** [comment]
Hi @RonEld
Thanks for the answer. I had read the latest blog entries, but that gave no clue about how to fix this library's **web site**.
My guess, it could have been done in the same way as new blog entries and articles were posted.

**Comment by RonEld** [comment]
Hi @irwir 
I apologize for confusion. 
I was under the impression you were referring to the readme file in this repository, and not the article in our website, as the issues here mostly target this repository.
I have created an issue in our documentation repository to track this, so we can keep this ticket closed.
Note that we are thinking of removing support for VS 2010, since it isn't c99 compatible
