### ISSUE TITLE
Release notification emails are consistently late

### ISSUE THREAD

**Issue by NWilson** [ARMmbed/mbedtls#1574]
I subscribe to your emails which provide notification of new releases.

For the last few releases, these have been consistently late: the mbedTLS 2.8.0 blog post was announced on March 21st, but the email didn't go out until 6 April.

Some users may be relying on the emails to be notified of security advisories; if the email notifications are not suitable for this purpose, the mailing list should indicate this clearly. Since the advisories in the 2.8.0 release may have affected our product, it would have been nice to notify the mailing list promptly.

**Comment by sbutcher-arm** [comment]
Hi @NWilson,

Over the past few months we've been planning a migration from the old Offspark Mbed TLS website to new infrastructure, and integrating Mbed TLS properly into the rest of the Mbed website. One part of that has been migrating how we issue release emails. 

Unfortunately, over the past two releases, we've had some initial problems and have been left very unsatisfied with the turnaround on the announcement emails, and the long delay between pushing Mbed TLS onto GitHub and the website, and the email going out. We've sought and received reassurances, that this should not happen again.

You have our sincere apologies for this, and I appreciate a security advisory that arrives late in a period measured in weeks isn't very useful. 

For the next release, I'll post an announcement on the Mbed TLS forum at the same time we issue the official email. If you subscribe to forum emails hopefully you'll receive that too.

For the moment I'll leave this issue open until after the next release.

**Comment by NWilson** [comment]
No problem then! Sounds like you're aware of it, so I'm happy. Thanks!

**Comment by RonEld** [comment]
This question has been answered, therefore closing
