### ISSUE TITLE
Usage of MBEDTLS_SSL_PRESET_SUITEB vs ECP curve configuration

### ISSUE THREAD

**Issue by dbedev** [ARMmbed/mbedtls#1591]
### Description
- Type: Bug / Question
- Priority:   Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build: **  
Version: 2.6.0
OS version:Linux

**Peer device TLS stack and version**  
Linux MbedTls 2.6.0
Version:  

**Expected behavior**   
Not sure what should the "correct" behavior is expected to be as the MBEDTLS_SSL_PRESET_SUITEB does not seem to be documented beyond having value "2". 

There are some alternatives that would be an improvement over the current reaction:

A. Strip the curve from the preset list based on the ( MBEDTLS_ECP_DP_SEC) config setting and try to connect with stripped list.
B. Get an error from the compiler indicating a configuration issue
C. Get an error code from mbedtls_ssl_config_defaults directly when using MBEDTLS_SSL_PRESET_SUITEB without having both curves enabled.

**Actual behavior**  

When performing the handshake the client will encounter "invalid curve in ssl configuration" and the handshake will fail.

**Steps to reproduce**  

Disable  MBEDTLS_ECP_DP_SECP384R1_ENABLED in the mbed config and setup a connection with MBEDTLS_SSL_PRESET_SUITEB as default config.

## Question(s)
- What is the purpose for the MBEDTLS_SSL_PRESET_SUITEB preset?
- Should MBEDTLS_SSL_PRESET_SUITEB still be usable in case SECP384R1 or SECP256R1 is disabled or is this considered an invalid configuration?

**Comment by RonEld** [comment]
Hi @dbedev as mentioned in [RFC6460](https://tools.ietf.org/html/rfc6460)
>The United States government has published guidelines for "NSA Suite
   B Cryptography" that define cryptographic algorithm policy for
   national security applications.

This RFC also mentions:
>A system compliant with the Suite B TLS and configured at a minimum
   level of security of 128 bits MUST use either ECDSA-256 or ECDSA-384
   for client or server authentication.

This means that at least one of these curves should be used. But nothing else, and it is not mandatory for both curves to be supported, so there shouldn't be an error if one of the curves is disabled, but the other curve is enabled.
It is reasonable that the handshake will fail, if the remote peer is trying to negotiate with a curve not part of the suite B profile. In addition, it is reasonable that a platform will not support one of the profiles, and still support the other profile, complying to SUITE B RFC.

**Comment by dbedev** [comment]
So do I undertand correctly that the predefined statics in ssl_tls.c:
ssl_preset_suiteb_hashes
ssl_preset_suiteb_curves
ssl_preset_suiteb_ciphersuites

Should at least have the MBEDTLS_XXX_C config flags to remove the unsupported crypto from the 
arrays if the library is built without support for the features ?

**Comment by RonEld** [comment]
@dbedev I am sorry, I don't understand what you mean. If you add the flag for `MBEDTLS_XXX_C ` in the configuration file, then the respected crypto module will be defined.
Do you mean to surround the `ssl_preset_suiteb_xxx` with `#if defined(MBEDTLS_XXX_C)`, same way it is done in [`supported_digests`](https://github.com/ARMmbed/mbedtls/blob/development/library/md.c#L59) for example?
If so, you *may* have a point, but it requires further look. Note that even without having this check, the feature will fail, if the respected `MBEDTLS_XXX_C` is not defined, in runtime

**Comment by dbedev** [comment]
Probably was not clear enough from the start, sorry for that.

Issue that we encounter is that a session using P256 certificates does not succeed when using the MBEDTLS_SSL_PRESET_SUITEB preset unless P384 is also enabled in the config for the client.

As it should be possible to operate whilst only having the P256 curve according to the above RFC6460 fragments. The suggestion is to at least modify ssl_tls.c line 7629 in a similar to what is done for supported_digests as you indicate:

#if defined(MBEDTLS_ECP_C)
static mbedtls_ecp_group_id ssl_preset_suiteb_curves[] = {
    MBEDTLS_ECP_DP_SECP256R1,
    MBEDTLS_ECP_DP_SECP384R1,
    MBEDTLS_ECP_DP_NONE
};
#endif

to

#if defined(MBEDTLS_ECP_C)
static mbedtls_ecp_group_id ssl_preset_suiteb_curves[] = {
#if defined(MBEDTLS_ECP_DP_SECP256R1_ENABLED)
    MBEDTLS_ECP_DP_SECP256R1,
#endif 
#if defined(MBEDTLS_ECP_DP_SECP384R1_ENABLED)
    MBEDTLS_ECP_DP_SECP384R1,
#endif 
    MBEDTLS_ECP_DP_NONE
};
#endif

This is a possible option to make sure the code does not encounter an unsupported curve whilst scanning the static array. For total correctness probably more is needed as there might be some similar issues with the other suite b predefined arrays.

**Comment by RonEld** [comment]
@dbedev As I said, you *may* have a point, but it requires further look. I believe that even without opting out these definition, you will not enable the specific modules, if they are not supported, because of `mbedtls_ssl_hash_from_md_alg`, for example, won't return the digest to the digest list. However, I tend to agree with you that it's better to add the guards as you mentioned, same way it's done for the default preset.
I am adding the bug label, since I agree it's a bug

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2270
