### ISSUE TITLE
Need automated tests for record compression

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1597]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

As discussed in PR #1592, there are no tests in the test system for record compression.

As @mpg states in the PR:

> We could add a build with zlib in all.sh and then run the existing "Large packet" tests from ssl-opt.sh and also add a test (conditional on zlib enabled) checking that compression is indeed used when enabled.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2242
