### ISSUE TITLE
Unused bits in asn1 bit string

### ISSUE THREAD

**Issue by moshe-shahar** [ARMmbed/mbedtls#1610]
### Description
- Type: Bug
- Priority: Minor

**mbed TLS build:**  
Version: 2.8.0 (latest)

---------------------------------------------------------------
## Bugs

The unused bits in [mbedtls_asn1_write_bitstring](https://github.com/ARMmbed/mbedtls/blob/84a1107818aaddfd2abe4c5a3478cf84ab2e26b4/library/asn1write.c#L309) are not as expected and should contain also the trailing zeros.
Tested against [Python cryptography library](https://cryptography.io/en/latest/)

From spec:
> Named bit lists are BIT STRINGs where the values have been assigned
   names.  This specification makes use of named bit lists in the
   definitions for the key usage, CRL distribution points, and freshest
   CRL certificate extensions, as well as the freshest CRL and issuing
   distribution point CRL extensions.  **When DER encoding a named bit
   list, trailing zeros MUST be omitted.**  That is, the encoded value
   ends with the last named bit that is set to one.

**Comment by RonEld** [comment]
For reference, the The quote is from [RFC5280 Appendix B](https://tools.ietf.org/html/rfc5280#appendix-B)

**Comment by RonEld** [comment]
@moshe-shahar Please specify what is the current behavior, what is the expected behavior and how to reproduce.

**Comment by moshe-shahar** [comment]
Current behavior is to set the _unused bits_ field in the DER to modulo 8 on bits argument.
Expected behavior is set the _unused bits_ field to include the trailing zeros.
Example for 1000000 bit string with 7 bits len:
Current  _unused bits_ is 1.
Expected is 7 (1+6 trailing zeros).

**Comment by trianglee** [comment]
@sbutcher-arm This defect is now biting us - we cannot encode a specific field we need to encode in a CSR. Is there any forecast to when this could be looked at?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2526

**Comment by hanno-arm** [comment]
@moshe-shahar I think we need to distinguish between raw bitstrings, which may include trailing zero bits, and named bit lists, for which such are forbidden in DER. Changing `mbedtls_asn1_write_bitstring()` to remove trailing bits doesn't seem to be the right approach to me. Instead, I think we should add a new pair of API calls for parsing and writing named bit lists. See #2028 for more details. Apologies if I mixed up things, please let me know if you see the matter differently.

**Comment by moshe-shahar** [comment]
@hanno-arm, I can't comment or suggest what is the correct fix since I'm not sure I'm familiar with all cases this library should support.
