### ISSUE TITLE
temp size check in mpi_montmul is incorrect

### ISSUE THREAD

**Issue by kwantam** [ARMmbed/mbedtls#1612]
https://github.com/ARMmbed/mbedtls/blob/84a1107818aaddfd2abe4c5a3478cf84ab2e26b4/library/bignum.c#L1571

`T` needs to be about 2x as big as `N`, but here the size check referenced above only enforces that `T` is about as big as `N`.

Notice how `d` is initialized to `T->p`:
https://github.com/ARMmbed/mbedtls/blob/84a1107818aaddfd2abe4c5a3478cf84ab2e26b4/library/bignum.c#L1576

and incremented `n = N->n` times:
https://github.com/ARMmbed/mbedtls/blob/84a1107818aaddfd2abe4c5a3478cf84ab2e26b4/library/bignum.c#L1591

and then after incrementing `d[0]` through `d[n]` are copied into `A->p`
https://github.com/ARMmbed/mbedtls/blob/84a1107818aaddfd2abe4c5a3478cf84ab2e26b4/library/bignum.c#L1594

This means that the copy reads up to `T->p[2*n-1]` (actually, because of the line where `d[n+1]` is set to 0, `T->p` needs to have size at least `2*N->n + 1`).

This is not currently a safety issue because only modular exponentiation actually calls `mpi_montmul`, and that function always ensures that `T` has sufficient size. So the defensive check is useless, but it isn't dangerous (until someone else decides to start using `mpi_montmul`).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2525

**Comment by hanno-arm** [comment]
@RonEld Why is this being closed without a single note?
