### ISSUE TITLE
mbedtls_ecdsa_write_signature not safe from memory overflow

### ISSUE THREAD

**Issue by moshe-shahar** [ARMmbed/mbedtls#1614]
### Description
- Type: Bug
- Priority: Major

mbed TLS build:
Version: 2.8.0 (latest)

---------------------------------------------------------------
## Bug

**Expected behavior**   
[mbedtls_ecdsa_write_signature](https://github.com/ARMmbed/mbedtls/blob/005239e3ed5edd6c3c152df73c30c65631b6c299/library/ecdsa.c#L341) return error if user buffer _sig_ is too small for writing signature

**Actual behavior**  
[mbedtls_ecdsa_write_signature](https://github.com/ARMmbed/mbedtls/blob/005239e3ed5edd6c3c152df73c30c65631b6c299/library/ecdsa.c#L341) not get the user buffer size and write the signature (in ecdsa_signature_to_asn1) to user buffer even if the buffer is too small.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2288

**Comment by gilles-peskine-arm** [comment]
Hi @moshe-shahar ,

`mbedtls_ecdsa_write_signature` doesn't know the length of its output buffer, so it has no way to check for overflow. That's unfortunate, but we can't change it without breaking the API.

The documentation of the function states the minimum size of the output buffer. It's up to the caller to pass a sufficiently large buffer.
