### ISSUE TITLE
IAR EWARM waning

### ISSUE THREAD

**Issue by rahmanih** [ARMmbed/mbedtls#1619]
Hi,

when compiling the mbedtls-2.9.0 with EWARM 8.20.2 there is the following warning:
`
Warning[Pa082]: undefined behavior: the order of volatile accesses is undefined in this statement mbedtls\include\mbedtls\ssl_internal.h 633 
`
could you please fix it?

regards
Haithem.

**Comment by RonEld** [comment]
@rahmanih Thank you for raising this issue!
We will look what is the best approach for this warning.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2289

**Comment by sbutcher-arm** [comment]
PR #1646 has now been merged into `development` so this issue can be closed.
