### ISSUE TITLE
`mbedtls_ctr_drbg_set_entropy_len` is redundant

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1649]
### Description
- Type: Bug
- Priority: Minor
The API `mbedtls_ctr_drbg_set_entropy_len` is redundant. 
When a user calls `mbedtls_ctr_drbg_seed` , it calls `mbedtls_ctr_drbg_seed_entropy_len` with `MBEDTLS_CTR_DRBG_ENTROPY_LEN` as entropy len. 
When a user calls `mbedtls_ctr_drbg_seed_entropy_len`, then they decide in this function what the entropy len is ( as the entropy_len in the context is overridden)

Both ways, `mbedtls_ctr_drbg_set_entropy_len` value is ignored

The only location where it is not ignored is if it is called before `mbedtls_ctr_drbg_reseed` , but in this case, it’s more dangerous for an error, by setting an invalid value, since it cannot exceed `MBEDTLS_ENTROPY_BLOCK_SIZE`
In addition, when calling `mbedtls_ctr_drbg_reseed` , it means that there was already a previous call to `mbedtls_ctr_drbg_seed`, and the entropy_len was already defined

---------------------------------------------------------------
## Bug \ Enhancement

**mbed TLS build:**  
Version: development

**Expected behavior**   
Deprecate `mbedtls_ctr_drbg_set_entropy_len` function

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2318
