### ISSUE TITLE
Incorrect `fscanf()` format string and data types in `programs/{aes,pkey}/...`

### ISSUE THREAD

**Issue by zv-io** [ARMmbed/mbedtls#1650]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.9.0 and development (2f3a5815674ab4cb37e773c521f9e753d43768c0)

In the following files:

1. `programs/aes/crypt_and_hash.c`
2. `programs/pkey/pk_decrypt.c`
3. `programs/pkey/rsa_decrypt.c`
4. `programs/pkey/rsa_verify.c`

there are several occurrences of `fscanf( f, "%02X", &c )` which are incorrect due to the data types used in the surrounding context. For example, `c` is declared as `int` and cast to `unsigned char`, while the format string `%02X` expects an integer. The appropriate format string is therefore `%02hhx`.

All four occurrences of this (with specific line numbers) may be found here: https://github.com/zv-io/mbedtls/commit/21a6457031a706ebe9abe9e85fd1eea5e243a1a4

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2323
