### ISSUE TITLE
VS build warning: uninitialized local variable in entropy.c

### ISSUE THREAD

**Issue by jwhui** [ARMmbed/mbedtls#1662]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS:**  
windows

**mbed TLS build:**  
Version: 2.9.0 
Configuration: [mbedtls-config.h](https://github.com/openthread/openthread/blob/master/third_party/mbedtls/mbedtls-config.h)
Compiler:  Microsoft (R) Build Engine version 14.0.25420.1
Build log: https://ci.appveyor.com/project/jwhui/openthread-owfg0/build/0.1.3068/job/05t5ottl504ji6ps

**Expected behavior**   
No compiler warnings.

**Actual behavior**  
```
c:\projects\openthread-owfg0\third_party\mbedtls\repo\library\entropy.c(305): error C2220: warning treated as error - no 'object' file generated [C:\projects\openthread-owfg0\etc\visual-studio\mbedtls_k.vcxproj]
c:\projects\openthread-owfg0\third_party\mbedtls\repo\library\entropy.c(305): warning C4701: potentially uninitialized local variable 'ret' used [C:\projects\openthread-owfg0\etc\visual-studio\mbedtls_k.vcxproj]
```

**Comment by RonEld** [comment]
@jwhui Thank you for reporting this issue!

Note that this warning is a false positive, since although `ret` is not initialized, it will *always* be assigned.
Whether `source_count > 0` and then it will be set with `ret = ctx->source[i].f_source()`, or whether `have_one_strong == 0`.

Nonetheless, since you get this build error, I am marking it as a bug. Note that #858 addresses similar issues

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2327

**Comment by jwhui** [comment]
@RonEld, thanks for your response!

**Comment by irwir** [comment]
Will the compiler stop complaining if the line 265 changes to
`if( ctx->source_count <= 0 )` ?

**Comment by jwhui** [comment]
@irwir, I just tested this change.  Unfortunately, it results in the same compiler warning.

Change: https://github.com/jwhui/openthread/commit/9999408d8d60d3258dfbec2c9fab20badaf17307
Build log: https://ci.appveyor.com/project/jwhui/openthread-owfg0/build/0.1.3071/job/wb8duif1631wajg4

**Comment by irwir** [comment]
@jwhui, thanks for testing.
Should be a compiler's bug, because VS 2017 15.7.2 issues no such warning when building `mbedtls.vcxproj` project with unmodified code.

Initialization of `ret` in declaration might "fix" the blocking bug for your testing case, but this is not good enough as a general solution.

**Comment by jwhui** [comment]
FWIW, I validated that initializing `ret` at declaration eliminates the warning.  To be clear, I do agree that the compiler warning is a false positive.  While this appears to be fixed in VS 2017, our project currently requires Visual Studio 2015.  Any thoughts on how to proceed?

**Comment by irwir** [comment]
By a general solution I was implying that this library should not make changes for every buggy compiler.

mbedTLS.vcxpoj uses `/W3 /WX-` options, which is "level 3 warnings" and "do not treat warning as errors".
openthread's project uses much tougher options `/W4 /WX`. That enables a few additional warnings, and "treat warnings as errors".
Therefore, maybe this issue does not deserve a `bug` label.

> Any thoughts on how to proceed?

You changed project options, so fix the issue in the project.
That could be:
lower warning level back to /W3;
or disable specific warning(s) for the project;
or, disable specific warning(s) for `entorpy.c` only.

**Comment by jwhui** [comment]
Thanks for pointing that out.  I dropped the warning level to 3 in our mbedtls build and we're good now.

**Comment by irwir** [comment]
@RonEld,
it would be good to apply the change mentioned earlier. This one:

> Will the compiler stop complaining if the line 265 changes to
> if( ctx->source_count <= 0 ) ?

The reasons are:

- early return
- better error code value ("no sources" instead of "no strong source").
