### ISSUE TITLE
Remove reference to yotta for Mbed OS

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbedtls#1675]
- Type: Bug
- Priority: Major 

## Bug

**Documentation**

Documentation states that yotta is required for Mbed OS
https://github.com/ARMmbed/mbedtls/blob/master/README.md

Doc linked from:
- https://github.com/ARMmbed/mbed-os/blob/master/features/mbedtls/README.md
- https://os-doc-builder.test.mbed.com/docs/latest/reference/mbed-tls-entropy.html
- https://os-doc-builder.test.mbed.com/docs/latest/reference/hardware-accelerated-crypto.html

This is not true and should be removed

@iriark01 @AnotherButler

**Comment by adbridge** [comment]
@sbutcher-arm Could you comment on this please? Are the references there for older build support for TLS or can they just be removed for mbed-os docs?

**Comment by sbutcher-arm** [comment]
We have an open PR to remove yotta support and references to yotta. That work is ongoing and is being resolved by PR #1609.

I don't think it's fair to say that the documentation 'states that yotta is required for Mbed OS'. It actually says Yotta is *a* supported build system and is used by Mbed OS 16.03, which was the old version numbering scheme for Mbed OS. I will agree it is misleading, and we're working to remove it.

This can't happen any earlier than Mbed OS 5.10 though, as to change the documentation in Mbed OS we need to release a new version of Mbed TLS into Mbed OS.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2344

**Comment by RonEld** [comment]
PR #1609 has been merged, so closing this
