### ISSUE TITLE
DRBG - 'reseed_interval' and 'reseed_counter' types don't allow the use of maximum size according to the standard

### ISSUE THREAD

**Issue by NirEkhauz** [ARMmbed/mbedtls#1676]
DRBG - 'reseed_interval' and 'reseed_counter' types don't allow the use of maximum size according to the standard
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
According to NIST SP 800-90A (table 2 ch. 10.1, and table 3 ch. 10.2), the maximum number of requests between reseeds is 2^48, but in both drbg mechanisms (ctr and hmac), reseed_interval and reseed_counter are defined as "int" (which in some implementations will allow maximum size 2^32).

[Table - 2.pptx](https://github.com/ARMmbed/mbedtls/files/2068101/Table.-.2.pptx)

**OS**  
linux

**mbed TLS build:**  
Version: 2.9.0 
Configuration: please attach config.h file where possible  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request
**Suggested enhancement**  
Need to change the 'int' type to 'unsigned long'

-----------------------------------------------------------------

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2343
