### ISSUE TITLE
Coverity branches fail Travis tests with check-files.py

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1691]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

New versions of the `development` branch pushed to the `coverity_scan` branch fail the Travis checks because the `check-files.py` script is finding Coverity intermediate files in the `./cov-int/` directory, and failing on them.

The script needs to ignore the coverity directory, or alternatively, not be run.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2342
