### ISSUE TITLE
check-files.py should ignore contents of .git directory

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#1697]
### Description
- Type: Bug
- Priority:  Major

The new test script `tests/scripts/check-files.py` currently throws error if one of the git branches in one of my remotes has a name that ends with of on the checked extension. For example, I currently have a branch name `cleanup-all.sh` in one of my remotes and it's too late to rename it, as there is already a PR for that branch (with non-trivial review history, so I can't just close it and open a new PR) and github doesn't allow changing the source branch of a PR once it's open.

## Bug

**Steps to reproduce**  

```
git remote add https://github.com/mpg/mbedtls/
git fetch mpg
tests/scripts/check-files.py
```

**Expected behavior**   
Should not throw any error (assuming the branch currently checked out is clean).

**Actual behavior**  
Throws errors such as:

```
Incorrect permissions:
./.git/logs/refs/remotes/mpg/cleanup-all.sh
./.git/refs/remotes/mpg/cleanup-all.sh

Tabs present:
./.git/logs/refs/remotes/mpg/cleanup-all.sh: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
```

**Comment by mpg** [comment]
@dgreen-arm do you agree? If so, do you think this would be easy to fix?

**Comment by dgreen-arm** [comment]
Yes, it should ignore the .git directory, it isn't part of the codebase. It should be a simple fix to do, I've had a look at it already due to a similar issue with the coverity-scan branch.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2356

**Comment by yanesca** [comment]
Fixed in https://github.com/ARMmbed/mbedtls/pull/2031.
