### ISSUE TITLE
vs2010, _M_AMD64, _M_X64

### ISSUE THREAD

**Issue by dhhome2006** [ARMmbed/mbedtls#1705]
### Description
- Type    : Bug
- Priority: Minor

## Bug
**OS**  
windows xp sp3

**mbed TLS build:**  
Version : mbedtls-2.9.0-apache.tgz
Compiler: vs2010, x64 target

{{{
package : mbedtls-2.9.0-apache.tgz
file    : bignum.h
line    : 115

current code:
    #if defined(_MSC_VER) && defined(_M_AMD64)
fixed code:
    #if defined(_MSC_VER) && (defined(_M_AMD64) || defined(_M_X64))

in vs2008, the _M_AMD64 is defined; in vs2010, it isn’t.
}}}

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2359

**Comment by irwir** [comment]
According to MSDN blogs, these macros should be equivalent.
`_M_AMD64` appeared first, but was superceded with `_M_X64.

Some microseconds could be saved if the conditions were reordered: 
`#if defined(_MSC_VER) && (defined(_M_X64) || defined(_M_AMD64))`

**Comment by RonEld** [comment]
This issue is not reproducible on our tests, and Windows XP is not a supported platform by Mbed TLS, however contributions from the community are welcome
