### ISSUE TITLE
Mbed TLS uses system time, instead of GMT, when available

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1714]
### Description
- Type: Bug 
- Priority: Minor
Raised by Email by 不幻想了

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.6.0
OS version: Ununto 16.04.3
Additional environment information:  GCC 5.4.0

**Expected behavior**   
GMT time is used when networking is available and GMT time is available. Use local system time when GMT time is not available.
Rfc5280 document：
>For the purposes of this profile, UTCTime values MUST be expressed in Greenwich Mean Time (Zulu) and MUST include seconds (i.e., times are YYMMDDHHMMSSZ), even where the number of seconds is zero.
 

**Actual behavior**  
When validating the validity period, MbedTLS dose not use GMT(Greenwich Mean Time, the mean solar time at the Royal Observatory in Greenwich, London), instead, it uses system local time。
**Steps to reproduce**

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2361
