### ISSUE TITLE
all.sh does not fail when GDB zeroize test does

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#1723]
### Description
- Type: Bug
- Priority: Major

GDB returns 0 (success) to the system even if the gdb script for testing whether a buffer was zeroized failed. It looks like this is caused by a bug in GDB reported [here](https://sourceware.org/bugzilla/show_bug.cgi?id=13000) when running the tool with the `-batch` argument and not by the gdb script `test_zeroize.gdb`.

---------------------------------------------------------------
## Bug

**Expected behavior** 
Executions of the zeroize test should return a failure code to the system if the gdb script failed.

**Actual behavior**  
gdb return 0 (success) even if the gdb script for zeroize testing failed.

**Steps to reproduce**  
The following commands should cause the zeroize test to fail because the library was compiled without symbols, but GDB still reports it as success by returning 0 to the system.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2363

**Comment by sbutcher-arm** [comment]
PR #1724 has now been merged so this issue can be closed.

It's worth noting while the PR fixed the issue, it also uncovered another issue in #1880! But that's a different bug, so not worth keeping this one open.
