### ISSUE TITLE
Misdocumented return value for ECDSA verification

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#1725]
### Description
- Type: Bug
- Priority: Minor

## Bug

The documentation for `mbedtls_ecdsa_verify()` states that the function return `MBEDTLS_ERR_ECP_BAD_INPUT_DATA` if the signature was invalid. This is not correct. The value returned on invalid signature is `MBEDTLS_ERR_ECP_VERIFY_FAILED`. The value `MBEDTLS_ERR_ECP_BAD_INPUT_DATA` indicates that the input data was otherwise invalid (for example trying to verify a signature with a Montgomery curve).

This issue is present in development, 2.7 and 2.1.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2362
