### ISSUE TITLE
missing documentation for flags in x509 verification

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1756]
### Description
- Type: Bug
- Priority: Minor

Raised by Christoph Rüdiger in the [forum](https://forums.mbed.com/t/hardfault-on-stm32f103/3074)

`mbedtls_x509_crt_verify_with_profile` does not mention that `flags` is a mandatory field, and cannot be `NULL`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2369

**Comment by Patater** [comment]
The approach we are taking in documenting our parameters is to not document when something is required, since that's most of the the time, but instead to document when it's optional. If a parameter is not documented as being nullable, it should be assumed that the parameter is required.
