### ISSUE TITLE
Dangling 'else' in ecp.c

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#1776]
https://github.com/ARMmbed/mbedtls/blob/8266acacc8d6e1c65fba9a048f56339d0827b2fe/library/ecp.c#L1895

Static analysers might find this line suspicious:
-  `else` after `return` statement is redundant
 - an empty line after `else` is possibly a missing or forgotten statement

The suggestion is to delete the  line.

**Comment by RonEld** [comment]
@irwir  thank you for reporting this!
This isn't a dangling `else` statement, as the compiler will regard this as an `else` for the `if` statement, and run the next statement ( in line 1897 ) as the `else`. So deleting this line will result in a different functionality. ( perhaps the intended one )
I agree this is not readable, and might not what the author intended.
We will look into this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2372

**Comment by irwir** [comment]
@RonEld
> This isn't a dangling else statement, as the compiler will regard this as an `else` for the `if` statement

Commonly used styles do not add empty lines after `else` keyword.
It could be that a programmer reserved a place for a statement, but got distracted and forgot to write a statement.
In that sense it is "dangling", and this is the reason to be flagged in static analysys.

> So deleting this line will result in a different functionality.

Could you give an example when deleting this `else` would change functionality?

**Comment by irwir** [comment]
> But I see your point, because if A is true, then we return and exit the function, so in this specific use case, there is no rel change in the functionality with your suggestion.

Yes.
If linear execution order is always broken in the block after `if A`, then the following  `else` is redundant.
Presense of that `else` becomes strictly a matter of style.
