### ISSUE TITLE
CRL not validated in x509_crt_verifycrl

### ISSUE THREAD

**Issue by HenrikRosenquistAndersson** [ARMmbed/mbedtls#1784]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.7.2

**Expected behavior**   
CRL is used for validation

**Actual behavior**  
CRL is not used

**Steps to reproduce**  
I went to www.renesas.com and downloaded the certificate chain and the CRLs.

When validating the chain I passed in root CA and the CRLs (From digicert)
When debugging I noticed that the CRL validation in (x509_crt_verifycrl) was bypassed.

The root CA has subject
C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
While the CRL has issuer
/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA

The name comparison fails due to this. If changing to use the x509_name_cmp function instead the validation progresses further.

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
Security bug not to use valid CRLs

**Suggested enhancement**  
Call x509_name_cmp instead.
-----------------------------------------------------------------

**Comment by RonEld** [comment]
@HenrikRosenquistAndersson Thank you for reporting this issue!
We will have a look at it

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2381

**Comment by hanno-arm** [comment]
Updated internal reference: IOTSSL-1770.

**Comment by hanno-arm** [comment]
Hi @HenrikRosenquistAndersson,

which tools did you use to print the subject and issuer information? I want to make sure the issue is not related to the use of `/` vs. `,` as a separator. Rather, it looks like this is due to a different character encoding used in the CRT and CRL, e.g. `PrintableString` vs. `UTF8String`. You could check this by calling `dumpasn1` on the (DER-encoded) CRT and CRL.

Kind regards,
Hanno, Mbed TLS team member

**Comment by HenrikRosenquistAndersson** [comment]
Hi,
I think I printed the information from openssl and mbedtls_x509_dn_gets.
I added logs into x509_crt_verifycrl and verified that the memcmp failed.

Here are the start of the asn1dumps. Let me know if you need more of the dumps.

CRL
  0 527: SEQUENCE {
  4 248:   SEQUENCE {
  7   1:     INTEGER 1
 10  13:     SEQUENCE {
 12   9:       OBJECT IDENTIFIER '1 2 840 113549 1 1 5'
 23   0:       NULL
       :       }
 25  97:     SEQUENCE {
 27  11:       SET {
 29   9:         SEQUENCE {
 31   3:           OBJECT IDENTIFIER '2 5 4 6'
 36   2:           PrintableString 'US'
       :           }
       :         }
 40  21:       SET {
 42  19:         SEQUENCE {
 44   3:           OBJECT IDENTIFIER '2 5 4 10'
 49  12:           PrintableString 'DigiCert Inc'
       :           }
       :         }
 63  25:       SET {
 65  23:         SEQUENCE {
 67   3:           OBJECT IDENTIFIER '2 5 4 11'
 72  16:           PrintableString 'www.digicert.com'
       :           }
       :         }
 90  32:       SET {
 92  30:         SEQUENCE {
 94   3:           OBJECT IDENTIFIER '2 5 4 3'
 99  23:           PrintableString 'DigiCert Global Root CA'
       :           }
       :         }
       :       }
124  13:     UTCTime 18/06/2018 17:00:00 GMT
139  13:     UTCTime 09/07/2018 17:00:00 GMT

Certificate
   0 1163: SEQUENCE {
   4  883:   SEQUENCE {
   8    3:     [0] {
  10    1:       INTEGER 2
         :       }
  13   16:     INTEGER 05 46 FE 18 23 F7 E1 94 1D A3 9F CE 14 C4 61 73
  31   13:     SEQUENCE {
  33    9:       OBJECT IDENTIFIER '1 2 840 113549 1 1 11'
  44    0:       NULL
         :       }
  46   97:     SEQUENCE {
  48   11:       SET {
  50    9:         SEQUENCE {
  52    3:           OBJECT IDENTIFIER '2 5 4 6'
  57    2:           PrintableString 'US'
         :           }
         :         }
  61   21:       SET {
  63   19:         SEQUENCE {
  65    3:           OBJECT IDENTIFIER '2 5 4 10'
  70   12:           PrintableString 'DigiCert Inc'
         :           }
         :         }
  84   25:       SET {
  86   23:         SEQUENCE {
  88    3:           OBJECT IDENTIFIER '2 5 4 11'
  93   16:           PrintableString 'www.digicert.com'
         :           }
         :         }
 111   32:       SET {
 113   30:         SEQUENCE {
 115    3:           OBJECT IDENTIFIER '2 5 4 3'
 120   23:           PrintableString 'DigiCert Global Root CA'
         :           }
         :         }
         :       }
 145   30:     SEQUENCE {
 147   13:       UTCTime 06/11/2017 12:23:45 GMT
 162   13:       UTCTime 06/11/2027 12:23:45 GMT
         :       }

**Comment by hanno-arm** [comment]
Hi @HenrikRosenquistAndersson,

apologies for the long response time. I agree that the `memcmp()` in `x509_crt_verifycrl()` is too strong, but I cannot yet align this bug with the failure you're seeing, as I don't spot any binary difference in the dumps you showed. Could you point me to those if I'm missing the obvious, or attach PEM encodings of the actual CRL and CA?

Regards,
Hanno

**Comment by HenrikRosenquistAndersson** [comment]
I'm not able to reproduce this issue anymore when downloading the certificate chain today. I unfortunally don't have the old chain anymore. So I Think you can close the issue.

**Comment by hanno-arm** [comment]
@HenrikRosenquistAndersson You have made a very important point, though, that the comparison of CRL issuer and CA subject name is too strict, and I have created PR #2167 to address this.

Could you let me know how you would like to be credited?

**Comment by HenrikRosenquistAndersson** [comment]
You can just mention my email address (Henrik.Andersson@se.bosch.com). Thanks!

**Comment by sbutcher-arm** [comment]
Hi @HenrikRosenquistAndersson. We don't normally credit people by email address. Can I suggest we credit you as `Henrik Andersson of Bosch GmbH`?

**Comment by HenrikRosenquistAndersson** [comment]
Works fine for me
