### ISSUE TITLE
ctr_drbg_update returns void, even though it could fail

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#1798]
### Description
- Type: Bug 
- Priority: Major 
as raised in https://github.com/ARMmbed/mbedtls/pull/1096#discussion_r197245452 , `ctr_drbg_update()` returns void, even though  a call to `ctr_drbg_update_internal()` might fail

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows

**Suggested solutionr**   
Create a new function that return an error in case `ctr_drbg_update_internal()` fails

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2375
