### ISSUE TITLE
Is Hardware accelerator protected against concurrency when multi threading support enabled

### ISSUE THREAD

**Issue by umanayana** [ARMmbed/mbedtls#1807]
I'm using mbedtls in a RTOS environment. 
I need to add hardware acceleration port for AES and SHA256. These two accelerators are implemented by the same accelerator unit in the MCU. Thus only one thread can be using the accelerator at any point in time. 
So my question is if I add the port to use the accelerator will mbed multi-threading support correctly protect against concurrent access across threads? 
This is especially a concern when AES encryption/decryption because it's a multi-step process, where the key has to be set first and then the encryption/decryption has to occur. When the key is set it has to make sure to lock a mutex which protects against all other calls wanting to use the hardware accelerator, until the encryption/decryption has finished. 

Please note I do not plan on using the hardware accelerator outside the context of mbedtls library.

Thanks

**Comment by RonEld** [comment]
@umanayana The AES and SHA256 in Mbed TLS do not use any globals, and as such, are thread safe.
If your specific HW accelerator requires only one thread to access the HW, I suggest you add the protection in your alternative implementation.
I could think of initializing a global mutex in the `mbedtls_platform_setup()`  alternative implementation, and in your AES and SHA256 alternative implementations, use this mutex.

**Comment by umanayana** [comment]
Hi roneld

Why would I need a global mutex if I enable MBEDTLS_THREADING_ALT. Isn't the point of this to mutex protect resources? 

The problem with your approach is that for any call  to mbed TLS I need to first lock this global mutex but what if the call hierarchy never uses the hardware accelerator. That mean I will technically be locking out any threads from using mbedtls even though the hardware accelerator is not used. This will drastically kill performance.

My main concern is when AES needs to be used because it's a multistep process between setting the key and encrypt/decrypt. That means any calls to setting the key must lock the hardware and only unlock it after it has finished encrypt/decrypt.

**Comment by RonEld** [comment]
Hi @umanayana The point of `MBEDTLS_THREADING` is to protect the Mbed TLS resources. You are trying to protect the HW resources, in your alternative implementation.
There isn't a mutex in the SW implementation of AES and SHA, as there is no resource to protect there, and adding a resource would affect performance.
I was talking about a global mutex, because my understanding is that you can't access the HW for both AES and SHA concurrent oprations. If the AES and SHA can run on your HW, you can have a seperate mutex in your alternative module context.

>The problem with your approach is that for any call to mbed TLS I need to first lock this global mutex but what if the call hierarchy never uses the hardware accelerator. 

This isn't my approach. My approach is to have a global mutex that can be reached from the AES and SHA256 alternative implementations. "You lock the mutex in *your alternative implementation* of AES and SHA256, before accessing the HW and release the mutex after finishing the access.

>My main concern is when AES needs to be used because it's a multistep process between setting the key and encrypt/decrypt. That means any calls to setting the key must lock the hardware and only unlock it after it has finished encrypt/decrypt.

As mentioned in previous answer, you should only lock before accessing the HW. I would suggest not locking the set key API, and only store the key in the context. in your encrypt \ decrypt operation, lock mutex, load the key to the HW, and then do the operation. After operation ends, unlock mutex.

**Comment by umanayana** [comment]
Hi @RonEld, 

> As mentioned in previous answer, you should only lock before accessing the HW. I would suggest not locking the set key API, and only store the key in the context. in your encrypt \ decrypt operation, lock mutex, load the key to the HW, and then do the operation. After operation ends, unlock mutex.

I like this approach as this is the approach I wanted to take initially, that is set the key and do the descrypt/encrypt all at the same time. In the `mbedtls_aes_context` should I just add a new entry that can store the key? I prefer to not modify the library as this will make it a little harder for upgrading. 

> The point of MBEDTLS_THREADING is to protect the Mbed TLS resources.

So if every thread uses it own context for utilise mbedtls is it safe to assume I do not need to enable `MBEDTLS_THREADING`

**Comment by RonEld** [comment]
Hi @umanayana 
>that is set the key and do the descrypt/encrypt all at the same time

If you mean set the key in the HW, then yes. but `mbedtls_aes_setkey_enc()` and `mbedtls_aes_setkey_dec()` should be called seperate. In your implementation of these functions, you should proabably copy the key to a buffer stored in your alternative definition of `mbedtls_aes_context`
The idea of having `mbedtls_aes_context ` defined in `aes_alt.h` when you define `MBEDTLS_AES_ALT` is for you to define this context as you need for your alternative implementation.
I suggest you read [this article](https://tls.mbed.org/kb/development/hw_acc_guidelines)

> is it safe to assume I do not need to enable `MBEDTLS_THREADING`

If you are working in a multithreaded environment, it is better you define `MBEDTLS_THREADING` for other resources you would like to protect, such as resources in hmac.
If all the modules you need are AES and SHA256, then you probably don't need `MBEDTLS_THREADING`, but it is dependant on what SW modules you need from Mbed TLS.

**Comment by RonEld** [comment]
Closing this issue, as I believe the question was answered.
If you believe this issue deserves further action, please reopen.
