### ISSUE TITLE
Please help me with an Aes-CFB problem   T_T 

### ISSUE THREAD

**Issue by neo1986** [ARMmbed/mbedtls#181]
#include <iostream>
#include <cstring>
#include "aes.h"

int main(int argc, const char** argv)
{
    unsigned char text[64] = " hello world !";
    unsigned char  key[64] = {0};
    unsigned char  iv[16] = {0};
    
    aes_context ctx;
    memset( key, 0, 32 );
    aes_init( &ctx );
    
    size_t offset = 0;
    unsigned char encode_buf[64] = {0};
    aes_setkey_enc(&ctx, key, 128);
//  aes_crypt_cbc(&ctx, AES_ENCRYPT, 64, iv,text,encode_buf); // it's ok for cbc
    aes_crypt_cfb128(&ctx, AES_ENCRYPT, 64,&offset,iv, text, encode_buf);
    std::cout << "encode == " << encode_buf << std::endl;
    
    offset = 0;
    memset(iv, 0, 16);
    unsigned char ret_buf[64] = {0};
    aes_setkey_dec(&ctx, key, 128);
//  aes_crypt_cbc(&ctx,AES_DECRYPT,64,iv,encode_buf,ret_buf); // it's ok for cbc
    aes_crypt_cfb128(&ctx, AES_DECRYPT, 64,&offset,iv, encode_buf,ret_buf );
    std::cout << "decode == " << ret_buf << std::endl;
    
return 0;
}

It's ok for using aes_crypt_cbc, but aes_crypt_cfb128 failed ! I have see the example in the aes.c for long time ! Do I misused this API ?  Please give me an example like codes I wrote, please !  please help me !

**Comment by pjbakker** [comment]
For CFB mode you have to use ENCRYPT mode for decryption as well!

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No: 2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No: 2548782

**Comment by neo1986** [comment]
Could you give an easy example ? Just encode a string and decode it with CFB

**Comment by neo1986** [comment]
Sorry to bother you ! Could you give an easy example by encoding a string and decoding it with Aes-CFB ?

**Comment by pjbakker** [comment]
Please use the forum for these kind of questions at https://tls.mbed.org/discussions
This is not a software issue.
