### ISSUE TITLE
Can't connect using public IP via UDP on Windows 10

### ISSUE THREAD

**Issue by Wizzard033** [ARMmbed/mbedtls#1817]
- Type: Bug
- Priority: Major

---------------------------------------------------------------

**OS**  
Windows 10

**mbed TLS build:**  
Version: 2.8.0
OS version: 10.0.17134
Built with MinGW

**Expected behavior**   
Connects to the server using my public IP
(as can be done with any other UDP application and networking library, tested thoroughly)

**Actual behavior**  
I can only connect using the local interface I have bound to.

For example
If I bind to "0.0.0.0" then I can connect to my local IP i.e. 192.168.0.178
If I bind to "127.0.0.1" then I can connect to 127.0.0.1 (but not my local IP)
Please note if the interface is left NULL, then I cannot connect to myself via any IP
When my colleague tried binding to "0.0.0.0", only 127.0.0.1 worked for connecting

**Steps to reproduce**  
Use the DTLS client and server demo on Windows 10, and optionally try binding to other interfaces

**Remarks**  
I think I'm going to not use the net_sockets.h implementation anymore.
It seems to be buggy in Windows and Mac OS, see #1246 and #977

**Comment by RonEld** [comment]
@Wizzard033 Thank you for reporting this!

I believe this issue is a duplicate of your own issue #977 and that #1627  resolves this issue.
Do you see this issue different than your previous opened issue?

**Comment by Wizzard033** [comment]
No. This is a separate issue. #1627 solves the issue with being able to run the demo. However, the demo is limited to work only from one PC for me (when using the build above). The server cannot be connected to from the internet for whatever reason. The IP "127.0.0.1" will work for connecting to the server,, but the public IP address of the server will not. Therefore, the server demo application cannot be on a different computer than the client demo application and still work.

**Comment by Wizzard033** [comment]
When I bind to "0.0.0.0", it should bind to all interfaces, and therefore connecting from the internet should be possible, but for some reason in my build setup it does not work. Of course, I also change the IP the client is connecting to.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2380

**Comment by Wizzard033** [comment]
After investigating a bit, it seems that my issue was with using a port number larger than 49151.
I'm not sure if it's common knowledge to use ports in the registered range,
but either way I'm happy that I finally found out why I couldn't connect to my server via public IP.
I had been changing the examples to use that port due to it being assigned by my server provider.
