### ISSUE TITLE
ssl server example not working on embedded platform

### ISSUE THREAD

**Issue by nieknooijens** [ARMmbed/mbedtls#1826]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
- Priority:  Minor

Hi there,

I'm trying to run this example onto our embedded LPC1768 board using freeRTOS:
https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_server.c
so far I can't even get beyond line 145, the mbedtls_test_srv_crt parses correctly, but the mbedtls_test_cas_pem returns -10368. I tried different certificates, both created with openSSL or with http://www.selfsignedcertificate.com/ and none of them work. But it's particularity intresting that the test certificate included with the example, does not work!

---------------------------------------------------------------
## Bug
test certificate in mbedTLS doesn't work.

**OS**  
FreeRTOS

**mbed TLS build:**  
Version: 2.9.0 
OS version: 9.0
Configuration: [mbedtls_config.h.txt](https://github.com/ARMmbed/mbedtls/files/2154508/mbedtls_config.h.txt)

Additional environment information:  
CPU: LPC1768

**Expected behavior**   
test certificate returns 0 on mbedtls_x509_crt_parse

**Actual behavior**  
test certificate returns -10368 on mbedtls_x509_crt_parse

**Steps to reproduce**  
create a freeRTOS thread on your embedded system of choice and point it to a renamed main function containing the example. from https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_server.c

## Question

no solution found in knowledge base and forums

**Comment by RonEld** [comment]
@nieknooijens 
The sample application were written as reference and tested on Linux and windows. Some of them require FS, some of them use the BSD sockets.
In order to make them work, you will need to adjust them to work on your platform. 
The error you are receiving is `-0x2880`, which is `MBEDTLS_ERR_X509_ALLOC_FAILED`
I suggest you try working with DER encoded certificates instead of PEM, and this will reduce some of your heap usage.

**Comment by nieknooijens** [comment]
@RonEld thanks for the quick reply, I did some research and it appears that I do have enough memory, but the malloc/calloc wrappers dump it onto the wrong rambank which is why I get the MBEDTLS_ERR_X509_ALLOC_FAILED. So i'll need to investigate further how I can fix this, but this issue is solved for now.
