### ISSUE TITLE
aes.c aes_setkey_enc() generates too many round keys

### ISSUE THREAD

**Issue by vividdream** [ARMmbed/mbedtls#183]
The total number of round keys for 128, 192 and 256 bit keys are 44, 52 and 60 respectively. However aes_setkey_enc() creates, 44, 54 and 64 respectively.

This doesn't cause any errors because as far as I can see it's intentional, since aes_context can hold 8 more round keys than it should, preventing an overflow. 

Is it really worth it to not implement better logic? All that's needed are:
1/ "if( i+1 == 8 ) break;" after https://github.com/ARMmbed/mbedtls/blob/development/library/aes.c#L557
2/ "if( i+1 == 7 ) break;" after https://github.com/ARMmbed/mbedtls/blob/development/library/aes.c#L575

**Comment by mpg** [comment]
Actually a bit more that that is needed, see aesni.c and padlock.c.

**Comment by mpg** [comment]
Closing as I think the current size in aes_context makes it easier on alternative implementations, and since there is room, why not use it ourselves?

Please feel free to re-open and try to convince me if you disagree.
