### ISSUE TITLE
DTLS example handshake failed sometimes

### ISSUE THREAD

**Issue by xiaoyanhao** [ARMmbed/mbedtls#1830]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.6.0
OS version: 14.04 LTS
Configuration: default config.h

**Expected behavior**   
Successful handshake every time.
**Actual behavior**  
Occasionally, `dtls_server` accepted an **additional** remote connection and then handshake failed.
It seemed that an alert message (type=21) has been received by the server.
```
. Waiting for a remote connection ... ok
. Performing the DTLS handshake...
ssl_tls.c:6557: => handshake
ssl_srv.c:4016: server state: 0
ssl_tls.c:2416: => flush output
ssl_tls.c:2428: <= flush output
ssl_srv.c:4016: server state: 1
ssl_tls.c:2416: => flush output
ssl_tls.c:2428: <= flush output
ssl_srv.c:1190: => parse client hello
ssl_tls.c:2208: => fetch input
ssl_tls.c:2269: in_left: 0, nb_want: 5
ssl_tls.c:2307: f_recv_timeout: 0 ms
ssl_tls.c:2315: ssl->f_recv(_timeout)() returned 39 (-0xffffffd9)
ssl_tls.c:2403: <= fetch input
ssl_srv.c:1234: client hello v3, message type: 21
ssl_srv.c:1238: bad client hello message
ssl_tls.c:6567: <= handshake
failed
! mbedtls_ssl_handshake returned -0x7900

Last error was: -30976 - SSL - Processing of the ClientHello handshake message failed
```
**Steps to reproduce**  
1. start `dtls_server` program
2. try to start `dtls_client` program several times

**Comment by RonEld** [comment]
@xiaoyanhao Thank you for raising this issue!
WE will look into this

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2382

**Comment by xiaoyanhao** [comment]
@RonEld 
I have found that it is not a bug about the library but `mbedtls_ssl_close_notify` from `dtls_client` program results in it.

After the first successful handshake, sometimes `dtls_server` may free the socket fast and then continue to wait for a new connection.
Meanwhile, `dtls_client` is possibly just calling `mbedtls_ssl_close_notify` to send an alert message to the server with the same port. As a result, `dtls_server` receives this new packet as a ClientHello handshake message and the so-called **additional** handshake fails.

There will be no additional failed handshake if I comment the below code snippet in **dtls_client.c**.
```c
close_notify:
    mbedtls_printf( "  . Closing the connection..." );

    /* No error checking, the connection might be closed already */
    do ret = mbedtls_ssl_close_notify( &ssl );
    while( ret == MBEDTLS_ERR_SSL_WANT_WRITE );
    ret = 0;

    mbedtls_printf( " done\n" );

```
