### ISSUE TITLE
Add README explaining test suites input files format

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbedtls#1841]
Mbed TLS test suites use source and data files in `tests/suites/`. Their format needs to documented for development and maintenance purpose. Since #930 changes the framework this issue should be worked after #930 is merged.

Documentation should include:
- All relevant file formats
- generate_test_code.py limitations/assumptions
- Guideline for creating new tests: data & functions.

**Comment by gilles-peskine-arm** [comment]
While it isn't exactly what was originally requested, I'm marking this task as fulfilled by https://tls.mbed.org/kb/development/test_suites . It documents the relevant file format, and includes some guidelines for writing tests.

I've filed https://github.com/ARMmbed/mbedtls/issues/3618 to improve the documentation with some non-obvious cases.
