### ISSUE TITLE
C++ header test doesn't clean up

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1862]
### Description
- Type: Bug
- Priority: Minor

@gilles-peskine-arm has raised the following point in review of PR #1454, 'Add a test with a cpp executable including all mbed TLS headers'.

> If you run make TEST_CPP=1 and later make clean, then test/cpp_dummy_build doesn't get cleaned. > There's a similar preexisting defect with ssl/ssl_pthread_server. The defect with test/cpp_dummy_build is worse because we include it in our test scripts.

As described by @gilles-peskine-arm, a possible remedy is to:

> arrange for make clean to remove test/cpp_dummy_build (and ssl/ssl_pthread_server) regardless of the value of TEST_CPP;

Note, this is an issue for a PR that hasn't yet been merged at the time of writing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2395
