### ISSUE TITLE
Visual Studio Community 2013: o_p_test.c(56): Cannot open include file: 'unistd.h'

### ISSUE THREAD

**Issue by ac** [ARMmbed/mbedtls#188]
> cmake .
> MSBuild.exe MBEDTLS.sln 
[...] 1 warning, 1 error:
mbedtls\programs\test\o_p_test.c(56): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [mbedtls\programs\test\o_p_test.vcxproj]

**Comment by mpg** [comment]
Well, apparently this header is not needed (as well as `sys/stat.h`) so just removing the include line should fix the problem.

Anyway, o_p_test is not useful any more, and we will remove it in 2.0, so you could also just comment it out in programs/CMakeLists.txt to get rid of the problem.
