### ISSUE TITLE
Zeroize test in all.sh does not work in all VM's

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1880]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

PR #1724 refines the zeroize test function in `all.sh` to ensure the zeroize function is operating correctly. However, the way it uses `gdb` doesn't seem to work well with some virtual environments, such as docker and on our Jenkins CI systems generates the following warnings:

```
Breakpoint 1 at 0x4006ec: file test/zeroize.c, line 100.
warning: Error disabling address space randomization: Operation not permitted

Breakpoint 1, main (argc=<optimized out>, argv=<optimized out>) at test/zeroize.c:101
101	}
The buffer was correctly zeroized
/*
 * Zeroize application for debugger-driven testing
 *
 * This is a simple test application used for debugger-driven testing to check
 * whether calls to mbedtls_platform_zeroize() are being eliminated by compiler
 * optimizations. This application is used by the GDB script at
 * tests/scripts/test_zeroize.gdb under the assumption that the code does not
 * change often (as opposed to the library code) because the script sets a
 * breakpoint at the last return statement in the main() function of this
 * program. The debugger facilities are then used to manually inspect the
 * memory and verify that the call to mbedtls_platform_zeroize() was not
 * eliminated.
 *
 *  Copyright (C) 2018, Arm Limited, All Rights Reserved
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless requir
[Inferior 1 (process 6449) exited normally]
The buffer was correctly zeroized
warning: Error disabling address space randomization: Operation not permitted
^^^^test: gcc -Os, mbedtls_platform_zeroize(): not grep -i error test_zeroize.log -> 1^^^^
```

Apparently this could be the docker configuration, so says the first [stackoverflow](https://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted) article I found.

So, we should probably make the test configurable, so it can be skipped, and we should also see if we can reconfigure the VM it's running in on the Jenkins CI.

cc: @andresag01, @mazimkhan

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2416

**Comment by gilles-peskine-arm** [comment]
The problem is that gdb sometimes tries and fails to disable ASLR, and if that happens it emits a warning that contains the word “error”, which causes `all.sh` to treat the test as having failed.

Since https://github.com/ARMmbed/mbed-crypto/pull/7 and https://github.com/ARMmbed/mbedtls/pull/2332 the code in `all.sh` takes care not to try to disable ASLR if this isn't possible. ASLR doesn't affect what we're testing so that's ok.
