### ISSUE TITLE
mbedtls_ssl_session_free frees null ticket pointer

### ISSUE THREAD

**Issue by hkluis** [ARMmbed/mbedtls#1881]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
mbedtls_ssl_session_free() calls mbedtls_free( session->ticket ) without first checking if session->ticket is null.  

A problem scenario is when I have to call mbedtls_ssl_get_session() to retrieve a session:

{
    mbedtls_ssl_session aSession;

    mbedtls_ssl_session_init(&aSession);  // this zeros the structure, including the "ticket" pointer
    mbedtls_ssl_get_session(&ssl, &aSession);
}

In the above, mbedtls_ssl_get_session() calls ssl_session_copy() which calls mbedtls_ssl_session_free(), which calls mbedtls_free( session->ticket ) without first checking it might be a null pointer.

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by RonEld** [comment]
@hkluis Thank you for your interest in Mbed TLS!
Quoting C standard, 7.20.3.2/2 from ISO-IEC 9899, for free() function:
> If ptr is a null pointer, no action occurs.

This means that it is Ok to send NULL as a parameter to `free()` and it is not a bug.

**Comment by hkluis** [comment]
You're correct that it's not a problem with free().  Thanks.  I had a stack corruption problem and thought it was due to freeing a null pointer.  It turns out that my app was built in VisualStudio2013 with _USE_32BIT_TIME_T, while mbedtls was not.  So the size of mbedtls_ssl_session (which contains time_t) do not match between the app and the library.
