### ISSUE TITLE
When RC4 and NULL ciphersuite is disabled, MBEDTLS_CHACHAPOLY_C won't build

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1890]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: mbedtls-2.12.0

When `MBEDTLS_ARC4_C` and `MBEDTLS_CIPHER_NULL_CIPHER` are disabled, but `MBEDTLS_CHACHAPOLY_C` is enabled, the build fails with the following warning:
```
  CC    cipher_wrap.c
cipher_wrap.c:1911:12: warning: unused function 'chacha20_stream_wrap'
      [-Wunused-function]
static int chacha20_stream_wrap( void *ctx,  size_t length,
           ^
1 warning generated.
```

Found by @hsleisink.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2432
