### ISSUE TITLE
Segfault in bignum

### ISSUE THREAD

**Issue by pravic** [ARMmbed/mbedtls#190]
Lot of functions (beginning from `mpi_size`) in bignum.c doesn't checking passed mpi's agains null pointer:

```
  mpi X;
  mpi_init(&X);
  mpi_size(&X); // segfault!
  mpi_free(&X);
```

**Comment by mpg** [comment]
Thanks for your report!

First I would like to point out that this code is not supposed to make sense. You should always set your mpi to some value before you use functions that access its value. `mpi_init()` does not do that, it only ensures the mpi is ready to be set or freed. (I updated the doc to state that explicitly.)

However, I agree that we should not segfault in that case. I just fixed `mpi_size()` and `mpi_msb()`. If other functions should be fixed too, please let us know.
