### ISSUE TITLE
Missing data files for ssl_cert_test

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1905]
The sample program `programs/test/ssl_cert_test.c` is designed to use data files with hard-coded names, but these data files are not present in the repository. They were removed in commit b64d9a79a466ed5c23e93fadbf74de4da4637715. We should do one of the following:

* Remove `ssl_cert_test.c`. Nothing uses it, and as sample code I think it's redundant with programs in the `x509` directory. This has been broken since 1.3, so evidently nobody cares.
* Revert b64d9a79a466ed5c23e93fadbf74de4da4637715, and move `ssl_cert_test.c` and the test data to the `x509` directory because this is not a test program.
* Modify `ssl_cert_test.c` to look for test data in `../tests/data-files` (as the motivation for b64d9a79a466ed5c23e93fadbf74de4da4637715 suggests), modify the program to use existing test data or add missing test data, and move `ssl_cert_test.c` to the `x509` directory because this is not a test program.

@mpg

**Comment by mpg** [comment]
I'd recommend just removing it. Why spend time maintaining redundant code that nobody is using?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2520
