### ISSUE TITLE
aescrypt2 shows bad practice

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1906]
The very first sample program in alphabetical order, `programs/aes/aescrypt2.c`, exhibits several bad practices. It rolls its own CBC mode on top of ECB. It does AEAD by combining AES-CBC with HMAC (at least it does encrypt-then-mac). It rolls its own key stretching by iterating SHA-256.

We should replace this by a program that illustrates best practices, and possibly by one or more other programs that illustrate how to use the low-level functions but not to implement dodgy schemes.

This is a bug, even though the program works, because people who don't know better may copy the code, and it gives a bad impression of the library to people who do know better.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2519
