### ISSUE TITLE
Aria.c uses printf instead of mbedtls_printf

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1908]
### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

The implementation of the aria cipher (aria.c) uses "printf"s instead of "mbedtls_printf"s.

**Comment by hanno-arm** [comment]
Thank you @TrinityTonic for raising this!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2440
