### ISSUE TITLE
Kicking watchdog while in mbedtls_ssl_handshake()

### ISSUE THREAD

**Issue by umanayana** [ARMmbed/mbedtls#1909]
Are there any hooks I can use to kick the watchdog while the handshake is occurring? The handshake takes longer than the time my watchdog needs to service. The method takes about 6 seconds.

The problem is occurring in bignum.c where it's taking too long to do the complex math. At the moment I need to use 2048 RSA certificate to connect to AWS server, so I can't switch solely to ECC. Because the top level versing certificate by AWS only comes in RSA. 

At some point in the future I will be adding a hardware secure element which will hold the private key of the device. So I will need to add my own ECDSA alternative implementation. At this point will bignum.c still be required?

**Comment by RonEld** [comment]
@umanayana I apologize for delayed reply

>Are there any hooks I can use to kick the watchdog while the handshake is occurring?

The only place I can think of are the bio callbacks, however I don't think it would help, as the blocking operation is in the ECC operations.

Note that we are working on a feature for a "restartable ECC" which should be integrated in the near future. This feature will allow you to do the operations in segments, allowing you to do other operations between those segments, so the watchdog won't expire. 
I don't think it will help you for the hardware secure element implementation though.

If you will implement your alternative ECDSA in your hardware secure element, and you won't be using bignum, then it will probably be required only for RSA.

**Comment by RonEld** [comment]
@umanayana We have recently released a feature called "restartable ECC \ non blocking ECC" which allows you to split the ECC operation into segments, allowing you to kick the watchdog between each segment.
More information on the feature can be found [here](https://tls.mbed.org/kb/development/restartable-ecc)

**Comment by umanayana** [comment]
@RonEld 
This is great news thanks.
