### ISSUE TITLE
On-target testing PR 930 non-blocking comments

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbedtls#1921]
Below are my notes from my review of PR #930. Most of the comments are about style and typos and things, which we can address separately from #930.

Line at end of file issues? or fixes?
- tests/Makefile
- tests/suites/helpers.function
- tests/suites/host_test.function

tests/scripts/generate_test_code.py says "/usr/bin/env python3" at the top, but has code to let it run as either python2 or python3

Mispelling
- "TEST FUNCTION NOT FUND" (tests/suites/host_test.function)

Adds a `hexcmp()`. Why is `memcmp()` not good enough? `hexcmp()` would be nice if it
outputted where in a buffer the issue is, but it doesn't, so I don't see the
point.

Some style issues:
- We should have variables like `char *b` and `char *d`, not `char * b` and `char * d`
- There is no need to have `exit: ;;`. Can remove the `exit` and things should
  work fine.
- Some test vectors changed "FAIL" to Mbed TLS error code (CCM), others like
  "AES-GCM NIST" did not and still say "FAIL" as a string.
- We usually do "sizeof( output )" not "sizeof  output"
- Some function calls don't have aligned parameters, like mbedtls_pk_encrypt()
  in pk_rsa_encrypt_test_vec() (and mbedtls_pk_decrypt() later on in the same
  file). See also: mbedtls_pkcs5_pbes2() test
- Pre-exisitng issue in a lot of cases, but many lines are too long. In some
  cases, the line was previously wrapped and it got unwrapped (mbedtls_rsa_pkcs1_verify).
- Alignment issue

  +    oid.p   = buf->x;
  +    oid.len   = buf->len;

  +    oid.p   = oid_buf->x;
  +    oid.len   = oid_buf->len;
- Weird wrapping
```
  +void x509_check_extended_key_usage( char * crt_file, data_t * oid, int ret
  +                                    )
```
- Unecessary casts
  TEST_ASSERT( mbedtls_x509_crt_check_extended_key_usage( &crt, (const char *)oid->x, oid->len ) == ret );

test_suite_ecp.function seems not changed to use data_t everywhere it would make sense to do so

Some hex strings turned into data_t, but kept their string name (e.g.
gcm_encrypt_and_tag). If they are still used as a hex string, we can keep them
as char * and don't need to turn them into data_t.

I don't see why we had to change these test vectors:
- mbedtls_mpi_write_binary:16:"123123123123123123123123123":"23123123123123123123123123":13:MBEDTLS_ERR_MPI_BUFFER_TOO_SMALL

Why did some mbedtls_rsa_private() test vectors need to change but not all?

**Comment by gilles-peskine-arm** [comment]
While you're at it, a cosmetic one:
```
ValueError: Test function arguments can only be 'int', 'char *' or 'data_t'
```
`'data_t'` → `'data_t *'`

**Comment by tom-cosgrove-arm** [comment]
Closing this issue as on-target testing was removed from Mbed TLS in PR #5116 (#4944 for 2.28 LTS), following the announcement in issue #4912 in Sep 2021.

A separate issue (#5595) has been raised as a placeholder, in case we want to come back to it at some point in the future.
