### ISSUE TITLE
Comment says "request" instead of "certificate"

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#1922]
https://github.com/ARMmbed/mbedtls/blob/b363382ba4c0489b6045112dbaf100758ec72cc2/programs/x509/cert_write.c#L773

Could be a copy-paste bug (see `cert_req.c`)

**Comment by irwir** [comment]
Another comment to fix in the same module: should have been "certificate" instead of "key"
https://github.com/ARMmbed/mbedtls/blob/b363382ba4c0489b6045112dbaf100758ec72cc2/programs/x509/cert_write.c#L167

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2466
