### ISSUE TITLE
Help with 'bad message length'

### ISSUE THREAD

**Issue by hjian2017** [ARMmbed/mbedtls#1933]
Dear all,

I have a small problem with 'bad message length'.
I have finished the dtls handshake and try to let client send a msg to server through the session, then fail in here:
`else
    {
        if( ssl->in_msglen < ssl->transform_in->minlen )
        {
            MBEDTLS_SSL_DEBUG_MSG( 1, ( "bad message length 3" ) );
            return( MBEDTLS_ERR_SSL_INVALID_RECORD );
        }

#if defined(MBEDTLS_SSL_PROTO_SSL3)`

. Below are some logs:
-MESH-CP-: bad message length
-MESH-CP-: discarding invalid record (header)
-MESH-CP-: bad application data message
-MESH-CP-: dropping unexpected ApplicationData
-MESH-CP-: discarding unexpected record (header)

Notice it does fail every time. Sometimes it succeed.

Best regards.

**Comment by hanno-arm** [comment]
Hi @hjian2017,

thanks for your request! Could you provide more information on your configuration, communication trace and/or the application code you are running?

Regards,
Hanno

**Comment by hjian2017** [comment]
Hi Hanno,

Thx so much for the response. Yes, I mean "Notice it does not fail every time. Sometimes it succeeds."
I do more testing now, and I want to verify the issue like:
After the client finish the dtls handshake with server, the client sometimes get a dtls packet which rval is MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE when call mbedtls_ssl_read(&mSsl, buf, sizeof(buf)).
And then my code will mbedtls_ssl_session_reset(&mSsl) and try to rebuild dtls handshake again mbedtls_ssl_handshake(&mSsl).
Then the client will sent a client hello and  hold on waiting for response. But the server doesn't know it . The server is on the MBEDTLS_SSL_HANDSHAKE_OVER state.

In fact, it is not my code, it is an opensource project(openthread) you might know. If you want to see the code , here is the link : https://github.com/openthread/openthread/blob/master/src/core/meshcop/dtls.cpp

The fuction is void Dtls::Process(void), please focus on the lines: 494 495.
I think that might be a bug.

**I want to know if the process of dtls handshake is finished. Is the client possible get a MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE packet. If it is possible, should we reset the ssl and try to rebuild the dtls handshake or just ignore MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE packet(I found if I ignore, it looks good.)**

Best regards.
Jian

**Comment by hjian2017** [comment]
By the way, if I add a line: 
`else if(rval == MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE && mSsl.state == MBEDTLS_SSL_HANDSHAKE_OVER)
            break; // ignore it`
then everything is good.

**Comment by hanno-arm** [comment]
Hi @hjian2017,

thanks for the additional information. Could you potentially turn on debugging output from the Mbed TLS client and post that here? That would reveal the message that triggers the failure. Alternatively, or even additionally, a Wireshark log would be helpful.

Thank you,
Hanno

**Comment by hjian2017** [comment]
Hi Hanno,
Here are the client logs:

MESH-CP-: => handshake

-MESH-CP-: client state: 0

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: client state: 1

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write client hello

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 99, out_left: 99

-MESH-CP-: ssl->f_send() returned 99 (-0xffffff9d)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write client hello

-MESH-CP-: client state: 2

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server hello

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 2

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server hello

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 60 (-0xffffffc4)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 60, nb_want: 60

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: received hello verify request

-MESH-CP-: <= parse server hello

-MESH-CP-: => parse hello verify request

-MESH-CP-: <= parse hello verify request

-MESH-CP-: client state: 1

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write client hello

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 131, out_left: 131

-MESH-CP-: ssl->f_send() returned 131 (-0xffffff7d)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write client hello

-MESH-CP-: client state: 2

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server hello

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 2

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server hello

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 838 (-0xfffffcba)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 838, nb_want: 78

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: server hello, total extension length: 13

-MESH-CP-: <= parse server hello

-MESH-CP-: client state: 3

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse certificate

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: next record in same datagram, offset: 78

-MESH-CP-: in_left: 760, nb_want: 13

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 760, nb_want: 532

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: <= parse certificate

-MESH-CP-: client state: 4

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server key exchange

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: next record in same datagram, offset: 532

-MESH-CP-: in_left: 228, nb_want: 13

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 228, nb_want: 170

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: ECDH curve: secp256r1

-MESH-CP-: Server used SignatureAlgorithm 3

-MESH-CP-: Server used HashAlgorithm 4

-MESH-CP-: <= parse server key exchange

-MESH-CP-: client state: 5

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse certificate request

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: next record in same datagram, offset: 170

-MESH-CP-: in_left: 58, nb_want: 13

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 58, nb_want: 33

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: <= parse certificate request

-MESH-CP-: client state: 6

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse server hello done

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: next record in same datagram, offset: 33

-MESH-CP-: in_left: 25, nb_want: 13

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 25, nb_want: 25

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: <= parse server hello done

-MESH-CP-: client state: 7

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write certificate

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 562, out_left: 562

-MESH-CP-: ssl->f_send() returned 562 (-0xfffffdce)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write certificate

-MESH-CP-: client state: 8

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write client key exchange

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 91, out_left: 91

-MESH-CP-: ssl->f_send() returned 91 (-0xffffffa5)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write client key exchange

-MESH-CP-: client state: 9

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write certificate verify

-MESH-CP-: => derive keys

-MESH-CP-: <= derive keys

-MESH-CP-: => calc verify sha256

-MESH-CP-: <= calc verify

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 99, out_left: 99

-MESH-CP-: ssl->f_send() returned 99 (-0xffffff9d)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write certificate verify

-MESH-CP-: client state: 10

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write change cipher spec

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 14, out_left: 14

-MESH-CP-: ssl->f_send() returned 14 (-0xfffffff2)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write change cipher spec

-MESH-CP-: client state: 11

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => write finished

-MESH-CP-: => calc  finished tls sha256

-MESH-CP-: <= calc  finished

-MESH-CP-: => write record

-MESH-CP-: => encrypt buf

-MESH-CP-: <= encrypt buf

-MESH-CP-: => flush output

-MESH-CP-: message length: 53, out_left: 53

-MESH-CP-: ssl->f_send() returned 53 (-0xffffffcb)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= write finished

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 78 (-0xffffffb2)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 78, nb_want: 78

-MESH-CP-: <= fetch input

-MESH-CP-: dropping out-of-sequence message: message_seq = 1, expected = 6

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 532 (-0xfffffdec)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 532, nb_want: 532

-MESH-CP-: <= fetch input

-MESH-CP-: dropping out-of-sequence message: message_seq = 2, expected = 6

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 170 (-0xffffff56)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 170, nb_want: 170

-MESH-CP-: <= fetch input

-MESH-CP-: dropping out-of-sequence message: message_seq = 3, expected = 6

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 33 (-0xffffffdf)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 33, nb_want: 33

-MESH-CP-: <= fetch input

-MESH-CP-: dropping out-of-sequence message: message_seq = 4, expected = 6

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 25 (-0xffffffe7)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 25, nb_want: 25

-MESH-CP-: <= fetch input

-MESH-CP-: received message from last flight, message_seq = 5, start_of_flight = 6

-MESH-CP-: => mbedtls_ssl_resend

-MESH-CP-: initialise resending

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 562, out_left: 562

-MESH-CP-: ssl->f_send() returned 562 (-0xfffffdce)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 91, out_left: 91

-MESH-CP-: ssl->f_send() returned 91 (-0xffffffa5)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 99, out_left: 99

-MESH-CP-: ssl->f_send() returned 99 (-0xffffff9d)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: => write record

-MESH-CP-: => flush output

-MESH-CP-: message length: 14, out_left: 14

-MESH-CP-: ssl->f_send() returned 14 (-0xfffffff2)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: => write record

-MESH-CP-: => encrypt buf

-MESH-CP-: <= encrypt buf

-MESH-CP-: => flush output

-MESH-CP-: message length: 53, out_left: 53

-MESH-CP-: ssl->f_send() returned 53 (-0xffffffcb)

-MESH-CP-: <= flush output

-MESH-CP-: <= write record

-MESH-CP-: <= mbedtls_ssl_resend

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: <= handshake

-MESH-CP-: => handshake

-MESH-CP-: client state: 12

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse change cipher spec

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 67 (-0xffffffbd)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 67, nb_want: 14

-MESH-CP-: <= fetch input

-MESH-CP-: <= read record

-MESH-CP-: <= parse change cipher spec

-MESH-CP-: client state: 13

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => parse finished

-MESH-CP-: => calc  finished tls sha256

-MESH-CP-: <= calc  finished

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: next record in same datagram, offset: 14

-MESH-CP-: in_left: 53, nb_want: 13

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 53, nb_want: 53

-MESH-CP-: <= fetch input

-MESH-CP-: => decrypt buf

-MESH-CP-: <= decrypt buf

-MESH-CP-: <= read record

-MESH-CP-: <= parse finished

-MESH-CP-: client state: 14

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: handshake: done

-MESH-CP-: client state: 15

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: <= handshake

-MESH-CP-: BH AE Dtls handshake has completed!
-MESH-CP-: => read

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 14 (-0xfffffff2)

-MESH-CP-: <= fetch input

-MESH-CP-: bad message length 3

-MESH-CP-: discarding invalid record (header)

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: => read

-MESH-CP-: => flush output

-MESH-CP-: <= flush output

-MESH-CP-: => read record

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 0, nb_want: 13

-MESH-CP-: ssl->f_recv(_timeout)() returned 53 (-0xffffffcb)

-MESH-CP-: <= fetch input

-MESH-CP-: => fetch input

-MESH-CP-: in_left: 53, nb_want: 53

-MESH-CP-: <= fetch input

-MESH-CP-: => decrypt buf

-MESH-CP-: <= decrypt buf

-MESH-CP-: <= read record

-MESH-CP-: bad application data message


B&R
Jian

**Comment by hanno-arm** [comment]
Hi @hjian2017,

thanks for the log! The path printing the last message is [here](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L7379) and to my present understanding, it should never be taken: alert and handshake messages are explicitly handled before, and CCS messages are [dropped](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L3839) - at least in theory. I would like to investigate this further, but for that I need a more detailed log, which you could obtain by increasing the debug level. This is passed as an argument to the debugging function configured through `mbedtls_ssl_conf_dbg`, so you should find that call and make sure the registered functions prints everything, regardless of the debugging level.

Thank you,
Hanno

**Comment by hjian2017** [comment]
Hi Hanno,

Thanks for the help. 
I tried but failed to get more log on client because of the serial port speed limit.
As you see , the handshake process has been finished, and then the client got a MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE msg. I think I have addressed the issue. 
So my question is:
if the process of dtls handshake is finished. Is the client possible get a MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE packet. If it is possible, should we reset the ssl and try to rebuild the dtls handshake or just ignore MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE packet(I found if I ignore, it looks good.)

In my opinion, it is possible. For example, after the handshake, the client possible receive some bad msgs . What we need to do is ignore the bad msgs.  So I add some codes like `else if(rval == MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE && mSsl.state == MBEDTLS_SSL_HANDSHAKE_OVER) break; // ignore it`, and then everything is ok.

Please have a look this fuction and then you will know what I mean (when we start a handshake or get a dtls msg, the client will run the Process function):
 
`void Dtls::Process(void)
{
         uint8_t buf[MBEDTLS_SSL_MAX_CONTENT_LEN];
         bool    shouldClose = false;
         int     rval;

    while (mStarted)
    {
        if (mSsl.state != MBEDTLS_SSL_HANDSHAKE_OVER)
        {
            rval = mbedtls_ssl_handshake(&mSsl);

            if ((mSsl.state == MBEDTLS_SSL_HANDSHAKE_OVER) && (mConnectedHandler != NULL))
            {
                mConnectedHandler(mContext, true);
            }
        }
        else
        {
           //after the handshanke, it might get a bad msg here.
            rval = mbedtls_ssl_read(&mSsl, buf, sizeof(buf));
        }

        if (rval > 0)
        {
            mReceiveHandler(mContext, buf, static_cast<uint16_t>(rval));
        }
        else if (rval == 0 || rval == MBEDTLS_ERR_SSL_WANT_READ || rval == MBEDTLS_ERR_SSL_WANT_WRITE)
        {
            break;
        }

        else
        {
            switch (rval)
            {
            case MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY:
                mbedtls_ssl_close_notify(&mSsl);
                ExitNow(shouldClose = true);
                break;

            case MBEDTLS_ERR_SSL_HELLO_VERIFY_REQUIRED:
                break;

            case MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE:
                mbedtls_ssl_close_notify(&mSsl);
                ExitNow(shouldClose = true);
                break;

            case MBEDTLS_ERR_SSL_INVALID_MAC:
                if (mSsl.state != MBEDTLS_SSL_HANDSHAKE_OVER)
                {
                    mbedtls_ssl_send_alert_message(&mSsl, MBEDTLS_SSL_ALERT_LEVEL_FATAL,
                                                   MBEDTLS_SSL_ALERT_MSG_BAD_RECORD_MAC);
                    ExitNow(shouldClose = true);
                }

                break;

            default:
                if (mSsl.state != MBEDTLS_SSL_HANDSHAKE_OVER)
                {
                    mbedtls_ssl_send_alert_message(&mSsl, MBEDTLS_SSL_ALERT_LEVEL_FATAL,
                                                   MBEDTLS_SSL_ALERT_MSG_HANDSHAKE_FAILURE);
                    ExitNow(shouldClose = true);
                }

                break;
            }

            ///We can't reset here. If we get a bad msg and  reset here, client will restart a handshake process but server doesn't know.
            mbedtls_ssl_session_reset(&mSsl); 
            mbedtls_ssl_set_hs_ecjpake_password(&mSsl, mPsk, mPskLength);
            break;
        }
    }

exit:

    if (shouldClose)
    {
        Close();
    }
}``

**Comment by hanno-arm** [comment]
Hi @hjian2017,

apologies for not getting back to you earlier.

I have studied the log you sent in more detail, and what's happening is the following:
* The client sends its last flight and listens for the server's last flight; when it receives a retransmission from the server instead, it resends its last flight.
* The server responds with its last flight containing the `ChangeCipherSpec` message and the `Finished` message (within a single datagram); Mbed TLS processes both records and completes the handshake. 
* When the server sees the Client's retransmission, it retransmits its last flight.
* When the client receives the server's last flight again, it has already completed the handshake and switched to the next incoming epoch. In that epoch, the `ChangeCipherSpec` record (length 14) is below the minimum record length, hence is dropped (logging `bad message length 3`). This is to be expected, and correct behavior. Next, the client receives the `Finished` message again, which should be dropped by the stack, and all LTS versions of Mbed TLS are doing that; see e.g. [here](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.7.0/library/ssl_tls.c#L6972). 

_However_, there was bug previously which would lead to the `Finished` message to go through, triggering the `MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE` error, in case `MBEDTLS_SSL_RENEGOTIATION` was not defined. 

Could you confirm that you are running a version >= 2.2 and <= 2.6, and that `MBEDTLS_SSL_RENEGOTIATION` is disabled? If so, please update to one of the LTS branches of Mbed TLS, which should fix the problem. If not, we'll need to investigate further.

Kind regards,
Hanno

**Comment by RonEld** [comment]
We believe this question was answered, therefore closing it.
If this issue remains, please reopen with additional information
