### ISSUE TITLE
On-Target Testing PR #930 non-blocking issues

### ISSUE THREAD

**Issue by itayzafrir** [ARMmbed/mbedtls#1950]
Non-blocking issues found in #930

*Note* there's 1 issue which breaks compilation, see comment https://github.com/ARMmbed/mbedtls/pull/930#pullrequestreview-146376603

__Typos:__
- nameing -> naming https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/Makefile#L78
- uint -> unit https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/scripts/all.sh#L1056
- FUND --> FOUND https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/host_test.function#L634

__Questions:__
- Does this mean that python 3 is mandatory?https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/scripts/generate_test_code.py#L1
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/scripts/test_generate_test_code.py#L1
- What is the benefit of using `hexcmp` over `memcmp`?https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/helpers.function#L458
- Why did the vector change? 3rd param current value is 1 char shorter than original value https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mpi.data#L62

__Styling:__
- AFAIK pointers are supposed to be declared as `data_t *src` and not as `data_t * src` (note the unnecessary space after the `*`)
- Duplicate `;` https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_base64.function#L108
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509parse.function#L766
- I don't think the cast is needed here, but there's also a style fix: `(uint8_t*) malloc( result->len + 2 );` https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_ccm.function#L125
- Align closing parentheses with opening parentheses https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_cipher.function#L603
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_cipher.function#L659
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509write.function#L214
- `sizeof( output )` https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mdx.function#L23
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mdx.function#L42
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mdx.function#L61
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mdx.function#L80
- Arguments alignment to the same column https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs5.function#L36
- Too many spaces before '=' sign https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509parse.function#L632
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509parse.function#L632
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509parse.function#L660
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_x509parse.function#L661
- Unnecessary empty lines https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_mpi.function#L96
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v15.function#L39
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v15.function#L85
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v15.function#L136
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v21.function#L39
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v21.function#L86
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_pkcs1_v21.function#L138
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L60
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L268
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L306
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L354
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L391
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L406
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L456
https://github.com/ARMmbed/mbedtls/blob/58e9c1833bfb386e385a345776c6f853306adddc/tests/suites/test_suite_rsa.function#L473

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2478
