### ISSUE TITLE
ssl-opt.sh does not include tests for DTLS session resumption

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#1969]
__Issue:__ Session resumption is currently only tested for TLS. The `Session resume ...` tests should have analogues for DTLS.

__Context:__ When PR #1939 introduced DTLS session resumption test in the presence of a proxy, this brought up a spurious timing failure which could already have been observed with a plain session resumption test. Also, such a test would witness the session ticket issue #1968.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2484
