### ISSUE TITLE
Arm C Compiler doesn't support gmtime()

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#1975]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS

-----------------------------------------------------------------

The [Arm C Compiler does not support `gmtime()` as stated in the documentation](https://github.com/ARMmbed/mbedtls/pull/1927/files). Yet, Mbed TLS will build with it, but calls to `gmtime()` will return a `NULL` - therefore `MBEDTLS_HAVE_TIME` can't work with ARM C Compiler.

We probably need a check in `check_config.h` to detect the ARM C Compiler and to issue an error if `MBEDTLS_HAVE_TIME` is enabled.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2486

**Comment by sbutcher-arm** [comment]
If a compiler or platform (such as the Arm C Compiler) doesn't provide `gmtime()` or `gmtime_r()`, we now allow users integrating the library to provide their own implementation of either by implementing the function `mbedtls_platform_gmtime_r()` which is an abstraction of `gmtime_r()`. This feature was introduced in PR #1927.

Therefore it doesn't matter if `gmtime()` isn't supported on any given platform - but it is however the responsibility of those integrating Mbed TLS with the platform to provide their own implementation.

And to be clear - the Mbed TLS project has no plans to provide it's own implementation of `gmtime()` or `gmtime_r()`.

Therefore this issue can now be closed.
