### ISSUE TITLE
POLARSSL_CIPHER_ID_3DES never used

### ISSUE THREAD

**Issue by evvliet** [ARMmbed/mbedtls#198]
In `include/polarssl/cipher.h` a `cipher_id_t value` is defined for `POLARSSL_CIPHER_ID_3DES` but it is actually never used.
I would have expected it to be used in `library/cipher_wrap.c` by `des_ede3_info` but that uses `POLARSSL_CIPHER_ID_DES` instead.

I'm not entirely sure if it can safely be omitted (from the header file) or changed. If not, it might be convenient to mark it as `/* Unused! */`.

**Comment by mpg** [comment]
Good catch. I'll mark it as unused in the 1.3 branch, and change `des_ede3_info` to use it in the 2.0 branch. Thanks for your report.
