### ISSUE TITLE
Why need to limit the `add` length?

### ISSUE THREAD

**Issue by edison-ai** [ARMmbed/mbedtls#1996]
### Description
- Type: Question
- Priority: Major

## Question
In CCM, why need to limit the `add` length as below?
https://github.com/ARMmbed/mbedtls/blob/9ce5160feaf889d5e4c337458edc1068bb76920a/library/ccm.c#L165-L166

Is there any SPEC to limit it? Could we remove that?

Thanks,
Edison

**Comment by edison-ai** [comment]
No needed. Thanks.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2640
