### ISSUE TITLE
ssl_handshake is stuck at client state: 2 in_left: 0, nb_want: 5, server state: 8 in_left : 0, nb_want : 5

### ISSUE THREAD

**Issue by tyxeron** [ARMmbed/mbedtls#1998]
### Description
- Type: Bug 
- Priority: Major 

I came along this bug that the ssl_handshake does not succeed and is stuck at  
`client state: 2 in_left: 0, nb_want: 5 `
on the client and
 `server state: 8 in_left : 0, nb_want : 5 `
at the server

I attached both debug outputs.
I am working on a project with Intel SGX and for that I currently using the SGX port of mbedtls (https://github.com/bl4ck5un/mbedtls-SGX).

To be able to properly debug I am using an untrusted version and use the official mbedtls library.

Both of them run into the same problem. I have currently four nodes that are trying to communicate with each other. The first opens up a connection to the node 2,3 and 4, the second to node 3 and 4 and so on. I never succeeded that all nodes connected to each other and two stuck in the scenario mentioned above. I already used valgrind to make sure there is no illegal memory writes and reads.
I also checked my locking mechanism that I have in place and it seems to generate no issues as both nodes affected (client and server) stuck at the handshake. If necessary I can provide the code for the client and server.

[output_client.txt](https://github.com/ARMmbed/mbedtls/files/2340440/output_client.txt)
[output_server.txt](https://github.com/ARMmbed/mbedtls/files/2340441/output_server.txt)

---------------------------------------------------------------
## Bug

**OS**  
linux debian

**mbed TLS build:**  
git commit id: c041435f
OS version: 4.9.0-6-amd64

**Comment by RonEld** [comment]
@tyxeron 
Thank you for raising this.
Note that you are referring to a networking port that is not maintained by us, and you are describing an issue that suggests this is a bug in the networking port. Hence, this issue is not considered a bug in Mbed TLS, at the moment.
I have seen, howevder, in both the client and ser ver logs, the following lines:
~~~
ssl->f_recv(_timeout)() returned -26624 (-0x6800)
~~~
This means that your connection timed out. This *could* be the root cause for your failures.

**Comment by hanno-arm** [comment]
Hi @tyxeron,

I can see from the log that the server sends his `ServerHello` flight, but the client does not receive it. To understand where things go wrong, could you please wrap the BIO functions by stub functions which include debug logs of the buffers that are read and written? This way, we can determine whether something goes wrong on the TLS side or on the underlying network socket.

Kind regards,
Hanno, Mbed TLS team member

**Comment by RonEld** [comment]
This issue has been addressed, and no response since. Assuming the issue resolved.
If your question is still relevant, please reopen, and respond to the followup questions.
Thanks!
