### ISSUE TITLE
Add cipher interface to key wrapping modes

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#2003]
We provide the NIST key wrapping modes (KW, KWP) through a custom interface (`mbedtls_nist_kw_xxx`). A key wrapping mode is an AEAD mode, functionally speaking, so it would make sense to provide an interface to these modes through the generic AEAD functions in the cipher module.

The key wrapping modes would only be supported by the one-shot functions (`mbedtls_cipher_auth_encrypt`, `mbedtls_cipher_auth_decrypt`), not by the multipart functions, because they process the full input at once. This is already the case for CCM (which processes the data in a streaming fashion but can't start encrypting until it knows the length of the plaintext) so we wouldn't be changing the philosophy of that API.

Requested by @jethrogb in https://github.com/ARMmbed/mbedtls/pull/1658#issuecomment-417461217

**Comment by jethrogb** [comment]
We have started working on this.
