### ISSUE TITLE
Error while loading keyfile to generating CSR

### ISSUE THREAD

**Issue by aanand23** [ARMmbed/mbedtls#2025]
I have generated RSA public and private key pair and now I am trying to generate CSR following (mbedTLS/programs/x509/cert_req.c)
I am getting an error while trying to load the private key file in pk context using mbedtls_pk_parse_keyfile(). This function is returning an error -15616. I checked the private key file by printing the key value and the path of private keyfile. I set the password as NULL. 
Has anyone of you come across this issue or know what this error means? Could anyone of you please help or guide me how to solve this?
Any help is appreciated.

Thank you

**Comment by k-stachowiak** [comment]
If you wish to check what an error code means, you can use the `mbedtls_strerror( )` function. There is also a utility program shipped with Mbed TLS: `programs/util/strerror`, which uses the same function on a code provided from the command line. Using it on the code that you provided gave me: "PK - Invalid key tag or value".

As for why you get this error, it seems like the function is not provided with a key file that it expects. Please consult the documentation for the function [here](https://tls.mbed.org/api/pk_8h.html#a935d710e542409462d0209f2381da83e). It contains a note about the key context parameter and key types. You may check your program in that regard.

Additionally, you mention the example: `programs/x509/cert_req`. Did you also consult the [Knowledge Base article](https://tls.mbed.org/kb/how-to/generate-a-certificate-request-csr)? I would suggest following the instructions from the article and compare them with what you did before you received the error.

**Comment by RonEld** [comment]
We believe this question was answered, therefore closing. If you have followup questions, please reopen, with your comments on what is still not clear
