### ISSUE TITLE
Debug messages not thread-safe

### ISSUE THREAD

**Issue by evvliet** [ARMmbed/mbedtls#203]
Due to the use of an intermediate buffer (the `debug_fmt` routine), macros like `SSL_DEBUG_MSG` are not thread-safe and can return (partial) messages from different threads. Those messages are then combined with e.g. file and line number, which therefore may result in debug messages that are plain wrong.

A simple test with 100 threads producing 1000 unique messages each (they basically logged their thread id and a counter), resulted in over 25% duplicate messages on my machine.

This could probably be avoided by not using the intermediate, globally static buffer. It is only used for `debug_print_msg` anyway.

**Comment by pjbakker** [comment]
Which version are you using?
Which global static buffer do you mean exactly?

**Comment by marmeladema** [comment]
I think he is talking about line 69 in this file: https://github.com/ARMmbed/mbedtls/blob/61977614d84c7b4d6aeaecaa003977472d4114db/library/debug.c

Removing the static attribute for the buffer should do the trick.

**Comment by marmeladema** [comment]
Indeed i was wrong.
However, using a thread local storage buffer (__thread attribute for gcc) should works.

**Comment by mpg** [comment]
Thanks for your report! We agree with you analysis. We can't just removed the `static` because the function returns a pointer to this buffer, so we'll move to dynamic allocation instead.
