### ISSUE TITLE
X.509 key usage MBEDTLS_X509_KU_DECIPHER_ONLY and MBEDTLS_X509_KU_ENCIPHER_ONLY ignored in CSR writing

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2047]
__Issue:__ The [documentation](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.13.1/include/mbedtls/x509_csr.h#L209) states:
```c
/**
 * \brief           Set the Key Usage Extension flags
 *                  (e.g. MBEDTLS_X509_KU_DIGITAL_SIGNATURE | MBEDTLS_X509_KU_KEY_CERT_SIGN)
 *
 * \param ctx       CSR context to use
 * \param key_usage key usage flags to set
 *
 * \return          0 if successful, or MBEDTLS_ERR_X509_ALLOC_FAILED
 */
int mbedtls_x509write_csr_set_key_usage( mbedtls_x509write_csr *ctx, unsigned char key_usage );
```
This suggests that any combination of the key usage flags from [x509_crt.h](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.13.1/include/mbedtls/x509.h#L113) can be used with this function:
```c
#define MBEDTLS_X509_KU_DIGITAL_SIGNATURE            (0x80)  /* bit 0 */
#define MBEDTLS_X509_KU_NON_REPUDIATION              (0x40)  /* bit 1 */
#define MBEDTLS_X509_KU_KEY_ENCIPHERMENT             (0x20)  /* bit 2 */
#define MBEDTLS_X509_KU_DATA_ENCIPHERMENT            (0x10)  /* bit 3 */
#define MBEDTLS_X509_KU_KEY_AGREEMENT                (0x08)  /* bit 4 */
#define MBEDTLS_X509_KU_KEY_CERT_SIGN                (0x04)  /* bit 5 */
#define MBEDTLS_X509_KU_CRL_SIGN                     (0x02)  /* bit 6 */
#define MBEDTLS_X509_KU_ENCIPHER_ONLY                (0x01)  /* bit 7 */
#define MBEDTLS_X509_KU_DECIPHER_ONLY              (0x8000)  /* bit 8 */
```
However, the `key_usage` parameter in `mbedtls_x509write_csr_set_key_usage()` is an `unsigned char` and hence not capable of expressing `MBEDTLS_X509_KU_DECIPHER_ONLY`. Moreover, we consider only the first 7 bits when writing the `keyUsage` extension:
```c
int mbedtls_x509write_csr_set_key_usage( mbedtls_x509write_csr *ctx, unsigned char key_usage )
{
    unsigned char buf[4];
    unsigned char *c;
    int ret;

    c = buf + 4;

    if( ( ret = mbedtls_asn1_write_bitstring( &c, buf, &key_usage, 7 ) ) != 4 )
        return( ret );

    ret = mbedtls_x509write_csr_set_extension( ctx, MBEDTLS_OID_KEY_USAGE,
                                       MBEDTLS_OID_SIZE( MBEDTLS_OID_KEY_USAGE ),
                                       buf, 4 );
    if( ret != 0 )
        return( ret );

    return( 0 );
}
```
This limitation needs either needs to be documented or removed, adding support for `MBEDTLS_X509_KU_DECIPHER_ONLY` and `MBEDTLS_X509_KU_ENCIPHER_ONLY`. It is not acceptable that users can pass them in the believe they'd be considered, but they are silently dropped.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2564

**Comment by moshe-shahar** [comment]
@hanno-arm, that is duplication of issue https://github.com/ARMmbed/mbedtls/issues/1605.
But I think you explain it better here

**Comment by hanno-arm** [comment]
@moshe-shahar Thank you very much for pointing that out!

**Comment by sbutcher-arm** [comment]
@hanno-arm - I'm closing this issue as that one was first, and to avoid accidentally missing the credit to @moshe-shahar for finding the bug. Can you please ensure that bug captures all information relating to this issue?
