### ISSUE TITLE
Wrong documentation of MBEDTLS_SSL_MAX_CONTENT_LEN

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2062]
The documentation in [config.h](...) states:

```c
/** \def MBEDTLS_SSL_MAX_CONTENT_LEN
 *
 * Maximum fragment length in bytes.
 *
 * Determines the size of both the incoming and outgoing TLS I/O buffers.
 *
 * Uncommenting MBEDTLS_SSL_IN_CONTENT_LEN and/or MBEDTLS_SSL_OUT_CONTENT_LEN
 * will override this length by setting maximum incoming and/or outgoing
 * fragment length, respectively.
 */
//#define MBEDTLS_SSL_MAX_CONTENT_LEN             16384
```

This is not true: `MBEDTLS_SSL_IN_CONTENT_LEN` and `MBEDTLS_SSL_OUT_CONTENT_LEN` do not  influence `MBEDTLS_SSL_MAX_CONTENT_LEN`. 

In contrast, if `MBEDTLS_SSL_IN/OUT_CONTENT_LEN` are not defined but `MBEDTLS_SSL_MAX_CONTENT_LEN` is, then the former will be defined in terms of the latter.

`MBEDTLS_SSL_MAX_CONTENT_LEN` is not meant to be used in the entire code base (it is, currently, used in `ssl_get_remaining_payload_in_datagram()`, but that's a bug) and is only present for legacy reasons and as a means to configure `MBEDTLS_SSL_IN/OUT_CONTENT_LEN` in case no distinction between incoming and outgoing data is needed.

__Suggested Action:__ Remove the comment and instead state that `MBEDTLS_SSL_MAX_CONTENT_LEN` acts as a default value for `MBEDTLS_SSL_IN/OUT_CONTENT_LEN` in case they are not defined, and that users should either define `MBEDTLS_SSL_MAX_CONTENT_LEN` _or_ both `MBEDTLS_SSL_MAX_IN_CONTENT_LEN` and `MBEDTLS_SSL_MAX_OUT_CONTENT_LEN`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2565
