### ISSUE TITLE
Counter intuitive behavior of mbedtls_pk_write_pubkey() for invalid keys

### ISSUE THREAD

**Issue by bmurray7** [ARMmbed/mbedtls#2063]
### Description
- Type: Enhancement 
- Priority:  Minor

---------------------------------------------------------------
## Bug

The behavior of `mbedtls_pk_write_pubkey()` is counter intuitive when the key type is `MBEDTLS_PK_NONE`.  In such circumstances, the function returns `MBEDTLS_ERR_PK_FEATURE_UNAVAILABLE`, but I feel `MBEDTLS_ERR_PK_INVALID_PUBKEY` would be a more intuitive return code.

The return code `MBEDTLS_ERR_PK_FEATURE_UNAVAILABLE` implies functionality is not available due to the local build config. I feel that `MBEDTLS_ERR_PK_INVALID_PUBKEY` is a more intuitive return code since calling `mbedtls_pk_write_pubkey()` for a key of type `MBEDTLS_PK_NONE` is likely due to a failure to properly initialize the key.

There appears to be similar behavior in `mbedtls_pk_write_key_pem()`.

If there is a consensus for this change, I can submit a PR.

**Comment by RonEld** [comment]
@bmurray7 Thank you for reporting this!
I don't think this is a bug.
For example:
If `MBEDTLS_RSA_C` is not defined, but the key is actually an RSA key, then the reasonable error code would be `MBEDTLS_ERR_PK_FEATURE_UNAVAILABLE `.
In addition, `mbedtls_pk_get_type` will return `MBEDTLS_PK_NONE ` in the following use cases:
1. the key context is `NULL`. Perhaps this merits an Invalid key error, but the user should not send a NULL key.
2. The `pk_info` member of the key is `NULL`.  This could happen if the the key was not parsed correct, or there is a missing configuration . Perhaps this merits an invalid key error as well, but this , again, will happen on a user error.

I can see why `MBEDTLS_ERR_PK_INVALID_PUBKEY` should be returned in some cases, but only when user didn't initialize correct the context. However, IMHO, `MBEDTLS_ERR_PK_FEATURE_UNAVAILABLE` fits better this ocation, in a normal flow, when there is a missing build configuration.

**Comment by RonEld** [comment]
We believe this issue has been addressed and answered, therefore closing.
If you believe it needs further action, please reopen with additional questions.
Thanks!
