### ISSUE TITLE
Sliding-window exponentiation issue in bignum.c

### ISSUE THREAD

**Issue by tofmassilia** [ARMmbed/mbedtls#207]
In bignum.c there is an issue for the destination size after calculation of Sliding-window exponentiation (X = A^E mod N).
For example the size of X (X.n) is 0x41 with N size (N.n) set to 0x40. It's impossible due to mod N operation; It should be equal to 0x40 in this case.
For information, the last element of the array (the 0x41th in above case) is filled with 0.

**Comment by mpg** [comment]
I don't see how that's an issue. `X.n` is the number of limbs allocated, it's an internal information that users are not supposed to look at. If you want to know the size of `X` you should use `mpi_size()` for the size in bytes, or `mpi_msb()` for the size in bits. They both give the correct result by handling zeros in the most significant limb(s) correctly.

**Comment by mpg** [comment]
Closing. If you still think this is an issue, please re-open and explain why.
