### ISSUE TITLE
README.md needs updating

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#2078]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

The [README.md](https://github.com/ARMmbed/mbedtls/blob/development/README.md) is out of date, and states that Perl is required to build tests. That's no longer true, and Python is now required!

This needs fixing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2584

**Comment by RonEld** [comment]
I have created #2366 to fix this issue
