### ISSUE TITLE
Null dereference

### ISSUE THREAD

**Issue by Bugcheckers** [ARMmbed/mbedtls#2089]
### Description
- Type: Probably Bug
- Priority: Not sure

---------------------------------------------------------------
## Probably Bug

Based on searching for inconsistencies

We have seen tag is checked before dereferencing here:

https://github.com/ARMmbed/mbedtls/blob/development/library/chachapoly.c#L372

But it is missed here:

https://github.com/ARMmbed/mbedtls/blob/development/library/gcm.c#L493
https://github.com/ARMmbed/mbedtls/blob/development/library/ccm.c#L353

If NULL is passed as tag, it might cause NULL dereference.

Thanks!

**Comment by hanno-arm** [comment]
Hi @Bugcheckers,

thank you for your report! I agree that this is an inconsistency in the code that should be fixed.

We're already working towards thorough parameter validation of public API - for example, GCM and CCMM are handled in https://github.com/ARMmbed/mbedtls/pull/1689 and https://github.com/ARMmbed/mbedtls/pull/1687.

We will close this issue once the parameter validation work is merged.

Thanks again,
Kind regards,
Hanno, Mbed TLS team member

**Comment by hanno-arm** [comment]
__NOTE:__ No need to additionally track this, but remember to close once #1689 and #1687 are closed.

**Comment by Bugcheckers** [comment]
Hi @hanno-arm,

Cool! Thank you!

**Comment by RonEld** [comment]
Closing, as the referenced PRs have been merged, and this issue has been addressed
