### ISSUE TITLE
programs/x509/cert_write not built 

### ISSUE THREAD

**Issue by kriben** [ARMmbed/mbedtls#209]
When following the steps to generate a self-signed certificate (https://tls.mbed.org/kb/how-to/generate-a-self-signed-certificate) I discovered that the /programs/x509/cert_write executable is not built when using make.

Version: 1.3.11
OS: Debian 7u1 64-bit

**Comment by mpg** [comment]
Thanks for your report! I did an full check and there were a few other programs that were not built, so I added them all.
