### ISSUE TITLE
mbedtls_x509write_csr_set_subject_name underline

### ISSUE THREAD

**Issue by ruankong** [ARMmbed/mbedtls#2161]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Blocker
std::string subject;
  subject.append("C=CN,ST=Shanghai,L=Shanghai,O=test,OU=test,CN=MP_");
  if ((ret = mbedtls_x509write_csr_set_subject_name(csr.get()->get(),
                                                    subject.c_str())) != 0) {
    return SSLStatus::error_x509write_csr_set_subject_name_failed;
  };
while use underline in subjectname, the csr can't be parsed correctly? please help
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by ruankong** [comment]
> Hi @ruankong,
> 
> thank you for your report. Could you clarify where the failure occurs? Does `mbedtls_x509write_csr_set_subject_name()` fail, or does it succeed but the generated CSR cannot be parsed?
> 
> Kind regards,
> Hanno, Mbed TLS team member

generating csr  is successful， but  the generated CSR cannot be parsed. the output is like this

-----BEGIN CERTIFICATE REQUEST-----
MIICpDCCAYwCAQAwXzELMAkGA1UEBhMCQ04xETAPBgNVBAgTCFNoYW5naGFpMREw
DwYDVQQHEwhTaGFuZ2hhaTENMAsGA1UEChMEdGVzdDENMAsGA1UECxMEdGVzdDEM
MAoGA1UEAxMDTVBfMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7A3l
vAnxQXa09Xv55HZXS0NxbYL5oVZe8WuMYIniKsw+1QvLxIu21/sF/kF5+8mtflps
3DXUJWMwvYOxw1Y8yc5UVNC2N+scYdCIt2Ki4TH2xFzekpaX0SEJAlg6bLFTCOc5
wPkkVpOvxHMKyRGs78Tt5tA5RYXS/eD+00TQ0wh1+ysk2xqNytu5iUaKDmU3m3JC
3jPrWnjpuu2oOdeyIqS70SlxdpPuOvQ47DBlGQDlT6j5SzqgAKkZ+GCESOHwA2yE
uPKmFCOlcCTn8HsCxVJ21cH8GcVN+Z3MuKVEzFRs5oG5NGVFkF6n4v06pwC33g4o
ixNy1rrKVNsZcA04tQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAIpeWBMrvhjX
EvF+AMFcFfA0sYyZk8s5FKbFK/uciwSn7J9KpzRsYtCcKzsonEg4TWlJLEo2dr9B
VDpWK+KOTtN+VfRu4RcTWdPa8ZSYi49tOaKYMsmJw3HaI0IBbt2HzP54dJ6KPpgK
ntZSjTWwwiMIn209T4m3tHu77xoM8CHF11JpSyDjvcJqnOKjgWpL4uDcY9VoB+3D
arUjl6twZOn7mnEta4RbENhUb8fa/qY0bNS7Xker1ufHYYbCkd0PSjOYAC8R+794
cEz8cXaSYC9wtzlcIdurPEbXCcEfQzqA3E1mTcq3E3axAccNSrReXYPMSpnYf31d
HOn1LItGQFI=
-----END CERTIFICATE REQUEST-----

it can't be parsed.


thank you for your help!

**Comment by hanno-arm** [comment]
Hi @ruankong,

how are you parsing the CSR? 

The issue might be that currently we're writing the CN in `PrintableString` format, the character set of which doesn't include `_`. This is being fixed in https://github.com/ARMmbed/mbedtls/pull/1641 which close to getting merged.

Still, I would like to understand where exactly you see a failure and make sure it's indeed caused by the use of `PrintableString`.

Regards,
Hanno

**Comment by ruankong** [comment]
> #1641

I use https://myssl.com/csr_decode.html this website to check the CSR. 

And do you mean that maybe the latest version has fixed this issue?

**Comment by hanno-arm** [comment]
Hi @ruankong,

could you check out #1641 and see if it fixes your issues?

Regards,
Hanno

**Comment by ruankong** [comment]
I think it has solved the problem. Thank you for your kind help.

> Hi @ruankong,
> 
> could you checkout and compile #1641 and see if it fixes your issues?
> 
> Regards,
> Hanno
