### ISSUE TITLE
build error when using alternative ECDH and ECDSA functions

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2163]
### Description
- Type: Bug
- Priority: Blocker
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS

**mbed TLS build:**  
Version: since https://github.com/ARMmbed/mbedtls/commit/66ba48a3c8e6522b48acffca9cb6beb7c9d7a23e

When defining `MBEDTLS_ECDH_COMPUTE_SHARED_ALT` and all the rest of the ECDH and ECDSA alternative functions, you get build error. 
Reason is that the functions were taken out of hte MACRO check, with the insertion of the restartable ECC feature.

**Expected behavior**   
build to succeed
**Actual behavior**  
Build fails on multiple definition:
~~~
       ecdh.o: In function `mbedtls_ecdh_compute_shared':
        ecdh.c:122: multiple definition of `mbedtls_ecdh_compute_shared'
        ecdh_alt.o:ecdh_alt.c:143: first defined here
        ecdsa.o: In function `mbedtls_ecdsa_sign':
        ecdsa.c:380: multiple definition of `mbedtls_ecdsa_sign'
        ecdsa_alt.o:ecdsa_alt.c:69: first defined here
        ecdsa.o: In function `ecdsa_sign_det_restartable':
        ecdsa.c:394: multiple definition of `mbedtls_ecdsa_verify'
        ecdsa_alt.o:ecdsa_alt.c:33: first defined here
~~~

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2612
