### ISSUE TITLE
Bug in include/mbedtls/compat-1.3.h

### ISSUE THREAD

**Issue by hsleisink** [ARMmbed/mbedtls#217]
There is a bug / typo in include/mbedtls/compat-1.3.h:
#define error_strerror mbedtls_error_strerror
should be
#define error_strerror mbedtls_strerror

**Comment by mpg** [comment]
Fixed, thanks. I also fixed that in the list used by the renaming script.

I also added an optional warning/error about using `POLARSSL_ERROR_STRERROR_BC` in the 1.3 branch, as this is marked as deprecated in the documentation (should use `polarssl_strerror()` instead) but didn't generate a warning/error with `POLARSSL_DEPRECTED_WARNING/REMOVED`.
