### ISSUE TITLE
ssl_set_dbg() replacement in 2.0.0

### ISSUE THREAD

**Issue by hsleisink** [ARMmbed/mbedtls#218]
In 1.3, I could supply a parameter to ssl_set_dbg(). The parameter I supplied was the thread id, which I printed along with the error message, in order to see which error messages in the logfile belong together (originated from the same thread). In 2.0.0, that is no longer possible, as I only have mbedtls_ssl_conf_dbg() and no mbedtls_ssl_set_dbg().

**Comment by mpg** [comment]
Thanks for your report!

We are aware of that, but hooped it would not be an issue as the debug module could get the thread id from the OS using calls such as `gettid()` on Linux or `pthread_getthreadid_np()` on some BSDs.

If that's not a satisfying solution for you, please explain us why and we may be convinced to add, for example `mbedtls_ssl_set_dbg_ctx()` for a thread-specific context that would be passed to the debug callback.

**Comment by hsleisink** [comment]
gettid is Linux only (not portable) and the _np() are not available on Linux. That's why I provided my own unique id in a portable way. But I'll first think about another solution.

**Comment by mpg** [comment]
I've done some more research and indeed it does not look so easy to get a numeric thread id in a reasonably portable way. I think the best I've found is [here](https://issues.apache.org/jira/browse/HADOOP-11638?focusedCommentId=14346448&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14346448) and I admit it does not look pretty.

Again, it has been planned from the start that we could add a `ssl_context`-specific context pointer for the debug callback for threaded environments if there was a need for it, so if after careful consideration you think this is the cleanest way to go, please tell us.

**Comment by hsleisink** [comment]
My goal is to have an error logfile in which it is clear which lines belong together. Please note that this is mainly in your interest, because in the past all I did which those logfiles is send them to Paul. It was by his request that I added the per-thread-unique ID to the loglines. The unique ID doesn't have to be a thread ID, it can also be an SSL context ID or something like that. If so, how can I extract the unique ID from the context? Perhaps you can include a unique ID to the functions specified via mbedtls_ssl_conf_dbg() by default?

**Comment by pjbakker** [comment]
I agree that this is not purely a Thread ID issue, but more a 'context ID' issue. Thread is less relevant than being able to group logging for each connection context during error hunting..

**Comment by mpg** [comment]
Good point. So this is something we could fix by using eg the address of the `mbedtls_ssl_context` structure as a unique identifier, right?

**Comment by pjbakker** [comment]
The best that we have to offer.

**Comment by hsleisink** [comment]
That's possible, though it wouldn't be my approach. I would go for a context_id integer within the context structure and set it via mbedtls_ssl_init() with an unique id. But in the end, it's you who will read the logfile when I have something to report. :) So, all fine with me.

**Comment by mpg** [comment]
API changes are not an option for now, so we'll go with a slightly dirty way: we'll prepend the "thread ID" (currently address of ssl context, we might later change to a more sophisticated scheme as you suggest) to the output message (just as we did for file and line before 1.3). I agree that if we had considered that before 2.0 was out, adding an argument to the callback would probably have been cleaner, but it's too late now.
