### ISSUE TITLE
No unit tests for mbedtls_cipher_auth_{encrypt/decrypt}() for GCM

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2198]
__Issue:__ There are no unit tests for GCM accessed through the cipher API `mbedtls_cipher_auth_encrypt()` and `mbedtls_cipher_auth_decrypt()`.

__Steps to reproduce:__ Change [mbedtls_cipher_auth_encrypt()](https://github.com/ARMmbed/mbedtls/blob/development/library/cipher.c#L1011) and [mbedtls_cipher_auth_decrypt()](https://github.com/ARMmbed/mbedtls/blob/development/library/cipher.c#L1060) to always fail for GCM, and observe that `make test` still succeeds.

__Task:__ Unit tests for accessing GCM through the cipher abstraction layer must be added to `test_suite_cipher.gcm.*`. Currently, this suite only tests the multipart cipher API. In contrast, accessing CCM through the single-step cipher API _is_ tested in `test_suite_cipher.ccm.*`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2631

**Comment by gilles-peskine-arm** [comment]
Resolved in `development-psa` by https://github.com/ARMmbed/mbedtls/pull/2201 and in `development` by https://github.com/ARMmbed/mbedtls/pull/2395.
