### ISSUE TITLE
mbedtls incorrectly fails validation of TLS chains that has a useless/broken tail

### ISSUE THREAD

**Issue by hannes-landeholm** [ARMmbed/mbedtls#220]
There has been lots of root certificates removed from mozilla lately that has caused problems for me when using a mbedtls based TLS client. I've found at least two sites on the web send an invalid tail of certificate chains that can be ignored. The end of the tail consists of legacy certificates that is no longer trusted but it doesn't matter because an intermediary certificate in the chain is trusted by an installed root certificate.

E.g. server sends: A <- B <- C

We don't trust C as a "top" certificate anymore because it depends on a deprecated/legacy root certificate. However B is now trusted as a "top" certificate by a new trusted root certificate and we didn't really need to check C in the first place.

In essence, if we can trust any of the certs in the chain as a top certificate, we don't need to proceed by walking further down the chain and can simply return an OK status instead and ignoring the rest of the chain. From my experiments this is how certificate validation is normally done and how it's not done in mbedtls.

This is my suggested fix: https://github.com/jumpstarter-io/librcd/commit/0f7c0386093242abecf7b0eada7abf7607f1f29d

Another fix is of course to tell all the people on the internet with a bad certificate chain to fix it by removing the useless tail certificates but unfortunately few of them will care.

**Comment by mpg** [comment]
I could argue that the TLS spec says nothing about ignoring invalid tail certificates, but yeah, in the real world that's something we should do, as it does not harm security in any way and provides better interop. I'll review your patch an integrate it.

**Comment by hannes-landeholm** [comment]
Exactly, thanks!

**Comment by mpg** [comment]
Hey, sorry for not coming back to you earlier on this. Your patch looks good and we would like to incorporate it. Can you please get in touch with @pjbakker regarding our contributor license agreement before we integrate your contribution? Thanks!

**Comment by hannes-landeholm** [comment]
Hey @pjbakker, can you give me information on the contributor license agreement? I can be contacted at hannes@jumpstarter.io.

**Comment by pjbakker** [comment]
@mpg Confirm that a signed CLA has been received

**Comment by cblach** [comment]
Any progress on this issue?. It concerns quite a number of certificates, including a number of Amazon and Google certificates.

**Comment by mpg** [comment]
Woking on it! Unfortunately upon close inspection it appears Hannes' patch is not usable as is, because of interactions with the verify callback, but we're going to implement something along the same general idea.

**Comment by mpg** [comment]
The fix is pending review. Just FYI, your current patch misses the case A -> B -> C -> D where C is trusted but D is not (ie you need to modify `x509_verify_child()` too for longer chains).

**Comment by hannes-landeholm** [comment]
True, I missed that.
