### ISSUE TITLE
ctr_drbg_init ios10  occasionally retrun !=0

### ISSUE THREAD

**Issue by liyunshuang** [ARMmbed/mbedtls#2200]
we are used old vesion Open source library about 2015 year,Recently, we Xcode9 buid this library usēd in ios10  occasionally ctr_drbg_init  retrun !=0。

	entropy_context entropy;
	ctr_drbg_context ctr_drbg;
	const char *pers = "rsa_encrypt";
	entropy_init(&entropy);
	ret = ctr_drbg_init( &ctr_drbg, entropy_func, &entropy,
									   (const unsigned char *) pers,
									   strlen(pers));

        ret!=0

**Comment by RonEld** [comment]
@liyunshuang please specify what is the error code you are receiving, and what is the Mbed TLS version you are using.
note that `mbedtls_ctr_drbg_init()` does not return any error code. `ctr_drbg_init()`, from versions prior to 1.3, do return an error, but these are not supported any more.
It is strongly recomended you update your library to the latest LTS version, and see if the issue reproduces. Note that there have been many updates and security fixes since the unsupported library version you are using.
please look at [this article](https://tls.mbed.org/kb/how-to/upgrade-2.0) to learn how to migrate your code to version 2.x note you will probably need to do additional modifications to fit to later versions.

**Comment by liyunshuang** [comment]
Thank you for your reply.This problem cannot be easily repeated. We need to send a version of app to collect error information. Then I hope to get your help，Thanks for your help。

**Comment by RonEld** [comment]
@liyunshuang As I believe you are working on an old Mbed TLS which is not supported anymore, you should update your Mbed TLS version before you reproduce the issue.

**Comment by liyunshuang** [comment]
> @liyunshuang please specify what is the error code you are receiving, and what is the Mbed TLS version you are using.
> note that `mbedtls_ctr_drbg_init()` does not return any error code. `ctr_drbg_init()`, from versions prior to 1.3, do return an error, but these are not supported any more.
> It is strongly recomended you update your library to the latest LTS version, and see if the issue reproduces. Note that there have been many updates and security fixes since the unsupported library version you are using.
> please look at [this article](https://tls.mbed.org/kb/how-to/upgrade-2.0) to learn how to migrate your code to version 2.x note you will probably need to do additional modifications to fit to later versions.

Thank you for your attention，We have collected the error code and the error path。

Event background：
Between 1 p.m. and 9 p.m., this error happens randomly on iOS10, most often when a new user first installs. 
We should be using older libraries prior to version 1.3, without MBEDTLS_THREADING_C POLARSSL_THREADING_C.

We have collected the error code and the error path ：
The path where our interface call went wrong was  ctr_drbg_init -> ctr_drbg_init_entropy_len -> ctr_drbg_reseed->entropy_func->entropy_gather->platform_entropy_poll->file = fopen( "/dev/urandom", "rb" ),   We found file == NULL，So the interface reports an error。

I have some ideas about this problem, and I hope to correct them：
1. Is it possible that our multi-thread call to this interface causes the /dev/urandom file to be abnormal
2. Is this /dev/urandom file of iOS10 system short of time and some environments have this problem

**Comment by RonEld** [comment]
>Is it possible that our multi-thread call to this interface causes the /dev/urandom file to be abnormal

If you are working in a multithreaded environment, you should enable `MBEDTLS_THREADING_C` .

>Is this /dev/urandom file of iOS10 system short of time and some environments have this problem

This is a platform specific question, and not part of hte Mbed TLS library.

Please upgrade your library to recent version, as stated before, as you are working on a version that is not supported anymore

**Comment by RonEld** [comment]
closing this question.
If issue persists after update, please reopen with relevant information
