### ISSUE TITLE
Need CI option in ssl-opt.sh and combat.sh

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#2204]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux|windows|

**mbed TLS build:**  
Version: 2.13.1

**Description**   

The scripts `ssl-opt.sh` and `compat.sh` automatically detect the CI machines by user, as you can see [here](https://github.com/ARMmbed/mbedtls/blob/2ab14bb2ca8cebc3175b076fa42c293a2bc72202/tests/compat.sh#L1218). This should be controlled by a command line parameter, not by detecting the machine the script is running on. Then the CI can be configured to pass that parameter.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2632

**Comment by mpg** [comment]
I think this was fixed in the meantime by https://github.com/ARMmbed/mbedtls/pull/1535, so I'm closing this issue. @sbutcher-arm Please re-open if you disagree.
