### ISSUE TITLE
ERROR# key_tries not used in mbedtls_ecdsa_sign when mbedtls_ecp_gen_keypair failed

### ISSUE THREAD

**Issue by ccruquan** [ARMmbed/mbedtls#224]
mbedtls_ecdsa_sign will goto cleanup when mbedtls_ecp_gen_keypair failed. 

https://github.com/ARMmbed/mbedtls/blob/development/library/ecdsa.c#L98

**Comment by mpg** [comment]
I think this is intended. The purpose of `key_tries` is to retry in the (highly unlikely) event r is zero mod N, not to retry on any error. `mbedtls_ecp_gen_keypair()` can fail for a number of reasons, including failed memory allocation, and I don't think retrying would be the right thing to do in that case.

Can you please expand on why you think goto cleanup is not the right thing to do here?

**Comment by ccruquan** [comment]
Hi @mpg , thanks for your explain. As you explained, i can't think out other case.

sorry for my poor English :)
