### ISSUE TITLE
9 Lives of Bleichenbacher's CAT - vulnerability

### ISSUE THREAD

**Issue by attritionorg** [ARMmbed/mbedtls#2251]
Regarding this recent disclosure: http://cat.eyalro.net/

They say they contacted the affected vendors, which include mbed TLS. Do you have a fixing commit or any references for this attack?

Thank you!

**Comment by attritionorg** [comment]
tag @sbutcher-arm

**Comment by hanno-arm** [comment]
Hi @attritionorg,

please see the latest [release of Mbed TLS 2.14.1](https://tls.mbed.org/tech-updates/releases/mbedtls-2.14.1-2.7.8-and-2.1.17-released).

Kind regards,
Hanno

**Comment by attritionorg** [comment]
@hanno-arm Saw that this morning, thank you for following up and the great advisory!
