### ISSUE TITLE
build failure when building with mingw on Windows command prompt

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2253]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
windows

**mbed TLS build:**  
Version: 556d7d9e3b09157555310466a47e25a9ebfd8f4e
OS version:Windows 10. 
Configuration:default configuration
using mingw32-make on Windows command prompt, there is build failure

**Expected behavior**   
Build to succeed
**Actual behavior**  
Build fails with the following messages:
~~~
  CC    platform_util.c
platform_util.c: In function 'mbedtls_platform_gmtime_r':
platform_util.c:109:15: warning: implicit declaration of function 'gmtime_s' [-Wimplicit-function-declaration]
     return( ( gmtime_s( tm_buf, tt ) == 0 ) ? tm_buf : NULL );
               ^~~~~~~~
~~~
and
~~~
 CC    aes/aescrypt2.c
../library/libmbedcrypto.a(platform_util.o):platform_util.c:(.text+0x44): undefined reference to `gmtime_s'
collect2.exe: error: ld returned 1 exit status
Makefile:96: recipe for target 'aes/aescrypt2.exe' failed
mingw32-make[1]: *** [aes/aescrypt2.exe] Error 1
Makefile:15: recipe for target 'programs' failed
mingw32-make: *** [programs] Error 2
~~~

*Note: On Visula Studio 2015, build succeeds*
**Steps to reproduce**  
in Windows comand prompt, run:
~~~
mingw32-make CC=gcc
~~~

**Comment by RonEld** [comment]
This is an issue with mingw32, as mentioned in https://sourceforge.net/p/mingw-w64/mailman/message/21523522/
However, we should probably not use `gmtime_s` when building with mingw

**Comment by RonEld** [comment]
The link I referenced was for `gmtime_r`
A better reference is in https://sourceforge.net/p/mingw-w64/bugs/452/

**Comment by RonEld** [comment]
Note: This could probably be fixed, if building mingw32 with `--enable-secure-api`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2657

**Comment by RonEld** [comment]
duplicate of #2087
