### ISSUE TITLE
Add DER-encoded CRTs to `library/certs.c`

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2254]
When building with `MBEDTLS_PEM_PARSE_C` and `MBEDTLS_FS_IO` unset, `ssl_client2` and `ssl_server2` fail to parse any hardcoded test CRTs because those are stored in PEM format in `library/certs.c`. This hardens testing of such minimal configurations.

A potential solution is to also provide DER-encodings of the certificates in `library/certs.c`.

**Comment by RonEld** [comment]
I tend to think this is a bug, because in these conditions, I would expect the application to have a stub `main()` functions, like when other configurations are unset.
