### ISSUE TITLE
transplant gmssl to mbedtls

### ISSUE THREAD

**Issue by swjtk** [ARMmbed/mbedtls#2278]
Does anyone want to transplant gmssl to mbedtls?

**Comment by RonEld** [comment]
@swjtk
Mbed TLS is  highly portable and configurable
I suggest you look ast our KB articles:
* https://tls.mbed.org/kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS
* https://tls.mbed.org/kb/compiling-and-building/how-do-i-configure-mbedtls
* https://tls.mbed.org/kb/generic/abstraction-layers

**Comment by RonEld** [comment]
We believe this issue has been addressed and answered, therefore closing.
If you believe it needs further action, please reopen with additional questions.
Thanks!
