### ISSUE TITLE
Using mbedTLS to sign a certificate given the CA and CSR on an embedded device during provisioning.

### ISSUE THREAD

**Issue by umanayana** [ARMmbed/mbedtls#2280]
Hello, 

I am working on a project that uses a hardware secure element. This is an embedded bare metal project running on a ARM. 
During our provisioning process we need to generate device certificate but these certificate cannot be generated before hand because the hardware secure element generate a public/private key pair.  

What I can do is generate the CSR for the device certificate I want and I have a CA.

So I am looking for a method where I can feed in

- The device CSR
- The CA key pair
- The CA certificate 

Then the output will be the device certificate, which I will then use to provision my hardware secure element.

How can I do this with the mbedTLS stack?

**Comment by RonEld** [comment]
Hi @umanayana 
I apologize for delay
we have an [example](https://github.com/ARMmbed/mbedtls/blob/development/programs/x509/cert_write.c) that writes a certificate given  the CA key ( issuer key ), and an optional CSR.
Note this example doesn't take the V3 extensions from the CSR, though, I'm afraid.
You will need to set the extensions manually, using the `mbedtls_x509write_crt_set_extension()` or the specific extension setting function.

**Comment by RonEld** [comment]
We believe this issue has been addressed and answered, therefore closing.
If you believe it needs further action, please reopen with additional questions.
Thanks!

**Comment by umanayana** [comment]
I have manage to get this working but the certificate has additional data which can't be there. It can't be there because we store parts of the certificate in a hardware secure elements and then rebuild the certificate when it's needed. These additional data elements is causing issue with our rebuilding algorytm. 

The certificate that generated is correct and was verified against the ca_chain, but the additional data has to go. We normally generate the certificate using python with the CSR obtained from the hardware secure element at production time, then transfer it back to the device to be stored securely.

In the picture below the signature field on the right has the parameter 0x05 0x00. But it shouldn't as the python generated certificate don't have this and out rebuild algorithm is based on that.

How could I remove this or not have it generated at all.

![image](https://user-images.githubusercontent.com/34135197/60544168-2a717300-9ce6-11e9-81b9-b5b753084a13.png)

**Comment by umanayana** [comment]
Resolved, by removing NULL asn1 encoding from the certificate. Certificate validate correctly still.

```
int mbedtls_asn1_write_algorithm_identifier( unsigned char **p, unsigned char *start,
                                     const char *oid, size_t oid_len,
                                     size_t par_len )
{
    int ret;
    size_t len = 0;
#ifndef CUSTOM_MBEDTLS_NO_NULL_TLV_IN_X509_GENERATION
    if( par_len == 0 )
        MBEDTLS_ASN1_CHK_ADD( len, mbedtls_asn1_write_null( p, start ) );
    else
        len += par_len;
#else
    len += par_len;
#endif

    MBEDTLS_ASN1_CHK_ADD( len, mbedtls_asn1_write_oid( p, start, oid, oid_len ) );

    MBEDTLS_ASN1_CHK_ADD( len, mbedtls_asn1_write_len( p, start, len ) );
    MBEDTLS_ASN1_CHK_ADD( len, mbedtls_asn1_write_tag( p, start,
                                       MBEDTLS_ASN1_CONSTRUCTED | MBEDTLS_ASN1_SEQUENCE ) );

    return( (int) len );
}```
