### ISSUE TITLE
2.7.8 When MBEDTLS_PLATFORM_NO_STD_FUNCTIONS is defined mbedtls_snprintf cannot get MBEDTLS_PLATFORM_STD_SNPRINTF!

### ISSUE THREAD

**Issue by yemair** [ARMmbed/mbedtls#2284]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.7.8
Configuration: 
Define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
Do not define MBEDTLS_PLATFORM_SNPRINTF_ALT and MBEDTLS_PLATFORM_SNPRINTF_MACRO

**Expected behavior**   
It can build pass

**Actual behavior**  
build failed for when MBEDTLS_PLATFORM_NO_STD_FUNCTIONS is defined, MBEDTLS_PLATFORM_STD_SNPRINTF will not be defined. And mbedtls_snprintf cannot find MBEDTLS_PLATFORM_STD_SNPRINTF!

----------------------------------------------------------------

**Suggested enhancement**  
Define it to snprintf simply.
-----------------------------------------------------------------

**Comment by RonEld** [comment]
Hi @yemair 
Thank you for your question.
I don't think this is a bug, as this is not the correct behavior.
As the [documentation](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/config.h#L183) mentions:
~~~
/**
 * \def MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
 *
 * Do not assign standard functions in the platform layer (e.g. calloc() to
 * MBEDTLS_PLATFORM_STD_CALLOC and printf() to MBEDTLS_PLATFORM_STD_PRINTF)
 *
 * This makes sure there are no linking errors on platforms that do not support
 * these functions. You will HAVE to provide alternatives, either at runtime
 * via the platform_set_xxx() functions or at compile time by setting
 * the MBEDTLS_PLATFORM_STD_XXX defines, or enabling a
 * MBEDTLS_PLATFORM_XXX_MACRO.
 *
 * Requires: MBEDTLS_PLATFORM_C
 *
 * Uncomment to prevent default assignment of standard functions in the
 * platform layer.
 */
~~~

This means that if you define `MBEDTLS_PLATFORM_NO_STD_FUNCTIONS` , you are *not* using the standard functions, and you *have* to define `MBEDTLS_PLATFORM_SNPRINTF_ALT` or `MBEDTLS_PLATFORM_SNPRINTF_MACRO`.
Am I missing something?

**Comment by RonEld** [comment]
Since we don't believe this is a bug, we believe we have answered your question, therefore closing.
If you believe it needs further action, please reopen with additional questions.
Thanks!
