### ISSUE TITLE
Building For Android NDK r10e Arm

### ISSUE THREAD

**Issue by mdmdmdmd** [ARMmbed/mbedtls#229]
Discovered that alignment of some structures like entropy context is very important for stability of SSL operations.

Make sure all memory structures are on 4 or 8 byte alignment boundaries.

Random Android SIGBUS exceptions are thrown otherwise.

Not tested on Android Intel, Only Arm v7 compiler so far on android 4.4.2 and 4.1.1

**Comment by mpg** [comment]
Thanks for your report, but I'm afraid we'll need more details in order to act on it: which structures precisely, and how comes the compiler is not already enforcing the required alignment? (Also, ARM-v7m is a 32-bit architecture, so I'm a bit surprised it needs 8-byte alignment for some objects.)

**Comment by mpg** [comment]
Tagging as invalid as the initial question does not contain enough information to act upon. If more information is not provided, I'll probably close this issue.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSSL-474
