### ISSUE TITLE
2.14.1: Compilation issue on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [ARMmbed/mbedtls#2310]
When compiling on NetBSD (8.99.27/amd64) the build stops because `sockaddr_storage` is not defined.

The problem is that in `library/net_sockets.c`, the symbol `_POSIX_C_SOURCE` is defined to `200112L`. In contrast to Linux, NetBSD _removes_ symbols from the namespace when particular namespaces are requested.

(I think this might also be a problem on Solaris because it also likes to removes symbols.)
Workaround:
````
--- library/net_sockets.c.orig  2018-12-02 13:20:52.000000000 +0000
+++ library/net_sockets.c
@@ -22,7 +22,7 @@
 /* Enable definition of getaddrinfo() even when compiling with -std=c99. Must
  * be set before config.h, which pulls in glibc's features.h indirectly.
  * Harmless on other platforms. */
-#define _POSIX_C_SOURCE 200112L
+//#define _POSIX_C_SOURCE 200112L
 
 #if !defined(MBEDTLS_CONFIG_FILE)
 #include "mbedtls/config.h"
````
Please note the comment is incorrect ;)

**Comment by gilles-peskine-arm** [comment]
`struct sockaddr_storage` is in [SUSv3](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/socket.h.html) with no note that it's an extension to POSIX.1-2001, so [`#define _POSIX_C_SOURCE 200112L`](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap02.html#tag_02_02_01) should bring it in. What does it take to get `struct sockaddr_storage` on NetBSD?

**Comment by gilles-peskine-arm** [comment]
We don't have NetBSD on our CI. A patch would be welcome, but of course it mustn't break other platforms. Commenting out `#define _POSIX_C_SOURCE 200112L` breaks glibc according to this comment so that's out. Note that Mbed TLS runs on many platforms that only implement a subset of POSIX, so sometimes strict conformance to POSIX isn't enough.

**Comment by 0-wiz-0** [comment]
AFAIK, both Solaris and NetBSD hide symbols when particular requirements are defined using e.g. _POSIX_C_SOURCE.
The simple solutions IMO are:
1.
````
#ifndef __NetBSD__
#define _POSIX_C_SOURCE 200112L
#endif
````
or
2. (in my eyes preferred) just define the symbol on the platform(s) that need it. I don't know the defines for that, sorry.
