### ISSUE TITLE
How to use mbedtls_ecdsa_sign_det()

### ISSUE THREAD

**Issue by danzadok** [ARMmbed/mbedtls#2312]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug | Enhancement\Feature Request | Question
- Priority: Blocker 

For signing a BitCoin transaction, I need to use the function mbedtls_ecdsa_sign_det(). Correct?
I cannot find any example how to call this function.
The first parameter is grp that needs to be initialized. I've used mbedtls_ecp_group_init(&grp); to initialize it, but this is not enough. The first failure is in ecdsa_sign_det_restartable() which calculates the grp_len and it turns out to 0. And as a result mbedtls_mpi_write_binary() fails .

So I initilized  grp.nbits as the number of bits in the private key.

I still fail, because when mbedtls_ecdsa_sign() is called it checks for grp->N.p which is NULL. 
How it should be initialized?

I am running this code on an Appolo3 ARM based board, from Ambiq.
No OS is on the board.

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by RonEld** [comment]
@danzadok 
I will answer your questions related to Mbed TLS.

Mbed TLS is shipped with several sample programs.
You can look in the [`ecdsa`](https://github.com/ARMmbed/mbedtls/blob/development/programs/pkey/ecdsa.c) sample application, which calls `mbedtls_ecdsa_write_signature()`, which basically calls `mbedtls_ecdsa_sign()` and generates ASN1 notation for the signature. In case `MBEDTLS_ECDSA_DETERMINISTIC` is defined, the deterministic ecdsa is used instead.

If you do not need ASN.1, you can call directly `mbedtls_ecdsa_sign_det()`, withe the relevant parameters that were used in the call for `mbedtls_ecdsa_write_signature()`

**Comment by RonEld** [comment]
We believe this question was answered, therefore closing.
If you think it requires further action, please reopen.
