### ISSUE TITLE
STM32F446RE how to create own entropy source?

### ISSUE THREAD

**Issue by Miroqil** [ARMmbed/mbedtls#2333]
How to use mbedtls in stm32f4 without ctr_drbg with static values or static entropy? I use mbedTLS in uvision Keil v5

**Comment by RonEld** [comment]
Hi @Miroqil 
Could you please edit the description with more details on your question?
For example:
* What OS?
* What is your use case?

**Comment by Miroqil** [comment]
How to use mbedtls in stm32f4 without ctr_drbg with static values or static entropy? I use mbedTLS in uvision Keil v5

**Comment by RonEld** [comment]
I have copied your comment to the description, for better view

**Comment by RonEld** [comment]
Your question is still not clear to me, DRBG is not entropy.
Why don't you want to use ctr_drbg? Do you wish to use hmac_drbg?

It is better you use a drbg such as ctr_drbg with a strong entropy source for seeding your DRBG.

In STM32F446RE you can use the HW entropy source as a strong source.
You can look in the [device's driver in Mbed OS](https://github.com/ARMmbed/mbed-os/blob/f3424da060734fa9e27bf6a798747fb48ad63938/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.c#L242) how the entropy is gathered.

To learn how to add a HW entropy source, please look at the following articles:
* https://tls.mbed.org/kb/how-to/add-entropy-sources-to-entropy-pool
* https://tls.mbed.org/kb/development/hw_acc_guidelines

Once you define `MBEDTLS_ENTROPY_HARDWARE_ALT` you should implement [`mbedtls_hardware_poll()`](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/entropy_poll.h#L92) in afile that will compile in your application.

**Comment by Miroqil** [comment]
Hi RonEld !
I use keil uvision 5 and with cubeMX generate code. when I use mbedTLS pack in keil without RTOS I got error MBEDTLS_ERR_CTR_DRBG_ENTROPY_SOURCE_FAILED -0x0034. How Can I solve this problem?

**Comment by RonEld** [comment]
Hi @mickrau 
The error you are receiving is because the `entropy_gather_internal()` has returned an error.
You should check what error it has returned. I can only *assume* that your implementation of the hardware entropy collection returned a failure.

**Comment by RonEld** [comment]
Hi @Miroqil 
Do you still get the error?
Is there any further question?
Thanks!

**Comment by Miroqil** [comment]
Hi @RonEld 
I can not implement MbedTLS AES and RSA cryptography on STM32F446RE. If you can build keil mvison5 project of implementing RSA and AES on this board pleaseeee send me it.
Thakns!

**Comment by RonEld** [comment]
Hi @Miroqil 
Unfortunately, Iwedon't have AES and RSA drivers for STM32F446RE, however, you can look at STM's implementation for [AES on MBED-OS](https://github.com/ARMmbed/mbed-os/blob/master/features/mbedtls/targets/TARGET_STM/aes_alt.c), which should be similar, I believe.
As Mbed TLS doesn't have driver implementations for different target, I cannot give you the RSA implementation.
Regards

**Comment by Miroqil** [comment]
Thanks !!!
