### ISSUE TITLE
check-python-files.sh fails

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#2348]
### Description
- Type: Bug 
- Priority:  Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.16.0
OS version: Ubuntu 16.04  

**Expected behavior**   

Running this script with pyling installed should find no error and exit zero. Additionally, when errors are found it should exit non-zero, which is not always the case.

**Actual behavior**  

On my machine it prints the following an and exits 2:
```
************* Module generate_test_code
W:282,25: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:298,65: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:399,35: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
************* Module test_generate_test_code
E: 38, 4: No name 'mock' in module 'unittest' (no-name-in-module)
E: 38, 4: Unable to import 'unittest.mock' (import-error)
************* Module mbedtls_test
E:185,22: Instance of 'MbedTlsTest' has no 'get_config_item' member (no-member)
```

On @gilles-peskine-arm machine (same OS and version!) it prints the following and exits 0 despite the error:
```
************* Module generate_test_code
W:282,25: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:298,65: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:399,35: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
************* Module test_generate_test_code
E: 38, 4: No name 'mock' in module 'unittest' (no-name-in-module)
E: 38, 4: Unable to import 'unittest.mock' (import-error)
```

**Steps to reproduce**  

Install pylint then invoke `tests/scripts/check-python-files.sh`.

**Comment by gilles-peskine-arm** [comment]
The problem in `test_generate_test_code` is because that script includes different modules in Python2 and Python3, but `pylint` is for Python2 on most platforms including Ubuntu. `check-python-files` should invoke `pylint3`, which returns different errors.

**Comment by mpg** [comment]
Additionally, `set -e` should be used in the `check-python-files.sh`.

**Comment by gilles-peskine-arm** [comment]
`check-python-files.sh` should use `set -e` or record errors so that it exits with a nonzero value on errors. Furthermore it should call `pylint3` unconditionally. If we want to skip pylint when not available then we should do that from `all.sh`.
