### ISSUE TITLE
mbedtls-2.0.0/library/ssl_tls.c:6827: possible missing break in switch ?

### ISSUE THREAD

**Issue by dcb314** [ARMmbed/mbedtls#235]
mbedtls-2.0.0/library/ssl_tls.c:6827]: (warning) Variable 'min_major_ver' is reassigned a value before the old one has been used. 'break;' missing?

**Comment by mpg** [comment]
Thanks! Just curious, which compiler (version, used flags) or other tool gave you this warning? We'll probably want to add it to our collection :)

**Comment by dcb314** [comment]
A static analysis tool called cppcheck, available from sourceforge.

**Comment by mpg** [comment]
Thanks!
