### ISSUE TITLE
Two typecasts missing in cipher.h

### ISSUE THREAD

**Issue by cblach** [ARMmbed/mbedtls#236]
I get two minor warnings upon compiling a program using mbedtls. This is due to return values not being casted properly in cipher.h on line 371 and 419:

```
/usr/local/include/mbedtls/cipher.h:371:30: warning: 
      implicit conversion changes signedness: 'const unsigned int'
      to 'int' [-Wsign-conversion]
    return ctx->cipher_info->iv_size;
    ~~~~~~ ~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/mbedtls/cipher.h:419:30: warning: 
      implicit conversion changes signedness: 'const unsigned int'
      to 'int' [-Wsign-conversion]
    return ctx->cipher_info->key_bitlen;
    ~~~~~~ ~~~~~~~~~~~~~~~~~~^~~~~~~~~~
```
Casting the return values to (int) should fix these issues.

**Comment by mpg** [comment]
Thanks for your report. I'll add explicit casts to int. Out of curiosity, which compiler (version, flags) gives you these warnings?

**Comment by cblach** [comment]
I currently use clang 3.5 and the following flags:
-pipe -std=c11 -g -fPIE -ftls-model=local-exec \
-fdata-sections -ffunction-sections \
-D_POSIX_SOURCE=1 -D_POSIX_C_SOURCE=200809L -D_BSD_SOURCE \
-D_XOPEN_SOURCE -Wdeclaration-after-statement \
-Wformat=2 -pedantic -Wall -Wextra -Wconversion \
-Wformat-security -fstack-protector --param ssp-buffer-size=4"

It's probably -Wconversion which gives the warning.
