### ISSUE TITLE
Mbedtls 2.16.0 include paths inconsistent

### ISSUE THREAD

**Issue by hasselyoko** [ARMmbed/mbedtls#2360]
I'm doing an upgrade from the Mbedtls 2.4.2 branch to Mbedtls 2.16.0 and I noticed that compilation fails because of inconsistent include paths of Mbedtls headers.
The inconsistency seems to include the, for my branch, new files.

##Example:
File: cipher.h
39: #include "mbedtls/platform_util.h"
I would expect:
39: #include "platform_util.h"

Above is done for all other (older) Mbedtls includes, so I suspect this are typo's? All headers are in the same folder.

**Comment by RonEld** [comment]
Dear @hasselyoko 
Thank you for reporting this issue!
I believe it has already been fixed in #2319

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2733

**Comment by RonEld** [comment]
This issue has been fixed in #2319 , and merged, so closing.
