### ISSUE TITLE
Verification of a signature

### ISSUE THREAD

**Issue by naynajain** [ARMmbed/mbedtls#2362]
RSA Signature Verification:

I have just started exploring mbedTLS. and I want to use it for RSA signature verification.
I was wondering if the verification function can accept the whole certificate rather than just the public key.

What I see is that it accepts only public key.

Can someone confirm please ?

Thanks & Regards,
     - Nayna

**Comment by naynajain** [comment]
Thanks Ron for the explanation.

Yes I need to use the public key from the certificate for other means. Basically it is to verify the signed data.

What I understand is :: 
I should use below API to extract the public key in as mbedtls_pk_context.

int mbedtls_x509_crt_parse( mbedtls_x509_crt *chain, const unsigned char *buf, size_t buflen );

After that I should use below API where I pass the above extracted mbedtls_pk_context from certificate context, pass the hashed data and signature to verify.

int mbedtls_pk_verify( mbedtls_pk_context *ctx, mbedtls_md_type_t md_alg,
               const unsigned char *hash, size_t hash_len,
               const unsigned char *sig, size_t sig_len );

Also, my understanding is that it can handle both PEM/DER format certificates.

Please confirm.
Thanks & Regards,
       - Nayna

**Comment by RonEld** [comment]
@naynajain Yes, your undestanding is braodly correct.
A few comments, though:
* >should use below API to extract the public key in as mbedtls_pk_context.

  That API is to parse the certificate, to `mbedtls_x509_crt` struct. That certificate contains a pointer to `mbedtls_pk_context` of the server certificate.

* The `mbedtls_pk_context` is freed once the certificate structure itself is freed, so you will need to copy the structure to your own local structure. Keep in mind that this is not a straight forward `memcpy`, as it contains a pointer to `pk_ctx`, which varies according to key type (RSA or ECC).

* >Also, my understanding is that it can handle both PEM/DER format certificates.

  Yes, assuming you have `MBEDTLS_PEM_PARSE_C` configured

**Comment by RonEld** [comment]
We believe this issue has been addressed and answered, therefore closing.
If you believe it needs further action, please reopen with additional questions.
Thanks!
