### ISSUE TITLE
Is this line still needed?

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2377]
## Question

https://github.com/ARMmbed/mbedtls/blob/11cdb0559e46dbe9301bd37a36d583e3d2fefd3b/library/bignum.c#L2104

The `i` value was used for calculating the upper limit of the next `for` loop.
Currently (since the commit https://github.com/ARMmbed/mbedtls/commit/b9eb7866ebddb7481a488204fabc52740a511b91) this limit is passed as a function parameter.

**Comment by RonEld** [comment]
@irwir Thank you for your question.
I am not sure I follow you, `i` in this line in `miller-rabin` is still used in the next `for` loop , and not given as a function parameter.

**Comment by irwir** [comment]
@RonEld
> I am not sure I follow you,

Code quote was taken from the old commit. Please compare with the current code.

**Comment by RonEld** [comment]
@irwir I was looking at the current code, and `i` is still used in the `for` loop.
However, I see what you mean, as it is initiated with `0`, thus I believe you are correct and the line is redundant.
Thank you for raising this issue!

**Comment by irwir** [comment]
Yes, the _value_ is not used and the calculation had no side effects. The _variable_ is in use,, but I did not suggest to remove  the declaration.
