### ISSUE TITLE
On Target Tests do not call mbedtls_platform_terminate()

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2378]
### Description
- Type: Bug
- Priority: Major
`mbedtls_platform_terminate()` is not called on target Green Tea tests. This could cause for undefined behavior on some platforms, when running many tests, causing the `mbedtls_platform_init()` to be called without termination in between.
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS
**mbed TLS build:**  
Version: 2.16.0
**Expected behavior**   
When tests finish, `mbedtls_platform_terminate()` should be called
**Actual behavior**  
The tests run in an infinite loop, until `__host_test_finished` is received, and then the htrunner terminates the test, without finishing `main()` function, where `mbedtls_platform_terminate()` is currently called.
This could 
**Steps to reproduce**

**Comment by RonEld** [comment]
In particular, when `mbedtls_test.py` notifies complete, the host test runner closes the connection, and the client greentea test is stuck in `greentea_getc()`

**Comment by tom-cosgrove-arm** [comment]
Closing this issue as on-target testing was removed from Mbed TLS in PR #5116 (#4944 for 2.28 LTS), following the announcement in issue #4912 in Sep 2021.

A separate issue (#5595) has been raised as a placeholder, in case we want to come back to it at some point in the future.
