### ISSUE TITLE
Printing errors as `string` (not `int`) e.g. `MBEDTLS_ERR_NET_SOCKET_FAILED` not `-0x0042`

### ISSUE THREAD

**Issue by p-i-** [ARMmbed/mbedtls#2379]
Feature Request, low-priority

`mbedtls_net_connect` may return -0x0042

This means the developer needs to look up & find:
```
#define MBEDTLS_ERR_NET_SOCKET_FAILED                     -0x0042  /**< Failed to open a socket. */
```

It would really be nice to have a `const char* string_for_errcode(int)` function, so `string_for_errcode(-0x0042)` returns `"MBEDTLS_ERR_NET_SOCKET_FAILED\0"`.

This could be done with some macro cunning / tail-recursion I think.
```
#define A 1
#define B 2

int vals[1024];
const char* keys[1024];
{
    int index=0;

    #define ADD(x) vals[index] = x; keys[index] = #x; ++index;
    #define ADD_ALL(x, ...)  ADD(x);  ADD_ALL(__VA_ARGS__);
    ADD_ALL(A,B);
}
```
but my C is rusty.

**Comment by irwir** [comment]
> This means the developer needs to look up & find:

Developers may use this error printing function:
https://github.com/ARMmbed/mbedtls/blob/8e763329adddfad47df9e3f048d25afbfce11ac4/include/mbedtls/error.h#L123
The output would be: `NET - Failed to open a socket`.

**Comment by RonEld** [comment]
@p-i- 
As @irwir rightfully claimed, we have such an API.
In addition, we have a utility application [strerror](https://github.com/ARMmbed/mbedtls/blob/development/programs/util/strerror.c) that runs on your PC, receives the error number ( in hexadecimal or decimal ), and prints the error.
For example:
~~~
./programs/util/strerror -0x0042
Last error was: -0x0042 - NET - Failed to open a socket
~~~

**Comment by RonEld** [comment]
We believe this question was answered, so closing it. If you think it requires further action, please reopen with additional information
