### ISSUE TITLE
mbedtls_zeroize should be inside FUNC_ALT ifdef

### ISSUE THREAD

**Issue by hnrkp** [ARMmbed/mbedtls#239]
When adding alternate implementations for sha256, md5, sha1 I got a few warnings. It seems that mbedtls_zeroize should just be moved down under the ifdef XXX_ALT, like it's working in aes.c, others.

sha256.c:36:13: warning: 'mbedtls_zeroize' defined but not used [-Wunused-function]
 static void mbedtls_zeroize( void *v, size_t n ) {
md5.c:36:13: warning: 'mbedtls_zeroize' defined but not used [-Wunused-function]
 static void mbedtls_zeroize( void *v, size_t n ) {
sha1.c:36:13: warning: 'mbedtls_zeroize' defined but not used [-Wunused-function]
 static void mbedtls_zeroize( void *v, size_t n ) {

I can produce a patch if needed, but seemed trivial enough not to bother.. :-)

**Comment by mpg** [comment]
Thanks for your report! That will be fixed.
