### ISSUE TITLE
ssl_client2 handshake failure with -0x2700.

### ISSUE THREAD

**Issue by KShingala** [ARMmbed/mbedtls#2394]
### Description
- Type: Bug | Question

ssl_client2 fails with error -0x2700. This error indicates that the verification of the CA chain of the server failed. I am using the ssl_server example to test. I notice this issue in the development branch and 2.7 branch. Is this the expected behaior?

**Comment by RonEld** [comment]
Hi @KShingala 
error `-0x2700` is certificate verification failure.
I would suggest checking the verification flags as well.
More information can be found in https://tls.mbed.org/kb/development/debugging-tls
The Mbed TLS test application use tests certificates. If I had to guess, I would say you haven't set the trusted root CA certificate of the server certificate you are trying to connect to.
Please add the `ca_cert` or `ca_path` param to your application

**Comment by KShingala** [comment]
Thank you for the quick reply @RonEld. The error I get MBEDTLS_X509_BADCERT_BAD_MD. 
I see that there is an additional configuration MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES. The test certificates use SHA1 as the signature algorithm, so by default, the example ssl_client2 does not work out of the box in the current branch. 

What surprises me is that this flag does not affect the use of SHA1 is own CA chain, only the verification.

**Comment by RonEld** [comment]
Yes, this is another reason for such a failure.
You can also run the client applications with parameter `allow_sha1=1`
More information can be found in https://github.com/ARMmbed/mbedtls/pull/1520

This flag is intended and used in certificate verification. I am not sure what you mean that it does not affect usage of SHA1 in own CA chain

**Comment by KShingala** [comment]
The server uses the same configuration. And there does not seem any check to use a CA chain with SHA1 on the server. I would have expected the flag to disallow setting the own CA chain from using SHA1.

**Comment by RonEld** [comment]
I see. I understand that you are testing with `ssl_server2`. Am I right? #1520 should fix this

**Comment by KShingala** [comment]
I am using ssl_server. Yes, #1520 should fix it. Thank you!
