### ISSUE TITLE
Shadowed declarations in ssl_tls.c

### ISSUE THREAD

**Issue by hnrkp** [ARMmbed/mbedtls#240]
I have a few cosmetic warnings when building mbedtls 2.0 with maybe more warnings than usual enabled:

ssl_tls.c: In function 'mbedtls_ssl_derive_keys':
ssl_tls.c:683:13: warning: declaration of 'ret' shadows a previous local [-Wshadow]
         int ret;
             ^
ssl_tls.c:474:9: warning: shadowed declaration is here [-Wshadow]
     int ret = 0;
         ^
ssl_tls.c: In function 'ssl_encrypt_buf':
ssl_tls.c:1444:17: warning: declaration of 'ret' shadows a previous local [-Wshadow]
             int ret = ssl->conf->f_rng( ssl->conf->p_rng, ssl->transform_out->iv_enc,
                 ^
ssl_tls.c:1417:13: warning: shadowed declaration is here [-Wshadow]
         int ret;
             ^

It seems the declaration can just be removed and the warning squelched that way. I can produce a patch if you want to, but I had to wrestle a bit to get everything working on my platform, so I have nothing readily available..

**Comment by mpg** [comment]
Thanks for reporting this! -Wshadow looks like a useful warning, I guess we'll want to add it to our standard build options. I'll fix those warnings.
