### ISSUE TITLE
Yotta build fails on Windows

### ISSUE THREAD

**Issue by anttiylitokola** [ARMmbed/mbedtls#241]
Following error occurs while executing "yotta install mbedtls" command.
C:\Users\antyli01\OOB>yotta install mbedtls
info: get versions for mbedtls
info: download mbedtls@2.0.4 from https://yotta-private.herokuapp.com
info: get versions for win
error: could not install target win  for win
error: win does not exist in the targets registry. Check that the name is correct, and that it has been published.

So is the yotta module supported only on Linux and should I use CMake instead?

**Comment by mpg** [comment]
Currently there is no yotta target for windows. This is independent from mbed TLS. Once there is a yotta target for windows, I expect mbedtls to build just fine with it (though surprises do happen).

Currently our yotta module is tested with the following yotta targets: frdm-k64f-gcc, frdm-k64f-armcc, x86-osx-native, x86-linux-native.

If you want to build mbed TLS on Windows, then I suggest you clone our repo or [download our latest tarball](https://tls.mbed.org/download) and use one of our other build systems. Options for Windows include:

* The provided Visual Studio project files in the visualc folder
* Using cmake with the Visual Studio generator that matches your version, eg `cmake -G "Visual Studio 12 2013 Win64" /path/to/source` then `cmake --build .`
* Using cmake or the makefiles with gcc in a unix-like environment such as MSYS2 or Cygwin
* Using mingw32-make.

Alternatively, you can create a yotta target for windows yourself, which could probably be helpful to others are well. James suggests that looking at the existing native targets for linux and osx could be a good starting point:

https://github.com/ARMmbed/target-x86-osx-native
https://github.com/armmbed/target-x86-linux-native

**Comment by anttiylitokola** [comment]
Some information was missing on my first post so my plan is to build for frdm-k64f target on Windows. Then I noticed that I have just missed yotta target command before executing yotta install mbedtls. After that everything went smoothly and I was able to build and run the examples.

**Comment by mpg** [comment]
Ok, cool!
