### ISSUE TITLE
Invalid Bitcoin sign because "S is too large"

### ISSUE THREAD

**Issue by danzadok** [ARMmbed/mbedtls#2423]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type:  Question
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
Mbed windows

**mbed TLS build:**  
Version: commit 8e763329adddfad47df9e3f048d25afbfce11ac4 (Wed 23 Jan 2019)  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question
Hello
I am  a newbie in MBEDTLS.

I am using the mbedtls_ecdsa_write_signature_det() API to sign a Bitcoin transaction.
The API succeeds and I get the R and S in ASN.1 format.
I've verified the signature and it also was OK.
When I broadcast the transaction to the Bitcoin network, I get an error that the "S is too large"
I've found the following article:
https://blog.blockcypher.com/enforcing-low-s-values-to-eliminate-a-bitcoin-network-attack-3582fc0ae948

It seems that MBEDTLS ECDS signing is different than what BitCoin expects for.
Would you please help?

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by RonEld** [comment]
Hi @danzadok 
thank you for your question.
Mbed TLS is intended first and foremost for TLS handshakes.
`mbedtls_ecdsa_write_signature_det()` writes a signature in ASN.1 notation, as defined in [RFC 4492](https://tools.ietf.org/html/rfc4492).
If Bitcoin transaction requires different representation to the signature, I suggest you call `mbedtls_ecdsa_sign_det()`, and the output signature ( `r` and `s` ) should be formatted in the way that you require, according to the Bitcoin specifications. however, the issue doesn't seem to be related to the representation of `s` and `r`, but the *value* of `s` that is being sent, which is larger than accepted.

As you can see, in the [code](https://github.com/ARMmbed/mbedtls/blob/development/library/ecdsa.c#L296), the ephemeral key pair is generated, by first calculating `r`, using randomness in the process, and then calculating `s`, until `s` , and check that `s` is not equal to `0`. If you want to modify the code, you might consider adding a check that `s` does not exceed the upper limit that want to check.

**Comment by danzadok** [comment]
Thanks a lot Ron.
You are the best!
