### ISSUE TITLE
X.509 CRT parser returns ASN.1 error code on empty TBSCertificate

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2431]
__Context:__ The first field in a `TBSCertificate` is the version which is parsed through `x509_get_version()`:
https://github.com/ARMmbed/mbedtls/blob/f352f75f6bd5734c8f671323dd6ab32472d5da34/library/x509_crt.c#L380-L400
If this function finds an empty buffer, the call to `mbedtls_asn1_get_tag()` will return `MBEDTLS_ERR_ASN1_OUT_OF_DATA`, which is then returned unmodified to the caller.

__Issue:__ This is not in line with the rest of the module, which wraps low-level ASN.1 error code with high-level X.509 error codes before returning. 

__Task:__ Make sure `x509_crt_parse_der_core()` always returns an X.509 error code. Add a test exercising an empty `TBSCertificate` body.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2781

**Comment by hanno-arm** [comment]
This also applies to `x509_get_uid()` in `x509_crt.c`.

**Comment by hanno-arm** [comment]
This also applies to `mbedtls_x509_get_ext()`.
