### ISSUE TITLE
example-tls-client test doesn't work

### ISSUE THREAD

**Issue by mikaleppanen** [ARMmbed/mbedtls#244]
Test example-tls-client doesn't work

It either fails to this error:

```

{{timeout;120}}
               {{host_test_name;default}}
                                         {{description;mbed TLS example HTTPS client}}
      {{test_id;MBEDTLS_EX_HTTPS_CLIENT}}
                                         {{start}}


Client IP Address is 10.45.0.28
Connecting to mbed.org:443
mbed.org address: 217.140.101.20
mbedtls_ssl_write() failed: -0x7b00 (-31488): SSL - Processing of the ServerKeyExchange handshake message failed
```

Or stops after "mbed.org address" line:

```
{{timeout;120}}
               {{host_test_name;default}}
                                         {{description;mbed TLS example HTTPS client}}
      {{test_id;MBEDTLS_EX_HTTPS_CLIENT}}
                                         {{start}}


Client IP Address is 10.45.0.28
Connecting to mbed.org:443
mbed.org address: 217.140.101.20

```

**Comment by mpg** [comment]
Can you test the version from the development branch? I fixed some misuse of minar yesterday that I think was the reason for the freeze. If using the development branch is inconvenient to you, I plan to upload a version to the yotta registry some time today (waiting for another fix).

**Comment by bridadan** [comment]
Can confirm having this issue in the current version in the yotta registry. Trying the latest development branch from the repository fixed the issue!
