### ISSUE TITLE
Use of uninitialized variable in server-side `ssl_pick_cert()`

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#2444]
__Context:__ The server-side routine `ssl_pick_cert()` iterates through the list of available CRTs and picks one which is suitable for the chosen ciphersuite. For that, it e.g. checks the key type, key usage contraints, and the ECC curve type.

__Issue:__ Consider the following parts of `ssl_pick_cert()` checking the current candidate's key usage:
https://github.com/ARMmbed/mbedtls/blob/f352f75f6bd5734c8f671323dd6ab32472d5da34/library/ssl_srv.c#L700-L706
https://github.com/ARMmbed/mbedtls/blob/f352f75f6bd5734c8f671323dd6ab32472d5da34/library/ssl_srv.c#L745-L751
Inside `mbedtls_ssl_check_cert_usage()`, we have
https://github.com/ARMmbed/mbedtls/blob/f352f75f6bd5734c8f671323dd6ab32472d5da34/library/ssl_tls.c#L9515-L9519
which reads and writes `*flags` without prior modification. This leads to undefined behavior from reading an uninitialized variable.

It seems that we don't have any tests exercising this code-path in place, as adding a `return( -1 );` in the `mbedtls_ssl_check_cert_usage()` branch doesn't appear to break anything in the tests.

__Criticality:__ Minor, as the `flags` field isn't used at all outside of the call to `mbedtls_ssl_check_cert_usage()`; success or failure is determined by the return value only.

__Task:__ Initialize `flags` in each iteration of the loop and make sure that there is a test in `ssl-opt.sh` exercising the above code-path.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2787

**Comment by AndrzejKurek** [comment]
PR created here: https://github.com/ARMmbed/mbedtls/pull/3105. Please also note that due to recent improvements to the ssl test suite, adding a forementioned `return -1;` to `mbedtls_ssl_check_cert_usage` makes many of the test cases fail.
