### ISSUE TITLE
tls-client Example does not compile with GCC

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#245]
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/source/main.cpp: In member function 'socket_error_t HelloHTTPS::startTest(const char*)':
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/source/main.cpp:155:53: error: too few arguments to function 'int mbedtls_ssl_config_defaults(mbedtls_ssl_config*, int, int, int)'
                         MBEDTLS_SSL_TRANSPORT_STREAM)) != 0) {
                                                     ^
In file included from /home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/source/main.cpp:30:0:
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/yotta_modules/mbedtls/mbedtls/ssl.h:2202:5: note: declared here
 int mbedtls_ssl_config_defaults( mbedtls_ssl_config *conf,
     ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/source/main.cpp: In member function 'void HelloHTTPS::onDNS(socket_error_t)':
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/tls-client/source/main.cpp:393:25: error: 'struct socket_addr' has no member named 'type'
         if (e->i.d.addr.type == SOCKET_STACK_UNINIT) {
                         ^
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

**Comment by mpg** [comment]
See my comment on #247
