### ISSUE TITLE
tls-client Example does not compile with ArmCC

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#246]
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ yt clean
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ yt target frdm-k64-armcc
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ yt build
info: get versions for frdm-k64-armcc
error: could not install target frdm-k64-armcc at * for frdm-k64-armcc
error: frdm-k64-armcc does not exist in the targets registry. Check that the name is correct, and that it has been published.
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ ls
module.json  README.md  source  yotta_modules  yotta_targets
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ yt target
frdm-k64-armcc,* missing
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$ yt up
info: get versions for frdm-k64-armcc
error: could not install target frdm-k64-armcc at * for frdm-k64-armcc
error: frdm-k64-armcc does not exist in the targets registry. Check that the name is correct, and that it has been published.
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/tls-client$

**Comment by mpg** [comment]
As the yotta error on line 5-6 says, frdm-k64-armcc is not the correct name for the target. The correct name is frdm-k64f-armcc (with an f).
