### ISSUE TITLE
Implementing mbedtls on STM32 with an external TCP/IP stack on SIM900 GSM module

### ISSUE THREAD

**Issue by kaizoku-619** [ARMmbed/mbedtls#2486]
### Description
- Type: Question
- Priority: Major | Minor

---------------------------------------------------------------

**OS**  
FreeRTOS on STM32L4A6 + SIM900 GSM module

-----------------------------------------------------------------

## Question
I'm working on implementing TLS with mbedtls on STM32L4A6 MCU and using SIM900 GSM module with its integrated TCP/IP stack. 
The STM MCU is communicating with the GSM module with AT commands sent and received through UART.
if I understand correctly the TLS implementation needs 2 things to function: 
- a TRNG (Hardware Random Number Generator) used inside mbedtls_hardware_poll() function (This STM MCU have a TRNG so that's not a problem).
- a networking interface; to use it we must override mbedtls_net_xxxx IO functions and pass them to mbedtls_ssl_set_bio() function.
- Now these IO functions by default are using a BSD style socket API which is not available on the MCU because I'm going to use the GSM module TCP/IP stack with AT commands.
**So my question is the following:**
Can I just go to an IO function like mbedtls_net_send() (ofc with its parameters) and inside it just put something like uart_send(TCP_SEND_AT_COMMAND) ?

**Comment by RonEld** [comment]
Hi @kaizoku-619 Thank you for your question and for your interest in Mbed TLS!

The short answer to your question is , yes, you hsould set your own bio callback functions through `mbedtls_ssl_set_bio()`, and disabling `MBEDTLS_NET_C` in your configuration.

The long answer is that you can probably also use the hw acceleration engine, if exists.

I suggest you read the following articles for more infomration:
* https://tls.mbed.org/kb/how-to/how-do-i-port-mbed-tls-to-a-new-environment-OS
* https://tls.mbed.org/kb/generic/abstraction-layers
* https://tls.mbed.org/kb/development/hw_acc_guidelines

You can also look at implementation for the crypto drivers from ST to their STM32L4 boards, on Mbed OS, in https://github.com/ARMmbed/mbed-os/tree/master/features/mbedtls/targets/TARGET_STM and https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/trng_api.c which may be similar to what is use d in your board.

**Comment by kaizoku-619** [comment]
Hi @RonEld Thank you for your answer, I have another question about the IO functions: for the sending function there is no problem but for the receiving function I don't really know how to implement it: does it need to be asynchronous meaning should it be woke up by a UART interruption or I need to keep polling the UART when I need to read received data?

**Comment by RonEld** [comment]
Hi @kaizoku-619 
You should implement it according to your platform.
You can implement it either asynchronous, which in this case it should be similar (but not same) to non blocking socket implementation, see call to [net_would_block](https://github.com/ARMmbed/mbedtls/blob/development/library/net_sockets.c#L553), or keep polling the UART, in which case, it would be like a blocking socket.
I believe it is dependent on how long you can block the connection without triggering the watchdog.

**Comment by kaizoku-619** [comment]
Thank you for your answer @RonEld

**Comment by kaizoku-619** [comment]
Hello again,
I have a question about the mbedtls_net_send() and mbedtls_net_receive() IO functions. In order to replace them with my own UART functions I need to know what do they expect as input and output, meaning what data is expected from them.
for example for mbedtls_net_send() what is expected to be inside the transmitting buffer: just app data or app data + headers and other stuff? also for the mbedtls_net_receive() what is expected to be in the recieving buffer? I'm asking these questions because I am reading and writing data on GSM module via UART. here is an example of the communication between MCU and GSM module:

NOTE: The symbol => indicates the command you need to enter, <= indicates the response received from the SIM900.

=>AT+CIPSTART="TCP","www.google.com","80"   // open TCP socket

<= CONNECT OK    // The TCP connection has been established successfully 

=>AT+CIPSEND /**Request initiation of data sending (the request)**/

<= > /**The response should be the string “>” to indicate, type your data to send**/

> GET  HTTP/1.1
Host: mysite.com
Connection: keep-alive
CTRL-Z

<= SEND OK

<= HTTP/1.1
Content-Type: text/html; charset=UTF-8
Content-Length: 925
Date: Mon, 04 Feb 2013 18:03:05 GMT

=>AT+CIPSHUT /**Request shutting down of the current connections**/

<=SHUT OK /**Indicates shutdown successful**/

**Comment by RonEld** [comment]
@kaizoku-619 The data that is being transmitted \ received is all the data the is needed in the TLS negotitation . It includes both the handshake message and the TLS headers. And after negotiation, the appdata and header.
However, your question is not clear to me. IIUC, the UART is the transport layer that you are using, and the data that it transmits should be opaque to it. It only needs to add its headers to the packets that are being sent.

**Comment by kaizoku-619** [comment]
By <<The data that is being transmitted \ received>> did you mean in my case:

**transmitted:**
> GET  HTTP/1.1
Host: mysite.com
Connection: keep-alive
CTRL-Z

**received:**
HTTP/1.1
Content-Type: text/html; charset=UTF-8
Content-Length: 925
Date: Mon, 04 Feb 2013 18:03:05 GMT

**Comment by RonEld** [comment]
Not exactly.
The data that you are showing is the application data that is sent \ received *after* the TLS succesful handshake. ( It will also be encrypted)
This is the data that you give as input for `mbedtls_ssl_write()` and given as output for `mbedtls_ssl_read()`.
However, the TLS stack ( Mbede TLS in this case) adds the TLS appdata header for the messages. So, in the callback itself, you will have the data *and* the TLS appdata header. This should be opaque to the transport layer though.

During handshake, the data will include the TLS handshake messages and headers.

**Comment by RonEld** [comment]
We believe this question has been addressed and answered, therefore closing.
If you think there are still open issues, please reopen, or create a new ticket.

**Comment by Amalghaezel** [comment]
Hello, I have to work with STM32 and mbedtls in a very important project but I am new to this field, so my problem is how to encrypt data transmission from WBAN to STM32 with mbedtls, I want help and thanks in advance.
