### ISSUE TITLE
Benchmark Example Does not compile with ArmCC

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#249]
"/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp", line 678: Error:  #135: class "mbedtls_ecp_curve_info" has no member "size"
              TIME_PUBLIC( title, "sign",
              ^
"/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp", line 692: Error:  #135: class "mbedtls_ecp_curve_info" has no member "size"
                  mbedtls_ecdsa_write_signature( &ecdsa, MBEDTLS_MD_SHA256, buf, curve_info->size,
                                                                                             ^
"/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp", line 701: Error:  #135: class "mbedtls_ecp_curve_info" has no member "size"
              TIME_PUBLIC( title, "verify",
              ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp: 0 warnings, 3 errors
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

**Comment by mpg** [comment]
see #247
