### ISSUE TITLE
Benchmark Example Does not compile with GCC

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#250]
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp: In function 'int main(int, char**)':
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp:679:102: error: 'const struct mbedtls_ecp_curve_info' has no member named 'size'
                     ret = mbedtls_ecdsa_write_signature( &ecdsa, MBEDTLS_MD_SHA256, buf, curve_info->size,
                                                                                                      ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp:173:5: note: in definition of macro 'TIME_PUBLIC'
     CODE; \
     ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp:692:92: error: 'const struct mbedtls_ecp_curve_info' has no member named 'size'
                 mbedtls_ecdsa_write_signature( &ecdsa, MBEDTLS_MD_SHA256, buf, curve_info->size,
                                                                                            ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp:702:82: error: 'const struct mbedtls_ecp_curve_info' has no member named 'size'
                     ret = mbedtls_ecdsa_read_signature( &ecdsa, buf, curve_info->size,
                                                                                  ^
/home/hasnain/Repos/OOB_Repo/mbedtls-examples/benchmark/source/main.cpp:173:5: note: in definition of macro 'TIME_PUBLIC'
     CODE; \
     ^
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

**Comment by mpg** [comment]
see #247
