### ISSUE TITLE
Weird result code from mbedtls_pk_parse_subpubkey()

### ISSUE THREAD

**Issue by jonasn-ge** [ARMmbed/mbedtls#2512]
There should be a plus sign when constructing the result code from MBEDTLS_ERR_PK_INVALID_PUBKEY + MBEDTLS_ERR_ASN1_LENGTH_MISMATCH at the end of mbedtls_pk_parse_subpubkey().

https://github.com/ARMmbed/mbedtls/blob/9c99dc862cd5cf9cdc62cbfcd200063c83295397/library/pkparse.c#L670

**Comment by RonEld** [comment]
Hi @jonasn-ge 
Thank you for reporting this issue!

You are correct that this is a bug, but this is a style bug, that doesn't conform with all other error codes in the source. *However*, in matter of functionality, there isn't any difference if there is or isn't a plus sign. Note that the error codes have negative values, so having a phrase ` -A-B` is equal to `-A +(-B)`.

**Comment by jonasn-ge** [comment]
@RonEld Yes, agreed, the code still works and does what it's supposed to do.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2806
