### ISSUE TITLE
Error parsing ca certificate with RSA 16384b key

### ISSUE THREAD

**Issue by brainode** [ARMmbed/mbedtls#2515]
### Description
- Type: Bug 
- Priority: Major

## Bug

**OS**  
linux?

Hello! I've a bug with OpenVPN Connect 3.0.5(1816) on Android and iOS OpenVPN 3.0.2(894) versions, when i try to use .ovpn profile with 16384bit key RSA and in log says:
`
08:15:35.630 -- ----- OpenVPN Start -----

08:15:35.631 -- EVENT: CORE_THREAD_ACTIVE

08:15:35.633 -- Frame=512/2048/512 mssfix-ctrl=1250

08:15:35.654 -- EVENT: CORE_THREAD_ERROR info='mbed TLS: error parsing ca
certificate : PK - The pubkey tag or value is invalid (only RSA and EC are
supported)'

08:15:35.657 -- EVENT: CORE_THREAD_INACTIVE

08:15:35.657 -- Tunnel bytes per CPU second: 0

08:15:35.658 -- ----- OpenVPN Stop -----
`
I've openned the [ticket](https://community.openvpn.net/openvpn/ticket/1165) , but reporter said that problem(limitation) with mbed TLS that they used. As i see in log, it also error in this module.

**Comment by RonEld** [comment]
@brainode Thank you for your information!

I see you are using 16Kb RSA key size.
Is your value of `MBEDTLS_MPI_MAX_SIZE` modified in your configuration? If not, by default it is set to 1024 bytes, which fits 8Kb RSA key size.
Have you tried configuring Mbed TLS with `MBEDTLS_MPI_MAX_SIZE` value of 2048?

**Comment by brainode** [comment]
@RonEld Hi! 
Is this configuration used while build?
I just use ready app, and i think you are right, becouse i have another ovpn profile with 8Kb RSA key,and it's work perfect!
I'll search for this configuration and value,thx for fast reply!

**Comment by RonEld** [comment]
@brainode 
>Is this configuration used while build?

Yes, it's a build time configuration, defined in the Mbed TLS configuration file
You can see more information on configuring Mbed TLS [here](https://tls.mbed.org/kb/compiling-and-building/how-do-i-configure-mbedtls)

**Comment by brainode** [comment]
I think I can close this issue. Thanks for helping!
