### ISSUE TITLE
Broken build dependencies with cmake and USE_CRYPTO_SUBMODULE

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#2517]
### Description
- Type: Bug
- Priority: Major

## Bug

When using the crypto submodule and building with cmake, the dependency analysis does not detect the correct headers. In particular, changing `crypto.h` inside the crypto submodule causes some files to be rebuilt (even though it is not actually used) while changing some other header files do not cause a rebuilt (even though they are not used). See https://github.com/ARMmbed/mbedtls/pull/2509

Example:
```
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Debug -D USE_CRYPTO_SUBMODULE=1 ..
make
touch ../crypto/include/mbedtls/aes.h
make
```
Desired: `aes.c.o` is rebuilt  
Actual: `aes.c.o` is not rebuilt  

`crypto/library/CMakeFiles/mbedcrypto.dir/depend.make` shows that some dependencies are on `../crypto/include/mbedtls/*.h` while others are on `../include/mbedtls/*.h` and I don't see a pattern.

**Comment by Patater** [comment]
As currently engineered, touching `../include/mbedtls/aes.h` should cause the rebuild, and it does.

```
$ touch ../include/mbedtls/aes.h
$ make
Scanning dependencies of target mbedcrypto
[  1%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/aes.c.o
[  1%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/aesni.c.o
[  1%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/cipher_wrap.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/ctr_drbg.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/error.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/gcm.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/padlock.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/pem.c.o
[  2%] Building C object crypto/library/CMakeFiles/mbedcrypto.dir/psa_crypto.c.o
[  2%] Linking C static library libmbedcrypto.a
[ 17%] Built target mbedcrypto
...
```

When aes.h is removed from the TLS repo, touching `../crypto/include/mbedtls/aes.h` will cause a rebuild.

The confusing issue to me is that touching `touch ../crypto/include/mbedtls/config.h` causes anything to rebuild, as that file should be unused (and only the TLS copy should be used). I'm not sure why aes.h and config.h exhibit different behavior.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2810

**Comment by AndrzejKurek** [comment]
Tested on commit bdcca1407656c4e2a9cd62b91b5586d4125126d8, touching `../crypto/include/mbedtls/aes.h` causes a rebuild, and touching `../crypto/include/mbedtls/config.h` does not cause a rebuild. Touching `../include/mbedtls/config.h` causes a global rebuild. 
Working as intended, @gilles-peskine-arm - can this issue be closed?

**Comment by gilles-peskine-arm** [comment]
I think we fixed this either when we made `USE_CRYPTO_SUBMODULE` mandatory or more likely when we removed crypto headers from mbedtls. Either way, this is fixed now.
