### ISSUE TITLE
test sign but not found right file

### ISSUE THREAD

**Issue by Txiaozhe** [ARMmbed/mbedtls#2518]
When I use this code to test sign by `mbedtls` lib., I got the err:
```shell
buf size: 1, return: -8576
version: 0
```
 -8576(-2180) code means in [mbedtls](https://tls.mbed.org/api/group__x509__module.html#ga45b8366804b7e2cbf3e25011f054802c)
```
The CRT/CRL/CSR format is invalid, e.g.
different type expected.
```

my source code:
```c
#include <stdio.h>
#include <mbedtls/x509_crl.h>
#include "mbedtls/platform.h"

int main()
{
  unsigned char buf = "-----BEGIN X509 CRL-----\nMIIBqzCBlDANBgkqhkiG9w0BAQIFADA7MQswCQYDVQQGEwJOTDERMA8GA1UEChMI\nUG9sYXJTU0wxGTAXBgNVBAMTEFBvbGFyU1NMIFRlc3QgQ0EXDTA5MDcxOTE5NTYz\nN1oXDTA5MDkxNzE5NTYzN1owKDASAgEBFw0wOTAyMDkyMTEyMzZaMBICAQMXDTA5\nMDIwOTIxMTIzNlowDQYJKoZIhvcNAQECBQADggEBAF8F5y82zgtxcwQ4aFvrkanT\nygyd5+RW/Y//vpck44V+CYx1d1r+QkauaXel9qUKBPsg2dUwQ+jwV/m+Sp2MHaX5\nNfW7XUb7Ji4yhwgh9/9vFPqqnKBf9esLJuJoQ4mLhcGB5J1yCcavLrynvB4PJEnG\ngraTbbyizelXBmk3ApvNYxczJZxt7EzpVbrFaev7myGmOffdDkIMc2WDpDkyLTlU\nkITjB7fMJhD/dgNskKZ4fgkKKKPCMJrJPO67Wzwqx/6vsrZcACB9X+143WZr4GVO\nFw2SaMnqfVLlUEndoOpbLCU4ugcc82kQQF3TsovXJYW7XqoWl2u/ENCwShl9rl4=\n-----END X509 CRL-----";

  mbedtls_x509_crl crl;
  mbedtls_x509_crl_init(&crl);
  int err = mbedtls_x509_crl_parse(&crl, &buf, strlen(&buf));
  if (err != 0) {
    mbedtls_printf("buf size: %lu, return: %d\n", sizeof(buf), err);
    mbedtls_x509_crl_free( &crl );
  }

  printf("version: %d\n", (&crl)->version);
  mbedtls_x509_crl_free (&crl);
}
```

In its [demo program](https://github.com/ARMmbed/mbedtls/blob/development/programs/x509/cert_app.c), it will use a default ca file: cert.crt, but I not found it, how can I get a right ca file?

**Comment by RonEld** [comment]
Hi @Txiaozhe 
Thank you for your question and for your interest in Mbed TLS!
The crl you are using has the following information:
~~~
Certificate Revocation List (CRL):
        Version 1 (0x0)
    Signature Algorithm: md2WithRSAEncryption
        Issuer: /C=NL/O=PolarSSL/CN=PolarSSL Test CA
        Last Update: Jul 19 19:56:37 2009 GMT
        Next Update: Sep 17 19:56:37 2009 GMT
Revoked Certificates:
    Serial Number: 01
        Revocation Date: Feb  9 21:12:36 2009 GMT
    Serial Number: 03
        Revocation Date: Feb  9 21:12:36 2009 GMT
    Signature Algorithm: md2WithRSAEncryption
         5f:05:e7:2f:36:ce:0b:71:73:04:38:68:5b:eb:91:a9:d3:ca:
         0c:9d:e7:e4:56:fd:8f:ff:be:97:24:e3:85:7e:09:8c:75:77:
         5a:fe:42:46:ae:69:77:a5:f6:a5:0a:04:fb:20:d9:d5:30:43:
         e8:f0:57:f9:be:4a:9d:8c:1d:a5:f9:35:f5:bb:5d:46:fb:26:
         2e:32:87:08:21:f7:ff:6f:14:fa:aa:9c:a0:5f:f5:eb:0b:26:
         e2:68:43:89:8b:85:c1:81:e4:9d:72:09:c6:af:2e:bc:a7:bc:
         1e:0f:24:49:c6:82:b6:93:6d:bc:a2:cd:e9:57:06:69:37:02:
         9b:cd:63:17:33:25:9c:6d:ec:4c:e9:55:ba:c5:69:eb:fb:9b:
         21:a6:39:f7:dd:0e:42:0c:73:65:83:a4:39:32:2d:39:54:90:
         84:e3:07:b7:cc:26:10:ff:76:03:6c:90:a6:78:7e:09:0a:28:
         a3:c2:30:9a:c9:3c:ee:bb:5b:3c:2a:c7:fe:af:b2:b6:5c:00:
         20:7d:5f:ed:78:dd:66:6b:e0:65:4e:17:0d:92:68:c9:ea:7d:
         52:e5:50:49:dd:a0:ea:5b:2c:25:38:ba:07:1c:f3:69:10:40:
         5d:d3:b2:8b:d7:25:85:bb:5e:aa:16:97:6b:bf:10:d0:b0:4a:
         19:7d:ae:5e
~~~
As you can see there are two issues that I spot:
1. It is hashed with md2, which is probably not defined in your configuration, as it is considered un secure. Since it is not defined, the crl fails to parse.
2. The crl has expired on Sep 17 19:56:37 2009 GMT , so even if you defined `MBEDTLS_MD2_C`, you will get a failiure due to expiration.
Regards

**Comment by Txiaozhe** [comment]
Thanks for your answer and attention, and I need to implement a function about Sign and Verify now, for example, I have a source word and a private key, they will be signed, and I can choose one encryption algorithm such sha256, finally, a signature will returned(this is pseudo code):
```
string signature = Sign(private_key, source_word, sha256);
```

when verify it, I will use this source word, signature, encryption algorithm and a public key, finally, the verification results (true or false) will returned:
```
boolean results = Verify(public_key, source_word, sha256, signature); // true or false
```
I have use `mbedtls_x509_crt` and its methods to do it but I found I can't choose the encryption algorithm and no expected results were obtained.
Can you give some advices?
Thanks!

**Comment by RonEld** [comment]
Note that sha256 is not an encryption algorithm, but a digest algorithm.
The signature is done on the digest of your message.
`mbedtls_x509_crt` is used to parse x509 certificates, not for signature generation.
If you want to sign and verify, you should be using the `mbedtls_pk` module , or the underlying RSA \ ECDSa algorithms.

**Comment by Txiaozhe** [comment]
Thanks!
Could you please give me some sign/verify demo?
Are `programs/pkey/pk_sign.c` and `programs/pkey/pk_verify.c` an example of it?

**Comment by RonEld** [comment]
You can find [here](https://github.com/ARMmbed/mbedtls/tree/development/programs/pkey) Mbed TLS example programs for the public key cryptography modules.

**Comment by Txiaozhe** [comment]
Thanks for your attention, I will try it :)

**Comment by RonEld** [comment]
@Txiaozhe 
>Are programs/pkey/pk_sign.c and programs/pkey/pk_verify.c an example of it?

Yes. There are also `rsa_sign` and `rsa_verify` and `ecdsa` applications

**Comment by Txiaozhe** [comment]
Thanks! :)

**Comment by RonEld** [comment]
Closing, as the quewstion was answered. For any follow-up, please reopen, or create a new question if different topic.

**Comment by Txiaozhe** [comment]
> Closing, as the quewstion was answered. For any follow-up, please reopen, or create a new question if different topic.

Thanks!
