### ISSUE TITLE
Hashing Example does not get compiled with ArmCC in Ubuntu

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#252]
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/hashing$ yt clean
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/hashing$ yt target frdm-k64-armcc
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/hashing$ yt build
info: get versions for frdm-k64-armcc
error: could not install target frdm-k64-armcc at * for frdm-k64-armcc
error: frdm-k64-armcc does not exist in the targets registry. Check that the name is correct, and that it has been published.
hasnain@ubuntu:~/Repos/OOB_Repo/mbedtls-examples/hashing$

**Comment by mpg** [comment]
see #246
