### ISSUE TITLE
error in mbedtls_rsa_rsaes_pkcs1_v15_encrypt

### ISSUE THREAD

**Issue by Elvisca** [ARMmbed/mbedtls#2529]
I use mbedtls_rsa_rsaes_pkcs1_v15_encrypt with the good param but I get MBEDTLS_ERR_RSA_VERIFY_FAILED                     -0x4380 error

- Type: Question

## Question
I use  mbedtls_rsa_rsaes_pkcs1_v15_encrypt with private key

first that I use gen_ken program generae a private key in 2048bits here is the key
~~~
const char loadon_private_key[] ={
	"-----BEGIN RSA PRIVATE KEY-----\n\
MIIEowIBAAKCAQEAyR4bKXqho0/8mnBBEd86jKpNCnieQ29wAKHQy/+NLIiO7nTt\
JlXyJcS+j0PE6ppAqCF8mdCi8L1AEdEKaKphHFYrq0z9/a+sryt9VYqpRLi2L+kl\
j/QULFDCgVREuPNTJUJbJC14XxVMbNfCUWvIKOGysnc1R4HasTUIA30tnC/yDMuq\
/xY8Fi1T3jlL4ffW9rcRYcJYbN9TPvMR0+ta4JAyFhPKa6BTxISQaE2QhopRACfT\
zgFpfjHCF825UaN1Fevzt/iZW5vTLjnPWBbPdBgbgvG6A4d5h6pYUv5e66XJwZZk\
dQXTvhT5MD2naU1N0HT7zCJPOHStZSYjK2vZdQIDAQABAoIBAAZB2Ih+1z6Ug4Bu\
k6exsUmlFsaHoCzq76olXrCqH8NN8Fx86M/zhpgkOeWNLzg5Wl+gwxaqBhfFW5Py\
VAeTnXfbOnqW56QX7iB5EuoxaTjJImn1MAT9jA8g6BxL+eNjNqgHG3zRqVgT+o+8\
WsBbwRt8ginJSbAS2zH+O2SYZW3hhdONH2yYEJmN1nt1eXLhZlu6qm6Xli/KwZOK\
vDEbu6hwYsMEeOvvm+tKhF4eHnOgOkp4RAkjPWZVH+WJPJNeiuQ1N84RhfB5pJc8\
r6PkmInN7DMG4hpUOhZ0QYcGNt0MywbJQTgbl1Rlt1XyjzQhcoEJuCllVgBQpzCj\
Xr7l69UCgYEA9zWsG8UNHivuGz21V8sADnqTqt11yd8/718mO9/c/QfSRqcovZZJ\
TOW0hGG1nU62tU2AU20VTQ6kvkLqvaKrw2RxxMuNABWwnH2ac3BSA0aygdC4TTmj\
D6hnGr3EFmpgbsJVjhLBVtF/Go3Nla8MZRGqapmJ9fhV85Wx2ayfbAcCgYEA0ETc\
pLtK4bKyuWflpPKTsDy7TD59bJtQn3lPkYwb1Hiwdd3APqBKXUMzBkvWRx5hPbKV\
nBMr0uqGlUNa/x9yc3Nw5A8ICQOuD8ixlFS3z8Sg/GLdgToYFqvebMFUKTWbOSak\
JfAqMVftKWFKIja4GodE9H6d8tgUvmtRtlCjJ6MCgYAIARrjg0vbcDyzcRoQD6ie\
z2U8oRMRSEM/susAAU2ce8ZZN0xgZx9UeBOSPb+tqkDMOggvq1aHOjQnXO9Q2JWL\
LBNq9dRI7mrbhk2b80UUihN5lJKDHZykAyXjfcV9nFAnBe/TO9Q6xWnCKFlBwXs7\
QoksDnCjIDlYO76Yd7hpvQKBgADhWaFknUNo8vJvqvvQfqlPCGehF/yeh2+1Ho35\
7qAuRmipIEfje4z7XLrZFTXFvhl5qMI5HoVMsnbtCvRrGJu+UCrWmW0YU+MDMST0\
WraJGTkX3eHO8g0eetkw0/88l8RdEnKKmlMNERaMr7iHTK3oBnWWF2rQWP4ZDAZe\
PuJLAoGBAJIxy4AuIhDkr+rQzk23zdZl88rzArHeRms0cjLWuZCyfV7doOxo146G\
YUNvFopx7Iw9cpdLV5xu15XfOjQbVkXAB3jCY6l0s91GDnTOl9LwcdBUNeEdzcjx\
evo5QoxGnIJ+Tu6tLEf0jCKJ7q1gFV3S5Cr7gLQ7pzkUK9z6pykl\n\
-----END RSA PRIVATE KEY-----"};
~~~

and I load the key form memory 
then I'd encyrpt my data ,before that I check the public key and private key they are all successfuly 

~~~
mbedtls_pk_parse_key(&pk,(const unsigned char *)opt->key, (size_t)opt->keylen,(const unsigned char *)opt->pwd, (size_t)opt->pwd )；

static int loadon_rsa_private_encrypt( void *ctx,
							 const unsigned char *input, size_t ilen,
							 unsigned char *output, size_t *olen, size_t osize,
							int (*f_rng)(void *, unsigned char *, size_t), void *p_rng )
{
    mbedtls_rsa_context * rsa = (mbedtls_rsa_context *) ctx;
    *olen = mbedtls_rsa_get_len( rsa );

	if (mbedtls_rsa_check_pubkey( rsa ) != 0) {
		return( MBEDTLS_ERR_RSA_KEY_CHECK_FAILED );
	}

	if ((mbedtls_rsa_check_privkey(rsa)) != 0) {
		return( MBEDTLS_ERR_RSA_KEY_CHECK_FAILED );
	}
    if( *olen > osize )
        return( MBEDTLS_ERR_RSA_OUTPUT_TOO_LARGE );
    return( mbedtls_rsa_pkcs1_encrypt( rsa, f_rng, p_rng, MBEDTLS_RSA_PRIVATE,
                                       ilen, input, output ) );
}

~~~

but when it run into the mbedtls_rsa_private function   it always failed   at  mbedtls_mpi_cmp_mpi( &C, &I ) 

/*
 * Do an RSA private key operation
 */
int mbedtls_rsa_private( mbedtls_rsa_context *ctx,
                 int (*f_rng)(void *, unsigned char *, size_t),
                 void *p_rng,
                 const unsigned char *input,
                 unsigned char *output )

 /* Verify the result to prevent glitching attacks. */
    MBEDTLS_MPI_CHK( mbedtls_mpi_exp_mod( &C, &T, &ctx->E,
                                          &ctx->N, &ctx->RN ) );
    if( mbedtls_mpi_cmp_mpi( &C, &I ) != 0 )
    {
        ret = MBEDTLS_ERR_RSA_VERIFY_FAILED;
        goto cleanup;
    }

 I try many ways but sill failed , could anyone give me some suggestion， I appreciate ！

English is not my mother language，and this is my first create issue，so if there is any suggestion，please tell me，thanks！

**Comment by RonEld** [comment]
@Elvisca 
Thank you for your question.
I am having trouble understanding your flow.

* Are you trying to encrypt using your test private key, and then decrypt it?
* Are you using your private key for both encryption and decryption?
* Are you using your private key for encryption and then trying to verify it using your private key?

Note that in usual case, when you do an RSA encryption, you should be using the *public key* as only the key pair owner should be able to decrypt it.

**Comment by Elvisca** [comment]
@RonEld 
Thank you for your reply.
My description may not  clearly. 

- About your first and second point I am trying to use private key to encrypt and use public key to decrypt.

- The third ， I am just want test encrypt data ，when I call    mbedtls_rsa_private    function  there is a  function in it , will check  if  the result  is correct， it's always check  failed at there.

/* Verify the result to prevent glitching attacks. */
MBEDTLS_MPI_CHK( mbedtls_mpi_exp_mod( &C, &T, &ctx->E,
&ctx->N, &ctx->RN ) );
if( mbedtls_mpi_cmp_mpi( &C, &I ) != 0 )
{
ret = MBEDTLS_ERR_RSA_VERIFY_FAILED;
goto cleanup;
}

**Comment by RonEld** [comment]
Hi @Elvisca 
I have sopme questions from your code:
1. Have you checked return code of `mbedtls_pk_parse_key()`? I tried your key, and for me parsing failed
2. What is the value of `opt->keylen`? Does it include the additional null character, as mentioned in the [documentation](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/pk.h#L595)
3. What is the context type that is sent as parameter to your `loadon_rsa_private_encrypt()` function? Is it `pk` (`mbedtls_pk_context`)  or type `mbedtls_rsa_context ` ?

**Comment by RonEld** [comment]
I had a copy\paste error when copied the key, now parsing succeeds.

After fixing the copy\paste issue, I manage to successfully encrypt using the private key, using the following code:
~~~
	mbedtls_pk_init(&pk);
    mbedtls_ctr_drbg_init( &ctr_drbg );
    mbedtls_entropy_init( &entropy );

    ret = mbedtls_ctr_drbg_seed( &ctr_drbg, mbedtls_entropy_func,
                                 &entropy, (const unsigned char *) pers,
                                 strlen( pers ) );
    if( ret != 0 )
    {
        goto exit;
    }

	if( ( ret = mbedtls_pk_parse_key( &pk, loadon_private_key, strlen(loadon_private_key) + 1, NULL, 0 ) ) != 0 )
	{
		goto exit;
	}
	rsa = mbedtls_pk_rsa(pk);
	if (mbedtls_rsa_check_pubkey(rsa) != 0) {
		return(MBEDTLS_ERR_RSA_KEY_CHECK_FAILED);
	}

	if ((mbedtls_rsa_check_privkey(rsa)) != 0) {
		return(MBEDTLS_ERR_RSA_KEY_CHECK_FAILED);
	}
    /*
     * Calculate the RSA encryption of the hash.
     */
    ret = mbedtls_rsa_pkcs1_encrypt( rsa, mbedtls_ctr_drbg_random,
                                     &ctr_drbg, MBEDTLS_RSA_PRIVATE,
                                     strlen( argv[1] ), input, buf );
    if( ret != 0 )
    {
        goto exit;
    }

exit:
    mbedtls_mpi_free( &N ); mbedtls_mpi_free( &E );
    mbedtls_ctr_drbg_free( &ctr_drbg );
    mbedtls_entropy_free( &entropy );
    mbedtls_pk_free( &pk );
~~~

Please check your flow, parameters, according to my previous questions

**Comment by Elvisca** [comment]
@RonEld 
Thank you very much for your reply.
1. I have tried mbedtls_pk_parse_key(), before you call the function , must define MBEDTLS_MPI_MAX_SIZE more then 256,  
#define MBEDTLS_MPI_MAX_SIZE            512 /**< Maximum number of bytes for usable MPIs. */
2.  opt is struct ,   opt->keylen  is the private key  I put it in a struct ,and the keylen is the private key length, the opt->pwd is NULL , 
3.the context type  sent to loadon_rsa_private_encrypt() is   mbedtls_pk_context pk;

**Comment by RonEld** [comment]
@Elvisca
>and the keylen is the private key length, 

Does it include the `+ 1` for the terminating null character?

>3.the context type sent to loadon_rsa_private_encrypt() is mbedtls_pk_context pk

This means that you *shouldn't* cast it to `mbedtls_rsa_context *`

The proper way to get the `mbedtls_rsa_context member of pk, is: `rsa = mbedtls_pk_rsa(pk);`
`

**Comment by Elvisca** [comment]
@RonEld 
Sorry, I just got it wrong.The context type sent to loadon_rsa_private_encrypt() is  pk.pk_ctx .
I will try code later , thank you  so much!

**Comment by RonEld** [comment]
No problem, please remember to generate a new private key and keep it a secret, once your code works

**Comment by Elvisca** [comment]
hi @RonEld 
I run the program was still failed.
I  compared the code of yours and mine，there is no different，except I run the code on Development board，used the random creat function that was write by myself, would that be the reason that cause program always encrypt failed? 

I add random creat function to the entropy struct , the loadon_random_entropy_creat  is a random creat funtion that I wrote .
	if( ( ret = mbedtls_entropy_add_source( &entropy, &loadon_random_entropy_creat,
											NULL, LOADON_RANDOM_THRESHOLD,
											MBEDTLS_ENTROPY_SOURCE_STRONG ) ) != 0 ) {
		goto exit;
	}

**Comment by Elvisca** [comment]
@RonEld 
I am confused.Is that failed beacuse of the random creat function, or there is others define that I need to do?

**Comment by Elvisca** [comment]
@RonEld 
I found a very strange phenomenon, I put the program looped, the first few times  call mbedtls_rsa_check_privkey function check the private key  will fail， after three or four times it will check success

**Comment by Elvisca** [comment]
@RonEld 
Finaly I use the mbedtls with version 1.5.0， with same code and it work，include generate private and public key ， encrypt and decrypt ，but I still don't understand where is the cause that use the higher version it would failed.

**Comment by RonEld** [comment]
@Elvisca If you  *upgraded* to version 1.5.0, it means you are working on an Mbed TLS version that is unsupported anymore. Please upgrade to one of our latest LTS versions, for further support, as there have been many bug fixes, and security improvements since the old version you are working on.

**Comment by Elvisca** [comment]
@RonEld 
Thanks for your reminder，I just use for test，I will choose a high version if I need to use in  normal working. I will closing the issue right now. Thank you again.
