### ISSUE TITLE
Selftest example does not gget compiled using ArmCC in Ubuntu

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#254]
rning: L6304W: Duplicate input file ym/mbed-core/source/mbed-core.ar ignored.
Warning: L6304W: Duplicate input file ym/mbed-hal/yotta_dummy_lib_mbed_hal/mbed-hal.ar ignored.
Warning: L6304W: Duplicate input file ym/mbed-hal-freescale/yotta_dummy_lib_mbed_hal_freescale/mbed-hal-freescale.ar ignored.
Warning: L6304W: Duplicate input file ym/mbed-hal-ksdk-mcu/source/mbed-hal-ksdk-mcu.ar ignored.
Warning: L6304W: Duplicate input file ym/mbed-hal-k64f/source/mbed-hal-k64f.ar ignored.
Warning: L6304W: Duplicate input file ym/mbed-hal-frdm-k64f/source/mbed-hal-frdm-k64f.ar ignored.
Warning: L6304W: Duplicate input file ym/cmsis-core/yotta_dummy_lib_cmsis_core/cmsis-core.ar ignored.
Warning: L6304W: Duplicate input file ym/cmsis-core-freescale/yotta_dummy_lib_cmsis_core_freescale/cmsis-core-freescale.ar ignored.
Warning: L6304W: Duplicate input file ym/cmsis-core-k64f/source/cmsis-core-k64f.ar ignored.
Error: L6218E: Undefined symbol vtable for __cxxabiv1::__class_type_info (referred from retarget.cpp.o).
Error: L6218E: Undefined symbol operator delete (void*) (referred from retarget.cpp.o).
Error: L6218E: Undefined symbol __cxa_pure_virtual (referred from retarget.cpp.o).
Error: L6218E: Undefined symbol vtable for __cxxabiv1::__si_class_type_info (referred from FileSystemLike.cpp.o).
Error: L6218E: Undefined symbol operator new(unsigned) (referred from FileSystemLike.cpp.o).
Finished: 0 information, 9 warning and 5 error messages.
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

**Comment by mpg** [comment]
see #247, I believe.
