### ISSUE TITLE
2.17.0 status?

### ISSUE THREAD

**Issue by pkolbus** [ARMmbed/mbedtls#2543]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
- Priority: Major

---------------------------------------------------------------
## Question

I noticed that 2.17.0 was tagged two weeks ago, but not released alongside 2.16.1 and 2.7.10. Were quality issues discovered, or is final testing of 2.17 just delayed? Or an oversight?

**Comment by RonEld** [comment]
Hi @pkolbus I apologize for the *very* late reply.
I was waiting for [this blog](https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3) to be posted, however I missed that it was already posted a while ago...

As menitoned in the blog:
>Until Mbed TLS 3.0 is released, only Long-Term Support (LTS) versions of Mbed TLS 2.x will be released. Feature releases will be targeting Mbed OS only.

This means that version 2.17.0 targeted Mbed OS, and not as a standalone release, and it was not an oversight.
You can, however, try to use it, but we can't guarantee that no big API change will occur until version 3.0 will be stabilized.

**Comment by pkolbus** [comment]
Thanks. I’ve read the blog post and it answers my questions.
