### ISSUE TITLE
TLS handshake is using TLSv1

### ISSUE THREAD

**Issue by nitinpadalia** [ARMmbed/mbedtls#2565]
Hi,
if some client has following configuration:
mbedtls_ssl_config_defaults(&session->conf,
                                     MBEDTLS_SSL_IS_CLIENT,
                                     MBEDTLS_SSL_TRANSPORT_STREAM,
                                     MBEDTLS_SSL_PRESET_DEFAULT);

then under which situations, client hello will be TLSv1? I believe it should use TLSv1.2 always. I am using a tools which uses mbedtls library. In some of my servers the tools does TLSv1 in client-hello due to which server is resetting connection. However same tools with same configs works fine in few other servers and uses TLSv1.2 in client-hello.

**Comment by RonEld** [comment]
Hi @nitinpadalia 
Thank you for your question!

The initial TLS version in the Client Hello, will be as configured through the `mbedtls_ssl_config_defaults()` function, and then optionally later through `mbedtls_ssl_conf_xxx_version()`.
However, if there is a renegotiation, the the version sent will be as the version accpeted by the server in the ServerHello message before the renegotiation, as you can see [here](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_cli.c#L834)

**Comment by nitinpadalia** [comment]
Thank! for explaining. I was able to find the issue.
