### ISSUE TITLE
C++ headers check in all.sh doesn't detect errors

### ISSUE THREAD

**Issue by k-stachowiak** [ARMmbed/mbedtls#2570]
Inside `all.sh` we run a test to see if a C++ build test program includes all the headers from the library. The following circumstances occur:

1) The test is performed inside a function `check_headers_in_cpp`
2) The last command in `check_headers_in_cpp` is `rm headers.txt` which leads to always returning `0` as the function result
3) we use `set -e` in the beginning of the `all.sh` script to exit on errors, with some exceptions (see point 5)).
4) `check_headers_in_cpp` is called using the `record_status` function
5) `record_status` runs its "command under test" inside an `if` test clause, which renders 3) ineffective

Points 2) and 5) lead to the `check_headers_in_cpp` error not being caught even though the `diff` call inside it correctly recognizes issues.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2833

**Comment by gilles-peskine-arm** [comment]
See #3057 for some thoughts on resolution.

Note that resolution includes both fixing `all.sh` not to ignore the test failure and fixing the actual underlying issue.
