### ISSUE TITLE
Do we really want to check for "TODO" in our code?

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbedtls#2587]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
All

**mbed TLS build:**  
development and LTS versions

**Expected behavior**   
It's sometimes useful to note when we want to do something in the future in our code comments. Yes, we should generally file an issue on GitHub for things we want to do, so we can remember to do them and track progress better, but checking for the "TODO" string seems the wrong way to go about this.

What value do we get by checking for "TODO"? Should the presence of "TODO" cause a hard failure in tests or just a warning? Should we also check for "XXX", "FIXME", and "To do"?

**Actual behavior**  
Our tests look for "TODO" strings and fail if any are present. This leads to developers  spelling "TODO" as "To do" or "FIXME" to bypass the check.

**Comment by gilles-peskine-arm** [comment]
For what it's worth, OpenSSL, GnuTLS, BearSSL and WolfSSL all have a double-digit number of `TODO` (the exact string) in their core code. So “TODO is unprofessional” doesn't apply in our space. Besides, FIXME is worse, and “to do” or “tonogrepdo” just makes it harder to find the thing afterwards.
