### ISSUE TITLE
mbedtls_ssl_handshake returned -0x2880

### ISSUE THREAD

**Issue by Rajkumar181** [ARMmbed/mbedtls#2590]
Hi Team,

  I am trying to add mbetls on my application. And i am getting some memory error. Please look once.

Hardware IC - STM32F429Zi  (https://www.st.com/en/microcontrollers-microprocessors/stm32f429zi.html)
Platform -  TrueStudio for STM32
Code Generator - STM32CubeMx

..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:3161: handshake message: msglen = 5021, type = 11, hslen = 5021
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:3846: <= read record
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:4180: => send alert message
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:4181: send alert level=2 message=80
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2764: => write record
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2910: output record: msgtype = 21, version = [3:3], msglen = 2
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2913: dumping 'output record sent to network' (7 bytes)
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2913: 0000:  15 03 03 00 02 02 50                             ......P
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2471: => flush output
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2490: message length: 7, out_left: 7
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2496: ssl->f_send() returned 7 (-0xfffffff9)
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2523: <= flush output
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2922: <= write record
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:4193: <= send alert message
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:4573:  mbedtls_x509_crt_parse_der() returned -10368 (-0x2880)
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:6764: <= handshake
 failed
  ! mbedtls_ssl_handshake returned -0x2880

Last error was: -10368 - X509 - Allocation of memory failed

..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:7542: => free
..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:7607: <= free

Thanks

**Comment by RonEld** [comment]
According to [this post](https://forums.mbed.com/t/mbedtls-ssl-handshake-failed/4877) you have resolved your issue, so I am closing this ticket.
If you think this issue was wrongfully closed, please reopen, with followup information.
