### ISSUE TITLE
Deprecate the HAVEGE module

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#2599]
### Description
- Type: Feature Request
- Priority: Major

I can't think of a solid use case for the HAVEGE module in Mbed TLS (or Mbed Crypto).

If you're running on a hosted platform like Linux or Windows, the kernel does a better job of collecting entropy than any process can do, and enabling an extra entropy source of hard-to-measure quality doesn't help. If you're running on a microcontroller where the operating system doesn't provide an entropy source, the processor is likely to have too few timing variations to provide any entropy.

We declare HAVEGE as a strong source. I agree with this assessment on a PC-like system running multiple processes and with multiple peripherals triggering interrupts, but on such a system, `mbedtls_platform_entropy_poll` gets the OS entropy which does a better job than HAVEGE (possibly including its own implementation of HAVEGE). On a microcontroller, on the other hand, this may give a false sense of security.

We should deprecate HAVEGE, then remove it.

**Comment by gilles-peskine-arm** [comment]
Mailing list discussion: https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000025.html

**Comment by chris-jones-arm** [comment]
HAVEGE has been removed from the library as part of Mbed TLS 3.0. See #4079 and #4089 for further details.
