### ISSUE TITLE
handshake succeeds on mbedtls server, fails on gnutls client with bad server cert.

### ISSUE THREAD

**Issue by dbaarda** [ARMmbed/mbedtls#2610]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux, debian buster/sid

**mbed TLS build:**  
$ dpkg -s libmbedtls-dev | grep Version:
Version: 2.16.0-1

**Peer device TLS stack and version**  
GnuTls in in ldapsearch provided by ldap-utils;

Version:  
$ dpkg -s ldap-utils | grep Version:
Version: 2.4.47+dfsg-3
$ dpkg -s libgnutls30 | grep Version:
Version: 3.6.6-2

The server is using a self-signed cert that is not trusted by the client. In this case the client is ldapsearch which is configured in /etc/ldap/ldap.conf using TLS_CACERT set to a file that does not include the self-signed cert.

**Expected behavior**   

When the client fails the handshake because of the untrusted server cert, the handshake should fail on the server.

**Actual behavior**  

The handshake fails on the client, but mbedtls_ssl_handshake() returns zero and succeeds on the server. This then results in the server failing the next mbedtls_ssl_read() with a status indicating "SSL - An invalid SSL record was received." when the ldapsearch client sends a followup unencrypted "unbind" ldap message before disconnecting.

On the server side I have the following simple debug output, where "handshake complete" is output when mbedtls_ssl_handshake() returns zero;
...
lightldapd: handshake_cb()
lightldapd: handshake complete
lightldapd: mbedtls_ssl_read: SSL - An invalid SSL record was received

On the client side I see the following debug output;
...
tls_read: want=32, got=32
  0000:  74 14 2a a3 4f 05 06 81  d5 e5 0b 9d 2d eb f6 5e   t.*.O.......-..^  
  0010:  e4 a7 3c 63 47 8b 80 c8  d2 b2 79 53 3a 95 47 a8   ..<cG.....yS:.G.  
TLS: peer cert untrusted or revoked (0x442)
TLS: can't connect: (unknown error code).
ldap_err2string
ldap_start_tls: Connect error (-11)
        additional info: (unknown error code)
ldap_free_connection 1 1
ldap_send_unbind
ber_flush2: 7 bytes to sd 3
  0000:  30 05 02 01 02 42 00                               0....B.           
ldap_write: want=7, written=7
  0000:  30 05 02 01 02 42 00                               0....B.           
ldap_free_connection: actually freed

**Steps to reproduce**  

I can send/share more info as required.

I'm not entirely sure if this is a bug in mbedtls, or more likely a bug in gnutls and/or ldapsearch. It looks to me like ldapsearch is completing the handshake and then deciding the cert is bad without any sort of tls notification to let mbedtls know about it. I'm not sure who to blame, or even if this is normal tls protocol handshake behavior. However I did a bit of a search and couldn't find any other reports of this so I figured it's worth filing a bug here so at least others know about it.

**Comment by RonEld** [comment]
@dbaarda Thank you for your information!
I don't consider this a bug, at least not in Mbed TLS. 
Does the client send a fatal alert to the server?
Since the server certificate is not trusted, then the client should fail the handshake. If the server does not know that client terminated connection, how does it know to terminate the tls session?
Could you share full logs of Mbed TLS? (you could start after the certificate message was sent )


However, is it possibkle that *after* tls session was terminated, the ldap still sends a non tls message to the server? This probably causes the tls server to read an invalid ssl message. The TLS stack should not get ldap message, as it doesn't know how to read them ( unless they are wncrypted \ wrapped with the TLS application data headers )

Maybe I am a bit off here, but if you are using an ldap client, should you use an ldap server? Do you have ldap support on your server?

**Comment by dbaarda** [comment]
I'm writing my own LDAP server using mbedtls for the TLS support. See

https://github.com/dbaarda/LightLdapd

I'm using the openldap ldapsearch tool as a client for debugging. The ldapsearch tool uses GnuTLS for its TLS client support.

The client's debugging does seem to indicate that it fails the handshake because it doesn't trust the server's cert. However, it also doesn't seem to show it sending anything to the server after the handshake failure message, and instead seems to assume that the TLS session was terminated and sends a non-tls ldap unbind message to terminate the ldap connection.

On the mbedtls server side the handshake appears to have succeeded, but as soon as the non-tls unbind message is received it sees it as an invalid ssl message.

So yes, it does kind of smell like either a GnuTLS bug in that it fails to indicate to the server that the handshake failed. Or perhaps it's something wrong in how the ldapsearch client uses GnuTLS?

Interestingly other types of invalid cert do correctly fail the handshake on the server side, like miss-matched hostnames or expired certs. So far I've only seen this strange failure mode when the client doesn't trust the self-signed cert.

**Comment by dbaarda** [comment]
Oh yeah, I'll see if I can figure out how to get mbedtls to give me full server-side logs... I think I need to add code to set the debug hook.

I've already got what appears to be pretty detailed client-side logs.

**Comment by RonEld** [comment]
@dbaarda Thanks for the information.
The client should send a fatal alert with `bad_certificate` although I couldn't find it explicitely in the standard.
How would the server know that the handshake failed on the client side otherwise?
The error is because the ldap message sent by the client is accepted first in the TLS stack, before your ldap layer handles it.

**Comment by dbaarda** [comment]
FTR, I was sure I saw examples of miss-matched hostnames or expired certs correctly failing the handshake, but I don't seem to be able to reproduce it now.

**Comment by dbaarda** [comment]
I think the cases where I saw the handshake fail on the mbedtls server were when the handshake failed early on the gnutls client side because of things like the key signature not matching, leaving the handshake incomplete on the server side. The client then proceeded to assume the handshake failed and sent the unencrypted ldap unbind request, which the mbedtls server couldn't understand and decided the handshake was broken.

In any case it appears that the GnuTLS client, or possibly ldapsearch's way of using GnuTLS, never sends any kind of alert to indicate the handshake has failed.

**Comment by RonEld** [comment]
We believe this issue is resolved, therefore closing.
If you think this was wrongfully closed, please reopen
