### ISSUE TITLE
Size limit is too small for x509 extension size(2KB) and x509 certificate size(4KB) in x509write_crt.c

### ISSUE THREAD

**Issue by soccerGB** [ARMmbed/mbedtls#2631]
### Description
- Type: Bug | Enhancement\Feature Request

The current low limit x509 extension size(2KB) and x509 certificate size(4KB) in x509write_crt.c is too small for our application, which requires embedding some attestation data (around 6 kb) for helping authenticating tls' connecting parties.  I found those two limitations were set by some local buffers in  mbedtls/mbedtls/library/x509write_crt.c

int mbedtls_x509write_crt_der(...)
{
    unsigned char tmp_buf[2048]; <--- extension limitation
...
}

int mbedtls_x509write_crt_pem(...)
{
..
  unsigned char output_buf[4096];  <--- certificate limitation
...
}

We found OpenSSL have no such limitation. I hate to move to Openssl because mbedtls is more well structured in many ways.

Currently, I have to adjust to 8k in both buffers in our local snapshot.
Is it possible to remove this limitation or include the limit in the master branch?

- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|

**mbed TLS build:**  
Version:  2.7.9
OS version: Ubuntu 18.04 
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   
No limit or higher limit (at least 8KB) x509 extension size and x509 certificate size

**Actual behavior**  

low size limit x509 extension size(2KB) and x509 certificate size(4KB)

**Steps to reproduce**  

Involved source code was mentioned in the issue description

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

mentioned in the issue description.

**Suggested enhancement**  

I can provide changes or PR.
-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by hanno-arm** [comment]
Hi @soccerGB,

thank you for your detailed report, I agree that we have an issue here. We should avoid the use of such large stack buffers altogether and instead work in-place, as for CSRs is done in #2118.

I have drafted a PR https://github.com/ARMmbed/mbedtls/pull/2632 to fix the issue - could you check if it works for you?

Kind regards, 
Hanno

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2844

**Comment by soccerGB** [comment]
@hanno-arm
I am sorry for the late response because of my vacation.
Thanks a lot for providing such a clever fix, way better than the dynamically allocated one that I have been using locally.

Your fix works well for my scenarios.

Looking forward to seeing this great fix in the upstream!

**Comment by soccerGB** [comment]
By the way, I forgot to mention the changes look good to me.

**Comment by hanno-arm** [comment]
Hi @soccerGB,

you're very welcome, and thanks again for your report.

Could you please leave a note in the PR stating how you'd like to be credited!

Kind regards,
Hanno

**Comment by hanno-arm** [comment]
Hi @soccerGB,

I saw that you already made use of the fix in PR #2632 in your [PR](https://github.com/microsoft/openenclave/pull/1761) on the OpenEnclave repository - while I'm happy to see that it solves your issue, please be aware that the PR hasn't received any review from the Mbed TLS team yet, so I'd advise that you either wait with using it or make sure a few critical eyes from your side check it. But that's of course entirely at your discretion.

Kind regards,
Hanno

**Comment by soccerGB** [comment]
@hanno-arm, thanks for the note.
I am curious on what criteria needs to be met (other than after being reviewed) before this fix could get into master branch.

**Comment by soccerGB** [comment]
It looks like mbedtls_x509write_csr_der has similar constraints that need similar fix.

**Comment by hanno-arm** [comment]
Hi @soccerGB,

yes that's right (see my initial comment), there's https://github.com/ARMmbed/mbedtls/pull/2118 open to fix it.

> I am curious on what criteria needs to be met (other than after being reviewed) before this fix could get into master branch.

It needs to be approved by two team members, plus pass CI and gatekeeper check, and @patater might be able to give an estimate when that might happen.

Kind regards,
Hanno
