### ISSUE TITLE
Parallel build of shared targets fails with crypto submodule usage turned on

### ISSUE THREAD

**Issue by AndrzejKurek** [ARMmbed/mbedtls#2634]
### Description
- Type: Bug 
- Priority: Minor

When building MbedTLS as a shared target with the crypto submodule being used, the build often fails due to an `No rule to make target '../crypto/library/libmbedcrypto.so'` error.
This is probably due to incomplete or incorrect dependency lists in the makefiles.
As a workaround, parallelization can be disabled in scripts/tests, and that's what was done in https://github.com/ARMmbed/mbedtls/pull/2403.

Probably related to https://github.com/ARMmbed/mbedtls/issues/2517.

**OS**  
Linux & Windows

**Steps to reproduce**  
Use code from the mentioned PR or enable the use of crypto submodule in config and run make SHARED=1 all check -j8 USE_CRYPTO_SUBMODULE=1.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2886

**Comment by AndrzejKurek** [comment]
PR raised.

**Comment by gilles-peskine-arm** [comment]
This was resolved by https://github.com/ARMmbed/mbedtls/pull/2884 which superseded https://github.com/ARMmbed/mbedtls/pull/2879.
