### ISSUE TITLE
The "mbedtls_test.py" should be compatible with Python 3.7.

### ISSUE THREAD

**Issue by viva-cy** [ARMmbed/mbedtls#2653]
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug
We use our test suite on Mbed-OS with Python 3.7.
The "mbedtls_test.py" was written using Python 2.7.
Need to rewrite this file to be compatible with Python 3.7.

**OS**  
Mbed OS|windows|

**mbed TLS build:**
Version: 2.16.1
OS version: 5.12.2
Compiler: GCC ARM
Additional environment information:
Mbed-os is used with Python 3.7.

**Comment by RonEld** [comment]
Hi @viva-cy 
Thank you for raising this issue!
Yes, Mbed TLS uses Python 2.7
Please elaborate why you think this is a bug, rather than a  feature request.

**Comment by viva-cy** [comment]
Hi Ron,
Yes, I can agree with you that this is not a bug, but rather a feature.
But, as I already wrote, we use your test-suite as part of Mbed-os to validate our ALT-implementation.
As far as we know, Mbed-os already supported Python 3.x for long time, since version 5.3, and support of our KITs also requires  using of  Python 3.x only.
Based on the above, we are very interested in this problem being solved as soon as possible.
Today I must compile tests on one machine with Python3.x , and execute them  on another with Python 2.x.
Not to mention that this is not comfortable, it does not allow us to perform out automatic testing of our solutions.

**Comment by RonEld** [comment]
Hi @viva-cy Thank you for your information.
We will take this into consideration.
Out of curiosity, Can't you install bith python 3.7 and python 2.7 on same machine and use alternatives, or use the python2 and python3 commands?

**Comment by viva-cy** [comment]
Hello Ron,
I spend some time to debug this issue and came up with following solution.
See attached file to review my fixes. 
I checked these fixes on Windows, Linux ans MacOS machines and they work. 
Please review attached files and let me know if this makes sense to be a part of mbedtls test-suite package. 

Currently I have one more issue but not in MbedTLS. I had to change one line in mbed_os_tools package (file mbed_os_tools\test\host_tests_conn_proxy\conn_primitive_serial.py).
In Python 3.x the encoding is very strong so Line #119 must be changed to:  self.serial.write(payload.encode('raw_unicode_escape')) to allow sending "binary" data to DUT.

[mbedtls_test.zip](https://github.com/ARMmbed/mbedtls/files/3224164/mbedtls_test.zip)

**Comment by viva-cy** [comment]
About your previous question:
Unfortunately, I think that we cannot. We only run the high-level Mbed-CLI commands, and it runs chains of commands by itself that use the "python" call.

**Comment by RonEld** [comment]
HI @viva-cy 
Thank you for your contribution!
I tried runing the test with Python 3.7 and got the following error:
~~~
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mbed_os_tools/test/host_tests_runner/host_test_default.py", line 306, in run_test
    self.test_supervisor.setup()
  File "/home/roneld01/work/temp/mbed-os/features/mbedtls/TESTS/host_tests/mbedtls_test.py", line 197, in setup
    parser.parse(data_file)
  File "/home/roneld01/work/temp/mbed-os/features/mbedtls/TESTS/host_tests/mbedtls_test.py", line 68, in parse
    self.__parse(data_f)
  File "/home/roneld01/work/temp/mbed-os/features/mbedtls/TESTS/host_tests/mbedtls_test.py", line 101, in __parse
    line = data_f.next().strip()
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'
~~~
Is this what you got?

**Comment by viva-cy** [comment]
It is only one issue I got. You could do diff check and found other.

**Comment by RonEld** [comment]
Hi @viva-cy 
I have noticed the script you used is based on the script from #2124 , and that the only change you did was to add a shebang. Unfortunately, this didn't work in my tests, and since it wasn't merged yet, we can't use it.
However, I have create a PR, #2660 that adapt the script to Python 3.7.
Could you confirm that it works for you? You can take the changes and incorporate to your script.
