### ISSUE TITLE
build failure when building with mingw on windows

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2656]
### Description
- Type: Bug
- Priority: Minor

Edit: Changed priority to minor, as with mingw64 the build failure doesn't happen, and this is is the `mingw` version that should be used.

---------------------------------------------------------------
## Bug

**OS**  
windows

**mbed TLS build:**  
Version: 2ab5cf658facf614f658391a8370e7cac3fd663f

**Expected behavior**   
build to succeed
**Actual behavior**  
Build fails with:
~~~
In file included from aes.c:39:0:
../include/mbedtls/platform.h:260:75: error: unknown type name 'va_list'
 int mbedtls_platform_win32_vsnprintf( char *s, size_t n, const char *fmt, va_list arg );
~~~
**Steps to reproduce**  
build with mingw:
~~~
mingw32-make CC=gcc
~~~

Note: A fix for this is including `stdarg.h`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2860
