### ISSUE TITLE
mbedtls_ssl_write doesn’t verify ACK packet?

### ISSUE THREAD

**Issue by tmtoan** [ARMmbed/mbedtls#2659]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
- Priority: Major
## Question
Hi guys,

I’m using lib mbedtls 2.13.0, I currently have an issue that function **mbedtls_ssl_write** return 0 (success on write) without verifying ACK packet from the receiver. I tried to shut down the network connection on my device and **mbedtls_ssl_write** also return 0.

It’s kinda strange because I have chose TCP protocol **MBEDTLS_NET_PROTO_TCP** when connecting with **mbedtls_net_connect**.

What am I doing wrong? If **mbedtls_ssl_write** couldn’t handle the verifying ACK, how should I resolve it manually?

Thanks in advanced.

**Comment by RonEld** [comment]
I have answered your question in our [ support forum](https://forums.mbed.com/t/mbedtls-ssl-write-doesnt-verify-ack-packet/5107) , therefore closing this issue.
We will continue the thread there.
