### ISSUE TITLE
`basic-build-test.sh` silently fails on test 'export keys functionality'

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#2662]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: `development` - commit id - 2ab5cf6 

**Steps to reproduce**  

Executing the script `basic-build-test.sh` on the `development` branch results in a silent failure in the execution of `ssl-opt.sh`. The following is a log extract:

```
DTLS proxy: 3d, gnutls server .......................................... PASS
DTLS proxy: 3d, gnutls server, fragmentation ........................... PASS
DTLS proxy: 3d, gnutls server, fragmentation, nbio ..................... PASS
export keys functionality .............................................. ssl-opt.sh: 619: kill: No such process

PASS
------------------------------------------------------------------------
PASSED (641 / 641 tests (27 skipped))

m->O tls1,no TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA ...................... PASS
m->O tls1,no TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA ...................... PASS
m->O tls1,no TLS-ECDH-ECDSA-WITH-AES-128-CBC-SHA ....................... PASS
```

The test `export keys functionality` should result in a failure or pass - not a test failure that's ignored silently.

Taken from build [#224](https://jenkins-internal.mbed.com/view/mbed-tls/job/mbedtls-release-new/224/).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2864

**Comment by RonEld** [comment]
The failure is because `mbedtls_ssl_tls_prf` with empty key fails, when `MBEDTLS_USE_PSA_CRYPTO` is defined`

On failure, the server terminates:
~~~
        if( ( ret = mbedtls_ssl_tls_prf( eap_tls_keying.tls_prf_type, NULL, 0,
                                         eap_tls_label,
                                         eap_tls_keying.randbytes,
                                         sizeof( eap_tls_keying.randbytes ),
                                         eap_tls_iv,
                                         sizeof( eap_tls_iv ) ) ) != 0 )
         {
             mbedtls_printf( " failed\n  ! mbedtls_ssl_tls_prf returned -0x%x\n\n",
                             -ret );
             goto exit;
         }
~~~
and `ssl-opt.sh` at the end of the test tries to kill the server process which was already terminated.
I think the issue that this issue describes as in issue in `ssl-opts.sh`, however the failure probably needs to be tracked in a different issue
