### ISSUE TITLE
Building mbedtls as a shared library with cmake?

### ISSUE THREAD

**Issue by malmaud** [ARMmbed/mbedtls#267]
The documentation seems to elide how to accomplish that. `cmake . && make SHARED=1` doesn't work - that just compiles the static library.

**Comment by mpg** [comment]
Thanks for your report. Feel free to re-open the issue if you think the new Readme still lacks some information.

**Comment by malmaud** [comment]
Thanks!

**Comment by tkelman** [comment]
Any reason for not using the standard cmake variable `BUILD_SHARED_LIBS` for this?

**Comment by mpg** [comment]
I'm not sure. I seem to understand `BUILD_SHARED_LIBS` builds shared libraries _instead_ of static libraries, while want to allow people to build both. Am I mistaken?

**Comment by tkelman** [comment]
I don't think it has to do so, ref http://www.cmake.org/cmake/help/v3.3/variable/BUILD_SHARED_LIBS.html, but it's somewhat up to each individual project to decide. It looks like when mbedtls builds static libraries you do so under suffixed names? Or is that only when both shared and static libraries are being built?
