### ISSUE TITLE
Invalid range aes_gen_tables

### ISSUE THREAD

**Issue by KammutierSpule** [ARMmbed/mbedtls#2683]
### Description
- Type: Bug
- Priority: Blocker

## Bug
**mbed TLS build:**  
mbed TLS 2.11.0 branch released 2018-06-18

I'm new to mbedTLS,
I'm not sure what flags do I have but my code is calling this function:
aes_gen_tables

And the code is crashing because in this line:
RSb[x] = 
the x has invalid range values.

**Comment by gilles-peskine-arm** [comment]
`aes_gen_tables` is a private function, so you must have patched the library to call it. Why are you calling it? It is called automatically the first time you set up an AES operation. This function is meant to be invoked once. If you're invoking it a second time, I think it'll replace the table with garbage and quite possibly overflow, but this can't happen with the unmodified library.

**Comment by KammutierSpule** [comment]
Hi Gilles, I was not calling it directly myself, I meant "the mbedTLS configurations I had at the time was made the code calling it"
meanwhile I managed to add hardware crypto to my project so I am not facing the issue

**Comment by gilles-peskine-arm** [comment]
Since this was a bug in a third-party modification of the library and is no longer relevant anyway, I'm closing this issue.
