### ISSUE TITLE
MBEDTLS_KEY_EXCHANGE__WITH_CERT__ENABLED

### ISSUE THREAD

**Issue by soundguy66** [ARMmbed/mbedtls#270]
This conditional define in ssl_ciphersuites.h (lines 249 to 258) improperly includes ECDHE-PSK. This prevents building without certs while enabling ECDHE-PSK.

Please remove line 254 from ssl_ciphersuites.h.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSSL-473

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-516
