### ISSUE TITLE
[Question] MBEDTLS_HAVE_ASM on Armv6-M

### ISSUE THREAD

**Issue by davidhuziji** [ARMmbed/mbedtls#2703]
Hi,

I'm using mbedtls on a Cortex-M0Plus core with ArmClang 6.10. If I enable `MBEDTLS_HAVE_ASM`, various errors will occur during compiling, such as for macro `MULADDC_INIT`:
> error: inline assembly requires more registers than available

If I comment `MBEDTLS_HAVE_ASM`, compiling can succeed without any above error.
It seems that Armv6-M cannot support assembly code feature of mbedtls well. Could someone give me more details about whether Armv6-M can support `MBEDTLS_HAVE_ASM`?

**Comment by RonEld** [comment]
Hi @davidhuziji 
Thank youi for your question!
As you can see in the archived issue https://github.com/ARMmbed/mbedtls/issues/1077 , you cannot use ARMC 6 on cortex M0
You can work around it, if you mentioned, without using assembly.

**Comment by davidhuziji** [comment]
> Hi @davidhuziji
> Thank youi for your question!
> As you can see in the issue #1077 , you cannot use ARMC 6 on cortex M0
> You can work around it, if you mentioned, without using assembly.

Thx a lot, @RonEld! Will try as you suggest.
