### ISSUE TITLE
Visual Studio cannot compile 

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2709]
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
Windows

**mbed TLS build:**  
Version: git commit c54ee936d7e2787143be6b3eb761f1a822ccad63 (development, 2.17.0; should be the same for 2.18 branch)
OS version: Windows Server 2019
Configuration: default
Compiler: Visual Studio 2019

**Expected behavior** 
Unpack downloaded .zip
Load solution into IDE
mbedTLS compiles with the default config.h, as it used to be previously

**Actual behavior**  
Compilation immediately fails, because `crypto` directory is empty, while VS project file refers to it and its subdirectories as if there are sources (source files are still in `library`).

_Additionaly, VS projects still have the line with the reference to `Windows 7.1 SDK`; it produces error when upgrading projects. That bug was reported long ago, but recently the issue was silently closed without any explanation._

**Comment by Patater** [comment]
Hi @irwir,

This is currently a limitation of GitHub, in that it does not include submodules in the zip files it makes available for download. Please also [download the Mbed Crypto zip file](https://github.com/ARMmbed/mbed-crypto/archive/mbedcrypto-1.1.0d2.zip) and make its contents be the contents of the `crypto` in the Mbed TLS project folder.

**Comment by irwir** [comment]
Thanks @Patater, it helped.
A small readme file in `crypto` directory could have been useful.
