### ISSUE TITLE
State of crypto code in mbedtls repo

### ISSUE THREAD

**Issue by jack-fortanix** [ARMmbed/mbedtls#2715]
I know you prefer questions on the support forum but this is not a usage question but instead something about project direction. Starting in 2.18.0, mbed-crypto is used to provide crypto operations and the relevent files in mbedtls repo (such as md5.c, aes.c, ...) are since 346747cd24dc0def1 completely ignored. Are these files going to be eventually removed? Am I correct in thinking that any PRs affecting these files should be directed to mbed-crypto? Thanks.

**Comment by Patater** [comment]
Hi @jack-fortanix,

Yes, that's correct. The crypto-related files will be removed from the mbedtls repo shortly. Please raise crypto related PRs to Mbed Crypto. We'll do one final merge of the crypto-related files from Mbed TLS to Mbed Crypto, to be sure we have everything up to date before we remove the files from Mbed TLS.

Cheers
