### ISSUE TITLE
partial zeroing in x509_get_other_name

### ISSUE THREAD

**Issue by ekse** [ARMmbed/mbedtls#2716]
In x509_get_other_name, sizeof is used to get the size of `other_name` which is a pointer (`mbedtls_x509_san_other_name *other_name`). As a result the structure is only partially zeroed. The same issue is also found on lines 1712 and 1727.

```c
mbedtls_platform_zeroize( other_name, sizeof( other_name ) );
```
https://github.com/ARMmbed/mbedtls/blob/development/library/x509_crt.c#L1690

A potential fix would be to use `sizeof(mbedtls_x509_san_other_name)` instead.

**Comment by RonEld** [comment]
Hi @ekse 
Yes, you are correct. It was an oversight, and the zeroization is wrong here.
I would fix it using `sizeof(*other_name )` though, for future compatibility.

**Comment by RonEld** [comment]
#2719 has been merged, so closing this issue
