### ISSUE TITLE
Strange sizeof

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2717]
https://github.com/ARMmbed/mbedtls/blob/66b7edb10865809a972362ce362c62820075ade3/library/ssl_tls.c#L6897-L6898
Since `MBEDTLS_SSL_PEER_CERT_DIGEST_DFL_LEN` is defined as a number, `sizeof` operator should be an error.

**Comment by hanno-arm** [comment]
Hi @irwir,

that's a typo, thanks for spotting it! We'll fix it.

Best,
Hanno
