### ISSUE TITLE
Build fails using swift 5 because of missing sys/types.h in mbedtls/platform_time.h

### ISSUE THREAD

**Issue by mman** [ARMmbed/mbedtls#2725]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Ubuntu 18.04 Bionic, Swift 5.0.1

**mbed TLS build:**  
Version: 2.18.0
OS version: Ubuntu 18.04  
Configuration: unmodified git checkout of mbedtls-2.18.0 tag 

**Expected behavior**   

The compilation using swift package manager 5.0.1 works as with swift package manager 4.2.

**Actual behavior**  

The compilation fails with error message from clang

```
mbedtls/include/mbedtls/platform_time.h:53:9: error: declaration of 'time_t' must be imported from module 'SwiftGlibc.POSIX.sys.types' before it is required
typedef time_t mbedtls_time_t;
        ^
//usr/include/x86_64-linux-gnu/bits/types/time_t.h:7:18: note: previous declaration is here
typedef __time_t time_t;
```

**Steps to reproduce**  

This is private code, but it looks like swift package manager 5.0.1 is invoking clang with very aggressive compiler options and mbedtls fails to build.

The fix is easy, apply the following patch to ``platform_time.h``

```
--- mbedtls/include/mbedtls/platform_time.h.orig	2019-06-28 14:54:12.386047088 +0000
+++ mbedtls/include/mbedtls/platform_time.h	2019-06-28 14:54:36.565915054 +0000
@@ -49,6 +49,7 @@
 typedef MBEDTLS_PLATFORM_TIME_TYPE_MACRO mbedtls_time_t;
 #else
 /* For time_t */
+#include <sys/types.h>
 #include <time.h>
 typedef time_t mbedtls_time_t;
 #endif /* MBEDTLS_PLATFORM_TIME_TYPE_MACRO */
```

**Comment by Patater** [comment]
`time_t` should come from `time.h`, and is a standard ISO C type. To require including any `sys/` header for this would break non-POSIX platforms.
