### ISSUE TITLE
Migrate changes to mbedtls-crypto

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2745]
### Description
- Type: Enhancement

**mbed TLS build:**  
Version: development
----------------------------------------------------------------
**Suggested enhancement** 
That would be opposite to "Requires backport" in PR template.
The issues/pull request made in `mbedtls`, especially old ones, might need to be re-implemented in `mbedtls-crypto` repository.
For example: #1430 and #2640

**Comment by Patater** [comment]
We periodically merge from Mbed TLS development to Mbed Crypto development to get changes in tools which are currently duplicated between the projects. For example, https://github.com/ARMmbed/mbed-crypto/pull/158

Another PR like that is in progress
