### ISSUE TITLE
What's this: 00 00 00 00 00 00 00

### ISSUE THREAD

**Issue by caobug** [ARMmbed/mbedtls#2746]
Hello, I tried send some data to remote server, but all request prefix have some 00 00 00 00 00 00 00 info. 

how to remove these zero?

This is my code:

```
int tls_init(remote_t *remote, int fd) {
    tls_session_t *tls = malloc(sizeof(tls_session_t));
    memset(tls, 0, sizeof(tls_session_t));
    
    // init config
    mbedtls_net_init(&tls->fd);
    mbedtls_ssl_init(&tls->ssl);
    mbedtls_ssl_config_init(&tls->conf);
    mbedtls_x509_crt_init(&tls->cacert);
    mbedtls_ctr_drbg_init(&tls->ctr_drbg);
    mbedtls_entropy_init(&tls->entropy);
    
    tls->fd.fd = fd;
    remote->tls = tls;
    
    int ret = 0;
    if((ret = mbedtls_ctr_drbg_seed(&tls->ctr_drbg, mbedtls_entropy_func, &tls->entropy, (const unsigned char *)WS_PERS, strlen(WS_PERS))) != 0) {
        printf("failed! mbedtls_ctr_drbg_seed returned %d\n", ret);
        return 1;
    }
    
    if ((ret = mbedtls_x509_crt_parse(&tls->cacert, (const unsigned char *)default_pem, sizeof(default_pem))) < 0) {
        printf("failed! mbedtls_x509_crt_parse returned -0x%x\n", -ret);
        return 1;
    }
    
    if ((ret = mbedtls_ssl_config_defaults(&tls->conf, MBEDTLS_SSL_IS_CLIENT, MBEDTLS_SSL_TRANSPORT_STREAM, MBEDTLS_SSL_PRESET_DEFAULT)) != 0) {
        printf("failed! mbedtls_ssl_config_defaults returned %d\n", ret);
        return 1;
    }
    
    mbedtls_ssl_conf_authmode(&tls->conf, MBEDTLS_SSL_VERIFY_OPTIONAL);
    mbedtls_ssl_conf_ca_chain(&tls->conf, &tls->cacert, NULL);
    
    mbedtls_ssl_conf_rng(&tls->conf, mbedtls_ctr_drbg_random, &tls->ctr_drbg);
    mbedtls_ssl_conf_dbg(&tls->conf, my_debug, stdout);
    
    if ((ret = mbedtls_ssl_setup(&tls->ssl, &tls->conf))) {
        return 1;
    }
    
    mbedtls_ssl_set_hostname(&tls->ssl, "mydomain.com");
    mbedtls_ssl_set_bio(&tls->ssl, &tls->fd, mbedtls_net_send, mbedtls_net_recv, NULL);
    
    return 0;
}

int tls_handshake(remote_t *remote) {
    tls_session_t *tls = remote->tls;
    int ret = 0, flags = 0;
    while ((ret = mbedtls_ssl_handshake(&tls->ssl)) != 0) {
        if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
            printf( "failed! mbedtls_ssl_handshake returned %d\n", ret);
            return 1;
        }
    }
    if ((flags = mbedtls_ssl_get_verify_result(&tls->ssl)) != 0) {
        return 1;
    }
    return 0;
}
```

Wireshark send and recv data:

```
Encrypted Application Data: 00000000000000027cd6bd2e5aa1a1c1c2bc010ccba17e29…
```

**Comment by irwir** [comment]
Do you have the same effect when building example programs (ssl_client1 is the simplest)?

**Comment by caobug** [comment]
@irwir Yes, the ssl_client1 have same issues.

**Comment by caobug** [comment]
![WX20190713-123713](https://user-images.githubusercontent.com/7737673/61167044-f78f7080-a56a-11e9-9d19-84074f1f883a.png)

**Comment by irwir** [comment]
From brief consulting with the [rfc5246](https://tools.ietf.org/html/rfc5246), zeros might be a part of `sequence number`.
As a first step, please compare your findings with the standars

**Comment by RonEld** [comment]
@caobug Why do you have `MBEDTLS_SSL_VERIFY_OPTIONAL` as the `authmode`?
In addition for this not being secured, can you confirm that the tls handshake completed successfully?
You shouldn't get these leading zeros
What do the Mbed TLS logs say? See https://tls.mbed.org/kb/development/debugging-tls
I am asusming that the server fails to encrypt your data.

**Comment by caobug** [comment]
@RonEld Hello, the TLS handshake is normal,`MBEDTLS_SSL_VERIFY_OPTIONAL` is just an example. I actually changed the option to`MBEDTLS_SSL_VERIFY_REQUIRED` without any problems. I can successfully send and receive all data, just don't understand these zeros. so far, these zeros have not affected my data transfer.

**Comment by caobug** [comment]
Sorry, I compiled the latest version "Mbed TLS 2.16.2", these zeros have disappeared. maybe my previous version is too low.

@irwir @RonEld Thanks.

**Comment by RonEld** [comment]
CLosing as the question was answered and resolved
