### ISSUE TITLE
Typo in Release Notes for Mbed TLS 2.16.2 and Mbed TLS 2.7.11

### ISSUE THREAD

**Issue by chaosbastler** [ARMmbed/mbedtls#2758]
The versions in the description of the release notes for 2.16.2 and 2.7.11 are wrong. This is a minor documentation issue but may confuse some users.

- https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.16.2
- https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.7.11

**Comment by Patater** [comment]
@chaosbastler Thanks! Fixed.
