### ISSUE TITLE
socklen_t isn't properly detected for musl libc

### ISSUE THREAD

**Issue by zhasha** [ARMmbed/mbedtls#278]
mbedtls generates a bunch of warnings with -Wpointer-sign because it doesn't detect the presence of socklen_t when compiling against musl. As a consequence it falls back to int, whereas musl uses unsigned for socklen_t. This patch rectifies it in the current #ifdef nightmare fashion.
https://gist.github.com/zhasha/3fc7e7fe594599c753d8

**Comment by dubek** [comment]
:+1: the patch solves the same problem for me when cross-compiling with arm-openwrt-linux-muslgnueabi-gcc

**Comment by mpg** [comment]
Patch approved for merge.
