### ISSUE TITLE
Typo in ASN1 test dependency

### ISSUE THREAD

**Issue by tmarti2** [ARMmbed/mbedtls#2782]
Hi,
I think I found a typo in the commit 0fbbc64.
Maybe I'm wrong, but I could not find `MBEDTLS_ASN1PARSE_C` anywhere, while `MBEDTLS_ASN1_PARSE_C` seems to be used in many files...
Because of this some tests were not enabled (message : "Test suite not enabled" ).
That's it, thanks !

**Comment by RonEld** [comment]
@tmarti2 Thank you for raising this issue!
This bug in fact needs to be fixed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2906

**Comment by AndrzejKurek** [comment]
Created a PR for it here: https://github.com/ARMmbed/mbedtls/pull/3124, development was fixed in the meantime.
