### ISSUE TITLE
all.sh silently ignores unknown component names

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#2783]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

`all.sh` does not complain when given non-existent component names. For example,
```
tests/scripts/all.sh barf
```
does nothing and returns 0.

This is technically correct since the arguments to `all.sh` are patterns. If no component matches the pattern `barf`, do nothing. However, it's very error-prone: if you make a mistake in a component name, the script will silently do nothing.

`all.sh` should complain at least if a command line argument does not contain wildcards and does not match any valid component name. I'm less sure what it should do if a command line argument contains wildcards but does not match any component. In exclude mode, it should remain fine to pass an argument that matches nothing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2905
