### ISSUE TITLE
Feature request - 'inline keyword must not be macroized when building C++ code'

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#279]
> I need to compile C++ code that includes mbedtls-headers with the 
> Visual Studio
> 2013 C++ compiler.
> 
> The "#define inline __inline" does not work with Visual Studio 2013 
> when compiling C++ code. The error message is (approximately) "The C++ 
> Standard Library does forbids macroizing keywords".
> 
> The #define inline should be guarded with #ifndef __cplusplus or similar.
> 
> Affects several h-files in mbedtls-2.1.0 and prior versions.

**Comment by mpg** [comment]
Fixed by 0223ab9
