### ISSUE TITLE
Unused variable warning in VS 2019

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2800]
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_tls.c#L122
When `MBEDTLS_SSL_PROTO_DTLS` is undefined, this declaration generates an _unused variable_ warning.

The simplest fix could be to make the declaration local in the block where the variable was used, which would be directly before this line:
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_tls.c#L139

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2904
