### ISSUE TITLE
Condition always false in x509_get_subject_alt_name

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2802]
Comparing with zero could be slightly more efficient, but also it is easier to understand.

https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/x509_crt.c#L648
It might be guessed that the intention was to check `end>=*p`, but the values are pointers, and thus unsigned.
In pointer arithmetics anything less than 1 is nothing but 0.
Hence the condition means `end == *p`,

In any case, the loop header ensures that `*p < end`.

**Comment by k-stachowiak** [comment]
The check is in fact redundant, but I disagree with the explanation. `end - *p` is of type `ptrdiff_t` which is a signed type. It could be negative if `*p` went beyond `end`.
That will not happen, but not because of the pointer arithmetic. It won't happen because of the loop condition that you have pointed out.

**Comment by irwir** [comment]
@k-stachowiak 
Thanks for looking at the issue.

> `end - *p` is of type `ptrdiff_t` which is a signed type.

You are right here. Idea of treating pointers as unsigned remained from old times; now this is implementation defined.
By the way, VS compiler would use signed comparison in case of `(end - *p) > 1`, but unsigned if the condition is `end > *p + 1` 

> It could be negative if `*p` went beyond `end`.

Or if the difference is above maximum positive value for `prtdiff_t` type?
That is why it might be better to avoid expressions such as `end - *p`  (quite a few of these are in `asn1parse.c`).
