### ISSUE TITLE
curl build with mbedtls error

### ISSUE THREAD

**Issue by zh794390558** [ARMmbed/mbedtls#2806]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
```
-Making all in lib
make[1]: Entering directory '/home/odin/ethanzhanghui/delta/tools/curl/lib'
make  all-am
make[2]: Entering directory '/home/odin/ethanzhanghui/delta/tools/curl/lib'
  CC       libcurl_la-file.lo
In file included from file.c:23:0:
curl_setup.h:674:27: fatal error: mbedtls/md4.h: No such file or directory
 #  include <mbedtls/md4.h>
                           ^
compilation terminated.
Makefile:1340: recipe for target 'libcurl_la-file.lo' failed
make[2]: *** [libcurl_la-file.lo] Error 1
make[2]: Leaving directory '/home/odin/ethanzhanghui/delta/tools/curl/lib'
Makefile:772: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/odin/ethanzhanghui/delta/tools/curl/lib'
Makefile:945: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

**Comment by RonEld** [comment]
@zh794390558 
Thank you for your question!

HAve you followed the guidelines in [this article](https://tls.mbed.org/kb/how-to/compile-curl-with-mbedtls)?

What is the Mbed TLS version you are using?
Did you set the correct include path when building curl?
I believe [this page](https://curl.haxx.se/docs/install.html) can also assist.

**Comment by zh794390558** [comment]
same to the article, makefile under crypto error. Makefile under this repo can not install headers under crypto dir.

**Comment by RonEld** [comment]
Hi @zh794390558 
From your answer I understand you are working on code from repository,which has the crypto folder, and not on official release. Am I right?

**Comment by zh794390558** [comment]
Yes, you are right. I using the code from this repo to build mbedtls share library, which is using for curl.

**Comment by RonEld** [comment]
Hi @zh794390558 
I apologize for delayed reply.
This may be an issue in the curl makefile, that was not integrated yet to the new Mbed TLS structure. However, when I ran the 'make install' command in the latest Mbed TLS commit id,  it copied all the header files to the `mbedtls` destination include folder('/usr/local'), as described in [this article](https://tls.mbed.org/kb/how-to/compile-curl-with-mbedtls). So I don't see an issue. Have you followed the article?

**Comment by zh794390558** [comment]
Almost, I using [this](https://github.com/didi/delta/blob/master/tools/Makefile#L215) to install curl with mbedtls.

**Comment by Benau** [comment]
Hello, it seems that starting with mbedtls 3.0.0 md4.h no longer exists, maybe time to update curl to allow building with latest mbedtls.....

https://github.com/ARMmbed/mbedtls/issues/4084

(maybe md4 support in curl can be disabled too?)

**Comment by Benau** [comment]
oh sorry this should belong to curl issue tracker anyway, thought i was posting there....

**Comment by Benau** [comment]
https://github.com/curl/curl/discussions/7376, see how they reply

**Comment by gilles-peskine-arm** [comment]
This issue was raised when crypto was in a submodule of mbedtls. Since then crypto has been reintegrated into the mbedtls repository, it is no longer applicable.

Mbed TLS 3.0 removed md4 altogether, which is [a different issue](https://github.com/curl/curl/discussions/7376).
