### ISSUE TITLE
Clarify dual-licensing situation?

### ISSUE THREAD

**Issue by malmaud** [ARMmbed/mbedtls#282]
I have built binaries of MbedTLS which are installed automatically as a consequence of installing the [Julia MbedTLS wrapper](https://github.com/JuliaWeb/MbedTLS.jl). Given that MbedTLS 2.1 comes in both an Apache version and GPL version, I'd like to dual-license my package under both GPL and Apache so that the package can be distributed alongside other GPL software. However, I've noticed that the binaries of the Apache and GPL version  of libmbedtls* are not bit-for-bit identical, so I'm unsure on whether it is safe to say in my package's license that the bundled libmbedtls code/binaries are actually dual-licensed.  

Can you provide guidance on the proper way to handle this? Thanks!

**Comment by mpg** [comment]
Are you sure the difference between the build results of the GPL and the Apache package are not attributable purely to the build not being reproducable? (Like, the toolchain embedding some metadata or whatever - I'm not very familiar with reproducable build efforts but I seem to understand toolchains tend to make this hard.)

As far as I know, the GPL tarball differs from the Apache tarball only in comments and the license files; the code itself is identical. (This should be easy enough to check with a recursive diff.)

@pjbakker: any comment on that?

**Comment by pjbakker** [comment]
I confirm that the only difference is the headers and LICENSE file.
There are no code changes.

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium.  Thank you.

ARM Limited, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2557590
ARM Holdings plc, Registered office 110 Fulbourn Road, Cambridge CB1 9NJ, Registered in England & Wales, Company No:  2548782
