### ISSUE TITLE
mbedtls cannot be built without tests on unix

### ISSUE THREAD

**Issue by arpadboda** [ARMmbed/mbedtls#2824]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Enhancement\Feature Request
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
linux

**Expected behavior**   
In case of embedding mbedtls to another project, it makes no sense to build it with tests. Tests are for development/release procedure only.

**Actual behavior**  
In case the compiler is not MSVC, mbedtls is build with tests

**Steps to reproduce**  
Just build it on unix.
----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
mbedtls build without tests for smaller footprint

**Suggested enhancement**  
Add a cmake option to disable tests

**Comment by Patater** [comment]
Hi @arpadboda,

Thanks for raising this with us. We support a few build targets that don't build the tests. Which targets are available depends on your build system.

### Makefile
- To build just the library, `make lib`.
- To build programs and library, `make no_test`.

## CMake
To build just the library, `make lib`.

Should we add the `no_test` target to CMake or does the `lib` target already meet your needs?

**Comment by gilles-peskine-arm** [comment]
As far as I understand the requested feature, it already exists. Therefore I'm closing this issue.

**Comment by vpodzime** [comment]
Since I ended up here trying to find a solution for what I believe is the same issue, but with a worse option for work-arounds, I'm going to ask in this closed issue.

I'm doing this:
```
include(FetchContent)
FetchContent_Declare(
  MbedTLS
  GIT_REPOSITORY https://github.com/Mbed-TLS/mbedtls
  GIT_TAG        v3.6.2
  DOWNLOAD_EXTRACT_TIMESTAMP TRUE
  FIND_PACKAGE_ARGS NAMES MbedTLS
)
message(STATUS "Fetching MbedTLS...")
FetchContent_MakeAvailable(MbedTLS)
find_package(MbedTLS REQUIRED)
```
And then when I build my project, it builds mbedtls tests and binaries. I haven't found any way that would allow me to tell CMake to set `ENABLE_TESTING` and `ENABLE_PROGRAMS` to `OFF` when using mbedtls like this.

What's the solution in my case?

**Comment by davidhorstmann-arm** [comment]
Hi, if I understand CMake's scoping rules correctly, any variables that are set when you call `add_subdirectory()` are automatically copied to the subdirectory's scope. That means that any variables you set before adding the Mbed TLS subdirectory are inherited by Mbed TLS.

IIUC with CMake FetchContent it is the call to `FetchContent_MakeAvailable()` which performs the `add_subdirectory()` call, so you should be able to do:
```cmake
set(ENABLE_TESTING OFF)
set(ENABLE_PROGRAMS OFF)
```
Before calling `FetchContent_MakeAvailable()`. It looks like this will work with CMake [newer than version 3.13](https://cmake.org/cmake/help/latest/policy/CMP0077.html).

For older CMake versions, Google suggests something like:
```cmake
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
```
But I'm afraid your search is as good as mine in that case.

**Comment by vpodzime** [comment]
With

```
set(ENABLE_TESTING OFF)
set(ENABLE_PROGRAMS OFF)
```

I get this: 

```
CMake Warning (dev) at _deps/mbedtls-src/CMakeLists.txt:65 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'ENABLE_PROGRAMS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at _deps/mbedtls-src/CMakeLists.txt:95 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'ENABLE_TESTING'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Even with cmake version 3.28.2 and it still builds the tests and programs. So I guess that's something to fix in mbedtls?

The approach for older CMake versions works. However, `ENABLE_TESTING` and `ENABLE_PROGRAMS` are not specific names one wants to set in their `CMakeLists.txt`. Perhaps there could be some `MBEDTLS`-prefixed options for this?
