### ISSUE TITLE
Is mbedtls 2.19.0d2 an actual release?

### ISSUE THREAD

**Issue by jack-fortanix** [ARMmbed/mbedtls#2844]
Hi. The situation on the mbedtls 2.19.0 release is not so clear - what is the meaning of the d1/d2 tags? "draft"? It appears the only difference between d1 and d2 is some fixes to the ChangeLog. And the d2 ChangeLog does indicate that 2.19.0 was released on Sep 6th. But I notice over in mbed-crypto that there are d0/d1/d2 tagged, which were each released about a week apart from each other. So it is not clear if we should expect a future 2.19.0d3, or 2.19.0 "final", or if 2.19.0d2 is in fact the 2.19.0 release. Thanks.

**Comment by RonEld** [comment]
Hi @jack-fortanix 
As you can see from [this blog](https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3), until Mbed TLS 3.0 will be out, our official releases are only for our LTS branches, and our feature releases are only targeting Mbed OS, at the moment.
You can use them, of course.
AS you can see from [this PR in Mbed OS](https://github.com/ARMmbed/mbed-os/pull/11435), the d2 was the latest developemnt release sent to Mbed OS.
As you can see from [this PR](https://github.com/ARMmbed/mbed-os/pull/11493), version 2.19.1 has already been merged to Mbed OS, so it is safe to say you won't expect a future 2.19.0d3 release, and 2.19.0d2 is the 2.19.0 release.
As for Mbed Crypto, it is different than Mbed TLS releases, and the Mbed Crypto version in the Mbed TLS 2.19.0 release is 2.0.0d2

**Comment by jack-fortanix** [comment]
Ah I see. OK.

One more q, the blog post you reference states "The split will be effective with the Mbed TLS 3.0 release, expected in June 2019." - is there an updated timeline for this? The library split seems to have already been completed.

**Comment by RonEld** [comment]
Hi @jack-fortanix 
As you can see from [this blog](https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3), until Mbed TLS 3.0 will be out, our official releases are only for our LTS branches, and our feature releases are only targeting Mbed OS, at the moment.
You can use them, of course.
As you can see from [this PR in Mbed OS](https://github.com/ARMmbed/mbed-os/pull/11435), the d2 was the latest developemnt release sent to Mbed OS.
As you can see from [this PR](https://github.com/ARMmbed/mbed-os/pull/11493), version 2.19.1 has already been merged to Mbed OS, so it is safe to say you won't expect a future 2.19.0d3 release, and 2.19.0d2 is the 2.19.0 release.
As for Mbed Crypto, it is different than Mbed TLS releases, and the Mbed Crypto version in the Mbed TLS 2.19.0 release is 2.0.0d2

**Comment by RonEld** [comment]
Hi @jack-fortanix 

Unfortunately, I don't have an updated timeline, but we are getting close.
The majority of the split has happened, but there are still some more tasks to be done before we can claim it's completed

**Comment by Patater** [comment]
The only split we've completed so far is splitting the repos. The remaining effort would be on making Mbed TLS use more crypto through the PSA Crypto API rather than the Mbed TLS crypto API. Then we'd remove the Mbed TLS crypto API from the public interface and expose only the PSA Crypto interface (and a few minor extensions) from Mbed Crypto.
