### ISSUE TITLE
Mbedtls 2.19.1 fails to build from source with MBEDTLS_ZLIB_SUPPORT

### ISSUE THREAD

**Issue by jack-fortanix** [ARMmbed/mbedtls#2859]
### Description
- Type: Bug

## Bug

**OS**  : any

**mbed TLS build:**   2.19.1
Configuration: MBEDTLS_ZLIB_SUPPORT
Compiler and options: gcc/any

**Steps to reproduce**  
Uncomment MBEDTLS_ZLIB_SUPPORT from the default config.h and attempt to build:
```
[ 19%] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls.c.o
/home/jack/sw/mbedtls/library/ssl_tls.c: In function ‘mbedtls_ssl_derive_keys’:
/home/jack/sw/mbedtls/library/ssl_tls.c:1862:9: error: ‘session’ undeclared (first use in this function); did you mean ‘setsid’?
     if( session->compression == MBEDTLS_SSL_COMPRESS_DEFLATE &&
         ^~~~~~~
         setsid
```

Looks to have been introduced between 2.18.0 and 2.19.0 though I could not find the exact commit. I believe this should now be `ssl->session_negotiate->compression`

**Comment by RonEld** [comment]
Hi @jack-fortanix Thank you for your input!
AS youc an see from the [ChangeLog](https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog#L923) ZLIB support has been deprecated. So you should have received a build error, but it should have been a deprecation error, and probably not this error.

I would actually rename this bug to: "Deprecated ferature `MBEDTLS_ZLIB_SUPPORT` still used in some locations", or something better in grammar
