### ISSUE TITLE
MBEDTLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION docs should include warning

### ISSUE THREAD

**Issue by NWilson** [ARMmbed/mbedtls#288]
In config.h, several of the options contain a strong warning:

    \warning Depending on your PKI use, disabling this can be a security risk!

However, `MBEDTLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION` does not come with this warning. I reckon it probably should.

One of my tests checks that certificate chains with violated X.509 nameConstraints are not allowed. (Note that I don't use nameConstraints, and I don't care if chains with satisfied nameConstraints validate or not, I just want to fail chains with violated constraints. This is partly a box-checking exercise on my part, since the PKIX RFC5280 has a "MUST" for nameConstraints. And, because I use some "well known" Verisign/Symantec roots in our product, and there's a small chance that a sub-CA out there has issued nameConstrained certificates, I want to be sure they won't be accepted in our product.)

So, I'm very happy with the mbedTLS default behaviour, which is to reject certificates entirely which contain (critical) nameConstraints. Would it be possible to add a warning to `config.h` for `MBEDTLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION`, indicating the consequences?

**Comment by mpg** [comment]
I agree, we'll add the warning. I'm actually surprised we don't have that warning already, thanks for noticing.
