### ISSUE TITLE
DTLS use at least one of SHA-1, SHA-256, SHA-512

### ISSUE THREAD

**Issue by VitSolcikNXP** [ARMmbed/mbedtls#2885]
In file ssl_cookie.c you are saying that usage of SHA-1, SHA-256, SHA-512 is needed, but in define section is used SHA-224 instead of SHA-256
https://github.com/ARMmbed/mbedtls/blob/74692aeb8c7e2c1c0f273592d87472a6f2aabacf/library/ssl_cookie.c#L52

https://github.com/ARMmbed/mbedtls/blob/74692aeb8c7e2c1c0f273592d87472a6f2aabacf/library/ssl_cookie.c#L53

Is this intentional? 
Thanks for reply.

**Comment by RonEld** [comment]
Hi @VitSolcik 
Thanks for raising this to our attention!
This is probably a writer's error in the comment.
However, note that `SHA224` is basically truncated `SHA256`(with different initial state), and uses the `MBEDTLS_SHA256_C` module definition.
Similar, `SHA384` is a truncated `SHA512`.

**Comment by mpg** [comment]
This has been reported again independently as #4457 and is becoming more of a problem now that we allow builds with SHA-256  but not SHA-224. So, I'm closing this one as a duplicate and keeping #4457 as it has more up-to-date information about our current build options.

Thanks again for your report!
