### ISSUE TITLE
How to re-use tickets in client mode?

### ISSUE THREAD

**Issue by HorvathAkosPeter** [ARMmbed/mbedtls#2917]
I am not sure if it would be better as bug report. I am trying to re-use ssl tickets from the client side, using `ssl_client2.c` as template.

Unfortunately, this tool makes only a single connection, what is completely cleaned up on exit, thus the problem does not appear.

My experience is that the ssl ticket data (ssl_ctx->session_negotiate->ticket) is completely zeroed up *on the ssl handshake*. Thus, the `mbedtls_ssl_handshake()` creates the ticket (in the `MBEDTLS_SSL_SERVER_NEW_SESSION_TICKET` state) correctly, but it is then zeroed in the last state (`MBEDTLS_SSL_HANDSHAKE_WRAPUP`). Checking `mbedtls_ssl_handshake_wrapup()` in ssl_tls.c, it is clear that it unconditionally deletes the `session_negotiate` field of the ssl context, deleting the ticket with it.

Furthermore, we also don't have the useful callback-based ticket saving mechanism what we would have in a server role.

The result is that, despite the support, I can't re-use ssl tickets in client mode.

Am I missing something, or I found a bug?

### Description
- Type: Question
- Priority: Blocker

## Bug

**OS**  
Mbed OS

**mbed TLS build:**  at least the one in the current FreeRTOS, but probably any latest, incl. the current "development" branch of the upstream
Version: any recent
OS version: FreeRTOS, but the problem looks cross-platform

Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Expected behavior**   

Some - ideally, intuitive - way to preserve the ssl tickets between client connections.

**Actual behavior**  

Ssl tickets are automatically deleted, as a side-effect of the client side of the handshake.

**Steps to reproduce**  

Try to re-use an ssl ticket between different connections (the examples connect only a single time, so ticketing is not problem).

----

Extension: now I found, that the `->resume` field must be non-zero, and the only way to set it on the client is to use `mbedtls_ssl_set_session()`. But exactly how, is still unclear - the first handshake won't have a saved session, thus there won't be anything to call `mbedtls_ssl_set_session()`. The example calls it *after the handshake*, thus the saved session will still have a zeroed ticket.

**Comment by HorvathAkosPeter** [comment]
I found the problem and the session ticketing is now working.

The important thing to know: in the ssl context (`mbedtls_ssl_context`), we have *multiple* session pointers (`*mbedtls_ssl_session`). The two important are: `ssl_ctx->session_negotiate` and `ssl_ctx->session`. The first is *for the session under negotiations during the handshake phase*. After that - in the `WRAPUP` state - it will be obviously deleted.

However, it will be also saved into the second, to `ssl_ctx->session`!

The `mbedtls_ssl_{get,set}_session` calls are saving/recovering *this session data*, into an `mbedtls_ssl_session` struct. This is the `saved_session` in the example source `ssl_client2.c`.

Thus, the essence what an ssl session ticketing client should do, is this:

1. Before all, we configure the ssl session tickets and renegotiation:

```
mbedtls_ssl_conf_session_tickets(&ssl_conf, MBEDTLS_SSL_SESSION_TICKETS_ENABLED);
mbedtls_ssl_conf_renegotiation(&ssl_conf, MBEDTLS_SSL_RENEGOTIATION_ENABLED);
```

2. We also declare a variable for the saved session data, *and also a boolean to know, if we already have used it*:

```
mbedtls_ssl_session saved_session;
int has_saved_session = 0;
```

3. *Before* every `mbedtls_ssl_handshake(...)`, we check if we already have a saved session, and if yes, first we recover the session data from it:

```
if (has_saved_session) {
      mbedtls_ssl_set_session(&ssl_ctx, &saved_session);
}```

4. Then we do the handshake:
```
 mbedtls_ssl_handshake(&ssl_ctx)
```

5. *After the handshake, but before any session cleanup, we save the session data.* We also sign in the `has_saved_session` boolean, that yes, already we have.

```
  mbedtls_ssl_get_session(&ssl_ctx, &saved_session);
  has_saved_session = 1;
```

6. Then we do the cleanups (relese the network file descriptor, reset context and so on).

7. For getting a new handshake, this time much faster, using the tickets, **goto 3**.

Done.

**Comment by Patater** [comment]
Thanks. I'm happy to hear it is working.

**Comment by shootao** [comment]
Hi @HorvathAkosPeter 
I used your method to test. When setting `mbedtls_ssl_set_session` for the second time, it appeared in Crash, at the `src->peer_cert->raw`position, is nullptr. Is there anything I need to save for this?
```c

    mbedtls_ssl_session saved_session;
    bool has_saved_session = false;
    mbedtls_ssl_conf_session_tickets(&conf, MBEDTLS_SSL_SESSION_TICKETS_ENABLED);
    mbedtls_ssl_conf_renegotiation(&conf, MBEDTLS_SSL_RENEGOTIATION_ENABLED);


    while(1) {
        /* Wait for the callback to set the CONNECTED_BIT in the
           event group.
        */
        xEventGroupWaitBits(wifi_event_group, CONNECTED_BIT,
                            false, true, portMAX_DELAY);
        ESP_LOGI(TAG, "Connected to AP");

        mbedtls_net_init(&server_fd);

        ESP_LOGI(TAG, "Connecting to %s:%s...", WEB_SERVER, WEB_PORT);

        if ((ret = mbedtls_net_connect(&server_fd, WEB_SERVER,
                                      WEB_PORT, MBEDTLS_NET_PROTO_TCP)) != 0)
        {
            ESP_LOGE(TAG, "mbedtls_net_connect returned -%x", -ret);
            goto exit;
        }

        ESP_LOGI(TAG, "Connected.");

        mbedtls_ssl_set_bio(&ssl, &server_fd, mbedtls_net_send, mbedtls_net_recv, NULL);

        ESP_LOGI(TAG, "Performing the SSL/TLS handshake...");
        if (has_saved_session) {
             mbedtls_ssl_set_session(&ssl, &saved_session);
        }
        while ((ret = mbedtls_ssl_handshake(&ssl)) != 0)
        {
            if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE)
            {
                ESP_LOGE(TAG, "mbedtls_ssl_handshake returned -0x%x", -ret);
                goto exit;
            }
        }
        ESP_LOGI(TAG, "end handshake");
        // mbedtls_ssl_get_session(&ssl, &saved_session);
        has_saved_session = true;

        ESP_LOGI(TAG, "Verifying peer X.509 certificate...");

        if ((flags = mbedtls_ssl_get_verify_result(&ssl)) != 0)
        {
            /* In real life, we probably want to close connection if ret != 0 */
            ESP_LOGW(TAG, "Failed to verify peer certificate!");
            bzero(buf, sizeof(buf));
            mbedtls_x509_crt_verify_info(buf, sizeof(buf), "  ! ", flags);
            ESP_LOGW(TAG, "verification info: %s", buf);
        }
        else {
            ESP_LOGI(TAG, "Certificate verified.");
        }

        ESP_LOGI(TAG, "Cipher suite is %s", mbedtls_ssl_get_ciphersuite(&ssl));

        ESP_LOGI(TAG, "Writing HTTP request...");

        size_t written_bytes = 0;
        do {
            ret = mbedtls_ssl_write(&ssl,
                                    (const unsigned char *)REQUEST + written_bytes,
                                    strlen(REQUEST) - written_bytes);
            if (ret >= 0) {
                ESP_LOGI(TAG, "%d bytes written", ret);
                written_bytes += ret;
            } else if (ret != MBEDTLS_ERR_SSL_WANT_WRITE && ret != MBEDTLS_ERR_SSL_WANT_READ) {
                ESP_LOGE(TAG, "mbedtls_ssl_write returned -0x%x", -ret);
                goto exit;
            }
        } while(written_bytes < strlen(REQUEST));

        ESP_LOGI(TAG, "Reading HTTP response...");

        do
        {
            len = sizeof(buf) - 1;
            bzero(buf, sizeof(buf));
            ret = mbedtls_ssl_read(&ssl, (unsigned char *)buf, len);

            if(ret == MBEDTLS_ERR_SSL_WANT_READ || ret == MBEDTLS_ERR_SSL_WANT_WRITE)
                continue;

            if(ret == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY) {
                ret = 0;
                break;
            }

            if(ret < 0)
            {
                ESP_LOGE(TAG, "mbedtls_ssl_read returned -0x%x", -ret);
                break;
            }
mbedtls_ssl_session
            if(ret == 0)
            {
                ESP_LOGI(TAG, "connection closed");
                break;
            }

            len = ret;
            ESP_LOGD(TAG, "%d bytes read", len);
            /* Print response directly to stdout as it is read */
            for(int i = 0; i < len; i++) {
                putchar(buf[i]);
            }
        } while(1);

        mbedtls_ssl_close_notify(&ssl);

    exit:
        mbedtls_ssl_session_reset(&ssl);
        mbedtls_net_free(&server_fd);

        if(ret != 0)
        {
            mbedtls_strerror(ret, buf, 100);
            ESP_LOGE(TAG, "Last error was: -0x%x - %s", -ret, buf);
        }

        putchar('\n'); // JSON output doesn't have a newline at end

        static int request_count;
        ESP_LOGI(TAG, "Completed %d requests", ++request_count);

        for(int countdown = 3; countdown >= 0; countdown--) {
            ESP_LOGI(TAG, "%d...", countdown);
            vTaskDelay(1000 / portTICK_PERIOD_MS);
        }
        ESP_LOGI(TAG, "Starting again!");
    }
```
Thanks
