### ISSUE TITLE
Suggestion: Syscall fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [ARMmbed/mbedtls#2944]
Hey Team I'm Yevgeny Pats, founder of [fuzzit](https://fuzzit.dev).

We are currently in beta for a syscall coverage guided fuzzer that works with different RTOS.

Wanted to know if this is something potentially relevant/interesting to you and worth to add a specific support for mbedtls?

Cheers,
Yevgeny

**Comment by yevgenypats** [comment]
friendly ping @Patater @gilles-peskine-arm @yanesca

**Comment by daverodgman** [comment]
Hi Yevgeny,

Thanks for bringing fuzzit to our attention!

Currently we make use of oss-fuzz in mbedtls. It sounds like fuzzit uses a different approach which could be interesting in the future, as the different approach could potentially help find additional issues, but at the moment, we aren't looking to increase our use of fuzzing. It might be something we find time to explore in the future though.

Cheers

Dave
