### ISSUE TITLE
Crypto's headers override TLS's headers

### ISSUE THREAD

**Issue by Ionic** [ARMmbed/mbedtls#2965]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Seen on Linux, but should be platform-agnostic.

**mbed TLS build:**  
Version: 2.19.1 (but, as far as I can tell, also reproducible with 2.18.x)

**Expected behavior** 

`config.h` from embedtls (`include/mbedtls/config.h`) NOT being overwritten

**Actual behavior**  

`crypto/include/mbedtls/config.h` overwrites `config.h`

**Steps to reproduce**

Just by normally building the software.

This is a regression from 2.16.x and below which didn't split out mbedcrypto into a git submodule/different repository.

However, more recent versions do and the `CMakeLists.txt` file in `crypto/include` wants to install all header files in the `mbedtls` subdirectory to the `$destroot/$prefix/include/mbedtls`. Unfortunately, one of those files is crypto's `config.h` file, and since these headers seem to be getting installed after the main header files, the actual `config.h` file is being overwritten.

This causes a lot of trouble, since crypto's `config.h` file doesn't include a lot of macros, such as `MBEDTLS_X509_CRT_PARSE_C` (just as an example).

Note: I haven't checked if there are other files being overwritten as well. There might well be.

**Comment by Xaymar** [comment]
I'm pretty sure this only happens with the CMakeLists.txt build and doesn't happen with the normal makefile. You can work around this (at least on Linux) by targeting very specific parts of mbedtls to install:

```
cmake --build build --target crypto/library/install
cmake --build build --target include/install
cmake --build build --target library/install
```

I'm not sure if this can also be done on Windows, as I'm pretty sure that Windows only has INSTALL unless a makefile generator like Ninja is being used.

**Comment by gemarcano** [comment]
I haven't tried the latest from git, but I used mbedtls-2.19.1.

I tried editing out the lines in `crypto/include/CMakeLists.txt` which control what gets installed from `crypto`. Specifically, I commented out the lines:
```cmake
    install(FILES ${headers}
        DESTINATION include/mbedtls
        PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
```
The top-most Makefile doesn't install these include files, so stopping that install line from executing makes the cmake build behave like the Makefile. The problem with this approach is that because it doesn't seem to install everything under `crypto/include`, including `aes.h`, which one particular program (the Dolphin Wii/Gamecube emulator) requires to build.

As a second experiment, I modified the order of some lines the top-most `CMakeLists.txt`, changing:
```cmake
    add_subdirectory(library)
    add_subdirectory(include)
    add_subdirectory(crypto/library)
    add_subdirectory(crypto/include)
```
to
```cmake
    add_subdirectory(library)
    add_subdirectory(crypto/library)
    add_subdirectory(crypto/include)
    add_subdirectory(include)
```
This order forces the `config.h` from `mbedtls` to be written out and overwrite the example one included in the `crypto` submodule.

With this second change, I can confirm I'm able to build the emulator.

I'm not sure what the correct behavior is supposed to be. A few questions:
 1. Are programs supposed to do something else to get `crypto`'s `aes.h` file now? Or in other words, is `crypto`'s `aes.h` meant to be installed to `include/mbedtls`? Because if so, it currently is not being installed there by the `Makefile`.
 2. Is the `Makefile` not installing enough files (e.g. `crypto`'s includes)?
 3. Are the CMake files installing too much? (I think so, as currently they install `mbedtls`'s includes and then install `crypto`'s includes trampling over `mbedtls`'s `config.h`.

**Comment by Ionic** [comment]
> I'm pretty sure this only happens with the CMakeLists.txt build and doesn't happen with the normal makefile.

Fair. I assumed that a cmake-based build is the default (and really only used) configuration (even on Windows, for that matter). I haven't tested plain Makefile builds.

> I tried editing out the lines in `crypto/include/CMakeLists.txt` which control what gets installed from `crypto`. Specifically, I commented out the lines:

Yeah, I likewise worked this problem around by (only) excluding `crypto`'s `config.h` from being installed in `crypto/include/CMakeLists.txt`:

```
diff -pNur mbedtls-mbedtls-2.19.1-orig/crypto/include/CMakeLists.txt mbedtls-mbedtls-2.19.1/crypto/include/CMakeLists.txt
--- mbedtls-mbedtls-2.19.1-orig/crypto/include/CMakeLists.txt   2019-12-20 09:24:46.806987628 +0100
+++ mbedtls-mbedtls-2.19.1/crypto/include/CMakeLists.txt        2019-12-20 09:25:51.257199271 +0100
@@ -5,6 +5,9 @@ if(INSTALL_MBEDTLS_HEADERS)
     file(GLOB headers "mbedtls/*.h")
     file(GLOB psa_headers "psa/*.h")
 
+    # Don't overwrite the global config.h file!
+    list(REMOVE_ITEM headers "${CMAKE_CURRENT_SOURCE_DIR}/mbedtls/config.h")
+
     install(FILES ${headers}
         DESTINATION include/mbedtls
         PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
```

This said, I don't **know** whether `crypto`'s `config.h` includes directives needed by `crypto` specifically, so I'm wary to recommend it.

> The top-most Makefile doesn't install these include files, so stopping that install line from executing makes the cmake build behave like the Makefile.

Historically, though, `crypto`'s headers were always installed, if I'm not mistaken. They were bundled with the other others, so there was no way (or need) to disable installation. I assume that this is the desired behavior? The (plain) `Makefile` not installing these headers sounds just like yet another bug (even though it works around this one).

**Comment by gemarcano** [comment]
Nice! That's neater than my approach (my CMake is rusty).

And yeah, we probably need to wait to hear from someone with a better understanding of the plan for the `crypto` submodule to determine how that should integrate with the build systems. For my personal purposes I'm fine with my second hack, but this should probably be fixed.

I'm willing to test at least by compiling against Dolphin, so just let me know if anyone wants more information or more testing.

**Comment by elsandosgrande** [comment]
@gemarcano Well, I think that further information on the matter and testing using Dolphin would be useful in these bugs (Gentoo; related to Dolphin failing at mbedtls stuff and the current situation discussed in this ticket): https://bugs.gentoo.org/705036 https://bugs.gentoo.org/705038

Have a nice day!

**Comment by Patater** [comment]
@Ionic Thanks for sharing your patch to fix this issue. Could you please raise a PR to [mbed-crypto](https://github.com/ARMmbed/mbed-crypto) with this fix? We can run our CI on the change, review, and merge from there. Thanks!

**Comment by Patater** [comment]
@Ionic I should note that we'll want to only conditionally remove the config.h. Mbed Crypto needs to continue to work standalone, which means it needs to install its copy of config.h when not used as a submodule of Mbed TLS. You can use `if(USE_CRYPTO_SUBMODULE)` to tell if Mbed Crypto is being built as submodule and then exclude the `config.h` from Mbed Crypto only in that case.

**Comment by Ionic** [comment]
I could, but I wonder whether that's the right fix.

  - As you mentioned, it should only be skipped when being part embedtls itself. That's easy to do.
  - is `crypto`s `config.h` file the only one to sport this issue? Maybe there are other duplicated headers that get overwritten? I haven't checked, though I guess it wouldn't be difficult to do so.
  - What `config.h` file is used when compiling `crypto` (be it is a submodule or standalone)? In the standalone case, since there is no other `config.h` file, it'll be definitely its own `config.h` file. In the submodule case, I'm not sure. It might be `tls`'s  `config.h` file, but it might also be `crypto`'s `config.h` file. What it both files differ? Especially, what if both files differ in an incompatible way and we install a header file does not represent `crypto`'s actual configuration?

**Comment by Patater** [comment]
> is cryptos config.h file the only one to sport this issue?

Possibly `error.h` and `version.h` have the same issue. It'd need looking into.

> What config.h file is used when compiling crypto? In the submodule case, I'm not sure.

In the submodule case, the Makefile will use the TLS `config.h`. It will be compatible. CI for Mbed Crypto tests that the TLS `config.h` will work for it. The TLS `config.h` should be a superset and used for configuring both Mbed TLS and Mbed Crypto.

To test the fix, we need a new test in `all.sh` as well, to prevent regressions. Simply doing a trial CMake install and verifying which headers were used would suffice.

**Comment by marcan** [comment]
Isn't de35f31 backwards? It removes the *main* mbedtls headers, not the *crypto* ones, so it doesn't fix the problem (but rather makes it worse).

**Comment by Ionic** [comment]
Why would you think so? It's in crypto's include subdirectory, not tls's, so... that's a no.

**Comment by marcan** [comment]
Sorry, I didn't realize it was in the crypto subproject. Gentoo pulled that patch in, but it's getting applied to the main include/MakeLists.txt, not the crypto one... because it happens to apply cleanly to that one. I was confused.

**Comment by Ionic** [comment]
Oh, well, I didn't pursue that. I'm generally using Gentoo, but patched the package myself and decided to rather go upstream directly, since it's obviously not a packaging bug. :)

Yeah, what they do is definitely wrong and will... not exactly cause bigger problems than before, but also not fix the issue.

**Comment by marcan** [comment]
It makes things worse inasmuch as now I have to revert the bad patch in my userpatches in addition to adding the correct patch (which is the same one but with /crypto/ in the path) :-)

But yeah, packaging bug here. It's pretty funny how that happened. It was a subproject patch, but happens to apply cleanly to the wrong file too...

**Comment by gilles-peskine-arm** [comment]
[Crypto is no longer a submodule with its own header directory and its own makefiles](https://github.com/ARMmbed/mbedtls/issues/3064), therefore I believe this issue is no longer applicable.

**Comment by gilles-peskine-arm** [comment]
[Crypto is no longer a submodule with its own header directory and its own makefiles](https://github.com/ARMmbed/mbedtls/issues/3064), therefore I believe this issue is no longer applicable.
