### ISSUE TITLE
compile time warning when building net_sockets.h on Android

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#2977]
### Description
- Type: Bug
- Priority: Minor
Raised in the [forum](https://forums.mbed.com/t/how-to-avoid-warning-passing-int-to-parameter-of-type-socklen-t-aka-unsigned-int-converts-between-pointers-to-integer-types-with-different-sign-wpointer-sign/6638) by pii

---------------------------------------------------------------
## Bug

**OS**  
Android

**mbed TLS build:**  
Version: 2.16.3
OS version: Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/

**Expected behavior**   
Build finishes without any warning
**Actual behavior**  
Build warning because neither `#if defined(__socklen_t_defined) || defined(_SOCKLEN_T) ||  \
    defined(_SOCKLEN_T_DECLARED) || defined(__DEFINED_socklen_t)` is defined:
~~~
External/.build_area/mbedtls-2.16.3/library/net_sockets.c:332:37: warning: passing 'int *'
      to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with
      different sign [-Wpointer-sign]
                    (void *) &type, &type_len ) != 0 ||
                                    ^~~~~~~~~
/Users/pi/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/sys/socket.h:311:92: note: 
      passing argument to parameter '__value_length' here
__socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                           ^
External/.build_area/mbedtls-2.16.3/library/net_sockets.c:342:80: warning: passing 'int *'
      to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with
      different sign [-Wpointer-sign]
                                             (struct sockaddr *) &client_addr, &n );
~~~
`getsockopt` receives 'socklen_t *' (aka 'unsigned int *') , however since none of the precompilation checks is defined, `int` is sent as parameter

**Comment by p-i-** [comment]
@RonEld Many thanks for elevating this forum post to an issue.
As I am unfamiliar with this terrain, I didn't feel confident to raise an issue directly.
Happy to provide any assistance, however I may need some guidance. This component is nested deep in the build system of the product I'm developing, so I offer to pass any directed enquiry through to our build maintainer.

**Comment by gilles-peskine-arm** [comment]
`net_sockets.c` tries to detect whether `socklen_t` is declared, and falls back to `int` for older systems that don't have `socklen_t`. But the detection isn't perfect: it depends on nonstandard symbols the libc. We're missing something for Android.

**Comment by gilles-peskine-arm** [comment]
`socklen_t` is POSIX, so checking any system that has (a sufficiently large?) `_POSIX_VERSION` should have `socklen_t`.
