### ISSUE TITLE
undefined reference to mbedtls_md_file 

### ISSUE THREAD

**Issue by alphabeta1212** [ARMmbed/mbedtls#2989]
getting an undefined reference to mbedtls_md_file even if it is defined in the config.h file.

**Comment by gilles-peskine-arm** [comment]
Hi @uddhavdave1,

Please make sure that `MBEDTLS_MD_C` and `MBEDTLS_FS_IO` are defined in `config.h`.

If you're using the shipped `Makefile`, note that after changing `config.h`, you need to run `make clean` then `make` again.
