### ISSUE TITLE
mbedtls_ssl_handshake failed

### ISSUE THREAD

**Issue by Qinch** [ARMmbed/mbedtls#2996]
### Description
- Type:  Question
- Priority: Blocker 
---------------------------------------------------------------

## Question
Hi, I am trying to use mbedtls  instead of openssl on civetweb.
when I call *mbedtls_ssl_handshake* fucntion, the function failed, the mbedtls error message is：
ssl_srv.c:3249: mbedtls_pk_sign() returned -34432 (-0x8680)

log info:
```bash
ssl_tls.c:8084: => handshake
ssl_srv.c:4259: server state: 0
ssl_tls.c:2755: => flush output
ssl_tls.c:2767: <= flush output
ssl_srv.c:4259: server state: 1
ssl_tls.c:2755: => flush output
ssl_tls.c:2767: <= flush output
ssl_srv.c:1211: => parse client hello
ssl_tls.c:2536: => fetch input
ssl_tls.c:2697: in_left: 0, nb_want: 5
ssl_tls.c:2721: in_left: 0, nb_want: 5
ssl_tls.c:2722: ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)
ssl_tls.c:2742: <= fetch input
ssl_tls.c:2536: => fetch input
ssl_tls.c:2697: in_left: 5, nb_want: 517
ssl_tls.c:2721: in_left: 5, nb_want: 517
ssl_tls.c:2722: ssl->f_recv(_timeout)() returned 512 (-0xfffffe00)
ssl_tls.c:2742: <= fetch input
ssl_srv.c:1999: selected ciphersuite: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
ssl_srv.c:2033: <= parse client hello
ssl_srv.c:4259: server state: 2
ssl_tls.c:2755: => flush output
ssl_tls.c:2767: <= flush output
ssl_srv.c:2417: => write server hello
ssl_tls.c:3184: => write handshake message
ssl_tls.c:3343: => write record
ssl_tls.c:2755: => flush output
ssl_tls.c:2774: message length: 68, out_left: 68
ssl_tls.c:2779: ssl->f_send() returned 68 (-0xffffffbc)
ssl_tls.c:2807: <= flush output
ssl_tls.c:3476: <= write record
ssl_tls.c:3320: <= write handshake message
ssl_srv.c:2638: <= write server hello
ssl_srv.c:4259: server state: 3
ssl_tls.c:2755: => flush output
ssl_tls.c:2767: <= flush output
ssl_tls.c:5329: => write certificate
ssl_tls.c:3184: => write handshake message
ssl_tls.c:3343: => write record
ssl_tls.c:2755: => flush output
ssl_tls.c:2774: message length: 793, out_left: 793
ssl_tls.c:2779: ssl->f_send() returned 793 (-0xfffffce7)
ssl_tls.c:2807: <= flush output
ssl_tls.c:3476: <= write record
ssl_tls.c:3320: <= write handshake message
ssl_tls.c:5433: <= write certificate
ssl_srv.c:4259: server state: 4
ssl_tls.c:2755: => flush output
ssl_tls.c:2767: <= flush output
ssl_srv.c:3271: => write server key exchange
ssl_srv.c:3049: ECDHE curve: secp384r1
ssl_srv.c:3249: mbedtls_pk_sign() returned -34432 (-0x8680)
ssl_tls.c:8094: <= handshake
ssl_tls.c:8725: => write close notify
ssl_tls.c:8741: <= write close notify
ssl_tls.c:8934: => free
```

（mbedtls_ssl_handshake rc -34432 UNKNOWN ERROR CODE (8680)  ssl.stat is :4）

 - What is the reason that result in the error msg?
- mbedtls Version: 2.16.2
- OS version: Linux version 4.12.14-94.41-default

**Comment by Qinch** [comment]
ssl_srv.c:3049: ECDHE curve: secp384r1
ssl_srv.c:3249: mbedtls_pk_sign() returned -34432 (-0x8680)

**Comment by vorot** [comment]
This issue was the first google link when I was looking for the reason of `mbedtls_pk_sign() returned -34432 (-0x8680)`.

In my case, the reason was that `MBEDTLS_THREADING_C` was disabled in the multi-threaded application (WinCE, ARM). After re-enabling `MBEDTLS_THREADING_C`, the problem disappeared.

**Comment by Qinch** [comment]
> This issue was the first google link when I was looking for the reason of `mbedtls_pk_sign() returned -34432 (-0x8680)`.
> 
> In my case, the reason was that `MBEDTLS_THREADING_C` was disabled in the multi-threaded application (WinCE, ARM). After re-enabling `MBEDTLS_THREADING_C`, the problem disappeared.

Yes, It works, see another issue #3025

**Comment by gilles-peskine-arm** [comment]
-0x8680 is actually a weird error code because Mbed TLS error codes should be in the range -0x7fff..-1. Of course, if your application's memory is corrupted due to missing synchronization, anything can happen.
