### ISSUE TITLE
Version not updated in 2.16.4?

### ISSUE THREAD

**Issue by hnrkp** [ARMmbed/mbedtls#3004]
It seems 2.16.4 did not update the version to 2.16.4 from 2.16.3. This makes things confusing when you are using the version.h strings to verify that the correct version has been built and linked against. Maybe a new version spin would be good?

**Comment by yanesca** [comment]
Hi @hnrkp,

Thanks for reporting this issue. It is indeed confusing and we would like to have a new release soon to correct the version reporting.

If you need correct version reporting immediately, as a workaround you can take the PR addressing this issue: https://github.com/ARMmbed/mbedtls/pull/2992

Alternatively running
```bash
./scripts/bump_version.sh --version 2.16.4
```
before compilation also works and results in changes identical to the above mentioned PR.

**Comment by hnrkp** [comment]
Thanks! Looking forwards to the new release.
