### ISSUE TITLE
How to return failure when loading intermedate certificate to verify peer

### ISSUE THREAD

**Issue by TerrenceYyang** [ARMmbed/mbedtls#3041]
Hi Mbed TLS team,

## Question

I noticed that when loading intermedate certificate to verify peer, it will also return success because of below case, How can I limit the verification of peer's certificates to root CA? Or I can choose whether to load imtermedate or root certificacte.

int x509_crt_verify_chain()
{
        /* Stop here for trusted roots (but not for trusted EE certs) */
        if( child_is_trusted )
            return( 0 );
}

Thanks,
Terrence

**Comment by yanesca** [comment]
Yes, you can choose to only pass the root CA as trusted and `mbedtls_x509_crt_verify()` won't stop at intermediate certificates and will verify the peer's certificate chain up to the root CA.

There are several ways to control which certificates are considered by `mbedtls_x509_crt_verify()`. You can pass the trusted certificates directly as a parameter (`trust_ca`) or passing a callback function that returns them (`f_vrfy` and `p_vrfy`).

**Comment by TerrenceYyang** [comment]
Hi Yanesca,

But when I load intermedate certificate to verify peer, how to return failure instead on success?

Thanks,
Terrence

**Comment by yanesca** [comment]
Hi Terrence,

I am sorry, I am not sure I understand. So you are passing an intermediate certificate as trusted (`trust_ca`) to `mbedtls_x509_crt_verify()`, is that correct? What is it that you would like to achieve? Under what conditions do you want the function to return failure? When should it return success?

**Comment by TerrenceYyang** [comment]
Hi Yanesca,

I mean how can I limit the verification of peer's certificates to root CA? If I load imtermedate certificate, will report verify failed. Only support root CA.

For example, if server have a certificate chain (A -> B -> C), where C is signed by B, and B is signed by A,  I require that certificate A be loaded as a trusted certificate in order to verify server's certificate chain(A->B->C), if B is loaded, the result will be failed.

Thanks,
Terrence

**Comment by yanesca** [comment]
Hi Terrence,

There is no option in `mbedtls_x509_crt_verify()` to achieve this, but you can check the trusted certificates list for intermediate certificates manually, return failure if it is present and calling `mbedtls_x509_crt_verify()` otherwise.

**Comment by TerrenceYyang** [comment]
Hi Yanesca,

So you mean I can check whether the trusted certificates list is intermediate certificates or not before calling mbedtls_x509_crt_verify() to verify peer's certificate?

Thanks,
Terrence

**Comment by yanesca** [comment]
Hi Terrence,

Yes, I mean that you can check the trusted certificate list for the intermediate certificates. If you find them you can just return failure (if I understand correctly then this is what you want). Alternatively you can remove the intermediate certificates from the trusted certificate list, make sure that the root CA is in the list, and then call `mbedtls_x509_crt_verify()`. In this latter case the whole certificate chain up to the root CA will be verified.

**Comment by yanesca** [comment]
I believe this question was answered, closing it down. Please reopen in case it needs further discussion.
