### ISSUE TITLE
Mbed TLS to drop requirement for a CLA

### ISSUE THREAD

**Issue by danh-arm** [ARMmbed/mbedtls#3054]
The Mbed TLS and Mbed Crypto projects are shortly about to drop their requirement for all contributions to have a CLA. The changes are implemented in these Pull Requests:
https://github.com/ARMmbed/mbed-crypto/pull/369
https://github.com/ARMmbed/mbedtls/pull/3051

After they merged, new contributions must be made under both Apache-2.0 AND GPL-2.0-or-later licenses, to enable LTS (Long Term Support) branches of the software to continue to be provided under either Apache-2.0 OR GPL-2.0-or-later. Contributors must accept the terms
of the Developer Certificate of Origin (DCO) by adding a Signed-off-by: line to
each commit message.

The software on the development branch continues to be provided under
Apache-2.0.

For existing PRs, contributors who have not yet signed the CLA will be asked to resubmit their PR(s) under the new licensing model above. Contributors who have already signed the CLA do not need to resubmit their PR(s).

The intention is that once the current LTS branches expire, the licensing model will change again so that contributions are made under Apache-2.0 only, resulting in a simple inbound=outbound licensing model.

**Comment by mpg** [comment]
The change is effective as of yesterday, when PRs #3051 and ARMmbed/mbed-crypto#369 were merged.
