### ISSUE TITLE
check_headers_in_cpp fails silently in all.sh

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3057]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

In `all.sh`, when running in `--keep-going` (`-k`) mode as we do on the CI, the function `record_status` is fragile: it runs its arguments as a shell command, but with `set -e` effectively disabled. This only has an impact if `record_status` is called on a shell function, which we do exactly once, to call `check_headers_in_cpp` inside `component_build_default_make_gcc_and_cxx`.

The impact is that if `check_headers_in_cpp` detects something that should be treated as a test failure, the failure of the test is not detected.

Sure enough, as @sbutcher-arm noticed, the test currently fails on the CI. From a [recent nightly](https://jenkins-internal.mbed.com/job/mbedtls-release-new/700/execution/node/768/log/):

```
******************************************************************
* build_default_make_gcc_and_cxx: test: verify header list in cpp_dummy_build.cpp 
* Tue Jan 28 21:27:31 UTC 2020
******************************************************************
0a1,12
> aes.h
> aesni.h
> arc4.h
> aria.h
> asn1.h
> asn1write.h
> base64.h
> bignum.h
> blowfish.h
> bn_mul.h
> camellia.h
> ccm.h
1a14,15
> chacha20.h
> chachapoly.h
2a17,19
> cipher.h
> cipher_internal.h
> cmac.h
4a22
> ctr_drbg.h
5a24,32
> des.h
> dhm.h
> ecdh.h
> ecdsa.h
> ecjpake.h
> ecp.h
> ecp_internal.h
> entropy.h
> entropy_poll.h
6a34,43
> gcm.h
> havege.h
> hkdf.h
> hmac_drbg.h
> md.h
> md2.h
> md4.h
> md5.h
> md_internal.h
> memory_buffer_alloc.h
8a46,51
> nist_kw.h
> oid.h
> padlock.h
> pem.h
> pk.h
> pk_internal.h
9a53,65
> pkcs12.h
> pkcs5.h
> platform.h
> platform_time.h
> platform_util.h
> poly1305.h
> psa_util.h
> ripemd160.h
> rsa.h
> rsa_internal.h
> sha1.h
> sha256.h
> sha512.h
15a72,73
> threading.h
> timing.h
20a79
> xtea.h
```

Fortunately nothing more important is going undetected, at least due to this particular failing.

Goals:

* Make sure that a failure of `check_headers_in_cpp` is properly detected.
* Document any usage restrictions on `record_status` and other similar functions.
* Fix the actual problem.

**Comment by gilles-peskine-arm** [comment]
Technical explanation for the bug: `set -e` causes the shell to exit immediately on an error, so normally a failing command exits the script immediately. However, in keep-going mode, we prefer to record failures and move on. `record_status` is one of the tools for recording failures: `record_status foo bar` runs `if foo bar; then <note success>; else <note failure>; fi`, and due to the design of the sh language, `foo bar` runs with `set -e` effectively disabled. Normally the argument of `set -e` is an external command, so the status of `set -e` in the parent shell is irrelevant. But `check_headers_in_cpp` is a function, which thus runs to completion even if a command fails partway through. Here `diff` fails but the subsequent call to `rm` succeeds so the function returns a success status which `record_status` dutifully records.

Simple workaround: add `&&` between the commands in `check_headers_in_cpp`.

**Comment by mpg** [comment]
Ran into it again today, and while looking for this issue to see if it was the same, I noticed the issue was also found months ago: https://github.com/ARMmbed/mbedtls/issues/2570

**Comment by mpg** [comment]
Note: while fixing this, we might want to make the following improvements as well, as they're in the same area:

- add `CXXFLAGS='--std=c++11 -pedantic -Werror -Wall -Wextra -O'` to the make invocation with `TEST_CPP=1` in `component_build_default_make_gcc_and_cxx` in `all.sh`.
- add a component to `all.sh` that exercises `TEST_CPP` with cmake - AFAICS this is currently entirely untested.

**Comment by gilles-peskine-arm** [comment]
Ah, thanks Manuel. Let's clone this one as a duplicate of #2570.
