### ISSUE TITLE
Website certificate improperly configured

### ISSUE THREAD

**Issue by matclab** [ARMmbed/mbedtls#3081]
As reported in [this oss-fuzz issue](https://github.com/google/oss-fuzz/issues/3455), we are unable to download mbedtls via curl:

 `curl https://tls.mbed.org/download/mbedtls-2.16.0-apache.tgz ` says:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
I've got the same problem on several linux distribution (arch linux, ubuntu, debian…)

`curl -v -k ` locally shows :
```
…
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=GB; ST=Cambridgeshire; L=Cambridge; O=Arm Ltd; CN=tls.mbed.org
*  start date: Feb 25 14:42:02 2020 GMT
*  expire date: May 13 15:41:05 2021 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify result: unable to get local issuer certificate (20)
…
```
As chown by https://www.ssllabs.com/ssltest/analyze.html?d=tls.mbed.org the certificate chain is incomplete.

**Comment by danh-arm** [comment]
Thanks for reporting this, @matclab. A recent server config update broke this. I believe it is fixed now.

**Comment by schwabe** [comment]
At least for me wget on the tls.mbed.org domain is working again

**Comment by matclab** [comment]
Works fine here too. 
Thanks !
