### ISSUE TITLE
How to verify the active cipher suite of a TLS and a DTLS connection.

### ISSUE THREAD

**Issue by fwh-dc** [ARMmbed/mbedtls#3089]
### Description
- Type: Question
- Priority: Minor

---------------------------------------------------------------

## Question
Hi,

We are actively using 
```#define MBEDTLS_SSL_CIPHERSUITES MBEDTLS_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384```
to restrict the available ciphersuites. However, we would like to verify that this actually used by the connection. Do you have any logging that can be enabled to verify it or any function calls to use to check the cipher suite?

In addition: 
Can you confirm that the cipher suite restriction also applies to DTLS connections?

Regards,
Frederik

**Comment by gilles-peskine-arm** [comment]
Hi Frederik,

The TLS module can log just about everything if you include `MBEDTLS_DEBUG_C` at compile time and call `mbedtls_debug_set_threshold(3)` (2 is enough in a server) in your application. Relevant log entries looks like this:
```
ssl_cli.c:1924: |3| server hello, chosen ciphersuite: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
ssl_srv.c:2122: |2| selected ciphersuite: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
```

You can also verify externally by looking at the connection with [Wireshark](https://wiki.wireshark.org/TLS).

From your application, you can call `mbedtls_ssl_get_ciphersuite` on the SSL context after the handshake.

**Comment by fwh-dc** [comment]
Hi Gilles,

Thanks. I will use ```mbedtls_ssl_get_ciphersuite``` to verify.

Can you confirm that the cipher suite restriction also applies to DTLS connections? I'm assuming it does, but I'm not 100% certain.

Regards,
Frederik

**Comment by gilles-peskine-arm** [comment]
Yes, ciphersuite restrictions and other configurations apply to all SSL/TLS/DTLS versions.
