### ISSUE TITLE
The certificate is signed with an unacceptable key (eg bad curve, RSA too short).

### ISSUE THREAD

**Issue by Luke9966** [ARMmbed/mbedtls#3095]
# Description
I regenerated mbedtls certificate with 2048length,and rsa-256, but now I get get a validation error on the server cert:
Verifying peer X.509 certificate... failed
! The certificate is signed with an unacceptable key (eg bad curve, RSA too short).
Could you help me?

**Comment by gilles-peskine-arm** [comment]
By “rsa-256”, do you mean a 2048-bit key? 2048 bits is 256 bytes but it's very uncommon to measure the size of an RSA key in bytes.

If that's not the problem, I don't know what could be wrong. We could help more if you posted the exact way you generated the key and the certificate, and exactly how you're using them.

**Comment by Luke9966** [comment]
Thanks！I am so sorry that it is SHA256 not ras256. I generated the key and the cerficate by using the commands：
openssl req -new -x509 -sha256 -keyout ca.key -out ca.crt 
openssl genrsa -out client.key 2048
openssl req -new -sha256 -key client.key -out client.csr
openssl genrsa -out server.key 2048
openssl req -new -sha256 -key server.key -out server.csr
openssl ca -in server.csr -md sha256 -out server.crt -cert ca.crt -keyfile ca.key
openssl ca -in client.csr -md sha256 -out client.crt -cert ca.crt -keyfile ca.key 
In my code, I loaded the certificate and the key by using codes:
mbedtls_x509_crt_parse( &cacert, (const unsigned char *) mbedtls_ca,                                                                strlen(mbedtls_ca)+1);
mbedtls_x509_crt_parse( &srvcert, (const unsigned char *) mbedtls_server,
                          strlen(mbedtls_server)+1);
mbedtls_pk_parse_key( &pkey, (const unsigned char *) mbedtls_srv_key,
                         strlen (mbedtls_srv_key)+1, NULL, 0 );
mbedtls_ssl_conf_ca_chain( &conf,  &cacert, NULL );
if( ( ret = mbedtls_ssl_conf_own_cert( &conf, &srvcert, &pkey ) ) != 0 )
    {
        mbedtls_printf( " failed\n  ! mbedtls_ssl_conf_own_cert returned %d\n\n", ret );
        goto exit;
    }
Could you help me?

**Comment by gilles-peskine-arm** [comment]
I can't see anything wrong in this code. Are both your client and your server using Mbed TLS? How did you configure them at build time? A 2048-bit RSA key with SHA-256 used for the signature is accepted by default in the default build-time configuration, but maybe you're using a more restrictive build?

**Comment by Luke9966** [comment]
Thanks! Could you give me some advice about the certificates and keys under file folder /mbedtls/tests/data_files? I want to use the  certificates and keys given by mbedtls and have a try.

**Comment by gilles-peskine-arm** [comment]
The certificates in `tests/data_files` are for testing. Beware that some of them are for negative tests, so not all of them are expected to work. To generate certificates, it's usually easier to follow recipes found online that use `openssl`.

The most likely problem is that your compile-time configuration is missing a necessary algorithm, or that you've set a policy that doesn't allow this particular algorithm combination. But these are only guesses. It may help if you run build mbedtls with debugging enabled, set a breakpoint on `x509_profile_check_key` in `x509_crt.c` and look at the exact path inside this function.
