### ISSUE TITLE
problem with compiling visual c projects

### ISSUE THREAD

**Issue by hamidkavianathar** [ARMmbed/mbedtls#3104]
### Description
some header files are missing.  I also could not find them in mbedTLS file's list.
#include "mbedtls/asn1.h"
#include "mbedtls/pk.h"

**Comment by paul-elliott-arm** [comment]
Hi! 

These are both under the crypto/include/mbedtls directory. If those are not present, are you sure you cloned the project with --recursive ?

**Comment by gilles-peskine-arm** [comment]
Do you still have this problem with the latest mbedtls development branch? The crypto files have been merged back into the toplevel directory, there is no more crypto submodule.

**Comment by hamidkavianathar** [comment]
hi thanks for your attention. I do not have this problem anymore.
