### ISSUE TITLE
"mbedtls_ecdh_gen_public" returning -16 during server key exchange message

### ISSUE THREAD

**Issue by RoshDevi** [ARMmbed/mbedtls#3110]
Type - "mbedtls_ecdh_gen_public" returning -16 during server key exchange message
Hello, 
I am using mbedTLS 2.16.3 version.
Currently, I am using DTLS.
I am working stm32 boards. 
I have successfully parsed public, private key , configuration cookies etc, 
Now, once I start my DTLS handshake, I am able to see client hello request from client.
And server is sending "Hello verify request".
And client is sending "client hello request along with cookie sent in the previous handshake message"
Now, when I debug inside the code - I am able to see it successfully parsed client hello.
It is constructing the server hello, certificate messages. So far everything is good,
Next step is to construct - server key exchange message. 
It is failing over there. The cipher suite chosen needs to prepare server key exchange message and curve selected is MBEDTLS_ECP_DP_SECP521R1. I have enabled the corresponding macro also. 

The failure is exactly at - "mbedtls_ecdh_gen_public" is returning -16. 
I am struck at this point for a week. Not able to decode where the problem is. And also  not sure return code -16 corresponds to what error message.

Note - Since I am using embedded platform, I have hardware entropy. Till now I haven't registered timer callback function. Is it due to that?

**Comment by gilles-peskine-arm** [comment]
> And also not sure return code -16 corresponds to what error message.

You can use the utility `programs/util/strerror` that comes with Mbed TLS. The error codes are the same on every platform and in every configuration, so even if you're making a cross-compiled build with a restricted configuration, you can compile Mbed TLS separately for your host platform to get this utility.

```
$ ./programs/util/strerror 16
Last error was: -0x0010 - BIGNUM - Memory allocation failed
```
So I'm afraid you're running out of memory.

**Comment by RoshDevi** [comment]
- So I'm afraid you're running out of memory.

Thanks a lot. I have increased the heap memory and it solved the problem.
