### ISSUE TITLE
Pylint may invoke Python2 pylint

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3111]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

Since https://github.com/ARMmbed/mbedtls/pull/3100, `all.sh check_python_files` fails on systems that have both Python 2 including `pylint` and Python 3 including `pylint3`. Python 2 is no longer upported, but it's too early to assume that everybody has uninstalled it.

For at least a few months, we should prefer `pylint3` to `pylint`.

**Comment by sbutcher-arm** [comment]
Are you sure @gilles-peskine-arm this isn't just an issue specific to your system? What is the default preferred version of Python on your machine? Is it Python 2 or 3?

Also, surely `all.sh` is a CI script to be executed in a specific controlled environment? Hence why the versions are so carefully selected.

**Comment by gilles-peskine-arm** [comment]
My system is Ubuntu 16.04 or Ubuntu 18.04, which are the systems that the CI runs. Ubuntu 18.04 is the latest LTS release of Ubuntu (only for another month or so, granted). [Ubuntu](https://packages.ubuntu.com/search?keywords=pylint) ships `/usr/bin/pylint` for Python 2 up to 19.04, and for Python 3 since 19.10.

Ubuntu follows [PEP 394](https://www.python.org/dev/peps/pep-0394/), which [until April 2018](https://github.com/python/peps/commit/cd59ec03c8ff1e75089d5872520cd0706774b35b#diff-1d22f7bd72cbc900670f058b1107d426) requires that `python` refer to Python 2. PEP 394 also requires that associated commands like `idle` and `python-config` are for `python` and `python3-idle` for `python3`, etc. It doesn't mention third-party commands like `pip` and `pylint` explicitly, but I'd expect them to follow the same guideline.

The current state of `all.sh` is fragile. It only works because the package `pylint` is not installed.
