### ISSUE TITLE
Valgrind reports memory leak in mbedtls_x509_...

### ISSUE THREAD

**Issue by dejanyy** [ARMmbed/mbedtls#3112]
Type: Possibly a Bug
OS: **mbedtls-2.16.5 on Linux**

Valgrind reports a memory leak which seem to be caused by a call to the **mbedtls_x509_crt_parse_file** function. The documentation does not mention that the caller is required to release any memory allocated by this function. Thus, we are assuming, the function is leaking memory i.e. this might be a bug.  Below is Valgrind's output, which is generated at the end (i.e. after our app cleanly closes):

==14637== 3,714 (192 direct, 3,522 indirect) bytes in 3 blocks are definitely lost in loss record 9 of 9
==14637==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==14637==    by 0x4D1336: mbedtls_x509_get_name (in /home/exec/server-linux)
==14637==    by 0x4CFE74: mbedtls_x509_crt_parse_der (in /home/exec/server-linux)
==14637==    by 0x4D095C: mbedtls_x509_crt_parse (in /home/exec/server-linux)
==14637==    by 0x4D09DF: mbedtls_x509_crt_parse_file (in /home/exec/server-linux)
==14637==    by 0x496FE4: RunServer() (in /home/exec/server-linux)
==14637==    by 0x4A5A19: Run() (in /home/exec/server-linux)
==14637==    by 0x4A669E: server_web(char const*, char const* const*) (in /home/exec/server-linux)
==14637==    by 0x4069CC: main (in /home/exec/server-linux)

**Comment by gilles-peskine-arm** [comment]
Is this a success or error case? Would you be able to share a small, complete program that reproduces the problem?

We do run our test suite with valgrind, but of course that only catches conditions that the test cases hit.

**Comment by dejanyy** [comment]
After some debugging, I discovered the bug was in my code. In addition to the server certificate I also had a CAChain certificate (initialized using mbedtls_x509_crt_init) which was not released at the end of the program by calling mbedtls_x509_crt_free. As soon as I fixed that, the memory leak was gone.

Attached is a test program I used to troubleshoot and find my bug. Feel free to use it in your own testing if you'd like.

[testprog.txt](https://github.com/ARMmbed/mbedtls/files/4379118/testprog.txt)

Running it under Valgrind generates a completely clean report without any memory leaks.

==4595== HEAP SUMMARY:
==4595==     in use at exit: 0 bytes in 0 blocks
==4595==   total heap usage: 39 allocs, 39 frees, 99,482 bytes allocated
==4595== 
==4595== All heap blocks were freed -- no leaks are possible
==4595== 
==4595== For counts of detected and suppressed errors, rerun with: -v
==4595== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Sorry about this false alarm. The bug report can be closed.
