### ISSUE TITLE
prevent SIGPIPE to end the process

### ISSUE THREAD

**Issue by anibalportero** [ARMmbed/mbedtls#3116]
## Question

Hi,

SIGPIPE is handled with a signal( SIGPIPE, SIG_IGN ) in mbedtls_net_connect. While the examples in programs/ssl/ssl_client1.c or programs/ssl/ssl_client2.c are calling mbedtls_net_connect, programs/ssl/mini_client.c is not, and therefore not changing the default behavior of SIGPIPE.

Our client is based on mini_client.c. What would the best way to handle SIGPIPE? Would it be worth it to add signal( SIGPIPE, SIG_IGN ) to the mini_client.c example for future reference? maybe even make net_prepare() visible from outside so a mini client like application can use it?

Thanks!

**Comment by danh-arm** [comment]
Hi @anibalportero. We've recently migrated Mbed TLS to TrustedFirmware.org. Could you direct this question to the new [Mbed TLS mailing list](mailto:mbed-tls@lists.trustedfirmware.org)? Thanks.

**Comment by danh-arm** [comment]
Question now posted on mailing list - closing
