### ISSUE TITLE
OID descriptor name typo for Extended Key Usage

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#314]
In mbed TLS 2.1.1 I think there is a typo in the OID descriptor name for Extended Key Usage (line 270 of library/oid.c). It says "id-ce-keyUsage" but it should say "id-ce-extKeyUsage".

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSSL-467

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-510
