### ISSUE TITLE
TLS context serialization: can it be done?

### ISSUE THREAD

**Issue by dimakuv** [ARMmbed/mbedtls#3141]
### Description
- Type: Question
- Priority: Minor

## Question

mbedTLS v2.21.0 has support for TLS context serialization in the form of two functions: `mbedtls_ssl_context_save()` and `mbedtls_ssl_context_load()`. I'm trying to use these functions in another project (Graphene, an Intel SGX framework). Slightly oversimplifying, I want to establish a secure communication channel between two different Linux processes. I'd like to persist one of them and then re-spawn it again with the communication channel intact (so that there is no need for a new TLS handshake).

However, I notice that currently these functions support only DTLS 1.2, see e.g.: https://github.com/ARMmbed/mbedtls/blob/aaabe86ac1f47193f4fc499846a0b3abeae9207b/library/ssl_tls.c#L5954

But I want to use a normal TLS channel, in particular with a ciphersuite `MBEDTLS_TLS_PSK_WITH_AES_128_GCM_SHA256`.

I commented out the checks on DTLS in these functions just to see what will happen. As expected, both functions serialized and then deserialized the context, but when doing a `write(ssl_ctx)` in one (not-persisted) process  and a `read(loaded_ssl_ctx)` in another (re-spawned) process, I get an error in `mbedtls_cipher_auth_decrypt()`. Clearly, my deserialized context didn't restore some vital information on the TLS session, and this led to failure in decryption.

Thus, I have two questions:
1. Is there any version of this code that also works on TLS?
2. What are the additional internal objects that must be serialized for TLS (if it makes things easier, in my particular case with AES-GCM and a pre-shared key)? I looked at the code and tried to dump more fields in `mbedtls_ssl_transform`, but it didn't help much. If you'd provide me with some pointers, I could tinker more with mbedTLS code and hopefully make it work.

**Comment by danh-arm** [comment]
Hi @dimakuv . We've recently migrated Mbed TLS to TrustedFirmware.org. Could you direct this question to the new [Mbed TLS mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) instead? Thanks.

**Comment by dimakuv** [comment]
Thanks @danh-arm, done. Should I close this issue here on GitHub?

**Comment by danh-arm** [comment]
> Should I close this issue here on GitHub?

Yes but don't worry, I've done it! Thanks

**Comment by DanielG** [comment]
Just going to leave links to the ML thread here:
- https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-March/000004.html
- https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000007.html

**Comment by dimakuv** [comment]
@DanielG The links do not work anymore.
