### ISSUE TITLE
mbedtls_base64_encode reports different olen's when used for size checking and when encoding

### ISSUE THREAD

**Issue by fwh-dc** [ARMmbed/mbedtls#3151]
#Question

Hi,

I don't understand why mbedtls_base64_encode returns different olen's for the same source buffer. See example below:

```
    uint8_t s[10];
    uint8_t d[17];
    size_t sz;
    int ret;
    ret = mbedtls_base64_encode(NULL, 0, &sz, s, 10);
    // returns sz == 17
    ret = mbedtls_base64_encode(d, 17, &sz, s, 10);
    // returns sz == 16
```
Shouldn't it be the same?

**Comment by danh-arm** [comment]
Hi @fwh-dc. Can you ask this question on the new [Mbed TLS list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)?

**Comment by fwh-dc** [comment]
Yes, but currently I am getting "Error code: SSL_ERROR_NO_CYPHER_OVERLAP" when accessing the mailing list subscription page. I don't know were to report that bug. It is consistent across Firefox, Chrome and Safari.

**Comment by fwh-dc** [comment]
I have posted the question to the mailing list now.

**Comment by WayneKeenan** [comment]
The list link is 404. where should we look now?

**Comment by gilles-peskine-arm** [comment]
@WayneKeenan The web interface URLs changed a while back due to an upgrade of the mailing list management software. It's now at https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/
