### ISSUE TITLE
When you support tls version 1.3？

### ISSUE THREAD

**Issue by husttb** [ARMmbed/mbedtls#3154]

**Comment by danh-arm** [comment]
Hi @husttb . Can you ask this question on the new [Mbed TLS list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)?

**Comment by mpg** [comment]
By the way, there was an older ticket which has some information (near the end) that you might find useful too: https://github.com/ARMmbed/mbedtls/issues/508#issuecomment-601258457

**Comment by danh-arm** [comment]
I'm closing this since the question is answered and we're trying not to use the issue tracker for questions anymore.
