### ISSUE TITLE
X.509 boolean values recognized on Windows and Linux, but not on OS X

### ISSUE THREAD

**Issue by jleroy** [ARMmbed/mbedtls#318]
I've created a self-signed CA with the `mbedtls_cert_write` command. This certificate works on Windows 10 and Fedora 21, but not on OS X 10.11 (El Capitan). 

The Basic Constraints extension critical flag is recognized on Windows, Linux, and with `openssl` command on Mac OS X 10.11, but not by OS X Keychain app: 

<img width="568" alt="criticalflagosx" src="https://cloud.githubusercontent.com/assets/671734/10420055/310d9dc0-7089-11e5-877b-9b7c61bccf77.png">

Also, the `CA` flag is not recognized on OS X.
Maybe OS X is expecting a value of `0xff` (255) for `TRUE`, not `1` ?

**Comment by NWilson** [comment]
In `mbedtls_asn1_write_bool`, BOOLEAN is written out with a 1. In BER, any non-zero value is 'true', but in DER, only 0xff is permitted.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSSL-465

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-508

**Comment by jleroy** [comment]
@rainierwolfcastle FYI this bug is fixed by PR #320.
