### ISSUE TITLE
Is assignment necessary in mbedtls_ssl_parse_certificate?

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#3182]
https://github.com/ARMmbed/mbedtls/blob/66e21efe47f9df0f5a9fe71cd86a20b7dc2f6fdc/library/ssl_tls.c#L2748-L2751
Return value `ret` cannot be non-zero here, therefore assignment and the check could be changed to
```
 if( authmode != MBEDTLS_SSL_VERIFY_OPTIONAL ) 
     ret = MBEDTLS_ERR_SSL_NO_CLIENT_CERTIFICATE; 
```

**Comment by danh-arm** [comment]
Hi @irwir . You are correct, although I imagine the compiler will make the necessary optimization. Would you like to submit a PR for the change you suggested?
