### ISSUE TITLE
Wrong AES-CCM tag calculation

### ISSUE THREAD

**Issue by ahpohl** [ARMmbed/mbedtls#3186]
### Description
- Type: Bug
- Priority: Minor

The tag calculated with `mbedtls_ccm_encrypt_and_tag()` does not match the expected tag for the NIST `#25` test vector. Hence the call to `mbedtls_ccm_auth_decrypt()` fails when using the tag given in the test vector.

---------------------------------------------------------------
## Bug

**OS** 
Linux

**mbed TLS build:**  
Version: 2.16.5-1
OS version: Arch Linux (up-to-date)

**Expected behavior**  
 ```
Name       : AES-128 CCM NIST #25 
Key        : F9FDCA4AC64FE7F014DE0F43039C7571
Iv         : 5A8AA485C316E9
Cipher     : 6BE31860CA271EF448DE8F8D8B39346DAF4B81D7E92D65B3
Plaintext  : A265480CA88D5F536DB0DC6ABC40FAF0D05BE7A966977768
Tag        : 38F125FA

Crypto++   : Encrypted and verified data
Cipher     : 6BE31860CA271EF448DE8F8D8B39346DAF4B81D7E92D65B3
Tag        : 38F125FA

Crypto++   : Decrypted and verified data
Plaintext  : A265480CA88D5F536DB0DC6ABC40FAF0D05BE7A966977768
```
**Actual behavior** 
 ```
  CCM-AES #1: passed
  CCM-AES #2: passed
  CCM-AES #3: passed

Name       : AES-128 CCM NIST #25
Key        : F9FDCA4AC64FE7F014DE0F43039C7571
Iv         : 5A8AA485C316E9
Cipher     : 6BE31860CA271EF448DE8F8D8B39346DAF4B81D7E92D65B3
Plaintext  : A265480CA88D5F536DB0DC6ABC40FAF0D05BE7A966977768
Tag        : 38F125FA

MbedTLS    : Encryption successful
Ciphertext : 6BE31860CA271EF448DE8F8D8B39346DAF4B81D7E92D65B3
Tag        : FC24CF6A

MbedTLS    : Authenticated decryption failed.
Plaintext  : 000000000000000000000000000000000000000000000000
```
**Steps to reproduce**  
Test code [mbedtls.c](https://github.com/ahpohl/xiaomi_lywsd03mmc/blob/mbedtls/resources/mbedtls.c) with MbedTLS and [cryptopp.cpp](https://github.com/ahpohl/xiaomi_lywsd03mmc/blob/mbedtls/resources/cryptopp.cpp) with Crypto++ for comparison.

Compile:
```
gcc -g -o mbedtls mbedtls.c -lmbedcrypto
g++ -g -o cryptopp cryptopp.cpp -lcryptopp
```

**Comment by gilles-peskine-arm** [comment]
[This exact test vector is in the Mbed TLS test suite](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.16.0/tests/suites/test_suite_cipher.ccm.data#L99) and it passes. So what's the bug supposed to be?

**Comment by ahpohl** [comment]
Hi, I found the problem with the tag calculation. Its actually just a mistake in my test code [mbedtls.c](https://github.com/ahpohl/xiaomi_lywsd03mmc/blob/mbedtls/resources/mbedtls.c).

In the call of `mbedtls_ccm_encrypt_and_tag()` I was using `testVectorCCM.datasize`. I should have used `testVectorCCM.authsize` instead.

I close the issue.

**Comment by gilles-peskine-arm** [comment]
No worries, glad you found the problem!
