### ISSUE TITLE
dependence from mbed-crypto no more?

### ISSUE THREAD

**Issue by KammutierSpule** [ARMmbed/mbedtls#3187]
I was using mbedtls with the mbed-crypto dependence.

I just updated now to the current master and it is not using the mbed-crypto as dependence.. did I miss something? did it changed again?

**Comment by gilles-peskine-arm** [comment]
Indeed, [Mbed Crypto has been merged back into Mbed TLS](https://github.com/ARMmbed/mbedtls/issues/3064).
