### ISSUE TITLE
Possible null pointer in ssl_decrypt_encrypted_pms

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#3201]
https://github.com/ARMmbed/mbedtls/blob/5f69cbe2ccf9477bb484c6f27d8a9a5719d6ad1c/library/ssl_srv.c#L3632
The code looks unsafe because `NULL` could be returned from `mbedtls_ssl_own_cert( ssl )`.

**Comment by gilles-peskine-arm** [comment]
This function is only called from an SSL connection at the step `MBEDTLS_SSL_CLIENT_KEY_EXCHANGE`, for an RSA or RSA-PSK ciphersuite. To reach this step, the server has to first go through all previous steps including `MBEDTLS_SSL_SERVER_CERTIFICATE` which calls `mbedtls_ssl_write_certificate`. In a ciphersuite that requires a certificate, if `mbedtls_ssl_own_cert( ssl )` is null, this function errors out.

So I don't see how `mbedtls_ssl_own_cert( ssl )` could return `NULL` at this point.

**Comment by irwir** [comment]
Should be good enough then.
Thanks for checking the issue.
