### ISSUE TITLE
md.c: same actions in switch statements

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#3202]
There are several places in `md.c` where exactly the same operators are performed in `switch` statements for different kinds of hashes.
For example:
https://github.com/ARMmbed/mbedtls/blob/5f69cbe2ccf9477bb484c6f27d8a9a5719d6ad1c/library/md.c#L561-L566
The suggestion is to leave the upper case empty (delete the line 563 in the given example).
That would clear the warnings that two cases execute the same action.

**Comment by danh-arm** [comment]
Hi @irwir. You are correct. Would like to contribute a change to this effect?
