### ISSUE TITLE
Superfluous code in mbedtls_ssl_set_hs_psk

### ISSUE THREAD

**Issue by guidovranken** [ARMmbed/mbedtls#321]
https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L5737

```C
    if( ( ssl->handshake->psk = mbedtls_calloc( 1, psk_len ) ) == NULL )
    {
        mbedtls_free( ssl->handshake->psk );
        ssl->handshake->psk = NULL;
        return( MBEDTLS_ERR_SSL_ALLOC_FAILED );
    }
```
```ssl->handshake->psk``` doesn't need to be freed because it's not allocated (it's ```NULL```), and ```ssl->handshake->psk``` doesn't need to be set to ```NULL``` because it's already ```NULL```.

Guido

**Comment by mpg** [comment]
Right. Thanks!
