### ISSUE TITLE
Testing of psa_import_key API 10 - Delete transaction temporary file

### ISSUE THREAD

**Issue by ronald-cron-arm** [ARMmbed/mbedtls#3228]
The import of a key in a SE involves the creation of several persistent data and a clean-up of those persistent data is necessary if the import does not proceed until the end because of a reset of the system. Thus, the creation in internal storage of a temporary file to mark the beginning of persistent data operation to import a key. At the end of the import sequence, the file is deleted.

The goal of this task is to tests the case where:
1) The deletion of the temporary file is interrupted by a system reset resulting in a corrupted file.

**Comment by gilles-peskine-arm** [comment]
Isn't this covered by #3171? Deletion is supposed to be atomic.

**Comment by ronald-cron-arm** [comment]
Not covered by #3171 but you are right from the point of view of psa_import_key, internal storage operation can be considered as atomic. The issues that can arise if the system is reset while a internal storage operation is on-going have to be dealt with by the internal storage module. Thus I am closing this issue.
