### ISSUE TITLE
Branch with the latest release but not day-to-day development

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3231]
As a user or distributor of Mbed TLS, I want to follow a branch of the repository which is updated when there is a new official release of the library (i.e. one with a version number) but is not updated on a daily basis, so that I can keep up with bug fixes and new features but I have a well-known reference point and I don't get updates on a daily basis.

In the past, the [`master`](https://github.com/ARMmbed/mbedtls/tree/master) branch was this , but it's now following the 2.16 long-time support branch, not the releases made on the development branch.

**Comment by danh-arm** [comment]
I'm not convinced of the need for us to maintain a branch that follows releases in the long term (see #3370) but in the short term we definitely should be updating `master` to follow the releases in the `development` branch rather than the latest LTS branch. This issue will track fixing that.

**Comment by yanesca** [comment]
We have announced the change and force pushed the master branch to address this.
