### ISSUE TITLE
Broken archive on tls.mbed.org

### ISSUE THREAD

**Issue by robotanarchy** [ARMmbed/mbedtls#324]
Is it just me, or is this archive broken?

https://tls.mbed.org/download/start/mbedtls-2.1.2-apache.tgz

**Comment by mpg** [comment]
Broken how? I just downloaded it, and was able to untar it, ran make, no error.

    % tar --version
    bsdtar 2.8.3 - libarchive 2.8.3
    % tar xf mbedtls-2.1.2-apache.tgz
    % echo $?
    0

**Comment by robotanarchy** [comment]
Sorry, my mistake >_> I've assumed that the link I've posted is the direct download link because of the file extension :confused:

**Comment by mpg** [comment]
Oh, I see. That's a bit confusing indeed.
