### ISSUE TITLE
Implement one-shot hash, MAC and cipher

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3258]
Implement one-shot hash, MAC and cipher APIs introduced in PSA Crypto API 1.0 beta1 (https://github.com/ARMmbed/mbed-crypto/pull/17).

* `psa_hash_compute`, `psa_hash_compare` — done in https://github.com/ARMmbed/mbed-crypto/pull/327
* `psa_mac_compute`, `psa_mac_verify`
* `psa_cipher_encrypt`, `psa_cipher_decrypt`

**Comment by hanno-arm** [comment]
(Apologies, moved this by accident).

**Comment by mpg** [comment]
Note: when adding those functions, make sure to also add tests that validate the related size macros introduced in #3386.

**Comment by gabor-mezei-arm** [comment]
Already planned that: https://github.com/ARMmbed/mbedtls/pull/4182#issuecomment-788080140.
