### ISSUE TITLE
Implement the openless crypto API

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3265]
Mbed Crypto currently implements version 1.0 beta 3 of the PSA Crypto API. In the final version of the API, there has been one major change to key management. Now, instead of calling `psa_open_key` on a persistent key identifier to obtain a transient handle to the key, the application directly uses the identifier as a handle. This is not yet possible in Mbed Crypto.

The goal of this task is to implement the openless API:

* Use `psa_key_id_t` wherever the API currently has `psa_key_handle_t`.
* Since `psa_key_id_t` is not restricted to a small range, there needs to be more indirection in the equivalent function to `psa_get_key_slot` for key ids. Possible methods include:
    * A linear search in the existing table `global_data.key_slots`.
    * Another table mapping key ids to indices in `global_data.key_slots`.
* Implement the new function `psa_purge_key`.
* Add tests that exercise the new behavior. It's ok to keep calls to the old functions in most existing tests.

The behavior if a key is purged while a multipart operation is in progress is out of scope of this task and tracked separately at https://github.com/ARMmbed/mbed-crypto/issues/86. However, there are commonalities in the design, so a prerequisite of this task is to [come up with a design that's compatible with both problems](https://github.com/ARMmbed/mbedtls/issues/3292).

For backward compatibility, keep the following declared in `include/psa/crypto_compat.h`:
* `psa_open_key` either as a function that only checks whether the key exists, or essentially as today (loading the key into memory).
* `psa_close_key` at least calls `psa_purge_key`.
* `psa_key_handle_t` is an alias of `psa_key_id_t`.

**Comment by ronald-cron-arm** [comment]
#3527 merged but not #3547 thus reopening this issue.
