### ISSUE TITLE
Use PSA_ERROR_DATA_INVALID where warranted

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3275]
Version 1.0.0 of the PSA Crypto API 1.0.0 added a new error code `PSA_ERROR_DATA_INVALID` which is distinct from ` PSA_ERROR_DATA_CORRUPT` and `PSA_ERROR_STORAGE_FAILURE`.

The goal of this task is to change the relevant PSA crypto storage-related code and documentation to return `PSA_ERROR_DATA_INVALID` where warranted, and update or add tests accordingly.

**Comment by gabor-mezei-arm** [comment]
In what cases should the PSA_ERROR_DATA_INVALID be used?

**Comment by gilles-peskine-arm** [comment]
https://armmbed.github.io/mbed-crypto/html/api/library/status.html?highlight=psa_error_data_invalid#c.PSA_ERROR_DATA_INVALID

> This error indicates that some data read from storage does not have a valid format.

If the ITS subsystem fails to read a file, it should return `PSA_ERROR_DATA_CORRUPT` or `PSA_ERROR_STORAGE_FAILURE`. If the file is read correctly, but it contains data that isn't valid, the crypto storage code should return `PSA_ERROR_DATA_INVALID`. Without checking, I think that means changing every place outside `psa_crypto_its.c` that returns `PSA_ERROR_DATA_CORRUPT` or `PSA_ERROR_STORAGE_FAILURE` to `PSA_ERROR_DATA_INVALID`.
