### ISSUE TITLE
question: mbedtls_ssl_read() API usage

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#3280]
Regarding mbedtls_ssl_read() return values and what "it means":

__1.__ What's the server condition that requires a new handshake, specifically when  ```MBEDTLS_ERR_SSL_CRYPTO_IN_PROGRESS``` is returned ?, is this a normal situation ?

https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c#L2922

__2.__ What's the scenario that mbedtls_ssl_read() might return ```MBEDTLS_ERR_SSL_WANT_WRITE``` ?, if my socket is asynchronous and I am only asking mbedtls to read, why it might need to write ?:

https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c#L2927 

if  ```MBEDTLS_ERR_SSL_WANT_WRITE``` is returned, calling mbedtls_ssl_read() again is enough ?

**Comment by hanno-arm** [comment]
Hi @edsiper. Can you ask this question on the new [Mbed TLS list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)?

**Comment by edsiper** [comment]
sent (pending approval)
