### ISSUE TITLE
Test failures (psa_its-suite, psa_crypto_slot_management-suite)

### ISSUE THREAD

**Issue by thesamesam** [ARMmbed/mbedtls#3291]
## Description
- Type: Bug
- Priority: Normal

I've attached all of the info that seems useful. Please let me know if I should provide anything more.

## Bug

**OS**  
Gentoo Linux (downstream [bug](https://bugs.gentoo.org/718390))

**mbed TLS build:**  
Version: 2.22.0  
OS version: Gentoo Linux (see [here](https://github.com/ARMmbed/mbedtls/files/4548958/info.txt) for a full `emerge --info`, including kernel version)
Configuration: [config.h](https://github.com/ARMmbed/mbedtls/files/4548966/config.h.txt)
Compiler and options:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/gcc-9.2.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/9.2.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/python --enable-languages=c,c++ --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --disable-nls --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 9.2.0-r2 p3' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-systemtap --enable-vtable-verify --disable-libquadmath --enable-lto --with-isl --disable-isl-version-check --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 9.2.0 (Gentoo Hardened 9.2.0-r2 p3)
```

```
[ebuild U] net-libs/mbedtls-2.22.0:0/13::gentoo [2.19.1-r2:0/13::gentoo] USE="test threads -doc -havege -libressl -programs -static-libs -zlib" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2" 0 KiB
```

**Logs**:
- Full [build.log](https://github.com/ARMmbed/mbedtls/files/4548987/build.log)
- [LastTest.log](https://github.com/ARMmbed/mbedtls/files/4548990/LastTest.log)

**Expected behavior**   
All tests pass / failing tests are XFAILed only.

**Actual behavior**  
The following tests FAILED:
         76 - psa_crypto_slot_management-suite (Failed)
         77 - psa_its-suite (Failed)
Errors while running CTest

**Steps to reproduce**  
Build mbed TLS with tests enabled.

**Comment by gilles-peskine-arm** [comment]
I see in the build logs:

```
>>> Unpacking mbedtls-2.22.0.tar.gz to /var/tmp/portage/net-libs/mbedtls-2.22.0/
work
>>> Unpacking mbedcrypto-3.1.0.tar.gz to /var/tmp/portage/net-libs/mbedtls-2.22.
0/work
```

But Mbed TLS no longer uses Mbed Crypto since the 2.22 release: [Mbed Crypto](https://github.com/ARMmbed/mbed-crypto/issues/374) has been merged back into Mbed TLS. Maybe there's a file from this slightly older Mbed Crypto that overwrites a file from Mbed TLS, resulting in some inconsistent state? And even if the build passed, you'd be overwriting recent files with unmaintained code.

**Comment by blueness** [comment]
@gilles-peskine-arm  I packaged this and wasn't aware that mbedcrypto was merged back.  I've removed the submodule and we'll restart our testing in Gentoo.

As an aside, submodules are a real pain for us in Gentoo (maybe other distros too?).  It helps to merge back for the final tarball releases.

**Comment by gilles-peskine-arm** [comment]
As far as I understand, this is a packaging issue in Gentoo which doesn't require any action on our side, so I'm closing this issue. Please let us know if you still expect some action from us.

@blueness The original idea with the separation of Mbed Crypto and Mbed TLS was that they would be completely separate projects, and Mbed Crypto would be a build-time dependency of Mbed TLS. For various reasons, the two projects never achieved much independence and we've merged them back. We do intend to separate the crypto and TLS parts of the library eventually, but only after doing some necessary preparation work that will make it viable for them to be separate projects. For information, there is now a low-traffic mailing list where we would announce such changes: [mbed-tls-announce@lists.trustedfirmware.org](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls-announce) .

@blueness Please let us know if we're doing things that make your life difficult. I can't promise that we'll always do things the way you want: we might be unable to, or we might not have the time, or we may have to arbitrate between making your life more difficult and making someone else's life more difficult. But your chances are better if we're aware of the problem.
