### ISSUE TITLE
A bug in .vcxpoj files and suggested fix

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#3297]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug
`x64|Debug` configuration in `mbedTLS.vcxproj` has an incorrect `WIN32` preprocessor definition instead of `WIN64`.
The macro was never used, but this is still a bug.

**OS**  
Windows

**mbed TLS build:**  
All versions have this bug.

----------------------------------------------------------------
## Enhancement

**Justification - why does the library need this feature?** 
MSVC has a number of predefined macros, and project wizards used to add something too.
Search in mbedTLS files reveals that macros `WIN32`, `WIN64` and, `_WINDOWS` remain unused; these are obsolete. Also, predefined `_DEBUG` is defined once again in projects, but never used.
Instead, predefined `_WIN32` and `_WIN64` are used in library code.

**Suggested enhancement**  
Remove unused definitions from scripts and projects; keep relying on predefined macros.
Visual Studio solution has built successfully with these changes in my test.

**Comment by paul-elliott-arm** [comment]
Hi!

You are indeed quite correct about debug|x64, and I can easily fix this. However, given you have already done the work for this and your added suggestion, could I suggest you converting your test as a Pull Request, and I can review it from there?

**Comment by irwir** [comment]
Hi @paul-elliott-arm 
Thanks for taking a look.
PR is created; please check additional comment there.
