### ISSUE TITLE
mbedtls_x509_crt_info cannot show non-ASCII string properly

### ISSUE THREAD

**Issue by kohnakagawa** [ARMmbed/mbedtls#3303]
### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
macOS Majove

**mbed TLS build:**  
Version: git-d9f694960
OS version: 10.14.6 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
mbedtls is installed as follows:

```
$ git clone https://github.com/ARMmbed/mbedtls.git
$ cd mbedtls
$ git co d9f694960
$ mkdir build && cd build
$ cmake ../
$ cmake --build .
$ sudo make install
```

Then, compile the source codes contained in the attached zip file ([sample.zip](https://github.com/ARMmbed/mbedtls/files/4578796/sample.zip)).

```
$ unzip sample.zip
$ cd sample && make
g++ -std=c++14 main.cpp -lmbedx509 -lmbedtls -lmbedcrypto -o a.out
$ ./a.out
```

This program generates `output.txt`. Open `output.txt` and see the "subject name" row.

```
subject name      : C=PL, O=Tomasz MoÅ?, CN=Tomasz MoÅ?, emailAddress=desowin@gmail.com
                                     ^^              ^^
```

`O=Tomasz Moń, CN=Tomasz Moń` is correct, but `mbedtls_x509_crt_info` fails to encode non-ASCII character `ń` and "subject name" is not properly shown.

I investigated this problem and I found the following lines are the root of the cause.

https://github.com/ARMmbed/mbedtls/blob/d9f694960f10c23cc5d7cb6de440fe3584ff7979/library/x509.c#L783-L793

`ń` is encoded as `0xc5 0x84` in UTF-8. The above lines convert `0xc5 0x84` into `0xc5 0x3f`, but this byte sequence can't be interpreted as UTF-8 encoded string. Therefore, the "subject name" row is not shown properly.

**Expected behavior**   
If `mbedtls_x509_crt_info` should escape non-ASCII string, the output should be

```
subject name      : C=PL, O=Tomasz Mo??, CN=Tomasz Mo??, emailAddress=desowin@gmail.com
```

**Comment by yanesca** [comment]
Hi @kohnakagawa, thank you very much for your interest in Mbed TLS and for submitting your report. The behaviour of `mbedtls_x509_crt_info()` would indeed be better and the output more readable if it would replace the non-ascii characters with `??`.

**Comment by kohnakagawa** [comment]
Hi @yanesca, thank you for your reply.

> The behaviour of mbedtls_x509_crt_info() would indeed be better and the output more readable if it would replace the non-ascii characters with ??.

OK. I will create a pull-request to fix this issue.

**Comment by yanesca** [comment]
Thank you for your contribution!
