### ISSUE TITLE
mbedtls_pk_parse_public_key && mbedtls_pk_parse_key return error: -16000

### ISSUE THREAD

**Issue by jwcesign** [ARMmbed/mbedtls#3327]
Hi, Here is my example:
~~~
mbedtls_rsa_context g_RSACtx;
mbedtls_pk_init(&g_RSAKeyContex);
mbedtls_pk_setup(&g_RSAKeyContex, mbedtls_pk_info_from_type((mbedtls_pk_type_t)MBEDTLS_PK_RSA));
mbedtls_pk_parse_public_key(&g_RSAKeyContex, (unsigned char*)pubKey, (size_t)keyLen);
~~~
`pubKey` is:
~~~
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKyZAeNWGOEKyar82M/ogMineDkB0Imx
Ck2PaSaBJhl9HGH+SvU8rjpuOTx3F9dBVNrZWuvt7c3+aaibOSKdafMCAwEAAQ==
-----END PUBLIC KEY-----
~~~
`keyLen` is `strlen(pubKey) + 1`, but when parse it, it return error -16000, where I did wrong?

**Comment by danh-arm** [comment]
Hi @jwcesign. Please post questions like this on the public mailing list here (you will need to register first):
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls

**Comment by Akshayghadage93** [comment]
Check spaces in the key....there should not be any spaces in the key
