### ISSUE TITLE
Win7: yotta install mbedtls succeeds but throws error

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/mbedtls#333]
Running `yt install mbedtls` in the Yotta cmd shell on Windows 7 SP1 downloads mbedtls correctly, however then complains about how there is no `win` target for Windows.
```
(workspace) C:\Users\nikhau01>yt install mbedtls
info: get versions for mbedtls
info: download mbedtls@2.1.4 from the public module registry
info: get versions for win
error: could not install target win at  for win
error: win does not exist in the targets registry. Check that the name is correct, and that it has been published.
```

This is not strictly speaking an mbedtls installation problem, as it was downloaded correctly, but confusing none the less. Executing `yt target frdm-k64f-gcc` before `yt install mbedtls` squelches this error obviously.

The readme suggests that one can simply execute this command, when in reality it is implied that the command is expected to be executed inside an existing yotta module with a defined target for which one would like to use mbedtls.

If one is just interested in the yotta module without having decided upon the target yet, this error message is a little confusing.

For OS X the installation just uses the osx-native target, which exists and therefore no error occurs:
```
 $ yt install mbedtls
info: get versions for mbedtls
info: download mbedtls@2.2.0-rc.1 from the public module registry
info: get versions for x86-osx-native
info: download x86-osx-native@0.0.7 from the public module registry
```

@autopulated @sbutcher-arm @mpg

**Comment by mpg** [comment]
> The readme suggests that one can simply execute this command, when in reality it is implied that the command is expected to be executed inside an existing yotta module with a defined target for which one would like to use mbedtls.

Another option is to have a target set globally with `yt target -g` before you invoke `yt install`: that way you don't need to be in a yotta module.

Otherwise I agree that the error message is confusing, but I think that's more an yotta issue than and mbedtls issue (sorry @autopulated ).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-529

**Comment by autopulated** [comment]
Yup, we should have a native target for windows. I think I saw a mingw one someone had created (http://yotta.mbed.com/#/target/mingw/0.0.1), which could become the default.

**Comment by mpg** [comment]
Closing as "not an mbed TLS issue".
