### ISSUE TITLE
DTLS Handshake flight message combination and fragmentation support

### ISSUE THREAD

**Issue by brycekahle** [ARMmbed/mbedtls#334]
It appears that the server handles DTLS handshake messages that are fragmented, but the client does not support combining all messages of a flight together into a series of fragments. This is desirable over UDP to avoid message order issues during the Handshake.

I'd be happy to submit a PR if you have any suggestion on how you would like this configured and implemented.

**Comment by mpg** [comment]
This is on our roadmap. (I assume by client/server in your description you actually mean sender/receiver).

When I was thinking about it, my ideas were something like:
- in `mbedtls_ssl_write_record()` we currently save handshake messages in case we need to resend them (that's the call to `ssl_flight_append()`, and then we send them - we could actually stop at saving them, not send them at this point.
- then when the outgoing flight is complete, `mbedtls_ssl_send_flight()` is called, and that would be the ideal point to examine the whole list of messages to be sent and pack them in datagrams in the most efficient way before sending them.

Might not be the best way, but that's how I would start.

**Comment by sbutcher-arm** [comment]
A series of PR's by @hanno-arm and @mpg to introduce this feature was recently merged, which is described in #1951. This issue can now be closed and the feature was shipped in [`mbedtls-2.13.0`](https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.13.0).
