### ISSUE TITLE
Write a test driver for transparent signatures

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3344]
Write a test transparent driver conforming to the interface defined in #3313 that supports the following functionality with at least one signature algoritm: key import, key generation, obtaining the public key, signing a hash, verifying a hash. This test driver will use Mbed TLS functions to perform the calculation.

Add a component to tests/scripts/all.sh that runs the unit tests in such a way that the relevant operations go through this driver using the build framework provided by #3325. Add a few unit tests to validate that the driver is used in this configuration.

**Comment by carlaageamundsen** [comment]
@gilles-peskine-arm Hi, can you assign this task to me?

**Comment by ronald-cron-arm** [comment]
This is completed: see tests/src/signature.c and tests/src/key_management.c.

**Comment by ronald-cron-arm** [comment]
This is completed: see tests/src/signature.c and tests/src/key_management.c. Thus closing.
