### ISSUE TITLE
Write a test driver with multipart operations

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3345]
Write a test transparent driver conforming to the interface defined in #3313 that supports at least one algorithm that uses a key with multipart operations (e.g. HMAC, or AES-CTR). This test driver will use Mbed TLS functions to perform the calculation.

Add the requisite hooks in the library code to call driver wrappers.

Add a component to tests/scripts/all.sh that runs the unit tests in such a way that the relevant operations go through this driver using the build framework provided by #3325. Add a few unit tests to validate that the driver is used in this configuration.

**Comment by stevew817** [comment]
Please assign me.

**Comment by ronald-cron-arm** [comment]
Done, tests/src/drivers/cipher.c provides a transparent test driver supporting cipher multi-part operations.
