### ISSUE TITLE
Add support for transparent drivers in a starter set of functions

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3347]
Instrument the library to add support for dispatch to a transparent driver conforming to the interface in #3313 in the following functions:

* `psa_sign_hash`, `psa_verify_hash`.
* `psa_generate_key`.

Validate these hooks with a test driver: #3344.

**Comment by carlaageamundsen** [comment]
@gilles-peskine-arm Hi, can you assign this task to me?

**Comment by gilles-peskine-arm** [comment]
@carlaageamundsen Done

**Comment by stevew817** [comment]
@gilles-peskine-arm Please re-assign to me, @carlaageamundsen is overloaded for next sprint.

**Comment by ronald-cron-arm** [comment]
Done.
