### ISSUE TITLE
PSA Crypto: allow to generate PSA constants in another directory

### ISSUE THREAD

**Issue by hug-dev** [ARMmbed/mbedtls#3365]
### Description
- Type: Bug and Enhancement
- Priority: Major

---------------------------------------------------------------

In [`rust-psa-crypto`](https://github.com/parallaxsecond/rust-psa-crypto) we are currently building a Rust wrapper around the PSA Crypto interface.
To be able to publish our library on crates.io, it needs to build without modifying the source directory (which is read-only) and only writing to the build directory.

We successfully were able to create the `config.h` file in the build directory with the `--write` option and to compile inside it using CMake.
However during compilation, CMake call the `generate_psa_constants.py` script which creates the `programs/psa/psa_constant_names_generated.c` file inside the source tree. This file is then included with an `#include` macro.

Would it be possible to control the directory where that file is generated? Maybe it should be generated in the CMake build directory by default?

**Comment by gilles-peskine-arm** [comment]
Yes, that's a mistake in the cmake script. Most of us aren't cmake experts, so a patch would be welcome.

**Comment by hug-dev** [comment]
I have made some changes that should fix the issue but I am not sure they are iodiomatic. I am happy to make a PR for this so that maintainers can help me 😃!
