### ISSUE TITLE
mbedtls_ssh_handshake error -0X50 when connecting to AWS

### ISSUE THREAD

**Issue by shrinivasragolu** [ARMmbed/mbedtls#3427]
Hi All,

I am working on Renesas RZA2M embedded board with Linux. It has limited memory of 6MB flash(R-Only)
I am using mbedtls version 2.16.5 for aws iot sdk for embedded c according to 
https://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html

When I run sample application, it is taking 15 secs for "Seeding random generator number..." and throwing below error

$ ./subscribe_publish_sample 

AWS IoT SDK Version 3.0.1-

DEBUG:   main L#159 rootCA /root/../certs/AmazonRootCA1.pem
DEBUG:   main L#160 clientCRT /root/../certs/774a17950a-certificate.pem.crt
DEBUG:   main L#161 clientKey /root/../certs/774a17950a-private.pem.key
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x50

ERROR: main L#190 Error(-4) connecting to a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com:443
----------------------------------------------------------------------------------------------------------------

 For detailed debug log using ssl_client2, go through [https://pastebin.com/mNXhB0xj](url)
https://pastebin.com/mNXhB0xj

my client device specifications 
**$ cat /proc/cpuinfo** 
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1056.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Generic R7S9210 (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000
**$ free** 
             total       used       free     shared    buffers     cached
Mem:          7544       4484       3060         40          0        304
-/+ buffers/cache:       4180       3364
Swap:            0          0          0

I am not getting any help to resolve this issue and spending days and days. I am suspecting the issue might be timing related (or) cpu clock related (or) memory footprint related (or) something else

I need this forum help badly to resolve the issue. Please ping me if you need any other data.

Thanks in advance,
Srinivas.

**Comment by danh-arm** [comment]
Hi @shrinivasragolu. You should ask questions like this on the developer mailing list:
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls

This tracker is for confirmed bugs and enhancements. Regards, Dan.
