### ISSUE TITLE
Will you continue to provide GPL licence?

### ISSUE THREAD

**Issue by hrk141** [ARMmbed/mbedtls#343]
The mbedtls is currently providing dual licence of GPL2.0 and Apache2.0.
However, I read you were planning to provide only in Apache2.0.

https://community.arm.com/groups/internet-of-things/blog/2015/02/09/polarssl-is-dead-long-live-mbed-tls

Will you provide GPL2.0 continuously also in the future?

I would like to use mbedtls with our GPL2.0's software if it will be provided in GPL2.0.

**Comment by mpg** [comment]
The wording in the linked article is (emphasis mine): "mbed TLS will change its *main* license from the GPL to the liberal Apache license", it doesn't state we're planning to provide *only* Apache 2.0 at any point. By "main" license we mean it's the one in the repo, not that there won't be other licenses. I'm not aware of any plans to stop providing GPL'd tarballs.

@pjbakker : would you like to comment on this?

**Comment by pjbakker** [comment]
Indeed.. There are no plans to discontinue GPL support in the future.

**Comment by hrk141** [comment]
Thanks your answer.
That's is good information for me. :smiley:
