### ISSUE TITLE
_GNU_SOURCE redefined

### ISSUE THREAD

**Issue by moe123** [ARMmbed/mbedtls#3432]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
|linux|

**mbed TLS build:**  
Version: 2.16.6
OS version: generic behaviors

entropy_poll.c line 24
```
- #if defined(__linux__)
- /* Ensure that syscall() is available even when compiling with -std=c99 */
- #define _GNU_SOURCE
- #endif

+ #if defined(__GLIBC__) && !defined(_GNU_SOURCE)
+ /* Ensure that syscall() is available even when compiling with -std=c99 */
+ #define _GNU_SOURCE
+ #endif

```

**Comment by gilles-peskine-arm** [comment]
Thanks! I see two issues here: that the redefinition of `_GNU_SOURCE` causes an error if `_GNU_SOURCE` was already defined with a non-empty expansion, and a change in the conditions under which `_GNU_SOURCE` is defined. Adding `&& !defined(_GNU_SOURCE)` looks correct, but I'm less sure about the other change.

Systems where `__linux__` is defined but not `__GLIBC__`: Linux kernel with a different libc. I'm not well-versed enough in the Linux libc ecosystem: would we want to define `_GNU_SOURCE` here? Does it matter?

Systems where `__GLIBC__` is defined but not `__linux__`: Glibc on a different kernel (e.g. FreeBSD, Hurd). We don't want to invoke `syscall(SYS_getrandom)` there. So should it be `defined(__GLIBC__) && defined(__linux__)`?

**Comment by moe123** [comment]
_GNU_SOURCE is a LIBC messy thingy; these days there are linux'es without glibc. For the rest, you need a better detection contract; yes coupling; as GLIBC is something different from the target OS; for instance Android is linux based however its default libc is Bionic.

**Comment by mpg** [comment]
I fully agree that we should not redefine `_GNU_SOURCE` if it's already defined, that is, we should add `!defined(_GNU_SOURCE)` to the condition.

Regarding the other part (adding `defined(__GLIBC__)` to the condition), the glibc is not the only libc out there that provides `syscall()` if `_GNU_SOURCE` is defined, for example uClibc looks at `_GNU_SOURCE` as well: https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/include/features.h - but it also defines `__GLIBC__`. So I don't think I have an objection to adding `defined(__GLIBC__)` to the condition.

Just out of curiosity: does defining `_GNU_SOURCE` actually cause problems with other libc implementation? I would assume when a non-GNU-compatible libc is in use, `_GNU_SOURCE` would be useless but harmless.

**Comment by moe123** [comment]
better including for not relaying on any GLIBC assumption and forwarding .
```
#include <sys/syscall.h>
extern long syscall(long number, ...);

#ifdef SYS_getrandom

...

// x86_64  318
// x86     355
// aarch64 278
// arm     384
// ppc64le 359

```

``` From manual:
      syscall():
           Since glibc 2.19:
               _DEFAULT_SOURCE
           Before glibc 2.19:
               _BSD_SOURCE || _SVID_SOURCE
```

**Comment by gilles-peskine-arm** [comment]
I think we can in fact remove `defined(__GLIBC__)` altogether and call the system call. The only question is whether `__linux_` implies the availability of `<sys/syscall.h>` and `syscall()`. If you have some experience with the libc ecosystem on Linux, I'd appreciate comments on https://github.com/ARMmbed/mbedtls/pull/3731.

**Comment by mpg** [comment]
> I think we can in fact remove defined(__GLIBC__) altogether and call the system call. The only question is whether __linux_ implies the availability of <sys/syscall.h> and syscall().

I don't understand your reasoning here. For me things go the other way: the first question is whether `__linux__` implies the availability of `<sys/syscall.h>` and `syscall()`. After we've answered this question, we'll know whether we can in fact remove `&& defined(__GLIBC__)` and just call the system call. Not before.

**Comment by gilles-peskine-arm** [comment]
@mpg Aren't we saying the same thing? I'm saying that if `__linux__` implies `<sys/syscall.h>` and `syscall()`, then we can and should remove `defined(__GLIBC__)`.

**Comment by moe123** [comment]
The best solution would be to move this concern within a configure step. __linux__ macro  is not enough you must exclude Android and certainly other linux-based OSes even if they declare __linux__. Their layout is so different + it's not guaranteed they expose public syscalls and `if even if` this syscall is avalaible. For instance, Bionic has an arc4random/arc4random_buf implementation which could be used for bootstrapping instead; it's not optimal as it doesn't guarantee a variety of sources however, you could immediatly apply a cipher tea pass on is output; if well implemented it should  be re-seed kernel-random.

**Comment by gilles-peskine-arm** [comment]
> move this concern within a configure step

I personally agree, but Mbed TLS doesn't currently have a configure script (in the sense of platform autodetection), and there is a sensible argument that platform autodetection is complicated in brittle. (A counter-argument is that configure doesn't have to mean autoconf, which is the source of most of the backlash against platform autodetection.)

Without autodetection, we're left with manual configuration. Which is possible, but painful.

If we can't find a good generic solution, is there a specific platform that you care about and that we could make work reliably?

**Comment by moe123** [comment]
yes, first for `__linux__` detection the rational would be  `#if __linux__ && !defined(ANDROID) and any excluded ones in the future` then treating android separately.
