### ISSUE TITLE
TLS 1.2 without client certificate

### ISSUE THREAD

**Issue by hawkandspit** [ARMmbed/mbedtls#3436]
I'm usiing:

#define MBEDTLS_VERSION_NUMBER         0x020D0100
#define MBEDTLS_VERSION_STRING         "2.13.1"
#define MBEDTLS_VERSION_STRING_FULL    "mbed TLS 2.13.1"

According to RFC5246:

If no suitable certificate is available,
      the client MUST send a certificate message containing no
      certificates.  That is, the certificate_list structure has a
      length of zero.

How do I do this with mbedTLS? It looks like mbedtls_x509_crt_parse() wants a list of certificates and will reject a zero-length list.

**Comment by danh-arm** [comment]
Hi. Please ask questions like this on the developer mailing list:
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls
