### ISSUE TITLE
mbedtls 1.3.14 build failure on s309x

### ISSUE THREAD

**Issue by jcowgill** [ARMmbed/mbedtls#344]
mbedtls 1.3.14 failed to build on s309x. 1.3.9 worked. This is the log:
https://buildd.debian.org/status/fetch.php?pkg=polarssl&arch=s390x&ver=1.3.14-0.1&stamp=1446485889

It seems to be caused by this line:
https://github.com/ARMmbed/mbedtls/blob/mbedtls-1.3/library/Makefile#L30

Firstly (at least with gcc), `-fPIC -fpic` is redundant since the options are mutually exclusive and will be converted to `-fpic` (the last option) when passed to the gcc back end. Secondly, using `-fpic` has portability issues since on some processors using this option will produce code which is faster but has extra constraints which might not be met.

See the GCC option summary:
https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html

Please can you change the line to just `-fPIC`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-537

**Comment by mpg** [comment]
Thanks for your report! We're investigating the issue.

**Comment by sbutcher-arm** [comment]
This was an issue for the Debian on the s309x platform. mbed TLS 1.3 now near the end of it's life, and if a minor platform such as s309x has been broken for sometime, we're not going to fix it now, so I think this issue can be closed.

It looks as if Debian has moved on to much newer versions of the library anyway, so this issue shouldn't be an issue any longer for them.

Therefore closing. If this is a problem for anyone, please comment!
