### ISSUE TITLE
Use local labels for inline asm

### ISSUE THREAD

**Issue by okhowang** [ARMmbed/mbedtls#3451]
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
iPhoneSimulator

**mbed TLS build:**  
Version: 2.22.0
OS version: 9.0
Configuration: default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  Xcode 11.5
Additional environment information:  

**Expected behavior**   
building success
**Actual behavior**  
got error when linking
```
<inline asm>:9:2: error: invalid symbol redefinition
        unsupported:              
        ^
LLVM ERROR: Error parsing inline asm

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`unsupported:` is located in `padlock.c` which use named labels in inline asm.
**Steps to reproduce**  
I can't make an reproducible minimized project.
but according https://stackoverflow.com/questions/14506151/invalid-symbol-redefinition-in-inline-asm-on-llvm.
we should use local labels for inline asm, not named labels.

**Comment by gilles-peskine-arm** [comment]
What version of Clang is invoked and with what options? I'm asking so that we can try to reproduce this. We have [a macOS build on our CI](https://travis-ci.org/github/ARMmbed/mbedtls/jobs/701250898) (Clang 9.1.0) that just runs `make` and it isn't complaining.

**Comment by okhowang** [comment]
```
$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by okhowang** [comment]
I add some extra parameter in my project, but i can't reproduce in mbedtls project.
```cmake
cmake_policy(SET CMP0069 NEW)
cmake_policy(SET CMP0063 NEW)
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE YES)
```

**Comment by gilles-peskine-arm** [comment]
Maybe `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)` turns on link-time optimization and clang decides to inline `mbedtls_padlock_has_support` in both places where it's called in `aes.c`. Our CI build doesn't turn on LTO anywhere AFAIR, maybe we should add this. I'll give it a try.

**Comment by gilles-peskine-arm** [comment]
`clang-10 -O3 -flto` on Linux doesn't complain. I don't have Clang 11 easily accessible. Can you share the compiler command line that results from these cmake settings?

**Comment by okhowang** [comment]
I'm building iOS library on macOS.
sorry for unable to provide compiler command detailly
