### ISSUE TITLE
DES self-test expected output is different from online DES tools

### ISSUE THREAD

**Issue by moschiel** [ARMmbed/mbedtls#3455]
### Description
- Type: Bug/Question
- Priority: Major

---------------------------------------------------------------
## DESCRIPTION
des.c has a self-test functionality  by calling the function **mbedtls_des_self_test** with some test buffers on it, all encrypt/decrypt test occurs as expected, but when I input the same inputs and key in some online DES tools, I get a totally different encrypt/decrypt result.  
OBS: I am running **ECB** mode.

## SELF-TEST BUFFERS FROM des.c   
This is the test input buffer, in ASCII it is equal to **"Now is t"**
`static const unsigned char des3_test_buf[8] = { 0x4E, 0x6F, 0x77, 0x20, 0x69, 0x73, 0x20, 0x74};  // == "Now is t"`

This is the test keys, as I am not using 3DES we use only the first key (**0123456789ABCDEF**)
```
static const unsigned char des3_test_keys[24] =
{
    0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF, //0123456789ABCDEF 
    0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF, 0x01,
    0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF, 0x01, 0x23
};
```

This is the decrypt ouptut expected by the self-test, as we aren't using 3DES, only the first result is analyzed (**CDD64F2F9427C15D**)
```
static const unsigned char des3_test_ecb_dec[3][8] =
{
    { 0xCD, 0xD6, 0x4F, 0x2F, 0x94, 0x27, 0xC1, 0x5D }, 
    { 0x69, 0x96, 0xC8, 0xFA, 0x47, 0xA2, 0xAB, 0xEB },
    { 0x83, 0x25, 0x39, 0x76, 0x44, 0x09, 0x1A, 0x0A }
};
```

This is the encrypt ouptut expected by the self-test, as we aren't using 3DES, only the first result is analyzed(**6A2A19F41ECA854B**)
```
static const unsigned char des3_test_ecb_enc[3][8] =
{
    { 0x6A, 0x2A, 0x19, 0xF4, 0x1E, 0xCA, 0x85, 0x4B },
    { 0x03, 0xE6, 0x9F, 0x5B, 0xFA, 0x58, 0xEB, 0x42 },
    { 0xDD, 0x17, 0xE8, 0xB8, 0xB4, 0x37, 0xD2, 0x32 }
};
```

## COMPARATION WITH ONLINE DES TOOLS   
Clicking on the links below, there is a online DES test with the same input and key, but the expected outputs are different
[DECRYPT TEST](https://emvlab.org/descalc/?key=0123456789ABCDEF&iv=0000000000000000&input=4E6F772069732074&mode=ecb&action=Decrypt&output=3FA40E8A984D4815) -> ouptut is **3FA40E8A984D4815**, but according to des.c self-test it was suposed to be **CDD64F2F9427C15D**
[ENCRYPT TEST](https://emvlab.org/descalc/?key=0123456789ABCDEF&iv=0000000000000000&input=4E6F772069732074&mode=ecb&action=Encrypt&output=A416143D9243704C) -> ouptut is **A416143D9243704C**, but according to des.c self-test it was suposed to be **6A2A19F41ECA854B**

## QUESTION
Shouldn't the encrypt/decrypt outputs be the same as the online DES tools?

**Comment by moschiel** [comment]
Closed to make more tests

**Comment by gilles-peskine-arm** [comment]
The DES self-tests to 100 rounds of encryption (with each round's output used as the input of the next round). Doing multiple rounds which is moderately common practice in self-tests for symmetric encryption, because it exercises the function over more data without requiring much storage for the inputs and outputs.

**Comment by moschiel** [comment]
> The DES self-tests to 100 rounds of encryption (with each round's output used as the input of the next round). Doing multiple rounds which is moderately common practice in self-tests for symmetric encryption, because it exercises the function over more data without requiring much storage for the inputs and outputs.

Yes I just saw that, it is actually 10000 iterations.
