### ISSUE TITLE
2.16 only: backport the removal of mbedtls_test_unhexify

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3459]
#3438 removes the remaining uses of `mbedtls_test_unhexify` on test case parameters where the test framework now allows using a `data_t*` parameter instead. This should be backported to 2.16 to keep the test code similar.

Not applicable to 2.7, where the test framework doesn't support `data_t`.

**Comment by mpg** [comment]
Note: the specific commit in #3438 that does this is https://github.com/ARMmbed/mbedtls/pull/3438/commits/b0e2f2224acf57c24c9ed044a702bf562c9ee969

**Comment by ronald-cron-arm** [comment]
Implemented by #3461 which is merged now thus closing.
