### ISSUE TITLE
Will ChaCha20 and Poly1305 be supported in mbedtls?

### ISSUE THREAD

**Issue by strrchr** [ARMmbed/mbedtls#346]
It seems to have good performance on ARM platform.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-539

**Comment by sbutcher-arm** [comment]
This is already a planned feature although we have no date as yet for when this may become available.

**Comment by carlaageamundsen** [comment]
What is the status of Poly1305 support in mbedtls now?
Thanks,
Carl Aage

**Comment by damaki** [comment]
Has there been any work on this internally at ARM, beyond it being a planned feature? Otherwise, if you're interested, I can make a pull request adding ChaCha20 and Poly1305.

**Comment by pjbakker** [comment]
It is still a planned feature without work being done.
We are open for contributions of original work that implement and add them to the library.
