### ISSUE TITLE
-Wformat-signedness is unavailable before gcc 5

### ISSUE THREAD

**Issue by okhowang** [ARMmbed/mbedtls#3478]
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug
build with gcc 4.8.5, will got
```
cc: error: unrecognized command line option '-Wformat-signedness'
```
there is no `-Wformat-signedness` in https://gcc.gnu.org/onlinedocs/gcc-4.9.4/gcc/Option-Index.html
there is `-Wformat-signedness` in https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Option-Index.html
**OS**  
linux

**mbed TLS build:**  
Version: 2.23.0
OS version: centos 7

**Expected behavior**
enable -Wformat-signedness when gcc >= 5

**Actual behavior**  

**Steps to reproduce**  
build with cmake on gcc 4.x

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb). If you can't find the answer you're looking for then please use the [Mbed TLS mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)**

**Comment by LoganMatrix** [comment]
mbed TLS Version: 2.23.0  add "option(MBEDTLS_FATAL_WARNINGS "Compiler warnings treated as errors" ON)" ,change OFF can build sucess or add_definitions(-D_SOCKLEN_T=1)
