### ISSUE TITLE
mbedtls openssl

### ISSUE THREAD

**Issue by Luke9966** [ARMmbed/mbedtls#3484]
I have a client programme developed in mbedtls and a server programme developed in openssl. What can I do if I want use the client programme to communicate with the server programme? Could you have me? Thanks!

**Comment by gilles-peskine-arm** [comment]
Please post support questions and discussions on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls). We use GitHub for bug tracking and feature requests only.

Mbed TLS and OpenSSL both implement the TLS protocol. You don't need to do anything special for them to talk to each other.
