### ISSUE TITLE
HTTPS client

### ISSUE THREAD

**Issue by nu8** [ARMmbed/mbedtls#3485]
I am looking for an HTTPS client that has support for Mbed TLS. I know cURL is
one option, but are any others available?

**Comment by gilles-peskine-arm** [comment]
Please post support questions and discussions on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls). We use GitHub for bug tracking and feature requests only.

The only “curl-like” software I'm familiar with is wget, and it doesn't support Mbed TLS. But you'd get better recommendations if you explained what you want to do and why you aren't using curl.
