### ISSUE TITLE
sha1sum breaks the system!

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#349]
The installation of mbedTLS generate a sha1sum program, the same one provided by coreutils on debian/ubuntu. 

When the mbedTLS version of sha1sum is installed (/usr/local/bin/), it generate a lot of conflicts when using the package manager as it claims there is some missing symbols (sha1_file). 

PLEASE rename your program, prefix it with "mbed" or something: mbed_sha1sum. I wasted hours running a system with broken packages!, installing a Kernel puts the system very unstable

```
update-initramfs: deferring update (hook will be called later)
initrd.img(/boot/initrd.img-3.19.0-33-generic
) points to /boot/initrd.img-3.19.0-33-generic
 (/boot/initrd.img-3.19.0-33-generic) -- doing nothing at /var/lib/dpkg/info/linux-image-3.19.0-33-generic.postinst line 491.
vmlinuz(/boot/vmlinuz-3.19.0-33-generic
) points to /boot/vmlinuz-3.19.0-33-generic
 (/boot/vmlinuz-3.19.0-33-generic) -- doing nothing at /var/lib/dpkg/info/linux-image-3.19.0-33-generic.postinst line 491.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 3.19.0-33-generic /boot/vmlinuz-3.19.0-33-generic
run-parts: executing /etc/kernel/postinst.d/dkms 3.19.0-33-generic /boot/vmlinuz-3.19.0-33-generic
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.19.0-33-generic /boot/vmlinuz-3.19.0-33-generic
update-initramfs: Generating /boot/initrd.img-3.19.0-33-generic
sha1sum: symbol lookup error: sha1sum: undefined symbol: sha1_file
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 127
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/linux-image-3.19.0-33-generic.postinst line 1025.
dpkg: error processing package linux-image-3.19.0-33-generic (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of linux-image-extra-3.19.0-33-generic:
 linux-image-extra-3.19.0-33-generic depends on linux-image-3.19.0-33-generic; however:
  Package linux-image-3.19.0-33-generic is not configured yet.
```

**Comment by mwgamera** [comment]
Perhaps this is a problem with cmake configuration, because when using regular make these programs were always installed with a prefix in their names. Anyway, there is no `sha1sum` at all since b327168 but I noticed there are outdated project files for Visual Studio still included in the tree.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-544

**Comment by mpg** [comment]
We're going to investigate if we can prefix those programs with CMake too, but in the meantime the workaround is indeed to use plain old Make, whose "install" target correctly prefixes the program names.

**Comment by sbutcher-arm** [comment]
`sha1sum` is no longer part of the main mbed TLS package. It remains part of older versions we still maintain, but for backwards compatibility I wouldn't want to either change the name or remove it from those older versions.

Therefore closing this issue, without a fix.
