### ISSUE TITLE
When verifying X.509 certificate, I just want to verify valid_to, instead of valid_from and valid_to.

### ISSUE THREAD

**Issue by Qinch** [ARMmbed/mbedtls#3494]
### Description
- Type: Question
- Priority:  Minor

Hi:
  X.509 certificat validity period is [valid_from, valid_to]. 
When verifying X.509 certificate, I just want to verify valid_to, instead of valid_from and valid_to.

I modified mbedtls_x509_time_is_future function  in x509.c, from
```bash
int mbedtls_x509_time_is_future( const mbedtls_x509_time *from )
{
    mbedtls_x509_time now;

    if( x509_get_current_time( &now ) != 0 )
        return( 1 );

    return( x509_check_time( from, &now ) );
}
```
to
```bash

int mbedtls_x509_time_is_future( const mbedtls_x509_time *from )
{
    ((void) from);
    return( 0 );
}
```

Is this modification OK？

Thanks a lot

**Comment by yanesca** [comment]
Hi Qinch, could you please ask this and questions like this on the developer mailing list: https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls
