### ISSUE TITLE
LGPL code in library/bignum.c

### ISSUE THREAD

**Issue by bmastenbrook** [ARMmbed/mbedtls#350]
In [bignum.c:1257](https://github.com/ARMmbed/mbedtls/blob/334a87be0bcf8319cb6dec883b8c128acc7d5ec4/library/bignum.c#L1257) there is a comment before a block of code:

```c
            /*
             * __udiv_qrnnd_c, from gmp/longlong.h
             */
```
The code that follows does in fact have a very close correspondence with `__udiv_qrnnd_c` from [GMP's longlong.h](https://gmplib.org/repo/gmp-6.1/file/tip/longlong.h#l2065), though it is not exactly the same.

Given that this code is nontrivial and derived from a LGPL licensed library, did ARM obtain permission to relicense this routine to Apache 2.0?

Additionally, there is a [comment near the top](https://github.com/ARMmbed/mbedtls/blob/334a87be0bcf8319cb6dec883b8c128acc7d5ec4/library/bignum.c#L25) that claims that the library is based on code from GPG, which is under the GPL. Other than using a similar structure for MPIs, I don't see any duplicated code, but it seems awfully suspect to claim that something is based on code which is licensed under the GPL in a file with an Apache license header.

*Edited 2015-11-13 to link to a specific version of the source*

**Comment by pjbakker** [comment]
Thanks for your report. We'll look into it.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-543

**Comment by OlegHahm** [comment]
Any news?

**Comment by sbutcher-arm** [comment]
Hi Brian,
 
Thanks for raising this with us! We have looked into the code you’ve highlighted, and found it was introduced many years ago by a developer who is no longer involved with the project, long before ARM became involved. 

To avoid any appearance of impropriety we decided to rewrite the code as you can see in this [commit](https://github.com/ARMmbed/mbedtls/commit/15b15d1361a177d9aca54633177474dccd997470).
 
We have also checked the rest of the code in this file, and have also scanned it with [BlackDuck](https://www.blackducksoftware.com) and do not believe there is any source code present in mbed TLS which is not original.

With regards to the ‘based on’ comment, the original developer has listed two other sources of information in addition to the GnuPG code you mention. Based on our review, we have concluded that the author at that time was just trying to cite the references he had used to understand the problem-space before creating his own implementation. To prevent similar confusion in the future, we have clarified the comment in the same [commit](https://github.com/ARMmbed/mbedtls/commit/15b15d1361a177d9aca54633177474dccd997470).
 
We support and respect the open source community and always work to ensure that we use open source code in conformance with its license.

Thank you again for bringing this to our attention.
