### ISSUE TITLE
error: 'mbedtls_rsa_context {aka struct <anonymous>}' has no member named 'N'

### ISSUE THREAD

**Issue by JunJianX** [ARMmbed/mbedtls#3523]
### Description
When I complie my project ,gcc said```
 error: 'mbedtls_rsa_context {aka struct <anonymous>}' has no member named 'N'
     if( ( ret = mbedtls_mpi_read_binary( &rsa.N, 16, n_buff ) ) != 0 ||
                                              ^
compilation terminated due to -Wfatal-errors.
build/aos_target_build.mk:266: recipe for target 'out/linkkitapp@bk7231udevkitc/modules/./framework/uOTA/src/verify/ota_sign_veri.o' failed
make[1]: *** [out/linkkitapp@bk7231udevkitc/modules/./framework/uOTA/src/verify/ota_sign_veri.o] Error 1
make[1]: *** Waiting for unfinished jobs....

```
I cann't fix it,anyone who can help me?This is AliOS things develop SDK,and it includes mbedtls as a tool in it.
---------------------------------------------------------------
## Bug

**OS**  
Ubuntu16.04

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  

##This is my code 

```
int ks_verify_signature(unsigned char* sign_dat, const char* src_hash_dat, mbedtls_md_type_t src_hash_method)
{
    char tmp_buf[32] = {0};
    mbedtls_rsa_context rsa;
    size_t i;
    unsigned c;
    int ret =1;
    unsigned char hash[32];
    unsigned char buf[MBEDTLS_MPI_MAX_SIZE];
    if((NULL == sign_dat) || (NULL == src_hash_dat)) {
        printf("ota verify download sign input parameter NULL");
        return -1;
    }
    mbedtls_rsa_init( &rsa, 0, 0 );
    if(ota_hex_str2buf(src_hash_dat, tmp_buf, sizeof(tmp_buf)) < 0) {
        OTA_LOG_E("rsa verify:str2buf translate failed!");
        return -1;
    }
    if( ( ret = mbedtls_mpi_read_binary( &rsa.N, 16, n_buff ) ) != 0 ||
        ( ret = mbedtls_mpi_read_binary( &rsa.E, 16, e_buff ) ) != 0 )
    {
        printf("failed\n  ! mbedtls_mpi_read_file returned %d\n",ret);
        goto exit;
    }
    rsa.len = ( mbedtls_mpi_bitlen( &rsa.N ) + 7 ) >> 3;
    printf("rsa.len = %d \n",rsa.len);

    if( ( ret = mbedtls_rsa_pkcs1_verify( &rsa, NULL, NULL, MBEDTLS_RSA_PUBLIC, src_hash_method, 20, src_hash_dat, sign_dat ) ) != 0 )
    {
        mbedtls_printf( " failed\n  ! mbedtls_rsa_pkcs1_verify returned -0x%0x\n\n", (unsigned int) -ret );
        goto exit;
    }

exit:
    mbedtls_rsa_free( &rsa );
    return ret;
}
```

**Comment by gilles-peskine-arm** [comment]
This is a support question, not a bug report or feature request. Please post support questions to the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls), not to GitHub.

You are more likely to get help if you post complete code. What you posted can't compile since it doesn't have any `#include` statement. Also, please share your `config.h`.
