### ISSUE TITLE
mbedtls_x509_crl_parse_der() error

### ISSUE THREAD

**Issue by robertns** [ARMmbed/mbedtls#3533]
Hello,

I'm using mbedTLS as part of [open62541](https://github.com/open62541/open62541) project (on debian buster). When using .der certificate as a revocation list, `mbedtls_x509_crl_parse_der ` returns code `-9058`, i.e. (after calling `mbedtls_strerror `function) "X509 - The algorithm tag or value is invalid : ASN1 - ASN1 tag was of an unexpected value".

I have also reproduced the issue with Microsoft Visual Studio 2017 on Windows 10 (I used _mbedTLS.sln_ solution, _crl_app_ project) with current development code (commit `ee7e85f5b94a49cbe7a1977e4ac089e4c9013aa8`).

DER certificate files I used were obtained with Unified Automation UA Base Library using OpenSSL. I also used the DER certificate file of UaExpert - same error happens on both of them.

Parsing of these certificate files works when passed as "trusted".
[certificates.zip](https://github.com/ARMmbed/mbedtls/files/5006690/certificates.zip)

**Comment by gilles-peskine-arm** [comment]
Hi @robertns ,

Could you clarify what you're passing to `mbedtls_x509_crl_parse_der` exactly? It expects a certificate revocation list, not a certificate. How are you building the CRL? The error that you're getting is consistent with a bug in the code that generates the CRL. Can you please share some code to reproduce the problem?

**Comment by robertns** [comment]
Hello @gilles-peskine-arm ,

I'm passing the DER certificate file (I provided some examples in the zip file). As I mentioned, I used _crl_app_ project from the _mbetTLS.sln_.

I detected this error when I put the certificate in _crl_ folder which I used for reloading certificates in [open62541 SDK](https://github.com/open62541). It is [`reloadCertificates`](https://github.com/open62541/open62541/blob/master/plugins/crypto/mbedtls/ua_pki_mbedtls.c#L130) function in [ua_pki_mbedtls.c](https://github.com/open62541/open62541/blob/master/plugins/crypto/mbedtls/ua_pki_mbedtls.c).

In this snippet I used folder with certificates which are revoked and should be rejected:
```c
/* Load the revocationlists */
    if(ci->revocationListFolder.length > 0) {
        UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "Reloading the revocation-list");
        size_t pathsSize = 0;
        UA_String *paths = NULL;
        retval = fileNamesFromFolder(&ci->revocationListFolder, &pathsSize, &paths);
        if(retval != UA_STATUSCODE_GOOD)
            return retval;
        mbedtls_x509_crl_free(&ci->certificateRevocationList);
        mbedtls_x509_crl_init(&ci->certificateRevocationList);
        for(size_t i = 0; i < pathsSize; i++) {
            char f[PATH_MAX];
            memcpy(f, paths[i].data, paths[i].length);
            f[paths[i].length] = 0;
            err = mbedtls_x509_crl_parse_file(&ci->certificateRevocationList, f);
            if(err == 0) {
                UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER,
                            "Loaded certificate from %.*s",
                            (int)paths[i].length, paths[i].data);
            } else {
                char errBuff[300];
                mbedtls_strerror(err, errBuff, 300);
                UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER,
                            "Failed to load certificate from %.*s, mbedTLS error: %s (error code: %d)",
                            (int)paths[i].length, paths[i].data, errBuff, err);
                internalErrorFlag = 1;
            }
        }
        UA_Array_delete(paths, pathsSize, &UA_TYPES[UA_TYPES_STRING]);
        paths = NULL;
        pathsSize = 0;
    }
```

If I'm not using CRL correctly, can you please point me to the correct usage, i.e. how should I generate the CRL?

**Comment by gilles-peskine-arm** [comment]
Are you passing certificate files to `mbedtls_x509_crl_parse_file`? That can't work. `mbedtls_x509_crl_parse_file` and any other CRL parsing function expects a **[certificate revocation list](https://en.wikipedia.org/wiki/Certificate_revocation_list)**, not a certificate. The [format of a CRL](https://tools.ietf.org/html/rfc5280#section-5.1) is not a list of certificates. It's a list of certificate serial numbers, surrounded by some metadata. The list has to be signed by the certificate authority that generated the certificate.

If you're running your own CA, you can find howtos for generating CRL with OpenSSL on the web. If not, you need to obtain the CRL from the CA.

**Comment by robertns** [comment]
@gilles-peskine-arm  Thank you for clarification.

**Comment by hanno-arm** [comment]
Hi @robertns, you might also find the [X.509 example applications](https://github.com/ARMmbed/mbedtls/tree/development/programs/x509) useful in this context.
