### ISSUE TITLE
reconnection with overflow

### ISSUE THREAD

**Issue by zhenglining** [ARMmbed/mbedtls#3545]
### Description
- Type: Bug 
- Priority: Blocker

---------------------------------------------------------------
## Bug
when device reconnect some time later, it will call mbedtls_timing_hardclock to get time, it returns unsigned long, while ( ( tv_cur.tv_sec  - tv_init.tv_sec  ) * 1000000 may overflow when the time interval bigger than 999.
**OS**  
Mbed OS|linux|windows|
linux

**Comment by gilles-peskine-arm** [comment]
This isn't a bug, it's a [documented feature](https://tls.mbed.org/api/timing_8h.html#aeec9ae2577ce34ab01f2d213b99d07e1). `mbedtls_timing_hardclock` only works for small intervals, in controlled environments.

> Warning
> This is only a best effort! Do not rely on this! In particular, it is known to be unreliable on virtual machines.

> Note
> This value starts at an unspecified origin and may wrap around.

There is no function in the Mbed TLS API to get the current time. The X.509 module needs to get the current date and time, and for this it calls the platform funtion `mbedtls_platform_gmtime_r`, which is implemented by `gmtime_r` or `gmtime` if the platform has one of these.
