### ISSUE TITLE
Corrupted input causes continuous alert messages

### ISSUE THREAD

**Issue by ddemoney** [ARMmbed/mbedtls#358]
A corrupted packet was received by a TLS server after the session was established. At that point, my app is regularly polling for new incoming messages. Call path is:
- mbedtls_ssl_read()
  - mbedtls_ssl_read_record()
    - mbedtls_ssl_fetch_input()
    - ssl_parse_record_header()

In fetch_input(), ssl.in_left = 5, and nb_want =5 (thus no additional data is read). The first byte is not a valid msgtype. As a result, ssl_parse_record_header() sends an alert message to the client. However, the in_left count is not decremented; thus the next read request produces the same result. This continues until the connection is terminated.

**Comment by mpg** [comment]
What's the return value of the first call to `mbedtls_ssl_read()` that encounters an invalid message? It should be negative, indicating an error. It is the responsibility of the caller to terminate the connection when one of the functions `mbedtls_ssl_handshake()`, `mbedtls_ssl_read()` or `mbedtls_ssl_write()` returns an error.

If `mbedtls_ssl_read()` sends a fatal alert but does not return a negative value, then this is a bug and we'll fix it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-554

**Comment by ddemoney** [comment]
Is any negative return value from any of these functions fatal?

Can you point me to where this is documented?



[http://static.ideasunplugged.com/signature/s_235/t_SpKxpg.jpg?v=50]
we are the smart grid people

David DeMoney
Senior Software Engineer
Networked Energy Services Corporation

david.demoney@networkedenergy.com<mailto:david.demoney@networkedenergy.com>

t:    +1.408.684.1033
m:  +1.415.702.5136

http://www.networkedenergy.com<http://www.networkedenergy.com/>

On Nov 30, 2015, at 11:57 PM, Manuel P?gouri?-Gonnard <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the return value of the first call to mbedtls_ssl_read() that encounters an invalid message? It should be negative, indicating an error. It is the responsibility of the caller to terminate the connection when one of the functions mbedtls_ssl_handshake(), mbedtls_ssl_read() or mbedtls_ssl_write() returns an error.

If mbedtls_ssl_read() sends a fatal alert but does not return a negative value, then this is a bug and we'll fix it.

-

**Comment by mpg** [comment]
I expanded the documentation to make that point clearer.

The rationale is simple: TLS is supposed to provide a reliable connection, so when a bad record is received, TLS can't just drop the data silently as that would break the contract provided to the upper layers. Since corruption shouldn't happen anyway (TCP is supposed to be reliable), and bad records might mean attack, when a bad record is received the TLS connection must be closed.

(This is different with DTLS: here bad records are silently dropped by default. We provide options to adjust that behaviour.)
