### ISSUE TITLE
OSS-Fuzz build failing due to a Clang 12 warning

### ISSUE THREAD

**Issue by guidovranken** [ARMmbed/mbedtls#3586]
```
Step #4: /src/mbedtls/library/md5.c:426:7: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
Step #4:       "345678901234567890" }
Step #4:       ^
Step #4: /src/mbedtls/library/md5.c:425:7: note: place parentheses around the string literal to silence warning
Step #4:     { "12345678901234567890123456789012345678901234567890123456789012"
```

https://oss-fuzz-build-logs.storage.googleapis.com/log-5247911e-6d4a-461a-8a06-1679a4d261c7.txt

**Comment by gilles-peskine-arm** [comment]
Clang 11 isn't even officially released yet, and [even it doesn't have this warning](https://prereleases.llvm.org/11.0.0/rc2/tools/clang/docs/DiagnosticsReference.html#wextra). It's being added to [`-Wextra` in Clang 12](https://clang.llvm.org/docs/DiagnosticsReference.html#wextra).

**Comment by gilles-peskine-arm** [comment]
Would you mind submitting a patch? This one is easy enough, but I don't have Clang 12 easily available, so I'd be going blind.

**Comment by gilles-peskine-arm** [comment]
Well, I've installed a snapshot build of Clang 12 from [apt.llvm.org](https://apt.llvm.org/) (version `12.0.0-++20200811020820+0fd3d379e26-1~exp1~20200811001451.3157`), and I can't reproduce this.

```
clang-12 -Werror -Wall -Wextra -Wstring-concatenation -I include -c library/md5.c
```

I'm not familiar with the oss-fuzz environment. What build of Clang is it pulling? Would it be possible to stick to a released version?
