### ISSUE TITLE
Wrong size limit in gcm.c

### ISSUE THREAD

**Issue by Andreas-N** [ARMmbed/mbedtls#362]
Hi, 
I'm trying to en/decrypt a large file (>70MB) with the AES-128-GCM algorithm. Unfortunately I get the error MBEDTLS_ERR_GCM_BAD_INPUT for files larger than 67 108 832 Bytes (0x03FFFFE0). 
As far as I understood, in GCM Mode, the plain data (data to be encrypted) is limited to (2^39-256) bits (FFFFFFFE0), which is something like 68GB. I found these line of code in gcm.c:362 which are raising the error:

```
/* Total length is restricted to 2^39 - 256 bits, ie 2^36 - 2^5 bytes 
 * Also check for possible overflow */
if( ctx->len + length < ctx->len || (uint64_t) ctx->len + length > 0x03FFFFE0ull ) {
   return( MBEDTLS_ERR_GCM_BAD_INPUT );
 }
```

This behavior can be reproduced with the executable in mbedtls-2.2.0/programs/aes
```
dd if=/dev/urandom of=file.plain bs=1024 count=70000;
crypt_and_hash 0 file.plain file.aes AES-128-GCM SHA1 hex:E76B2413958B00E193
mbedtls_cipher_update() returned error
```
Thanks and regards Andreas

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-557

**Comment by mpg** [comment]
Thanks for your report, and sorry for not replying earlier (I thought I did, but apparently not). This will be fixed in a future release.
