### ISSUE TITLE
mbedTLS 2.2 rejects valid certificate with a max_pathlen=0 constraint

### ISSUE THREAD

**Issue by jcowgill** [ARMmbed/mbedtls#363]
While doing some stuff with linphone, I noticed that starting with 2.2, mbedTLS rejects the certificate used by https://smtp.linphone.org/. Older versions of mbedTLS and OpenSSL both accept this certificate.

I bisected it to this commit:
```
5dd4fe1b304eae211371408f1075ad414c48d2b4 is the first bad commit
commit 5dd4fe1b304eae211371408f1075ad414c48d2b4
Author: Janos Follath <janos.follath@gmail.com>
Date:   Mon Oct 12 09:02:20 2015 +0200

    Fixed pathlen contraint enforcement.

:040000 040000 a76811683c8e4ed049da2d47859f298d1c01fe7f 2a74913ef873a97228e295381aff6e1bf6f12258 M	library
```

I've put the certificate chain here (although you can just connect to linphone): https://gist.github.com/jcowgill/bcf9ea9223c041c8b0de

The penultimate certificate in the chain has 'max_pathlen=0' which seems related to the breaking commit. This is the output of cert_app from a good version of mbedtls:
```
[.. other CA certs above this...]

Verify requested for (Depth 1):
cert. version     : 3
serial number     : 05:E4:DC:3B:94:38:AB:3B:85:97:CB:A6:A1:98:50:E3
issuer name       : C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
subject name      : C=FR, ST=Paris, L=Paris, O=Gandi, CN=Gandi Standard SSL CA 2
issued  on        : 2014-09-12 00:00:00
expires on        : 2024-09-11 23:59:59
signed using      : RSA with SHA-384
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
  This certificate has no flags

Verify requested for (Depth 0):
cert. version     : 3
serial number     : 4B:86:87:7E:BE:2C:66:B9:45:44:25:1E:38:F6:37:31
issuer name       : C=FR, ST=Paris, L=Paris, O=Gandi, CN=Gandi Standard SSL CA 2
subject name      : OU=Domain Control Validated, OU=Gandi Standard Wildcard SSL, CN=*.linphone.org
issued  on        : 2015-09-23 00:00:00
expires on        : 2016-01-07 23:59:59
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.linphone.org, linphone.org
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
  This certificate has no flags
```

**Comment by jcowgill** [comment]
This also affects 2.1.3 (but not 2.1.2 which I was originally testing against).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-561

**Comment by mpg** [comment]
Thanks for your report! This was already reported [here](https://github.com/ARMmbed/mbedtls/issues/280#issuecomment-155764672) (though we should probably have opened a new issue to make it more visible). A fix is available in [its own branch](https://github.com/ARMmbed/mbedtls/commits/iotssl-541-pathlen-bugfix) (you'll find a similar branch for 2.1, 1.3 and 1.2) and will soon be merged and included in a released version.

Closing as a duplicate.

**Comment by jcowgill** [comment]
Ah sorry I didn't see that branch, but it does fix the bug for me so thanks.

**Comment by wolfeidau** [comment]
Is someone planning to publish 2.2.1 to mbed yotto repository it fixed the issue i had with chained certificates.

Cheers!

**Comment by sbutcher-arm** [comment]
A new release is due very soon, but I'm afraid I don't know the precise date. You shouldn't have to wait long though.
