### ISSUE TITLE
MBEDTLS_ERR_SSL_CONN_EOF

### ISSUE THREAD

**Issue by primesoftware** [ARMmbed/mbedtls#364]
I am curious why in ssl_tls.c there are several blocks (i.e. lines 6506 and 6522) that return 0 for MBEDTLS_ERR_SSL_CONN_EOF. Why not just return MBEDTLS_ERR_SSL_CONN_EOF? I am assuming this gets returned when the connection is closed. Not sure if it is really an error? The reason I ask is that the ssl_client2.c has an issue here:

```
            if( ret <= 0 )
            {
                printf("Code: %i", ret);
            	switch( ret )
                {
                    case MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY:
                        mbedtls_printf( " connection was closed gracefully\n" );
                        ret = 0;
                        goto close_notify;

                    case 0:
                    case MBEDTLS_ERR_NET_CONN_RESET:
                        mbedtls_printf( " connection was reset by peer\n" );
                        ret = 0;
                        goto reconnect;

                    default:
                        mbedtls_printf( " mbedtls_ssl_read returned -0x%x\n", -ret );
                        goto exit;
                }
            }
```
It returns 0 as if it were an error, but then nothing breaks the switch loop for case 0. Should there be a goto close_notify?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-560

**Comment by mpg** [comment]
Hi,

With TCP sockets the standard `recv()` API returns when the connection is closed by the peer. `mbedtls_ssl_read()` just mimicks this behaviour for consistency.

Regarding the `switch` statement in `ssl_client2.c`, don't forget that in C there is always an implicit fallback from one `case` to the next, unless it's explicitly prohibited by a `break;` statement. Here that means the same lines are executed when `ret == 0` and when `ret == MBEDTLS_ERR_NET_CONN_RESET`.

I hope this answers your question.

**Comment by primesoftware** [comment]
@mpg "Here that means the same lines are executed when ret == 0 and when ret == MBEDTLS_ERR_NET_CONN_RESET."

Yes, this is my question. Is this the appropriate behavior? I know when the server closes the connection you get a peer reset connection, but if that is the correct behavior for TCP then it should be labeled an error. Also, MBEDTLS_ERR_NET_CONN_RESET and MBEDTLS_ERR_SSL_CONN_EOF both return non 0 values as if they are errors (hence the ERR in the macro) when they are normal behavior. Also, should those switch case statements have a break so they do not loop through all conditions. Right now, I do not get a graceful shutdown.

**Comment by mpg** [comment]
Well, it's up to the application to decide whether the connection being reset by the peer, with or without a proper close notify, should be treated as an error or not. I the case of this example application, we decided to treat neither as an error, as we definitely expect the server to close the connection when it's done sending its response, and we use that client to test interop with a number of servers, some of which porperly send a close notify, and some of which don't, and we only want the client to exit non-zero when something went actually wrong.

Again, the meaning of "something went wrong" is up to your application to decide.

Regarding the switch statement, it doesn't need break statements as is has `goto`s already.
