### ISSUE TITLE
Migrate to new documentation platorm

### ISSUE THREAD

**Issue by bensze01** [ARMmbed/mbedtls#3643]
Since the recent changes in the release process, the documentation on the old website is getting outdated. We should move to a new documentation platform that can host the up-to-date documentation - preferably in a CI fashion.

The team has expressed a requirement for both versioned and unversioned documentation to be supported on whatever platform we migrate to.

Notes form the Read the Docs platform investigation:
* Automation support for automatically updating documentation as commits are added to branches.
* Support for versioned and unversioned documentation ("Single Version Documentation")
  * Versioned and unversioned documentation can co-exist in the same search space via the sub-project system.
  * This would require a separate branch or repo for the unversioned documentation.
* The breathe plugin can ingest the existing Doxygen in-code documentation, and display it in a style consistent with the rest of the documentation.

**Comment by yanesca** [comment]
Prerequisite: https://github.com/ARMmbed/mbedtls/issues/3852

The task is done once
- a Read the Docs project is set up for Mbed TLS
- version independent (https://github.com/ARMmbed/mbedtls-docs) documentation is displayed
- version dependant (doc directory in https://github.com/ARMmbed/mbedtls) documentation is displayed
- doxygen documentation in the latter is displayed in a consistent style

**Comment by davidhorstmann-arm** [comment]
The version-independent documentation has been set up with a Sphinx configuration in ARMmbed/mbedtls-docs#16. I have opened #4848 to track the migration of the version-dependent documentation at a future time. All that remains is to set up a Read The Docs project and move the version-independent documentation.

**Comment by yanesca** [comment]
Parts of the tasks have been moved to https://github.com/ARMmbed/mbedtls/issues/4862 and #4848. Everything else in this task is done.
