### ISSUE TITLE
How to port AES APIs to use to HW acceralator

### ISSUE THREAD

**Issue by boyina123** [ARMmbed/mbedtls#365]
The porting guidelines for AES APIs was given in below link:
https://github.com/ARMmbed/sal-stack-nanostack-private/blob/master/nanostack/platform/arm_hal_aes.h

Currently, those APIs defined in aes_mbedtls_adapter.c in mbed OS.
As this file in defined mbed os, can I over write my AES functions in this file with some build flag? 

Is it possible to define these APIs in nxp-rf-driver module and include in the build and suppress the aes_mbedtls_adapter.c for build?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-559

**Comment by mlnx** [comment]
@sbutcher-arm Please comment on this request

**Comment by RonEld** [comment]
Closing since this is outdated and replaced by mbed-OS 5
Please reopen if neccessary
