### ISSUE TITLE
Introduce MBEDTLS_PSA_CRYPTO_CONFIG for ECDSA

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3670]
The goal of this task is to kickstart the PSA cryptographic mechanism selection described in https://github.com/ARMmbed/mbedtls/blob/development/docs/proposed/psa-conditional-inclusion-c.md .

Create the infrastructure:

* Create `include/psa/crypto_config.h` (user-editable file) and `include/mbedtls/config_psa.h` (file that includes `"psa/crypto_config.h"` and defines induced symbols, and is not part of the Mbed TLS stable API).
* Add `MBEDTLS_PSA_CRYPTO_CONFIG` to `include/mbedtls/config.h`, defaulting off.
* In the stock `include/mbedtls/config.h`, add `#include "mbedtls/config_psa.h"`, guarded by `defined(MBEDTLS_PSA_CRYPTO_CONFIG)`.
* Turn off `MBEDTLS_PSA_CRYPTO_CONFIG` in the full config for now, until the build and test scripts have been adapted.
* In `all.sh`, add a build+test with the full config plus `MBEDTLS_PSA_CRYPTO_CONFIG` and `MBEDTLS_PSA_CRYPTO_DRIVERS` and `PSA_CRYPTO_DRIVER_TEST` minus `MBEDTLS_USE_PSA_CRYPTO`.

Add phase 1 ECDSA support:

* `config_psa.h`: conditionally define `MBEDTLS_PSA_BUILTIN_ALG_ECDSA` and `MBEDTLS_PSA_BUILTIN_ALG_DETERMINISTIC_ECDSA` based on `PSA_WANT_ALG_xxx` and `MBEDTLS_PSA_ACCEL_xxx`.
* `config_psa.h`: conditionally define `MBEDTLS_ECDSA_C` and `MBEDTLS_ECDSA_DETERMINISTIC`.
* Replace `MBEDTLS_ECDSA_xxx` by `PSA_WANT_ALG_ECDSA{,_DETERMINISTIC}`:
    * in code that calls PSA crypto APIs (except code guarded by `MBEDTLS_USE_PSA_CRYPTO` (which will be done later in https://github.com/ARMmbed/mbedtls/issues/3674);
    * in `psa_crypto*.c`, for code that runs outside of the driver dispatch;
    * but, in `psa_crypto*.c`, not for code that is specific to the built-in implementation: this code should not change.
* In `all.sh`, add a build+test with the full config plus `MBEDTLS_PSA_CRYPTO_CONFIG` and `MBEDTLS_PSA_CRYPTO_DRIVERS` and `PSA_CRYPTO_DRIVER_TEST` minus `MBEDTLS_USE_PSA_CRYPTO`, minus `MBEDTLS_ECDSA_C` and everything that relies on it, with `PSA_WANT_ALG_ECDSA` and `MBEDTLS_PSA_ACCEL_ALG_ECDSA`. This is only expected to build, not to pass tests, because the current test driver is a wrapper that can't calculate the signatures when the build-in code isn't available.
* Anything else caught during code inspection, review or testing.

**Comment by jdurkop** [comment]
@gilles-peskine-arm Couple of clarifying questions on the tasking as it relates to the documentation. My current dev branch for this effort can be found here, please feel free to check it out and let me know if there are any issues.

https://github.com/jdurkop/mbedtls/tree/psa-crypto-config-ecdsa-3670

1) Is the default configuration going to be updated to have PSA_WANT_ALG_ECDSA defined by default? After making changes suggested above, the default build will no longer pass tests because the ECDSA support usually built with MBEDTLS_ECDSA_C is now guarded by PSA_WANT_ALGS_ECDSA.

2) Is there a difference between implementations guarded by MBEDTLS_ECDSA_C and MBEDTLS_PSA_BUILTIN_ALG_ECDSA? The code mentions conditionally setting up the BUILTIN variant, but does not indicate where those guards should be used in the code.

**Comment by gilles-peskine-arm** [comment]
I expanded “Definition of internal inclusion symbols” in the specification in https://github.com/ARMmbed/mbedtls/pull/3697 . Hopefully this should make things clearer.

Please note that I've only written this up in English. There's a significant chance that you'll find typos, copypasta or outright design mistakes when you write actual code. Don't hesitate to let me know and to fix things if you figure out what's wrong.

To answer your specific question:

1. The default configuration won't change. More generally, any existing `config.h` should work (as long as it doesn't do anything “silly” like define an option that wasn't used before). The reason the default build should still pass is that `PSA_WANT_ALG_ECDSA` is now defined by `mbedtls/config_psa.h` which is included in (headers included by) `psa/crypto.h`.
2. For ECDSA, `MBEDTLS_ECDSA_C` and `MBEDTLS_PSA_BUILTIN_ALG_ECDSA` are equivalent. PSA code (`include/psa/crypto*.h` and `library/psa*.h` should use the new names, and non-PSA code should use the old names. The reasons for the duplication of symbol names are that a significant number of `MBEDTLS_PSA_BUILTIN_xxx` don't correspond exactly to existing `MBEDTLS_xxx` symbols, and that the more consistent naming separates the problems “I want this feature from Mbed TLS” [never mind how to get it] from “this is how to get this feature in Mbed TLS” [in case it's wanted].

**Comment by jdurkop** [comment]
Thanks for the clarification it does help some. I did have one final question. The tasking mentions replacing the ECDSA_C defines in library/psa*.c with the new ones for PSA_WANT_ALGS_ECDSA. If those changes are made, when MBEDTLS_PSA_CRYPTO_CONFIG is not defined the code will no longer build/test properly since some code will be removed since the PSA_WANT are not defined. Instead of replacing the ifdef should we make it an OR condition using both the MBEDTLS_ECDSA_C and PSA_WANT_ALGS_ECDSA?

**Comment by gilles-peskine-arm** [comment]
When `MBEDTLS_PSA_CRYPTO_CONFIG` is not defined and `MBEDTLS_ECDSA_C` is defined, `mbedtls/config_psa.h` defines `MBEDTLS_PSA_BUILTIN_ECDSA`.

It strikes me now that the tests for ECDSA through the PSA API should now use `PSA_WANT_ALG_ECDSA`, and we do want to execute them even when `MBEDTLS_PSA_CRYPTO_CONFIG` is not defined. So `mbedtls/config_psa.h` should also define `PSA_WANT_ALG_ECDSA`.

**Comment by jdurkop** [comment]
@gilles-peskine-arm Ok, I think this makes more sense now as long as config_psa.h is always included even if MBEDTLS_PSA_CRYPTO_CONFIG is not defined. The tasking listed above mentioned guarding the inclusion of config_psa.h, but if we instead moved the gaurding inside of config_psa.h to not process the PSA configuration like setting up the MBEDTLS_PSA_BUILTIN_* values then I think that would probably work. Is that what you were thinking too?

**Comment by jdurkop** [comment]
@gilles-peskine-arm I also updated my dev branch to show what I described above. If that seems reasonable I think this should be ready for a PR.

**Comment by gilles-peskine-arm** [comment]
Regarding the guarding of `config_psa.h`: yes, we can have all the guarding inside `config_psa.h`. What's important is that as long as `MBEDTLS_PSA_CRYPTO_CONFIG` is not defined, the build must work even if `config.h` does not include `config_psa.h`. Having the guard in `config.h` is an easy way to ensure that this is the case, even when we're testing with a `config.h` that's modified from the default and so has the conditional inclusion.

**Comment by gilles-peskine-arm** [comment]
Please make a PR for your test branch. It's easier to explore and comment on the code that way. And you get the benefit of CI feedback.

**Comment by jdurkop** [comment]
Sounds good. I created a PR here:
https://github.com/ARMmbed/mbedtls/pull/3712
