### ISSUE TITLE
MBEDTLS_PSA_CRYPTO_CONFIG for ECP (phase 1)

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3671]
Continuation of https://github.com/ARMmbed/mbedtls/issues/3670

Continue the process for `ALG_ECDH`, `KEY_TYPE_ECC_KEY_PAIR` and `KEY_TYPE_ECC_PUBLIC_KEY`.

**Comment by jdurkop** [comment]
@gilles-peskine-arm I have opened #3830 to address this ticket. I left a question on the initial version for you there if you don't mind taking a look. Thanks.
