### ISSUE TITLE
mbedtls_x509_string_to_names failed when names include some comma

### ISSUE THREAD

**Issue by Prochg** [ARMmbed/mbedtls#368]
mbedtls_x509_string_to_names use comma as the spilt of oid name,when some name include a comma it will faile with MBEDTLS_ERR_X509_UNKNOWN_OID.
such as:  O=xxxx Co., Ltd ,CN=xxx

**Comment by mpg** [comment]
I think you need to "escape" the embedded comma with a backslash. Otherwise there is no way for the function to guess what you mean.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-568

**Comment by Prochg** [comment]
i fixed it in other way.
it happen when i try get the subject name (mbedtls_x509_dn_gets) from a ssl-peer-cert and set to another cert (mbedtls_x509write_crt_set_subject_name).it  should be work,i think.

**Comment by mpg** [comment]
Closing this issue then. Also, please note that `mbedtls_x509_string_to_names()` is an internal function (you can still use it if you choose to, but don't be surprised if it changes).
