### ISSUE TITLE
mbedTLS on ST hardware

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbedtls#369]
mbedtls on mbedOS relies on K64F. It would be good to have mbedtls compile on ST platforms as well.

An example to be able to compile it on ST is at https://github.com/markus-becker-tridonic-com/mbedtls-yotta/blob/c1171ba1d859db9b1e8eb21151e8ce883233bc11/source/entropy_hardware_poll.c . This is a no-entropy hack, but at least one is able to run the mbed-client examples.

@bcostm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-571

**Comment by sbutcher-arm** [comment]
Thanks for the feedback. Support is already planned although we have no date yet as for when this may become available.

I will leave this issue open until support has been added to allow the issue to be tracked.

**Comment by markus-becker-tridonic-com** [comment]
@sbutcher-arm Any progress?

**Comment by sbutcher-arm** [comment]
Progress has been made, but I'm afraid I still don't have a date for when this will ship yet.

**Comment by markus-becker-tridonic-com** [comment]
Looks like this is solved in mbed5.1
