### ISSUE TITLE
FreeBSD seems under-provisioned in the CI

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#3700]
When a few CI runs are started around the same time, FreeBSD jobs run very slowly (around 5x slower than usual) and eventually time out. This is likely caused by under-provisioning of the FreeBSD machine(s). We should work with the infra team to improve that capacity - or if that can't be done, consider limiting the number of jobs Jenkins with push for FreeBSD concurrently (which would avoid time-outs, but at the cost of increased latency).

**Comment by daverodgman** [comment]
The CI has been adjusted so that we have 3 FreeBSD agents (instead of 1), each running a single executor (instead of 6). So total executors has halved, but the 3 should run better due to being isolated. So this should now be resolved.
