### ISSUE TITLE
Unconditional endianness macros

### ISSUE THREAD

**Issue by despair86** [ARMmbed/mbedtls#3704]
https://github.com/ARMmbed/mbedtls/blob/5cb54f7b27e1ebc1602233f50c44c1ff05304852/library/xtea.c#L40-L61
do these work as expected on _real_ big-endian machines? I don't have access to any to see for myself, but something tells me that XTEA ends up doing the exact opposite on big-endian systems (?)

which would be awkward if data was being exchanged across machines with differing endianness

**Comment by ronald-cron-arm** [comment]
This macro reads 4 bytes in memory and builds a four bytes integer from them. The byte at the lowest address in memory is handled as the most significant byte of the four bytes integer which corresponds to the big-endian order of multi-bytes integers in memory.
Then if you look at the bytes of "n" in memory, on a big-endian machine they will be in the same order as in "b" while on a little-endian machine they will be in reverse order.
That's my understanding of this. Does it help?

**Comment by despair86** [comment]
somewhat. but the question i was seeking to answer was whether or not these macros break the algorithm when presented with data and keys from machines with differing endianness.

**Comment by ronald-cron-arm** [comment]
GET_UINT32_BE reads in memory four bytes assuming those four bytes constitute a big-endian four bytes integer (most significant byte at the smallest address).  As long as the assumption is true, this macro can be used on a big-endian or little-endian machine.

**Comment by despair86** [comment]
ohhh
ok that makes sense
it effectively leaves the conversion itself to the app developer to handle
just that the algorithm as specified here expects big endian data

thanks!
