### ISSUE TITLE
Set up a webserver via MbedTLS

### ISSUE THREAD

**Issue by durun-durun** [ARMmbed/mbedtls#3711]
Hi,
have anyone a example for a webserver using the MbedTLS libs?
Can I base on the SSL Server example (https://github.com/ARMmbed/mbedtls/tree/development/programs/ssl)?

Thanks for help!

**Comment by yanesca** [comment]
Hi @durun-durun 

Thank you for your interest in Mbed TLS! 

Among the sample applications in that directory [ssl_server2.c](https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_server2.c) is the most up to date and most tested, thus that would be the best candidate to use as a starting point.

Also, [Hiawatha](https://www.hiawatha-webserver.org/) is a web server that uses Mbed TLS and it is open source, you could potentially find more production oriented example there.

**Comment by yanesca** [comment]
One more thing, in the future could you please submit questions to the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)? (We would prefer to reserve github for bug reports and feature requests.)

**Comment by durun-durun** [comment]
Thanks for your reply!
Yes, I go now this way!
