### ISSUE TITLE
Error handling of ccm assosiate data length.

### ISSUE THREAD

**Issue by soloicesky** [ARMmbed/mbedtls#3719]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug | Enhancement\Feature Request
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   

**Actual behavior**  

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb). If you can't find the answer you're looking for then please use the [Mbed TLS mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)**
I found an issue in ccm implementation. code block as follows:
![image](https://user-images.githubusercontent.com/5044681/94354874-f8e68380-00b1-11eb-80b5-f0eb96eee55a.png)
I think as your intent
Line#178 should be **add_len >= 0xFF00**
otherwise
line#224 to line#225 is conflicting with standard when aad_len = 0xFF00. because per standard aad_len should encoded as six octets but current is 2.
![image](https://user-images.githubusercontent.com/5044681/94354934-54187600-00b2-11eb-9956-6a85714ff89c.png)

**Comment by yanesca** [comment]
Thank you for reporting this  bug!
