### ISSUE TITLE
PSA Crypto key generation doesn't support Curve25519 without Everest

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#3727]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
N/A

**mbed TLS build:**  
development

**Peer device TLS stack and version**  
N/A

**Expected behavior**   
`psa_generate_key` can generate a Curve25519 key independent of whether the ECDH implementation is Everest or mbed TLS.

**Actual behavior**  
`psa_generate_key` fails with a `NOT_SUPPORTED` error when Everest is not present.

**Steps to reproduce**  
Try to generate a Curve25519 key without Everest compiled in.

I've traced this back to mbed TLS' `ecp.c`, where the Curve25519 curve ID is guarded behind `MBEDTLS_ECDH_VARIANT_EVEREST_ENABLED`. The PSA Core calls `mbedtls_ecp_curve_info_from_grp_id` (which will fail to find Curve25519 since it checks the list in `ecp.c`) solely to figure out the bit size of a curve. I suggest adding knowledge of bit sizes to the PSA Crypto core instead, where the Everest guard can be dropped (to preserve TLS behaviour).
`mbedtls_ecc_group_of_psa` defines Curve25519 as a 255-bit curve, but `mbedtls_ecp_curve_info_from_grp_id` proclaims it is a 256-bit curve. @gilles-peskine-arm which of the two should PSA Crypto adhere to?

**Comment by gilles-peskine-arm** [comment]
Ugh, another key size issue. Curve25519 has a private key which is a 256-bit string whose most significant bit is 0… So is it a 255-bit key or a 256-bit key? Consistency with other key types in PSA crypto makes it 255 but consistency with other libraries tends to make it 256.

Thanks for doing the analysis. So it looks like https://github.com/ARMmbed/mbedtls/pull/3512/commits/2f77505553a5012e82f507560df7447f32b31766 would fix it, right? What is listed in `ecp_supported_curves` shouldn't have depended on whether Everest was enabled, but we made a mistake in the PR that enabled Everest. I'll make sure fixing that is prioritized, and also adding a test case for Curve25519 key generation.

**Comment by stevew817** [comment]
That would fix it. Thanks for the swift action!

**Comment by stevew817** [comment]
On second thought, it wouldn't resolve the bit size mismatch though. Currently that's fine since `mbedtls_ecc_group_of_psa` takes bytes instead of bits (and theamount of bytes to contain 255 and 256 are equal), but users would need to set key bits to 256 instead of 255 for key attributes belonging to a Curve25519 key.

Should probably be documented somewhere, and `mbedtls_ecc_group_of_psa` updated accordingly?

**Comment by stevew817** [comment]
@gilles-peskine-arm I went back to the PSA Crypto API specification, and it apparently [specifically states that key_bits == 255 for curve25519](https://armmbed.github.io/mbed-crypto/html/api/keys/types.html?highlight=montgomery#c.PSA_ECC_FAMILY_MONTGOMERY). That patch is thus incomplete from a fixing the Crypto core perspective.

**Comment by gilles-peskine-arm** [comment]
@stevew817 Right. Turns out the size check is actually a leftover that's no longer needed. So the fix should be easy (let's see if CI agrees): https://github.com/ARMmbed/mbedtls/pull/3730
