### ISSUE TITLE
Setting Invalid Curves using the function mbedtls_ssl_conf_curves can lead to a segmentation fault in ssl_write_supported_elliptic_curves_ext

### ISSUE THREAD

**Issue by JayaraghavendranK** [ARMmbed/mbedtls#373]
The function mbedtls_ssl_conf_curves is implemented as shown below, where there is no validation for the curves being passed. Is this Intentional (is there an implicit trust that user will always pass only the appropriate supported curves)?

``` C
    void mbedtls_ssl_conf_curves( mbedtls_ssl_config *conf,
                             const mbedtls_ecp_group_id *curve_list )
    {
         conf->curve_list = curve_list;
    }
```

In the function ssl_write_supported_elliptic_curves_ext, which is called from ssl_write_client_hello, the structure info is retrieved and accessed based on the curves set in the function mbedtls_ssl_conf_curves which if invalid could lead to a segmentation fault. Check the below code snippet from ssl_write_supported_elliptic_curves_ext:

``` C
    #if defined(MBEDTLS_ECP_C)
        for( grp_id = ssl->conf->curve_list; *grp_id != MBEDTLS_ECP_DP_NONE; grp_id++ )
        {
            /** info is being retrieved from user set list. It may return NULL if invalid curves are set **/
            info = mbedtls_ecp_curve_info_from_grp_id( *grp_id );
    #else
        for( info = mbedtls_ecp_curve_list(); info->grp_id != MBEDTLS_ECP_DP_NONE; info++ )
        {
    #endif
         /**** Possible Bug: Even for invalid curves the count will be increased ****/
         elliptic_curve_len += 2;
      }

      if( end < p || (size_t)( end - p ) < 6 + elliptic_curve_len )
      {
            MBEDTLS_SSL_DEBUG_MSG( 1, ( "buffer too small" ) );
            return;
      }

      elliptic_curve_len = 0;

     #if defined(MBEDTLS_ECP_C)
     for( grp_id = ssl->conf->curve_list; *grp_id != MBEDTLS_ECP_DP_NONE; grp_id++ )
     {
        /** info is being retrieved from user set list. It may return NULL if invalid curves are set **/
        info = mbedtls_ecp_curve_info_from_grp_id( *grp_id );
     #else
     for( info = mbedtls_ecp_curve_list(); info->grp_id != MBEDTLS_ECP_DP_NONE; info++ )
     {
     #endif

      /**** Possible Bug: info will be NULL and can be accessed below if one of curves set using   mbedtls_ssl_conf_curves is invalid  ****/
        elliptic_curve_list[elliptic_curve_len++] = info->tls_id >> 8;
        elliptic_curve_list[elliptic_curve_len++] = info->tls_id & 0xFF;
    }
```

Fix Suggestions:

Since, the function mbedtls_ssl_conf_curves doesn't return anything adding a check there may not be feasible, a NULL check can be added in 
ssl_write_supported_elliptic_curves_ext to prevent this. 

Code snippet for the suggested fix:

``` C
    #if defined(MBEDTLS_ECP_C)
    for( grp_id = ssl->conf->curve_list; *grp_id != MBEDTLS_ECP_DP_NONE; grp_id++ )
    {
        info = mbedtls_ecp_curve_info_from_grp_id( *grp_id );
    #else
    for( info = mbedtls_ecp_curve_list(); info->grp_id != MBEDTLS_ECP_DP_NONE; info++ )
    {
    #endif

       if (NULL != info)
        elliptic_curve_len += 2;
    }

    if( end < p || (size_t)( end - p ) < 6 + elliptic_curve_len )
    {
        MBEDTLS_SSL_DEBUG_MSG( 1, ( "buffer too small" ) );
        return;
    }

    elliptic_curve_len = 0;

    #if defined(MBEDTLS_ECP_C)
    for( grp_id = ssl->conf->curve_list; *grp_id != MBEDTLS_ECP_DP_NONE; grp_id++ )
    {
        info = mbedtls_ecp_curve_info_from_grp_id( *grp_id );
    #else
    for( info = mbedtls_ecp_curve_list(); info->grp_id != MBEDTLS_ECP_DP_NONE; info++ )
    {
    #endif

       if(NULL != info)
       {
            elliptic_curve_list[elliptic_curve_len++] = info->tls_id >> 8;
            elliptic_curve_list[elliptic_curve_len++] = info->tls_id & 0xFF;
       }
    }
```

Note: If there is an assumption that it is the responsibility of the layer above mbedtls to ensure only valid curves are to be set, then the statement " info = mbedtls_ecp_curve_info_from_grp_id( *grp_id );" can be removed from the first loop in the code snippet above. info is not being used in that loop and is being retrieved again in the second loop.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-580

**Comment by mpg** [comment]
Thanks for your report! At first glance I agree with your analysis.

Generally speaking, we do expect users to pass valid parameters to the various `mbedtls_ssl_conf_xxx()` functions, but indeed we should probably avoid crashing when that's not the case.

**Comment by RonEld** [comment]
Closing, as I believe that https://github.com/ARMmbed/mbedtls/commit/4e03439e6a915bdafcd2adc6596f98a2e834f315 has fixed this, and has already been merged.
If you think that this issue was closed mistakingly, please reopen
