### ISSUE TITLE
Clarification on PSA key algorithm restriction for agreement/derivation

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#3741]
### Description
- Type: Inconsistency/Question

---------------------------------------------------------------
## Question
PSA says (on the topic of key usage restrictions) :
`
In addition to the usage bitmask, a policy specifies which algorithm is permitted with the key. This specification only defines policies that restrict keys to a single algorithm, which is consistent with both common practice and security good practice.
`

This is implemented super strict inside of `psa_crypto.c`, and I'm wondering why it does so. Consider a key used for ECDH, stored non-exportable persistent. The algorithm declared when generating the key needs to match strictly with the algorithm the key is used for.

1. If one wants to use the key with `psa_raw_key_agreement()`, it needs to be defined with `PSA_ALG_ECDH`, and the core doesn't care what happens with the shared secret.
2. If one wants to use the key with `psa_key_derivation_key_agreement()`, then it needs to be defined with `PSA_ALG_KEY_AGREEMENT(PSA_ALG_ECDH, PSA_ALG_xKDF(PSA_ALG_xHASH))`, all depending on which KDF is used. The key is thus bound to one specific combination of both agreement, derivation and hash primitive algorithms.

The question then begs: a key declared for use with `PSA_ALG_ECDH`, shouldn't that be allowed to be presented to `psa_key_derivation_key_agreement` for use of a combined agreement/derivation operation? Since it is under-specified in a way?

I assume this'll be a larger problem when porting the TLS portion on top of PSA Crypto with long-term keys. If you have an ECDH key, and didn't specify a restriction on derivation algorithm, it really shouldn't matter for the usage restriction which derivation algorithm you're using after the agreement step.

**Comment by gilles-peskine-arm** [comment]
Yes, this makes sense. The PSA interface aims at keeping key policies simple (in particular we rejected policy expressions such as A or B), but there is a precedent for a policy “wildcard” (signature key that allows any hash), and it makes sense similarly to have `PSA_ALG_ECDH` be a “wildcard” that allows either raw key agreement or key agreement combined with any KDF.

This is a backward compatible extension so it can be added to the PSA Crypto specification in a 1.x version.

**Comment by stevew817** [comment]
On the same note: calling `psa_key_derivation_key_agreement` doesn't currently 'unlock the permission to output to a key object'. I assume that's a bug?

**Comment by gilles-peskine-arm** [comment]
Sorry, I don't understand 'unlock the permission to output to a key object'.

**Comment by stevew817** [comment]
`operation->can_output_key` is not being set if a key is added to the derivation operation through `psa_key_derivation_key_agreement`, meaning `psa_key_derivation_output_key` will refuse to output a key if the derivation is key agreement based.

**Comment by gilles-peskine-arm** [comment]
Ah ok. That would indeed be a bug. Please file it separately.
