### ISSUE TITLE
Build error (compiler not in C99 mode)

### ISSUE THREAD

**Issue by kotegowder** [ARMmbed/mbedtls#3771]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 72ca39737f974db44723760623d1b29980c00a88  

**Actual behavior**  
Seeing build error:
mbedtls/library/ssl_msg.c: In function 'mbedtls_ssl_cf_memcpy_if_eq':
../mbedtls/library/ssl_msg.c:1168:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < len; i++ )
     ^
../mbedtls/library/ssl_msg.c:1168:5: note: use option -std=c99 or -std=gnu99 to compile your code

**Steps to reproduce**  
cd <mbedtls source directory>
mkdir <build dir>
cd <build dir>

cmake -D CMAKE_BUILD_TYPE=Debug ../
cmake --build .
----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

Please provide fix for this?

**Comment by gilles-peskine-arm** [comment]
This is a [known defect](https://github.com/ARMmbed/mbedtls/issues/3631) in our cmake script: it doesn't detect older compilers that default to C89 mode. There's [work in progress to fix it](https://github.com/ARMmbed/mbedtls/pull/3641).

What compiler (looks like GCC, but what version) are you using and what version of cmake?

**Comment by kotegowder** [comment]
cmake version 3.10.2
 gcc (GCC) 4.8.5 20150623

**Comment by gilles-peskine-arm** [comment]
All right, thanks for the information. So this is already covered by the [existing issue](https://github.com/ARMmbed/mbedtls/issues/3631).

**Comment by gilles-peskine-arm** [comment]
In the meantime, as a workaround, you can pass `-std=c99` explicitly in `CFLAGS` when using GCC 4.x.
