### ISSUE TITLE
Some test code breaks the contract of the code under test wrt buffer size

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#3792]
### Description
- Type: Bug (in test code, not the library itself)
- Priority: Minor

---------------------------------------------------------------

For example, see ccm_lengths() in test_suite_ccm.function. This declares the add[] buffer as 10 bytes, which it passes on to mbedtls_ccm_encrypt_and_tag, along with whatever value of add_len was specified in test_suite_ccm.data. So for values of 10 < add_len < 0xFF00, the test reads off the end of the add buffer and may crash.

Suggest reviewing test code for similar issues, and fixing by using ASSERT_ALLOC_WEAK to allocate the add buffer.

**Comment by gilles-peskine-arm** [comment]
The CCM `add_len` case isn't a problem with the current code because it checks the range of `add_len` before trying to access the buffer. However this could be a bug in an alternative implementation (i.e. `MBEDTLS_CCM_ALT`) or in a future implementation where `mbedtls_ccm_xxx` calls `psa_xxx`.
