### ISSUE TITLE
programs/ssl/ssl_context_info.c fails to compile if `char` is unsigned

### ISSUE THREAD

**Issue by d3zd3z** [ARMmbed/mbedtls#3794]
### Description
- Type: Bug
- Priority: Minor

## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.24.0

**Expected behavior**   

**Actual behavior**
When compiling on a target with `char` as unsigned (arm64 Linux), compilation fails with:
```
../programs/ssl/ssl_context_info.c: In function ‘read_next_b64_code’:                                │
../programs/ssl/ssl_context_info.c:382:16: error: comparison is always true due to limited range of d│
ata type [-Werror=type-limits]                                                                       │
  382 |     while( EOF != c )                                                                        │
      |                ^~                                                                            │
```

**Comment by gilles-peskine-arm** [comment]
There are independent two pull requests to fix this, but both require changes and I don't think anybody is actively working on them: https://github.com/ARMmbed/mbedtls/pull/3449 and https://github.com/ARMmbed/mbedtls/pull/3567
