### ISSUE TITLE
Qemu testing: investigation

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3795]
Investigate how to run cross-compile Mbed TLS and run unit tests in Qemu.

* Host operating system: Linux (Ubuntu 16.04, Ubuntu 18.04 or Ubuntu 20.04).
* Target operating system: Linux (no particular constraint; eventually we'll want to run tests with small libc such as uclibc or musl, but for now any target environment will do).
* Compiler: gcc or clang (we don't care at this point).
* Target machine architecture: anything that Qemu supports, but focusing on Arm for a start.

The goal of this task is to write a document (e.g. wiki page) that a developer can follow to:

* Set up the host machine: what packages to install for cross-compilation, Qemu, target system image.
* Cross-compile.
* Run one unit test program and get results.
* Run the whole test suite. This may require different instructions after a make build (where we normally run `run-test-suites.pl`) and after a cmake build (which runs `ctest`).

Foreseeable extensions:

* Optimize the target system image for quick download and startup.
* Update the Docker images on the CI to have the necessary tools for some chosen target platforms.
* Patch test scripts if necessary so that the tests can be run automatically in a CI environment.
* Add components to `all.sh` to do Qemu-based testing for some platforms.
* TLS tests on the target.
* Bare metal target system.

**Comment by chris-jones-arm** [comment]
Running cross-compiled code via Qemu (user mode) should be a simple task once the required dependencies are correctly installed.
The following instructions are an example of how the arm-linux gcc compiler can be used to cross compile MbedTLS, on an Ubuntu 18.04 host machine, however the process should be almost identical for any other architecture and corresponding cross-compiler.

**Dependencies**
- Install Qemu user mode:
`$ apt-get install qemu-user`

- Install compiler for required architecture:
`$ apt-get install gcc-arm-linux-gnueabi`

**Compiling and running tests**
- Cross-compile MbedTLS:
`$ make CC=arm-linux-gnueabi-gcc`

- Double check the compiled files have been compiled for the correct architecture (it doesn't matter which file is checked):
    ```
    $ file library/des.o
    library/des.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
    ```
- Run tests, specifying the path to our toolchain:
`$ QEMU_LD_PREFIX=/usr/arm-linux-gnueabi make check`

**Comment by gilles-peskine-arm** [comment]
How does Qemu determine exactly what hardware platform to emulate?

In particular, we'll sometimes want to run the same binary with different emulated hardware. For example an Aarch64 binary running on (emulated) hardware with or without the armv8 crypto extensions. How would we specify “run `make test` on a platform with crypto extensions” vs “run `make test` on a platform without crypto extensions”?

**Comment by yuhaoth** [comment]
> 
> 
> How does Qemu determine exactly what hardware platform to emulate?
> 

qemu-aarch64 -cpu <cputype> , that will emulator different cpu

**Comment by chris-jones-arm** [comment]
Building upon @yuhaoth's answer, to do this via the semi-transparent execution method listed above you can do:
```
#specify the toolchain to use
$ export QEMU_LD_PREFIX=/path/to/toolchain

#specify the processor to use (use qemu-x -cpu help for a list of supported processors)
$ export QEMU_CPU=cortex-a8

#controls hwcaps to specify processor capabilities (turns on/off different crypto extensions)
$ export QEMU_CUST_FEATURE=0x800
$ make test
```

**Comment by chris-jones-arm** [comment]
Upon further investigation there does not appear to be any way to specify exact hardware capabilities in Qemu.

While certain capabilities can be controlled through use of the cpu flag this is limited to the number of options in Qemu (~30 mostly older 32-bit processors and 3 aarch64 processors). Because of this it is not possible to directly turn on or off the armv8 cryptography extensions however if simply testing that Mbed TLS should run on other architectures then this method should be sufficient.
