### ISSUE TITLE
Minimalist mbedTLS

### ISSUE THREAD

**Issue by primesoftware** [ARMmbed/mbedtls#381]
I am looking into building mbedTLS into a game engine to handle networking so I only plan on using it programmatically (no CLI). Also, I only need to support TLS1.1 and TLS1.2. What is the best config to use for that purpose. I do not control the server end so I am assuming 

```
#define MBEDTLS_SSL_MAX_CONTENT_LEN
```
should not be set as per the comments. Is config-mini-tls1_1.h a good start? What needs to be modified to include TLS1.2 also?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-586

**Comment by mpg** [comment]
If you choose to use `config-mini-tls1_1.h` as a starting point, I recommend you replace DES with AES, as there is not reason to use 3DES theses days except if you want to interact with particularly old peers, but then they probably won't support TLS 1.1 anyway. If you want a fairly minimal and modern TLS 1.1/1.2 config, I'd recommend you somehow merge `config-mini-tls1_1.h` (with AES substituted to DES) with `config-suiteb.h` which adds support for TLS 1.2, ECC and AES-GCM. You'll most likely want to add the `ECDHE_RSA` key exchange too.

You're correct that you should not change the value of `MBEDTLS_SSL_MAX_CONTENT_LEN` in your case. Regarding the other parameters in `config-suiteb.h`, they mostly control trade-offs between resource usage and speed, so it's up to you to decide what's the best trade-off in your case. I recommend you keep the default value unless you know (eg from measuring resource usage) you need to change them.

Finally, please note that "the best config" is highly dependent on your specific needs. We do provide a lot of configurability and documentation, and can also give general advice as above, but at the end of the day, only you can find out what the "best" config is for you.
