### ISSUE TITLE
Example needed how to load certificates from memory using libcurl

### ISSUE THREAD

**Issue by mindej** [ARMmbed/mbedtls#382]
Hello I am implementing an application with libcurl. I have a certificate and private key in memory.
```
const chat *cert = "-----BEGIN CERTIFICATE----- ...."; 
const char *key = "-----BEGIN RSA PRIVATE KEY----- ....";
```
I have found an example in to do so with openSSL http://curl.haxx.se/libcurl/c/usercertinmem.html but according to documentation this approach is for OpenSSL or wolfSSL/CyaSSL

Maybe one of you have an example how to to do it ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-587

**Comment by mpg** [comment]
I think [`mbedtls_x509_crt_parse()`](https://tls.mbed.org/api/group__x509__module.html#ga033567483649030f7f859db4f4cb7e14)  and [`mbedtls_pk_parse_key()`](https://tls.mbed.org/api/pk_8h.html#a072d27dc4143bfd600786232f9417e08) are the functions you're looking for.
