### ISSUE TITLE
cmake: use of `target_sources` only available in newer cmake versions

### ISSUE THREAD

**Issue by d3zd3z** [ARMmbed/mbedtls#3825]
### Description
- Type: Bug
- Priority: Minor

The top-level `CMakeLists.txt` file sets a CMake minimum version to 2.6. However, several of the `CMakeLists.txt` files use the command `target_sources` which was only added to cmake in 3.0.0. This results in a error when running cmake.

## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 01fc2099694e6abad21ec507e7ec211c1e65f6b4
OS version: Fedora 32

**Expected behavior**   
Running `cmake` generates build scripts for the desired build system.

**Actual behavior**  
If cmake < 3.0 is used, this results in the error:
```
CMake Error at programs/fuzz/CMakeLists.txt:39 (target_sources):
  Unknown CMake command "target_sources".
```

**Steps to reproduce**  
``` sh
mkdir build
cd build
../cmake ..
```

**Comment by gilles-peskine-arm** [comment]
Since [today](https://github.com/ARMmbed/mbedtls/pull/3802) the minimum required CMake version is officially 2.8.12 (the version on CentOS 7).

**Comment by paul-elliott-arm** [comment]
see also https://github.com/ARMmbed/mbedtls/issues/3788

**Comment by d3zd3z** [comment]
I would consider this the same as #3788, so I'll close this as a duplicate.
