### ISSUE TITLE
Yotta gcc debug build fails

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbedtls#383]
Build fails when building mbedtls with following configuration:
```
yt target frdm-k64f-gcc
yotta build --debug-build
```
The produced error is:
*/mbedtls/yotta/module/source/bignum.c: In function 'mpi_mul_hlp':
mbedtls/yotta/module/source/bignum.c:1159:1: error: r7 cannot be used in asm here*

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-588

**Comment by mpg** [comment]
The workaround is to disable `MBEDTLS_HAVE_ASM` in `config.h`, using the method explain [here](https://github.com/ARMmbed/mbedtls/blob/1285ab5dc26948e6f937f6ab0cdabe5ffca11259/yotta/data/README.md#configuring-mbed-tls-features)

We're working on a proper fix.

**Comment by edsiper** [comment]
is there any estimated date for the fix ?

**Comment by sbutcher-arm** [comment]
This issue has been resolved in the last mbed TLS yotta release, and because this issue was a duplicate it was missed when the bug was closed.
