### ISSUE TITLE
CMake: test MBEDTLS_TARGET_PREFIX support

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3832]
https://github.com/ARMmbed/mbedtls/pull/3407 improves CMake build scripts to allow modifying the names of target files by prepending `MBEDTLS_TARGET_PREFIX`. Since `MBEDTLS_TARGET_PREFIX`, there's a risk that this feature will break, for example because some code in a `CMakeLists.txt` hard-codes a target name instead of using the new variables.

The goal of this pull request is to add a component to `all.sh`, or modify an existing one, that sets `MBEDTLS_TARGET_PREFIX` and that would break if `MBEDTLS_TARGET_PREFIX` is not used everywhere it should be.

**Comment by bensze01** [comment]
@gilles-peskine-arm `MBEDTLS_TARGET_PREFIX `is tested. The `cmake_subproject` test [was modified](https://github.com/ARMmbed/mbedtls/pull/3407/files#diff-0c4cb1578f651514fd7632223957d5a044b11fdc1dbd536d9d709a5c7299941c) in the merged PR to also test this feature.

**Comment by gilles-peskine-arm** [comment]
Oh, thank you! I saw that there was no change to `all.sh` and missed that it was tested this way.
