### ISSUE TITLE
Migrate Travis testing to the .com domain

### ISSUE THREAD

**Issue by bensze01** [ARMmbed/mbedtls#3837]
[Travis will be making the .org domain read-only on December 31 2020.](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) In the meantime, [they have reduced the job allowances on the .com domain](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions), which may contribute to the issue we are seeing with travis builds for PRs hanging for a long time (the time our builds spent in queue on an org level has increased by _1504%_ recently, according to stats from travis)

If we want to keep the travis tests functional, we have to migrate to the .com domain by the end of the year, however we should consider migrating as soon as possible, since that would result in more available jobs to run our tests, and fewer tests getting cancelled.

**Comment by mpg** [comment]
It looks to me that this task was already completed. @bensze01 can you confirm and close the issue if you agree?

**Comment by mpg** [comment]
Well, we're past the deadline and Travis is still working, so I'm taking this as a confirmation that everything is in order and closing this issue. Please re-open if I'm wrong and there's still work to track here.
