### ISSUE TITLE
Update PSA test suites to NOT use UID=0 (ITS).

### ISSUE THREAD

**Issue by bykyjung** [ARMmbed/mbedtls#3838]
### Description
- Type: Bug | Enhancement\Feature Request

---------------------------------------------------------------
## Bug

There are many PSA test vectors that still use UID=0, according to the ITS specification, only the nonzero UIDs should be accepted. This makes it impossible to run e.g. opaque tests where we want to use our own backend implementation for ITS where it rejects UID=0.

**Comment by gilles-peskine-arm** [comment]
@silabs-PeterK Pinning an issue puts it at the top of the issue list it for everyone, not just for you. So please don't use that as a bookmark. It's designed for very important things that everyone needs to know about.

**Comment by silabs-PeterK** [comment]
@gilles-peskine-arm Sorry, I thought its only for me.
