### ISSUE TITLE
PolarSSL 1.2 does not build with Visual Studio 2010

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#385]
Recent versions of PolarSSL 1.2 (1.2.18 and earlier) do not build under Visual Studio 2010, although they do build on later versions of Visual Studio - 2013 and 2015.

Other later versions of mbed TLS are unaffected.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-590

**Comment by mpg** [comment]
Unless I'm mistaken, you fixed that in 1.2.19, so I'm closing that bug now.
