### ISSUE TITLE
Create a public documentation repository

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3852]
Create a public repository for documentation.

* Lightweight review process.
* No CI (except DCO?).
* License?
* Precursor to https://github.com/ARMmbed/mbedtls/issues/3643. The goal of this task is only to set up the repository, not to arrange to serve it through readthedocs.

**Comment by gilles-peskine-arm** [comment]
- [ ] Create the new repository https://github.com/ARMmbed/mbedtls-docs
- [ ] Create a minimal readme file explaining what's in there.
- [ ] Indicate what the license is (Apache license, so that content can be moved freely between Mbed TLS itself and the documentation repository). → https://github.com/ARMmbed/mbedtls-docs/pull/1
- [ ] Enforce that contributions have a developer certificate of origin.

**Comment by tom-daubney-arm** [comment]
Given that the DCO enforcing is now operational, I will close this issue.
