### ISSUE TITLE
UWP outputs "mbedTLS(C): mbedtls_ssl_fetch_input() returned -76 (-0x004c)"

### ISSUE THREAD

**Issue by ionutcosminmihaipfa** [ARMmbed/mbedtls#3873]
### Description
- Type: Bug
- Priority: Blocker | Major | Minor
I found that on UWP the SSL handhsake is not usccessfull:
```
BLIP[->wss://nameserver.com:443/db/_blipsync] performNextMessage
task 3 calling Actor<0000014833A09890>mbedTLS(C): mbedtls_ssl_fetch_input() returned -76 (-0x004c)
mbedTLS(C): ssl_get_next_record() returned -76 (-0x004c)
Pull->wss://nameserver.com:443/db/_blipsync performNextMessage2
mbedTLS(C): mbedtls_ssl_read_record() returned -76 (-0x004c)
ClientSocket got POSIX error 5 "Input/output error"
Received -1 bytes from socket 1
task 6 calling Actor<0000014833F28600>Close with error
```

The above problem seems to come from bio_return_value which handles the 10035 (WSAEWOULDBLOCK) as fatal error.
According to Microsoft documentation (https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2), WSAEWOULDBLOCK it's not a fatal error, and the operation should be retried later.

I changed 
```
ret = ssl->f_recv(ssl->p_bio,
                            ssl->in_hdr + ssl->in_left, len);
```

to
```
                   unsigned count = 0;
                    do
                    {
                        ret = ssl->f_recv(ssl->p_bio,
                            ssl->in_hdr + ssl->in_left, len);
                        count++;
                        if (count > WSAEWOULDBLOCK_RETRY_ATTEMPTS)
                            break;
                    } while (ret == -0x4C);
```

in mbedtls_ssl_fetch_input function and it looks like the handshake succeeds.

What do you think about this handling? How should this be done?

---------------------------------------------------------------
## Bug

**OS**  
windows 10

**mbed TLS build:**  
Version: ec3a2712b1bd77158dd42b28681101c4da6f3c93
OS version: Windows 10
Configuration: The lib is used under a UWP application
Compiler and options: Obtained the .lib compiling couchbase-lite-C

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   
The SSL handshake should succeeed

**Actual behavior**  
The SSL handshake fails with the following error: mbedtls_ssl_fetch_input() returned -76 (-0x004c)

**Steps to reproduce**  
Not straight forward to reproduce as it's integrated in a bigger app.

**Comment by gilles-peskine-arm** [comment]
`f_recv` should conform to the [documentation of its type `mbedtls_ssl_recv_t`](https://tls.mbed.org/api/ssl_8h.html#ac06b19b96b643090c55f19b6c28b10c4):

> If performing non-blocking I/O, `MBEDTLS_ERR_SSL_WANT_READ` must be returned when the operation would block.

It looks like your implementation of `f_recv` does not translate error codes correctly. The [built-in implementation `mbedtls_net_recv`](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.24.0/library/net_sockets.c#L540) returns `MBEDTLS_ERR_SSL_WANT_READ` if `read` fails and `errno` is `EAGAIN` or `EWOULDBLOCK`. I don't know how these functions map to the lower-level win32 APIs, maybe some extra condition is missing there.

Are you using a custom `f_recv`, or the built-in `mbedtls_net_recv`?

I don't see any bug in `mbedtls_ssl_fetch_input`. In non-blocking mode, it is not supposed to block: it's supposed to propagate `MBEDTLS_ERR_SSL_WANT_READ` to its caller.

**Comment by borrrden** [comment]
LiteCore does override the `f_recv` function, to provide some context.  Pretty much everything I am going to talk about in this comment is in [this file](https://github.com/couchbasedeps/sockpp/blob/TLS/src/mbedtls_context.cpp) which hooks into the socket library we are using.  Of note in there is the `setup_bio` function, which depending on the mode either sets `f_recv` or `f_recv_timeout`.  In the end both of these make their way to calls to `recv` as the actual operation on the socket so it looks like a thinner version of what the library would be doing.  However, it seems like even if the default function were being used, this error code would not be appropriate for retry right?

**Comment by gilles-peskine-arm** [comment]
Right, `EIO` is not appropriate for retry. Looks like [`bio_return_value`](https://github.com/couchbasedeps/sockpp/blob/TLS/src/mbedtls_context.cpp#L401) is doing the right thing by translating `EINTR`, `EAGAIN` and `EWOULDBLOCK` into `MBEDTLS_ERR_SSL_WANT_{READ,WRITE}`, but [`stream().read_r`](https://github.com/couchbasedeps/sockpp/blob/TLS/src/mbedtls_context.cpp#L311) is returning `EIO` when it should be returning `EWOULDBLOCK`.

**Comment by ionutcosminmihaipfa** [comment]
Ok, so the solution seems to be to add the below case to have the same effect as `EWOULDBLOCK` under bio_return_value, I tested it and it works, I'll add a pull request if you think it's correct.
```
#if defined(WSAEWOULDBLOCK)
				case WSAEWOULDBLOCK:
#endif
```

**Comment by gilles-peskine-arm** [comment]
Where would you add this code? `mbedtls_net_recv` already checks for `WSAEWOULDBLOCK` via `net_would_block`.

**Comment by ionutcosminmihaipfa** [comment]
Right, it's a [modification ](https://github.com/couchbasedeps/sockpp/blob/8dad5c3c2dc7e5b926bcf4e2fb3ec272dc85dff1/src/mbedtls_context.cpp#L401)for [sockpp ](https://github.com/couchbasedeps/sockpp) project not for this one.

**Comment by gilles-peskine-arm** [comment]
Alright, I'm glad you managed to locate the root cause.

**Comment by ionutcosminmihaipfa** [comment]
Thanks for pointing it out to me.
