### ISSUE TITLE
uninstalling psa header files does not appear in Makefile

### ISSUE THREAD

**Issue by goodwaterwu** [ARMmbed/mbedtls#3909]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|
all
**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**

Type "make uninstall" command should delete psa header files

**Actual behavior**  

Type "make uninstall" command does not delete psa header files

**Steps to reproduce**  

"make install" then "make uninstall"
_Maybe add "rm -rf $(DESTDIR)/include/psa" to uninstall part in Makefile?_

**Comment by mpg** [comment]
Hi @goodwaterwu, and thanks for your report! I was able to confirm the issue, and the modification you suggest looks like the correct fix indeed. Would you like to submit a PR with that patch?

**Comment by chris-jones-arm** [comment]
This has been fixed in #3917 and has now been merged. Thank you for your report and subsequent fix!
