### ISSUE TITLE
How can I use MBEDTLS as an SSL bidirectional authenticated server?

### ISSUE THREAD

**Issue by wowyyy** [ARMmbed/mbedtls#3940]
How do I code to use EMBEDTLS as a server and is bi-certificated?

There are no examples of this in official procedures.

**Comment by gilles-peskine-arm** [comment]
Server authentication is automatic. (You can turn it off, but you should not.)

To require client authentication, call
```
mbedtls_ssl_conf_authmode( &conf, MBEDTLS_SSL_VERIFY_REQUIRED );
mbedtls_ssl_conf_ca_chain( &conf, &ca_cert, NULL );
```
where `ca_cert` is your trusted CA certificate (or a list of trusted CA certificates). See [`cert_app.c`](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.24.0/programs/x509/cert_app.c#L416) for a simple example illustrating the most common use case, and [`ssl_server2.c`](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.24.0/programs/ssl/ssl_server2.c#L3007) for a test program that potentially uses all the options.

We use GitHub for bug reports and feature requests only. If you need support from the community, please post on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls).
