### ISSUE TITLE
Memory leak when using ecjpake

### ISSUE THREAD

**Issue by terhei** [ARMmbed/mbedtls#395]
Memory leak when flag `MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED` is set. 
Pointer allocated to `ssl->handshake->curves` is not freed in `mbedtls_ssl_handshake_free` when handshake is done.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-599

**Comment by sbutcher-arm** [comment]
This issue has been fixed in the development branch and can be closed. No other maintained version impacted.
