### ISSUE TITLE
Add a level of indirection to the config file inclusion

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3960]
The file `mbedtls/config.h` has a dual role: it's the file that you edit to change the library configuration, and it's the file that you include to know the library configuration. This dual role doesn't give us the opportunity to adjust the configuration.

In concrete terms, with explicit-but-not-idiomatic names:

* `scripts/config.py` and users modify `mbedtls/editable-config.h`, which as shipped is just a bunch of `#define` and `//#define`. Nothing includes `editable-config.h` except `includable-config.h`.
* Our own code and application code includes `mbedtls/includable-config.h`. This file is not user-modifiable.

The initial content of `includable-config.h` would be something like
```
#ifndef MBEDTLS_CONFIG_H
#if defined(MBEDTLS_CONFIG_FILE)
#include MBEDTLS_CONFIG_FILE
#else
#include "mbedtls/editable-config.h"
#endif

#include "check-config.h"
#endif
```

For example, the new (and still experimental) PSA crypto configuration mechanism `MBEDTLS_PSA_CRYPTO_CONFIG` takes `PSA_WANT_xxx` symbols as input from the user configuration to determine what cryptographic mechanisms the application wants, as well as `MBEDTLS_PSA_ACCEL_xxx` symbols from the driver declarations, and determines `MBEDTLS_PSA_BUILTIN_xxx` symbols for the mechanisms that must be implemented in software. This calculation is currently done in `mbedtls/config_psa.h`, which must be included from `config.h` if you enable `MBEDTLS_PSA_CRYPTO_CONFIG`. It would be better if this inclusion was automatic, i.e. `includable-config.h` would contain
```
#ifdef MBEDTLS_PSA_CRYPTO_CONFIG
#include "config_psa.h" // or even the whole config adjustments could be there
#endif
```

----

Design questions:

* The names of the two header files (one of which can remain `config.h`).
* Whether to include some kind of versioning. If a user writes their own header file, should we tell them to put something like `#define MBEDTLS_CONFIG_VERSION 0x0300`, which would let us evolve the configuration system, but avoid breaking changes when `MBEDTLS_CONFIG_VERSION` is defined? Initially, `MBEDTLS_CONFIG_VERSION` would just be ignored. Let's say that in 3.5 we want to change some aspect of the configuration, such as deciding that `MBEDTLS_SHA256_C` no longer enables SHA-224 as well and you need `MBEDTLS_SHA256_SHA224` to enable SHA-224. Then we could have this in `config-includable.h`:
    ```
    #if MBEDTLS_CONFIG_VERSION < 0x0305
    #if defined(MBEDTLS_SHA256_C)
    #define MBEDTLS_SHA256_SHA224
    #endif
    #endif
    ```

----

Implementation (we only need to do one of these if one of the names stays `config.h`):

* Every place that currently includes `config.h`, with or without the `MBEDTLS_CONFIG_FILE` dance, becomes `#include "mbedtls/config-includable.h"`.
* Every place in build and test scripts that currently modifies or reads `config.h` must instead access `config-editable.h`.
* No longer need to include `check_config.h` elsewhere.

**Comment by gilles-peskine-arm** [comment]
There's a request to rename `config.h` to have a name that includes `mbedtls`: https://github.com/ARMmbed/mbedtls/pull/2459

**Comment by Hadatko** [comment]
Hello i appreciate that you still consider renaming of config file. But i would change name for user and also application config file name. As the file name is the issue not its purpose. For example i did same for erpc when new freertos came out. We had collision in names and i think best way to handle collisions should be prefix in names. 

F.e.: erpc config file name: https://github.com/EmbeddedRPC/erpc/tree/develop/erpc_c/config
library names: https://github.com/EmbeddedRPC/erpc/tree/develop/erpc_c/infra

rpmsg config file: https://github.com/NXPmicro/rpmsg-lite/tree/f12ffe998a9b52f0327e109b5b3005a2ef787770/lib/include
library names: https://github.com/NXPmicro/rpmsg-lite/tree/master/lib/rpmsg_lite

If you are doing version 3 and you are bringing changes which are breaking compatibility you can consider to due it in bigger scale. 

Just saying... Thank you for considering the changes.

**Comment by gilles-peskine-arm** [comment]
Could you clarify the problem with header file names?

In C code, you should only ever have `#include <mbedtls/config.h>`. If there's a `<something_else/config.h>`, it doesn't matter.

My understanding was that you wanted a different name for the file that's edited by maintenance scripts to set the project's configuration.

**Comment by Hadatko** [comment]
Well it was some time ago(2years) and i am not working with that tool since i left company (1.5year). But if i member is correctly (i can imagine errors from that time as i spent a lot of time to fix that), the issue is that tool was generating include paths based on header file location (so manual+generated include paths were used). So if another project has include like "#include <config.h>, your config file overwritte theirs config file.

mbedtls source file: #include <mbedtls/config.h>
other source file: #include <config.h>

manual linker flags: -I<pathToMbedtlsLib> -I<pathToOtherHeaderFileLocation> 
generated linker flag: -I<pathToMedtlsLib/mbedtls>

Build tool was combination of eclipse based IDE and armgcc compiler. Don't know if issue is in tool itself or eclipse. Also i don't know if there is another used tool which has this type of behavior or if they removed this behavior already. But you can get rid of one invalid(conflict) behavior.
