### ISSUE TITLE
Protocol mismatch error - ssl3.0 instead of tls1.2

### ISSUE THREAD

**Issue by Raghu41189** [ARMmbed/mbedtls#3978]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug | Enhancement\Feature Request
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
RTOS 

**mbed TLS build:**  

**Peer device TLS stack and version** 

**Expected behavior**   
We are using mbed TLS library in our application. We have two different mqtt broker running in two different servers (server1 and server2). Once after the handshake procedure it's reading protocol version as ssl 3.0 in one broker(server1) and in another it's reading as tls1.2(server2)

Can someone help why it's reading different names even after using same certificate in both the servers
--------------------------------------------------------------

**Comment by mpg** [comment]
Hi @Raghu41189 this looks more like question (or maybe two?) than a bug report, so I'm closing this as questions should be asked on [the mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) instead.

Also, I'm afraid there's not quite enough information about your setup to answers, so when posting to the mailing list I'd encourage you to give more details so can people can hopefully help you.
