### ISSUE TITLE
mini_client: Fails on OS X?

### ISSUE THREAD

**Issue by IngwiePhoenix** [ARMmbed/mbedtls#398]
To reproduce:

```
$ hub clone ARMmbed/mbedtls
$ cd mbedtls
$ mkdir out; cd out
$ cmake -G Ninja ..
$ ninja # Exits successfuly.
# In terminal tab 1:
$ ./programs/ssl/mini_server
# And in another:
$ ./programs/ssl/mini_client
```

Obviously, I wanted to just poke, so I ran the `mini_client` first out of curiosity. And what I got is:

https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/mini_client.c#L43-L59 being executed.

On OS X, `UNIX` is not defined, but `__APPLE__` is. Thus, Since I used CMake, I was expecting the proper values to be set and configured. So I am very confused about why this isn't working...

The other server/client examples work, by the way. I was able to use them to test around - but the `mini_` versions don't work.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-600

**Comment by mpg** [comment]
Thanks for your report! CMake is not like autotools, it doesn't handle that kind of thing (at least not the way we use it). The code should be using the proper `#ifdef`s and it will be fixed to do that.

**Comment by IngwiePhoenix** [comment]
Thanks for the reply!

I am aware of CMake not being like Autotools - I have been researching in the field of build tools for a while. So I know it’s flaws. :)

Good to know it’ll be fixed!
