### ISSUE TITLE
 There is no y-axis as exchange information in the example of ecdh_curve25519.c.

### ISSUE THREAD

**Issue by carloscn** [ARMmbed/mbedtls#3982]
## Question

Hello, When I learned the mbedtls ecdh example, I found that the client and server did not exchange information about the Y axis. It is just exchange information about X axis data .In my demo of building TCP exchange secret key, the lack of y-axis information is not allowed, using the  mbedtls_ecp_check_pubkey() function to dectect received public key will return  MBEDTLS_ERR_ECP_INVALID_KEY error code.

**file : ./programs/pkey/ecdh_curve25519.c.** 
https://github.com/ARMmbed/mbedtls/blob/e9e0388934534ff3772078f2bf0b42ccab8c3064/programs/pkey/ecdh_curve25519.c#L199
ctx_cli.Qp.Z assign 1
ctx_cli.Qp.X assign from srv_to_cli.
but there is no process to assign the ctx_cli.Qp.Y value.

**Comment by gilles-peskine-arm** [comment]
X25519 and X448 are defined as outputting the X coordinate (often called U coordinate, e.g. in [RFC 7748](https://tools.ietf.org/html/rfc7748)) of the shared secret. Could you clarify why you want the Y coordinate? I'm not aware of any cryptographic protocol that needs it.

**Comment by carloscn** [comment]
> X25519 and X448 are defined as outputting the X coordinate (often called U coordinate, e.g. in [RFC 7748](https://tools.ietf.org/html/rfc7748)) of the shared secret. Could you clarify why you want the Y coordinate? I'm not aware of any cryptographic protocol that needs it.

**Hi Gilles,**
Thanks for your reply. I have figured it out.
I found out the CUR_ID MBEDTLS_ECP_DP_SECP256K1 curve is my selected in my program.  The secp256k1 is Weierstrass Curve , and it need both x-axis and y-axis information as share parameters. But x25519 and x448 are Montgomery Curve, it just need U coordinate. 
Thanks for your direction. I closed the this issue.

Carlos
