### ISSUE TITLE
PBKDF2 PSA interface

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4003]
Specify the PSA API for using PBKDF2

**Comment by gilles-peskine-arm** [comment]
Private link for API discussion: https://github.com/ARMmbed/psa-crypto-api/issues/456, https://github.com/ARMmbed/psa-crypto-api/issues/457

**Comment by mpg** [comment]
I completed a review of the literature in order to determine the "abstract API" (inputs and outputs) of current password hashing functions. The result is in the attached file.

[Uploading password-hashing-abstract-api.md…]()

**Comment by gilles-peskine-arm** [comment]
Thanks for the review! That's a nice analysis of commonly used schemes.

What about interfaces? Have you looked into how these schemes are used? E.g.

* Typical amounts of derived material.
* Whether it's common to use the output to seed a non-stretching KDF.
* How people typically combine password verification and key stretching from the same password.

**Comment by mpg** [comment]
I haven't looked into how these schemes are commonly used, and I'm not entirely how I would go about this.

Regarding doing verification and key stretching on the same password, Catena has distinct modes for that, and Catena and Argon2 provide "additional data" that seems intended to provide domain separation, but I was a bit surprised that those are the only two that provide syntactic support for that kind of thing. PKCS#5 recommends using a structured salt with PBKDF2 to provide separation if necessary (including deriving keys for different uses).

**Comment by gilles-peskine-arm** [comment]
* How people typically pass pepper into the salt with algorithms that don't have a separate pepper input.
