### ISSUE TITLE
Using a weak ciphersuite without allowing all the other weak ciphersuites because the config was enabled

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#4013]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Question
- Priority: Minor

---------------------------------------------------------------
## Question
mbedtls-2.16.4

My application sadly needs some of the weak ciphersuites to be enabled ... specifically MBEDTLS_TLS_ECDHE_PSK_WITH_NULL_SHA256. Allowing this ciphersuite also foces me to to enable MBEDTLS_ENABLE_WEAK_CIPHERSUITES inside the configuration file.

However I don't want to to allow any ofthe other weak ciphersuites. There must be a way to only allow the ONE weak ciphersuite i really need for the application right? What would be the best way to do that?

Thanks

**Comment by gabor-mezei-arm** [comment]
When configuring the tls connection you can set the list of allowed ciphersuites and the preference order with `mbedtls_ssl_conf_ciphersuites`.

Do you really want a connection without encryption? Can you share the use case are you using?

**Comment by TrinityTonic** [comment]
Yea, I know that I can configure the ciphersuites, but if these are not enabled within the config file - it will not work.

UseCase: Realtime communication protocol (example Profinet) where confidentiality is not important but data integrity is.

**Comment by TrinityTonic** [comment]
I can't add MBEDTLS_TLS_ECDHE_PSK_WITH_NULL_SHA256 to my list, if I haven't enabled the config for enabling null cipher suites and weak ciphersuites.

**Comment by gabor-mezei-arm** [comment]
You have to enable MBEDTLS_ENABLE_WEAK_CIPHERSUITES and MBEDTLS_CIPHER_NULL_CIPHER to enable MBEDTLS_TLS_ECDHE_PSK_WITH_NULL_SHA256 at compile time. Use the function `mbedtls_ssl_conf_ciphersuites` to select only that which you want to enable at runtime. If you are configuring what is enabled at runtime then only those can be used and nothing else.

The MBEDTLS_ENABLE_WEAK_CIPHERSUITES macro must be set to enabling the weak ciphers and it is used for that purpose only. You need to indicate explicitly that you want to use the weak ciphers to not enable them accidentally.

You can disable some of the weak ciphers like DES and SHA1 with unset MBEDTLS_DES_C and MBEDTLS_SHA1_C. You can check all of them in ssl_ciphersuites.c.

**Comment by chris-jones-arm** [comment]
I believe this question has been answered so I am closing it down. Please reopen if this still needs further discussion or open a new issue if you have a feature request or bug report.
