### ISSUE TITLE
Remove some modules from Mbed TLS 3.0

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4030]
Remove these modules and associated includes, etc:

Wrapper for PKCS#11 library libpkcs11-helper (library/pkcs11.c)
HAVEGE (library/havege.c)
X.509 test certificates (library/certs.c) (this should remain under tests, but not in the core library)
RC4 cipher
Net socket
Memory allocator

This task needs review to verify the list of modules

**Comment by yanesca** [comment]
- Wrapper for PKCS#11 library libpkcs11-helper (library/pkcs11.c) has been discussed on the mailing list and confirmed for removal
- HAVEGE (library/havege.c) has been discussed on the mailing list and confirmed for removal
- X.509 test certificates (library/certs.c) has been discussed, there were no objections, technical details might need design review.
- I don't think we want to remove RC4 from the library just for the default configuration and is part of #4035 and #4036.
- memory_buffer_alloc.c we still want to remove it, but there were objections, several users are relying on it, we shouldn't be removing it in a rush
- net_socket.c and timing.c, there is no decision so far, @mpg proposes to move them into `programs/`, @gilles-peskine-arm  is on the opinion that we should move them into a `platform_posix.c` and a `platform_windows.c` modules within the library. I suggest we move these two to a separate issue and don't block the rest while we are coming up with an approach

**Comment by gilles-peskine-arm** [comment]
I think that for task management, each module should have its own task. Removing modules is not a generic endeavor.

**Comment by daverodgman** [comment]
I think breaking these into separate tasks is much better than tracking them all together here. I'll add individual tasks and close this one when done.

**Comment by daverodgman** [comment]
Closing as this has been captured in individual issues
