### ISSUE TITLE
mbedTLS rejects a cert while OpenSSL, GnuTLS, and wolfSSL accept it

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [ARMmbed/mbedtls#4062]
### Description
- Type: Bug 
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS linux

**mbed TLS build:**  
Version: 2.25.0
OS version: 18.04, 20.04  
Configuration: no
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  gcc 9.3.0
Additional environment information:  no

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other 

Version:  OpenSSL 1.1.1f, GnuTLS  3.5.5 & 3.6.13, wolfSSL 4.6.0

**Expected behavior**   

Consistent verification results among mbedTLS and others (i.e., OpenSSL, GnuTLS, and wolfSSL).

**Actual behavior**  
```
  . Loading the CA root certificate ... ok (0 skipped)

  . Loading the certificate(s) ... failed
  !  mbedtls_x509_crt_parse_file returned -8320
```

**Steps to reproduce**  

`./cert_app mode=file ca_file=ca.pem filename=seed-5s26-41s18-189s27.pem`

**Attachments**

[ca.zip](https://github.com/ARMmbed/mbedtls/files/5873233/ca.zip)

[seed-5s26-41s18-189s27.zip](https://github.com/ARMmbed/mbedtls/files/5873234/seed-5s26-41s18-189s27.zip)

**Comment by tom-daubney-arm** [comment]
Looking at the error code that was generated by the test, this is actually a feature that is not supported, rather than a bug.

Error code 8320 yields:
Unavailable feature, e.g. RSA hashing/encryption combination

when examined with programs/util/strerror.

Since this is labelled a bug report, and not a request to actually implement this feature, this issue will now be closed.

**Comment by gilles-peskine-arm** [comment]
Specifically, what is unsupported is the content of the CertificatePolicies extension. Mbed TLS only supports `anyPolicy`. This certificate has a different policy, so Mbed TLS is unable to determine whether it is permitted (it doesn't know what the caller wants to do with the certificate anyway) and rejects it.
