### ISSUE TITLE
Building mbedTLS

### ISSUE THREAD

**Issue by primesoftware** [ARMmbed/mbedtls#407]
I have an interest in writing a Scons script to build mbedtls. I was poking around in the Makefile straight from GitHub for the library dir and noticed the following dynamic libs are linked against (-lws2_32 -lwinmm -lgdi32).

First, these are all Windows libs. I don't see anything for linux or other platforms except -static-libgcc. Are no other libs needed for unix based systems / ARM CPU's?

Secondly, for windows I can understand the need for ws2_32, but why the other 2? Aren't they multimedia and graphics libs?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-608

**Comment by sbutcher-arm** [comment]
Hi, and thanks for the interest in the project.

mbed TLS has very few external dependencies, and is designed to be easy to port across platforms and to embed. [This article](https://tls.mbed.org/kb/development/what-external-dependencies-does-mbedtls-rely-on) on our support site describes the precise dependencies.

I think when you look at the dependencies you mention, you're actually looking at the `libmbedx509.dll` target in the Makefile and those are the dependencies used to build the Windows library, and not the Unix variants listed below. Offhand I don't know why the library needs those additional libraries, but I do know from experience GDI is added by default to new DLL and Console projects in Visual Studio, so they don't look that unusual to me.

I'm closing the issue, but please feel free to reply if you don't feel this is a satisfactory answer.
