### ISSUE TITLE
Remove module: libpkcs11-helper

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4078]
Remove the wrapper for PKCS#11 library libpkcs11-helper (library/pkcs11.c).

Deprecating this module was covered in #3006, and there is some mailing list discussion here:

https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000024.html

This forms part of #4030

Estimated task size: S

**Comment by mpg** [comment]
Expanding on the definition of this task:

- `library/pkcs11.c` and `include/mbedtls/pkcs11.h` are removed from the source three
- `MBEDTLS_PKCS11_C` is removed from `config.h` and it variants
- support for linking with libpkcs11-helper is removed from the build systems (CMake, make)
- at the end of the task, `git grep -i pkcs11` should find no occurrence except in ChangeLog entries.
