### ISSUE TITLE
Changelog strategy in the 3.0 branch

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4114]
How do we document the changes that have been made in `development_3.0`?

For a while, this branch is going to have both changes merged from `development` and API-breaking changes. Both require changelog entries. The entries should be in separate sections.

My suggestion: every 3.0 PR documents what it does in a file in `ChangeLog3.d`.

Rationale:
* One file per PR (unless a PR is a follow-up to one that is already merge), to avoid merge conflicts. It's the same reason we have `ChangeLog.d` which is later consolidated into `ChangeLog`.
* Separate directory so that we'll have separate sections when we consolidate the changelog file. We'll want a section for 2.26.0 changes (which will reach `development_3.0` via `development` that is separate from the section from 3.0 changes
* Document in each PR because otherwise we'll scramble later when things aren't fresh on our minds anymore.

**Comment by mpg** [comment]
Thanks for raising the issue! I'm not sure I understand the problem however, at it seems to me that the naive strategy would work:

1. create entries in ChangeLog.d in both branches: development only has the 2.x entries, and development_3.0 has both.
2. prepare the 2.26.0 release as usual, and after the 2.26 release, merge it back to the 3.0 branch (which is also pushed as development at this point)
3. from now on, ChangeLog.d in the 3.0 branch (now known as development) only has the 3.0 entries, so when we prepare the 3.0 release, 3.0 entries naturally go the 3.0.0 section of the ChangeLog. (And as usual we have subsections with "API Change", "Removals", etc.)

Am I missing something?

**Comment by gilles-peskine-arm** [comment]
When I wrote this, I must have thought the naive strategy would cause 2.x and 3.0 entries to be mixed. But I think you're right and I was wrong: I don't see a problem with it now. As long as we don't run `assemble_changelog` on the 3.0 branch, merging will do the right thing.

**Comment by mpg** [comment]
I'm closing this as we seem to have agreement that there is no problem after all.
