### ISSUE TITLE
Exit value truncated in example code

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#412]
Posix defines exit codes can only be 8-bits (see here: http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html) yet the example program programs/pkey/rsa_verify.c passes back the return value of mbedtls_rsa_pkcs1_verify().

Potentially, some values returned by the verify function could return an exit code of 0, indicating success, and yet be reporting a failure.

Reported by email.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-620

**Comment by mpg** [comment]
Looks like a duplicate of #352 to me.

**Comment by sbutcher-arm** [comment]
I agree @mpg that this is related to #352, but I'd like to deal with this one separately from the general problem of #352, so I'm reopening this one.

**Comment by sbutcher-arm** [comment]
This issue has been addressed by PR #532, so can now be closed.
