### ISSUE TITLE
Separation of Public/Private keys

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#417]
With PolarSSL client software could assume that the context passed for operations only had to have the key required for the operation to be executed. So for signing or encrypting operations only the private key needed to be present, or for decryption or signature verification, only the public key needed to be present.

That is no longer true, and in the function `mbedtls_rsa_rsassa_pkcs1_v15_sign()` in `library/rsa.c` for instance, reference is made to the public key as a verification operation.

It should be possible to perform operations with only the key necessary for the operation, and  verifying steps should be somehow optional (possibly by conditional compilation or an API change). Test cases should be added to confirm that the separation of keys is maintained.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-631

**Comment by sbutcher-arm** [comment]
I believe this issue was fixed in commits 88ec2381d6af..6f486a6fb5c7, and shipped in Mbed TLS 2.8.0.  What is currently stopping me from closing this bug is we should really have tests to prove it's work and ensure it keeps working.
