### ISSUE TITLE
How to use certificate chain to verify national secret certificate?

### ISSUE THREAD

**Issue by jiangbinghua** [ARMmbed/mbedtls#4170]
Hello!
The certificate chain failed to use the interface 
`mbedtls_x509_crt_parse_der` when verifying the national secret certificate. What interface should be called?

Thanks!

**Comment by gabor-mezei-arm** [comment]
Hello,
if you have any question please write to the mbedtls mailing list: mbed-tls@lists.trustedfirmware.org. The mailing list has a broader audience and your question can be answered easier.
