### ISSUE TITLE
Prepare SSL session resumption API for TLS 1.3

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4184]
__Context:__ The Mbed TLS mailing list post 
https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000049.html explains that the existing idempotemt semantics of the SSL session resumption API `mbedtls_ssl_session_{get,set}()` is not suitable for TLS 1.3, where a client may receive multiple session tickets from a server. Moreover, the post proposes a change of semantics for the session resumption API for Mbed TLS 3 which would resolve the issue and prepare the library for the upcoming TLS 1.3 implementation.

This has been discussed internally with @yanesca and @mpg, and @mpg has approved the design.

__Task:__ This issue is to track the implementation of this proposal.

**Comment by hanno-arm** [comment]
@daverodgman Can you tag and track this appropriately?

**Comment by yanesca** [comment]
A change in semantics can be confusing to users. Suggestion: let us introduce new functions with the new semantics and deprecate the old one.

**Comment by yanesca** [comment]
I think one approving design review should suffice at this stage. @mpg could you add an "approved for design" label if you are still happy with the general direction?

**Comment by mpg** [comment]
I've added the label "approved for design" to reflect my approval, previously expressed on another channel.

**Comment by hanno-arm** [comment]
@mpg @gilles-peskine-arm Following up from yesterday's meeting, I consider this an important change for Mbed TLS 3.0 and would like to move it from `Mbed TLS 3.0 Optional` to `Mbed TLS 3.0`, understanding that this can only happen if I do the design and engineering work, but of course the team would need to provide the review. Are you OK with that?

**Comment by mpg** [comment]
I'm more inclined to leave that in the optional column, near the top. IMO it doesn't quite check the second criterion for the non-optional 3.0 epic: "Would block further work / cause significant pain if delayed to 4.0" - if this misses 3.0, we can live with adding a new set of functions for 1.3; the resulting API will be less clean than if this changes makes it to 3.0, but will still be something we can live with until 4.0 IMO.

That said, if you make a PR for this, I hope we manage to squeeze it into our review list at some point.
