### ISSUE TITLE
Relax specification of mbedtls_ssl_conf_psk()

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4191]
This came up in and is related to #4121. The documentation for `mbedtls_ssl_conf_psk()` states:
```c
/**
 * \brief          Configure a pre-shared key (PSK) and identity
 *                 to be used in PSK-based ciphersuites.
 * ...
 * \warning        Currently, clients can only register a single pre-shared key.
 *                 Calling this function or mbedtls_ssl_conf_psk_opaque() more
 *                 than once will overwrite values configured in previous calls.
 *                 Support for setting multiple PSKs on clients and selecting
 *                 one based on the identity hint is not a planned feature,
 *                 but feedback is welcomed.
 *
 * ...
 */
```
I feel that this is overspecifying the implementation, and would like to suggest that we relax it for Mbed TLS 3 by _allowing_ implementations to store multiple PSKs, and return a dedicated non-fatal error code once no further PSKs can be loaded. This allows us to keep the existing implementation which limits the number of PSKs to max. 1, but gives us the flexibility to extend it should the need arise.

This should be trivial to implement: Adapt the documentation, and return an error instead of silently overwriting old PSKs when `mbedtls_ssl_conf_psk()` is called multiple times.

**Comment by mpg** [comment]
That seems reasonable to me: it's a behaviour change, so we 3.0 is really the right time for this, and it's a little amount of work, we we can probably squeeze it in our already very packed 3.0 schedule. I'm adding it to the epic.

**Comment by hanno-arm** [comment]
The same applies to `mbedtls_ssl_conf_psk_opaque()`.
