### ISSUE TITLE
How to port mbedtls to contiki os?

### ISSUE THREAD

**Issue by WEN-XUE** [ARMmbed/mbedtls#4200]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Question
Hi everyone, I want to port mbedtls to contiki os and use the coap protocol to transmit encrypted data, but I currently have no idea. Can someone give me some suggestions or is there any example for reference?

I want to use contiki os+coap+mbedtls+uip on my client side and libcoap on the server side.

Thanks you in advance.

**Comment by gabor-mezei-arm** [comment]
Thank you for using mbedtls.
If you have any integration related question please write to the mbedtls mailing list: mbed-tls@lists.trustedfirmware.org. The mailing list has a broader audience and your question can be answered easier.
