### ISSUE TITLE
OpenSSL and MbedTLS public/private key incompatibility

### ISSUE THREAD

**Issue by RyanLindemanCAE** [ARMmbed/mbedtls#4204]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor
We use the Python cryptography library, which I believe uses OpenSSL, to allow our customer to generate their own public/private keys for use in signing firmware images for their products. We discovered that one of several keys we have generated with this code fails to verify the signature of a firmware image. We discovered that the public/private key was to blame and created a new one. I have been given the task of trying to find out why the firmware image signature passes in Python but fails in the firmware which uses mbedTLS.

---------------------------------------------------------------
## Bug

**OS**  
Either bare metal or FreeRTOS based

**mbed TLS build:**  
I have carefully compiled the attached test program against mbedTLS versions 2.4.2, 2.16.6, and 2.25.0 - all without success.
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
I extracted various versions of mbedTLS into my test directory and compiled a library for each using a custom config.h and the Makefile's provided. Then I compiled my test application using a command line similar to this:
gcc -o mbedtls_test main.c -I mbedtls-2.4.2/include/ -L mbedtls-2.4.2/library/ -l mbedtls -l mbedcrypto

I am using the Python v3.6+ and cryptography module version 3.2.1 for running my scripts.

**Peer device TLS stack and version**  
The Python cryptography module claims to use either OpenSSL version 1.1.1-latest or 1.1.0-latest. I'm unsure which was used to build module version 3.2.1.

**Expected behavior**   
I would expect that creating a firmware update signature using the Python cryptography module could be verified by firmware using mbedTLS and the same public key bytes.

**Actual behavior**  
The mbedTLS implementation appears to reject potentially EVERY signature created with the attached public/private key pair for unknown reasons. The Python OpenSSL based verification passes every time.

**Steps to reproduce**  
You can review my test_broken_key.py file to see that it generates a single random byte into a SHA224 hash and signature using the broken public/private key and that verification of this passes using OpenSSL backed cryptography python module.
You can review my main.c file (usually compiled to become mbedtls_test executable as described above) to see that the hash and signature generated by the test_broken_key.py file fails the verification process (there is also the original hash/signature embedded in the file which resulted in this research).

----------------------------------------------------------------
## Enhancement\Feature Request

My customer and I would like to know what went wrong and if there is any risk in using the new keys we generated in the future. Ideally, we would like to avoid publishing a firmware image + signature that would fail in the end product due to this slight incompatibility.

-----------------------------------------------------------------

## Question

I could not find any other issue that seemed to be the same. There were some that seemed somewhat similar but didn't answer my customers question stated above.
[mbed_issue.zip](https://github.com/ARMmbed/mbedtls/files/6094161/mbed_issue.zip)

**Comment by ronald-cron-arm** [comment]
Hi, the public key used to verify the signature with Mbed TLS does not seem to be the same as the one used in the Python script. The X-coordinate of the public key point in the Python script is:
X= 0xec66c0a8f0a4272b4f70fb761db50643b7ef7dba79bbf04e347fcaa1
compared to, in main.c:                                                                
X= 0x9c2180a0fbd54008b262536c8afad82d8f32dfc3db3c298076f18162
When I change to the Python script public key in main.c the verification succeeds. Please find in the zip below the changes I've done to test_broken_key.py and main.c to print the public key coordinates and change the Mbed TLS public key.          
[mbed_issue.zip](https://github.com/ARMmbed/mbedtls/files/6450885/mbed_issue.zip).
