### ISSUE TITLE
Possible unbalanced parenthesis

### ISSUE THREAD

**Issue by mbeniamino** [ARMmbed/mbedtls#4217]
Running a translation tool I get this warning while parsing this library:

`Unbalanced opening parenthesis in C++ code (or abuse of the C++ preprocessor)`

here:

https://github.com/ARMmbed/mbedtls/blob/1c54b5410fd48d6bcada97e30cac417c5c7eea67/library/ecp.c#L2449

Looking at the code it seems to me it's right, but that line is compiled only when `MBEDTLS_ECP_RANDOMIZE_MXZ_ALT` is defined and in my use case this is false, so I haven't actually tried and checked.

**Comment by stevew817** [comment]
You would be right. This one's on me, probably due to copy-paste error when transposing the patch. Fix incoming.

**Comment by stevew817** [comment]
Hang on... No, it's not actually on me. I assumed it was since I touched the `ECP_xxx_ALT` functionality last. Nevertheless, I'll open a PR for you.
