### ISSUE TITLE
Test the block sizes are powers of 2

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4228]
In `crypto_sizes.h` we rely on the fact that the largest block size is a multiple of all possible block sizes when we compute maximum output lengths by rounding up to a multiple of the maximum block size. (This would not be correct if the largest block size was not a multiple of the others: for example if 8, 12 and 16 are possible block sizes the length to round up is say 13, then the maximum will be 24, rounding to a multiple of 12.) In practice this works because block sizes are always powers of two, so the largest one is always a multiple of the others.

However, as a matter of principle, we shouldn't rely on untested assumptions, so we should have a test ensuring that block sizes are indeed powers of two, and appropriate comments linking that test to the places we rely on it.

Quoting from Gilles: "a good place to check would be in `test_suite_psa_crypto_metadata`, in `block_cipher_key_type`".

**Comment by KenCox94** [comment]
@mpg Can I take this on?

**Comment by gilles-peskine-arm** [comment]
@KenCox94 Sure! Any contirbution is welcome.
