### ISSUE TITLE
[BUG] Bias in private key generation in Diffie-Hellman

### ISSUE THREAD

**Issue by FlorianF89** [ARMmbed/mbedtls#4245]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
All

**mbed TLS build:**  

Version: git commit id  5121ce5bdbc92e134a42220a1aa23f95037c7625 ,(12 years old)

**Expected behavior** 

In **library/dhm.c** l.179, the code used to generate a private key _X_ should generate a random value between _2_ and _P - 2_ **following a uniform distribution**.

**Actual behavior**  

The code used is

```
    do
    {
        MBEDTLS_MPI_CHK( mbedtls_mpi_fill_random( &ctx->X, x_size, f_rng, p_rng ) );

        while( mbedtls_mpi_cmp_mpi( &ctx->X, &ctx->P ) >= 0 )
            MBEDTLS_MPI_CHK( mbedtls_mpi_shift_r( &ctx->X, 1 ) );

        if( count++ > 10 )
            return( MBEDTLS_ERR_DHM_MAKE_PARAMS_FAILED );
    }
    while( dhm_check_range( &ctx->X, &ctx->P ) != 0 );
```

This first produces a random stream _X_ of as many bytes as _P_ and then shifts right _X_ until it becomes strictly smaller than _P_. This introduces a bias in the random distribution of _X_. 
Here is a simple example to help understand the claim (this is not a formal mathematical proof). To simplify things, let's assume that mbedtls_mpi_fill_random generates nibbles and not bytes and that _P = 11 = (1011)2_. Here is the table of what _X_ becomes after being generated in the while loop:

- 0000 -> 0000 - 0001 -> 0001 
- 0010 -> 0010 - 0011 -> 0011 
- 0100 -> 0100 - 0101 -> 0101 
- 0110 -> 0110 - 0111 -> 0111 
- 1000 -> 1000 - 1001 -> 1001 
- 1010 -> 1010 - 1011 -> 0101 
- 1100 -> 0110 - 1101 -> 0110 
- 1110 -> 0111 - 1111 -> 0111 

Now, discarding the values not between _2_ and _P - 2_ (excluded), we have the following distribution:
- values  ||  number of times the value is taken
- 0011    ||  1
- 0100    ||  1
- 0101    ||  2
- 0110    ||  3
- 0111    ||  3
- 1000    ||  1
- 1001    ||  1
- 1010    ||  1

As you can see, the values 0110 and 0111 get output 3 times while 0011 gets output 1 time only. The actual maths are slightly more complicated as one has to factor in the fact that a rejected value (e.g.  0000) triggers a new call to the prng but I guess this is enough to convince that the code, as it is now, does not implement a uniform random distribution.

**Fix** 

The fix is simple: set all the bits of _X_ above the MSB of _P_ to 0 instead of shifting right _X_. For example:

  ```
x_bit_length = mbedtls_mpi_bitlen(&X);
  if (x_bit_length > p_bit_length)
  {
      // We Mask the upper part of X
      for (size_t i = x_bit_length; i >  p_bit_length; i--)
      {
          // The argument position in mbedtls_mpi_set_bit is a Zero based
          // index so we use i - 1
          mbedtls_mpi_set_bit(&X, i - 1, 0);
      }
  }
```

**Comment by gilles-peskine-arm** [comment]
Thanks for reporting this issue! The same biased generation was used for blinding values in DHM and ECP. This should all be fixed in https://github.com/ARMmbed/mbedtls/pull/4276.
