### ISSUE TITLE
dtls timer timeouts when multiple Finished messages are sent

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbedtls#425]
When a client runs slowly, it is possible for the server to resend multiple flights of "Server Hello done" message. This leads the client to resend "Change Cipher Spec" and "Finished" messages multiple times as well (with each resend starting a dtls timer), resulting in the corresponding flights of messages to come back from the server. However, on the client, the handshake is done after parsing the first "Finished" message, and only the dtls timer corresponding to the first flight of "Finished" message sent is stopped. The dtls timers for the other outstanding flights of "Finished" messages sent are not stopped, and the remaining flights of received responses are left in the buffer. 

The dtls timers will eventually expire after 60 secs, leading to "Error occured: M2MInterface::NetworkError" being seen in the context of the mbed-client-linux-example.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-643

**Comment by mpg** [comment]
mbed TLS has no concept of "multiple timers" running. While I trust your report that you're getting timeouts when you shouldn't, I think that either (a) your interpretation that this comes from have multiple timers running at a given time, and only one of them being canceled, is wrong, or (b) the timer callbacks are not implemented correctly. If (b) is the case, then this is a bug in the application using mbed TLS, not in mbed TLS itself.

**Comment by mpg** [comment]
I've just edited our [DTLS tutorial]() to make the following point explicit:

> *Note:* you need to make sure that calling set_delay() while a timer is already running cancels it (more precisely, that no event will be generated when the final delay expires). In particular, after a call like set_delay(0, 0), no timer should be running any more. Said otherwise, there should be at most one running timer at any given time.

**Comment by vanti** [comment]
Thanks for looking into this. It is possible that my interpretation is inaccurate, given I am new to this. I tried to dig into the mbed code, but maybe I shouldn't have. =P Nevertheless, as you said, I am seeing timeouts in the context of the mbed-client-linux-example whenever the server resends message flight 4 in Fig.1 from http://tools.ietf.org/html/rfc4347 due to the client running slow.  The error "Error occured: M2MInterface::NetworkError" is displayed when M2MConnectionSecurityPimpl::timer_expired() is invoked after the DTLS handshake is complete, when the timer eventually expires.

**Comment by sbutcher-arm** [comment]
Thanks for taking an interest in the project @vanti. I'm closing this issue as I see it as more of a question than a defect, and @mpg has clarified the documentation. If for any reason you're unsatisfied, please feel  free to respond and we'll look into this again.

**Comment by vanti** [comment]
@mpg's post still does not explain why I am getting timeouts from the DTLS timer *after* the handshake is complete in mbed-client-linux-example, when the handshake is performed as described. The issue needs to be looked at. Do you want me to re-file this with the 'mbed-client-linux-example' project, given you feel this is a problem with the application itself?
