### ISSUE TITLE
Fix return value for psa_copy_key() if lifetime or identifier in attributes is invalid.

### ISSUE THREAD

**Issue by maulik-arm** [ARMmbed/mbedtls#4271]
### Description
- Type: Bug 
- Priority: Major
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.26.0  

**Expected behavior**   
As per the PSA Crypto Specification 1.0.0, MbedTLS library function psa_copy_key() should return PSA_ERROR_INVALID_ARGUMENT, if the lifetime or identifier in attributes is invalid. However, it returns PSA_ERROR_INVALID_HANDLE instead.

**Actual behavior**  
psa_copy_key() returns PSA_ERROR_INVALID_HANDLE when identifier or lifetime is invalid.

**Comment by ronald-cron-arm** [comment]
I started to work on a fix.
