### ISSUE TITLE
TLS1.2, client, mbedtls_ssl_handshake returns ERR_SSL_INTERNAL_ERROR

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#428]
From the [mbed TLS forum](https://tls.mbed.org/discussions/generic/tls1-2-client-mbedtls_ssl_handshake-returns-err_ssl_internal_error), an issue has been reported that when the option  `MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED` is configured, but not `MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED`, `ERR_SSL_INTERNAL_ERROR` is returned by the ssl handshake, where the function `mbedtls_ssl_handshake_client_step` is failing at state `MBEDTLS_SSL_CERTIFICATE_REQUEST`.

This looks like an issue with the configuration options.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-647

**Comment by david0fc** [comment]
By adding `!defined(MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED) && \` in the "right" places, as indicated in the forum posts (2nd solution), the peer-verify result, goes from 0x0c for the first solution to 0x04 for the second solution... so I guess that the most likely case is that those two defines are missing.

Anyway, just reminding that I'm using the master-2.2.1 version, and you can find attached my current configuration file.

[mbedtlsopts.h.txt](https://github.com/ARMmbed/mbedtls/files/141098/mbedtlsopts.h.txt)

**Comment by sbutcher-arm** [comment]
Fixed by pull request #550. Can now be closed.

**Comment by burkulesomesh43** [comment]
hi,
I am using esp idf environment
I want to decode the string in url. mbedtls_base64_decode() function does not gives an error after compiling.   but when i see  decoded result in decode_pass variable, the processor gets restart again and again. 
char *getpass="cabin336%40efc";
unsigned char *decode_pass=NULL;
 size_t len;
 mbedtls_base64_decode(decode_pass, sizeof(decode_pass), &len, (unsigned char *) get_pass, strlen(get_pass));

**Comment by RonEld** [comment]
@burkulesomesh43 you should open a new issue for your query.
Your question is not related to the issue
