### ISSUE TITLE
Remove deprecated things in psa/crypto_compat.h

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4284]
There are a number of deprecated types and constants in `include/psa/crypto_compat.h` which seem to be for compatibility with previous version and should be removed. (For a list, search for `DEPRECATED` in that file.)

**Comment by mpg** [comment]
@gilles-peskine-arm Can you double-check that this makes sense? Also, I see that `scripts/generate_psa_constant.py` has provisions for skipping deprecated constants - can these be removed once the deprecated things in `psa/crypto_compat.h` or should support remain in the script?

**Comment by gilles-peskine-arm** [comment]
Yes, we should remove everything from `crypto_compat.h` in 3.0. We might as well remove that header file altogether.

There are two kinds of things in `crypto_compat.h`: old constants, and support for open/close.

Old constants can just go away, removing any reference to them in tests.

Removing open/close means removing more tests and code and there's a requested feature (https://github.com/ARMmbed/mbedtls/issues/4218) that may reuse some of the code that's currently specific to open/close, so I suggest deferring that: just remove the declarations of `psa_open_key` and `psa_close_key` and supporting macros/funtions from public APIs, but keep the code and tests until after the 3.0 release.

I recommend not touching `generate_psa_constants.py`. I'm heavily refactoring it as part of my work to generate test cases for storage format stability; the code is now in `scripts/mbedtls_dev/macro_collector.py`, and it's just 3 lines of code: not worth the trouble of merge conflicts.

**Comment by TRodziewicz** [comment]
The issue has been fixed by: "Remove deprecated things from crypto_compat.h and dependent tests. #4344" so I'm closing it.
