### ISSUE TITLE
./programs/ssl/ssl_fork_server.c compiles but doesn't appear to function correctly

### ISSUE THREAD

**Issue by fargly** [ARMmbed/mbedtls#429]
This appears in 2.2.0 and 2.2.1. I'm attempting to add TLS support to a web server that uses a forking model. My first thought was to use ssl_fork_server as a starting point but when I run it and communicate via ssl_client1 or ssl_client2, I receive the following:

Client End:
ssl> ./ssl_client1

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...ssl_tls.c:3768: mbedtls_ssl_fetch_input() returned -29312 (-0x7280)
ssl_cli.c:1402: mbedtls_ssl_read_record() returned -29312 (-0x7280)
 failed
  ! mbedtls_ssl_handshake returned -0x7280

Last error was: -29312 - SSL - The connection indicated an EOF

Server End:
./ssl_fork_server

  . Initial seeding of the random generator... ok
  . Loading the server cert. and key... ok
  . Configuring SSL... ok
  . Bind on https://localhost:4433/ ... ok
  . Waiting for a remote connection ... ok
  . Forking to handle connection ... ok
  . Forking to handle connection ... ok
  . Setting up the SSL data....  . Waiting for a remote connection ... failed
  ! mbedtls_net_accept returned -74

 ssl>  ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -80

Both ssl_server and ssl_server2 function correctly but I'm consistently encountering this issue with the forking server. 

If I am missing something in the build or on this system, any insight would be greatly appreciated.

Thanks
-Kurt

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-648

**Comment by mpg** [comment]
Thanks for your report! I was able to reproduce the issue, we'll be looking into it.

**Comment by sbutcher-arm** [comment]
This issue is now fixed on the `development` and `mbedtls-2.1` branches, so this issue can be closed.
