### ISSUE TITLE
ecdsa: pre-compute grp->T to gain runtime performance

### ISSUE THREAD

**Issue by Kxuan** [ARMmbed/mbedtls#4303]
### Description
- Type: Enhancement / Feature Request
- Priority: Major

## Enhancement / Feature Request

**Suggested enhancement**  
Provide a config option to use pre-computed `grp->T` table for well-known ecc curves (SECP256R1, SECP384R1, etc).

**Justification - why does the library need this feature?**  
The mbedtls currently compute `grp->T` in function `ecp_mul_comb`.

I have tested establish a tls connection with a server which is using ECDSA certificate (both server certificate and CA certificate). It shows that compute `grp->T` consumes about **25%** time.

However, for well-known ecc curves, the `grp->T` can be pre-computed, and statically initialized. 

I have moved the code which is used to compute `grp->T` from `ecp_mul_comb` to `ecp_group_load`. And then, all test are passed, and tls connection can be established without error.

```C
    unsigned char p_eq_g = 1;
    unsigned char w = ecp_pick_window_size( grp, p_eq_g );
    size_t T_size = 1U << ( w - 1 );
    size_t d = ( grp->nbits + w - 1 ) / w;

    grp->T = mbedtls_calloc( T_size, sizeof( mbedtls_ecp_point ) );
    if( grp->T == NULL )
    {
        abort();
    }

    for( size_t i = 0; i < T_size; i++ )
        mbedtls_ecp_point_init( &grp->T[i] );

    ecp_precompute_comb( grp, grp->T, &grp->G, w, d, NULL );
```

The only thing that makes `grp->T` different is the config option `MBEDTLS_ECP_WINDOW_SIZE`.

Since almost all users will not set `MBEDTLS_ECP_WINDOW_SIZE` to a customized value. And even if they set to a lower value, we can provider at most 5 statically computed `grp->T`.

Please implemnet this feature, it really affect the TLS performance a lot.

**Comment by chris-jones-arm** [comment]
Thanks for the request @Kxuan.

After looking at this it seems like a useful and very welcome addition to the library. If you would like to contribute this to the library then please feel free to open a pull request, otherwise we will try to pick this up when possible.

**Comment by mpg** [comment]
Hi @Kxuan and thanks for your report! I agree that it makes sense, and actually I created an issue some time ago which I think is about the same thing: https://github.com/ARMmbed/mbedtls/issues/4128 Can you check, and if you agree that we're talking about the same thing, then we can close one of the issues in order to avoid duplication?

And as @chris-jones-arm said, if you'd like to open a PR for that, you're welcome!

**Comment by Kxuan** [comment]
Hi @mpg 
Thianks for your reply. 
It seems the two issues are related to a same problem.

I will open a PR for this problem this week.
