### ISSUE TITLE
Upstream TLS 1.3 state machine logic 

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4329]
__Task:__ Study whether it is possible to upstream the core TLS 1.3 state machine logic without at the same time upstreaming each handshake state handler. Ideally, we upstream the frame first and then insert the state handlers one message a time. 

At the time of writing, it's not yet clear to me how feasible this is, but as a monolithic PR upstreaming the entire TLS 1.3 state machine with all state handlers at once is certainly not desirable, it's worth exploring at least.

**Comment by mpg** [comment]
As discussed today with @ronald-cron-arm and @yuhaoth we decided to not upstream the state machine separately, but do each step as we implement the corresponding step in the handshake. Hence closing this issue, as the work will be covered by other issues.
