### ISSUE TITLE
Mismatch of root CA and issuer of CRL not caught

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#433]
If the issuer of the CRL is not a given root CA, verification of the anomaly is not detected when calling `mbedtls_x509_crt_verify()`. This should be detected during verification.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-651

**Comment by sbutcher-arm** [comment]
This is planned to be fixed, but in the meantime as a workaround, a user could compare the name(s)
of the CRL(s) provide to the name(s) of the CA(s) before calling `mbedtls_x509_crt_verify()`.
