### ISSUE TITLE
Modify SSL session cache API to operate on opaque data

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4333]
__Context:__ Server-side session resumption is a feature of TLS by which client and server remember and continue a previously established session solely in terms of a unique identifier, the "session ID", that was attached to that session at the time of it handshake. This form of session resumption (which is to be distinguished from ticket- or PSK-based resumption in TLS <= 1.2) is suggested by the client by setting the `session_id` field in the `ClientHello` to the ID of the session the client wishes to continue. The server then looks up the session from its ID by means within an implementation defined 'session cache', and accepts or rejects the request based on the success and the metadata of the session it finds. This 'session cache' is conceptually a partial map from session IDs to sessions. 

__Support in Mbed TLS:__ The current server-side session cache APIs are as follows:

```c
/**
 * \brief          Cache get callback implementation
 *                 (Thread-safe if MBEDTLS_THREADING_C is enabled)
 *
 * \param data     SSL cache context
 * \param session  session to retrieve entry for
 */
int mbedtls_ssl_cache_get( void *data, mbedtls_ssl_session *session );

/**
 * \brief          Cache set callback implementation
 *                 (Thread-safe if MBEDTLS_THREADING_C is enabled)
 *
 * \param data     SSL cache context
 * \param session  session to store entry for
 */
int mbedtls_ssl_cache_set( void *data, const mbedtls_ssl_session *session );
```

What is striking here is that neither get nor set API pass the session ID as an explicit parameter. Instead, the session ID is a field within `mbedtls_ssl_session` and implementations have to extract the session ID from that. 

__Issue:__ The present choice of signature for the session cache API prevents us from making `mbedtls_ssl_session` opaque in Mbed TLS 3.0, as is -- to my understanding -- the general goal for most structures. The issue is to track the task of and discussion around finding a potential replacement API for the SSL session cache which allows us to make `mbedtls_ssl_session` opaque.

**Comment by hanno-arm** [comment]
__Proposal:__ Modify the signatures of `mbedtls_ssl_cache_{get,set}()` so that they take the session ID as an explicit parameter, and operate on _serialized_ sessions only:

```c
int mbedtls_ssl_cache_get( void *data,
                           unsigned char const *session_id,
                           size_t session_id_len,
                           unsigned char *dst_session,
                           size_t max_session_len,
                           size_t *session_len );

int mbedtls_ssl_cache_set( void *data,
                           unsigned char const *session_id,
                           size_t session_id_len,
                           unsigned char const *session,
                           size_t session_len );
```

__Implications:__
* Because the session ID is an explicit parameter, we can attempt to have the session cache operate on serialized sessions only, not the actual `mbedtls_ssl_session` instances.
* This implies a dependency of server-side session resumption on session serialization.
* Our reference implementation simplifies significantly, because it doesn't need to make copies of _referenced_ data in the session structure anymore, such as the peer's CRT: This is in fact taken care of by serialization already.
* The session cache abstraction gets simplified to a plain key-value associative array, with opaque keys and opaque values. 
* In particular, implementations cannot inspect session metadata anymore and incorporate it into their decision of whether to buffer the session or not. __Question:__ Is this a problem?
* Our present reference session cache implementation does more than just look up a session based on its ID: As mandated by [the standard](https://tools.ietf.org/html/rfc5246), it also checks that the ciphersuite and choice of compression match the server's choice after seeing the `ClientHello`. This logic can no longer be part of the session cache, and arguably, it doesn't belong there in the first place? Instead, the library would do the following:
  - Query the session cache for a serialized session matching the issued session ID.
  - If successful, deserialize the session.
  - If successful, validate the session's metadata in relation to the `ClientHello` (ciphersuite, compression) and perhaps expiration.
  - If successful, use the session for resumption.

Team, any opinions on this proposal?

I am happy to implement it if there's consensus -- I think it should be rather straightforward to implement and review.

**Comment by hanno-arm** [comment]
A flexible way to give the user access to connection information would be to pass the SSL context as another (`const`?) parameter to `mbedtls_ssl_cache_set()`. This way, whatever property of the established connection the user is able to retrieve by means of the existing SSL function API, can also be taken into account when deciding whether to cache a session or not. If there's a piece of information missing with this design, it's likely that the SSL function API is already incomplete.

**Comment by mpg** [comment]
Before commenting on the rest: I fully agree that all checks that are mandated by the standard need to be done inside the library rather that assuming the callback does them. I think that's a design mistake in the current API and I'd even consider it a bug that we probably want to fix in 2.x and 2.16.

I also agree about adding the session ID as a parameter to the callback: that's indeed something all callback implementations are going to need. (And presumably that's all that's be need for most callback implementations.)

I'm not sure I like the idea of passing the SSL context to `cache_set`, but I'll think about it.

**Comment by hanno-arm** [comment]
@mpg Thank you very much for your quick reply and for considering the proposal.

Do you think it makes sense at this stage to prototype the proposal, excl. the additional SSL context parameter for now (which our reference implementation wouldn't need)?

**Comment by mpg** [comment]
Yes, I was thinking a prototype could be a good way to validate the design or clarify what needs to be refined at this point.

I suspect `ssl_cache.c` will end up being quite simpler (no need to fiddle with `peer_cert` etc.) which is probably the sign of a design that's better than the current one.

**Comment by hanno-arm** [comment]
Prototyping this made me realize that passing the serialized session to `mbedtls_ssl_cache_set()` enforces an unnecessary allocation and copy: The caller (us) needs to temporarily allocate a buffer to hold the serialized data, which the cache implementation then needs to copy again because we use copy-semantics (move-semantics would solve this but isn't common in the library).

After discussion with @mpg, I've now implemented the following API instead:

**Comment by hanno-arm** [comment]
@laumor01 As suggested by @gilles-peskine-arm @mpg @yanesca in yesterday's engineering sync, marking this as `Mbed TLS 3.0`, not `Mbed TLS 3.0 optional`, as it's an important change for the forthcoming TLS 1.3 uspport.

**Comment by mpg** [comment]
I agree with moving to 3.0 (non-optional), as it's a necessary follow-up to work that is already in 3.0 non-optional, namely making structures opaque. Without that, 3.0 server-side session caching would not be usable in 3.0, which would be an unacceptable regression.
