### ISSUE TITLE
Question about fuzzing a binary using mbedtls

### ISSUE THREAD

**Issue by disconnect3d** [ARMmbed/mbedtls#4343]
Hey,

I am fuzzing an application that uses mbedtls and I am wondering if there a way to make mbedtls pass in application data with the recv/send functions registered into `mbedtls_ssl_set_bio` but not perform a SSL handshake?

I actually got my harness running by mocking the `mbedtl_ssl_handshake` to simply return 0 and the `mbedtls_ssl_read` to call the `recv` function that is registered with the `mbedtls_ssl_set_bio` call but maybe there is a better way to do it? As this solution may risk testing a case that may not happen on production (since it depends on whether the mocked `mbedtls_ssl_read` makes similar calls to the `recv` function).

**Comment by mpg** [comment]
Hi @disconnect3d and thanks for your interest in Mbed TLS. For questions and discussions, please use our mailing list https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls - we use github issues for bugs and feature requests only. Thanks!
