### ISSUE TITLE
Change the cipher.h API to allow delayed output of the last block for AEAD

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4355]
For some AEAD algorithms, such as GCM or CCM, when using a hardware accelerator, it may not be possible to process partial blocks. This means that if the input to `update()` does not end on a block boundary, it may need to keep a partial block in reserve. The finish function then outputs that last partial block of ciphertext/plaintext. See https://github.com/ARMmbed/mbedtls/issues/4350 for how the problem arose in GCM.

In the `mbedtls/cipher.h` API, for AEAD, the “finish” functions are `mbedtls_cipher_check_tag` and `mbedtls_cipher_write_tag`. Either these functions need to take an extra output buffer, or there needs to be an additional call (to the existing function `mbedtls_cipher_finish`?) to output the last block.

Goal of this task: adjust the `cipher.h` API to support alternative implementations. The implementation in `cipher.c` and the tests may be incompatible with alternative implementations that delay output for partial blocks.

Follow-up: adapt `cipher.c` and the tests https://github.com/ARMmbed/mbedtls/issues/4356

**Comment by mpg** [comment]
@gilles-peskine-arm It's unclear to me why we would need to improve our support for `_ALT` implementations now, considering PSA is the preferred way going forward.

(Note: I moved this provisionally to "3.0 optional" just because it wasn't part of the original plan while waiting for us to discuss priorities - nothing to do with the question/opinion above.)

**Comment by gilles-peskine-arm** [comment]
This isn't about improving ALT support, it's about relaxing the API to allow GCM with input that isn't block-aligned. This was necessary at the level of the GCM and CCM modules to implement multipart GCM/CCM through the PSA API (unless we were willing to duplicate the GCM/CCM code in `psa_crypto.c`).

Strictly speaking, we don't have to relax the cipher API: we could just make it error out if an application tries to use non-block-aligned input chunks. But it would be unfriendly to the many users who are not using the PSA API, for example because they're mostly using TLS and they don't care about opaque keys.

**Comment by gilles-peskine-arm** [comment]
> it wasn't part of the original plan

It wasn't in the original plan explicitly because we didn't realize that implementing multipart AEAD in PSA would require API changes to GCM and CCM. Multipart AEAD in PSA was in the original plan for 3.x, and any API changes required for it need to go into 3.0.

**Comment by mpg** [comment]
I did a review of the existing (or in progress, for CCM) APIs as a preparation for improving the cipher API.

- *GCM* `starts`(nonce) - `update_ad` - `update` - `finish`->output+tag
- *CCM* `starts`(nonce+lengths) - `update_ad` - `update` - `finish`->tag
- *ChachaPoly* `starts`(nonce) - `update_aad` - `update` - `finish`->tag
- *Current cipher* `set_iv`(nonce) - `reset` - `update_ad` - `update` - `finish`->output - `{write,check}_tag`->tag
- *PSA Crypto* `set_nonce`(nonce) - `set_lengths`(lengths)` - `update_ad` - `update` - `finish/verify`->output+tag

I included PSA Crypto in this list I understand it is a requirement that both PSA Crypto and the Cipher layer can be implemented reasonably efficiently on top of the first 3. (Also perhaps at one point we'll have a desire to implement Cipher on top of PSA Crypto - not saying it will happen, but I don't think that's a scenario we can rule out, so it's probably better if we can support this efficiently too.)

Currently there are discrepancies in how inputs/output are grouped:

- at the beginning: PSA Crypto uses separate functions for nonce and length, CCM uses only one (Cipher does not support multi-part CCM at the moment);
- at the end: Cipher uses two separate functions for remaining output and tag, PSA Crypto and GCM group them in a single function (CCM handles remaining output at the `update` stage, ChachaPoly never has remaining output).

While it's always possible to work around those discrepancies by buffering some data in the abstraction layer, it's undesirable as it complicates the implementation and consumes extra memory. I think it would be desirable to remove those discrepancies by:

- at the beginning: using separate functions for nonce and length in CCM too (and in Cipher as well)
- at the end: using a single function for ouput+tag in Cipher as well

@ronald-cron-arm @gilles-peskine-arm Wdyt?

**Comment by mpg** [comment]
> > we'll have a desire to implement Cipher on top of PSA Crypto
> 
> This is already happening with `MBEDTLS_USE_PSA_CRYPTO`,

Oh right, I should have known, thanks for the reminder.

Thanks for your feedback, I'll start reworking the Cipher API based on that!

**Comment by ronald-cron-arm** [comment]
I agree with the above. Regarding CCM, while working on the multi-part APIs, I wondered if it would not be better for finish() to have an output parameter (as GCM) and remove the burden on update() to detect the last part of data. I can see here that this would align the signature of CCM finish with the other AEAD finish function (but chachapoly). Thus wdyt ?

**Comment by gilles-peskine-arm** [comment]
For CCM I prefer to remove the burden on finish to handle remaining data.

**Comment by mpg** [comment]
I don't really have an opinion here, I think both are fine.

**Comment by ronald-cron-arm** [comment]
Thanks both. I haven't changed it in CCM.

**Comment by mpg** [comment]
> Either these functions need to take an extra output buffer, or there needs to be an additional call (to the existing function `mbedtls_cipher_finish`?) to output the last block.

Actually the multi-part tests already call `mbedtls_cipher_finish()` for AEAD ciphers as well. The documentation doesn't say that it shouldn't be called for AEAD ciphers, so arguably calling it was already mandatory. So I think here the least disruptive change is to not change any of the existing functions, but simply improve the documentation in order to make it clear that calling `finish()` is mandatory for AEAD ciphers as well.

(Also, regarding `set_lengths()`, since the Cipher layer currently doesn't support multi-part CCM, I don't think we have anything to do now: we'll add `mbedtls_cipher_set_lengths()` when we add multi-part CCM support to Cipher, not before.)
