### ISSUE TITLE
tls.mbed.org certificate expired this morning

### ISSUE THREAD

**Issue by jay** [ARMmbed/mbedtls#436]
~~~
The server (tls.mbed.org) presented a certificate that did not validate, due to RemoteCertificateChainErrors.

0 - A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

EXPIRED: 3/5/2016 5:31:02 AM
~~~

**Comment by sbutcher-arm** [comment]
Thanks for raising this! It has already been spotted and we're chasing up our ops guys to fix it. Apologies for lack of service in the meantime. It'll be fixed as soon as I can make it happen.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-660

**Comment by sbutcher-arm** [comment]
Now fixed. Apologies for the interruption to service. The certificate was renewed sometime ago but due to an error, not deployed on the mbed TLS site.
