### ISSUE TITLE
Implement rejecting use of private fields

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4373]
Implement the strategy for rejecting the use of private fields investigated in #4372 to the private fields of the classic API in 3.0 documented in #4371, as well as to PSA API private fields in both 2.2x and 3.0.

**Comment by mpg** [comment]
Note: we have about a hundred structures in public headers. We probably don't need to do all of them at once, though.

**Comment by gilles-peskine-arm** [comment]
> We probably don't need to do all of them at once, though.

It'll be easier to do them all at once with a global search-and-replace.

**Comment by mpg** [comment]
I'm probably missing something, but I was thinking it would need to be done struct by struct.

**Comment by gilles-peskine-arm** [comment]
This was done in https://github.com/ARMmbed/mbedtls/pull/4511
