### ISSUE TITLE
Test suites should work under Windows

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#438]
The mbed TLS unit test suites should work under Windows. @NWilson has raised a [PR #353](https://github.com/ARMmbed/mbedtls/pull/353). This should be reviewed and merged.

In addition the other tests should be ported.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-667

**Comment by sbutcher-arm** [comment]
This was fixed sometime ago by pull request #353, and so can now be closed.
