### ISSUE TITLE
Remove TLS record expansion API in Mbed TLS 3.0

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4384]
__Context:__ The SSL API `mbedtls_ssl_get_max_record_expansion()` provides an upper bound for the difference between record plaintext and ciphertext sizes, that is, the amount of overhead that record protection adds on the wire.

I can't see a reason why this would be of interest to users. If the goal is to calculate approximations of the maximum plaintext sizes from knowledge of the I/O buffer sizes, this isn't the way to do it as there's dedicated API for that purpose (see #4381). 

Suggestion: Remove `mbedtls_ssl_get_max_record_expansion()` from the public API for Mbed TLS 3.0.

__Work items for Mbed TLS 3.0:__
* Move the declaration of `mbedtls_ssl_get_max_record_expansion()` to `ssl_misc.h`.

**Comment by TRodziewicz** [comment]
@hanno-arm , I cannot find the `mbedtls_ssl_get_max_record_expansion()` function in the current code. The only similar function I see is `mbedtls_ssl_get_max_record_payload()`. Is this a typo or the function has been deleted in the meantime?

**Comment by hanno-arm** [comment]
@TRodziewicz I think we've just solved this, but forgot to tie the PR to this issue. #4382

**Comment by TRodziewicz** [comment]
As @hanno-arm said the issue has been resolved in #4382, so I'm closing this issue.

**Comment by ronald-cron-arm** [comment]
Thus just to be sure, @hanno-arm is it the case that #4382 fixed both #4381 and this issue ?
