### ISSUE TITLE
Baud rate suggested in readme not working

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbedtls#439]
https://github.com/ARMmbed/mbedtls/blob/development/yotta/data/example-selftest/README.md#getting-started
Suggest the baud rate is 115200 but in testing it is found the baud rate for k64f is defaulted to 9600. 

same for other examples as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-670

**Comment by sbutcher-arm** [comment]
This issue has been fixed in the most recent mbed TLS yotta release.
