### ISSUE TITLE
  utility rate of MDx, SHAx, AES and DES modules

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbedtls#440]
If MCU with HW security capability, mbedtls could support to override core functions from MDx, SHAx, AES and DES modules.

For cost effective & performance improvement, we consider to implement 1 or 2 **HW security** to accelerate the performance. For normal or default case of mbedtls operation, what's the _ranking of utility rate of these 4 security modules_ ?

**Comment by sbutcher-arm** [comment]
Both DES and MD5 are older and weak and have been broken, whilst AES and SHAx are newer and preferred. If you want to accelerate only one or two functions, I would recommend first providing support for AES, and then SHA.

I hope this answers your question. If not, please feel free to reply.

**Comment by cyliangtw** [comment]
Thanks of your reply.
In ChangeLog, it mentioned: 
`Ability to override core functions from MDx, SHAx, AES and DES modules with custom implementation (eg hardware accelerated), complementing the ability to override the whole module.
`
After tracing aes.c & sha256.c in library, I can't find any function defined with __weak export their symbols weakly. Except modify library source code & pull requests, how to override core functions for HW acceleration ?

More, I also found RSA & ECC (Elliptic Curve Cryptography) implementation in library, could we accelerate these 2 by the same overriding methodology ?

**Comment by sbutcher-arm** [comment]
Hi @cyliangtw,

This is really a support question, and a better place to pose the question would be through either ARM mbed support, or in the [mbed TLS forum here](https://tls.mbed.org/discussions).

To answer your question, hardware acceleration can be added to the library through conditional compilation, and by adding your own implementation of certain functions. These can be contained in separate source files, and linked into mbed TLS to provide substitute functions that work with the rest of the library.

For instance, if you wanted to provide your own implementation of AES encrypt, you could compile out the library implementation by defining in `config.h` the preprocessor symbol `MBEDTLS_AES_ENCRYPT_ALT` and providing your own implementation of `mbedtls_aes_encrypt()` in your own source file.

If you look through the source code you'll see use of equivalent `MBEDTLS_XXXX_ALT` symbols to allow you to remove and replace other functions.

Hope this helps!

**Comment by cyliangtw** [comment]
Hi Sbutcher,

Thanks of your kindly reply. It's clear to utilize ` MBEDTLS_XXX_ALT` .
Because my chip has  **RSA & ECP (Elliptic Curve Cryptography)** capacities and want to follow AES instance, I can't find any `xxx_ALT` symbol relative to **RSA & ECP** in source or header files.

**Comment by sbutcher-arm** [comment]
We plan to extend and include RSA and ECC at some point in the near future.
