### ISSUE TITLE
crypt_and_hash.c bug with GCM

### ISSUE THREAD

**Issue by udf2457** [ARMmbed/mbedtls#441]
The following test is a buggy in that it fails when used with GCM ciphers (e.g. AES-128-GCM) 

mbedtls/programs/aes/crypt_and_hash.c 
>         if( ( ( filesize - mbedtls_md_get_size( md_info ) ) %
>                 mbedtls_cipher_get_block_size( &cipher_ctx ) ) != 0 )
>         {
>             mbedtls_fprintf( stderr, "File content not a multiple of the block size (%d).\n",
>                      mbedtls_cipher_get_block_size( &cipher_ctx ));
>             goto exit;
>         }

My understanding is that GCM does not require padding.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-678

**Comment by sbutcher-arm** [comment]
Fixed by PR#546, so the issue can now be closed.
