### ISSUE TITLE
Remove MBEDTLS_ENABLE_WEAK_CIPHERSUITES configuration option

### ISSUE THREAD

**Issue by ronald-cron-arm** [ARMmbed/mbedtls#4416]
### Rationale
Remove the configuration option to enable weak ciphersuites -- These suites are dangerous to use and it is highly recommended not to use them and to upgrade to more secure ciphersuites. 

----------------------------------------------------------------
### Work items for 3.0
- Remove all references to MBEDTLS_ENABLE_WEAK_CIPHERSUITES.

**Comment by mpg** [comment]
Note: weak ciphersuites have already been removed in a previous PR, so all that's left to do is to remove the option.
