### ISSUE TITLE
Upstream TLS 1.3 ClientHello writing, ephemeral-only exchanges

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4417]
__Depends on:__ https://github.com/ARMmbed/mbedtls/pull/4864

__Task:__

Upstream the preparation, writing and postprocessing of the `ClientHello` in TLS 1.3, restricting to pure-ECDHE key exchanges. In particular, at this point we do _not_ want to upstream `psk_key_exchange_modes` and the `pre_shared_key` extensions. In particular, we do _not_ need the PSK-specific amendment https://github.com/hannestschofenig/mbedtls/blob/7fb7a3dbc3d9ce786199447c3a31661e08a0f78f/library/ssl_tls13_client.c#L1377-L1392. 

Tentative breakdown of technical steps:
- [x] Identify which SSL context/handshake fields are needed for the writing of the `ClientHello` message, and upstream them, with appropriate documentation. Example: The `handshake->offered_group_id` field is needed to track the group ID of the key share the client offers.
- [x] Identify which SSL API needs upstreaming and add command line parameters to `ssl_client2` to configure them. _Example:_ We probably need the new [sig_hash API](https://github.com/hannestschofenig/mbedtls/pull/322) __NOTE:__ We might want to do this in separate PRs.
- [x] Add [state machine handler](https://github.com/hannestschofenig/mbedtls/blob/7fb7a3dbc3d9ce786199447c3a31661e08a0f78f/library/ssl_tls13_client.c#L1351) for `ClientHello` and the [dispatch](https://github.com/hannestschofenig/mbedtls/blob/7fb7a3dbc3d9ce786199447c3a31661e08a0f78f/library/ssl_tls13_client.c#L3942) from the top-level client-side state machine
- [x] Add dummy state machine handler for `ServerHello` stage, which fails gracefully with `FEATURE_UNAVAILABLE` and prints something we can grep for, and potentially even send a `HANDSHAKE_FAILURE` alert to the server.
- [x] Add a test to `ssl-opt.sh` exercising the functionality -- see acceptance criteria.

__Acceptance criteria:__
* `ssl-opt.sh` has a test which runs a TLS 1.3 "handshake" with an Mbed TLS client against an OpenSSL server. The debug output confirms that the OpenSSL server has received and parsed the ClientHello, and replied with a ServerHello. The Mbed TLS client fails gracefully at the `ServerHello` stage -- either with a debug message we can grep for, or potentially with an alert which we can confirm on the OpenSSL server side.

**Comment by mpg** [comment]
Re-opening as #4861 was only the first of several parts.

**Comment by yuhaoth** [comment]
we haven't reached the target. openssl server haven't sent server hello msg

**Comment by ronald-cron-arm** [comment]
#4811 was only part of the story.

**Comment by mpg** [comment]
4879 was not the end yet.

**Comment by ronald-cron-arm** [comment]
Not completed yet, one last PR to merge: #4891.
