### ISSUE TITLE
ChaCha20 Poly1305 (enhancement request)

### ISSUE THREAD

**Issue by udf2457** [ARMmbed/mbedtls#442]
Any plans to add ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-680

**Comment by sbutcher-arm** [comment]
Yes we have! This is a planned feature, and has already requested in issue #346. Unfortunately beyond it being a planned feature, I'm unable to say when we might support it.

Closing this issue as a duplicate.
