### ISSUE TITLE
Header name is too common in `#include "common.h"`

### ISSUE THREAD

**Issue by tommikas** [ARMmbed/mbedtls#4425]
---------------------------------------------------------------
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

https://github.com/ARMmbed/mbedtls/pull/3454 introduced an include `#include "common.h"`. This is an often used filename for such shared headers so the omission of any specifying path can easily cause clashes with other headers.

Changing the include to follow the previously established pattern of `#include "mbedtls/common.h"` resolves the problem.

**mbed TLS build:**  
Version: Since #db09ef6d22f3043536910833c43faf425a7e0401

**Expected behavior**   
Compiling with another file called `common.h` in the include paths works predictably. Provided both files are included with path, at least.

**Actual behavior**  
Behavior depends on toolchain. Depending on exact circumstances everything might work, or compilation just fails.

**Steps to reproduce**  
Add another `common.h` file into the build.

**Comment by tommikas** [comment]
@gilles-peskine-arm fyi ^

I ran into this trying to update to the latest mbed OS release.

**Comment by gilles-peskine-arm** [comment]
Well, we certainly can rename `common.h`. But if your build process passes directories ahead of `.` in the include path, you're likely to run into many such problems.

**Comment by tommikas** [comment]
> Well, we certainly can rename `common.h`.

It's not the name of the header that is the problem as much as going from `mbedtls/config.h` to just `common.h`. Both header names are generic, but the path makes one specific for mbedtls. All the other mbedtls library internal includes have the path in them, so why shouldn't this?

> But if your build process passes directories ahead of . in the include path, you're likely to run into many such problems.

Perhaps, but wouldn't it make sense for mbedtls to minimize its contributions to such issues? To be as well behaved as reasonably possible, in a way.

Anyway, this is a particularly big problem with the `mbed` build tools with the single "everything is visible to everyone" way of handling include paths. If the list of paths is generated only once, it can't be ordered by shortest path relative to each file or even library.

**Comment by gilles-peskine-arm** [comment]
> All the other mbedtls library internal includes have the path in them, so why shouldn't this?

No, internal includes don't have a directory part. Our source tree layout is pretty standard for a crypto library ([this came up recently](https://github.com/ARMmbed/mbedtls/pull/4164)). Having the library name in the path to internal headers is not usual.

> Anyway, this is a particularly big problem with the mbed build tools with the "everything is visible to everyone" way of handling include paths.

I was aware that Mbed OS needed unique object names. I wasn't aware of issues with header file names.

> If the list of paths is generated only once, it can't be ordered by shortest path relative to each file or even library.

This isn't about changing the order of header inclusion for different parts of Mbed OS. Why isn't `.` first on the include path? If it isn't, I'm surprised that Mbed TLS is the first thing to break.

**Comment by tommikas** [comment]
Oh now I see what you're getting at... Sorry, I missed the changes in https://github.com/ARMmbed/mbedtls/pull/4164. When I ran into the problem I was using mbed OS 6.9.0 which is missing this PR so `common.h` is still in `include/mbedtls/common.h`. With the moving of the header into the source directory the problem is resolved. (For mbedtls anyway, but for the internal component it'd be our problem if it broke.)

So yeah, you're right, even the mbed build system gets it right if the header is in the same path with the source file. That means the real fix for this is updating the mbed OS version of mbedtls to a recent enough version.

Sorry about the bother. I'll close this.

**Comment by gilles-peskine-arm** [comment]
We never had `include/mbedtls/common.h`. `library/common.h` was introduced in #3121 and never moved.

It looks like there's a problem with the Mbed OS importer, that it's importing Mbed TLS's `library/common.h` into `include/mbedtls` instead of `source`. It's correctly importing `ssl_invasive.h` to `source`, however.

**Comment by tommikas** [comment]
> It looks like there's a problem with the Mbed OS importer, that it's importing Mbed TLS's library/common.h into include/mbedtls instead of source. It's correctly importing ssl_invasive.h to source, however.

So where should that issue be reported?

**Comment by gilles-peskine-arm** [comment]
In Mbed OS. The Mbed TLS team doesn't maintain the Mbed TLS integration in Mbed OS. Checking the Git history, `common.h` was moved in https://github.com/ARMmbed/mbed-os/pull/14354 “so PSA Crypto can find it”, but this doesn't look right. It's a private header of the Mbed TLS source and it doesn't make sense to include it from non-Mbed-TLS source files. I haven't looked further into what problem this was supposed to solve so I can't offer an alternative solution.

**Comment by tommikas** [comment]
Alright, thanks, I'll talk to the mbed OS guys then 👍 Sorry again for the bother.
