### ISSUE TITLE
SipHash (enhancement request)

### ISSUE THREAD

**Issue by udf2457** [ARMmbed/mbedtls#444]
PRF optimized for speed on short messages

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-681

**Comment by sbutcher-arm** [comment]
As I've already said in my reply to issue #443, mbed TLS is a [SSL library](https://tls.mbed.org/ssl-library) and as a consequence, the crypto primitives it supports are there to support TLS. SipHash is not yet part of the TLS standards in any form, so is not something we are planning to support.

In addition, I'm not sure there's much value in mbed TLS having an implementation. mbed TLS is a C library you can choose the functions you want or need from, and for SipHash [there are already many alternative implementations available](https://131002.net/siphash/#sw) under different licenses. I'm not sure we'd offer anything that isn't already available.

Therefore I'm closing this issue, but if anyone wants to contribute code, and really wants to see it in mbed TLS, we're happy to discuss it.
