### ISSUE TITLE
How to improve performance of RSA sign?

### ISSUE THREAD

**Issue by icefrog** [ARMmbed/mbedtls#447]
Hi,

It's known that the signing of RSA is much slower than verifying. Are there possibilities to optimize signing? e.g., enable settings in config file.  (though I'm aware it is difficult to optimize the algorithm itself) The signing function I used here is `mbedtls_rsa_pkcs1_sign()`.  

Our stress tests(50 threads) show signing degrades TPS by 60-70%, while verifying degrades TPS by only 5-10%

Many thanks.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-689

**Comment by sbutcher-arm** [comment]
Hi @icefrog 

This is actually a support question and not an issue, and would be better posted to the [mbed TLS support forum](https://tls.mbed.org/discussions) to seek an answer from the community, or alternatively [commercial support is available to mbed Partners](https://www.mbed.com/en/partners/become-partner/).

To answer your question, very simply, I'm not sure there is an easy answer. If your choice of platform offers hardware acceleration for RSA in some form, you could use that, but outside of getting faster hardware, there are no library configurations that will help, and any other optimisations will involve changing the source code of the library.
