### ISSUE TITLE
Process for generating source files in releases

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4475]
Since https://github.com/ARMmbed/mbedtls/pull/4395, the `development` branch no longer includes some source code files and build scripts that are automatically generated. We still want these generated files to be present in releases.

The goal of this task is to define a process to generate the files for releases. Depending on what the process is, additional tasks may be necessary to build some tooling.

**Comment by yanesca** [comment]
I have updated the release process, so far it looks like we won't need additional tooling. Keeping this issue open until the next release and only close it when we have already tested the process and have higher confidence.

**Comment by gilles-peskine-arm** [comment]
We have now done two releases following the process. It's working well enough (with [one known issue](https://github.com/ARMmbed/mbedtls/issues/5432)). We can close this issue.
