### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by samphunter** [ARMmbed/mbedtls#451]
file: mbedtls/include/mbedtls/dhm.h
line: 224
`param olen     must be equal to ctx->P.len`
Shouldn't it be ctx->len ??

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-696

**Comment by sbutcher-arm** [comment]
Yes, I think you're right. I've tried to clarify the parameter in 2917b9e.

This has been pushed to the development branch, so I think this issue can now be closed.
