### ISSUE TITLE
mbedtls yotta module tied to target K64F

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbedtls#453]
mbedtls is #include "MK64F12.h" in https://github.com/ARMmbed/mbedtls/blob/development/yotta/data/entropy_hardware_poll.c

Tying the mbedtls yotta module to K64F target only. This should use an Entropy API, that can be implemented by different targets.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-699

**Comment by sbutcher-arm** [comment]
Hi,

It's a known limitation of the current port of mbed TLS to mbed OS only supports the Freescale K64F. A more generic solution is planned for the future.

**Comment by markus-becker-tridonic-com** [comment]
@mlnx Please share, when this will be changed.

**Comment by Areontar** [comment]
Hi, 

Seems that this is now an issue now when trying to compile the Atmel-samg55j19-gcc target, same error as stated above.  MbedTLS get brought in by adding the mbed-client dependency.  I will try to see how I can work around that for now, but is there a roadmap for the resolution?

Thanks

**Comment by markus-becker-tridonic-com** [comment]
Looks like this is solved with mbed5.1
