### ISSUE TITLE
all.sh does not execute on OSX

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#455]
The script tests/scripts/all.sh does not execute on OSX, and does not fail gracefully. It also appears to fail differently for the 2.1 upwards and in 1.3.

By the nature of `all.sh`, it may not be possible to execute all tests because some may not be available on OSX (such as armcc may not be available), but whatever the current issues, they should either be fixed, or alternatively it should exit with a nice error message of why it can't execute, or on what platform it can't run on.

It should also be considered whether it's worthwhile executing what _can_ be executed, with test exceptions noted at the end of the run.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-701
