### ISSUE TITLE
NXP 5746C [PPC] run programs/ecdsa fail

### ISSUE THREAD

**Issue by shengxiang200788** [ARMmbed/mbedtls#4556]
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
rtos

**mbed TLS build:**  
Version: 2.26.0
OS version: x.x.x  01.00
plateform: NXP 5746C big endian

**Expected behavior**   
Run progam/ecdsa
mbedtls_ecdsa_read_signature() should return 0

**Actual behavior**  
mbedtls_ecdsa_read_signature() return  MBEDTLS_ERR_ECP_INVALID_KEY

**Steps to reproduce**  
1. run ecdsa
2. mbedtls_ecdsa_read_signature() return  MBEDTLS_ERR_ECP_INVALID_KEY
----------------------------------------------------------------

**Comment by tom-daubney-arm** [comment]
Hi @shengxiang200788 ,

It is possible that you are seeing an arithmetic bug since we do not test on PPC architecture. In order to help I will need more information, please.

Can you tell me what compiler you are using? And also any compiler flags would be helpful too.

Additionally I will need the contents of your config.h file so please send that over as well.

Thanks,
Tom

**Comment by shengxiang200788** [comment]
I use S32DS to compile the mbedtls
compile flags are: -std=c99 -DCPU_MPC5746C  -O0 -g3 -Wall -c -fmessage-length=0 -msdata=eabi -mlra -funsigned-bitfields -ffunction-sections -fdata-sections -fno-common -mcpu=e200z4 -specs=ewl_c9x.specs -mbig -mvle -mregnames -mhard-float

[config.zip](https://github.com/ARMmbed/mbedtls/files/6545524/config.zip)

**Comment by daverodgman** [comment]
#3855 may be relevant for improving testing on PPC

**Comment by shengxiang200788** [comment]
I add memset in function  mbedtls_mpi_grow( mbedtls_mpi *X, size_t [`[nblimbs](url)`](url) ) to
zeroize the memory allocated by mbedtls_calloc( nblimbs, ciL ) , like:
 memset(p, 0 , nblimbs * ciL);
It works now.

**Comment by gilles-peskine-arm** [comment]
> to zeroize the memory allocated by mbedtls_calloc

I'm glad you found the problem!

Your fix is incomplete, however. `mbedtls_calloc` must zeroize the memory. That's the job of `calloc` (as opposed to `malloc` which leaves the memory contents undefined). If `mbedtls_calloc` doesn't zeroize the memory, you'll have a lot of other problems. So you need to fix the library integration (or the platform library).

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue since it turned out not to be a bug in Mbed TLS.

**Comment by shengxiang200788** [comment]
Good, thanks for your reply.

> I'm closing this issue since it turned out not to be a bug in Mbed TLS.
