### ISSUE TITLE
clang-analyzer is identifying some minor issues that should be resolved

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#458]
The [Clang Static Analyzer](http://clang-analyzer.llvm.org) when used on mbed TLS is identifying some minor issues that should be resolved.

@NWilson has raised a Pull Request #457, which fixes those issues he's seen.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-706

**Comment by RonEld** [comment]
Closed since it was outdated, fixed and merged.
If you feel this was wrongfully closed, you may reopen this issue
