### ISSUE TITLE
2.16: Bias in private key generation in Diffie-Hellman

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4612]
This is a duplicate of https://github.com/ARMmbed/mbedtls/issues/4245 for tracking purposes. The goal is to fix the issue in Mbed TLS 2.16. The fix for 2.x/3.0 in https://github.com/ARMmbed/mbedtls/pull/4276 is too invasive for an LTS branch so we need a simpler structure in 2.16.

**Comment by bensze01** [comment]
I believe this was fixed in #4628. Can we go ahead and close it?

**Comment by gilles-peskine-arm** [comment]
Fixed in https://github.com/ARMmbed/mbedtls/pull/4628
