### ISSUE TITLE
Add -fPIC compiler flag

### ISSUE THREAD

**Issue by janekolszak** [ARMmbed/mbedtls#462]
Hi,
Is there any reason the -fPIC flag isn't added in the library's CMakeLists.txt?

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")

Cheers,
Jan

**Comment by jcowgill** [comment]
When building shared libraries, CMake adds `-fPIC` by default. For static libraries, most of the time you probably don't need position independent code anyway.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-711

**Comment by sbutcher-arm** [comment]
mbed TLS is used in many different ways on many different platforms, both as as a static library and a dynamic library, so I don't think we want to include much in `CMAKE_C_FLAGS` as that's too inflexible.

If you look at the `Makefile` we ship with mbed TLS you'll see we include `-fPIC` when building the shared library, and if you use CMake, as @jcowgill has already said, CMake includes the option for the shared library target.
