### ISSUE TITLE
New releases ?

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#463]
would you please clarify what's the proper way to get new mbedtls releases ?, In the Github [releases page](https://github.com/ARMmbed/mbedtls/releases) I see different release names, not sure what they are:

- yotta-2.3.0
- mbedos-2016q1-oob3

In the other side, in the main web site the latest release is mbedtls-2.2.1:

https://tls.mbed.org/download

Please clarify what's the latest version of mbedtls, as well explain release names.

**Comment by sbutcher-arm** [comment]
mbed TLS is available as a standalone download from the [mbed TLS website, here](https://tls.mbed.org/download). Versions in the repository that lead 'mbedtls-x.y.z' relate to those releases.

However, mbed TLS is also available as a [yotta module](http://yottadocs.mbed.com), and as a part of [mbed OS](https://www.mbed.com/en/development/software/mbed-os/), which is what the other version numbers relate to.

Unless you're using mbed OS, I would recommend you download mbed TLS from the website using the link above, or if you take it from github, checkout the version that's appropriate for you that is tagged 'mbedtls-x.y.z' from [the last release](https://tls.mbed.org/tech-updates/releases/mbedtls-2.2.1-2.1.4-1.3.16-and-polarssl.1.2.19-released).

I hope this helps.

**Comment by edsiper** [comment]
I am facing issue #383 when using mbedtls-2.2.1, what's the suggestion ? (common Linux on ARM)

**Comment by edsiper** [comment]
I found that mbedtls-yotta-2.3.0 fixes the issue, but the library still is named as mbedtls-2.2.1. When mbedtls-2.3.0 will be out with these changes ?

**Comment by sbutcher-arm** [comment]
Hi,

I know it's confusing but the Yotta version numbers are independent of the mbed TLS version numbers, so the yotta version 2.3.0 is actually between the last formal mbed TLS version and the next one - which may also be version 2.3.0. To avoid confusion in future, we're considering bumping the yotta number by 10 to 12.3.0 or similar so they are more obviously unrelated.

However, to answer your question, while I can't give an exact date, I can say we're working on a release right now, and I expect to see it out in the next few weeks.

Again, I hope this helps!
