### ISSUE TITLE
Add support for copying opaque keys within the same lifetime

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#4638]
### Suggested enhancement

Add support for copying opaque keys within the same lifetime, as described in `psa-driver-interface.md`

Follow-up task for #4294 

### Justification

Mbed TLS needs this because it is part of an already-described specification document.

**Comment by mpg** [comment]
@ronald-cron-arm I'm not familiar with this area, do you think you could add a size estimate for this? Thanks!

**Comment by ronald-cron-arm** [comment]
I will have a look.
