### ISSUE TITLE
Define process for updating Dockerfiles

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4639]
Placeholder to track the work in:

https://github.com/ARMmbed/mbedtls-test/issues/165

so that we can accurately estimate the Q3 Tech Debt epic

**Comment by ronald-cron-arm** [comment]
I've removed this issue form the product backlog and the unified projects as it was a duplicate of https://github.com/ARMmbed/mbedtls-test/issues/165 in those boards. I've kept it in the EPICs board as https://github.com/ARMmbed/mbedtls-test/issues/165 cannot be added to this project.
