### ISSUE TITLE
compat.sh: write a python tool to translate ciphersuite names

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4674]
Currently `tests/compat.sh` has manually-maintained lists of ciphersuites to test, which need to exist in three versions: one with the Mbed TLS name (which is the same as the standard except for `_` vs `-` everywhere), one with the OpenSSL names, and one with the Gnu TLS priority string that will enable that ciphersuite. See the three variables `M_CIPHERS`, `O_CIPHERS` and `G_CIPHERS` in the script.

It would be desirable (as a first step) to only have a single list to maintain. Unfortunately, the naming scheme in OpenSSL is irregular (for example, the key exchange is omitted when it's RSA) and AFAIK undocumented; Gnu TLS priority strings are more regular and better documented but IIRC there are some quirks too. The rules can probably be inferred from looking at the names in the existing lists, though.

The goal of this task is to:

1. Write a python script that is able to auto-translate from the standard/Mbed TLS  name of a ciphersuite to its OpenSSL name or the corresponding Gnu TLS priority string.
2. Call it from `compat.sh` to avoid the need for the `O_CIPHERS` and `G_CIPHERS` variables, which should be removed.

Validation: the PR should include evidence that the new script translates correctly by comparing its results to the existing lists.

Note: the point of writing this new script in Python is twofold: (1) writing it in shell would probably be harder and (2) in the mid/long-term we'd like to re-implement `compat.sh` in Python, to it helps if some of the building blocks already exist as Python scripts.

Note: this only needs to work for (D)TLS 1.2 ciphersuite names. Earlier versions have been removed, 1.3 is not supported yet and will have a different concept of ciphersuite anyway.

**Comment by JoeSubbiani** [comment]
```
297:     TLS-DHE-RSA-WITH-3DES-EDE-CBC-SHA
311:    +DHE-RSA:+3DES-CBC:+SHA1
325:     EDH-RSA-DES-CBC3-SHA
```
Is this a typo on line 325, or is the OpenSSL convention just really bizarre? The lines before 325 for OSSL begin with `DHE-RSA` so thought I should check just incase. I presume it is a typo but the OSSL convention has so many quirks I thought it would be worth bringing up

![image](https://user-images.githubusercontent.com/85489920/126334638-700ca0d9-8fde-4696-9d0d-80deff510c79.png)

**Comment by gilles-peskine-arm** [comment]
> Is this a typo on line 325, or is the OpenSSL convention just really bizarre? The lines before 325 for OSSL begin with DHE-RSA so thought I should check just incase.

Looks correct. From `man ciphers`:
```
       DHE, EDH
           Cipher suites using authenticated ephemeral DH key agreement.
```
I don't know if there's supposed to be a difference between the two or if you have to use the correct form for each ciphersuite. Listing ciphersuites with an old OpenSSL does show `EDH` for the DES ciphersuites (which recent versions of OpenSSL no longer support).
```
~/Packages/openssl-1.0.2g/bin/openssl ciphers | tr : \\n | sort | grep EDH
EDH-DSS-DES-CBC3-SHA
EDH-RSA-DES-CBC3-SHA
```

----

> There is also a NULL-SHA256 on line 386 that does not correspond to MBedTLS or GNU and I don't understand why it is there

Null ciphersuites (which do authentication (unless also disabled) and data integrity but not encryption) are a thing. You have to go out of your way to enable them.
```
$ openssl ciphers ALL:COMPLEMENTOFALL | tr : \\n | sort | grep NULL
AECDH-NULL-SHA
DHE-PSK-NULL-SHA
DHE-PSK-NULL-SHA256
DHE-PSK-NULL-SHA384
ECDHE-ECDSA-NULL-SHA
ECDHE-PSK-NULL-SHA
ECDHE-PSK-NULL-SHA256
ECDHE-PSK-NULL-SHA384
ECDHE-RSA-NULL-SHA
NULL-MD5
NULL-SHA
NULL-SHA256
PSK-NULL-SHA
PSK-NULL-SHA256
PSK-NULL-SHA384
RSA-PSK-NULL-SHA
RSA-PSK-NULL-SHA256
RSA-PSK-NULL-SHA384
```

I don't know if something is missing from the M list. We do enable some NULL ciphersuites for M above. In the G list, I guess the `+NULL` in the `` `minor_ver "$MODE"` -gt 0 `` block is enough.

----

> ```
> What it is:
> PSK-3DES-EDE-CBC-SHA
> PSK-AES128-CBC-SHA
> PSK-AES256-CBC-SHA
> 
> What it should be:
> PSK-DES-CBC3-SHA
> PSK-AES128-SHA
> PSK-AES256-SHA
> ```

Again, looks correct based on the cipher list in older OpenSSL. 

----

> There is also 2 instances I have found so far where I would need to do something along these lines: replace("ECDHE-RSA-ARIA", "ECDHE-ARIA").

No, those would be different ciphersuites. ECDHE-symmetric is a ciphersuite without authentication. ECDHE-RSA-symmetric, ECDHE-ECDSA-symmetric and so on use RSA/ECDSA/… for authentication. It looks like OpenSSL doesn't have ECDHE-RSA ciphersuites for whatever reason.

**Comment by gilles-peskine-arm** [comment]
If you rewrite names from a canonical set, the best canonical set would be the [official names](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4). Alternatively, use the Mbed TLS names. I think they're the official names except with `_` replaced by `-` for some reason (but there may be inadvertent exceptions).
