### ISSUE TITLE
Remove MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES in 2.28

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4679]
The compile-time option `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` was intended as a temporary thing to facilitate the transition in environments with SHA-1 certificates. It's been over 3 years, and it's way past time it got removed. Everyone should have upgraded their infrastructure to support and use SHA2 by now.

We've of course [removed it in 3.0](https://github.com/ARMmbed/mbedtls/pull/4266). I propose to remove it from 2.27 or 2.28 as well before it goes LTS.

I'm on the fence with `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE` which is less dangerous, but still not something people should be using in 2021.

This would be mostly a backport of https://github.com/ARMmbed/mbedtls/pull/4266 (note that a couple of tests needed to be tweaked), plus possibly a commit from https://github.com/ARMmbed/mbedtls/pull/4604.

**Comment by yanesca** [comment]
We discussed it with @mpg and think that probably it would be best to keep the `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE` option, but disable it in the default configuration.

**Comment by mpg** [comment]
We discussed this with @daverodgman and @yanesca and reached a consensus that for 2.28 we should:

1. Remove `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` entirely (which was already disabled by default in `config.h)
2. Disable `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE` by default but not remove it (it is currently enabled by default).

**Comment by mpg** [comment]
Considering the previous comment, I think this no longer needs design approval.

**Comment by gilles-peskine-arm** [comment]
Merged https://github.com/ARMmbed/mbedtls/pull/4898
