### ISSUE TITLE
PRINTABLE_STRING in signing request prevents wildcard domains

### ISSUE THREAD

**Issue by kevinpt** [ARMmbed/mbedtls#468]
When creating a certificate signing request, x509_write_name() uses the PRINTABLE_STRING type for everything but emailAddress. This prevents the use of asterisks to create a wildcard domain as part of the common/domain name since they aren't part of that character set. The request will still be created but Openssl complains about invalid characters and stops processing the request.

It would be more useful to also use IA5_STRING for the MBEDTLS_OID_AT_CN OID.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-733

**Comment by sbutcher-arm** [comment]
Hi @kevinpt,

This isn't a planned enhancement, but we would certainly welcome a community contribution that provides this as a configurable option.

**Comment by hanno-arm** [comment]
Fixed through #1641.
