### ISSUE TITLE
Re-introduce extended checks for psa unlock/wipe key slot

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4680]
As part of #4516, commit https://github.com/ARMmbed/mbedtls/pull/4516/commits/cc7074128a437cbca66dcc0f710c764d0021d0cd remove calls to `MBEDTLS_PARAM_FAILED()` in `psa_unlock_key_slot()` and `psa_wipe_key_slot()` that we want to replace in some way, see for example https://github.com/ARMmbed/mbedtls/pull/4516#issuecomment-851317735

These will probably be re-introduced by the means of some kind of callback when `MBEDTLS_TEST_HOOKS` is defined, somewhat similarly to what's done for testing mutexes (see `tests/src/threading_helpers.c`).

**Comment by mpg** [comment]
@ronald-cron-arm @gilles-peskine-arm Could one of you double-check that the description makes sense and that the size estimate looks realistic? Thanks!

**Comment by gilles-peskine-arm** [comment]
I think S is a realistic size estimate: `psa_unlock_key_slot` already returns an error code, and all we need to do is make sure that we don't further corrupt an already corrupt slot on the recovery path.

Related: [testing](https://github.com/ARMmbed/mbedtls/issues/4464)
