### ISSUE TITLE
[placeholder] community feedback on private fields

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4682]
This is a placeholder for planning / estimation purposes, as an attempt to account for a known unknown.

What we know: since we made most structure fields private, it's almost certain that we overshot and that we'll get some feedback that we broke some uses cases that are important to users, and we'll have to fix this early in the 3.x cycle in order to make Mbed TLS usable again for those users. (This will likely be done either by making some fields public again, or adding accessor functions or other suitable APIs.)

What we don't know: what uses cases exactly did we break? We're counting on our users to tell us! Until then, we can't fix things.

Estimating as an M, but it should be clear from the nature of this placeholder that this estimate is completely arbitrary and comes with a lot of uncertainty.

**Comment by paul-elliott-arm** [comment]
First request : https://github.com/ARMmbed/mbedtls/issues/4885 (added to this epic)

**Comment by mpg** [comment]
Closing as this was only a placeholder and now that the community had time to react and report issues, we now have specific issues to track instead:

- #4885 
- https://github.com/ARMmbed/mbedtls/issues/4839
- https://github.com/ARMmbed/mbedtls/issues/4868
- part of https://github.com/ARMmbed/mbedtls/issues/4790

The first three issues above have been added to this EPIC, so this placeholder can now be closed.

**Comment by gilles-peskine-arm** [comment]
I expect that more similar issues will come up, that's fine, we'll handle them as they come.
