### ISSUE TITLE
Finalize 3.0 migration guide (and changelog)

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4691]
Once code is frozen for 3.0, in addition to the normal release process there are a few things to do regarding the migration guide (and ChangeLog).

1. Assemble the migration guide. (Could be something like `cat docs/3.0-migration-guide.d/*.md > docs/3.0-migration-guide.md` followed by `git rm`.)
2. Go over the assembled migration guide, check for inconsistencies between entries and resolve them (examples: one entrie says `starts()` had been removed, you should use `starts_ret()` and another entry says `starts_ret()` has been rename to `starts()`; some entries mention changes in MD2 but it has been removed later, etc.) _Note:_ this step applies to the ChangeLog too!
3. Re-order entries in the migration guide to place the most impactful changes first. Perhaps also write a summary of the highlights before the long list of entries.
4. Ideally, make the style more consistent across entries.
5. Move the migration guide file from the mbedtls repo to the mbedtls-docs repo.

**Comment by gilles-peskine-arm** [comment]
> Move the migration guide file from the mbedtls repo to the mbedtls-docs repo.

Why not keep it in the mbedtls tree? This is version-specific, at least for the time being.

**Comment by mpg** [comment]
Yes, I wasn't sure about that one either. Initially we said we wanted it in mbedtls-docs and were only putting it in the code repo temporarily to make our lives easier. But now I'm thinking it's not so clear. Perhaps people would like to have a look at what the migration involves before deciding to migrate and for that it might be easier to have it in mbedtls-docs?

**Comment by daverodgman** [comment]
I have an updated draft here, for people to review

https://github.com/daverodgman/mbedtls/blob/migration-guide/docs/3.0-migration-guide.md

**Comment by mpg** [comment]
It looks to me like #4737 addressed points 1-4 and it seems point 5 is no longer something we want to do, so I'm closing this issue. Please re-open if you disagree.

**Comment by gilles-peskine-arm** [comment]
#4737 didn't handle the changelog. I figured we'd do that during the release preparation.
