### ISSUE TITLE
Curve order in Mbed TLS 2.2x

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4698]
In Mbed TLS 2.23 onwards, the order of elliptic curves in `mbedtls_ecp_curve_list()`, which is the default order of preference in TLS (documented in `mbedtls_ssl_conf_curves`), is inconsistent: it has Weierstrass curves in decreasing order of size, and Montgomery curves in reverse order at the end. In both cases, up to Mbed TLS 2.26 the documentation only mentions “ordered by decreasing preference”, without saying what the preference is. https://github.com/ARMmbed/mbedtls/pull/4621 updates the documentation in 2.27.

Mbed TLS 3.0 [changes the order](https://github.com/ARMmbed/mbedtls/pull/4604) to have curves in decreasing order of size. Mbed TLS 2.16 didn't have Montgomery curves yet so it is not concerned (not that we'd make such a change in an LTS anyway) except that we may want to clarify the order in the documentation.

Goals of this issue:
* Decide whether curves should go in increasing or decreasing order of size or some other rule — but make it consistent.
* Note that Mbed TLS 2.2x allows some weak curves (<256 bits). These curves should only be used as a last resort.
* Whatever the order is, Montgomery curves should be in the appropriate place, not at the end because they happened to be added to the library last.
* Whatever the order is, in TLS, there should be a preset that in practice will lead to the same selection as before in most cases, to minimize disruption.
* Make sure the documentation is consistent and informative.

Points of discussion:
* Do we keep the order of `mbedtls_ecp_curve_list` as largest curve first?
* Do we keep the default order in TLS as largest curve first?
* Is it sensible to make the order: first all the strong curves, fastest first, then the weak curves, least weak first?

**Comment by daverodgman** [comment]
Dropping this from 2.28 LTS due to time constraints.

**Comment by gilles-peskine-arm** [comment]
Why was this closed?

If we don't have time before 2.28, we should do it for 2.29, or whatever becomes the last 2.x LTS.
