### ISSUE TITLE
Pre-release task: analyze and fix Coverity defects

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4728]
Analyze and if needed, fix defects reported by Coverity before the release.

**Comment by daverodgman** [comment]
Coverity reports 6 new issues:

4 uninitialised field in test_suite_rsa - false alarms
1 uninitialised field in test_suite_psa_crypto.function - false alarm
1 uninitialised field in programs/fuzz/fuzz_server.c - false alarm
