### ISSUE TITLE
DES/3DES CBC MAC Support

### ISSUE THREAD

**Issue by bmurray7** [ARMmbed/mbedtls#478]
My employer (Clover Network) is developing an embedded application for a retail point of sale system.

We need the following MAC algorithms.
- ISO 9797-1 CBC-MAC Algorithm 1 with 3DES and Padding Option 1
- ISO 9797-1 CBC-MAC Algorithm 3 with DES and Padding Option 1 (aka ANSI X9.19-19 Retail MAC)

Since these algorithms are not included in the existing codebase, we are working to add them to our local version.  We would like to share our contributions with the community and will be signing a contributor license agreement.

A few questions before we submit our pull request:
1. Would the community welcome a contribution that only supports a ciphers with a 64 bit block size?  The existing implementations of  CCM and CMAC (branch not merged in) only support 128 bit block ciphers. 
2. Would the community prefer that the new functionality be in a single large file or multiple separate files?  There is some overlap between the two algorithms, but our implementation has separate contexts and processing methods for each algorithm.  Separate files would mean smaller compiled code size when only using one algorithm and larger compiled code size when using both algorithms.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-762

**Comment by pjbakker** [comment]
Hi, Thanks for your question.

The functionality you suggest is something we see as things that should be part of libraries that use mbed TLS as their crypto core. So A library providing ISO 9797-1 compliant algorithms that uses the base building blocks from mbed TLS,

That way maintainability over time and the ability to receive up-stream updates from us is guaranteed.

That said. If there is a simple patch that allows you to re-use our 128-bit block CCM/CMAC for 64-bit as well, we might be open for adopting it.

**Comment by sbutcher-arm** [comment]
CMAC support has been merged in #603 using the work @bmurray7 has contributed. This issue can now be closed.
