### ISSUE TITLE
Why "mbedtls_ecp_point_read_binary" must check buf[0]==0x04 ???

### ISSUE THREAD

**Issue by SongPuNew** [ARMmbed/mbedtls#4785]
### Suggested enhancement
Why "mbedtls_ecp_point_read_binary" must check buf[0]==0x04 ???
        if( buf[0] != 0x04 )
            return( MBEDTLS_ERR_ECP_FEATURE_UNAVAILABLE );

Please tell me the reason.
Thanks

### Justification

Mbed TLS needs this because 
When user use local private key and peer public key to generate shared_key, need use "mbedtls_ecp_point_read_binary" to covert byte array to ECP point.
but the byte array haven't "first 0x04"
![image](https://user-images.githubusercontent.com/26473844/125887154-e1582b58-8f59-4dde-8db9-3c47aa5f625b.png)

**Comment by gilles-peskine-arm** [comment]
`mbedtls_ecp_point_binary` needs the point to be represented in a standard format. For Weierstrass curves, this is the format described in [SEC](https://www.secg.org/sec1-v2.pdf) (§2.3.3, §2.3.4) (also in X9.62 §4.3.6). There are several possible representations and the first byte indicates the representation: 0 for zero, 2 or 3 for a compressed representation, 4 for an uncompressed representation. Mbed TLS does not support the compressed representation, so the first byte.

If you have the point in a different format, you need to convert it to the ANSI/SEC uncompressed format.

We should document this. `mbedtls_ecp_point_write_binary` documents its output format, but the read functions don't document their input format.

**Comment by SongPuNew** [comment]
Hi gilles,

Got it.
Thanks for your reply.

Best regards
Song
