### ISSUE TITLE
Multithreading with memory_buffer_alloc_init() failed

### ISSUE THREAD

**Issue by AlamShariful** [ARMmbed/mbedtls#4788]
### Summary
[stackMemory_multithread.zip](https://github.com/ARMmbed/mbedtls/files/6837249/stackMemory_multithread.zip)
I'm using a stack-based memory allocator. Code works with a single thread. Executing the code with multi-thread cause decryption failure.
  
### System information

Mbed TLS version (number or commit id):  1.3.9
Operating system and version: Linux 4.4.0-200-generic
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Steps to reproduce
Provide the complete source code including a Makefile.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because it's a support question. The correct place for that is the mailing list, [where it has already been asked](https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-July/000411.html).
