### ISSUE TITLE
Port oss-fuzz fuzzers to Mbed TLS 3.0

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4790]
The goal of this task is to switch the oss-fuzz fuzzers to Mbed TLS 3.0, reverting https://github.com/google/oss-fuzz/pull/5636.

Goal of this task:
* [x] Make fields public or add accessor functions where fuzzer code needs to access fields that have become private. → https://github.com/ARMmbed/mbedtls/pull/4842
* [x] Adapt the fuzzer code as necessary to cope with removed features. → nothing to do
* [x] Submit and merge any necessary patches to the individual fuzzers. → nothing to do
* [x] Submit and merge a patch to oss-fuzz.

I have done a preliminary investigation and if I haven't missed anything, the only necessary change is to make some `mbedtls_ecp_curve_info` fields accessible to ecfuzzer, with no changes needed to any of the fuzzer projects.

This should be done at the latest before 2.2x becomes LTS, since the fuzzers should run on the latest code with all the features.

**Comment by daverodgman** [comment]
3/4 projects on OSS-fuzz have been updated; only cryptofuzz remains. There is an open PR for this:

https://github.com/google/oss-fuzz/pull/6992 but this does depend on crypto-fuzz making some updates first.

**Comment by daverodgman** [comment]
crypto-fuzz is now updated, so oss-fuzz is fully fuzzing against the development branch. I think we can close this now.

**Comment by paul-elliott-arm** [comment]
Closing this as it appears to be done.
