### ISSUE TITLE
Files missing in v3.0.0

### ISSUE THREAD

**Issue by Aethedor** [ARMmbed/mbedtls#4796]
The files library/error.c and library/version_features.c are missing in the 3.0.0 release.

**Comment by gilles-peskine-arm** [comment]
Both files are present in the [release zip](https://github.com/ARMmbed/mbedtls/archive/refs/tags/v3.0.0.zip), the [release tgz](https://github.com/ARMmbed/mbedtls/archive/refs/tags/v3.0.0.tar.gz) and [on the release tag](https://github.com/ARMmbed/mbedtls/tree/v3.0.0/library). Is there some place that is the 3.0.0 release where the files are missing?

The files are not present in the [development tree](https://github.com/ARMmbed/mbedtls/tree/development/library). This is deliberate: [they are generated from other files](https://github.com/ARMmbed/mbedtls/blob/development/README.md#user-content-generated-source-files-in-the-development-branch). The files are generated automatically if you run `make`, but if you use other build systems such as CMake, you need to run `tests/scripts/check-generated-files.sh -u` or `scripts\make_generated_files.bat` first. ([PR pending for CMake](https://github.com/ARMmbed/mbedtls/pull/4514))

**Comment by Aethedor** [comment]
A bit confusing, but ok. I will extract them from the zip file. Thanks!

**Comment by gilles-peskine-arm** [comment]
If the files are not in what you're using then you probably shouldn't extract them from the zip file. How are you obtaining Mbed TLS exactly?

If you're using a zip/tarball then you should extract the files like the others.

If you're checking out from the release tag (or any tag on the `master` branch), the files are already present.

If you're checking out from the `development` branch, the files need to be generated from the exact revision that you checked out. Using the files from another revision will not work (your program may or may not compile, but even if it does it might break in unpredictable ways).

**Comment by Aethedor** [comment]
Ok, got it. Will extract from the release tag. Thanks!
