### ISSUE TITLE
Remove duplicated extension parsers/writers between TLS 1.2 and TLS 1.3

### ISSUE THREAD

**Issue by hanno-arm** [ARMmbed/mbedtls#4843]
Some extensions in `ClientHello` and `ServerHello` are the same between TLS 1.2 and TLS 1.3, and we should aim for code reuse. Short-term, this is for maintainability. Mid-term, runtime-negotiation of 1.2 vs. 1.3 likely demands a unified parser/writer for `ClientHello` and `ServerHello`, since at this stage the implementations don't know which version is going to be picked.

This is on the edge between TLS 1.3 MVP and post-MVP -- strictly speaking, we can leave with the duplication, but it's undesirable.

**Comment by ronald-cron-arm** [comment]
#5351 was the first PR. At least #5355 remaining.
