### ISSUE TITLE
Make the 2.28 LTS release

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4867]
Release Mbed TLS 2.28 LTS. Need to ensure alignment with 3.0 features (ie may also need a 3.0.1 release to ensure feature parity).

**Comment by Sir-Branch** [comment]
Hi Dave,

Wanted to double check to see if the 2.28 release is a LTS version as I could not find that in the release notes.
I know the 2.28 release is very recent and it's the holiday season, so apologies in advance if this has not been announced yet. 

Thanks,
Ramiro

**Comment by gilles-peskine-arm** [comment]
@Sir-Branch Yes, 2.28 is a long-time support version. We did state it in the [release announcement](https://lists.trustedfirmware.org/pipermail/mbed-tls-announce/2021-December/000022.html). I'll edit the release description to add this information, good idea.
