### ISSUE TITLE
Basic constraints extension fix in x509 code was not ported to 2.16 as believed.

### ISSUE THREAD

**Issue by aj-mcl** [ARMmbed/mbedtls#4870]
The changelog for 2.16.10 includes this item:

> This change makes 'mbedtls_x509write_crt_set_basic_constraints' consistent with RFC 5280 4.2.1.9 which says: "Conforming CAs MUST include this extension in all CA certificates that contain public keys used to validate digital signatures on certificates and MUST mark the extension as critical in such certificates." Previous to this change, the extension was always marked as non-critical. This was fixed by #4044.

However, 4044 (https://github.com/ARMmbed/mbedtls/pull/4044) is still marked as open.

Downloading 2.16.10 and 2.16.11, I've examined x509write_crt.c, and the expected code change has not been made. It is also not shown in https://github.com/ARMmbed/mbedtls/compare/mbedtls-2.16.9...mbedtls-2.16.10 - implying that this change did not receive final approval and was not merged, but is still listed in 2.16.10's changelog.

The relevant section of the RFC is https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.9

**Comment by yanesca** [comment]
Indeed, thank you for catching this!

**Comment by yanesca** [comment]
Task is complete when
- [ ] The missing PR (#4044) is merged
- [ ] A new PR is raised and merged that adds a ChangeLog entry explaining that this fix was added now and wasn't added in 2.16.10 as claimed
