### ISSUE TITLE
error if MBEDTLS_PLATFORM_C disabled

### ISSUE THREAD

**Issue by AlessandroBudroni** [ARMmbed/mbedtls#490]
What I've done:
- Download the developer branch on MacBook PRO, OS X El Capitan
- in config.h comment MBEDTLS_PLATFORM_C
- compile the library using cmake

During the compilation (make) I get the error in ssl.h

```
unknown type name 'mbedtls_time_t'
mbedtls_time_t start;       /*!< starting time      */
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-783
