### ISSUE TITLE
Retirement of on-target testing from Mbed TLS 2.28 and 3.1

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4912]
On-target testing (with greentea, using `target_test.function` and possibly `mbedtls_test.py`) is practically unmaintained. Should we commit to maintaining it, or should we remove it altogether?

## Technical information

Mbed TLS unit tests can be built in one of two modes: “hosted” or “on-target”. Concretely, this means running `generate_test_code.py` with either `host_test.function` or `target_test.function` as the “platform code file”. With GNU makefiles, you can build on-target tests with `make -C tests embedded_test_suite_xxx`.

On-target tests use the [greentea](https://github.com/ARMmbed/greentea) framework, which is mainly intended for Mbed OS (I don't know if it's used anywhere else). Building them requires the greentea client C library. Mbed TLS also ships a helper script to run the tests: `mbedtls_test.py`. Even with this helper script, building and running the tests on an Mbed OS target requires quite a few manual steps.

## Current support status

As far as I can tell, there is no public documentation of on-target testing anywhere (not in the Mbed TLS tree, not on the old website, not on the TF wiki, not on mbedtls-docs). (We do have an internal wiki page in Arm.) So the support status is unclear: is it undocumented and therefore unsupported, or is there an implicit commitment that what currently works will keep working?

The Mbed TLS team does not maintain any continuous integration that even tries to build the on-target tests, let alone run them. We also don't often run them manually. They probably still work because there haven't been many changes to the test framework since a time when we did run them manually from time to time.

## Possible scenarios

Here I describe a few plausible scenarios. Other scenarios are definitely possible, proposals welcome.

### Complete retirement

Retire `target_test.function` altogether, and consider ourselves free to break the distinction between `main_test.function` and `host_test.function`.

Advantage: we can finally do improvements to the unit test frameworks without being afraid of breaking on-target testing.

Downside: anyone relying on `target_test.function`, or on the ability to plug in a replacement, will no longer be able to run the unit tests on their target platform.

In terms of cost-benefit for the Mbed TLS team alone, this is the best scenario by far.

### Current situation

Try not to break `target_test.function` and `mbedtls_test.py`. Don't actively maintain them, but accept patches.

Advantage: no direct maintenance cost for the Mbed TLS team.

Downside: “try not to break” is a significant burden. It's held us back from doing some long-awaited improvements to the unit test framework. (Most of these enhancement requests have not been posted on GitHub because we know that they're difficult to do in the current situation).

Advantage: users relying on on-target testing can keep using it, they just have to participate in maintaining it.

### Replace on-target testing by an API

Transfer the maintenance of greentea-specific code (`target_test.function`, `mbedtls_test.py`) to the Mbed OS maintainers. But define a documented, tested interface between `target_test.function` and the rest of the test framework.

Advantage: it continues to be possible to use greentea to run Mbed TLS unit tests. Other platforms can write their own automation for on-target testing.

Advantage: the Mbed TLS test framework can evolve. It just needs to respect the API.

Downside: the API needs to be documented, and we need to have some testing for it. The tests can run on any platform since they only need to validate that the right data is being passed.

### Start maintaining on-target testing

Have CI for on-target testing.

Advantage: it's good for users who want it, obviously. And it means we can do improvements to the unit test framework, we just have one more configuration in which the new code needs to work.

Downside: this is a significant maintenance burden, especially considering that we currently don't do any Mbed OS testing at all. That's a huge upfront cost.

**Comment by danh-arm** [comment]
I'm sympathetic to the cost of maintaining this, especially while there's no active CI for it within the project. At the moment, the lack of on-target testing is not a major concern since there are few architecture/platform specific optimizations in the project. However, we'd expect such optimizations to be added in the (hopefully not too distant) future, and having working on-target testing would be an essential part of that. I wonder what would be least effort: Completely retiring this now and adding a new API in the future, or retaining some potentially useful parts of the existing framework (in unsupported form) and reworking/rebuilding this in future? I trust you maintainers to make the right choice here.

I personally wouldn't worry too much about retaining the GreenTea / Mbed OS specifics but others may want to comment about that.

**Comment by gilles-peskine-arm** [comment]
Based on feedback from the Mbed OS team (they aren't Mbed TLS's unit tests and have no plan to do so), and on the lack of feedback otherwise (no replies to the mailing list posts in [Apr 2020](https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000036.html) and [Sep 2021](https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-September/000436.html)), the Mbed TLS team has concluded that there is no interest in the current facilities for running unit tests on platforms without a filesystem (either with Greentea or with a custom third-party hook into the undocumented, interface that `target_test.function` and `host_test.function` implement).

As a consequence, **we will remove the current “on-target testing” functionality** from Mbed TLS 2.28 and 3.1.

We will keep the general structure of the test framework, with test data stored separately (so you don't have to upload all the bulky test data to a small platform at once) and filesystem access separated from the rest (so that it won't be hard to bring back a way to pass test data other than reading from a file). So it'll be possible to add better ways to do on-target testing later, but when we do that, it'll be with a documented and tested interface.
