### ISSUE TITLE
mbedtls_x509_crt_parse_path() -  the array char entry_name[255] is too small

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#492]
In the function `mbedtls_x509_crt_parse_path()` in file `x509_crt.c`, the array char entry_name[255] is too small. It is intended to hold path/filename where filename is entry->d_name which is an array of 256 chars.

When the size of (path/filename) exceeds the size of entry_name then calling stat() fails and the function returns MBEDTLS_ERR_X509_FILE_IO_ERROR.

The size of entry_name[] must be increased so that long filenames are supported.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-784

**Comment by sbutcher-arm** [comment]
Fixed in #592 which has now been merged, so closing this issue as it has now been resolved.
