### ISSUE TITLE
size_t in gcm.c 

### ISSUE THREAD

**Issue by maniteja007** [ARMmbed/mbedtls#494]
Hi Mbed,

As per my understanding sizeof "size_t" is 4 bytes in ARM_GNU compiler,

size_t iv_len
size_t add_len  
need to be 8 bytes as per GCM

If you refer below code  from GCM.C  and in the line from the function mbedtls_gcm_starts
    if( ( (uint64_t) iv_len  ) >> 61 != 0 ||  ( (uint64_t) add_len ) >> 61 != 0 )

which leads to CONSTANT EXPRESSION RESULT i mean (0) always, which leads to portable issues;

PLEASE correct me if im wrong

 **mbedtls_gcm_starts( mbedtls_gcm_context *ctx,
                int mode,
                const unsigned char *iv,
                size_t iv_len,
                const unsigned char *add,
                size_t add_len )
{
    /* IV and AD are limited to 2^64 bits, so 2^61 bytes */
    if( ( (uint64_t) iv_len  ) >> 61 != 0 ||
        ( (uint64_t) add_len ) >> 61 != 0 )
    {
        return( MBEDTLS_ERR_GCM_BAD_INPUT );
    }

}**

Thanks & Regards,
Teja.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-803

**Comment by maniteja007** [comment]
Any update?

**Comment by pjbakker** [comment]
The binary-width of `size_t` is a platform dependent value (for a reason). `size_t` should be capable of holding the largest size that an architecture can provide (by `malloc()`). So if in a platform `size_t` is **only** 4 bytes, it means that a buffer can never be longer anyway.

So on a platform with a 4-byte `size_t`, GCM can never write to a larger buffer. That does not mean that the implementation cannot handle 2^61 bytes on platforms that DO support larger buffers.

So in this case, you are right that the function can support larger platforms, but in your specific situation your platform cannot, and thus has 'redundant' lines that will always be positive in your situation.
