### ISSUE TITLE
Clang 12 bignum issue also affects aarch64

### ISSUE THREAD

**Issue by sfan5** [ARMmbed/mbedtls#4962]
Issue #4943 exists as a reminder but it doesn't look like you're aware of concrete bugs, so I'm opening this issue.
If you are aware of this bug already feel free to close this one.

This is functionally identical to #4917.

Just like the other issue it goes away with gcc *or* `-O1` *or* by downgrading to mbedTLS 2.26.0.

### Steps to reproduce

```bash
git clone https://github.com/ARMmbed/mbedtls -b development
cd mbedtls
make -j4 programs || exit 1

echo "Running on $(uname -rms)"
echo "compiler: $($CC --version | head -1)"
echo "commit: $(git rev-parse HEAD)"

./programs/ssl/ssl_server &>/dev/null &
sleep 1
./programs/ssl/ssl_client1
killall ssl_server
```

### Expected behavior

Running on Linux 5.14.1-0-ARCH aarch64
compiler: gcc (GCC) 10.2.0
commit: 304689e4c413ada1991ef5e0199b022bb1123441
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake... ok
  . Verifying peer X.509 certificate... ok
[...]
</pre>

### Actual behavior

Running on Linux 5.14.1-0-ARCH aarch64
compiler: clang version 12.0.1
commit: 304689e4c413ada1991ef5e0199b022bb1123441
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...ssl_tls.c:2121: x509_verify_cert() returned -9984 (-0x2700)
ssl_msg.c:4384: mbedtls_ssl_fetch_input() returned -29312 (-0x7280)
ssl_msg.c:3735: ssl_get_next_record() returned -29312 (-0x7280)
ssl_cli.c:2932: mbedtls_ssl_read_record() returned -29312 (-0x7280)
 failed
  ! mbedtls_ssl_handshake returned -0x7280

Last error was: -29312 - SSL - The connection indicated an EOF
</pre>

**Comment by davidhorstmann-arm** [comment]
Thanks for letting us know! We were unaware of this specific bug.
