### ISSUE TITLE
Extend PSA operation setup tests to always cover both one-shot and multipart

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4964]
In `test_suite_psa_crypto`, for historical reasons, tests of operation setup (`hash_setup`, `mac_key_policy`, `cipher_key_policy`, `aead_key_policy`) sometimes use one-shot operations and sometimes multi-part operations. Preferably, when both are possible, they should all test both, since we can't be sure that the checks are in the proper place to be done in all cases.

**Comment by akbhuker** [comment]
hey, can I have this issue?
I'm quite new to this so I might need some guidance

**Comment by gilles-peskine-arm** [comment]
@akbhuker Thanks for volunteering! Writing unit tests can be a little boring sometimes, but it's a very good way to get familiar with the project. It would be best to wait until https://github.com/ARMmbed/mbedtls/pull/4338 is merged, though. This is likely to take a couple of weeks.

In a bit more detail, here's the goal of the task. In [`test_suite_psa_crypto.function`](https://github.com/ARMmbed/mbedtls/blob/mbedtls-3.0.0/tests/suites/test_suite_psa_crypto.function), there are several test functions that try to start a cryptographic operation with various parameters and check that the attempt either succeeds or fails with the expected error code, depending on the validity of the parameters. These functions are `hash_setup`, `mac_key_policy`, `cipher_key_policy`, `aead_key_policy`, and possibly others that I haven't listed.

Hash, MAC, cipher and (with #4338) AEAD operations can either be [single-part](https://armmbed.github.io/mbed-crypto/html/overview/functionality.html#single-part-functions) or [multi-part](https://armmbed.github.io/mbed-crypto/html/overview/functionality.html#multi-part-operations). For historical reasons, some of the functions only test the single-part interface, and some only test the multi-part interface. We'd like to be sure that both interfaces test the same conditions, so we want the unit tests to cover both interfaces.
