### ISSUE TITLE
Download website disallows `HEAD` requests

### ISSUE THREAD

**Issue by staticfloat** [ARMmbed/mbedtls#497]
Hello there, I run a [caching server](https://cache.julialang.org) for the [Julia Language project](https://julialang.org), and we cache requests to your site in an effort to provide a combination of an extra layer of reliability, greater permanence of older versions, and decreased load to source servers, when downloading external dependencies.  mbedtls is one such dependency, and in order to ensure that our caching server is consistent with your server, we dispatch `HEAD` requests for the files in question to check headers such as the `ETag` and `Last-Modified` headers.  I have noticed that recently, your site does not allow `HEAD` requests to your downloads:

```
$  curl --head https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz
HTTP/1.1 404 Not Found
Date: Thu, 02 Jun 2016 18:26:22 GMT
...
```

Is it possible for you to enable `HEAD` requests again?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-804

**Comment by pjbakker** [comment]
Should be fixed now.

**Comment by staticfloat** [comment]
Great!  Thanks!
