### ISSUE TITLE
Add missing getters, setters or remove the private modifier from some structs

### ISSUE THREAD

**Issue by sevilS** [ARMmbed/mbedtls#4994]
### Suggested enhancement
We need access to some of the fields that are now private since version 3.0.0, we saw there is already a PR opened which will cover all our use cases but it seems it still not available https://github.com/ARMmbed/mbedtls/pull/4842:
- mbedtls_x509_time:
year
month
day
hour
min
sec

- mbedtls_x509_crt
valid_to
valid_from
raw

- mbedtls_pk_context
pk_ctx

- mbedtls_ecp_keypair
d

- mbedtls_net_context
fd

- mbedtls_asn1_buf:
len
buf
tag

### Justification

Mbed TLS needs this because this is required for us in order to do a correct management of our internal logic:

- mbedtls_x509_time fields: used in order to create an struct tm in order to compare our backend date with this actual time

- mbedtls_x509_crt:
    - valid_to and valid_from are used in order to know if a certificate has expired compared to the time of our backend which is in format tm struct
    - raw: used for calling mbedtls_pem_write_buffer

- mbedtls_pk_context: We have to configure a pk_ctx in order to be able to implement ecdsa_alt fucntionality 

- mbedtls_ecp_keypair: Same, for ecdsa_alt fucntionality we need to provide the key information inside d field

- mbedtls_net_context: Used in order to have a tracking of the opened sockets

**Comment by davidhorstmann-arm** [comment]
#4842 has just been merged, so closing this.
