### ISSUE TITLE
function mbedtls_mpi_gcd get wrong result when one of the parameters is 0

### ISSUE THREAD

**Issue by qingqing202110** [ARMmbed/mbedtls#5008]
### Summary
[Problem Description] The gcd of 0 and any number should be 0,not other

### System information
(1)branch：origin/mbedtls-2.16
commit：ccfc2bff6fbcf3c3650f4cf8af020c3015663039
(2)branch：origin/development
commit：023aa11760186e32eb79f4465395676eaac703cc

### behavior
	 parameter1         parameter2         Actual result      Expected result
 (1)    0x998866             0                         0x998866            0
 (2)    0                          0x06                    0x06                    0

### Steps to reproduce （test script）
    //B=0
    TEST_EQ(mbedtls_mpi_lset(&A,0x998866),0,ret);
    TEST_EQ(mbedtls_mpi_lset(&B,0),0,ret);
    TEST_EQ(mbedtls_mpi_gcd(&X,&A,&B),0,ret);
    mpi_print(&X);
    //A=0
    TEST_EQ(mbedtls_mpi_lset(&A,0),0,ret);
    TEST_EQ(mbedtls_mpi_lset(&B,6),0,ret);
    TEST_EQ(mbedtls_mpi_gcd(&X,&A,&B),0,ret);
    mpi_print(&X);

**Comment by gilles-peskine-arm** [comment]
> The gcd of 0 and any number should be 0,not other

Er, no? The GCD of any number and 0 is the other number. gcd(x, 0) has to divide x, and 0 doesn't divide x (except when x = 0).
