### ISSUE TITLE
Add public getter APIs for `mbedtls_ecp_curve_info`

### ISSUE THREAD

**Issue by gabor-mezei-arm** [ARMmbed/mbedtls#5018]
As part of #4683, as a result of reviewing the programs there are uses of `MBEDTLS_PRIVATE` fields of the `mbedtls_ecp_curve_info` structure. To avoid the access of the private fields create and use new public getter APIs for the fields of the `mbedtls_ecp_curve_info` structure.

Accessed flelds:
- `name`
- `grp_id`

Affected files:
- `pkey/ecdsa.c`
- `pkey/gen_key.c`
- `ssl/ssl_server2.c`

**Comment by gilles-peskine-arm** [comment]
https://github.com/ARMmbed/mbedtls/pull/4842 made all the fields of `mbedtls_ecp_curve_info` public.
