### ISSUE TITLE
Add public getter APIs for `mbedtls_x509_csr`

### ISSUE THREAD

**Issue by gabor-mezei-arm** [ARMmbed/mbedtls#5020]
As part of #4683, as a result of reviewing the programs there are uses of `MBEDTLS_PRIVATE` fields of the `mbedtls_x509_csr` structure. To avoid the access of the private fields create and use new public getter APIs for the fields of the `mbedtls_x509_csr` structure.

Accessed fields:
- `subject`
- `pk`
- `version`

Affected files:
- `x509/cert_write.c`

**Comment by gilles-peskine-arm** [comment]
https://github.com/ARMmbed/mbedtls/pull/4842 made those fields public.
