### ISSUE TITLE
Make the fileds of `mbedtls_net_context` public

### ISSUE THREAD

**Issue by gabor-mezei-arm** [ARMmbed/mbedtls#5021]
As part of #4683, as a result of reviewing the programs there are uses of `MBEDTLS_PRIVATE` fields of the `mbedtls_net_context` structure. To avoid the access of the private fields make the fields of `mbedtls_net_context` public.

Accessed fields:
- `fd`

Affected files:
- `ssl/mini_client.c`

**Comment by gilles-peskine-arm** [comment]
https://github.com/ARMmbed/mbedtls/pull/4842 made this field public (with a documented stipulation that this is only guaranteed on Unix/POSIX platforms).
