### ISSUE TITLE
Comprehensive testing of TLS 1.3 MVP against OpenSSL and GnuTLS TLS 1.3 servers

### ISSUE THREAD

**Issue by ronald-cron-arm** [ARMmbed/mbedtls#5030]
### Suggested enhancement
- Interoperability testing with OpenSSL and GnuTLS. Test with all ecdhe groups (x448 included), cipher suites and signature algorithms supported by OpenSSL/GnuTLS server. Tests to be added in ssl-opt.sh (see ssl-opt.sh in the prototype and in PR https://github.com/hannestschofenig/mbedtls/pull/375 where there is a fair amount of such tests). If key exchange does not work with x448 (not in the scope of the MVP), just remove the support for it and create a ticket to investigate this.
   
- Negative testing against OpenSSL/GnuTLS servers with which the handshake fails due to incompatibility with the capabilities of the MVP: TLS 1.2 or 1.1 server, server sending an HelloRetryRequest message in response to the MVP ClientHello, server sending a CertificateRequest message ... Tests to be added in ssl-opt.sh

### Justification
As agreed in tls13-experimental.md.

**Comment by yuhaoth** [comment]
There are some open PRs.

**Comment by ronald-cron-arm** [comment]
Still on-going.
