### ISSUE TITLE
`scripts/generate_errors.pl` does not work with GREP_OPTIONS=--color=always

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#504]
Executing `scripts/generate_errors.pl`on OSX fails with the following text:

```
Error: Do not know how to handle:

```

(Note the missing module name it doesn't know how to handle.)

The issues seems to be a difference in how grep works on OSX. This probably also fails on FreeBSD et al.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-823

**Comment by andresag01** [comment]
I have been unable to reproduce the error on OS X. Could you please provide more information about your setup? For instance, Perl version, command line arguments to the script, mbedtls version, etc.

**Comment by RonEld** [comment]
Could https://github.com/ARMmbed/mbedtls/pull/1056 fix this issue?

**Comment by sbutcher-arm** [comment]
Hi @RonEld. #1056 doesn't fix the problem (whatever it is).

To answer @andresag01's question -

Perl version - `This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level`
Script is executed without parameters. e.g. `./scripts/generate_errors.pl`
Last reproduced on the Mbed TLS version on the current head for `development`.

What the problem actually appears to be, is an issue with how my `grep` is configured. Studying this I found that my environment was set to: `GREP_OPTIONS= --color=always`. If I set `GREP_OPTIONS=
 `, the issue goes away.

I guess our script doesn't like the colour escape codes `grep` is outputting.

So is that my fault for forcing colour into grep, or should our script accommodate it?

**Comment by sbutcher-arm** [comment]
Changing the call to `grep` at [line 49](https://github.com/ARMmbed/mbedtls/blob/development/scripts/generate_errors.pl#L49) to pass `grep --color=never` fixes the problem, but the option of `--color` isn't POSIX. If it works on BSD and GNU systems, is it good enough?

**Comment by gilles-peskine-arm** [comment]
@sbutcher-arm If you set `GREP_OPTIONS='--color=always'`, you'll run into similar issues with a lot of scripts. This is such a common issue that GNU has removed support for `GREP_OPTIONS`, and if you want color with GNU grep you should use `alias grep='grep --color=always'` (which also works with BSD), which doesn't affect grep when it's launched by a script. So this is a user error.

We could remove `GREP_OPTIONS` from the environment in `generate_errors.pl` anyway. That wouldn't cause any harm (beyond one more line in our code).

**Comment by andresag01** [comment]
@sbutcher-arm, @gilles-peskine-arm: I am not an expert, but if we use the grep command from perl the color sequences will not be generated by grep because it notices the output is for the script. I think the following change should work:
```
diff --git a/scripts/generate_errors.pl b/scripts/generate_errors.pl
index cfcf07c..040a488 100755
--- a/scripts/generate_errors.pl
+++ b/scripts/generate_errors.pl
@@ -46,7 +46,14 @@ close(FORMAT_FILE);
 
 $/ = $line_separator;
 
-open(GREP, "grep \"define MBEDTLS_ERR_\" $include_dir/* |") || die("Failure when calling grep: $!");
+my @files = <$include_dir/*>;
+my @matches;
+foreach my $file (@files) {
+    open(FILE, "$file");
+    my @grep_res = grep(/define MBEDTLS_ERR_/, <FILE>);
+    push(@matches, @grep_res);
+    close FILE;
+}
 
 my $ll_old_define = "";
 my $hl_old_define = "";
@@ -58,7 +65,8 @@ my $headers = "";
 
 my %error_codes_seen;
 
-while (my $line = <GREP>)
+
+foreach my $line (@matches)
 {
     next if ($line =~ /compat-1.2.h/);
     my ($error_name, $error_code) = $line =~ /(MBEDTLS_ERR_\w+)\s+\-(0x\w+)/;

```

**Comment by gilles-peskine-arm** [comment]
@andresag01 A quick fix would be `undef $ENV{GREP_OPTIONS}`, but your fix has the advantage of removing the dependency on grep, which may make things easier for mbedtls developers who use Windows. Since you've already done the work, please submit that as a PR.

**Comment by andresag01** [comment]
@gilles-peskine-arm: Created the PR https://github.com/ARMmbed/mbedtls/pull/1134. The issue also happens in earlier versions of the library, do you think we should backport it even though is just a really minor tools fix?

**Comment by sbutcher-arm** [comment]
@andresag01 - This is not an important fix and a bit of a distraction. I don't think a backport is important, so please leave it. PR #1134 is enough.
