### ISSUE TITLE
Create getter functions for ECP internals and X.509 public key context

### ISSUE THREAD

**Issue by GlitchedPolygons** [ARMmbed/mbedtls#5081]
### Suggested enhancement

Getter functions (as suggested to be posted here according to [the official migration guide to v3.0.0](https://github.com/ARMmbed/mbedtls/blob/8e5020deade1ce688fefe7892d963137f69a62b2/docs/3.0-migration-guide.md#most-structure-fields-are-now-private)) for the following MbedTLS x509/ecp internals:

* `mbedtls_x509_crt::pk`
* `mbedtls_ecp_keypair::grp`
* `mbedtls_ecp_keypair::Q`
* `mbedtls_ecp_keypair::d`

### Justification

MbedTLS needs this because C-implementations of the [JWT](https://jwt.io) ES256, ES256K, ES384 and ES512 depend on the signature protocol as defined by the official [JWT RFC 7518 document (ECDSA chapter)](https://datatracker.ietf.org/doc/html/rfc7518#page-9). 

Since MbedTLS v3, most fields of the library's data structures are private. That's... great! 
But some usages out there need deeper access to these structs, ECP internals, etc...

In my implementation of JWT ([l8w8jwt](https://github.com/GlitchedPolygons/l8w8jwt)), I upgraded to the latest version of MbedTLS. 
For signing and verifying RFC standard-compliant tokens using one of the above mentioned ECDSA variants, I now had to resort to the nasty `MBEDTLS_PRIVATE()` macro to get access to the ECP internals needed for handling the token signatures (for me, this is kind of a regression since this wasn't necessary before: what was fully legit earlier, now feels like an illegal usage of the library).
Same applies to the public key context of an X.509 certificate (since those can be used for verifying JWTs as well).

**Check it out:**

The following are examples of where I had to now resort to the `MBEDTLS_PRIVATE()` macro to retain functionality (not the only ones, but the main ones). Search the [l8w8jwt repo](https://github.com/GlitchedPolygons/l8w8jwt) for "MBEDTLS_PRIVATE" to find them all.

* `mbedtls_x509_crt::pk`
* * https://github.com/GlitchedPolygons/l8w8jwt/blob/491dca27166c2453ea6397c2c8909df9b5295ce1/src/decode.c#L370
* `mbedtls_ecp_keypair::grp`
* * https://github.com/GlitchedPolygons/l8w8jwt/blob/491dca27166c2453ea6397c2c8909df9b5295ce1/src/decode.c#L518
* `mbedtls_ecp_keypair::Q`
* * https://github.com/GlitchedPolygons/l8w8jwt/blob/491dca27166c2453ea6397c2c8909df9b5295ce1/src/decode.c#L518
* `mbedtls_ecp_keypair::d`
* * https://github.com/GlitchedPolygons/l8w8jwt/blob/491dca27166c2453ea6397c2c8909df9b5295ce1/src/encode.c#L486

Cheers, and thanks for developing this awesome library and being so awesome with the community! :)

**Comment by gilles-peskine-arm** [comment]
Thanks for sharing concrete use cases!

`mbedtls_x509_crt::pk` will be public in Mbed TLS 3.1 (#4842).

The fields of `mbedtls_ecp_keypair` have been requested for other reasons, we're tracking this in https://github.com/ARMmbed/mbedtls/issues/4838, so I'm closing this issue because the remaining part is a duplicate.
