### ISSUE TITLE
Detect PSA leaks in SSL test programs

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5099]
The two test SSL programs `ssl_server2.c` and `ssl_client2.c` use some PSA features if `MBEDTLS_USE_PSA_CRYPTO` is enabled. Depending on command-line options, they may allocate some PSA resources, need to clean them up properly (for example calling `psa_destroy_key()` on any key created).

We want to make sure that all resources are cleared at the end as expected. This is not important for the program itself (it's just a test program and the resources are going to be freed when it exits anyway), but it's useful to make sure that there aren't any leaks in the library either.

Currently, in the test suites, a call to `PSA_DONE()` at the end of the test function is used for that purpose. However that doesn't work for the test programs, as it relies on the test suites framework to report any failure. Instead, we want to call `mbedtls_test_helper_is_psa_leaking()` directly and handle any errors ourselves (quite similarly to the current call to `test_hooks_failure_detected()`.

However, there's an additional complication here: `mbedtls_test_helper_is_psa_leaking()` is declared in `tests/include/test/psa_crypto_helpers.h` which `#include`s `library/psa_crypto_slot_management.h` and currently `library` is not on the include path when building programs, and we'd like to keep it that way in order to avoid test/example programs accidentally depending on library internals.

One solution would be to split In `psa_crypto_helpers.h` in two parts: one with imports for the sake of test code (using the header) (which ideally shouldn't include any `library/*.h`) and imports for the sake of test helper code (which does include some `library/*.h` for the sake of somewhat-invasive tests — such as checking if the PSA keystore is empty.)

**Comment by mprse** [comment]
Bot PRs are merged. Closing this one.
