### ISSUE TITLE
Why is the parameter  'a' of 256-bit Elliptic Curve omitted?

### ISSUE THREAD

**Issue by mrpre** [ARMmbed/mbedtls#510]
I find the definition of secp256r1 in ecp_curves.c, it contains secp256r1_p, secp256r1_b, secp256r1_gx,secp256r1_gy,secp256r1_n.
But i also find the definition of secp256r1 in 'http://www.secg.org/', it contains the parameter a:

a = FFFFFFFF 00000001 00000000 00000000 00000000 FFFFFFFF FFFFFFFF
FFFFFFFC

I want to know why we can omit a and it works correctly.

**Comment by zeil** [comment]
I recommend you to read about an invariant of an elliptic curve: http://mathworld.wolfram.com/j-Invariant.html
This constant value allows you derive a and b parameters from each other.

**Comment by mrpre** [comment]
Thanks a lot . It has been confused me for long.
