### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Dragris** [ARMmbed/mbedtls#5138]
### Summary
Got a crash on app close after doing cipher_innit and cipher_free.

### System information

Mbed TLS version (number or commit id):  2.27
Operating system and version: MacOS Big Sur 11.6 (20G165)
Configuration (if not default, please attach `mbedtls_config.h`): We've added the following
```
#define MBEDTLS_ECDSA_SIGN_ALT
#undef MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_CMAC_C
```
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  Xcode 13.0 default compiler.
Additional environment information: 

### Expected behavior

We expect the app to close correctly.

### Actual behavior

App gives sigterm error at the end of execution.

### Steps to reproduce

When trying to add the following lines of code we got a crash error on Xcode 13.0 while simulating an iPhone 8 (iOS 15.0)

```    
    mbedtls_cipher_context_t *mCtx;
    mbedtls_cipher_init(mCtx);
    mbedtls_cipher_free(mCtx);
```

We found that we could solve the problem by allocating some memory before:
```
    mbedtls_cipher_context_t *mCtx;
    mCtx = malloc(sizeof(mbedtls_cipher_context_t));
    mbedtls_cipher_init(mCtx);
    mbedtls_cipher_free(mCtx);
```

**Comment by paul-elliott-arm** [comment]
Hi all,
`mbedtls_cipher_init()` expects the application to allocate and look after the lifetime of the `cipher_context_t` - its the information for your cipher operation, and requires to be passed into all `mbedtls_cipher_*` operations. It would not necessarily be practical for the library to have ownership of it.

Furthermore, `mbedtls_cipher_free()` does not free the `mbedtls_cipher_context_t` structure itself, it frees the items within it that may have been allocated by cipher functions - It is down to the application to free the structure, as per the docs.

Any further questions, please feel free to join our mailing list at https://www.trustedfirmware.org/projects/mbed-tls/
