### ISSUE TITLE
Aborted key derivation returns PSA_ERROR_NOT_PERMITTED instead of PSA_ERROR_BAD_STATE

### ISSUE THREAD

**Issue by bensze01** [ARMmbed/mbedtls#5143]
[`psa_key_derivation_output_key()`](https://armmbed.github.io/mbed-crypto/html/api/ops/kdf.html#c.psa_key_derivation_output_key) returns `PSA_ERROR_NOT_PERMITTED` instead of
`PSA_ERROR_BAD_STATE` when called after the operation was aborted.

This causes [a failure in `test_c021`](https://github.com/ARM-software/psa-arch-tests/blob/5620d85b4a8acc77133d9f4bd540edb4fc2f907c/api-tests/dev_apis/crypto/test_c021/test_c021.c#L178-L181) of the [PSA compliance test suite](https://github.com/ARM-software/psa-arch-tests).

**Comment by gilles-peskine-arm** [comment]
`psa_key_derivation_output_key` returns `NOT_PERMITTED` unless a key has already been passed as input. I agree that as long as no algorithm has been set, `BAD_STATE` would be a more appropriate error code. This would mean adding
```
if( operation->alg == PSA_ALG_NONE )
    return( PSA_ERROR_BAD_STATE );
```
before the `can_output_key` check.

If `psa_key_derivation_setup` has been called but no `SECRET` input has been passed yet, it's still unknown whether the operation will permit outputting a key. So arguably `BAD_STATE` would still be a better error code in that case. However, I don't think it's worth the added complexity to change this case.
