### ISSUE TITLE
psa_aead_encrypt/decrypt() erroneously returns PSA_ERROR_NOT_SUPPORTED when the nonce is invalid

### ISSUE THREAD

**Issue by bensze01** [ARMmbed/mbedtls#5144]
### Summary
`psa_aead_encrypt()` and `psa_aead_decrypt()` (by way of [`psa_aead_check_nonce_length()`](https://github.com/ARMmbed/mbedtls/blob/91fe315c69506c6ac9a1321058dfd9ed19859200/library/psa_crypto.c#L3626-L3663)) return `PSA_ERROR_NOT_SUPPORTED` instead of `PSA_ERROR_INVALID_ARGUMENT` when called with a supported AEAD algorithm and an invalid nonce (eg. `0`).

This causes a failure in [`test_c024`](https://github.com/ARM-software/psa-arch-tests/blob/5620d85b4a8acc77133d9f4bd540edb4fc2f907c/api-tests/dev_apis/crypto/test_c024/test_data.h#L231-L249) and [`test_c025`](https://github.com/ARM-software/psa-arch-tests/blob/master/api-tests/dev_apis/crypto/test_c025/test_data.h#L231-L249) of the [PSA Complaince test suite](https://github.com/ARM-software/psa-arch-tests).

**Comment by gilles-peskine-arm** [comment]
In this case, I think NOT_SUPPORTED is a valid error. Mbed TLS doesn't support all potential nonce sizes. We can change the error to accommodate compliance if it's not too difficult, but I don't think this is a bug in Mbed TLS.

**Comment by bensze01** [comment]
@gilles-peskine-arm  This *is* a regression / change of behavior from `development_2.x` though.
We used to return `PSA_ERROR_INVALID_ARGUMENT ` in this scenario.

**Comment by bensze01** [comment]
In fact, from what I can see, this behavior change happened after the release of Mbed TLS 3.0.

**Comment by gilles-peskine-arm** [comment]
It's a plausible consequence of adding support for multipart AEAD, which happened after 3.0.

It's a change of behavior, but only a marginal one, it isn't an incompatible change. When multiple error codes apply in a given situation, we don't guarantee that the particular choice of error code will remain the same over time.

**Comment by daverodgman** [comment]
I agree with @gilles-peskine-arm that this is within-spec behaviour, but it's probably preferable to stay consistent with 2.x behaviour and with the compliance suite - so we should make the change.
