### ISSUE TITLE
Support non-ascii encoding in certificate DN

### ISSUE THREAD

**Issue by stepanovsn** [ARMmbed/mbedtls#5148]
Function [mbedtls_x509_dn_gets](https://github.com/ARMmbed/mbedtls/blob/development/library/x509.c#:~:text=int-,mbedtls_x509_dn_gets,-\(%20char%20*buf%2C%20size_t) prints certificate dn in printable format, but it [replaces](https://github.com/ARMmbed/mbedtls/blob/development/library/x509.c#:~:text=if\(%20c%20%3C%2032,s%5Bi%5D%20%3D%20c%3B) some symbols with '?'. This breaks the name if it was in utf-8 format.
Is there a reason for such logic? Can it be changed somehow to make it possible to get utf-8 encoded strings correctly? Cases when people issue certificates with dn written in other languages are not rare so it would be good to have them supported.

**Comment by gabor-mezei-arm** [comment]
This issue is already reported in #3865. Closing due to duplication.
