### ISSUE TITLE
mbedtls_ssl_config_defaults preset

### ISSUE THREAD

**Issue by github-monoculture** [ARMmbed/mbedtls#516]
In release 2.2.1, the mbedtls_ssl_config_defaults() header says
\param preset a MBEDTLS_SSL_PRESET_XXX value
(currently unused).

but it is indeed used.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-836

**Comment by RonEld** [comment]
This issue does not exist on [`mbedtls-2.7`](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.7/include/mbedtls/ssl.h#L2614) which is our oldest LTS branch, therefore closing
