### ISSUE TITLE
TLS Cipher 1a: extend testing of tickets

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5181]
Session tickets can be protected using any AEAD construct according to [the documentation](https://github.com/ARMmbed/mbedtls/blob/bb41a88f2e012244ef266092f6e4bf0a321963d2/include/mbedtls/ssl_ticket.h#L91) but we only ever test the default value. Since we're going to change that part, it needs to be tested.

- [ ] In `ssl_server2.c`, add an option `ticket_aead` alongside the existing `tickets` and `ticket_timeout` options, accepting a string and controlling the value used in the existing call to `mbedtls_ssl_ticket_setup()` instead of the currently hardcoded `MBEDTLS_CIPHER_AES_256_GCM`.
- [ ] In `ssl-opt.sh` next to the existing `tickets=1` tests, add tests using various values of that option (ideally one of each value in `mbedtls_cipher_type_t` that's GCM, CCM or ChachaPoly).

Follow-up: #5203

**Comment by gabor-mezei-arm** [comment]
> In ssl-opt.sh next to the existing tickets=1 tests, add tests using various values of that option (ideally one of each value in mbedtls_cipher_type_t that's GCM, CCM or ChachaPoly).


ChachaPoly ciphers are not suppprted by `mbedtls_ssl_ticket_setup()`.

**Comment by mpg** [comment]
> ChachaPoly ciphers are not suppprted by `mbedtls_ssl_ticket_setup()`.

Good point. We should probably update the documentation to reflect that, then. (Perhaps in a separate PR, as this documentation fix probably needs backporting, as it is also relevant for 2.28.)
