### ISSUE TITLE
mbedtls_x509_name private fields getters

### ISSUE THREAD

**Issue by jaudiger** [ARMmbed/mbedtls#5186]
### Suggested enhancement

I would like to have access to private fields of `mbedtls_x509_name` through getters. Right now, I'm using macro `MBEDTLS_PRIVATE()`.

This follows this issue: https://github.com/ARMmbed/mbedtls/issues/5019

### Justification

For now, I just need to access the private fields:

- `next`
- `oid`
- `val`

**Comment by gabor-mezei-arm** [comment]
#4842 made those fields public.
