### ISSUE TITLE
mbedtls_asn1_buf private fields getters

### ISSUE THREAD

**Issue by jaudiger** [ARMmbed/mbedtls#5187]
### Suggested enhancement

I would like to have access to private fields of `mbedtls_asn1_buf` through getters. Right now, I'm using macro `MBEDTLS_PRIVATE()`.

This follows this issue: https://github.com/ARMmbed/mbedtls/issues/5186

### Justification

For now, I just need to access the private fields:

- `p`
- `len`

**Comment by gabor-mezei-arm** [comment]
#4842 made those fields public.
