### ISSUE TITLE
Allow access to private x509 structure field to allow printing a peer certificate

### ISSUE THREAD

**Issue by graeme-walker** [ARMmbed/mbedtls#5201]
### Suggested enhancement

Provide a mechanism to print a peer's certificate as obtained from mbedtls_ssl_get_peer_cert().

### Justification

It is useful to store a peer certificate to allow off-line verification using tools that were developed independently (eg openssl). This was possible in v2 by passing the x509_crt 'raw' field to mbedtls_pem_write_buffer(), but access to 'raw' has been removed in v3. Using mbedtls_x509write_crt might be possible, but would be over-complicated and bug-prone when written by a non-expert.

**Comment by bensze01** [comment]
Hi! Thanks for the report. That access was to the `raw` field was brought to our attention in #4885, and the PR addressing it (#4842) was already merged in development, and will be included in the next release.

We removed the `MBEDTLS_PRIVATE` macro, so it should be possible to use the same method, as in v2.
