### ISSUE TITLE
LTS: CMAC support alters library behaviour

### ISSUE THREAD

**Issue by Tachi107** [ARMmbed/mbedtls#5225]
### Summary

When compiling the library with `MBEDTLS_CMAC_C`, the behaviour of some other components is altered in unpredictable ways (working on providing more details), only on 64 bit architectures

### System information

**Mbed TLS version**: tested from tag v2.16.9 to v2.16.11

**Operating system and version:** Debian Testing

**Configuration:** set: `MBEDTLS_DEPRECATED_WARNING`, `MBEDTLS_HAVEGE_C`, `MBEDTLS_MD2_C`, `MBEDTLS_MD4_C`, `MBEDTLS_THREADING_C`, `MBEDTLS_THREADING_PTHREAD`, **`MBEDTLS_CMAC_C`**

**Compiler and options:**

CMake call: `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DLIB_INSTALL_DIR=lib/x86_64-linux-gnu -DUSE_STATIC_MBEDTLS_LIBRARY=ON -DUSE_SHARED_MBEDTLS_LIBRARY=ON -DENABLE_PROGRAMS=OFF`

Compiler command line example: `/usr/bin/cc  -I/<<PKGBUILDDIR>>/include -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wlogical-op -Wshadow -Wmissing-declarations -Wmissing-prototypes -MD -MT library/CMakeFiles/mbedcrypto_static.dir/cmac.c.o -MF CMakeFiles/mbedcrypto_static.dir/cmac.c.o.d -o CMakeFiles/mbedcrypto_static.dir/cmac.c.o -c /<<PKGBUILDDIR>>/library/cmac.c`

**Additional environment information:** see logs at https://buildd.debian.org/status/fetch.php?pkg=mbedtls&arch=amd64&ver=2.16.11-0.1&stamp=1637269746&raw=0

### Expected behavior

Compiling with CMAC support shouldn't have side effects on unrelated code.

### Actual behavior

When using libmbedcrypto with CMAC support to test shadowsocks-libev, the tests become flaky and failures occur on 64 bit architectures. You can see an example here: https://ci.debian.net/data/autopkgtest/testing/amd64/s/shadowsocks-libev/16942142/log.gz and you can find other related information [here](https://qa.debian.org/excuses.php?package=mbedtls). Since failures only occur in a unpredictable way, could this be related to some kind of use of unallocated/freed memory?

### Steps to reproduce

Compile an LTS version of mbedtls with the options provided above.
Compile the latest version of shadowsocks-libev and link it with the previusly compiled libmbedcrypto version
Run shadowsocks-libev tests

### Additional information

I'm working on isolating the pieces of code that cause the issues, but I'm reporting this issue anyway because maybe you could already know what's going on here.

**Comment by gilles-peskine-arm** [comment]
Enabling `MBEDTLS_CMAC_C` changes the ABI. Generally speaking, most compilation options change the ABI. If you change the Mbed TLS configuration, you must recompile all code that depends on it.

**Comment by Tachi107** [comment]
I believe I recompiled both libraries, but I may be wrong. I hope I did not and that's the cause of the issue (because yes, this really looks like problems that could arise from an ABI mismatch), because this would mean that it's entirely my fault and there are no bugs to be fixed :)

I can't re-test now, but I'll do in a few hours. Thanks for the hint!

**Comment by gilles-peskine-arm** [comment]
By the way, the `library/Makefile` that comes with Mbed TLS does not have correct dependencies: if you change `config.h`, you need to run `make clean`. I didn't mention it earlier because you seem to use CMake, and with CMake, the dependencies are correct. (Or at least I've never had a problem with changing the config and rebuilding with cmake.)

**Comment by Tachi107** [comment]
Hey @gilles-peskine-arm, you were right! The issue was caused by an ABI mismatch. Thank you for the hint, I could've spent countless hours debugging an issue that didn't exist :)

Sorry for the trouble, and thanks again!
