### ISSUE TITLE
mbedtls_x509_crt_parse_path() return value

### ISSUE THREAD

**Issue by github-monoculture** [ARMmbed/mbedtls#524]
The documentation says
"If some certificates can be parsed, the result is the number of failed certificates it encountered. If none complete correctly, the first error is returned."
I made a directory, put in 3 files that were all filled with random keypresses, and the return value was 3.

["What platform were you using (e.g. WIndows or Linux)?"  I'm using Linux.]

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-848

**Comment by pjbakker** [comment]
The documentation is outdated with the way this works. Thanks for noticing.
Return should be 3 for 3 unparsed files.

**Comment by RonEld** [comment]
Closing this issue as we believe this issue has already been fixed.
If you believe this issue was wrongfully closed, please reopen.
