### ISSUE TITLE
The comments about  mbedtls_cipher_cmac_reset is not right.

### ISSUE THREAD

**Issue by soloicesky** [ARMmbed/mbedtls#5241]
### Summary

The comments about  mbedtls_cipher_cmac_reset is not right.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 
Following is the comments of mbedtls_cipher_cmac_reset 

![image](https://user-images.githubusercontent.com/5044681/143833703-8f0d17a6-de03-4b66-9a16-50aa6dcddd95.png)

### Expected behavior
I think it should be 
’It is called after mbedtls_cipher_cmac_update() and before mbedtls_cipher_cmac_finish().‘
because when finish is called the state and unprocessed data in the CMAC context are clear,
no need to call reset to clear them. see below:

![image](https://user-images.githubusercontent.com/5044681/143834081-df187b9c-edea-4d27-93c2-8de3080de822.png)

**Comment by davidhorstmann-arm** [comment]
Thanks for your interest!
I've had a look, and it's in fact not a mistake. The correct usage is:
```C
mbedtls_cipher_cmac_starts(...);
mbedtls_cipher_cmac_update(...); /* As many times as needed */
mbedtls_cipher_cmac_finish(...); /* Write result to output buffer */

mbedtls_cipher_cmac_reset(...); /* Reset to calculate new CMAC with same key */
mbedtls_cipher_cmac_update(...); /* As many times as needed */
mbedtls_cipher_cmac_finish(...); /* Write result to output buffer */

/* Call reset, update, finish as many times as needed */
```
The fact that `mbedtls_cipher_cmac_finish()` clears the same state as `mbedtls_cipher_cmac_reset()` is just coincidence - users can't rely on this behaviour in future versions of Mbed TLS, and they should always call `_reset()` to start a new CMAC operation after calling `_finish()` and before calling `_update()`.
