### ISSUE TITLE
PK: ECDSA signing

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5274]
In `library/pk_wrap.c`, provide an implementation of `ecdsa_sign_wrap` to use `psa_sign_hash()` instead of `mbedtls_ecdsa_write_signature()`.

This will require creating a temporary PSA private key with appropriate permissions. An example of something similar, but with a public key, can be found in `ecdsa_verify_wrap()` in the same file (note: there are two definitions of `ecdsa_very_wrap()`, we want to look at the one used with `MBEDTLS_USE_PSA_CRYPTO`).

This will also require transcoding the resulting signature, as PSA doesn't output ECDSA signatures in the format we expect. We already have a helper function for that: `pk_ecdsa_sig_asn1_from_psa()`, used in `psa_sign_hash()`, which can be re-used here.

Similar: #5160 and #5162 are also creating a temporary PSA private key.

**Comment by superna9999** [comment]
@mpg Can you assign me this issue and link #5518 ?
