### ISSUE TITLE
mbedtls_pk_parse_key 

### ISSUE THREAD

**Issue by SergeyKanatov** [ARMmbed/mbedtls#5304]
/*
 * pkparse.c
 *
 *  Created on: Dec 10, 2021
 *      Author: sergey.kanatov
 */
When user call mbedtls_pk_parse_key for pkcs8_unencrypted_der or for key_pkcs1_der passwords
and set parameter pwdlen=0 suggested code avoid to unuseful calling of: 

mbedtls_calloc (this is critical for embedded systems to avoid defragmentation of memory),
memcpy, 
pk_parse_key_pkcs8_encrypted_der(which return error MBEDTLS_ERR_PK_PASSWORD_REQUIRED), 
mbedtls_pk_free,
mbedtls_pk_init

Thank you.

Kanatov Sergey
sergey.kanatov@medicop.eu

please replace theese lines:

#if defined(MBEDTLS_PKCS12_C) || defined(MBEDTLS_PKCS5_C)
{
    unsigned char *key_copy;

    if( ( key_copy = mbedtls_calloc( 1, keylen ) ) == NULL )
        return( MBEDTLS_ERR_PK_ALLOC_FAILED );

    memcpy( key_copy, key, keylen );

    ret = pk_parse_key_pkcs8_encrypted_der( pk, key_copy, keylen,
                                            pwd, pwdlen );

    mbedtls_platform_zeroize( key_copy, keylen );
    mbedtls_free( key_copy );
}

if( ret == 0 )
    return( 0 );

mbedtls_pk_free( pk );
mbedtls_pk_init( pk );

if( ret == MBEDTLS_ERR_PK_PASSWORD_MISMATCH )
{
    return( ret );
}
#endif /* MBEDTLS_PKCS12_C || MBEDTLS_PKCS5_C */

by theese:

#if defined(MBEDTLS_PKCS12_C) || defined(MBEDTLS_PKCS5_C)
    if(pwdlen!=0) /* OR:  if(pwdlen!=0 && pwd!=NULL) */
    {
        unsigned char *key_copy;

        if( ( key_copy = mbedtls_calloc( 1, keylen ) ) == NULL )
            return( MBEDTLS_ERR_PK_ALLOC_FAILED );

        memcpy( key_copy, key, keylen );

        ret = pk_parse_key_pkcs8_encrypted_der( pk, key_copy, keylen,
                                                pwd, pwdlen );

        mbedtls_platform_zeroize( key_copy, keylen );
        mbedtls_free( key_copy );
	
		if( ret == 0 )
			return( 0 );
	
		mbedtls_pk_free( pk );
		mbedtls_pk_init( pk );
	
		if( ret == MBEDTLS_ERR_PK_PASSWORD_MISMATCH )
		{
			return( ret );
		}
    }
#endif /* MBEDTLS_PKCS12_C || MBEDTLS_PKCS5_C */

**Comment by gilles-peskine-arm** [comment]
This changes the workflow from:
1. Copy key.
2. Try decrypting — which sets `ret` to `MBEDTLS_ERR_PK_PASSWORD_REQUIRED` if `pwdlen == 0`
3. If `ret` is neither 0 nor `MBEDTLS_ERR_PK_PASSWORD_MISMATCH`, try other methods.

to:
1. If `pwdlen != 0`: skip directly to trying other methods
2. Try decrypting — which sets `ret` to `MBEDTLS_ERR_PK_PASSWORD_REQUIRED` if `pwdlen == 0`
3. If `ret` is neither 0 nor `MBEDTLS_ERR_PK_PASSWORD_MISMATCH`, try other methods.

This is indeed equivalent, so it would be a good optimization, thanks for suggesting it.

**Comment by SergeyKanatov** [comment]
Hello, Gilles.
Thank you for answer.

Why functions like pk_parse_key_pkcs8_unencrypted_der declared as static???
Why I can not call it directly? In my case I have private key as binary array in my ARM MCU.
I know format – why I need to call mbedtls_pk_parse_key?

I can call directly mbedtls_x509_crt_parse_der , I don't need to call mbedtls_x509_crt_parse

I suggest remove »static« from declaration of    pk_parse_key_pkcs8_unencrypted_der     and others.

Thank you

Lep pozdrav / Best regards

Sergey Kanatov

***@***.***

**Comment by gilles-peskine-arm** [comment]
If we make an extra function part of the public API, we need to test it, and we can't change its interface later. This has a cost.

I don't really see an advantage to making `pk_parse_key_pkcs8_unencrypted_der` public. If you disable the features your application doesn't need (PEM, encryption), `mbedtls_pk_parse_key` doesn't do much more than call that function.

**Comment by SergeyKanatov** [comment]
Hello, Gilles.

About “static” of some functions. I think that these functions must be public, like mbedtls_x509_crt_parse_der
I can avoid calling  mbedtls_x509_crl_parse<https://tls.mbed.org/api/group__x509__module.html#gadfce4fc5f5af62e371695e74c5b67d70>, because mbedtls_x509_crt_parse_der is public declared.

Same situation – I know format of key and I don’t want to call common function mbedtls_pk_parse_key
This code successful work in my STM32H723 project:

#ifndef HACKED_pk_parse_key_pkcs1_der
    ret=mbedtls_pk_parse_key(&pk, Key_MedicanBus_private, sizeof(Key_MedicanBus_private), NULL, 0);
#else
    //to HACK:
    //remove "static" declaration of pk_parse_key_pkcs1_der() in file "pkparse.c"
    //and declare its prototype

    int pk_parse_key_pkcs1_der( mbedtls_rsa_context *rsa, const unsigned char *key, size_t keylen );
    ret=mbedtls_pk_setup( &pk, mbedtls_pk_info_from_type( MBEDTLS_PK_RSA ));
    ret=pk_parse_key_pkcs1_der( mbedtls_pk_rsa(pk), Key_MedicanBus_private, sizeof(Key_MedicanBus_private) );
#endif
Can you
What a programmer want to say »static inline«? standard function(not a class method in C++) declared static is not visible for call from other files, inline functions(usally in *.h files) say to compiler: don't make call/ret – insert code in all place where call this function.
static inline mbedtls_rsa_context *mbedtls_pk_rsa( const mbedtls_pk_context pk )
{
    return( (mbedtls_rsa_context *) (pk).pk_ctx );
}
I think that »static« must be removed

And I am not alone. Theese example of other man request:

-----------------------------
Hello there,
first at all thank you very much for this great library!
I need a method to parse PKCS#1 encoded private RSA key and found pk_parse_key_pkcs1_der. Unfortunately, it's static so I cannot simply access it. It would be nice if it was non-static, because I assume I'm not the only one who needs this and why reinventing the wheel?
Thank you very much!
Max
-----------------

Lep pozdrav / Best regards

Sergey Kanatov

***@***.***

**Comment by daverodgman** [comment]
I think @gilles-peskine-arm has a good point - if you configure Mbed TLS with only the required features, calling `mbedtls_pk_parse_key` should be efficient as many of the code paths will be `#ifdef'd` out. If you have any real-world measurements that show a significant impact on code size this would be interesting to see though.

Otherwise, I don't think it makes sense to increase the public API surface area, for the reasons Gilles mentions. So I'm closing this, but please let us know if you have some code size measurements which support the idea.
