### ISSUE TITLE
Tinycrypt performance & integration

### ISSUE THREAD

**Issue by andrei-menzopol** [ARMmbed/mbedtls#5356]
Hello,

I want to test/analyze the performance increase of using tinycrypt for ECC operations instead of the standard MbedTLS ECC functions. Could you please help me with a few answers regarding this?

-  I am aware that tinycrypt is already integrated in the **baremetal branch** Do you happen to know what is the performance increase of using this tinycrypt uECC implementation instead of the standard one?

- I would like to port the tinycrypt uECC changes from **baremetal branch** to a Mbed TLS 2.25.0 version used in [Matter repo](https://github.com/project-chip/connectedhomeip) (from where Mbed TLS repo is refered), more exactly [this commit.](https://github.com/ARMmbed/mbedtls/tree/1c54b5410fd48d6bcada97e30cac417c5c7eea67) What do you think is the best approach? I thought of forking Mbed TLS, creating a separate branch with that commit and adding there the tinycrypt changes from baremetal branch. Is this approach ok?

Thank you!

**Comment by minosgalanakis** [comment]
Given the open endded nature of the the question, finding "the best approach" relies on feedback from various sides of the communty. Have you asked this question on the maililing list? It may be a more usefull channel to reach more of the userbase.

**Comment by andrei-menzopol** [comment]
I haven't tried the mailing list, I will post the question there. Thank you.

**Comment by mpg** [comment]
I'm closing this issue, as we use [the mailing-list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) for questions, and you've said you'd post the question there.

**Comment by andrei-menzopol** [comment]
Thank you.
