### ISSUE TITLE
cmake with build directory doesn't find scripts/config.pl

### ISSUE THREAD

**Issue by jwurzer** [ARMmbed/mbedtls#541]
If I want to compile mbedTLS at a separate subdirectory (like "build") the perl script config.pl is not found.

```
mbedtls$ mkdir build
mbedtls$ cd build
mbedtls/build$ cmake ..
...
-- Found Perl: /usr/bin/perl (found version "5.20.2") 
Can't open perl script "scripts/config.pl": No such file or directory
...
```

This can be fixed by in CMakeLists.txt by adding ${CMAKE_CURRENT_SOURCE_DIR} at line 34.
```
    execute_process(COMMAND ${PERL_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/config.pl get MBEDTLS_TEST_NULL_ENTROPY
                        RESULT_VARIABLE result)
```
Maybe this should be fixed/changed at the current dev branch

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-870

**Comment by tripplet** [comment]
Pullrequest #526 should fix this

**Comment by sbutcher-arm** [comment]
Pull request #589 now fixes the problem (and adds a test so we don't miss this again), so this issue can now be closed.
