### ISSUE TITLE
Missing changelog item for API change in 3.1.0

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#5415]
### Summary
Commit https://github.com/ARMmbed/mbedtls/commit/39c2aba9209c0d93bec37f5307304a8ed7ac1e57 introduced an API change to the PSA driver wrapper layer, but this did not get reflected in the changelog.

Additionally, the PR number from the commit message does not exist in this repository. I'm assuming that means the commit got done in a different repository, but it makes it really hard to track the changes and reasoning for those changes.

### Expected behavior
All relevant changes are detailed in the changelog.
All PRs mentioned in the public commit log have public information.

### Actual behavior
Changelog does not contain all relevant changes.
There are a bunch of PRs which landed in the 3.1.0 release which do not link to PRs in this repository.

### Steps to reproduce
Look at the changelog and commit linked above.

**Comment by paul-elliott-arm** [comment]
Hi!
The PR numbers for those issues do not exist in this repository, because they were security issues, and as such were worked on in private prior to disclosure, and merged as part of the release process.

The missing documentation for the API change is, however an issue.

**Comment by paul-elliott-arm** [comment]
Hi Steven,

Having discussed this with the team, we were not adding Changlog items for the driver interface at this point, as it was considered experimental, and thus highly volatile. We will definitely be including any changes to the driver interface in the changelog from here on out.
