### ISSUE TITLE
Add certificate selection callback

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5430]
### Suggested enhancement

Add a new callback (server-side) that's called at the right time for the server to select a certificate.

Constraints:
- must be after all ClientHello extensions have been parsed, at the server might use information from those extensions in order to select a certificate
- must be before the ServerHello is sent, as the selection of the ciphersuite depends on the type of certificate selected.

### Justification

Mbed TLS needs this because sometimes the server needs to adjust its behaviour based on multiple extensions, so per-extension callback (such as the existing SNI callback) are not enough. An example is servers who want to support the ACME "tls-alpn-01" challenge, where certificate selection needs to happen based not only on SNI but also ALPN extension, as reported in #5331.

Finally, it appears there's a similar callback in OpenSSL since 1.0.2 and people are using it.

**Comment by gstrauss** [comment]
#5454 "server certificate selection callback" submitted as a Draft for discussion.

**Comment by mpg** [comment]
Renaming to  "add certificate selection callback" - after discussion with the team, we agreed that new callbacks should not be named after a particular point in the handshake, but after the action they're meant to allow. Handshake flows might change between versions and it's our job to shield users from those low-level details and just run the callback at the right time for the associated action.
