### ISSUE TITLE
Mbed TLS gets miscompiled on ARM64 with MSVC

### ISSUE THREAD

**Issue by TautvydasZilys** [ARMmbed/mbedtls#5467]
### Summary

When built using Microsoft's C++ compiler for ARM64, the function `mbedtls_mpi_exp_mod` gets miscompiled and doesn't properly work. Specifically, when `mbedtls_mpi_safe_cond_assign` gets inlined, it calculates an incorrect mask, which makes the assignment miss the bits 1-7.

I've reported this to Microsoft here: https://developercommunity.visualstudio.com/t/c-compiler-miscompiles-part-of-mbedtls-library-on/1646989

I was able to work around this in our fork of mbedtls by marking `mbedtls_mpi_safe_cond_assign` as noinline:

```
#if defined(_MSC_VER) && defined(_M_ARM64)
__declspec(noinline)
#endif
```

### System information

Mbed TLS version (number or commit id): [v2.27.0](https://github.com/ARMmbed/mbedtls/releases/tag/v2.27.0)
Operating system and version: Windows 11 (build 22000.318)
Configuration (if not default, please attach `mbedtls_config.h`): It has these modifications:

```
// We handle file and network ops outside the tls impl
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_FS_IO
#undef MBEDTLS_NET_C

// We have our own pem parser
#undef MBEDTLS_PEM_PARSE_C
#undef MBEDTLS_PEM_WRITE_C

// not needed since HAVEGE is
// disabled by default
#undef MBEDTLS_TIMING_C

// We use our own mutex impl
#define MBEDTLS_THREADING_C
#define MBEDTLS_THREADING_ALT

// Enable SIMD where applicable
#if PLATFORM_SUPPORTS_SSE
#define MBEDTLS_HAVE_SSE2
#endif

#undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
```

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): We're using Visual Studio 2019 C++ compiler. But I checked and it's still reproducible when built using VS 2022 (and that's why I reported it to Microsoft).

```
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for ARM64
cl.exe "library\bignum.c" /MD /c /bigobj /utf-8 /cgthreads2 /Ox /Gw /Zo /Oy- /d2ssa-cse- /TC /Zm200 /EHsc /GR /Gy /nologo /GF /Zi /Zf /GS- /W3 /we4002 /we4003 /we4547 /we4549 /we4555 /we4554 /we4578 /we4263 /we4312 /we4102 /we4555 /we4065 /we4715 /we4805 /we4351 /we4005 /we4090 /we4013 /we4146 /we4521 /we4068 /we4067 /we4882 /we4180 /we4305 /we4334 /we4995 /we4996 /we4474 /we4476 /we4193 /we4099 /we4551 /wd4244 /wd4251 /wd4018 /wd4800 /wd4267 /wd4345 /wd4482 /wd4577 /DUNICODE /D_UNICODE /D_SECURE_SCL=0 /D_ITERATOR_DEBUG_LEVEL=0 /D_HAS_ITERATOR_DEBUGGING=0 /D__WRL_NO_DEFAULT_LIB__ /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D_WINDLL=1 /DWIN32 /DWINDOWS /D_WINDOWS /DMBEDTLS_NO_PLATFORM_ENTROPY=1 /DENABLE_MBEDTLS=1 /DMBEDTLS_USER_CONFIG=1 /DMBEDTLS_PSK_MAX_LEN=64 /DNDEBUG /D_CRT_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_DEPRECATE /D_WINSOCK_DEPRECATED_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_WIN64 /D_ARM64_ /I"." /I"include" /I"<MSVCToolChainDir>\include" /I"<winsdkdir>\Include\10.0.18362.0\shared" /I"<winsdkdir>\Include\10.0.18362.0\um" /I"<winsdkdir>\Include\10.0.18362.0\winrt" /I"<winsdkdir>\Include\10.0.18362.0\ucrt" /I"<winsdkdir>\Include\10.0.18362.0\cppwinrt" /Fd"artifacts\VS2019_arm64_dev_i_ut_r\arm64_release_il2cpp_compiler.pdb" /FS /Fo"artifacts\VS2019_arm64_dev_i_ut_r\nml4\bignum.obj" /Zc:__cplusplus /std:c++17 -d2FH4-
```

Additional environment information: We reproduced this issue on HoloLens 2 and on M1 Mac running Windows 11 via Parallels.

### Additional information

This started happening after we updated Mbed TLS to 2.27.0. I suspect one of these commits had something to do with it:

https://github.com/ARMmbed/mbedtls/commit/1297ef3762880320864cb6d7b92981e1db710dde
https://github.com/ARMmbed/mbedtls/commit/92413ef5bcb5ca47bd132ae7bdb55c8cf7223d2d

While this isn't really a bug in Mbed TLS, it might be worth putting in a workaround. It doesn't impact us whether you do it or not as we have our own fork.

**Comment by paul-elliott-arm** [comment]
Hi!
I would invite you to submit a PR with the workaround, although it would be nice to tie the workaround down to non-working compiler versions, as obviously there is the danger of the workaround remaining on longer than it needs to be.

It would certainly not be good for users not to be able to compile our library for windows on arm out of the box due to this, I will attempt to watch your bug report progress.

Paul.

**Comment by TautvydasZilys** [comment]
> although it would be nice to tie the workaround down to non-working compiler versions

Well, there isn't a fix in sight yet so I don't know which version it will be fixed in. Therefore I don't think I can do that.

**Comment by TautvydasZilys** [comment]
I created a pull request here: https://github.com/ARMmbed/mbedtls/pull/5468

**Comment by TautvydasZilys** [comment]
The PRs were merged so I'm closing this issue as resolved.
