### ISSUE TITLE
`chachapoly` cipher has reversed constants for operation modes

### ISSUE THREAD

**Issue by Oldes** [ARMmbed/mbedtls#5474]
### Summary

There is used `enum` in the `chachapoly` code:
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/chachapoly.h#L50-L54
which means, that `MBEDTLS_CHACHAPOLY_ENCRYPT == 0`, but generic mode for encryption is `1`:
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/cipher.h#L216-L220

and also in other ciphers it is `1`:
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/aes.h#L51-L52
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/aria.h#L40-L41
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/camellia.h#L33-L34
https://github.com/ARMmbed/mbedtls/blob/a9f32fbb21c663b73462ea8b18d620818d300f59/include/mbedtls/des.h#L37-L38

### Expected behavior

There should be consistency.

**Comment by mpg** [comment]
Hi, and thanks for your report. While I agree that consistency is important, and it would have been nice if we noticed and aligned chachapoly on existing ciphers when it was introduced, I'm not sure if it's really worth changing now. This would be an ABI break, and while we don't promise ABI stability in the development branch, we still try not to break the ABI too often.

Is this causing practical problems? I'm under the impression that the value of the constants shouldn't matter that much in practice, since everyone should be using the symbolic names. Am I missing something?

**Comment by Oldes** [comment]
Not a big problem... if I don't count that I spend quite a long time figuring out, why my code (which does not use the generic api, because I have my own sort of generic dispatcher) is not working as expected.

I just have to use now:
```
mbedtls_chachapoly_mode_t mode = ctx->operation == MBEDTLS_ENCRYPT ? MBEDTLS_CHACHAPOLY_ENCRYPT : MBEDTLS_CHACHAPOLY_DECRYPT;
```
Instead of using `(mbedtls_chachapoly_mode_t)ctx->operation` directly.

I understand, that the change is not only about swapping two lines and so may be risky in current state. At least I wanted to let you know about it.

**Comment by Oldes** [comment]
Feel free to close the issue if you want. I already have a comment in my code with a link here, co it will be clear, why I have the strange `mode` definition, when it is not used for other ciphers.

**Comment by mpg** [comment]
> Not a big problem... if I don't count that I spend quite a long time figuring out [...]

Sorry for that.

> Feel free to close the issue if you want. I already have a comment in my code with a link here, co it will be clear, why I have the strange mode definition, when it is not used for other ciphers.

Thanks for letting us know! I'll ask for a second opinion whether this is worth changing the values. Or perhaps we could just add a comment - do you think a comment would have save you some time here?

**Comment by Oldes** [comment]
Yes, it make sense to have a comment in `cipher.h` that the values are not guaranteed to be same for all ciphers and also probably in the `chachapoly.h`. It would definitely save my time... because I added ChaChaPoly later and before the values were compatible, so I was searching a problem elsewhere.

**Comment by mpg** [comment]
After discussing with colleagues, we've decided not to change the value. People writing their own dispatch layer is a relatively rare case, and in the long run all the low-level modules (aes.h, camelia.h, etc), as well as the abstraction in `cipher.h` are going to be deprecated in favour of the PSA Crypto API, and improving them is not a priority.

So, I'm closing this as wontfix, but want to thank you again nonetheless for your report. Hopefully it will help the next person who stumbles upon this, and we'll keep this in mind if similar situations happen in the future when developing new code.
