### ISSUE TITLE
Compiler warning about ambiguous if statement

### ISSUE THREAD

**Issue by sbranden** [ARMmbed/mbedtls#552]
Please add braces around the following if statement to remove a compile warning about ambiguous if statements.  For us, mbedtls_fprintf is a macro with another if statment inside of it.

`---
 library/memory_buffer_alloc.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/library/memory_buffer_alloc.c b/library/memory_buffer_alloc.c
index b2c775a..44b029d 100644
--- a/library/memory_buffer_alloc.c
+++ b/library/memory_buffer_alloc.c
@@ -523,7 +523,9 @@ void mbedtls_memory_buffer_alloc_status()
                       heap.alloc_count, heap.free_count );

```
 if( heap.first->next == NULL )
```
-    {
       mbedtls_fprintf( stderr, "All memory de-allocated in stack buffer\n" );
-    }
   else
   {
       mbedtls_fprintf( stderr, "Memory currently allocated:\n" );
  -- `

**Comment by mjs-arm** [comment]
Rather than try to adjust all call sites. Why not fix the macro definition itself?

http://stackoverflow.com/questions/257418/do-while-0-what-is-it-good-for

**Comment by sbranden** [comment]
Thanks for suggestion - will adjust macro.

But, it would also be good to cleanup mbedtls  This first part of this if statement has no braces while the second half does.  Typical coding style is if one part of if else has braces then other portion should as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-960

**Comment by sbutcher-arm** [comment]
PR's to address this issue, #1182 for `development`, #1581 for `mbedtls-2.7` and #1581 for `mbedtls-2.1` have now been merged, so this issue can now be closed.
