### ISSUE TITLE
Adding mbedtls to hostapd

### ISSUE THREAD

**Issue by laoshaw** [ARMmbed/mbedtls#5550]
### Suggested enhancement

Adding mbedtls to hostapd, e.g https://www.spinics.net/lists/hostap/msg04111.html

### Justification

Mbed TLS needs this because probably millions of routers(e.g. running openwrt or its modified version) and IoT devices with wifi can benefit due to its compact size and liberal license. OpenSSL is just too large in size.

**Comment by gilles-peskine-arm** [comment]
Hi @laoshaw,

Unfortunately the Mbed TLS team does not have any bandwidth for integrating the library into third-party software. We do not currently maintain any packaging or integration of Mbed TLS. This is something you need to take up with the hostapd project.

If Mbed TLS lacks specific features, feel free to open a feature request here. (Or even better, a pull request.)

**Comment by gstrauss** [comment]
FYI: follow-up discussion (and prototype code) at https://github.com/openwrt/openwrt/issues/10303
