### ISSUE TITLE
compiler warnings involving shadowing of 'index' and 'time' standard C library functions

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#557]
In mbed TLS 2.3.0 there are some function prototypes that use argument names that shadow two standard C library function names: index and time.

This is in:
mbedtls_ecp_group_load in ecp.h (2nd arg named index) 
mbedtls_x509_time_is_past in x509.h (1st arg named time)
mbedtls_x509_time_is_future in x509.h (1st arg named time)

It would be nice if these argument names were changed in these header files to avoid this warning on older toolchains.

**Comment by pjbakker** [comment]
Duly noted.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-957

**Comment by sbutcher-arm** [comment]
Fixed in PR's #886, #1032, #1031, merged respectively into the private `development`, `mbedtls-2.1` and `mbedtls-1.3` branches.
