### ISSUE TITLE
mbedtls_rsa_gen_key no longer guarantees that P > Q

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#558]
In mbed TLS 2.3.0 the function mbedtls_rsa_gen_key no longer guarantees that P is greater than Q in the generated key. The PKCS#1 spec says nothing about this, but many other libraries guarantee this and it would be easy for this function to continue to do so. It seems like breaking an existing convention like this is not a good idea (this behavior was changed by 10c575be3ee5d332923a888cf261b650e590eb32 in git).

**Comment by pjbakker** [comment]
Agreed that it's not required by the spec, but something done often.

Not sure why that change was introduced in that patch as it does not seem part of the rest of the issue it tried to fix.

Will investigate and probably re-introduce the 'switch' that was removed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-956

**Comment by sbutcher-arm** [comment]
Fixed by PR #625 on the development branch.
