### ISSUE TITLE
build error in programs/pkey/gen_key.c involving MBEDTLS_PEM_WRITE_C

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#559]
In mbed TLS 2.3.0 when the library is built without MBEDTLS_PDM_WRITE_C there is a build error in programs/pkey/gen_key.c (it references mbedtls_pk_write_key_pem with no ifdef).

There should be an ifdef around line 157 surrounding the calls to mbedtls_pk_write_key_pem and strlen (the else side of the ifdef should just return -1).

**Comment by pjbakker** [comment]
Thanks for noticing. Will be fixed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-955

**Comment by sbutcher-arm** [comment]
This is fixed by pull request #640 so this issue can now be closed.
