### ISSUE TITLE
Error when building shared library

### ISSUE THREAD

**Issue by Ayrx** [ARMmbed/mbedtls#56]
I encountered an issue when attempting to compile a shared library with `make`. This problem does not occur when using `cmake` with 

> option(USE_SHARED_POLARSSL_LIBRARY "Build PolarSSL as a shared library." ON)

Any tips on resolving this without using `cmake`? 

> [ayrx@c00kies library]$ make shared
>   CC    aes.c
>   CC    aesni.c
>   CC    arc4.c
>   CC    asn1parse.c
>   CC    asn1write.c
>   CC    base64.c
>   CC    bignum.c
>   CC    blowfish.c
>   CC    camellia.c
>   CC    certs.c
>   CC    cipher.c
>   CC    cipher_wrap.c
>   CC    ctr_drbg.c
>   CC    debug.c
>   CC    des.c
>   CC    dhm.c
>   CC    ecdh.c
>   CC    ecdsa.c
>   CC    ecp.c
>   CC    ecp_curves.c
>   CC    entropy.c
>   CC    entropy_poll.c
>   CC    error.c
>   CC    gcm.c
>   CC    havege.c
>   CC    md.c
>   CC    md_wrap.c
>   CC    md2.c
>   CC    md4.c
>   CC    md5.c
>   CC    memory.c
>   CC    memory_buffer_alloc.c
>   CC    net.c
>   CC    oid.c
>   CC    padlock.c
>   CC    pbkdf2.c
>   CC    pem.c
>   CC    pkcs5.c
>   CC    pkcs11.c
>   CC    pkcs12.c
>   CC    pk.c
>   CC    pk_wrap.c
>   CC    pkparse.c
>   CC    pkwrite.c
>   CC    rsa.c
>   CC    sha1.c
>   CC    sha256.c
>   CC    sha512.c
>   CC    ssl_cache.c
>   CC    ssl_cli.c
>   CC    ssl_srv.c
>   CC    ssl_ciphersuites.c
>   CC    ssl_tls.c
>   CC    threading.c
>   CC    timing.c
>   CC    version.c
>   CC    x509.c
>   CC    x509_create.c
>   CC    x509_crl.c
>   CC    x509_crt.c
>   CC    x509_csr.c
>   CC    x509write_crt.c
>   CC    x509write_csr.c
>   CC    xtea.c
>   AR    libpolarssl.a
> ar: creating libpolarssl.a
>   RL    libpolarssl.a
>   LD    libpolarssl.so.5
> /usr/bin/ld: aes.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
> aes.o: could not read symbols: Bad value
> collect2: error: ld returned 1 exit status
> make: **\* [libpolarssl.so.5] Error 1

**Comment by azhai** [comment]
export CFLAGS="-fPIC"

**Comment by mpg** [comment]
The "official" way is still (as Paul said) to define `SHARED` as an environment variable in your shell or in your invocation of make, eg `make SHARED=1`, see https://github.com/ARMmbed/mbedtls/blob/development/README.rst#make
