### ISSUE TITLE
Unable to access handshake.resume member of mbedtls_ssl_context struct to check whether session cache was used in dtls_psk_server.c example program

### ISSUE THREAD

**Issue by Eoin-McMahon** [ARMmbed/mbedtls#5606]
### Summary

To note: I am using tag v3.0.0 

I am trying to modify https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/dtls_server.c to print out whether session caching has been used for a given connection.

Looking at the docs it seems i can check the value of ssl.handshake.resume 

but when i try to add a line to print the value of this member, i get 
error: 'struct mbedtls_ssl_context' has no member named 'handshake'

I have added:
`printf( " session cache status:  %d\n", ssl.handshake.resume );`

to line 321, just after the handshake completes: 
```C
    /*
     * 5. Handshake
     */
    printf( "  . Performing the DTLS handshake..." );
    fflush( stdout );

    do ret = mbedtls_ssl_handshake( &ssl );
    while( ret == MBEDTLS_ERR_SSL_WANT_READ ||
           ret == MBEDTLS_ERR_SSL_WANT_WRITE );

    if( ret == MBEDTLS_ERR_SSL_HELLO_VERIFY_REQUIRED )
    {
        printf( " hello verification requested\n" );
        ret = 0;
        goto reset;
    }
    else if( ret != 0 )
    {
        printf( " failed\n  ! mbedtls_ssl_handshake returned -0x%x\n\n", (unsigned int) -ret );
        goto reset;
    }

    printf( " session cache status:  %d\n", ssl.handshake.resume );
    printf( " ok\n" );

```

**Comment by tom-cosgrove-arm** [comment]
Note that `handshake` is documented as

```
mbedtls_ssl_handshake_params *MBEDTLS_PRIVATE(handshake);    /*!<  params required only during the handshake process */
```

i.e. it is private. Where in the docs does it say to examine this field?

You may be better off asking describing what you are trying to do on the Mbed TLS mailing list - see https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/

**Comment by tom-cosgrove-arm** [comment]
Closing this issue as the question has now been raised on the mailing list (@Eoin-McMahon thanks for doing that - it's a better place for questions like this, and the devs are all on the list)
