### ISSUE TITLE
regression in x509_crt_verify_top in 2.3.0

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#561]
In mbed TLS 2.3.0 there is a new bug in x509_crt_verify_top that was introduced by git b437b4b1252fa8f2e9bb1585a613fd70fc6c0525.

Basically this breaks mbed TLS users that use callbacks to filter out time-related certificate chain errors (MBEDTLS_X509_BADCERT_EXPIRED and MBEDTLS_X509_BADCERT_FUTURE). Before this change callers with broken time() implementations could use their callback to filter out those two errors and then if all other checks passed the overall validation would pass. After this change callers with broken time() implementations end up receiving MBEDTLS_X509_BADCERT_NOT_TRUSTED instead with no way to filter that out.

Change b437b4b1252fa8f2e9bb1585a613fd70fc6c0525 should be reverted (I understand what it was trying to do but the fix is wrong).

**Comment by pjbakker** [comment]
Thanks for the report. Agree with the analysis that it introduces a new behaviour while trying to fix an issue.

Will need to be investigated.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-953

**Comment by sbutcher-arm** [comment]
Fixed, pending release.
