### ISSUE TITLE
unused variables in x509_crt.c

### ISSUE THREAD

**Issue by omnium21** [ARMmbed/mbedtls#562]
When building ARM Trusted Firmware with mbedtls version 2.3.0, compilation fails due to the declaration of unused variables and the "-Werror=unused-variable" flag passed to GCC.

The error output from the ARM-TF build is:

  CC      plat/arm/css/common/css_bl1_setup.c
/working/platforms/mbedtls/library/x509_crt.c: In function
'mbedtls_x509_crt_parse':
/working/platforms/mbedtls/library/x509_crt.c:972:39: error: unused
variable 'total_failed' [-Werror=unused-variable]
     int success = 0, first_error = 0, total_failed = 0;
                                       ^
/working/platforms/mbedtls/library/x509_crt.c:972:22: error: unused
variable 'first_error' [-Werror=unused-variable]
     int success = 0, first_error = 0, total_failed = 0;
                      ^
/working/platforms/mbedtls/library/x509_crt.c:972:9: error: unused
variable 'success' [-Werror=unused-variable]
     int success = 0, first_error = 0, total_failed = 0;
         ^

**Comment by pjbakker** [comment]
Thanks for reporting this. Will be fixed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-952

**Comment by sbutcher-arm** [comment]
This issue has been fixed in `development`, `mbedtls-2.4`, `mbedtls-2.1` and `mbedtls-1.3` branches, using pull requests #713, #714 and #715.

Therefore this issue can now be closed.

**Comment by omnium21** [comment]
Is there a plan for this to be merged to the master branch?

**Comment by sbutcher-arm** [comment]
There are lots of different ways of using git, and our method (for mbed TLS - mbed OS is different), is to push back to `master` on each release, so the head of `master` always reflects the most recent release, whilst `development`will reflect the latest development changes.

So, @omnium21, to answer your question - yes, when we ship the next version.
