### ISSUE TITLE
TLS 1.3: Incorrect check of EC group when verifying a certificate

### ISSUE THREAD

**Issue by ronald-cron-arm** [ARMmbed/mbedtls#5646]
### Summary
TLS 1.3 RFC:
"When sent by the client, the "supported_groups" extension indicates the named groups which the client supports for key exchange, ordered from most preferred to least preferred.

Note: In versions of TLS prior to TLS 1.3, this extension was named "elliptic_curves" and only contained elliptic curve groups. See
[RFC8422] and [RFC7919]. This extension was also used to negotiate ECDSA curves. Signature algorithms are now negotiated independently (see Section 4.2.3)."

When verifying a server certificate with an EC key, we currently check that the group associated to the key has been proposed in the `supported_group` which is not correct.

### System information

Mbed TLS version (number or commit id): development
Operating system and version: -
Configuration (if not default, please attach `mbedtls_config.h`): - 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): -
Additional environment information: -

### Expected behavior
We should remove the check that the EC group is valid for key exchange.

### Additional information
The tests in tls13-compat.sh should be changed to remove the EC group used for verifying the signature from the list of groups for key exchange.

**Comment by gaoqingshui** [comment]
|    Extension name        |           Usage              |
-------------------------------------------------------------
TLS1.2  |    elliptic curves          |      ECDH and ECDSA  |
-------------------------------------------------------------
TLS1.3  |    supported groups   |        ECDH only           |
-------------------------------------------------------------
