### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by rongsaws** [ARMmbed/mbedtls#569]
I wonder if the check for `MBEDTLS_HAVE_INT64` at line 1303 is really required here? It's not done in ecp_mod_p256k1() or ecp_mod_p192k1():

https://github.com/ARMmbed/mbedtls/blob/development/library/ecp_curves.c#L1303-L1307

With argument `adjust` being 1 when function ecp_mod_koblitz() is called, at line 1328 `M->n` will increase by 0:
`
    M.n += R.n - adjust; /* Make room for multiplication by R */
`

and then when it gets to line 1247
`
    MBEDTLS_MPI_CHK( mbedtls_mpi_mul_mpi( &M, &M, &R ) );
`

mbedtls_mpi_grow() may force releasing the buffer (Mp) of M, which is allocated on the stack at line 1216:
`
 mbedtls_mpi_uint Mp[P_KOBLITZ_MAX + P_KOBLITZ_R];
`

**Comment by yanesca** [comment]
Hi, thank you for taking interest in mbed TLS!

I think `MBEDTLS_HAVE_INT64` is necessary at that line. If you have 64 bit words, then your 256 and 192 bit modulus will perfectly fit within the word boundaries, but when the modulus is 224 bit long then may have to do some adjustments.

Yes, you are right that the buffer `Mp` in `ecp_mod_koblitz()` is allocated on the stack and it would be very unfortunate if the `mbedtls_mpi_grow()` function would try to free it. 

Clearly this is very suspicious and probably shouldn't be like this. Thank you for pointing it out!

**Comment by rongsaws** [comment]
If needed, I could provide a test case to show how this bug can be reproduced.

**Comment by yanesca** [comment]
Yes, that sounds very good!

But please know, that to accept any contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. You can find an agreement to sign [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and accept a slightly different agreement [here](https://developer.mbed.org/contributor_agreement/) with a click through if this is a personal contribution.

Also we can't promise anything about when this bug will be fixed or when your contribution will be merged.

Thanks for your understanding!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-951

**Comment by sbutcher-arm** [comment]
The issue that, as @yanesca describes of, "the buffer `Mp` in `ecp_mod_koblitz()` being allocated on the stack and ... if the `mbedtls_mpi_grow()` function would try to free it" has been fixed and is now pending release.
