### ISSUE TITLE
Run-time error/exception due to un-initialized rsa structure 

### ISSUE THREAD

**Issue by ShadowGuan** [ARMmbed/mbedtls#570]
**Version:** 2.3.0
**How to Reproduce:** 
1. Open the VC solution
2. Build and Run rsa_genkey
3. Build and Run rsa_encrypt with any string argument
4. Build and Run rsa_decrypt - You can see a memory writing exception thrown out, which occurs when memset the p pointer in function `mbedtls_mpi_lset`

```
int mbedtls_mpi_lset( mbedtls_mpi *X, mbedtls_mpi_sint z )
{
    int ret;

    MBEDTLS_MPI_CHK( mbedtls_mpi_grow( X, 1 ) );
    memset( X->p, 0, X->n * ciL );  <==== the program stopped here.
    X->p[0] = ( z < 0 ) ? -z : z;
    X->s    = ( z < 0 ) ? -1 : 1;

cleanup:

    return( ret );
}
```

**Root Cause**
in the main function of file rsa_decrypt.c,  the variable rsa is not initialized before `mbedtls_mpi_read_file` is called.
In the following function we can see X->p pointer will have mem calloced only when X->n < nblimbs.
But as X is not initialized, the X->n has an undefined value. If you are not lucky enough, the n will much bigger than nblimbs and X->p will never got calloced.

```
int mbedtls_mpi_grow( mbedtls_mpi *X, size_t nblimbs )
{
    mbedtls_mpi_uint *p;

    if( nblimbs > MBEDTLS_MPI_MAX_LIMBS )
        return( MBEDTLS_ERR_MPI_ALLOC_FAILED );

    if( X->n < nblimbs )
    {
        if( ( p = (mbedtls_mpi_uint*)mbedtls_calloc( nblimbs, ciL ) ) == NULL )
            return( MBEDTLS_ERR_MPI_ALLOC_FAILED );

        if( X->p != NULL )
        {
            memcpy( p, X->p, X->n * ciL );
            mbedtls_mpi_zeroize( X->p, X->n );
            mbedtls_free( X->p );
        }

        X->n = nblimbs;
        X->p = p;
    }

    return( 0 );
}
```

Additional, the rsa_decrypt main function of 2.2.1 version has the initialization `mbedtls_rsa_init` before `mbedtls_mpi_read_file`, which is deleted by version 2.3.0.

**Comment by pjbakker** [comment]
Verified that commit 6b46c62d erroneously missed a line when moving initialization code in *rsa_decrypt.c*

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-950
