### ISSUE TITLE
esp8266 support

### ISSUE THREAD

**Issue by chennakeshavaSoC** [ARMmbed/mbedtls#571]
Hi mbedtls,

We are using AWS C SDK, and we are facing issues in integrating mbedtls. From AWS SDK the example programs are targeted for windows, linux. When we integrate the same SDK with our target the code size is exceeding our target size. From the AWS documentation the following cipher suites are recommended.
ECDHE-ECDSA-AES128-GCM-SHA256 (recommended)
ECDHE-RSA-AES128-GCM-SHA256 (recommended)

We do not have support for file system on our target.
Is there any config file which enables the bare minimum per-requisites of TLS to connect to AWS.

Regards,
Chennakeshava

**Comment by chennakeshavaSoC** [comment]
AWS TLS clients must support all of the following in their TLS implementation:
    TLS 1.2.
    SHA-256 RSA certificate signature validation.
    One of the cipher suites from the TLS cipher suite support section.

**Comment by pjbakker** [comment]
We don't have a specific config for AWS. All our example configs we test with are in the [configs directory](https://github.com/ARMmbed/mbedtls/tree/development/configs).

If you make a minimal config specifically for AWS we might be able to include it in the future.

Based on your description, it would be straightforward (using the config.h explanations) to make such a minimal configuration even without file system support (which mbed TLS does not need as long as you have all your important keys / certificates in ROM values)

(As this is not a real bug, I'll close this issue)
