### ISSUE TITLE
mbedtls_md_get_size has the wrong return type

### ISSUE THREAD

**Issue by aaronmdjones** [ARMmbed/mbedtls#573]
The function `mbedtls_md_get_size` has a return type of `unsigned char`, however the field it returns is of type `int`.

I argue both that the return type should match the field type, and the field type should be `size_t` (EDIT: Or, at least, `unsigned int`). 

However, changing the latter will change the ABI.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-949

**Comment by hanno-arm** [comment]
@RonEld Why is this being closed without a single note?
