### ISSUE TITLE
ssl->out_left in handling ssl_write_real

### ISSUE THREAD

**Issue by zecke** [ARMmbed/mbedtls#575]
Sorry I am currently exploring which TLS server/client library to use and was just browsing the code to understand if the system can be operated genuinely non-blocking/etc.

In ssl_write_real I see this part of the code. To me it looks like:

* If ssl->out_left != 0
* And mbedtls_ssl_flush_output succeeds (all data written, ctr doesn't wrap)

The method will return len _without_ anything being queued for writing? Am I wrong?

```
    if( ssl->out_left != 0 )
    {
        if( ( ret = mbedtls_ssl_flush_output( ssl ) ) != 0 )
        {
            MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_ssl_flush_output", ret );
            return( ret );
        }
    }
    else
    {
        ssl->out_msglen  = len;
        ssl->out_msgtype = MBEDTLS_SSL_MSG_APPLICATION_DATA;
        memcpy( ssl->out_msg, buf, len );

        if( ( ret = mbedtls_ssl_write_record( ssl ) ) != 0 )
        {
            MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_ssl_write_record", ret );
            return( ret );
        }
    }

    return( (int) len );
```

**Comment by pjbakker** [comment]
That seems curious indeed.
On initial inspection I would assume a `len = 0` on success would be appropriate there.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-948

**Comment by yanesca** [comment]
I don't think you are wrong @zecke . But I think it is the intended behaviour. Namely it will return `MBEDTLS_ERR_SSL_WANT_WRITE` while there is any data being queued for writing. Whenever `mbedtls_ssl_flush_output` returns with 0 then all data is already written.

The return value is still correct because it doesn't reflect the number of byte queued, but the _total_ number of bytes written.

You can find a detailed description of this behaviour in the [doxygen documentation](https://tls.mbed.org/api/ssl_8h.html#a5bbda87d484de82df730758b475f32e5).

**Comment by zecke** [comment]
Okay, you are right.

```
When this function returns MBEDTLS_ERR_SSL_WANT_WRITE/READ, it must be called later with the same arguments, until it returns a positive value.
```

in GNUtls it says call it with NULL, 0 to make it more clear that it is about flushing the buffer. For an implementer that uses non blocking sockets both of your notes must be followed. for > 0 returns i need to remember how much was consumed and for < 0 need to call with same arguments. Maybe you can remove the warning as it can't happen right now?

**Comment by yanesca** [comment]
Sorry, which warning do you mean?

**Comment by zecke** [comment]
```
Warning
This function will do partial writes in some cases. If the return value is non-negative but less than length, the function must be called again with updated arguments: buf + ret, len - ret (if ret is the return value) until it returns a value equal to the last 'len' argument.
```

For non blocking cases as an API user it would be easier to consider one abnormal case instead of mixing the two. After a brief look I don't think   ret > 0 && ret < len will occur (for -EWOULDBLOCK/-EAGAIN MBEDTLS_ERR_SSL_WANT_WRITE seems to be returned besides some data having been written in a previous run of the do {} while)

**Comment by yanesca** [comment]
You are right, that case won't occur in `ssl_write_real`. But it is only a static function for inner use and it is not exposed directly. The API user can only call `mbedtls_ssl_write`, which besides being a public wrapper for `ssl_write_real`, handles the fragmentation of the message if necessary.

Therefore 
> If the requested length is greater than the maximum fragment length (either the built-in limit or the  one set or negotiated with the peer), then:
> with TLS, less bytes than requested are written.

**Comment by zecke** [comment]
Okay
