### ISSUE TITLE
fix warnings from wdk

### ISSUE THREAD

**Issue by redplait** [ARMmbed/mbedtls#586]
windows driver kit claims on several implicit typecasts. simple patch to fix it:

<pre>diff -up D:\work\src\crypto\mbedtls-2.3.0\library/asn1write.c D:\work\src\mbedtls-2.3.0\library/asn1write.c
*** D:\work\src\crypto\mbedtls-2.3.0\library/asn1write.c    Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library/asn1write.c   Tue Aug 30 19:30:17 2016
*************** int mbedtls_asn1_write_int( unsigned cha
*** 213,219 ****
          return( MBEDTLS_ERR_ASN1_BUF_TOO_SMALL );
  
      len += 1;
!     *--(*p) = val;
  
      if( val > 0 && **p & 0x80 )
      {
--- 213,219 ----
          return( MBEDTLS_ERR_ASN1_BUF_TOO_SMALL );
  
      len += 1;
!     *--(*p) = (unsigned char)val;
  
      if( val > 0 && **p & 0x80 )
      {
diff -up D:\work\src\crypto\mbedtls-2.3.0\library/ctr_drbg.c D:\work\src\mbedtls-2.3.0\library/ctr_drbg.c
*** D:\work\src\crypto\mbedtls-2.3.0\library/ctr_drbg.c Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library/ctr_drbg.c    Tue Aug 30 18:04:09 2016
*************** static int block_cipher_df( unsigned cha
*** 178,184 ****
      buf_len = MBEDTLS_CTR_DRBG_BLOCKSIZE + 8 + data_len + 1;
  
      for( i = 0; i < MBEDTLS_CTR_DRBG_KEYSIZE; i++ )
!         key[i] = i;
  
      mbedtls_aes_setkey_enc( &aes_ctx, key, MBEDTLS_CTR_DRBG_KEYBITS );
  
--- 178,184 ----
      buf_len = MBEDTLS_CTR_DRBG_BLOCKSIZE + 8 + data_len + 1;
  
      for( i = 0; i < MBEDTLS_CTR_DRBG_KEYSIZE; i++ )
!         key[i] = (unsigned char)i;
  
      mbedtls_aes_setkey_enc( &aes_ctx, key, MBEDTLS_CTR_DRBG_KEYBITS );
  
diff -up D:\work\src\crypto\mbedtls-2.3.0\library/ecp.c D:\work\src\mbedtls-2.3.0\library/ecp.c
*** D:\work\src\crypto\mbedtls-2.3.0\library/ecp.c  Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library/ecp.c Tue Aug 30 18:04:35 2016
*************** static int ecp_mul_mxz( mbedtls_ecp_grou
*** 1580,1586 ****
      i = mbedtls_mpi_bitlen( m ); /* one past the (zero-based) most significant bit */
      while( i-- > 0 )
      {
!         b = mbedtls_mpi_get_bit( m, i );
          /*
           *  if (b) R = 2R + P else R = 2R,
           * which is:
--- 1580,1586 ----
      i = mbedtls_mpi_bitlen( m ); /* one past the (zero-based) most significant bit */
      while( i-- > 0 )
      {
!         b = (unsigned char)mbedtls_mpi_get_bit( m, i );
          /*
           *  if (b) R = 2R + P else R = 2R,
           * which is:
diff -up D:\work\src\crypto\mbedtls-2.3.0\library/md.c D:\work\src\mbedtls-2.3.0\library/md.c
*** D:\work\src\crypto\mbedtls-2.3.0\library/md.c   Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library/md.c  Tue Aug 30 18:05:03 2016
*************** unsigned char mbedtls_md_get_size( const
*** 449,455 ****
      if( md_info == NULL )
          return( 0 );
  
!     return md_info->size;
  }
  
  mbedtls_md_type_t mbedtls_md_get_type( const mbedtls_md_info_t *md_info )
--- 449,455 ----
      if( md_info == NULL )
          return( 0 );
  
!     return (unsigned char)md_info->size;
  }
  
  mbedtls_md_type_t mbedtls_md_get_type( const mbedtls_md_info_t *md_info )
diff -up D:\work\src\crypto\mbedtls-2.3.0\library/rsa.c D:\work\src\mbedtls-2.3.0\library/rsa.c
*** D:\work\src\crypto\mbedtls-2.3.0\library/rsa.c  Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library/rsa.c Tue Aug 30 18:06:17 2016
*************** int mbedtls_rsa_rsassa_pkcs1_v15_sign( m
*** 1096,1102 ****
          *p++ = MBEDTLS_ASN1_NULL;
          *p++ = 0x00;
          *p++ = MBEDTLS_ASN1_OCTET_STRING;
!         *p++ = hashlen;
          memcpy( p, hash, hashlen );
      }
  
--- 1096,1102 ----
          *p++ = MBEDTLS_ASN1_NULL;
          *p++ = 0x00;
          *p++ = MBEDTLS_ASN1_OCTET_STRING;
!         *p++ = (unsigned char)hashlen;
          memcpy( p, hash, hashlen );
      }
  
</pre>

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-947
