### ISSUE TITLE
move ssl_preset_suiteb_hashes, ssl_preset_suiteb_ciphersuites, ssl_preset_default_hashes to .rodata

### ISSUE THREAD

**Issue by Xeenych** [ARMmbed/mbedtls#5891]
### Suggested enhancement
move 
* ssl_preset_suiteb_hashes, 
* ssl_preset_suiteb_ciphersuites, 
* ssl_preset_default_hashes 
* ssl_preset_suiteb_curves

to .rodata by declaring them with const
see: https://github.com/Mbed-TLS/mbedtls/blob/5e03d9e601a7ab6fbd0521d9c58dab41f40ae65f/library/ssl_tls.c#L4029

### Justification
This will slightly reduce ram usage.

Mbed TLS needs this because SRAM is expensive

**Comment by ronald-cron-arm** [comment]
Thanks for pointing out that. This seems a good idea. Would you mind creating a PR doing that change ?

**Comment by Xeenych** [comment]
Here:
https://github.com/Mbed-TLS/mbedtls/pull/5894
