### ISSUE TITLE
x509_crt.c does not respect alternate threading implementations

### ISSUE THREAD

**Issue by Thuffir** [ARMmbed/mbedtls#59]
The mutex calls in ```x509_crt.c``` are ```#ifdef```-ed against ```POLARSSL_THREADING_PTHREAD``` so they won't respect any alternate threading implementation. I think they should be depending on ```POLARSSL_THREADING_C```.

**Comment by mpg** [comment]
This is fixed in the 2.0 branch (currently internal, hopefully release in the next few weeks).
