### ISSUE TITLE
handle leak in x509_crt.c

### ISSUE THREAD

**Issue by redplait** [ARMmbed/mbedtls#590]
under windows there is handles leak in function mbedtls_x509_crt_parse_path - hFind going out of scope leaks the handle on line 1146

simple patch:

<pre>
*** D:\work\src\crypto\mbedtls-2.3.0\library\x509_crt.c Mon Jun 27 21:50:36 2016
--- D:\work\src\mbedtls-2.3.0\library\x509_crt.c        Thu Sep 01 16:03:21 2016
*************** int mbedtls_x509_crt_parse_path( mbedtls
*** 1144,1150 ****
--- 1144,1153 ----
                                       p, (int) len - 1,
                                       NULL, NULL );
          if( w_ret == 0 )
+         {
+             FindClose( hFind );
              return( MBEDTLS_ERR_X509_FILE_IO_ERROR );
+         }

          w_ret = mbedtls_x509_crt_parse_file( chain, filename );
          if( w_ret < 0 )
</pre>

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-945

**Comment by sbutcher-arm** [comment]
Fixed in merged PR's #738, #751, and #752. Issue can now be closed.
