### ISSUE TITLE
OpenBSD current

### ISSUE THREAD

**Issue by pjbakker** [ARMmbed/mbedtls#591]
Reported:

I have a big issue on OpenBSD current with hiawatha and TLS. In OpenBSD 6.0 stable (new) all is great.

After booting OpenBSD current, only new Kernel, hiawatha with TLS is unusable.

OpenBSD is doing something in ip stack and with RELRO:

"The system now uses the RELRO design ("read-only after relocation") to
lay out executables and libraries such that they use fewer mappings and
more of the initial data can be protected as read-only. Unlike other
OSes, this applies to all dynamic executables and libraries by default,
as well as to static PIE executables."

I can't say what is the reason.

I tried to build hiawatha with debug, but make is broken :/

SCP is also encrypted and is working fine. As I see also imaps is working fine. Only TLS in hiawatha is unusable.

Hugo also has no idea.

I hope you have a chance to fix?

#### Stable Kernel: ####

all is great

uname -a
OpenBSD X.Y.Z 6.0 GENERIC.MP#0 amd64

**** SCP ****

time scp -P 62222 X@Y:trans.tgz .
trans.tgz
                     100%   12MB 164.1KB/s   01:12

real	1m15.705s
user	0m0.169s
sys	0m0.275s

**** With TLS ****

time wget https://X/trans.tgz
--2016-09-01 18:06:41--  https://X/trans.tgz
Auflösen des Hostnamens »X
(X)« … Y
Verbindungsaufbau zu X
(X)|Y|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 12095437 (12M) [application/x-tar]
Wird in »»trans.tgz«« gespeichert.

trans.tgz 100%[=======================================================>]  11,53M 2,36MB/s    in 9,1s

2016-09-01 18:06:51 (1,27 MB/s) - »»trans.tgz«« gespeichert
[12095437/12095437]

real	0m10.055s
user	0m0.097s
sys	0m0.183s

**** Without TLS ****

time wget http://X/trans.tgz
URL transformed to HTTPS due to an HSTS policy
--2016-09-01 18:07:28--  https://X/trans.tgz
Auflösen des Hostnamens »X
(X)« … Y
Verbindungsaufbau zu X
(X)|Y3|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 12095437 (12M) [application/x-tar]
Wird in »»trans.tgz.2«« gespeichert.

trans.tgz.2
100%[=======================================================>]  11,53M
2,78MB/s    in 5,0s

2016-09-01 18:07:33 (2,32 MB/s) - »»trans.tgz.2«« gespeichert
[12095437/12095437]

real	0m5.317s
user	0m0.097s
sys	0m0.178s

#### Current Kernel: ####

TLS sucks.

**** SCP ****

time scp -P 62222 X@Y:trans.tgz .
trans.tgz
                     100%   12MB 787.5KB/s   00:15

real	0m17.433s
user	0m0.144s
sys	0m0.188s

**** With TLS ****

Broke up after 22 minutes.

time wget https://X/trans.tgz
--2016-09-01 18:25:35--  https://X/trans.tgz
Auflösen des Hostnamens »X
(X)« … Y
Verbindungsaufbau zu X
(X)|Y|:443 …
fehlgeschlagen: Operation timed out.
Verbindungsaufbau zu X
(X)Y|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 12095437 (12M) [application/x-tar]
Wird in »»trans.tgz«« gespeichert.

trans.tgz                        32%[=================>
                    ]   3,77M  3,00KB/s    eta 44m 43s^C

real	22m18.335s
user	0m0.114s
sys	0m0.203s

**** Without TLS ****

 wget http://Z/trans.tgz
--2016-09-01 18:57:30--  http://Z/trans.tgz
Auflösen des Hostnamens »Z (Z)« … A
Verbindungsaufbau zu Z
(Z)|A|:80 … fehlgeschlagen:
Operation timed out.
Verbindungsaufbau zu Z
(Z)|A|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 12095437 (12M) [application/x-tar]
Wird in »»trans.tgz.1«« gespeichert.

trans.tgz.1
100%[====================================================>]  11,53M
490KB/s    in 59s

2016-09-01 18:58:59 (200 KB/s) - »»trans.tgz.1«« gespeichert
[12095437/12095437]
--

**Comment by hsleisink** [comment]
Hi Paul. Heiko just sent me an e-mail in which he stated that all is working fine now. It seemed to be a glitch in the OpenBSD matrix. This issue can be closed.

**Comment by pjbakker** [comment]
Thanks for reporting this back.
