### ISSUE TITLE
Error:-17168 :: MBEDTLS_ERR_RSA_PRIVATE_FAILED

### ISSUE THREAD

**Issue by chennakeshavaSoC** [ARMmbed/mbedtls#594]
Hi,
We are using mbedTLS in our platform while connecting to AWS Cloud we are seeing error "-17168" (-0x4300-0x000A) RSA error.
[MBEDTLS_ERR_RSA_PRIVATE_FAILED + MBEDTLS_ERR_MPI_NEGATIVE_VALUE]

We are storing the certificates in const buffers and accessing them.

We are seeing this issue very often when we are power cycle the hardware (remove the power supply, and connect it), and rarely during the reset.

Please suggest me how to resolve this issue.

**Comment by pjbakker** [comment]
This error alone does not give enough information to determine where the error occurs.
The error itself indicates something is wrong (memory wise most likely.

Can you let us know / verify:

* Does this also occur when connecting to other servers? (Is it AWS Cloud related?)
* Can you provide a debug log (debug_level=5) to show the context of when the error happens?
* What version of mbed TLS are you using?
* Do you have  multi-threaded operation?

**Comment by chennakeshavaSoC** [comment]
Our application is a multi-threaded one, latest version of mbedTLS we are using.
For testing I am starting other tasks after ssl success, we are not seeing this error. What is the dynamic  memory requirement during ssl connection?

mbedtls_ssl_handshake() is taking longer time to connect to server, its around 10 sec. No other tasks are running during this. How can we reduce this time.

**Comment by pjbakker** [comment]
Can you provide a debug log (debug_level=5) to show the context of when the error happens?

**Comment by chennakeshavaSoC** [comment]
Hi pjbakker,

After allocating sufficient memory, the issue got resolved for us.
Do you have any timing statistics for the "mbedtls_ssl_handshake()" for connecting to a secure server (aws.amazon.com), how much time it is really taking.

For us it is taking around 15 seconds, but for a battery powered sleepy node it is considerably long. Is it possible to reduce this time by any means?

**Comment by pjbakker** [comment]
That's good to hear.

Timing statistics are dependent on a number of factors, such as Ciphersuite / Public Key mechanism used. Size of public key. mbed TLS compile time configuration. And of course on the performance of the relevant MCU.

So there is no generic answer.

Reducing time often requires: more memory consumption, smaller key sizes, or smarter ciphersuite choices.

I'll close this issue. For your question on performance I suggest you look into our KB articles, or ask on the discussion forum (while providing some additional information on your situation).

**Comment by NOA-Vernon** [comment]
Hi,
  we are using mbedTLS in our platform while connecting to AWS Cloud we are seeing error "-0x7200" 
#define MBEDTLS_ERR_SSL_INVALID_RECORD                    -0x7200  /**< An invalid SSL record was received. */
followiing is the debug log:
ssl_tls.c:6313: => handshake
ssl_cli.c:3264: client state: 0
ssl_tls.c:2429: => flush output
ssl_tls.c:2441: <= flush output
ssl_cli.c:3264: client state: 1
ssl_tls.c:2429: => flush output
ssl_tls.c:2441: <= flush output
ssl_cli.c:0712: => write client hello
ssl_cli.c:0750: client hello, max version: [3:3]
ssl_cli.c:0759: dumping 'client hello, random bytes' (32 bytes)
ssl_cli.c:0759: 0000:  13 82 ef 31 b5 7d d7 d3 8a db 13 49 3b cb c0 32  ...1.}.....I;..2
ssl_cli.c:0759: 0010:  fb 32 93 27 0a a8 01 55 36 ae 6c bd ee ca 08 0a  .2.'...U6.l.....
ssl_cli.c:0812: client hello, session id len.: 0
ssl_cli.c:0813: dumping 'client hello, session id' (0 bytes)
ssl_cli.c:0880: client hello, add ciphersuite: 003d
ssl_cli.c:0880: client hello, add ciphersuite: 0035
ssl_cli.c:0880: client hello, add ciphersuite: 003c
ssl_cli.c:0880: client hello, add ciphersuite: 002f
ssl_cli.c:0880: client hello, add ciphersuite: 00b7
ssl_cli.c:0880: client hello, add ciphersuite: 0095
ssl_cli.c:0880: client hello, add ciphersuite: 00b6
ssl_cli.c:0880: client hello, add ciphersuite: 0094
ssl_cli.c:0913: client hello, got 9 ciphersuites
ssl_cli.c:0944: client hello, compress len.: 1
ssl_cli.c:0946: client hello, compress alg.: 0
ssl_cli.c:0072: client hello, adding server name extension: a2slq08v8uk221.iot.us-east-1.amazonaws.com
ssl_cli.c:0078: buffer too small
ssl_cli.c:0178: client hello, adding signature_algorithms extension
ssl_cli.c:0192: buffer too small
ssl_cli.c:1018: client hello, total extension length: 0
ssl_tls.c:2714: => write record
ssl_tls.c:2849: output record: msgtype = 22, version = [3:1], msglen = 61
ssl_tls.c:2852: dumping 'output record sent to network' (66 bytes)
ssl_tls.c:2852: 0000:  16 03 01 00 3d 01 00 00 39 03 03 13 82 ef 31 b5  ....=...9.....1.
ssl_tls.c:2852: 0010:  7d d7 d3 8a db 13 49 3b cb c0 32 fb 32 93 27 0a  }.....I;..2.2.'.
ssl_tls.c:2852: 0020:  a8 01 55 36 ae 6c bd ee ca 08 0a 00 00 12 00 3d  ..U6.l.........=
ssl_tls.c:2852: 0030:  00 35 00 3c 00 2f 00 b7 00 95 00 b6 00 94 00 ff  .5.<./..........
ssl_tls.c:2852: 0040:  01 00                                            ..
ssl_tls.c:2429: => flush output
ssl_tls.c:2448: message length: 66, out_left: 66
ssl_tls.c:2454: ssl->f_send() returned 66 (-0xffffffbe)
ssl_tls.c:2473: <= flush output
ssl_tls.c:2861: <= write record
ssl_cli.c:1044: <= write client hello
ssl_cli.c:3264: client state: 2
ssl_tls.c:2429: => flush output
ssl_tls.c:2441: <= flush output
ssl_cli.c:1396: => parse server hello
ssl_tls.c:3739: => read record
ssl_tls.c:2221: => fetch input
ssl_tls.c:2379: in_left: 0, nb_want: 5
ssl_tls.c:2403: in_left: 0, nb_want: 5
ssl_tls.c:2404: ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)
ssl_tls.c:2416: <= fetch input
ssl_tls.c:3486: dumping 'input record header' (5 bytes)
ssl_tls.c:3486: 0000:  16 03 03 0b e1                                   .....
ssl_tls.c:3495: input record: msgtype = 22, version = [3:3], msglen = 3041
ssl_tls.c:3532: bad message length
ssl_cli.c:1402: mbedtls_ssl_read_record() returned -29184 (-0x7200)
ssl_tls.c:6323: <= handshake

**Comment by johnnyodonnell** [comment]
I am getting the same error as @NOA-Vernon. I will open this in a separate issue
