### ISSUE TITLE
Sample applications report errors inconsistently

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#596]
The sample applications report errors and error numbers inconsistently, sometimes in decimal (such as in `programs/ssl/ssl_server2.c`) and sometimes in hex (such as in `programs/ssl_client2.c`). 

Errors should be reported consistently in hex, as that's how they're defined in the header files, and wherever possible, with an associated error message.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-974
