### ISSUE TITLE
mbedtls_gcm_finish parameter tag_len has implementation / documentation missmatch

### ISSUE THREAD

**Issue by cmiatpaar** [ARMmbed/mbedtls#602]
The Online documentation (https://tls.mbed.org/api/gcm_8h.html#a1fc3a11f761e37d515e013d8c8f8975f) of "mbedtls_gcm_finish" says "tag  	buffer for holding the tag (may be NULL if tag_len is 0)". If "mbedtls_gcm_finish" is called with a tag_len of 0 the value MBEDTLS_ERR_GCM_BAD_INPUT is returned. 

Tested with mbedtls-2.3.0-apache

**Comment by pjbakker** [comment]
Agreed this is not correct.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-972

**Comment by thomasknauth** [comment]
I've just been bitten by this too.

**Comment by sbutcher-arm** [comment]
This has now been fixed by PR #628. Backported to mbedtls-2.1 and mbedtls-1.3 also.
