### ISSUE TITLE
SSL handshake error - Bad input parameter to function

### ISSUE THREAD

**Issue by RafsanjaniRahman** [ARMmbed/mbedtls#621]
Anyone can pin point me what is the cause of the error. I'm using curl and mbedtls to download file from https url. Below is the verbose i print out from curl.

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* mbedTLS: Connecting to localhost:443
* mbedTLS: Set SSL version to TLS 1.1
* ssl_handshake returned - mbedTLS: (-0x7100) SSL - Bad input parameters to function
* Curl_http_done: called premature == 1
* Closing connection 0

**Comment by pjbakker** [comment]
The fact that the `ssl_handshake()` function returns 'Bad input parameter', seems to point to an incompatibility between the version of cURL and mbed TLS working together. Not necessarily an mbed TLS issue.

Are you using stable versions of cURL and the correct mbed TLS version? If so, I suggest you post an issue with cURL instead.

If you believe this is really an issue with mbed TLS, and not the way cURL is using mbed TLS, please feel free to re-open this issue with additional information.
