### ISSUE TITLE
Issue with PEM certificate parsing

### ISSUE THREAD

**Issue by tofmassilia** [ARMmbed/mbedtls#630]
In mbed TLS 2.3.0 there are an issue in programs x509_crt.c.
Through mbedtls_x509_crt_parse function, the certifcate format is set to MBEDTLS_X509_FORMAT_DER in case of PEM.

int mbedtls_x509_crt_parse( mbedtls_x509_crt *chain, const unsigned char *buf, size_t buflen )
{
    int success = 0, first_error = 0, total_failed = 0;
#if defined(MBEDTLS_PEM_PARSE_C)
    int buf_format = MBEDTLS_X509_FORMAT_DER;   <== To replace by MBEDTLS_X509_FORMAT_PEM
#endif
...

**Comment by jcowgill** [comment]
Why do you think there's a bug here? Do you have an example certificate which isn't parsed correctly?

**Comment by tofmassilia** [comment]
Sure!!!
You could use PEM certificate define into file certs.c

**Comment by jcowgill** [comment]
The certificate from certs.c parses fine for me. If it works for you only when you change `buf_format` then maybe your input certificate is malformed? It has to be `NULL` terminated.

**Comment by tofmassilia** [comment]
Hi James,

Thanks for your feedback.
I’ve investigate through my code; I discovered an issue with length parameter pass to “mbedtls_x509_crt_parse” function.
In fact, I provide length with strlen function instead of sizeof; then the length was the length of the 1st line of PEM because each line are ending with \0.
Could you close this issuer submission.
Sorry for wrong information ☹.

Another question:
Do you have an example code for SSL client through general purpose MCU like STM32 with IP stack like LWIP ?


Regards.


[cid:image001.png@01D2196F.6B606770]

Christophe DELAUNAY | Tel: +33 442688279
MMS-SMD | Application engineer

STMicroelectronics SAS
190 Avenue Celestin Coq
ZI Rousset Peynier
13106 Rousset Cedex
FRANCE

ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world<http://twitter.com/#!/ST_World>

This communication is confidential and intended solely for the addressee(s). If you are not the intended
recipient, you should not review, retain, copy or distribute the e-mail itself or the information it contains.
In such case, we kindly request you notify the sender by replying to this transmission and delete the
message without disclosing it. Thank you!
