### ISSUE TITLE
Coding style change: pull the switch

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#6359]
The goal of this task is to change to the [new coding style](https://github.com/Mbed-TLS/mbedtls/issues/6343). This means:

* Change the [`all.sh` component](https://github.com/Mbed-TLS/mbedtls/issues/6354) so that deviations are now failures.
* Apply the reformatting to `development` and `mbedtls-2.28`.

Preview branches with the new code style are available:

* [`features/new-code-style/development`](https://github.com/Mbed-TLS/mbedtls/tree/features/new-code-style/development)
* [`features/new-code-style/mbedtls-2.28`](https://github.com/Mbed-TLS/mbedtls/tree/features/new-code-style/mbedtls-2.28)

The preview branches are updated from time to time. This is manually triggered but done [using an automatic script](https://github.com/Mbed-TLS/mbedtls/pull/6758). “Pulling the switch” means that these preview branches will become the new official branches (via pull requests).

Once the switch has been pulled, all work in progress will need to be restyled (otherwise almost anything that touches C code will have merge conflicts). We will provide a [script to rewrite branches commit by commit](https://github.com/Mbed-TLS/mbedtls/issues/6353).

For open pull requests that are undergoing review, synchronize with the reviewers to decide when to do the rewriting.

We will pull the switch in early January 2023.

**Comment by davidhorstmann-arm** [comment]
Switched in #6907, #6908
