### ISSUE TITLE
CLANG analyzer

### ISSUE THREAD

**Issue by moe123** [ARMmbed/mbedtls#645]
mbedtls-2.3.0/library/rsa.c:839:9: warning: Assigned value is garbage or undefined
    bad |= _p++; /_ First byte must be 0 */
        ^  ~~~~
mbedtls-2.3.0/library/rsa.c:1252:16: warning: The left operand of '>>' is a garbage value
    if( buf[0] >> ( 8 - siglen \* 8 + msb ) )
        ~~~~~~ ^
mbedtls-2.3.0/library/rsa.c:1365:14: warning: The left operand of '!=' is a garbage value
    if( *p++ != 0 || *p++ != MBEDTLS_RSA_SIGN )
        ~~~~ ^

Apple LLVM version 7.3.0 (clang-703.0.31)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1031

**Comment by moe123** [comment]
@hello, may I close it?

**Comment by moe123** [comment]
@hello gents don't want to tease (still there's always room for brits 8-) ) sadly 2.4.0 does not really fix it, nice try! ; for those who would ask again : not that's not a false positive match ... (some animal asked ...) .

**Comment by sbutcher-arm** [comment]
Sorry, @moe123, but why did you close this issue?

**Comment by moe123** [comment]
2.4.0 changed few things hence it needs an update.
