### ISSUE TITLE
Error code for running out of memory

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/mbedtls#663]
When mbedtls_ssl_handshake() fails due to a dynamic memory failure the error code `-0x2700` is returned. This corresponds to `X509 - Certificate verification failed, e.g. CRL, CA or signature check failed`. Having an error message that indicates a dynamic memory failure would make it much easier to determine the cause of an operation failure.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1067
