### ISSUE TITLE
Auto-detect and configure minimum SSL version available.

### ISSUE THREAD

**Issue by MarcoLizza** [ARMmbed/mbedtls#664]
Running some test with a SSL3 server, I found that even by defining the `MBEDTLS_SSL_PROTO_SSL3` macro, the library doesn't detect automatically this version as _minimum available_. I suspect that  `ssl_tls.c` lines `7286` and `7287`, that is

```
conf->min_major_ver = MBEDTLS_SSL_MAJOR_VERSION_3;
conf->min_minor_ver = MBEDTLS_SSL_MINOR_VERSION_1; /* TLS 1.0 */
```

should be changed to

```
conf->min_major_ver = MBEDTLS_SSL_MIN_MAJOR_VERSION;
conf->min_minor_ver = MBEDTLS_SSL_MIN_MINOR_VERSION;
```

Am I correct? Or should one explicitly call `mbedtls_ssl_conf_min_version()`?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1072
