### ISSUE TITLE
Consider dropping generic elliptic curve support

### ISSUE THREAD

**Issue by DemiMarie** [ARMmbed/mbedtls#6647]
### Suggested enhancement

Mbed TLS should drop support for arbitrary elliptic curves, at least in the default build.  Explicitly-specified curves that are actually aliases for known named curves would continue to be supported (by being translated to said named curve), as e.g. the biometric passport standard uses them.  This support could be turn on or off at runtime.

### Justification

Mbed TLS needs this because arbitrary elliptic curves are impossible to implement efficiently in constant-time, and many standards require the use of the named-curve form.

**Comment by DemiMarie** [comment]
Mbed TLS at the very least contains code for parsing AlgorithmIdentifiers that use explicitly specified curve parameters.  I am not sure if such AlgorithmIdentifiers can be used to successfully verify a signature, though.

**Comment by davidhorstmann-arm** [comment]
Since we don't support arbitrary curves in practice, I'm going to close this as a non-issue. Feel free to open a follow-up issues related to other pkparse improvements if needed.
