### ISSUE TITLE
NULL entropy check ignores MBEDTLS_CONFIG_FILE

### ISSUE THREAD

**Issue by jethrogb** [ARMmbed/mbedtls#669]
CMakeLists.txt runs scripts/config.pl to check for `MBEDTLS_TEST_NULL_ENTROPY`. However, it always looks at `include/mbedtls/config.h` and ignores the `MBEDTLS_CONFIG_FILE` environment variable.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1076
