### ISSUE TITLE
Inconsistent types for key_bitlen in mbedtls_cipher_setkey() API

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#671]
The parameter `key_bitlen` of the `mbedtls_cipher_setkey()` function is of type `int`, however for sizes most of the library uses `size_t` to hold these integer values.

**Comment by andresag01** [comment]
@sbutcher-arm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1080
