### ISSUE TITLE
macro redefinition warning: compat-1.3.h #define ssl_set_bio

### ISSUE THREAD

**Issue by omlib-lin** [ARMmbed/mbedtls#673]
#define ssl_set_bio mbedtls_ssl_set_bio
#define ssl_set_bio mbedtls_ssl_set_bio_timeout

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1079

**Comment by andresag01** [comment]
Thanks for reporting. You are correct, `ssl_set_bio` is being redefined to a symbol that is no longer present in the library (`ssl_set_bio_timeout` was was removed in mbed TLS 1.4, https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog#L492). We will review this and make an appropriate fix.

**Comment by sbutcher-arm** [comment]
Fix has been merged on `development`, `mbedtls-2.4`, and `mbedtls-2.1` branches. Issue can be closed.
