### ISSUE TITLE
gnuk improvment

### ISSUE THREAD

**Issue by bastien-roucaries** [ARMmbed/mbedtls#682]
Could you get a glimpse at https://anonscm.debian.org/cgit/gnuk/gnuk/gnuk.git/tree/polarssl and see if some improvment could be merged ?

Thank you

**Comment by RonEld** [comment]
According to https://anonscm.debian.org/ the service is disconnected, and moved to gitlab.
Since this question is outdated, it will be closed.

If this question is still valid, please reopen, with an updated link.
