### ISSUE TITLE
pointless integer comparisons 

### ISSUE THREAD

**Issue by rahmanih** [ARMmbed/mbedtls#683]
Hi,
When compiling the mbedTLS on stm32 using the IAR compiler, I'm getting the following warnings:
<code>Warning[Pa084]: pointless integer comparison, the result is always false  mbedTLS\library\pkcs5.c  234
Warning[Pa084]: pointless integer comparison, the result is always true  mbedTLS\library\asn1write.c  86</code>

regards
Haithem.

**Comment by sbutcher-arm** [comment]
Checking the code, those checks look applicable only to 64 bit systems, so probably need to be excluded in 32 bit builds.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1083

**Comment by rahmanih** [comment]
Hi,

this fix hasn't been merged yet, any reason for that?

regards
Haithem.

**Comment by sbutcher-arm** [comment]
PR's #1727 and #1646 for `development`, #1728 and #1646 for `mbedtls-2.7` and #1656 for `mbedtls-2.1` have been merged, so this issue can now be closed.
