### ISSUE TITLE
Building tests on Windows requires elevated environment

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#686]
When building the tests for Visual Studio, executing cmake to generate the necessary Visual Studio project files requires an elevated command prompt because of the use of `mklink` to create a hard link.

If this is changed to a junction in `tests\CMakeLists.txt`. e.g. `mklink /d /j` this shouldn't be necessary any longer.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1097

**Comment by redtangent** [comment]
Fixed by PR #688 on development and PR #689 on mbed TLS 2.1.

Backport for mbed TLS 1.3 not necessary as the `tests` subdirectory is not built on 1.3.
