### ISSUE TITLE
Integration with event loop libraries

### ISSUE THREAD

**Issue by nuuman** [ARMmbed/mbedtls#690]
libevent, libuv, etc.

I understand there are BIO functions in mbedtls. Can these be used to integrate with asynchronous eventloop libraries like libuv (which is used in node.js) ?

**Comment by NWilson** [comment]
Yes. mbedTLS can be used to integrate with any I/O framework of your choosing. mbedTLS is not tied to any I/O framework, and can be used in a completely non-blocking manner. You simply provide a read and write callback, which consume data from any stream/buffer/event queue of your choosing. The read callback supports returning "no more data" and the write callback allows applying backpressure. When you receive readability and writability notifications from your I/O framework, you simply call mbedtls_ssl_read/write to prompt it to consume/generate fresh data.

It's pretty much an ideal API, from my point of view as a user. At my company, we use mbedTLS in desktop & mobile applications, with a cross-platform event loop that runs on a wide variety of frameworks (WinSock, CoreFoundation, unix select, Android NDK Looper, etc) - each of these is able to feed our cross-platform I/O streams, and those streams are used to feed mbedTLS without any platform-specific code needed. I found it pretty painless to integrate mbedTLS with our streams, including backpressure and lazy buffering on read/write; hopefully libuv shouldn't either present a mismatch with the mbedTLS model.

**Comment by sbutcher-arm** [comment]
This is just a question, and hopefully @NWilson's answer is sufficient, so I'll close this issue.

For further questions, I really recommend posting to the mbed TLS forum [here](https://tls.mbed.org/discussions), as wider number of people are more likely to see the question and answer it.
