### ISSUE TITLE
Incorrect leap year handling in X.509 validation

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#694]
The function `x509_date_is_valid()` in the file `library/x509.c`, is not validating leap years correctly, as it's not handling 100 year nor 400 year intervals correctly.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1100

**Comment by sbutcher-arm** [comment]
Fix in PR #702 has been merged with `development` and backported to `mbedtls-2.1` and `mbedtls-1.3`.

Issue can now be closed.
