### ISSUE TITLE
Wrong preprocessor condition used in `x509_crt.c` for threading

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#696]
In file `x509_crt.c`, line 1172, function `mbedtls_x509_crt_parse_path()`use of a mutex is protected by  the preprocessor condition `#if defined(MBEDTLS_THREADING_PTHREAD)`. All use of concurrency primitives should be protected by `#if defined(MBEDTLS_THREADING_C)` as the library cannot assume they will always be implemented by pthread support.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1102

**Comment by sbutcher-arm** [comment]
Fixed in PR's #739, #753 and #754, which have now been merged. This issue can be closed.
