### ISSUE TITLE
Use gmtime_r

### ISSUE THREAD

**Issue by NWilson** [ARMmbed/mbedtls#704]
mbedTLS uses `gmtime`, which is not thread-safe. It tries to fix things up by protecting its use with a mutex, but the mutex provides only an illusion of safety. The problem with `gmtime` is that other threads in the application could be calling it at the same time, not necessarily inside mbedTLS code.

This is a very improbable bug, but in the worst case it could enable a certificate validity check to be bypassed.

mbedTLS should use `gmtime_r`, which is safe, and is present on a wide variety of non-Windows platforms. We use it in our codebase, so I can confirm it's present on our supported platforms (Linux, Mac, Solaris, HP-UX, AIX, FreeBSD - any SUSv2 platform). There may be embedded/low-level platforms you support where `gmtime_r` is not provided.

I can submit a PR - but it's not too urgent for me. Also, you'd have to provide guidance on how you would prefer to detect presence of support for `gmtime_r` (detecting it in the CMake script would be fine, but then what about people not using CMake, etc).

**Comment by sbutcher-arm** [comment]
Hi @NWilson. Nice to hear from you again!

I hadn't appreciated there was an issue here, and I think we would gratefully accept a PR in this area. 

My suggestion - and I'm open to other ideas - would be to make a platform abstraction function of `mbedtls_gmtime_r()` which maps to `gmtime_r` to allow the function to be changed more easily, and change the call to `gmtime()` to one of `mbedtls_gmtime_r()`.

I had planned already to abstract the function, (and as ever, hadn't gotten around to it), but not to make the change to `gmtime_r()`.

If the function is as widely adopted as you suggest, I think it's acceptable to make it the default library function to be used. For Windows, `mbedtls_gmtime_r()` can call a glue function that actually calls `gmtime()` or something similar.

**Comment by NWilson** [comment]
Great, since gmtime is only called from mbedtls_time, I think the existing platform time abstraction should be enough (I seem to remember there's a way to swap in your own mbedtls_time? - I'll add it if not). I'll make a PR changing mbedtls_time to use gmtime_r by default - and non-Windows platforms that don't have gmtime_r will have to provide their own mbedtls_time implementation (tough love).

**Comment by sbutcher-arm** [comment]
This issue has now been resolved with the merge of PR #1198 and #1927.
