### ISSUE TITLE
Not possible to force a 32 bit only build without code changes

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#708]
The available configurations in `config.h` combined with the platform symbols do not allow a 32-bit only build. That is a build that has only 32-bit integers and without `MBEDTLS_HAVE_UDBL` defined.

If `MBEDTLS_HAVE_UDBL` is defined, on most platforms this will build, but can create a dependency to additional library functions, which may not be available on all bare metal platforms.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1112

**Comment by iduhetonas** [comment]
Specifically seeing this issue on an ARM Cortex-M3, which causes an `Undefined instruction` fault on an attempt to divide two uint64_t primitives, which are only defined with `MBEDTLS_HAVE_UDBL`.

**Comment by dp-arm** [comment]
Is there an update on this issue? We are about to merge some code in ARM TF that seems to trigger this case.  Would be nice to see it resolved.

**Comment by iduhetonas** [comment]
Any progress on this issue? I see that @gilles-peskine-arm committed a fix.

**Comment by gilles-peskine-arm** [comment]
Hi @iduhetonas, PR #949  fixes the issue, pending review. I'm afraid we're still backlogged on review, we're actively working on improving this.

**Comment by andresag01** [comment]
PR https://github.com/ARMmbed/mbedtls/pull/893 fixes this issue as it includes all changes from https://github.com/ARMmbed/mbedtls/pull/949.

**Comment by sbutcher-arm** [comment]
Merged PR #893 which addresses the issue so this can now be closed.
