### ISSUE TITLE
GCM initialisation vector length

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#716]
mbed TLS does not check if the initialisation vector length is zero (which is an invalid value).

Found by roberto, and reported on [the mbed TLS forum](https://tls.mbed.org/discussions/bug-report-issues/check-on-iv-lenght-of-gcm).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1118

**Comment by sbutcher-arm** [comment]
Merged PR's, #727, #790, and #793. Issue is resolved and can be closed.
