### ISSUE TITLE
fcntl can fail -> Not checked in net_would_block

### ISSUE THREAD

**Issue by cmorty** [ARMmbed/mbedtls#733]
fctntl in [net_would_block] might fail. In that case the -1 will not cause the test to fail, but errno will be overwritten. This is unlikely on Linux, but might happen on semi-POSIX-OS like eCos.

[net_would_block]: https://github.com/ARMmbed/mbedtls/blob/development/library/net_sockets.c#L275

**Comment by sbutcher-arm** [comment]
Good point! We'll look into it. Thanks!

**Comment by adbridge** [comment]
ARM Internal Ref: IOTSSL-1145

**Comment by hanno-arm** [comment]
Fixed through #895.
