### ISSUE TITLE
mbedtls_x509_crt_parse_file() return value is different in 2.3.x than 2.4.x

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#734]
I am testing an upgrade to mbedtls-2.4.x (2.4.0 & 2.4.1) and found that my code is failing here:

```
    mbedtls_x509_crt_init(&ctx->ca_cert);
    ret = mbedtls_x509_crt_parse_file(&ctx->ca_cert, ca_file);
    if (ret != 0) {
        char tmp[1024];
        mbedtls_strerror(ret, tmp, 1024);
        flb_error("[TLS] Invalid CA file: %s | %s", ca_file, tmp);
        goto error;
    }
```

the error is:

```
[TLS] Invalid CA file: /etc/ssl/certs/ca-certificates.crt | UNKNOWN ERROR CODE (0001)
```

if I use mbedtls-2.3 parsing /etc/ssl/certs/ca-certificates.crt works just fine, but with 2.4 I got a different value (UNKNOWN ERROR CODE). 

would you please advice how to fix it ?

**Comment by edsiper** [comment]
checking the mbedtls examples I found:

- cert_write.c: it checks return value of mbedtls_x509_crt_parse_file() != 0
- cert_app.c:  it checks return value of __mbedtls_x509_crt_parse_file() < 0__
- cert_write.c: it checks return value of mbedtls_x509_crt_parse_file() != 0

what's the proper way to validate ?

**Comment by RonEld** [comment]
Hi Eduardo,

As mentioned in [`include/mbedtls/error.h`](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/error.h#L31):

`Currently we try to keep all error codes within the negative space of 16 bits signed integers to support all platforms (-0x0001 - -0x7FFF).`

Therefore, only negative values are considered errors.

The [documentation](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/x509_crt.h#L207) for ` mbedtls_x509_crt_parse_file()` says that this function is "permissive", so it may return a positive value whenever some certificates can be parsed but others cannot. If this is the case, the positive value corresponds to the number of failed certificates.
 
As for the examples you showed, it is very dependent on the usage of `mbedtls_x509_crt_parse_file()`. For example, on `cert_write.c`, we don't want any failures in the issuer certificate chain, hence we check for any value different from `0`. On `cert_app.c`, the application parses the CA certificate chain, and it is possible that it will return failed certificates along the chain.

Regards,  
mbed TLS Team Member  
Ron

**Comment by edsiper** [comment]
Thanks for the explanation!
