### ISSUE TITLE
2.3.0 Not Building on Win7Pro-VS2010

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#742]
mirrored from https://tls.mbed.org/discussions/platform-specific/2-3-0-not-building-on-win7pro-vs2010
reported by Steve Valliere
I just discovered mbedtls today and downloaded the latest apache licensed build from the web site. It extracted to a folder named mdebtls-2.3.0. There are at least two issues:

When I loaded the solution (.sln) file, there was an error reported because the project ecdh_curve25519.vcxproj could not be found. I have verified that there is a ecdh_curve25519.c file in the ..\programs folder, so I'm not sure why there is a missing project.

When I tried to build the solution as it opened, I got many error messages about things that appear to be caused by all projects sharing a single output folder, yet using the same name for some of the files (like vc100.pdb and CL.read.1.tlog which are most of the error messages).

Has anyone actually built this release with VS2010? On Windows 7 Pro? If so, where is the missing project and what could I possibly have wrong?

FYI, I've been using VS2010 since it was released and just about every version of Microsoft C compiler/IDE since the mid-80s, so the environment isn't new to me, but I've never had anything get errors like these before and I don't know how to trigger them. Hopefully someone can and will help out. Thanks!

**Comment by adbridge** [comment]
ARM Internal Ref: IOTSSL-1147

**Comment by sbutcher-arm** [comment]
Issue has now been fixed in commits 08902ed and 6406e81, so can now be closed.

The fix has been merged with `development`, `mbedtls-2.4`, `mbedtls-2.1` and `mbedtls-1.3`.
