### ISSUE TITLE
ssl_get_ecdh_params_from_cert in ssl_srv.c may fail without checking return value

### ISSUE THREAD

**Issue by guidovranken** [ARMmbed/mbedtls#757]
```ssl_get_ecdh_params_from_cert``` calls ```mbedtls_ecdh_get_params``` which calls failable functions like ```mbedtls_mpi_*``` that, I think, can fail under memory shortage.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1168
