### ISSUE TITLE
Should the client validate server's P and G parameters in the Diffie-Hellman key exchange?

### ISSUE THREAD

**Issue by guidovranken** [ARMmbed/mbedtls#759]
So it appears that mbed TLS as a client doesn't verify that the server's P is prime.

To test you can change the original ```MBEDTLS_DHM_RFC5114_MODP_2048_P``` into 

```c
#define MBEDTLS_DHM_RFC5114_MODP_2048_P               \
    "AD107E1E9123A9D0D660FAA79559C51FA20D64E5683B9FD1" \
    "B54B1597B61D0A75E6FA141DF95A56DBAF9A3C407BA1DF15" \
    "EB3D688A309C180E1DE6B85A1274A0A66D3F8152AD6AC212" \
    "9037C9EDEFDA4DF8D91E8FEF55B7394B7AD5B7D0B6C12207" \
    "C9F98D11ED34DBF6C6BA0B2C8BBC27BE6A00E0A0B9C49708" \
    "B3BF8A317091883681286130BC8985DB1602E714415D9330" \
    "278273C7DE31EFDC7310F7121FD5A07415987D9ADC0A486D" \
    "CDF93ACC44328387315D75E198C641A480CD86A1B9E587E8" \
    "BE60E69CC928B2B9C52172E413042E9B23F10B0E16E79763" \
    "000000000000000000000000000000000000000000000000" \
    "00000000000000000000000000000001"
```

Which is not a prime number according to the Miller-Rabin test.

Compile and run ```programs/ssl/ssl_server2 ```with a DHE ciphersuite.

Connect to it with ```ssl_client2``` and they will communicate fine, despite P not being prime. P needs to be prime or else its security is weakened (https://crypto.stackexchange.com/questions/32415/how-does-a-non-prime-modulus-for-diffie-hellman-allow-for-a-backdoor). Since mbed TLS' objective is to provide a secure communications channel between itself and the peer, shouldn't it fail if it can reliably determine (through a primality test on P) during the handshake that the server is providing it with corrupt parameters? After all it's not just the server's discretion that is compromised but the client's as well. The article mentions ```socat``` which was breached after someone, possibly an adversary, added a non-prime P to its code. This goes to show that neither the client or the server need to be "malicious"; the server can be compromised without being aware of it, and it will affect both the client and the server.

Guido

**Comment by bmurray7** [comment]
The Miller-Rabin test should not be used to test the primality of a untrusted input, so we cannot Miller-Rabin to reliably determine if the server is providing corrupt parameters.

Note that it is possible to construct a number _n_ such that the Miller-Rabin test fails for about 75% of witnesses _a_.    Such numbers are of the form _n = (2p + 1)(4p + 1)_ where , where _(2p + 1)_ and _(4p + 1)_ are prime and _p_ is odd.  For details, see [this paper](http://dx.doi.org/10.1016/0304-3975(80)90007-9
).

**Comment by guidovranken** [comment]
Thanks! I wasn't aware of that.

Would you say that anything can be done to assert the primality of P within a reasonable span of time (say under a second) with a high degree of confidence? If a second is too long for the average user, the check could be optional using ifdefs or implemented as a separate function for users for whom the time/security trade-off is acceptable and preferred.

**Comment by sbutcher-arm** [comment]
TLS provides a secure connection between two endpoints which can authenticate each other through use of X.509 PKI.

If one side deliberately attempts to circumvent the communication by passing invalid data to the other end, whether malicious or not and has the result of undermining the security, then that is a weakness in the implementation, and is similar to any other bug that reveals the plaintext accidentally to a third party.

There's an interesting question about the motive of the far end, and whether backdoors are possible - but a backdoor assumes the compromise of one endpoint already - and beyond PKI we have nothing else within the scope of the protocol to trust that far end. It's about the trustworthiness of the endpoint - and that's outside of TLS and more a concern of TCG or similar.

As such - I don't see an immediate concern here.

@yanesca is working on a knowledgebase article along these lines.
