### ISSUE TITLE
vsnprintf call in debug.c should be wrapped platform_c

### ISSUE THREAD

**Issue by jorisa** [ARMmbed/mbedtls#760]
mbedtls_debug_print_msg calls vsnprintf directly (with some inline hotfixing for WIN32).
This should be wrapped by platform.c through mbedtls_vsnprintf like the other standard functions (printf, snprintf, etc).

**Comment by sbutcher-arm** [comment]
We are currently considering providing as part of the library our own optional implementation of `snprintf()` behind an appropriate platform abstraction.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1167

**Comment by mpg** [comment]
This has been fixed by https://github.com/ARMmbed/mbedtls/pull/1551 which is now merged, so closing this issue.
