### ISSUE TITLE
-0x7200 error

### ISSUE THREAD

**Issue by Astomat** [ARMmbed/mbedtls#764]
Hello, 
The TLS fails with -0x7200 error.
I have tried changing to different ciphers but it didn't help.

I see from the debug log on the server the following error:

ssl_tls.c:2460: |2| <= flush output
ssl_tls.c:2850: |2| <= write record
ssl_tls.c:4045: |2| <= send alert message
ssl_tls.c:3734: |1| mbedtls_ssl_read_record_layer() returned -29184 (-0x7200)
ssl_tls.c:6568: |1| mbedtls_ssl_read_record() returned -29184 (-0x7200)
ssl_tls.c:6897: |2| => write close notify
ssl_tls.c:4032: |2| => send alert message
ssl_tls.c:2701: |2| => write record
ssl_tls.c:1258: |2| => encrypt buf
ssl_tls.c:1269: |4| dumping 'before encrypt: output payload' (2 bytes)
ssl_tls.c:1269: |4| 0000:  01 00                                            ..

Thanks.

**Comment by jorisa** [comment]
I don't think this is an issue with the library.
You probably want to try here: https://tls.mbed.org/discussions

**Comment by Astomat** [comment]
The issue is that it happens only on MIPs

**Comment by sbutcher-arm** [comment]
If there's a bug, we'd be happy to look at it, but unfortunately there's not enough here to work on. We don't have access to MIPS hardware, and so we need the community to give us either a fix (if it's a real bug) or enough debug information to be able to study the problem.

Right now, it looks like a porting problem in your platform integration code, not an issue with mbed TLS, so I'm closing the issue.

Please feel to reopen the issue if you have more information for the mbed TLS team or community to work on..
