### ISSUE TITLE
How to validate chain of trust 

### ISSUE THREAD

**Issue by SuchatNg** [ARMmbed/mbedtls#766]
Hi guy,

I'm TLS/SSL beginner. I am using the ssl_client1 for my example project ported to STM32F10x. I would like to know "how to validate chain of trust. Which part of MbedTLS source code is related to chain validating.

Thank you very much.
Suchat Ngamchuen

**Comment by sbutcher-arm** [comment]
Hi @SuchatNg and thank you for the interest in mbed TLS!

Questions such as these are best posted to the mbed TLS forum which you can find [here](https://tls.mbed.org/discussions), where both the mbed TLS team and community can best help you, and you're likely to get a much quicker answer.

As this isn't actually a problem with mbed TLS, I'll close this issue, but I would urge you, that if you still need an answer, please do post this same question to the forum.
