### ISSUE TITLE
HMAC_DBRG vs pure SHA256 configuration

### ISSUE THREAD

**Issue by dbedev** [ARMmbed/mbedtls#770]
I am using mbed 2.1  with only SHA256 configured as MD.   I'm running into an issue with the HMAC_DBRG coupled to the entropy accumulator in this configuration.

Did some digging in the code and found that the entropy accumulator will only accept a maximum of 32 bytes per request when it does not use the SHA512 accumulator (MBEDTLS_ENTROPY_BLOCK_SIZE). 

However the hmac_dbrg will request 48 bytes on a _seed call when specifying SHA256 due to the following code
"
ctx->entropy_len = entropy_len * 3  / 2;  (32*3/2 == 48)
"

This will then trigger a entropy source failure triggering  seed of the HMAC_DBRG to fail. Not sure though what the correct way forward is for this. 
Is this an  invalid configuration and does one simply need SHA512 or is this bug in the hmac_dbrg?

**Comment by sbutcher-arm** [comment]
Thanks for the feedback. We'll look into this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1174

**Comment by gilles-peskine-arm** [comment]
It seems that we [independently rediscovered this](https://github.com/ARMmbed/mbed-crypto/issues/237) :frowning_face: This bug is fixed in Mbed TLS 2.7.9, Mbed TLS 2.16.3 and Mbed Crypto 2.0.0 :smile: Sorry it took so long!
