### ISSUE TITLE
cert_write does not handle EC signed certificates

### ISSUE THREAD

**Issue by dbedev** [ARMmbed/mbedtls#777]
The cert_write application fails on the public private key check when attempting create a certificate chain based on ECDSA.

Seems like it the cert_write application currently only checks public/private keys based on rsa.

```
    // Check if key and issuer certificate match
    //
    if( strlen( opt.issuer_crt ) )
    {
        if( !mbedtls_pk_can_do( &issuer_crt.pk, MBEDTLS_PK_RSA ) ||
            mbedtls_mpi_cmp_mpi( &mbedtls_pk_rsa( issuer_crt.pk )->N,
                         &mbedtls_pk_rsa( *issuer_key )->N ) != 0 ||
            mbedtls_mpi_cmp_mpi( &mbedtls_pk_rsa( issuer_crt.pk )->E,
                         &mbedtls_pk_rsa( *issuer_key )->E ) != 0 )
        {
            mbedtls_printf( " failed\n  !  issuer_key does not match issuer certificate\n\n" );
            ret = -1;
            goto exit;
        }
    }
```

Is it sufficient to use the mbedtls_pk_check_pair as below instead ?

```
    // Check if key and issuer certificate match
    //
    if( strlen( opt.issuer_crt ) )
    {
        if (0 != mbedtls_pk_check_pair(&issuer_crt.pk, issuer_key))
        {
            mbedtls_printf( " failed\n  !  issuer_key does not match issuer certificate\n\n" );
            ret = -1;
            goto exit;
        }
    }
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1201

**Comment by RonEld** [comment]
Hi dbedev,  
You are correct, using `mbedtls_pk_check_pair` is a better approach for verifying the issuer certificate and issuer key match, in this reference application.  
Regards,  
mbed TLS Team member
Ron

**Comment by MemAllox** [comment]
I had the same problem and this fix works like a charm for me, thanks! Please merge it into the master branch.

**Comment by dbedev** [comment]
has been working for me for over a year, any idea when this can be expected in a release ?

**Comment by sbutcher-arm** [comment]
PR #795 has now been merged, so this issue can be closed.
