### ISSUE TITLE
Name of mbedtls_ssl_safer_memcmp() is misleading

### ISSUE THREAD

**Issue by antonio-nino-diaz-arm** [ARMmbed/mbedtls#781]
The name of the function mbedtls_ssl_safer_memcmp() in include/mbedtls/ssl_internal.h is misleading. memcmp returns -1/0/1 depending on the inputs, but this implementation only returns 0 for equality, anything else for inequality.

It doesn't make sense to stick to the behaviour of memcmp because in this library it is only used to compare for equality, but it could be renamed to bcmp to prevent anybody from wrongly assuming this function can be used for anything else than to check for equality.

**Comment by sbutcher-arm** [comment]
The function does the comparison in constant time - that is why it's safer.

The name is possibly misleading if it encourages comparisons with `memcmp()`, but this is an internal function and not intended to be part of the functionality the library uses, so I'm not sure it's name should be too much of a problem, and given the amount of work we have outstanding, I'm not sure this is worth a bug.

@antonio-nino-diaz-arm - Do you have any strong feelings about this?

**Comment by antonio-nino-diaz-arm** [comment]
Not really, it's just a suggestion. As you say, it's an internal function. As long as it's always used to check for equality it'll be fine.

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! It's always welcome. If we had more bandwidth, we might fix this, but as it doesn't impact functionality and I don't think anyone is going to submit a PR, I'll close it.

You are welcome to submit a PR to change it to a different name of course! I would suggest as a new name `mbedtls_ssl_safe_byte_cmp()`.
