### ISSUE TITLE
programs/pkey/rsa_decrypt.c doesn't initialize rsa structure -- crash

### ISSUE THREAD

**Issue by guidovranken** [ARMmbed/mbedtls#788]
This file does not call ```mbedtls_rsa_init``` and thus may crash if ```mbedtls_rsa_free``` is called before the structure is fully initialized (for example if ```rsa_priv.txt``` is missing and it jumps to the ```exit``` label).

**Comment by sbutcher-arm** [comment]
I think this is a duplicate of #691, which has a fix in #728 that's pending merge. Please reopen or reply if you disagree.

**Comment by guidovranken** [comment]
Woops, didn't see.
