### ISSUE TITLE
mbedtls_mpi_exp_mod() fails when a^e is smaller than m

### ISSUE THREAD

**Issue by hannob** [ARMmbed/mbedtls#789]
The bignum function mbedtls_mpi_exp_mod() fails if one passes inputs that cause a situation where the modulus doesn't do anything or, in other word, when the result of the exponentiation is smaller than the modulus.

E.g. a simple example would be trying to calculate 2^2 mod 10. This has a well defined result (4), but the function just returns an error. I have pasted an example code below.

In RSA and Diffie Hellman such a situation should never appear with valid inputs. I'm not sure if there are other crypto functions where this has implications. But nevertheless, this is a public function that is documented as part of the API [1], it should produce correct results for all valid inputs.

[1] https://tls.mbed.org/api/bignum_8h.html#a55433a16c951178e2b98a01c6386239e

```
#include "mbedtls/bignum.h"

int main() {
  mbedtls_mpi a, b, m, r;
  int ret;

  mbedtls_mpi_init(&a);
  mbedtls_mpi_init(&b);
  mbedtls_mpi_init(&m);
  mbedtls_mpi_init(&r);

  mbedtls_mpi_read_string(&a, 16, "2");
  mbedtls_mpi_read_string(&b, 16, "2");
  mbedtls_mpi_read_string(&m, 16, "10");

  ret = mbedtls_mpi_exp_mod(&r, &a, &b, &m, 0);

  if (ret != 0)
    printf("mbedtls_mpi_exp_mod returned error %i\n", ret);
}

**Comment by sbutcher-arm** [comment]
Thank you for the bug report! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1206

**Comment by RonEld** [comment]
Hi @hannob This is a [documented restiriction](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/bignum.h#L667) on the input to mpi_exp_mod that the modulus must not be even or negative

**Comment by RonEld** [comment]
I believe this issue has been addressed and answered, therefore closing it.
If you are unhappy with the result, please reopen it.
