### ISSUE TITLE
SHA Hashes Are Incorrect

### ISSUE THREAD

**Issue by chepurko** [ARMmbed/mbedtls#798]
The SHA-1 and SHA-256 hashes at this link  https://tls.mbed.org/download and in the release notes don't match my hash values.

`sha1sum --version
sha1sum (GNU coreutils) 8.25`

My hash is `9fd1f260c504416870aa0753cf58a4e32276c62e  mbedtls-2.4.0-apache.tgz`. All the other versions hashes aren't matching either.

Are the hashes provided by mbed some kind of mbed-only versions? If so then it would seem problematic to verify checksums for your files when you haven't installed the required software yet.

**Comment by pjbakker** [comment]
I think you are hashing the download page for 2.4.0 (which is at https://tls.mbed.org/download/start/mbedtls-2.4.0-apache.tgz) , not the actual tarball (which is at https://tls.mbed.org/download/mbedtls-2.4.0-apache.tgz).

Just downloaded the tarball and ran it through a random online SHA1 generator. Hash is identical.

**Comment by chepurko** [comment]
That'll do it! Thanks.
