### ISSUE TITLE
mbedTLS accepts a certificate whose validity is not in the range of its CA certificate's without any warning

### ISSUE THREAD

**Issue by chenchuAtXidian** [ARMmbed/mbedtls#805]
Summary: As for a certificate, its validity should be in the range of its CA certificate's in logic. For example, if a CA certificate's validity is from Aug 15 10:28:44 2016 GMT to Aug 15 10:28:44 2017 GMT, the validity of a certificate which is issued by this CA should not be from Aug  1 12:12:12 2008 GMT to Nov  3 12:12:12 2018 GMT or from Sep  3 12:12:12 2016 GMT to Nov  3 12:12:12 2018 GMT. mbedTLS should reject such certificates or give warnings in logic, instead of depending on CRL or OCSP.
   
   Versions of mbedTLS: 2.3.0
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  
				mbedtls_cert_app mode='file' filename=3.pem ca_file=ca.pem
				mbedtls_cert_app mode='file' filename=4.pem ca_file=ca.pem
   
   Actual results: OK
   Expected results: mbedTLS should reject such certificates or give some warnings at least.
   
   The attachement contains ca.pem and 3.pem and 4.pem.
   
   Please rename the file "test cases.txt" to "test cases.zip" and extract it.
   
   ca.pem:
	    Not Before: Aug 15 10:28:44 2016 GMT
            Not After : Aug 15 10:28:44 2017 GMT
   
  3.pem:
	    Not Before: Aug  1 12:12:12 2008 GMT
            Not After : Nov  3 12:12:12 2018 GMT
						
  4.pem 
	    Not Before: Sep  3 12:12:12 2016 GMT
            Not After : Nov  3 12:12:12 2018 GMT

[test cases.txt](https://github.com/ARMmbed/mbedtls/files/776567/test.cases.txt)

**Comment by RonEld** [comment]
@chenchuAtXidian Thank you for reporting this issue, please upload test cases.txt again

**Comment by chenchuAtXidian** [comment]
@RonEld The file "test cases.txt" has been uploaded. Thank you!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1220

**Comment by jcowgill** [comment]
Is this actually a bug? Once the CA expires, both `3.pem` and `4.pem` will no longer be regarded as valid anyway. Is this required by any RFC? If not, mbedTLS will probably end up rejecting some certificates which validate everywhere else.

**Comment by chenchuAtXidian** [comment]
@jcowgill A valid CA should not issue certificates whose validity is beyond its date range in logic even when the CA certificate is valid. Is it right for us to accept such certificates without warning?

**Comment by jcowgill** [comment]
A warning would probably be appropriate, but I think rejecting certificates like this would be wrong because what the CA has done is (strictly speaking) valid and does not cause any security issues.

**Comment by chenchuAtXidian** [comment]
@jcowgill I agree that corresponding warnings should be given at least. I am not good at launching attacks using bugs. Therefore it is difficult for me to tell how to use it.

**Comment by NWilson** [comment]
Indeed, not only is it OK, it's desirable to accept leaf certificates with validity which extends beyond the parent certificate's validity - business models may involve a customer buying a 5-year certificate, and the root certificate's validity is also extended every five or ten years, causing some certificates to extend a little beyond the root certificate's validity (for a while). I know it's not common, but that has happened in the past with public CA roots.

The main thing is that the chain is valid only as long as every certificate in the chain is individually valid - which is what the standards require and what mbedTLS implements.

**Comment by mpg** [comment]
@chenchuAtXidian Thanks for your report. However, we couldn't find anything in RFC 5280 that requires or even suggests such a check from validating parties. Additionally, @NWilson provided an argument why such a check might actually be harmful in some real-world cases. We don't think we should be stricter than what the RFC suggests unless there is a security reason for it, which we don't think is the case here.

Therefore I'm closing this a "not a bug". As usual, if you disagree please reopen and quote standards documents supporting your point.
