### ISSUE TITLE
mbedtls_aes_encrypt() and mbedtls_aes_derypt() do no have return values

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#817]
The default software implementation of the AES module can be replaced by an alternative implementation at compile-time by defining the macro `MBEDTLS_AES_ALT` and providing implementations for the AES API functions/data structures.

When the alternative AES implementation makes use of hardware accelerators, it is desirable to check the return status code from the accelerated crypto operations. However, the functions `mbedtls_aes_encrypt()` and `mbedtls_aes_decrypt()` have a `void` return code, making it very difficult to detect errors in these operations. This issue is a proposal to enhance the AES API by adding `int` return values for those functions and deprecating the existing ones.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1229

**Comment by adustm** [comment]
Hello,
I have the same request for mbed_tls_sha1 and mbedtls_sha256 functions. 
Kind regards

**Comment by sbutcher-arm** [comment]
This was fixed in commit 31c5eef. Issue can now be closed.
