### ISSUE TITLE
Test suites not indicating failed tests

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#820]
In the test suites, `stdout` is redirected during execution of each test to keep the output clean, just in case a test wants to output something.

However, if the test fails, the [`test_fail()`](https://github.com/ARMmbed/mbedtls/blob/e709f7c9e07b54542f368297272b0fca36304300/tests/suites/helpers.function#L396) the failure text is output during execution so is also redirected and the test suite isn't indicating a clear test failure.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1233

**Comment by sbutcher-arm** [comment]
Fixed in PR #997, now merged.
