### ISSUE TITLE
X.509 Parse Test Cases Dependent on outdated configurations

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/mbedtls#821]
Some of the test cases in the `test_suite_x509parse` are dependent on configurations which are no longer defaults in the library (such as MD2, MD5), and are only executed if *all* configurations are enabled.

That means if you're compiling only the default configuration you will not be executing some test cases which you should and need to.

Therefore the test cases should be reviewed, and anything that requires an old hash unnecessarily, should be upgraded to SHA256 or similar.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1232

**Comment by hanno-arm** [comment]
#2430 fixes this.

**Comment by Patater** [comment]
#2430 has been merged, so this issue can be considered fixed.
