### ISSUE TITLE
ssl_server2 does not work with Chrome

### ISSUE THREAD

**Issue by hefloryd** [ARMmbed/mbedtls#823]
Using mbedTLS-2.4.0 and Chrome 56.0.2924.87 (on Windows 7), running ssl_server2 works fine with Firefox and IE but Chrome fails with "ERR_SSL_PROTOCOL_ERROR". A Wireshark trace shows an SSL_Alert (Illegal Parameter) being sent from Chrome after the certificate is received. 

Issue #30 seems related. The comments there indicate there was an issue with ECHDE_ECDSA in Chrome but that it should be resolved in later versions?

**Comment by sbutcher-arm** [comment]
I suspect this is unrelated, but we'll look into it. Thanks for raising this issue.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1241

**Comment by 13xforever** [comment]
Looks like I got this bug too, here's a [comment](https://bugs.chromium.org/p/chromium/issues/detail?id=705948#c3) from Chromium devs:

> There's a bug in how the server processes signature algorithms. The signature algorithms list is a pair of hash/algorithm pairs and mbedTLS only looks at the hash half and not the algorithm half. This is incorrect. Notably, Chrome does not advertise the same set of hashes with ECDSA and RSA due to ECDSA having less legacy and generally needing a tighter binding between the algorithm and hash.
> 
> Here's the bug:
> https://github.com/ARMmbed/mbedtls/blob/99000142cba168b410669631a654efc23117952a/library/ssl_srv.c#L207
> 
> Here's the recent Chrome change:
> https://www.chromestatus.com/feature/5725838074970112
> https://groups.google.com/a/chromium.org/d/msg/blink-dev/kWwLfeIQIBM/9chGZ40TCQAJ

**Comment by RafaelBaptista** [comment]
This bug is alive and well and making it impossible for current chrome to connect to mbedtls servers with ECC certificates. 

Basically Chrome is asking that ECDSA server keys be signed with SHA256 or SHA384. mbedtls is ignoring that and signing it with SHA512.

See my question here: https://crypto.stackexchange.com/questions/46726/ecc-certificate-works-with-all-browsers-and-ssl-labs-but-not-chrome

and support post here: https://tls.mbed.org/discussions/crypto-and-ssl/mbedtls-ssl-handshake-failure-with-chrome-and-ecc-certificate

**Comment by RafaelBaptista** [comment]
This is my patch to solve this problem. Index: src/mbedtls/ssl.h

===================================================================
--- src/mbedtls/ssl.h	(revision 6423)
+++ src/mbedtls/ssl.h	(working copy)
@@ -251,6 +251,7 @@
 #define MBEDTLS_SSL_SIG_ANON                 0
 #define MBEDTLS_SSL_SIG_RSA                  1
 #define MBEDTLS_SSL_SIG_ECDSA                3
+#define MBEDTLS_SSL_SIG_MAX                  4

 /*
  * Client Certificate Types
Index: src/mbedtls/ssl_internal.h
===================================================================
--- src/mbedtls/ssl_internal.h	(revision 6423)
+++ src/mbedtls/ssl_internal.h	(working copy)
@@ -165,8 +165,8 @@
     /*
      * Handshake specific crypto variables
      */
-    int sig_alg;                        /*!<  Hash algorithm for signature   */
-    int verify_sig_alg;                 /*!<  Signature algorithm for verify */
+    int sig_alg[MBEDTLS_SSL_SIG_MAX];           /*!<  Hash algorithm for signature - one per signature type */
+    int verify_sig_alg;                         /*!<  Signature algorithm for verify */
 #if defined(MBEDTLS_DHM_C)
     mbedtls_dhm_context dhm_ctx;                /*!<  DHM key exchange        */
 #endif
Index: src/ssl_srv.c
===================================================================
--- src/ssl_srv.c	(revision 6423)
+++ src/ssl_srv.c	(working copy)
@@ -205,27 +205,33 @@
     }

     /*
-     * For now, ignore the SignatureAlgorithm part and rely on offered
-     * ciphersuites only for that part. To be fixed later.
-     *
-     * So, just look at the HashAlgorithm part.
+     *  default is sha1, we could just overwrite it, but we don't want to overwrite
+     *  if that is what is requested first by client. So store none for now...
      */
+    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
+       ssl->handshake->sig_alg[i] = MBEDTLS_SSL_HASH_NONE;
+
+    /*
+     * Get the signature algorithm hash per supported signature algorith
+     * For now in practice this means just RSA and ECDSA
+     */
     for( md_cur = ssl->conf->sig_hashes; *md_cur != MBEDTLS_MD_NONE; md_cur++ ) {
         for( p = buf + 2; p < end; p += 2 ) {
-            if( *md_cur == (int) mbedtls_ssl_md_alg_from_hash( p[0] ) ) {
-                ssl->handshake->sig_alg = p[0];
-                goto have_sig_alg;
+            int sigType = p[1];
+            if ( sigType > MBEDTLS_SSL_SIG_MAX ) continue;
+            if( ( *md_cur == (int) mbedtls_ssl_md_alg_from_hash( p[0] ) ) &&
+                ( ssl->handshake->sig_alg[sigType] == MBEDTLS_SSL_HASH_NONE ) ) {
+                ssl->handshake->sig_alg[sigType] = p[0];
             }
         }
     }

-    /* Some key echanges do not need signatures at all */
-    MBEDTLS_SSL_DEBUG_MSG( 3, ( "no signature_algorithm in common" ) );
-    return( 0 );
+    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
+       if ( ssl->handshake->sig_alg[i] == MBEDTLS_SSL_HASH_NONE )
+          ssl->handshake->sig_alg[i] = MBEDTLS_SSL_HASH_SHA1;

-have_sig_alg:
-    MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello v3, signature_algorithm ext: %d",
-                   ssl->handshake->sig_alg ) );
+    MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello v3, signature_algorithms ext rsa: %d, ecdsa: %d",
+                                ssl->handshake->sig_alg[1], ssl->handshake->sig_alg[3] ) );

     return( 0 );
 }
@@ -2869,8 +2875,11 @@
 #if defined(MBEDTLS_SSL_PROTO_TLS1_2)
         if( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_3 )
         {
-            md_alg = mbedtls_ssl_md_alg_from_hash( ssl->handshake->sig_alg );
+            int sigIdx = (( ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA ) ? MBEDTLS_SSL_SIG_ECDSA : MBEDTLS_SSL_SIG_RSA );
+            md_alg = mbedtls_ssl_md_alg_from_hash( ssl->handshake->sig_alg[sigIdx] );

+            MBEDTLS_SSL_DEBUG_MSG( 3, ( "final selected signature_algorithm: %d", ssl->handshake->sig_alg[sigIdx] ) );
+
             if( md_alg == MBEDTLS_MD_NONE )
             {
                 MBEDTLS_SSL_DEBUG_MSG( 1, ( "should never happen" ) );
@@ -2990,8 +2999,9 @@
 #if defined(MBEDTLS_SSL_PROTO_TLS1_2)
         if( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_3 )
         {
-            *(p++) = ssl->handshake->sig_alg;
-            *(p++) = mbedtls_ssl_sig_from_pk( mbedtls_ssl_own_key( ssl ) );
+            int sig = mbedtls_ssl_sig_from_pk( mbedtls_ssl_own_key( ssl ) );
+            *(p++) = ssl->handshake->sig_alg[sig];
+            *(p++) = sig;

             n += 2;
         }
Index: src/ssl_tls.c
===================================================================
--- src/ssl_tls.c	(revision 6423)
+++ src/ssl_tls.c	(working copy)
@@ -5244,7 +5244,8 @@
 #endif /* MBEDTLS_SSL_PROTO_TLS1_2 */

     handshake->update_checksum = ssl_update_checksum_start;
-    handshake->sig_alg = MBEDTLS_SSL_HASH_SHA1;
+    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
+       handshake->sig_alg[i] = MBEDTLS_SSL_HASH_SHA1;

 #if defined(MBEDTLS_DHM_C)
     mbedtls_dhm_init( &handshake->dhm_ctx );

**Comment by RafaelBaptista** [comment]
Please consider my patch for this problem.

    Index: src/mbedtls/ssl.h
    ===================================================================
    --- src/mbedtls/ssl.h	(revision 6423)
    +++ src/mbedtls/ssl.h	(working copy)
    @@ -251,6 +251,7 @@
     #define MBEDTLS_SSL_SIG_ANON                 0
     #define MBEDTLS_SSL_SIG_RSA                  1
     #define MBEDTLS_SSL_SIG_ECDSA                3
    +#define MBEDTLS_SSL_SIG_MAX                  4
    
     /*
      * Client Certificate Types
    Index: src/mbedtls/ssl_internal.h
    ===================================================================
    --- src/mbedtls/ssl_internal.h	(revision 6423)
    +++ src/mbedtls/ssl_internal.h	(working copy)
    @@ -165,8 +165,8 @@
         /*
          * Handshake specific crypto variables
          */
    -    int sig_alg;                        /*!<  Hash algorithm for signature   */
    -    int verify_sig_alg;                 /*!<  Signature algorithm for verify */
    +    int sig_alg[MBEDTLS_SSL_SIG_MAX];           /*!<  Hash algorithm for signature - one per signature type */
    +    int verify_sig_alg;                         /*!<  Signature algorithm for verify */
     #if defined(MBEDTLS_DHM_C)
         mbedtls_dhm_context dhm_ctx;                /*!<  DHM key exchange        */
     #endif
    Index: src/ssl_srv.c
    ===================================================================
    --- src/ssl_srv.c	(revision 6423)
    +++ src/ssl_srv.c	(working copy)
    @@ -205,27 +205,33 @@
         }
    
         /*
    -     * For now, ignore the SignatureAlgorithm part and rely on offered
    -     * ciphersuites only for that part. To be fixed later.
    -     *
    -     * So, just look at the HashAlgorithm part.
    +     *  default is sha1, we could just overwrite it, but we don't want to overwrite
    +     *  if that is what is requested first by client. So store none for now...
          */
    +    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
    +       ssl->handshake->sig_alg[i] = MBEDTLS_SSL_HASH_NONE;
    +
    +    /*
    +     * Get the signature algorithm hash per supported signature algorith
    +     * For now in practice this means just RSA and ECDSA
    +     */
         for( md_cur = ssl->conf->sig_hashes; *md_cur != MBEDTLS_MD_NONE; md_cur++ ) {
             for( p = buf + 2; p < end; p += 2 ) {
    -            if( *md_cur == (int) mbedtls_ssl_md_alg_from_hash( p[0] ) ) {
    -                ssl->handshake->sig_alg = p[0];
    -                goto have_sig_alg;
    +            int sigType = p[1];
    +            if ( sigType > MBEDTLS_SSL_SIG_MAX ) continue;
    +            if( ( *md_cur == (int) mbedtls_ssl_md_alg_from_hash( p[0] ) ) &&
    +                ( ssl->handshake->sig_alg[sigType] == MBEDTLS_SSL_HASH_NONE ) ) {
    +                ssl->handshake->sig_alg[sigType] = p[0];
                 }
             }
         }
    
    -    /* Some key echanges do not need signatures at all */
    -    MBEDTLS_SSL_DEBUG_MSG( 3, ( "no signature_algorithm in common" ) );
    -    return( 0 );
    +    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
    +       if ( ssl->handshake->sig_alg[i] == MBEDTLS_SSL_HASH_NONE )
    +          ssl->handshake->sig_alg[i] = MBEDTLS_SSL_HASH_SHA1;
    
    -have_sig_alg:
    -    MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello v3, signature_algorithm ext: %d",
    -                   ssl->handshake->sig_alg ) );
    +    MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello v3, signature_algorithms ext rsa: %d, ecdsa: %d",
    +                                ssl->handshake->sig_alg[1], ssl->handshake->sig_alg[3] ) );
    
         return( 0 );
     }
    @@ -2869,8 +2875,11 @@
     #if defined(MBEDTLS_SSL_PROTO_TLS1_2)
             if( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_3 )
             {
    -            md_alg = mbedtls_ssl_md_alg_from_hash( ssl->handshake->sig_alg );
    +            int sigIdx = (( ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA ) ? MBEDTLS_SSL_SIG_ECDSA : MBEDTLS_SSL_SIG_RSA );
    +            md_alg = mbedtls_ssl_md_alg_from_hash( ssl->handshake->sig_alg[sigIdx] );
    
    +            MBEDTLS_SSL_DEBUG_MSG( 3, ( "final selected signature_algorithm: %d", ssl->handshake->sig_alg[sigIdx] ) );
    +
                 if( md_alg == MBEDTLS_MD_NONE )
                 {
                     MBEDTLS_SSL_DEBUG_MSG( 1, ( "should never happen" ) );
    @@ -2990,8 +2999,9 @@
     #if defined(MBEDTLS_SSL_PROTO_TLS1_2)
             if( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_3 )
             {
    -            *(p++) = ssl->handshake->sig_alg;
    -            *(p++) = mbedtls_ssl_sig_from_pk( mbedtls_ssl_own_key( ssl ) );
    +            int sig = mbedtls_ssl_sig_from_pk( mbedtls_ssl_own_key( ssl ) );
    +            *(p++) = ssl->handshake->sig_alg[sig];
    +            *(p++) = sig;
    
                 n += 2;
             }
    Index: src/ssl_tls.c
    ===================================================================
    --- src/ssl_tls.c	(revision 6423)
    +++ src/ssl_tls.c	(working copy)
    @@ -5244,7 +5244,8 @@
     #endif /* MBEDTLS_SSL_PROTO_TLS1_2 */
    
         handshake->update_checksum = ssl_update_checksum_start;
    -    handshake->sig_alg = MBEDTLS_SSL_HASH_SHA1;
    +    for ( int i = 0; i < MBEDTLS_SSL_SIG_MAX; i++ )
    +       handshake->sig_alg[i] = MBEDTLS_SSL_HASH_SHA1;
    
     #if defined(MBEDTLS_DHM_C)
         mbedtls_dhm_init( &handshake->dhm_ctx );

**Comment by 13xforever** [comment]
Seeing how other issues are being incorporated, I wouldn't expect it to be fixed this year. mbedTLS moves _very_ slow and I start to question why people even using it, if in the end everyone has its own custom build with their own patches anyway...

It is very frustrating when serious compatibility issues are being ignored for months with no progress communication whatsoever.

**Comment by sbutcher-arm** [comment]
We recognise this as a significant issue and plan to fix it in the next quarterly release of mbed TLS. Unfortunately, the bug landed too close to our release of [mbed TLS 2.4.2](https://tls.mbed.org/tech-updates/releases/mbedtls-2.4.2-2.1.7-and-1.3.19-released) for us to be able to fix it in that release, similar to bug #810 which is also pretty significant.

So these issues are certainly not ignored, although maybe we could communicate our plans better.

**Comment by RafaelBaptista** [comment]
I appreciate the work the team does. I like the feature set of mbedtls. It has been a little frustrating with some development issues not getting good feedback in a timely manner. Part of this is that the mbedtls community is very small - so there just aren't a lot of people on the forums. 

It was definitely frustrating to spend several days trying to figure out what was wrong before finding that this very basic bug was known. A word on the support forum would have saved me a lot of time.
