### ISSUE TITLE
mis-used variable in x509_crt_verify_top()

### ISSUE THREAD

**Issue by luocm** [ARMmbed/mbedtls#825]
it should be  child->subject_raw.len but not  child->issuer_raw.len in the following code piece:

       if( child->subject_raw.len == trust_ca->subject_raw.len &&
            memcmp( child->subject_raw.p, trust_ca->subject_raw.p,
                            child->issuer_raw.len ) == 0 )
        {
            check_path_cnt--;
        }

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1678

**Comment by hanno-arm** [comment]
Hi @luocm, 

thanks alot for reporting this :+1:, and apologies for the late response. We are working on the issue.

Kind regards,
Hanno
