### ISSUE TITLE
x509_crt_verify_top() dosen't work as expected if top of the chain is the same as the trusted CA

### ISSUE THREAD

**Issue by luocm** [ARMmbed/mbedtls#827]
If top of the chain ("child") is the same as the trusted CA, the following piece of code will just continue, and doesn't get chance to validate cert "child"

if( x509_crt_check_parent( child, trust_ca, 1, path_cnt == 0 ) != 0 )
            continue;

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1676

**Comment by RonEld** [comment]
Hi @luocm I don't think I follow you.
It is not a valid use case where the the child is the same as the trusted CA. The trusted CA is the CA trusted root certificate, while the certificate chain is sent by the peer for verification, which means the top of the chain should be generated by a CA, which is verify against the root CA certificate,

Please elaborate what you mean, as it is not so clear to me
