### ISSUE TITLE
yotta\data\example-benchmark\main.cpp POLARSSL_CONFIG_FILE not renamed

### ISSUE THREAD

**Issue by rmstein** [ARMmbed/mbedtls#832]
The file yotta\data\example-benchmark\main.cpp hasn't had it's defines rename completed and still has a check for POLARSSL_CONFIG_FILE.  The check needs to be done against the rename MBEDTLS_CONFIG_FILE.  This causes a multiple redefine error in VS2015.  

mbed TLS 2.2.1 released 2016-01-05
VS2015 on Windows 7

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1364

**Comment by sbutcher-arm** [comment]
Yotta is no longer actively maintained, and whilst we still continue to test it on the maintained branches, we consider new bugs on a case by case basis, and old bugs which are minor and haven't yet been fixed won't be, so this issue won't be fixed and can be closed.

cc: @RonEld, @ndevillard
