### ISSUE TITLE
Memory leak in mbedtls_ssl_set_hostname

### ISSUE THREAD

**Issue by jethrogb** [ARMmbed/mbedtls#836]
[mbedtls_ssl_set_hostname](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L5978) does not check if `ssl->hostname` is already set, therefore leaking memory if called twice.

Incidentally, there is no way to unset `ssl->hostname` (e.g. doesn't get cleared with `mbedtls_ssl_session_reset`). `mbedtls_x509_crt_verify` behaves differently if set vs. unset.

**Comment by sbutcher-arm** [comment]
Thanks for raising this. We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1240

**Comment by sbutcher-arm** [comment]
Reviewed and merged fix for this issue into branches `development`, `mbedtls-2.1` and `mbedtls-1.3`. Issue can now be closed.
