### ISSUE TITLE
ssl_server.c connection reset after handshake

### ISSUE THREAD

**Issue by efancier** [ARMmbed/mbedtls#838]
Use the example code ssl_server.c from 2.4.0 release, compile and run in VS2010, use what ever IE,edge or Chrome, the connect got resetted after handshake, after several trial,  the browser start to exchange data with ssl_server.

Following is the log from ssl_server.c

```
  _. Loading the server cert. and key... ok
  . Bind on https://localhost:4433/ ... ok
  . Seeding the random number generator... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok:0
  < Read from client: mbedtls_ssl_read returned -0x0
  > Write to client: 150 bytes written

HTTP/1.0 200 OK
Content-Type: text/html

<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384</p>

  . Closing the connection... failed
  ! mbedtls_ssl_close_notify returned -78

Last error was: -78 - NET - Sending information through the socket failed

  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok:0
  < Read from client: mbedtls_ssl_read returned -0x0
  > Write to client: 150 bytes written

HTTP/1.0 200 OK
Content-Type: text/html

<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384</p>

  . Closing the connection... failed
  ! mbedtls_ssl_close_notify returned -78

Last error was: -78 - NET - Sending information through the socket failed

  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok:0
  < Read from client: mbedtls_ssl_read returned -0x0
  > Write to client: 150 bytes written

HTTP/1.0 200 OK
Content-Type: text/html

<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384</p>

  . Closing the connection... failed
  ! mbedtls_ssl_close_notify returned -78

Last error was: -78 - NET - Sending information through the socket failed

  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok:0
  < Read from client: 451 bytes read

GET / HTTP/1.1
Host: localhost:4433
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cookie: Webstorm-8a941dfe=ebce63e0-a4b3-42a5-86e6-c20586ff5f5e; locale=en

  > Write to client: 150 bytes written_
```

**Comment by sbutcher-arm** [comment]
Can you say what version of Windows you were using?

**Comment by efancier** [comment]
Hello Simon,
Thanks so much for your email. Attached is my OS and browser version information.
Best Regards!


-Robin Li






At 2017-03-11 17:08:11, "Simon Butcher" <notifications@github.com> wrote:


Can you say what version of Windows you were using?

**Comment by efancier** [comment]
Hi Simon,
I was sending the information back via pictures, I noticed a moment ago git hub does not take picture, so I am sending again in text:
OS information: Windows 10 Pro, version 1607,64 bit , build 14393.693, CPU: i7 6500U, 
Browser information:  Google Chrome, Version 55.0.2883.87m


Best Regards!


-Robin Li






在 2017-03-11 17:08:11，"Simon Butcher" <notifications@github.com> 写道：


Can you say what version of Windows you were using?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1344

**Comment by RonEld** [comment]
Hi @efancier 
I believe the error you are receiving is because your server is sending the test certificate issued by the PolarSSL test CA. This CA is probably ont part of your trust CA chain list, and your browser denies it, causing the socket to be closed. I believe that you are receiving in your browser a message that your connection is not secure .
I suggest you either replace your server certificate with a trusted one (preferred), or add the polar SSL test CA root certificate(in `certs.c`) .

**Comment by efancier** [comment]
Hi Roneld,
I was thinking the same while even I add the PolarSSL test CA to browser trusted ca list, I still got the same result.
I did more wireshark and found the browser actually send 2 connection request in parallel,  and randomly pick up one connection for data communication after handshake,  I am modifying my code to support multi-thread so I can monitor what happened in detail. so far it most likely not an issue from mbedtls.
Best Regards!


在 2017-04-30 19:25:08，"RonEld" <notifications@github.com> 写道：


Hi @efancier
I believe the error you are receiving is because your server is sending the test certificate issued by the PolarSSL test CA. This CA is probably ont part of your trust CA chain list, and your browser denies it, causing the socket to be closed. I believe that you are receiving in your browser a message that your connection is not secure .
I suggest you either replace your server certificate with a trusted one (preferred), or add the polar SSL test CA root certificate(in certs.c) .

**Comment by RonEld** [comment]
>so far it most likely not an issue from mbedtls.

Since this issue is not an Mbed TLS issue, it is being closed.
If you think this was wrongfully closed, please reopen
