### ISSUE TITLE
Problem with errno and fcntl

### ISSUE THREAD

**Issue by nkolban** [ARMmbed/mbedtls#845]
If we look at the following code, we see that it checks errno ... however I think there is a problem ...

https://github.com/ARMmbed/mbedtls/blob/master/library/net_sockets.c#L278

What we want to check is errno's value when the function is called.  However, what I think we are checking is the errno value from the last fcntl is the same function.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1324

**Comment by RonEld** [comment]
duplicate of #733
