### ISSUE TITLE
New test in 2.4.2 pk_rsa_alt segfaults on 64-bit ILP32 systems

### ISSUE THREAD

**Issue by jcowgill** [ARMmbed/mbedtls#849]
The test added to `pk_rsa_alt` in 511f83db0712fbcb8b3a5b173ae074ae035a4748 segfaults on 64-bit ILP32 systems (eg: x86 x32, mips n32, etc). These systems have a 64-bit native word size, but store pointers in 32-bits.

Here `MBEDTLS_HAVE_INT64` is defined due to the native word size but `size_t` is still only 32-bits. This means that the check added in 2.4.2 here: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.4.2/library/pk_wrap.c#L419 does not return because all `size_t` values will fit in an `unsigned int`, and then the test segfaults because `sig_len` is `NULL`.

```
RSA_ALT consistency ............................................... 
Program received signal SIGSEGV, Segmentation fault.
0x0041e790 in rsa_alt_sign_wrap (ctx=0x65c6f0, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, p_rng=0x0)
    at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk_wrap.c:423
423	    *sig_len = rsa_alt->key_len_func( rsa_alt->key );
(gdb) bt
#0  0x0041e790 in rsa_alt_sign_wrap (ctx=0x65c6f0, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, 
    p_rng=0x0) at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk_wrap.c:423
#1  0x0041dcab in mbedtls_pk_sign (ctx=0xffffc230, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, 
    p_rng=0x0) at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk.c:269
#2  0x00408a3d in test_suite_pk_rsa_alt () at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/tests/suites/test_suite_pk.function:496
#3  0x0040a078 in dispatch_test (cnt=1, params=0xffffc4e0) at main_test.function:424
#4  0x0040aad6 in main (argc=1, argv=0xffffda54) at main_test.function:420
```

**Comment by sbutcher-arm** [comment]
Hi @jcowgill - is this a blocker for adoption into Debian? I'm guessing you can't take the security fixes until we've addressed this issue.

My anticipation was we'd refactor this and allow better 32/64 bit configuration when we fix [708].

**Comment by jcowgill** [comment]
It isn't, because it only affects x32 which is not a release arch.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1300
