### ISSUE TITLE
Incorrect print messages in benchmark example

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#850]
The benchmark example at `programs/test/benchmark.c` displays some statistics for a number of crypto features. However, the printed messages from the statement at [line 129](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c#L129) say that the performance is in `Kb/s`, while the code actually calculates `KB/s`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1287
