### ISSUE TITLE
ec prase key failed

### ISSUE THREAD

**Issue by linbeithree** [ARMmbed/mbedtls#851]
- when I use ecc,execute the command below,generate an ec private key,then use `key_app` read the key,it always failed.
``` 
cd programs/pkey/
./gen_key type=ec 
./key_app mode=private filename=keyfile.key 
```
```
  . Loading the private key ... ok
  . Key information    ...
Q(X): 019CD965D68B718F0A30C52DD2123DD7ABE0B275560CE0A7701C056F8FBEAAC91ECECEC0BD73AD8619D1A90BE05FCD1F4B1096CAF4E386C5C251C70C0EE142DE08BA
Q(Y): 01BAC4CEF97D29D4802C82A359FC2B0166FB4F0269551AD74F48604AAF7F12AD1F04FFAF23A82504B771BC596C96AD4F05192CA7100A9ACCB00499DECF19B9363820
Q(Z): 01
D   : 014D5AE98DA578AF8ED67E5096544E8B31CB38B3B42FAC4D3A3A2F7D366E30F5511E406E921095840775B7B28360CA0202BAC0A7D66D7E938C2AE4CC095EA2D9EDB6
  !  Last error was: 
```

It shows the same error when I use key from openssl.

**Comment by RonEld** [comment]
@linbeithree As you can see, the key information is printed correct.  
The print of `!  Last error was:` is wrongfully printed by the `key_app` sample application, but the key itself is parsed correct.  I have created an issue to track the wrong print case in https://github.com/ARMmbed/mbedtls/issues/852

**Comment by linbeithree** [comment]
@RonEld hi,thanks.I wanna use another feature,but it always error too.
I wanna use ec for encrypt and decrypt string  like rsa.
```
./gen_key type=ec
openssl ec -in keyfile.key -pubout -out ecpubkey.pem
./pk_encrypt ecpubkey.pem hellombedtls
```
this will show error 
```
! mbedtls_pk_encrypt returned -0x3f00
!  Last error was: PK - Type mismatch, eg attempt to encrypt with an ECDSA key
```
could you help me about this?

**Comment by RonEld** [comment]
Hi @linbeithree ,
as menitoned in the [forum](https://tls.mbed.org/discussions/generic/how-to-use-ecc-for-encrypt-and-decrypt-data-like-aes-and-rsa), mbed TLS does not support ECC cipher schemes, as it is not a requirement by TLS protocol.
This enhancement is refernced in #854

**Comment by linbeithree** [comment]
Hi，@RonEld 
thanks for your feedback.Maybe this will be a  feature request.
