### ISSUE TITLE
key_app sample application suggests there is an error, even if no error

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#852]
when using the sample application `key_app`, even on success, it will print:
~~~
!  Last error was: 
~~~

I suggest this line will be printed only if there was an error

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1323

**Comment by sbutcher-arm** [comment]
@RonEld - Wasn't this found by a user? Do you know who? We need to credit them if so.

**Comment by RonEld** [comment]
@sbutcher-arm It was raised as part of the discussion of #851
