### ISSUE TITLE
relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object

### ISSUE THREAD

**Issue by Cstream** [ARMmbed/mbedtls#853]
/usr/bin/ld: //usr/local/lib/libmbedtls.a(ssl_tls.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libmbedtls.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:522: recipe for target 'libbctoolbox.la' failed
make[2]: *** [libbctoolbox.la] Error 1
make[2]: Leaving directory '/home/c/下载/linphone-3.11.1/bctoolbox/src'
Makefile:495: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/c/下载/linphone-3.11.1/bctoolbox'
Makefile:402: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sbutcher-arm** [comment]
Hi @Cstream, 

I can see that the build is failing to build a shared object because the generated code isn't position independent, but can you say how you were building mbed TLS? It's not obvious from the bug.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1343

**Comment by RonEld** [comment]
Hi @Cstream ,
As you can see from the error you should compile your code with the `CFLAGs=-fPIC`.
for example:

> make shared CFLAGS=-fPIC

**Comment by RonEld** [comment]
I believe this question was answered, therefore closing it
If you are not happy with the answer, please reopen
