### ISSUE TITLE
ec pk_encrypt data failed

### ISSUE THREAD

**Issue by linbeithree** [ARMmbed/mbedtls#854]
## I wanna use ec to encrypt and decrypt data like below, the key prase is right,but encrypt data is error.

```
./pk_encrypt ecpub.pem hello

  . Seeding the random number generator...
  . Reading public key from 'ecpub.pem'
  . Generating the encrypted value failed
  ! mbedtls_pk_encrypt returned -0x3f00
  !  Last error was: PK - Type mismatch, eg attempt to encrypt with an ECDSA key
```

so,did I do something wrong?I use this `pk_encrypt` by rsa like below is ok.

` ./pk_encrypt rsa_public_key_2048.pem helloworld`
```
  . Seeding the random number generator...
  . Reading public key from 'rsa_public_key_2048.pem'
  . Generating the encrypted value
  . Done (created "result-enc.txt")
```
` ./pk_decrypt rsa_private_key_2048.pem `
```
  . Seeding the random number generator...
  . Reading private key from 'rsa_private_key_2048.pem'
  . Decrypting the encrypted data
  . OK

The decrypted result is: 'helloworld'
```

I wonder ,whether something is wrong in ec?

**Comment by linbeithree** [comment]
@sbutcher-arm hi，could you help me about this？

**Comment by RonEld** [comment]
Hi @linbeithree ,
as menitoned in the [forum](https://tls.mbed.org/discussions/generic/how-to-use-ecc-for-encrypt-and-decrypt-data-like-aes-and-rsa) and in #851 , mbed TLS does not support ECC cipher schemes, as it is not a requirement by TLS protocol.
I am marking this issue as enhancement

**Comment by linbeithree** [comment]
Hi, @RonEld ,

Thanks for your feedback,I will use ECC for sign and verify,maybe it will support cipher schemes.

**Comment by holmescn** [comment]
I found there is a function named "psa_asymmetric_encrypt/decrypt". Is it usable for ECC encryption/decryption? No example here.

**Comment by gilles-peskine-arm** [comment]
`psa_asymmetric_{encrypt,decrypt}` only supports RSA-PKCS1v15 and RSA-OAEP. It does not support any ECC-based encryption method.

You can implement [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme) on top of ECDH, which is implemented in `mbedtls_ecdh_xxx` and `psa_raw_key_agreement`.
