### ISSUE TITLE
Program crashes while writing data to disconnected socket

### ISSUE THREAD

**Issue by PravallikaKG** [ARMmbed/mbedtls#870]
My Client application is getting crashed when i write data to invalid Socket, i.,e, disconnected socket.
Is there a way to verify whether socket is valid or not(i.e., connected or disconnected) before writing or reading to/from mbedTls socket?

Which data member in 'mbedtls_ssl_context' structure can be used to know whether socket is connected or disconnected?

Or is there any API which gives state of mbedtls Socket?

**Comment by RonEld** [comment]
Hi @PravallikaKG these checks should be done in the `bio` callback that you are supplying in the `mbedtls_ssl_set_bio` API. These callbacks should receive the socket descriptor, and either check the socket before you try to read\write to it, if possible on your system, or check the error code of the system's end\recv functions.

**Comment by PravallikaKG** [comment]
Thank you RonEld

**Comment by RonEld** [comment]
I believe this question was answered, therefore closing it
If you are not happy with the answer, please reopen
