### ISSUE TITLE
warning variables used before they are set in ssl_parse_server_key_exchange()

### ISSUE THREAD

**Issue by gkerrien38** [ARMmbed/mbedtls#875]
In ssl_cli.c, function ssl_parse_server_key_exchange(), the IAR compiler for ARM outputs a warning about 2 variables (p and end) being used before they are set:

 ((void) p);
((void) end);

it happens twice at lines 2207-2208 and 2226-2227.

it happens if MBEDTLS_KEY_EXCHANGE_RSA_ENABLED and MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED are defined.

These lines can be either removed, or they can be moved after 'p' and 'end' variables are set (lines 2260-2261).

**Comment by sbutcher-arm** [comment]
Thanks for raising the issue! We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1340

**Comment by gilles-peskine-arm** [comment]
Thanks for letting us know! I believe that PR #988 resolves the issue, and it has been merged into the development branch, therefore I am closing this issue.
