### ISSUE TITLE
mbedtls_pk_parse_keyfile() cannot parse encrypted 4096-bit RSA private key

### ISSUE THREAD

**Issue by Mishamax** [ARMmbed/mbedtls#878]
I generated RSA private key and certificate using the following command:

`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem`

mbedtls_pk_parse_keyfile() function cannot parse this private key and returns error code -0x3E80 (MBEDTLS_ERR_PK_BAD_INPUT_DATA).

Apparently this happens because the buffer in function pk_parse_key_pkcs8_encrypted_der (pkparse.c:944) is too small. After increasing it to 4096 bytes the issue was resolved.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1345

**Comment by gilles-peskine-arm** [comment]
Merged #1062 so closing this ticket. Thanks for reporting the bug!
