### ISSUE TITLE
compilation flags gets omitted if set in make command\environment

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#896]
https://github.com/ARMmbed/mbedtls/blob/development/library/Makefile contains the following lines:
```
CFLAGS	?= -O2
WARNING_CFLAGS ?=  -Wall -W -Wdeclaration-after-statement
```
This means, that if `CFLAGS` is exported as environment variable, as a parameter to make command, `-O2` compilation flag will be omitted.
Same for `-Wall -W -Wdeclaration-after-statement` on `WARNING_CFLAGS`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1391

**Comment by Patater** [comment]
This is by design. `CFLAGS` is overridable, and you need to specify all the options you want including `-O2` if you want that, or without if you don't (and you might not want it).
