### ISSUE TITLE
wrong log for number of ciphersuites in ssl_write_client_hello

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#918]
in `ssl_write_client_hello`, the following log is incorrect: `client hello, got %d ciphersuites`  
The reason is because it is located after optionally adding renegotiation info and fallback SCSV.  
This may increase `n` by 1 or two, logging a larger number of ciphersuites sent

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1390
