### ISSUE TITLE
Memory saving options

### ISSUE THREAD

**Issue by antonio-nino-diaz-arm** [ARMmbed/mbedtls#929]
I'm trying to save memory (here https://github.com/ARM-software/arm-trusted-firmware). So far, I've done the following two things:

1. Enable the option `MBEDTLS_SHA256_SMALLER`.

2. mbed TLS uses `snprintf`, which makes our code grow a lot because we only use that family of functions for mbed TLS. There's the option `MBEDTLS_PLATFORM_SNPRINTF_ALT` that allows me to use `mbedtls_platform_set_snprintf` to use instead a small implementation that only supports the format `'%d'`, which is the only one that we need for mbed TLS to work in our project.

I've checked the documentation but I can't find any other obvious way to save memory without touching the code of the library itself. Is there anything I've missed?

This is our config file: https://github.com/ARM-software/arm-trusted-firmware/blob/82cb2c1ad9897473743f08437d0a3995bed561b9/include/drivers/auth/mbedtls/mbedtls_config.h

CC: @sandrine-bailleux-arm

**Comment by RonEld** [comment]
Hi @antonio-nino-diaz-arm the following [article](https://tls.mbed.org/kb/how-to/reduce-mbedtls-memory-and-storage-footprint) that may help you. In addition, you can undefine some features that you don't need in your project

**Comment by sbutcher-arm** [comment]
@antonio-nino-diaz-arm - I've spoken to Dan before about contributing your `snprintf` implementation to the library. We'd be very keen to accept it as a contribution. Could you email me the source? And would it be okay for us to take it and distribute it under GPL and Apache?

**Comment by antonio-nino-diaz-arm** [comment]
@sbutcher-arm Yes, sure, you can use it in any way you want, and I'm fine with licensing it under the GPL and Apache licenses. I'll send it to you in a minute.

**Comment by antonio-nino-diaz-arm** [comment]
The code is now in the master branch our repository: https://github.com/ARM-software/arm-trusted-firmware/pull/949

**Comment by RonEld** [comment]
The code has been riased in PR #1463, therefore closing this question
