### ISSUE TITLE
Test: support negative conditions in depends_on

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#931]
In our test cases (in a `.function` or `.data` file), we can write e.g. `depends_on:MBEDTLS_SHA1_C:MBEDTLS_RSA_C` to indicate that a test case must only run if all of the specified preprocessor macros are defined in `config.h` (or elsewhere).

It would be nice to also support negative conditions, e.g. `depends_on:FOO:!BAR` would only run if `FOO` was defined and `BAR` was not defined. We've actually attempted to do it once (https://github.com/ARMmbed/mbedtls/blob/development/tests/suites/test_suite_entropy.data#L56) but that test case currently never runs.

**Comment by RonEld** [comment]
nternal ref: IOTSSL-144

**Comment by hanno-arm** [comment]
@gilles-peskine-arm Does this issue have a Jira ticket? (If not, we don't need to create one, the issue is treated as part of #1025 belonging to IOTSSL-1580).

**Comment by gilles-peskine-arm** [comment]
Implemented in #1025 which is now merged in `development`.
