### ISSUE TITLE
Inconsistencies in checking CRLs

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#933]
The function `x509_verify_crt_crl()` can sometimes set the flags `MBEDTLS_X509_BADCERT_BAD_KEY` while it should set `MBEDTLS_X509_BADCRL_BAD_KEY` (CRL vs CERT).

Also, looping is inconsistent as some errors break out of the loop and some don't, with no apparent logic. Behaviour should be unified and a rationale (for either breaking or not) added in the comments.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1421
