### ISSUE TITLE
Configuration issue with using only MONTGOMERY and no SHORT_WEIERSTRASS

### ISSUE THREAD

**Issue by signpainter** [ARMmbed/mbedtls#941]
[mbedtls_config.txt](https://github.com/ARMmbed/mbedtls/files/1035992/mbedtls_config.txt)

I was creating my own config.h. You can find it attached. When I build my application I get

    In function `mbedtls_ecp_muladd': 
    ./libs/mbedtls-2.4.2/library/ecp.c:1739: undefined reference to `ecp_add_mixed'
    ./libs/mbedtls-2.4.2/library/ecp.c:1740: undefined reference to `ecp_normalize_jac'

Both `ecp_add_mixed` and `ecp_normalize_jac` are only defined if `ECP_SHORTWEIERSTRASS` is defined. `mbedtls_ecp_muladd` itself returns with an error code if the group type is not equal to `ECP_TYPE_SHORT_WEIERSTRASS`. 

I therefore assume that the whole function can be put into the 
 
    #if defined(ECP_SHORTWEIERSTRASS)
    ...
    #endif

block beginning in line 1431 of ecp.c (and probably also `mbedtls_ecp_mul_shortcuts`. Am I correct? Or is there a reason why this is like it is?

**Comment by RonEld** [comment]
Hi @signpainter , thank you for pointing us to this issue. In fact, I have tried using your config, and I have failed in compilation a lot sooner, in the check_config for `MBEDTLS_ECP_C`.
We will look into this

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1418

**Comment by signpainter** [comment]
Hi @RonEld, thanks for your quick response. The first issue also occured for me but this was easily been solved by adding X25519 to the possible Curves for ECP beginning in line 106 of check_config.h.

**Comment by RonEld** [comment]
Hi @signpainter , yes , but it still need to be tracked and mentioned

**Comment by RonEld** [comment]
Hi @signpainter  After some further investigation, there is areason why the behaviour is like this.
At the moment, Mbed TLS supports montgomery curve  (25519) only as primitive, and not as a cipher suite.
At the moment, the way to do ECDH with curve 25519 is as in the [example](https://github.com/ARMmbed/mbedtls/blob/development/programs/pkey/ecdh_curve25519.c)  
Since this is a missing feature, I am changing this to enhancement

**Comment by RonEld** [comment]
I correct my previous comment, there shouldn't be a compilation error in this case, I got mixed up with a different issue related to curve 25519
