### ISSUE TITLE
Can the AWS IOT Broker be installed on local server for testing AWS IOT Client

### ISSUE THREAD

**Issue by PravallikaKG** [ARMmbed/mbedtls#952]
I have coded my IOT client device using AWS IOT Client SDK in Embedded C wherein the SDK is free. Later i came to know that AWS IOT Broker which is in AMAZON cloud is not a free service, there is limit for certain amount of messages per month. 
I am looking for a solution is it possible  to get the AWS IOT Broker installer for free, so that i can host the AWS IOT Broker on  my local server and use it? so i need not to pay for AWS IOT Cloud services. Does we have this option or we have to compulsory use the AMAZON AWS IOT Cloud services only(which is not free)?

**Comment by sbutcher-arm** [comment]
I'm afraid as AWS question, there's not much the mbed TLS team can say about this, although hopefully someone in the community can.

**Comment by RonEld** [comment]
We believe this question is not in the Mbed TLS area, therefore we are closing it.
We recommenced you ask your question in the Amazon support forum and other public forums.
Best of luck
