### ISSUE TITLE
inconsistency in the `crypt_and_hash` sample application

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#961]
when I decrypt a file, it writes: "File content not a multiple of the block size (16)." , for AES-CTR as well (which is not mandatory for CTR)
When I encrypt , we don't do the check for the filesize%block_size
and the error will\should be returned by the cipher itself, if it isn't a multiple of block size.
I think we should be consistent, either check the file size for both encryption and decryption(and for CTR mode not check the size), or not check at all, and rely on the cipher to return the proper error.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1445
