### ISSUE TITLE
 Upgrade from MAC-then-encrypt to encrypt-then-MAC mechanism is not negotiated correctly

### ISSUE THREAD

**Issue by borkarab** [ARMmbed/mbedtls#962]
Currently re-handshake is failing at handshake step **SSL_HANDSHAKE_WRAPUP** where the renegotiated session  **encrypt-then-MAC** using the mechanism of the current session which is **MAC-then-encrypt** and then the message that follows was continue with MAC-then-encrypt.

NOTE: *This isue is present only if renegotiation is supported*

    if( ssl->session )
    {
      #if defined(MBEDTLS_SSL_ENCRYPT_THEN_MAC)
        /* RFC 7366 3.1: keep the EtM state */
           ssl->session_negotiate->encrypt_then_mac = ssl->session->encrypt_then_mac;
      #endif

        mbedtls_ssl_session_free( ssl->session );
        mbedtls_free( ssl->session );
    }

To Keep EtM state, this code Need to check whether the last session is using EtM?
ie. if (ssl->session->encrypt_then_mac == 0x01)

RFC 7366 :- section 3.1. Rehandshake Issues
If an upgrade from MAC-then-encrypt to encrypt-then-MAC is negotiated as per the second line in the table below, then the change will take place in the first message that follows the Change Cipher Spec (CCS) message. In other words, all messages up to and including the CCS will use MAC-then-encrypt, and then **the message that follows will continue with encrypt-then-MAC**.

Table 1: Encrypt-then-MAC with Renegotiation 
===============================

 Current Session | Renegotiated Session | Action to take |
------------------|-------------------------|--------------------------
| MAC-then-encrypt | MAC-then-encrypt | No change |
| **MAC-then-encrypt** | **Encrypt-then-MAC** | **Upgrade to Encrypt-then-MAC** |
| Encrypt-then-MAC | MAC-then-encrypt | Error |
| Encrypt-then-MAC | Encrypt-then-MAC | No change |

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1444

**Comment by borkarab** [comment]
shall I expect this will get fix in next Version?

**Comment by jcowgill** [comment]
If I understand correctly, your bug is that mbedtls doesn't correctly deny the change of encrypt-to-mac state from the other party?

I think the table is a red-herring. It seems to me that RFC 7366 3.1 explicitly states that implementations SHOULD NOT allow renegotiation which changes the encrypt-then-mac state. The table is only used when implementations chose to ignore that advice. Or are you asking for mbedtls to allow this?

**Comment by borkarab** [comment]
I am talking about following case :

Current Session | Renegotiated Session | Action to take |
----------------|---------------------|--------------------------|
MAC-then-encrypt | Encrypt-then-MAC | Upgrade to Encrypt-then-MAC |

If you see the code below line which copies the current session mechanism into negotiated session.
**ssl->session_negotiate->encrypt_then_mac = ssl->session->encrypt_then_mac;**
ie. If my current session is MtE and negotiated session is EtM then also it copies MtE into negotiated session and following message comes with MtE.

I think confusion is due to its name 
ssl->session->encrypt_then_mac = **0x00** means **MAC-then-encrypt (or EtM is disable)**
ssl->session->encrypt_then_mac = **0x01** means **Encrypt-then-MAC (or EtM is enable)**

Your understanding is correct implementations SHOULD NOT allow renegotiation which changes the encrypt-then-mac state. This means if my current session is EtM and try to renegotiated with MtE is not allowed it should maintain the state EtM.

**To Keep EtM state, this code Need to check whether the last session is using EtM?**
**ie. if (ssl->session->encrypt_then_mac == 0x01)**

**Comment by jcowgill** [comment]
I'm still not sure I understand your point. The code you mentioned looks correct to me - if we want to keep the old EtM state then copying it over from the previous session should be OK? Why do we need an `if` here (and what is going to go inside this `if`)? Are you trying to argue that MtE -> EtM upgrades should be allowed?

**Comment by borkarab** [comment]
MtE -> EtM upgrades should be allowed?
Yes RFC 7366 also talks the same for more flexibility, as mentioned in the table.

**Comment by jcowgill** [comment]
OK I understand now.

My point is that RFC 7366 also states that implementations should not allow upgrades (but does not completely prohibit it). The table is for implementations which for some reason need to allow this - most people should be ignoring the table completely. I think you would need to provide some very good reasons for adding this - presumably there were good reasons for advising against implementing it when RFC 7366 was written.

**Comment by borkarab** [comment]
As RFC does not prohibit it completely,  we as a Client need to verify all the scenarios.
SSL as a library it needs to provide support to test all the scenario mentioned in RFC. Request is to provide the support for flexible behavior .

**Comment by RonEld** [comment]
Closing this issue as not reproducible.
If you think this issue was wrongfully closed, please reopen
