### ISSUE TITLE
Server key exchange is taking lot of time for ECC

### ISSUE THREAD

**Issue by vikasshah1991** [ARMmbed/mbedtls#970]
Hello,
I am running DTLS server on low footprint micro-controller platform. From DTLS client when we do handshake with ECDHE-ECDSA cipher suite then server key exchange message is taking long time ( around 60s ) which is triggering timeout for client and it retransmit the last chunk of handshake messages. This takes bit  longer to finish handshake and seeing lot of retransmission because of this.

I have already enabled below flag in config.h file.
/* Significant speed benefit at the expense of some ROM */
#define MBEDTLS_ECP_NIST_OPTIM

Any suggestion on how to speed up the server key exchange packet framing?.

Thanks

**Comment by RonEld** [comment]
Hi @vikasshah1991 I suggest you look [here](https://tls.mbed.org/kb/cryptography/elliptic-curve-performance-nist-vs-brainpool) for some information on the ECC performance. Check what curves you need, in the trade off of security strength and performance

**Comment by vikasshah1991** [comment]
Hi,
Thank you for your response. I see below line for ECDHE-SEC256r1 curve.
ECDHE-secp256r1          :     334 handshake/s   ( what does it mean? )

And results are measured with 2 GHz i7 processor. I am trying to run mbedtls on embedded platform. so is there any possibility to reduce the handshake time?

**Comment by RonEld** [comment]
Hi @vikasshah1991 I apologize for my bad explanation.
The article I referenced earlier was meant for you to see differences in the curves, for you to choose the relevant ECC for your device. You will get different results, as the processor is different.
The output of the [benchmark application](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c) (which you could execute on your device for better results) is checking how much handshake operations are done on the device, **without** the networking delay.
I suggest you run the benchmark application, so you could:
1) choose relevant curve
2) check if bottleneck could be networking rather then cryptography

**Comment by RonEld** [comment]
I believe your question was answered, therefore closing it.
If you are not happy with the answer, please reopen
