### ISSUE TITLE
most selftest function declarations are not surrounded by `MBEDTLS_SELF_TEST`

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#971]
most of the selftest function declarations are not surrounded by ``#if defined(MBEDTLS_SELF_TEST)` check.
Note: The .c files function implementations are surrounded
sha512.h
aes.h
ctr_drbg.h
ripemd160.h
arc4.h
dhm.h
md5.h
base64.h
xtea.h
x509.h
camelilia.h
pkcs5.h
md2
md4
gcm.h
sha256.h
bignum.h
sha1.h
rsa.h
des.h

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1470

**Comment by RonEld** [comment]
This is a subset of #660

**Comment by sbutcher-arm** [comment]
PR #975 has been merged. This issue can be closed.
