### ISSUE TITLE
Useless (preprocessor) code in writing supported_curves extension

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#973]
The following preprocessor directive makes no sense: https://github.com/ARMmbed/mbedtls/blob/45d269555b3cb9785a75e804fe74413baffd4f0a/library/ssl_cli.c#L265 as this extension is only written in `ECP_C` is defined anyway.

This is probably a remnant from when `curves_list` was not always available. The code should be simplified now by removing parts that will always be preprocessed away, and the corresponding preprocessor conditionals.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1472

**Comment by hanno-arm** [comment]
@RonEld Why is this being closed?
