### ISSUE TITLE
2.5 broke the ABI

### ISSUE THREAD

**Issue by jcowgill** [ARMmbed/mbedtls#978]
While packaging 2.5.1 for Debian, I noticed the ABI has been broken in a few small places. These functions / variables have been removed:

##### libmbedcrypto
* `mbedtls_aes_decrypt`
* `mbedtls_aes_encrypt`
##### libmbedtls
* `mbedtls_ssl_ciphersuite_uses_ec`
* `mbedtls_ssl_ciphersuite_uses_psk`
##### libmbedx509
* `mbedtls_test_ca_crt_rsa_len`
* `mbedtls_test_cli_crt_rsa_len`

I see that for the first 4, you have added `static inline` stubs to the headers to maintain API compatability. Unfortunately doing this does not maintain ABI compatability - you need to put the stubs in the libraries for that. The last 2 still exist in `include/mbedtls/certs.h` and anyone trying to use them will presumably get a linker error.

You should either (with a strong preference for the first option):
* Add the symbols back into the library.
* Increment the `SOVERSION` on all 3 libraries to force everyone to rebuild.

In the meantime I will add some stubs to the Debian package to maintain ABI compatability.

**Comment by RonEld** [comment]
Hi @jcowgill Thanks for raising this issue
Note that `mbedtls_aes_decrypt` and `mbedtls_aes_encrypt`  have been deprecated as well.
as for `mbedtls_test_ca_crt_rsa_len` and `mbedtls_test_cli_crt_rsa_len`, we have missed that unfortunately. I believe the same issue is for `mbedtls_test_ca_crt_rsa[]` and `mbedtls_test_cli_crt_rsa[]`

**Comment by jcowgill** [comment]
> I believe the same issue is for `mbedtls_test_ca_crt_rsa[]` and `mbedtls_test_cli_crt_rsa[]`

Yes you are right, I must have missed those.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1484

**Comment by sbutcher-arm** [comment]
Hi @jcowgill,

Thanks for picking up on this! We had already spotted some API/ABI breaks in the library which had been reverted, but sadly we appear to have missed these.

Can I ask how you spotted the mistakes that we missed so quickly? I'd like to include and automate in our test system such checking to avoid this happening again.

Concerning the changes - I think we need to revert the following in our next release - 2.5.2:

##### libmbedcrypto
* `mbedtls_aes_decrypt`
* `mbedtls_aes_encrypt`
##### libmbedtls
* `mbedtls_ssl_ciphersuite_uses_ec`
* `mbedtls_ssl_ciphersuite_uses_psk`

The symbols removed from `certs.c` I'm less convinced by though, as they're very much intended for testing, and arguably shouldn't be used unless for testing and debugging of the library.

From your position as Debian package maintainer, does that satisfy you?

**Comment by jcowgill** [comment]
Hi,

> Can I ask how you spotted the mistakes that we missed so quickly? I'd like to include and automate in our test system such checking to avoid this happening again.

There is an optional Debian packaging feature I use in mbedTLS called "symbols files". Their main purpose is for calculating suitable dependencies for other packages using mbedTLS, but as an extra feature, the Debian build tools will fail the build if they find that any symbols listed in the symbols files are not actually present in the built libraries.

The symbols files I have for mbedTLS are here: https://sources.debian.net/src/mbedtls/unstable/debian/
The gory details are in [Debian policy](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-updates) and [dpkg-gensymbols(1)](https://manpages.debian.org/stretch/dpkg-dev/dpkg-gensymbols.1.en.html).

> Concerning the changes - I think we need to revert the following in our next release - 2.5.2:

Thanks!

> The symbols removed from certs.c I'm less convinced by though, as they're very much intended for testing, and arguably shouldn't be used unless for testing and debugging of the library.
>
> From your position as Debian package maintainer, does that satisfy you?

I think I can live with that. However, if these symbols are for internal use only, then they shouldn't have been exported from the library in the first place. I should have probably disabled `MBEDTLS_CERTS_C` (as well as other Linux distros)?

**Comment by sbutcher-arm** [comment]
Fixed by PR #986 now merged.
