### ISSUE TITLE
CCM documentation error on the supported key size

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#979]
The [CCM documentation for the supported key size](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ccm.h#L56) claims that the cipher should be a 128-bit block cipher, however, according to the [benchmark application](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c#L461), it is clear that other key size are supported as well

**Comment by mpg** [comment]
The 128-bit in the CCM documentation is about the size of the block, not the size of the key. Perhaps this could be reworded to make it clearer?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1488

**Comment by RonEld** [comment]
Hi @mpg, Actually, I misread it. I read it as "128-bit cipher block", while it states "128-bit block cipher".
I don't think a change is mandatory

**Comment by RonEld** [comment]
This was a misreading of the comment, therefore, closing this issue
