### ISSUE TITLE
cannot build shared library

### ISSUE THREAD

**Issue by Yuzeyang** [ARMmbed/mbedtls#983]
CMake Error at library/CMakeLists.txt:151 (install):
 install TARGETS given no LIBRARY DESTINATION for shared library target
"mbedtls"

**Comment by RonEld** [comment]
Hi @Yuzeyang when you create an issue, it is important you mention full way of reproducing the issue.
Please verify you run the `cmake` command from the root directoy, as mentioned in the [Readme](https://github.com/ARMmbed/mbedtls#cmake) file:
~~~
cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On .
~~~

**Comment by Yuzeyang** [comment]
@RonEld  sorry, i forgot to set it as a question

`➜  libmbedtls git:(feature/port-mbedtls) ✗ cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On .
-- The C compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Perl: /usr/bin/perl (found version "5.18.2")
No such file: /include/mbedtls/config.h
CMake Error at library/CMakeLists.txt:151 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "mbedtls".


-- Configuring incomplete, errors occurred!
See also "/Users/yzy/Documents/mercury-client-native/libmbedtls/CMakeFiles/CMakeOutput.log".`

I run the cmake command from the root directoy, still have the same error

**Comment by RonEld** [comment]
Hi @Yuzeyang I cannot reproduce this issue, please check your environment.
I am concerned by the line:
~~~
No such file: /include/mbedtls/config.h
~~~
I believe that it means that `CMAKE_SOURCE_DIR` is not correct.
You should try in a new shell environment as well

**Comment by Yuzeyang** [comment]
thanks for remind me, i download the new code, and run the cmake command, and have no error

 but it have not any .project file?

**Comment by RonEld** [comment]
Hi @Yuzeyang *`.project`* is not part of the mbed TLS code. It is a file generated by your IDE (e.g. eclipse )

**Comment by Yuzeyang** [comment]
@RonEld thanks for your help!
